### ISSUE TITLE
oidc-client http timeout

### ISSUE THREAD

**Issue by astanciu** [auth0/nextjs-auth0#1]
The oidc-client uses a default http timeout of 2500ms. It would be useful to increase this default or allow configuring this via the settings passed in.

**Comment by sandrinodimattia** [comment]
Thanks, makes total sense! Added as part of the initial release: https://github.com/auth0/nextjs-auth0/commit/36608af56a9e09f67f6c02074364272b23158b79

**Comment by Muhriddin6261** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nexts@0.1.0 dev: `next dev`
npm ERR! Exit status 1
