### ISSUE TITLE
Using client.endSessionUrl instead of hardcoded url for logout

### ISSUE THREAD

**Issue by civerazdaM** [auth0/nextjs-auth0#100]
### Describe the problem you'd like to have solved

I see that logout handler has hardcoded url, and not the one that could be generated from the client.endSessionUrl. If that would be the case, then it could be used for various providers. I am wondering would you have something like that in mind, or maybe you would prefer that it stays coupled to this specific logout endpoint of auth0 implementation? 

### Describe the ideal solution

Here is a quick draft of what could be achieved.
createLogoutUrl could be modified to make use of client.endSessionUrl, or to be replaced by it.
```
function createLogoutUrl(settings: IAuth0Settings, client: Client, idToken: string): string {
  return client.endSessionUrl({
    id_token_hint: idToken,
    post_logout_redirect_uri: encodeURIComponent(settings.postLogoutRedirectUri)
  });
}
```
In handlers/logout.ts params that this modified function would need could be declared :
```
    const client = await clientProvider();
    const tokenCache = tokenCacheHandler(clientProvider, sessionStore)(req, res);
    const { idToken } = await tokenCache.getIdToken();
    if (!idToken) {
      throw new Error('No id token available to logout user');
    }
```

In tokens/session-token-cache.ts could have additional function for returning idToken, e.g.
```
  async getIdToken(): Promise<IdTokenResponse> {
    const session = await this.store.read(this.req);
    if (!session) {
      throw new IdTokenError('invalid_session', 'The user does not have a valid session.');
    }
    if (!session.idToken) {
      throw new IdTokenError('invalid_session', 'The user does not have a valid id token.');
    }
    return {
      idToken: session.idToken
    };
  }
```

**Comment by sandrinodimattia** [comment]
Added as part of [v0.12.0](https://github.com/auth0/nextjs-auth0/releases/tag/v0.12.0)
