### ISSUE TITLE
Sign-in user with webAuth.login() triggers state error when redirecting to callback URL

### ISSUE THREAD

**Issue by Will956** [auth0/nextjs-auth0#1016]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hey 👋 

For some reason, we have to implement a custom sign-up page in our web app. We are using the Management API to create the user and once it's done we would like to automatically sign-in the user.

In order to perform that, we use `auth0-js` with `webAuth.login()`:
```js
const auth0Client = new auth0.WebAuth({
  domain: 'https://domain.eu.auth0.com',
  clientID: 'client_id',
});

(...)

<button
    onClick={() => {
      auth0Client.login(
        {
          realm: 'application-name',
          email: 'email@email.fr', // gathered from sign-up form
          password: 'password', // gathered from sign-up form
          responseType: 'code',
          redirectUri: 'http://localhost:3000/api/auth/callback'
        },
        (err, authResult) => {
          console.log(err, authResult);
        }
      );
    }}
  >
  Sign-in
</button>

```
_`<button>` in the example is just in order to try, the login function will live in an onClick handler._

When clicking on sign-in, it uses the `/co/authenticate` then goes to `/authorize` and then to my callback `/api/auth/callback`. But as you can imagine, since it doesn't go to `/api/auth/login`, the state cookie is not there and so we have a `MissingStateCookieError`.

By looking at others issues, this is exactly the same as https://github.com/auth0/nextjs-auth0/issues/647 _(except we are not implementing Google login)_. So I fixed that by implementing the suggestion:
```js
export default handleAuth({
  login: handleLogin({
    authorizationParams: {
      audience: 'https://domain/api',
      scope: 'openid profile email offline_access',
    },
  }),
  async callback(req, res) {
    try {
      await handleCallback(req, res);
    } catch (error) {
      // if MissingStateCookieError
      res.redirect(302, '/api/auth/login');
    }
  },
});
```

And it makes the trick, it's just working 👌 But I guess this is not an ideal way of doing that.

Are there any others better ways to implement this flow that I missed?

Thanks 🙏 

### Reproduction

Reproduction available above 👆 

### SDK version

2.0.1

### Next.js version

13.1.1

### Node.js version

18.12.1

**Comment by adamjmcgrath** [comment]
Hey @Will956 - thanks for raising this

Your suggestion looks ok, but I would just go for something like:

```js
auth0Client.login({
   redirectUri: 'http://localhost:3000/api/auth/login'
```

Then you don't need to customise the callback handler
