### ISSUE TITLE
Is it safe to use accessToken in props?

### ISSUE THREAD

**Issue by deegansiwicki** [auth0/nextjs-auth0#1020]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am using Apollo client with nextjs, and am wondering if it is ok to get the access token in server side props and then pass it into the page for mutations that require authorization? 

### Reproduction

.

### SDK version

2.1.0

### Next.js version

13.1.1

### Node.js version

18.13.0

**Comment by adamjmcgrath** [comment]
Hi @deegansiwicki - thanks for raising this, there are a few security consideration to take into account when accessing the access token on the frontend. They're a good list of them here https://www.ietf.org/archive/id/draft-bertocci-oauth2-tmi-bff-01.html#section-6 - if you're happy with those then there's no reason why you couldn't pass the access token to the frontend using server side props

**Comment by deegansiwicki** [comment]
> Hi @deegansiwicki - thanks for raising this, there are a few security consideration to take into account when accessing the access token on the frontend. They're a good list of them here https://www.ietf.org/archive/id/draft-bertocci-oauth2-tmi-bff-01.html#section-6 - if you're happy with those then there's no reason why you couldn't pass the access token to the frontend using server side props

Ok, thank you so much!
