### ISSUE TITLE
Generate Id of session based on session data

### ISSUE THREAD

**Issue by PSoltes** [auth0/nextjs-auth0#1024]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'd like to generate session id based on session data about user, eg. email, name, internal id, to be able to find users session in external session store. Of course taking in account that this id will be included in cookies.

### Describe the ideal solution

Pass `session` to genId function.

### Additional context

Only opening this issue to add PR to it.

**Comment by PSoltes** [comment]
@adamjmcgrath wasn't allow to push into branch in this repo, here is fork with just code changes (no docs, no test) https://github.com/PSoltes/nextjs-auth0/tree/feat/passSessionToGenId

**Comment by adamjmcgrath** [comment]
lgtm, thanks @PSoltes 👍 

Feel free to raise a PR from that fork once you have updated the tests (just need to pop something in [here](https://github.com/auth0/nextjs-auth0/blob/main/tests/stateful-session.test.ts) and [here](https://github.com/auth0/nextjs-auth0/blob/main/tests/auth0-session/session/stateful-session.test.ts))

Also, check [this step](https://github.com/auth0/nextjs-auth0/blob/main/tests/global-setup.ts#L8) when running the tests locally

**Comment by PSoltes** [comment]
https://github.com/auth0/nextjs-auth0/pull/1158
