### ISSUE TITLE
Typescript question: getSession return type does not seem to conform to docs example

### ISSUE THREAD

**Issue by GriffinSauce** [auth0/nextjs-auth0#103]
The `getSession` function has a return type `Promise<ISession | null | undefined>`

In the [readme ](https://github.com/auth0/nextjs-auth0/blob/master/README.md#user-profile) the suggested use is as follows:

```.js
const { user } = await auth0.getSession(req);
```

This fails in TypeScript because you might be destructuring `null` or `undefined`.

So my question is: is that example overly optimistic for assuming session will always be returned or is the return type incorrect? (or am I too inexperienced with TS and missing something... 😅)

**Comment by sandrinodimattia** [comment]
Thanks for calling it out, docs were updated 👍

**Comment by GriffinSauce** [comment]
Great!

Is my interpretation correct that it might be undefined (on the client) in getInitialProps but will always return a session in API functions?
