### ISSUE TITLE
Links to API reference in `README.md` return 404

### ISSUE THREAD

**Issue by linardsblk** [auth0/nextjs-auth0#1031]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

All of the links to API reference in `README.md` return 404. 

For example - https://auth0.github.io/nextjs-auth0/modules/config.html

Seems like a different url works but I am not sure if the content is the same as previously linked https://auth0.github.io/nextjs-auth0/index.html

### Reproduction

1. Just click any link in README.md

### SDK version

2.2.0

### Next.js version

-

### Node.js version

-

**Comment by adamjmcgrath** [comment]
Thanks for raising this @linardsblk - looks like our recent typedoc update broke the links - will investigate.

Please us the homepage for now and we'll fix https://auth0.github.io/nextjs-auth0/
