### ISSUE TITLE
Expose AccessTokenErrorCode (and any other relevant enums) also from nextjs-auth0/client package

### ISSUE THREAD

**Issue by rlaucik** [auth0/nextjs-auth0#1033]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

In our Next app, we use `getAccessToken` method to enrich calls on our GraphQL server with user access token, which is then passed to provide accesses to the underlying services. In case of an error thrown by the `getAccessToken` method, we pass the caught error message in the GraphQL response body. Since we use SPA architecture, we do the handling of these errors on the frontend side of Next codebase: E.g. redirecting to login screen in case of e.g. expired token, or showing an error message and logging the error in case of unexpected errors like "insufficient scope". 
As we tried to import `AccessTokenErrorCode` enum to handle these errors safely and prevent unexpected changes in the future (since error code values were changed in nextjs-auth0 v2.0), we get the `Module not found: Can't resolve 'v8'` error on app build, mentioned e.g. in this issue https://github.com/auth0/nextjs-auth0/issues/983 
Seems like this is due to importing code from the server package, instead of `nextjs-auth0/client`. However, having access to error enums is a valid case also for client-side code, especially when e.g. passing errors further via an API.

### Describe the ideal solution

Expose AccessTokenErrorCode (and any other relevant enums) also from nextjs-auth0/client package.

### Alternatives and current workarounds

Copying/hardcoding error enums into own codebase, which defeats the purpose of using library enums directly, to not need to watch these changes manually on each package update.

**Comment by adamjmcgrath** [comment]
Hi @rlaucik - thanks for raising this

These errors are thrown by code that runs on the server, to be caught by server side code. We provide no API on the frontend for these errors, so wont be exporting them from the client package.

However, if you really want to import them into your client side code, you should be able to import the types only, for example `import type { AccessTokenErrorCode } from '@nextjs-auth0'`

**Comment by rlaucik** [comment]
Thanks for the reply! Actually importing just a type is an idea I originally ignored, since enum is not just a type. But revisiting that idea, I came up with solution like this:
```
import type { AccessTokenErrorCode } from '@auth0/nextjs-auth0';

export type Auth0AccesTokenErrorCode = `${AccessTokenErrorCode}`;

export const ACCESS_TOKEN_HANDLED_ERROR_CODES: Auth0AccesTokenErrorCode[] = [
  'ERR_EXPIRED_ACCESS_TOKEN',
  'ERR_MISSING_ACCESS_TOKEN',
  'ERR_MISSING_REFRESH_TOKEN',
  'ERR_MISSING_SESSION',
];```

Not perfect, but does the job of TS rejecting to compile in case the error codes would be changed on your side. I'd still prefer being able to simply import enums in the client-side code, but if that is somehow against your principles, I completely understand.
Thank you!

**Comment by adamjmcgrath** [comment]
Thanks for sharing your your solution @rlaucik!
