### ISSUE TITLE
useUser Hook reporting error

### ISSUE THREAD

**Issue by collinsrs** [auth0/nextjs-auth0#1035]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Ever since today (1/25), I have received errors anywhere I have called the `useUser` hook in my applications. They still deploy perfectly fine, but now I am unable to retrieve user context information. Specifically, `user.name` is returning `undefined`

This is the error that is highlighted when I hover over the useUser hook: `'useUser' cannot be used as a value because it was exported using 'export type'.ts(1362)
client.d.ts(1, 1): 'useUser' was exported here.`

### Reproduction

1. import {useUser} Hook
2. Declare it as a const (i.e.) `const {user} = useUser();`

### SDK version

2.2.0

### Next.js version

13.1.2

### Node.js version

16.13.0

**Comment by adamjmcgrath** [comment]
Hi @collinsrs - thanks for raising this

Seems to be working for me - can you share some more code, including how you are importing `useUser`?

**Comment by byzyk** [comment]
I have the same error after upgrading from the beta release, with every export from the SDK like `useUser` or `withMiddlewareAuthRequired`. Importing them as follows:

```
import { withMiddlewareAuthRequired } from '@auth0/nextjs-auth0/edge';
import { useUser } from '@auth0/nextjs-auth0/client';
```

Everything works fine for me, but the annoying TS error is there for some reason. Let me know if you need me to share anything else or assist with debugging here.

**Comment by adamjmcgrath** [comment]
Hi @byzyk - thanks for sharing the code sample

I just created a TypeScript Next app with `create-next-app` and added the latest version of this SDK (2.2.0) and don't have any problem importing `withMiddlewareAuthRequired` or `useUser` (repo: https://github.com/adamjmcgrath/ts-next-test).
I've tried running `build` and `dev` and they both work without any errors or warnings.

Could you share an example repo that demonstrates the issue?

**Comment by collinsrs** [comment]
Hi, @adamjmcgrath - thanks for reaching out. I am receiving this error whenever I call the `useUser` hook, or even when rendering `UserProvider` in `_app.tsx`.

Code sample for where I am calling `useUser`:
```
import { useUser } from "@auth0/nextjs-auth0/client";
import { useQuery } from "@apollo/client";
import { MyTags } from "graphql/queries";

export default function Component() {
    const {user} = useUser();
    const {data, loading, error} = useQuery(MyTags, { 
            variables: {
                name: user.name
            }
        }
    );
 // returning component below
}
```
`useUser` returns the error `'useUser' cannot be used as a value because it was exported using 'export type'.`, but it still "works" in the essence that I can render `user.name` in text. The only issue I have is when I try and run my GraphQL query, passing in the variable `user.name`, the query does not run correctly, as `user.name` is passed into it as `undefined`. 


Below is my `_app.tsx` file, showing the same error with `UserProvider`, but with zero issues:
```
import type { AppProps } from 'next/app';
import { ThemeProvider } from 'next-themes';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { ApolloProvider } from '@apollo/client';
import apolloClient from 'apollo-client';


export default function App({ Component, pageProps }: AppProps) {
  return (
    <UserProvider>
      <ApolloProvider client={apolloClient}>
        <Component {...pageProps} />
        </MantineProvider>
      </ApolloProvider>
    </UserProvider>
  );
}
```

Returning `'UserProvider' cannot be used as a value because it was exported using 'export type'.ts(1362)
client.d.ts(1, 1): 'UserProvider' was exported here.`

Any help would be appreciated! Let me know if you need me to share any more code.

**Comment by adamjmcgrath** [comment]
Hi @collinsrs - thanks for sharing those code samples

I'm not seeing the same issue in my example app, either [importing `UserProvider` in _app.tsx](https://github.com/adamjmcgrath/ts-next-test/blob/main/pages/_app.tsx#L3) or [importing useUser](https://github.com/adamjmcgrath/ts-next-test/blob/main/pages/index.tsx#L5)

Could you share an example repo that demonstrates the issue?

**Comment by selcukcihan** [comment]
I have the same issue, it works fine but I'm getting this linter error:

https://github.com/selcukcihan/tweeted-about/blob/4662b55aee89ecab4136d0aa4bd91b49f7982068/pages/index.tsx#L17

![Screenshot 2023-01-27 at 12 54 26](https://user-images.githubusercontent.com/7043904/215057969-2e98437f-0313-42d1-ac2e-2c2d7213c3b9.png)

**Comment by adamjmcgrath** [comment]
Thanks for sharing your repo @selcukcihan - I've checked it out and am not able to repro the issue. No lint errors and the project builds fine - will continue to investigate.

**Comment by ewanharris** [comment]
We've determined this to be caused by a change in the TypeScript 5.0.0 beta, specifically the new support for [`export type *`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#support-for-export-type) that's used in the `client.d.ts`, `edge.d.ts`, and `testing.d.ts` files in this project.

Given that this seems to only be flagged in the editor it might be down to something like the [nightly TypeScript extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next), editing the files as in #1037 should fix this for you until we release a fix

**Comment by adamjmcgrath** [comment]
Shipped in https://github.com/auth0/nextjs-auth0/releases/tag/v2.2.1

**Comment by selcukcihan** [comment]
> Shipped in https://github.com/auth0/nextjs-auth0/releases/tag/v2.2.1

Just upgraded and the error is gone, thank you very much 🙏
