### ISSUE TITLE
Email Verification Workflow

### ISSUE THREAD

**Issue by bnd5k** [auth0/nextjs-auth0#104]
### Describe the problem you'd like to have solved 

Would it be possible to create a profile but not receive a session cookie for that profile?  I would like to require email verification, ala [ https://auth0.com/rules/email-verified]( https://auth0.com/rules/email-verified).  The documentation mentions `Lock` and `auth0.js`, but I don't see any equivalent in `nextjs-auth0`.

### Describe the ideal solution

I would like to be able to create a profile and add a parameter to the request.  e.g. 
```
{
  loginAfterSignup: false 
}
```

## Alternatives and current work-arounds

One alternative would just be to log out the user once Auth0 redirects back to the app.  That seems unideal since it involves creating Auth0 resources that we don't need (e.g. session cookie).

**Comment by sandrinodimattia** [comment]
I documented an example here: https://github.com/auth0/nextjs-auth0/wiki/Examples

Let me know if this helps.

**Comment by bnd5k** [comment]
This helps a lot!  Thank you.  It's great knowing that we have so much control over state from within our app.  

Thanks for your work on this library. We're very happy with it. :)
