### ISSUE TITLE
withPageAuthRequired return type weakened between 2.1.0 and 2.2.1

### ISSUE THREAD

**Issue by jrr** [auth0/nextjs-auth0#1043]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm using the return type of `getServerSideProps()` to define the input props of my Next.js pages, [as described in next.js' documentation](https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#getserversideprops-with-typescript). This works nicely with **@auth0/nextjs-auth0 2.1.0**:

<img width="845" alt="2 1 0-return-type" src="https://user-images.githubusercontent.com/164652/216104448-ce8d9b2f-6e1b-406d-b5d9-815dec9dc2ae.png">

When updating the library to **2.2.1**, though, the returned Props type loosens to `[key: string]: any;`:

<img width="848" alt="2 2 1-return-type" src="https://user-images.githubusercontent.com/164652/216104603-88343548-48ea-4359-ab0a-4727a441a792.png">

I suspect this came from the change to `with-page-auth-required.ts` in https://github.com/auth0/nextjs-auth0/pull/1017

@adamjmcgrath do you remember why that change was needed? (related to typedoc?)

### Reproduction

Put this in a Next.js project with @auth0/nextjs-auth0 2.1.0:

```ts
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import { InferGetServerSidePropsType } from "next";

export const getServerSideProps = withPageAuthRequired({
  getServerSideProps: async ({ query, req, res }) => {
    if ((query.foo = "bar")) {
      return { notFound: true };
    }
    return { props: { hello: "world" } };
  },
});

export type Props = InferGetServerSidePropsType<typeof getServerSideProps>;

```

Observe the props type from the screenshot above. Update the library to 2.2.1 and see the type change.

### SDK version

2.2.1

### Next.js version

13.1.6

### Node.js version

v18.13.0

**Comment by adamjmcgrath** [comment]
Hi @jrr - thanks for raising this

> @adamjmcgrath do you remember why that change was needed? (related to typedoc?)

Updating typedoc pulled in a new minor of typescript - which then caused the following compilation error

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/1299658/216343438-50527132-5734-4810-aa6b-b5bdc7c9993e.png">

So I changed `P = any` to `P extends { [key: string]: any } = { [key: string]: any }` to match https://github.com/vercel/next.js/blob/v13.1.5/packages/next/types/index.d.ts#L194

Will investigate why that seems to have broken your example

**Comment by adamjmcgrath** [comment]
Hi @jrr - I can't repro your issue using next@13.1.6, auth0-next@2.2.1, node@18 and typescript@4.9.5 see https://github.com/auth0/nextjs-auth0/compare/ts-infer-test

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/1299658/216373124-a93837a0-6371-42db-8705-46b1a6ed39bd.png">

What version of typescript are you using?

**Comment by jrr** [comment]
Typescript 4.9.5!

Here's a small repro based on an empty Next.js project, containing a statement that compiles under 2.1.0 but produces a type error on 2.2.1:

https://github.com/jrr/auth0-repro

Here's what I'm seeing:
```
> ./node_modules/.bin/tsc --version
Version 4.9.5

> ./node_modules/.bin/next --version
Next.js v13.1.6

> node --version
v18.13.0

> npm why @auth0/nextjs-auth0
@auth0/nextjs-auth0@2.2.1 dev
node_modules/@auth0/nextjs-auth0
  dev @auth0/nextjs-auth0@"2.2.1" from the root project

> ./node_modules/.bin/tsc
src/pages/repro.tsx:21:9 - error TS2741: Property 'hello' is missing in type '{ [key: string]: any; } & { user: Claims; }' but required in type 'ActualProps'.

21   const x: ActualProps = input;
           ~

  src/pages/repro.tsx:17:3
    17   hello: string;
         ~~~~~
    'hello' is declared here.


Found 1 error in src/pages/repro.tsx:21
```

**Comment by adamjmcgrath** [comment]
Thanks for sharing the repro @jrr - will take a look

**Comment by adamjmcgrath** [comment]
Done some investigation @jrr - am a bit stumped at the moment.

Interestingly, it seems to work if you don't have the branch that returns `{ notFound: true }`

<img width="762" alt="image" src="https://user-images.githubusercontent.com/1299658/217533361-0a766775-e4ad-42c4-bee3-371688b6df50.png">

I also notice that https://github.com/gladly-team/next-firebase-auth#typescript requires you to specify the generic argument, suggesting that inferring it from the code wont work. This seems to work fine, so you may have to use that as a workaround:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/1299658/217534657-174f4317-1a38-4759-854f-7263910d0f61.png">

Will leave this open for a bit in case you or anyone else has any ideas

**Comment by jrr** [comment]
It looks like the TypeScript error began in 4.8 with [some new strictness around unconstrained type parameters](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-8.html#unconstrained-generics-no-longer-assignable-to-).

On a hunch, I tried [removing auth0 entirely](https://github.com/jrr/auth0-repro/commit/eddad5332a9a6866a6e7ff49211fb23a11490d2f), and found that same issue occurs with Next's getServerSideProps even when you're not wrapping it. So `nextjs-auth0` is absolved :)

This is a problem between Nextjs and Typescript, and until now `nextjs-auth0` was sheltering me from it.

The solution is to supply the type parameter explicitly, like you found.

Thanks!

**Comment by adamjmcgrath** [comment]
Thanks for investigating @jrr!
