### ISSUE TITLE
Checking logout in another tab.

### ISSUE THREAD

**Issue by RafaelStudartDiPiero** [auth0/nextjs-auth0#1044]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have an application that uses an wrapper to return every page with withPageAuthRequired(), so to access any page, there is the need to login.
If I open my application in multiple tabs and then logout in one of them, the rest of tabs continue showing up the pages until they are refreshed.
I expected that , after logging out in one tab, the rest of the tabs also stopped showing their contents until the user logins again.
There is a way to check if a user is logged in? The useUser (my first idea) hook only seems to update after a refresh.
I saw some related issues in the github, but none of the solutions worked. 

### Reproduction

1. Create an App and use withPageAuthRequired() to wrap multiple routes.
2. Open your application in multiple tabs.
3. Logout in one tab.
4. Check the others and see they still respond until a refresh.

### SDK version

2.2.1

### Next.js version

12.2.5

### Node.js version

12.22.9

**Comment by adamjmcgrath** [comment]
Hi @RafaelStudartDiPiero - thanks for raising this

> There is a way to check if a user is logged in? 

You can use `checkSession` like so:

```js
const { checkSession } = useUser();

await checkSession();
```

We don't provide any mechanism to sync the front end login state across tabs or window, you would need to do that yourself wither by polling, or hooking onto an browser event like `visibilitychange`

**Comment by RafaelStudartDiPiero** [comment]
Thanks, that solves the issue!
