### ISSUE TITLE
Access "access token" from client side for getting user roles and permissions

### ISSUE THREAD

**Issue by ahkhanjani** [auth0/nextjs-auth0#1046]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Unfortunately despite all the searching I've done for quite some time now, getting roles and permissions into the ID token is a real hell while it's right there in the access token. That is if there is something really obvious that I'm missing. The option of adding them to the ID token should really be part of the main thing honestly. There are many buttons we would want to hide from an unauthorized user.

### Describe the ideal solution

An async hook like "get client-side access token" would be appreciated.

**Comment by adamjmcgrath** [comment]
Hi @ahkhanjani - thanks for raising this

Access Tokens are designed to be read by the resource (the external API) not by the application. So you should not attempt to read them on the SDK, they are solely for use by an external api (that you specify when setting an audience config) - See https://auth0.com/blog/id-token-access-token-what-is-the-difference/#What-Is-an-Access-Token-NOT-Suitable-For for more info

You should therefore use the ID Token - our recommended way to add roles to an ID Token is using actions, more info here https://github.com/auth0/node-oauth2-jwt-bearer

**Comment by ahkhanjani** [comment]
Adding roles is certainly possible but permissions is something I couldn't find a solution for. It's really inconvenient to make an API request. Why not just add it to the ID token as an option?

**Comment by adamjmcgrath** [comment]
For adding permissions see https://community.auth0.com/t/how-to-add-roles-and-permissions-to-the-id-token-using-actions/84506#h-12-permissions-4

> Why not just add it to the ID token as an option?

It's not up to this SDK what gets added to an ID Token, it's up to the Authorization Server. If you want to provide feedback to Auth0 about this - I recommend you use https://community.auth0.com/c/feedback/95

**Comment by adamjmcgrath** [comment]
Closing as I think https://github.com/auth0/nextjs-auth0/issues/1046#issuecomment-1418960094 answers your question
