### ISSUE TITLE
Support for Access Token Authentication

### ISSUE THREAD

**Issue by Wolfleader101** [auth0/nextjs-auth0#1049]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would like to be able to use nextjs api routes from my mobile app, which uses auth0 for authentication. Currently there isnt any way for me to validate this access token in my api routes. 

### Describe the ideal solution

Ideally I would like to be able to generate a valid session between my react native app, and the nextjs api routes using the access token, thus allowing me to access the api route.

**Comment by adamjmcgrath** [comment]
See https://github.com/auth0/nextjs-auth0/pull/1052#issuecomment-1418801403

**Comment by Wolfleader101** [comment]
> See [#1052 (comment)](https://github.com/auth0/nextjs-auth0/pull/1052#issuecomment-1418801403)

@adamjmcgrath Thanks, responded in the PR :)
