### ISSUE TITLE
Get user information by cookie

### ISSUE THREAD

**Issue by krystian50** [auth0/nextjs-auth0#105]
### Description
I'm trying to inform fronted if a user is logged in or (best case scenario) what is the actual user data. I tried to use function `onUserLoaded` in `/callback` endpoint to set information about user in a cookie (boolean flag or string object). And use `/logout` callback to remove the cookie. Unfortunately this function does not set any cookie. Probably, because `Set-Cookie` header is used somewhere else in the code
```
 onUserLoaded: async (req, res, session, state) => {
        res.setHeader(
          'Set-Cookie',
          cookie.serialize('user', '{foo: "bar"}', { path: '/' }),
        );
        return session;
      },
```
Any way to actually inform frontend about user data? I want to show some layout features such as username, login button synchronously, without waiting for response from` /me` (SSG pages).

### Reproduction

//callback file
```
import auth0 from 'common/utils/auth0';
import { NextApiResponse, NextApiRequest } from 'next';
import cookie from 'cookie';

export default async (req: NextApiRequest, res: NextApiResponse) => {
  try {
    await auth0.handleCallback(req, res, {
      redirectTo: '/',
      onUserLoaded: async (req, res, session, state) => {
        res.setHeader(
          'Set-Cookie',
          cookie.serialize('user', '{foo: "bar"}', { path: '/' }),
        );
        return session;
      },
    });
  } catch (error) {
    console.error(error);
    res.status(error.status || 400).end(error.message);
  }
};
```

### Environment

- "@auth0/nextjs-auth0": "^0.12.0"
- "next": "9.3.6"
- "cookie": "^0.4.1",
- osx

**Comment by haf** [comment]
SSG pages already have a `NextPageContext` that has a `req: http.IncomingMessage` that you can feed to `auth0.getSession()` that gets you the id-token as well as access-token. That way you don't have to keep a secondary storage of the user details.

**Comment by Widcket** [comment]
Hi @krystian50, in the new [v1.0.0-beta.0](https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0) release you can now check the user authentication status and get their profile on the client side by using the `useUser` hook. Check out the details in the [beta README](https://github.com/auth0/nextjs-auth0/tree/beta#basic-setup).
