### ISSUE TITLE
Unsure universal login passwordless is possible in nextjs-auth0

### ISSUE THREAD

**Issue by JameelKhan9** [auth0/nextjs-auth0#1056]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Trying to implement Passwordless via Universal Login is not currently possible with nextjs-auth0.

https://auth0.com/docs/passwordless-with-new-universal-login#update-your-application

### Describe the ideal solution

Should be able to find an option for changing connection type:
https://auth0.com/docs/authenticate/passwordless/passwordless-with-new-universal-login#update-your-application

### Alternatives and current workarounds

Current workaround is to Customize the Login Page to the Classic:
https://auth0.com/docs/authenticate/passwordless/implement-login/universal-login

**Comment by adamjmcgrath** [comment]
Hi @JameelKhan9 - thanks for raising this

Looks like you're using an Early Access feature.

> Should be able to find an option for changing connection type:

The docs you've shared (https://auth0.com/docs/authenticate/passwordless/passwordless-with-new-universal-login) suggest that you should pass a `connection` parameter to the `/authorize` endpoint.

You can do this by passing the `authorizationParams` option to `handleLogin` - there are some docs here https://auth0.github.io/nextjs-auth0/interfaces/handlers_login.AuthorizationParams.html#connection

**Comment by JameelKhan9** [comment]
Thanks @adamjmcgrath, will have a look into the `authorizationParams`.

**Comment by adamjmcgrath** [comment]
np @JameelKhan9 - ping me to reopen this issue if it doesn't work for you

**Comment by JameelKhan9** [comment]
@adamjmcgrath appreciate it. It looks like specifying this connection stops the social logins setup in auth0. Please let me know if you have any thoughts as to support both passwordless and social logins using this Early Access Feature.
