### ISSUE TITLE
PKCE Support

### ISSUE THREAD

**Issue by reicheltp** [auth0/nextjs-auth0#109]
### Describe the problem you'd like to have solved

The OAuth 2.0 Security Best Current Practice recommends the usage of PKCE for the authorization code grant: https://tools.ietf.org/html/draft-ietf-oauth-security-topics-15#section-2.1.1

### Describe the ideal solution

If the discovery document shows that the endpoint supports PKCE, `auth0.handleLogin` should add the `code_challenge` and not use `state`.

### Additional context
- https://tools.ietf.org/html/rfc8414#section-2 at `code_challenge_methods_supported` 
- https://github.com/panva/node-openid-client#authorization-code-flow

**Comment by Widcket** [comment]
Hi @reicheltp, this is now fixed in the new [v1.0.0-beta.0](https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0) release.

**Comment by reicheltp** [comment]
This is awesome 👍 I'll try out next week! 😃

**Comment by balazsorban44** [comment]
@Widcket did you use a cookie to store the `code_verifier`?

**Comment by Widcket** [comment]
@balazsorban44 yup, take a look at [this file](https://github.com/auth0/nextjs-auth0/blob/beta/src/auth0-session/transient-store.ts).
