### ISSUE TITLE
Login with multiple tabs opened gives error of invalid state, invalid grant_type

### ISSUE THREAD

**Issue by HamzaTrimulabs** [auth0/nextjs-auth0#1090]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

This issue has been discussed in [Auth0 community](https://community.auth0.com/t/authentication-fails-anomalydetected-invalid-state-after-multiple-tabs-logout-login-in-old-tab/58793/5) and solution has been provided for React app that adding cacheLocation solves the problem.

However, I cannot find a way to fix this issue in Next Js app. How can I add the cacheLocation in Next app ?

### Reproduction

**Steps to reproduce**

- Make sure no prior session exists
- Open your next app in a tab, it will lead to login page
- In a new tab open the same Next app , it will lead to login page
- Login in one tab
- Then login in the other tab
- Error will appear in one or both tabs like --> Invalid state or invalid grant_type or anomaly detected. 

### SDK version

1.9.1

### Next.js version

12.2.5

### Node.js version

16.13.2

**Comment by adamjmcgrath** [comment]
Hi @HamzaTrimulabs - thanks for raising this

This is expected behaviour - see https://github.com/auth0/nextjs-auth0/issues/142#issuecomment-763529732 for more info

> and solution has been provided for React app that adding cacheLocation solves the problem.

We can't use `SessionStorage` (which resolves the problem for `auth0-react`) because `SessionStorage` is only accessible to the browser and the state in this SDK is set/read by the server (which is limited to cookies)
