### ISSUE TITLE
Problems creating own instance

### ISSUE THREAD

**Issue by ben-propflo** [auth0/nextjs-auth0#1098]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm trying to update nextjs-auth0 in our app and hit the following error:

>  Error: You cannot mix creating your own instance with `initAuth0` and using named exports like `import { handleAuth } from '@auth0/nextjs-auth0'`

We are using our own instance so that we can override the client ID and secret based on the request host, which looked something like this:

[...auth0].ts
```
import { initAuth0 } from '@auth0/nextjs-auth0'
import { IncomingMessage } from 'http'
import { NextApiRequest, NextApiResponse } from 'next'

const initializeAuth0 = (req: NextApiRequest | IncomingMessage): ReturnType<typeof initAuth0> => {
  // code
  return initAuth0({
    baseURL:<custom>,
    clientID: <custom>,
    clientSecret: <custom>
  })
}

export default function auth(req: NextApiRequest, res: NextApiResponse) {
  const auth0 = initializeAuth0(req)
  return auth0.handleAuth()(req, res)
}
```

I found [the following](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#create-your-own-instance-of-the-sdk) and have been trying to replace the import usages with ones that use my own instance instance (some code taken from closed issues):

**[...auth0].ts**
```
import { NextApiRequest, NextApiResponse } from 'next'
import getAuth from 'shared/auth0/auth'

export default function auth(req: NextApiRequest, res: NextApiResponse) {
  const auth0 = getAuth(req)
  return auth0.handleAuth()(req, res)
}
```

**shared/auth0/auth.ts**
```
import { initAuth0 } from '@auth0/nextjs-auth0'
import { IncomingMessage, ServerResponse } from 'http'
import { NextApiRequest, NextApiResponse } from "next"

export default function getAuth(req: NextApiRequest | IncomingMessage): ReturnType<typeof initAuth0> {
    // code
  return initAuth0({
    baseURL:<custom>,
    clientID: <custom>,
    clientSecret: <custom>
  })
}

export async function getSession(req: NextApiRequest | IncomingMessage, res: NextApiResponse | ServerResponse) {
    const auth = getAuth(req);
    return auth.getSession(req, res);
}
```

**page.tsx**
```
import getAuth, { getSession } from 'shared/auth0/auth'

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const instance = getAuth(ctx.req)

  return instance.withPageAuthRequired<Props>({
    async getServerSideProps({ req, res }) {
      const sessionUser = (await getSession(req, res))?.user!
      const dbUser = await getDbUser(sessionUser)
  
      return { props: { dbUser } }
    },
  })(ctx)
}
```

Though I am still running into the same error when trying to load that updated page, am I missing something somewhere, is this the correct approach, can I somehow trace where a 'default' instance is being created? There are no other named imports from the auth0 package from what I can see on the above page :think

### Reproduction

1. Create a func to return a custom instance
2. Create similar function(s) to that of nextjs-auth0 like getSession, call custom func to create own instance and return getSession etc.
3. Update page to use custom instance to then call withPageAuthRequired on it.

### SDK version

2.2.2

### Next.js version

13.2.3

### Node.js version

18.14.0

**Comment by adamjmcgrath** [comment]
Hi @ben-propflo - thanks for raising this

From the code you've shared it I can't see any reason why you'd get that error.

One suggestion, the check that throws that error stores its state in memory, so if you switch between own instance and named exports without restarting the dev server, you may get that error. Try restarting the dev server when you switch between the 2 modes.

Otherwise, check if you're not importing a named export elsewhere in your code

**Comment by ben-propflo** [comment]
Hey @adamjmcgrath, really appreciate your help. I hadn't realized that it stored that in memory, which now makes sense why it worked on the first load only! We had an API call the page was making that was still using the old getSession method, doh! All appears to work fine now 🚀
