### ISSUE TITLE
New universal login passwordless link issue

### ISSUE THREAD

**Issue by JamesBliss** [auth0/nextjs-auth0#1100]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello,

I'm trying to get passwordless link working with this package. I can get the "Code" version to work but from everything I am reading online and within the documentation to change to "link" you need to be able to provide a param of `passwordlessMethod`. 

I'm using the New Universal Lock so I cannot add this code to the instantiation of the Lock itself within the Auth0 UI.

Here is what I'm using a the moment:

```
import { handleLogin } from '@auth0/nextjs-auth0';

export default async function login(req, res) {
  const options = {
    authorizationParams: {
      scope: "openid profile email offline_access",
      // Switches to passwordless
      connection: "email",
      // This is what I _think_ I need to switch from code
      passwordlessMethod: "link"
    },
  };

  try {
    await auth0.handleLogin(req, res, options);
  } catch (error) {
    res.status(error.status || 500).end(error.message);
  }
}
```

Hopefully, I'm just missing something straightforward. 

### Reproduction

Standard NextJS project and standard setup of this package, then create a new `pages/api/auth/login.js` route with code to switch to passwordless e.g. 

```
import { handleLogin } from '@auth0/nextjs-auth0';

export default async function login(req, res) {
  const options = {
    authorizationParams: {
      scope: "openid profile email offline_access",
      connection: "email",
      passwordlessMethod: "link",
    },
  };

  try {
    await handleLogin(req, res, options);
  } catch (error) {
    res.status(error.status || 500).end(error.message);
  }
}
```

### SDK version

2.2.2

### Next.js version

13.2.3

### Node.js version

16.13.2

**Comment by adamjmcgrath** [comment]
Hi @JamesBliss - thanks for raising this

Right now, for new universal login, we only support Passwordless to be configured with a code. I don't know when magic link might be added I'm afraid.

**Comment by JamesBliss** [comment]
@adamjmcgrath Thanks for getting back to me so quickly.

That's disappointing to hear, I assumed it existed since within the UI of auth0 you can manage the copy for that screen in the "custom_text" page.

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/895768/223127414-1a6be2a0-78f3-4a31-bef4-f48e44b6e62b.png">

**Comment by adamjmcgrath** [comment]
Hi @JamesBliss - thanks for sharing that

Apologies if that is confusing, I'll pass your feedback on to the product team

You can confirm here that Magic link is not currently available on the new universal login page: https://auth0.com/docs/authenticate/passwordless/authentication-methods/email-magic-link#:~:text=Note%3A%20Magic%20Links%20are%20not%20supported%20in%20New%20Universal%20Login.

**Comment by JamesBliss** [comment]
@adamjmcgrath No problem and thanks for confirming 😄
