### ISSUE TITLE
[DOCS] Vercel (edge) Middleware does not seem to pickup AUTH0_BASE_URL from .env.production in Preview environments

### ISSUE THREAD

**Issue by Izhaki** [auth0/nextjs-auth0#1106]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The [Assigning the AUTH0_BASE_URL](https://github.com/auth0/nextjs-auth0/blob/main/examples/README.md#assigning-the-auth0_base_url) guide is split into:

- Preview deployments
- Production deployments

The preview deployments guide recommends:

```env
# .env.production
AUTH0_BASE_URL=$VERCEL_URL
```

which works perfectly fine until one introduces `middleware.ts` and uses `auth0` in there:

```ts
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { getSession } from '@auth0/nextjs-auth0/edge';

export async function middleware(req: NextRequest) {
  const { pathname } = req.nextUrl;

  if (pathname === '/') {
    const res = NextResponse.next();
    const session = await getSession(req, res);
    const loggedIn = Boolean(session);
    if (!loggedIn) {
      return NextResponse.rewrite(new URL('/guest', req.url));
    }
  }
}

export const config = {
  matcher: ['/'],
};
```

The actual build on Vercel does pickup `.env.production`:

```sh
info  - Loaded env from /vercel/path0/app/.env.production
```

However, this is not seen by the middleware, which crashes (and does the whole app) with:

```
TypeError: "baseURL" is required
    at (../node_modules/.pnpm/@auth0+nextjs-auth0@2.2.2_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/get-config.js:163:0)
```

I'm not sure, but this could be an issue with Vercel itself?

# Fix

The fix for this is to follow the "Production Deployments" instructions, and add `AUTH0_BASE_URL=$VERCEL_URL` in Vercel's `Settings > Environment Variables`.

# Action Proposed

Even if a bug in Vercel, the [Assigning the AUTH0_BASE_URL](https://github.com/auth0/nextjs-auth0/blob/main/examples/README.md#assigning-the-auth0_base_url) documentation could be updated mentioning the above.

### Reproduction

- Create a nextJS app
- Add `middleware.ts`, add and use `auth0` in there
- Deploy to a preview environment in Vercel

### SDK version

2.2.2

### Next.js version

13.1.6

### Node.js version

18.14.1

**Comment by adamjmcgrath** [comment]
Hi @Izhaki - thanks for raising this

The information was accurate the last time I tested this on Vercel, but something may have changed since then. I'll try and take a look soon and get back to you.

**Comment by adamjmcgrath** [comment]
@Izhaki - after some investigation, this is because runtime environment variables aren't available in Vercel Middleware they have to be made available at build time and Next.js doesn't evaluate `.env.production` at build time.

It "works" when you set `AUTH0_BASE_URL` to `$VERCEL_URL` in Vercel's `Settings > Environment Variables` in preview deployments because you are setting a value for `AUTH0_BASE_URL` which satisfies the validation in `getSession`. But you are literally setting the value to "$VERCEL_URL" not a url - this doesn't matter though because `getSession` doesn't use the `AUTH0_BASE_URL` value - you can effectively set it to anything to satisfy the validation in "Preview" as long as you have a `.env.production` that the Node server will use at runtime.

So for now, you can use your workaround, but we will need to figure out a better way of doing dynamic Preview Deployment URLs since Middleware doesn't support runtime environment variables.

**Comment by Izhaki** [comment]
Wow. Thanks for the thorough investigation and explanation.

I wonder if `getSession` doesn't use `AUTH0_BASE_URL`, why validate in the first place? Ditto for all other `@auth0/nextjs-auth0/edge` API?

Point is "we will need to figure out a better way of doing dynamic Preview Deployment URLs " is all good and sound, but I don't think `getSession` should validate if it is not using it to begin with.

`WithMiddlewareAuthRequired` hints at an assumption that apps will use `middleware.ts` exclusively to block private resources on the edge (resources are defined in `matcher`), but I think in practice most app will use `middleware.ts` for much more than that, hence won't be using `WithMiddlewareAuthRequired` directly, rather use `getSession()` in the middleware body and block resources that way. I'm pretty sure `WithMiddlewareAuthRequired` doesn't need BASE_URL either.

All of this is just to say that the common use cases may not require BASE_URL, making the problem with dynamic preview deployments something that can be deferred until someone hits that issue in practice.

Removing validation from `getSession` (et al) could involve less work.

**Comment by adamjmcgrath** [comment]
> Removing validation from getSession (et al) could involve less work.

Thanks for the suggestion @Izhaki - it's a good one, however the instance that backs `getSession` does require `AUTH0_BASE_URL` - or at least will when the edge runtime code has feature parity with the Node runtime code, so removing it temporarily only to have to add it back in a breaking change is not going to work for us.

Please continue to use your workaround as we consider other options.

**Comment by adamjmcgrath** [comment]
> But you are literally setting the value to "$VERCEL_URL" not a url

Have just tested this on a new deployment on Vercel and you can now reference system env vars - so this is no longer correct. Tested here:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/1299658/228479166-68ed8168-ce5b-47dc-96f6-5be215cfba9a.png">

Which deploys to: https://vercel-env-vars-test-git-preview-test-adamjmcgrath.vercel.app/

We no longer need the `.env.production` workaround so have updated the deployment instructions in #1135

**Comment by cbovis** [comment]
@adamjmcgrath it's worth noting that this solution is close but has edges, specifically because of preview url truncation: https://vercel.com/docs/concepts/deployments/generated-urls#truncation

**Comment by jonahallibone** [comment]
@adamjmcgrath Is this the selection solution to this problem? It seems like the addition of the docs was closed because another solution was required. My current solution is to forego the withMiddleware entirely and use:

```
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import auth0 from "util/auth0-edge";
import getEnvUrl from "util/get-env-url";

const middleware = async (req: NextRequest) => {
  const res = NextResponse.next();
  const user = await auth0.getSession(req, res);

  if (user) {
    return NextResponse.next();
  }

  const envUrl = getEnvUrl();

  const baseURL = envUrl;

  return NextResponse.redirect(
    `${baseURL}/api/auth/login?returnTo=${encodeURI(req.nextUrl.href)}`
  );
};

export const config = {
  matcher: [
    "/",
    "/nonprofit/:path*",
    "/foundation/:path*",
    "/admin:path*",
    "/reviewer/tasks",
    "/referee/task/:path*",
    "/formauth/:path*",
    "/aggregate/:path*",
  ],
};

export default middleware;
```
with `getEnvUrl()` looking like:
```
const getEnvUrl = () => {
  if (process.env.ENVIRONMENT_URL) {
    return process.env.ENVIRONMENT_URL;
  }
  if (process.env.VERCEL_URL) {
    return `https://${process.env.VERCEL_URL}`;
  }

  return process.env.AUTH0_BASE_URL;
};

export default getEnvUrl;
```

`process.env.ENVIRONMENT_URL` is basically any assigned url we have like `staging.myapp.com` or `development.myapp.com`

**Comment by adamjmcgrath** [comment]
@jonahallibone - as of [2.6.0](https://github.com/auth0/nextjs-auth0/releases/tag/v2.6.0) you can now specify `NEXT_PUBLIC_AUTH0_BASE_URL` which does get picked up by Middleware

See the new docs: https://github.com/auth0/nextjs-auth0/blob/main/examples/README.md#assigning-the-auth0_base_url
