### ISSUE TITLE
useFetchUser uses global in deps array

### ISSUE THREAD

**Issue by haf** [auth0/nextjs-auth0#112]
<img width="909" alt="image" src="https://user-images.githubusercontent.com/193115/82155692-17707e80-9877-11ea-92db-d9a1146a9da0.png">

It should not

**Comment by Widcket** [comment]
Hi @haf, this is fixed in [v1.0.0-beta.0](https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0).
