### ISSUE TITLE
Add helper: withEdgeApiAuthRequired

### ISSUE THREAD

**Issue by amitav13** [auth0/nextjs-auth0#1129]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'm trying to authenticate my edge API routes. This feels like a fundamental problem - I just updated to the v2 SDK and can't find anything in the docs that enables this.

`withApiAuthRequired` doesn't support the request/response params needed for edge API routes. 

### Describe the ideal solution

A helper function like how we have it for API routes - `withApiAuthRequired` would be ideal. We'd also need `getSession` to work in an edge API.  

### Alternatives and current workarounds

I haven't tried this out yet but I suppose we could use `withMiddlewareAuthRequired` to authenticate my edge API routes?

**Comment by adamjmcgrath** [comment]
Hi @amitav13 - thanks for raising this

`getSession` and `withMiddlewareAuthRequired` both run on the edge runtime, so you can use those to protect edge APIs - see https://github.com/auth0/nextjs-auth0#edge-for-middleware-and-the-edge-runtime

**Comment by amitav13** [comment]
I'm still not sure how we can configure some public routes to do something and others to be protected and do something else. 
`middleware.ts`: 
```ts
import {withMiddlewareAuthRequired} from "@auth0/nextjs-auth0/edge";
import {NextRequest, NextResponse} from "next/server";

export const config = {
  matcher: ["/publicroute"],
};

export async function middleware(req: NextRequest) {
  const {nextUrl: url, geo} = req;
  // DO THINGS FOR PUBLIC ROUTES - but now they are not public anymore

  return NextResponse.rewrite(url);
}

export default withMiddlewareAuthRequired();
// how I do define auth required for the rest of my routes? 
```

**Comment by adamjmcgrath** [comment]
Hi @amitav13 

You could just execute the `withMiddlewareAuthRequired()` handler based on the path in your middleware, something like

```js
const mw = withMiddlewareAuthRequired();

export async function middleware(...args) {
  const [ req ] = args;
  const {nextUrl: url, geo} = req;
  if (req.path === "/publicroute") {
    // Do things for public routes
  } else {
    //  define auth required for the rest of your routes
    return mw(...args);
  }
}

```
