### ISSUE TITLE
Debugging withPageAuthRequired proxy api call

### ISSUE THREAD

**Issue by tn819** [auth0/nextjs-auth0#1133]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We are attempting to understand 10-15 second delayed reponses on sporadic requests to the Vercel service and suspect an error in our auth implementation is the root cause. This issue strongly resembles the issues described in https://github.com/auth0/nextjs-auth0/issues/751#issuecomment-1181987739, except rather than 4 seconds we are now at 10-15 seconds (15 seconds being the Vercel Pro timeout).

Our auth code can be summarized as the below.

file: `lib/auth/auth0.ts`
- we instantiate auth0 per guidelines provided 
```ts
import { Auth0Server, initAuth0 } from "@auth0/nextjs-auth0";
let instance: Auth0Server;

/** This function allows replaces the $VERCEL_URL variable inside the $AUTH0_BASE_URL.
 * This allows to configured the base URL dynamically for Vercel preview deployments.
 */
export const baseUrl = () => {
  const auth0BaseUrl = process.env.AUTH0_BASE_URL;
  const baseUrl =
    auth0BaseUrl?.indexOf("$VERCEL_URL") !== -1 && process.env.VERCEL_URL
      ? auth0BaseUrl?.replaceAll("$VERCEL_URL", process.env.VERCEL_URL)
      : auth0BaseUrl;

  console.info(`Using Auth0 base URL: ${baseUrl}`);
  return baseUrl;
};

export function getAuth0Instance(): Auth0Server {
  if (instance) {
    return instance;
  }
  instance = init();
  return instance;
}

const init = () =>
  initAuth0({
    baseURL: baseUrl(),
  });
 ```
path: `pages/api/auth/[...auth0].ts`
- instantiation is certain to use the same instance
```ts
import { getAuth0Instance } from "@lib/auth/auth0";

export default getAuth0Instance().handleAuth();
```

path: `pages/api/[...path].ts`
- we have to proxy in order to hit an external API that is validating nextjs token
```ts
import type { NextApiRequest, NextApiResponse } from "next";
import httpProxy from "http-proxy";

import { getAuth0Instance } from "@lib/auth/auth0";
import buildUrl from "@lib/api/apiUrlBuilder";

const proxy: httpProxy = httpProxy.createProxyServer();

// Do not delete this.
export const config = {
  api: {
    externalResolver: true,
    bodyParser: false,
  },
};

export default getAuth0Instance().withApiAuthRequired(
  async (req: NextApiRequest, res: NextApiResponse) => {
    let accessToken: string | undefined;
    try {
      const tokens = await getAuth0Instance().getAccessToken(req, res);
      accessToken = tokens.accessToken;
    } catch (e) {
      console.warn(e);
      return res.status(401).send("getting access token failed");
    }

    return new Promise<void>((resolve, reject) => {
      if (!req.url) {
        return reject("Missing request url");
      }

      const apiUrl = buildUrl(req.url);
      req.url = apiUrl.href;

      proxy.web(
        req,
        res,
        {
          changeOrigin: true,
          target: apiUrl,
          headers: {
            Authorization: `Bearer ${accessToken}`,
          },
        },
        (err) => {
          if (err) {
            return reject(err);
          }
          resolve();
        }
      );
    });
  }
```

Next logs show that in the instantiation phase we are sometimes getting caught 10-15 seconds. This is difficult to debug and understand and obviously not reproducible locally. 3-5 seconds as cited in your previous responses and docs feels normal, but we cannot understand the possible issues

### Reproduction

Intermittent api calls with no consistent pattern failing. Every time Auth0 instantiates we get a console.log in vercel logs and see that is the source of a delayed response.

![image](https://user-images.githubusercontent.com/12561498/228019343-da40be58-3c4c-410d-ae2b-d0bb3ce6ba2c.png)
![Screenshot 2023-03-27 at 19 27 37](https://user-images.githubusercontent.com/12561498/228019648-0409ff5e-1b37-45c9-9958-7eee84550dc0.png)

### SDK version

2.2.1

### Next.js version

13.1.6

### Node.js version

18.x

**Comment by adamjmcgrath** [comment]
Hi @tn819 - thanks for raising this

The only thing that looks unusual about your setup, and the only thing I can recommend beyond https://github.com/auth0/nextjs-auth0/issues/751#issuecomment-1181987739, is the use of a proxy server.

Could you not just use the built in fetch to request the `apiUrl` and return the response? eg https://github.com/auth0/nextjs-auth0/blob/main/examples/kitchen-sink-example/pages/api/shows.ts

**Comment by tn819** [comment]
@adamjmcgrath - thanks for the clarification. The proxy is really a nicer solution in some ways as it avoids the whole downstream CORS situation, but maybe it will come to that.

We were also thinking of trying to use the edge network to see if that speeds anything up. However, right now the proxy build fails with the edge config as it has some dependencies that aren't part of the edge runtime. However, if we work around that, is edge fully supported on your side now? It isn't 100% clear from reading the threads. 

Access to edge network might motivate us to ditch the proxy (encouraged in vercel docs) or write an edge network compatible one. We've also inquired with Vercel.

**Comment by adamjmcgrath** [comment]
> The proxy is really a nicer solution in some ways as it avoids the whole downstream CORS situation, but maybe it will come to that.

How does the proxy help with CORs? The request is being made from server to server and CORs only applies to a browser.

> However, if we work around that, is edge fully supported on your side now? It isn't 100% clear from reading the threads.

You can access the session on the edge, see https://github.com/auth0/nextjs-auth0#edge-for-middleware-and-the-edge-runtime

**Comment by tn819** [comment]
> > The proxy is really a nicer solution in some ways as it avoids the whole downstream CORS situation, but maybe it will come to that.
> 
> How does the proxy help with CORs? The request is being made from server to server and CORs only applies to a browser.
> 
> > However, if we work around that, is edge fully supported on your side now? It isn't 100% clear from reading the threads.
> 
> You can access the session on the edge, see https://github.com/auth0/nextjs-auth0#edge-for-middleware-and-the-edge-runtime

We've been looking at this and still seeing some strangeness. I have attempted to create a fake proxy compatible with the Edge, still not quite there. 

Timing all the runs/performance and just the overall JS bundle loading in the function seems to be the problem. However, it clearly can't be isolated to the auth0 library so will close @adamjmcgrath

**Comment by harrycollin** [comment]
@tn819 I am also facing a very similar issue. I also proxy API calls and have a similar setup to you. Did you manage to find out what was causing this?

**Comment by tn819** [comment]
Yes @harrycollin --> we were using Material UI and the full import of MUI caused serverless function deployment type to be extremely slow. In spite of the claims of tree-shaking in their docs, we had to adjust how we imported in components (you can also use next modularizeImports setting to reduce the bundle to a manageable size). 

This brought our function execution time down to ~3 seconds from 10-15. There's a few threads on MUI side around this, but definitely not an Auth0 problem.

**Comment by tusbar** [comment]
@tn819 I’ve been at this for a while and finally came up with an edge middleware proxy that works and thought I’d share it here.

```ts
import {getAccessToken, withMiddlewareAuthRequired} from '@auth0/nextjs-auth0/edge'
import {NextResponse} from 'next/server'

export default withMiddlewareAuthRequired(async function (req) {
  const res = NextResponse.next()

  const url = new URL(process.env.API_URL!)
  url.pathname = req.nextUrl.pathname.replace(/^\/api/, '')
  url.search = req.nextUrl.search
  url.searchParams.delete('path')

  const newRequest = new Request(url, req)

  const {accessToken} = await getAccessToken(req, res)
  newRequest.headers.delete('cookie')
  newRequest.headers.set('host', url.host)
  newRequest.headers.set('user-agent', 'xxx')
  newRequest.headers.set('authorization', `Bearer ${accessToken}`)
  newRequest.headers.set('x-forwarded-host', req.nextUrl.host)
  newRequest.headers.set('x-forwarded-proto', req.nextUrl.protocol.slice(0, -1))
  newRequest.headers.set('x-forwarded-port', req.nextUrl.port)

  return fetch(newRequest)
})
```
