### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isKeyObject')

### ISSUE THREAD

**Issue by mayurborkar27** [auth0/nextjs-auth0#1139]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

1. We've updated @auth0/nextjs-auth0's version from 1.9.1 to 2.0.0.
2. After updating @auth0/nextjs-auth0 to 2.0.0, getting error `TypeError: Cannot read properties of undefined (reading 'isKeyObject')`. 
3. We have custom auth0 store in our project and inside pages/index.ts file using getInitialProps we are passing session to our hook.

### Reproduction

1. Upgrade @auth0/nextjs-auth0 from 1.9.1 to 2.0.0 in next app.
2. Run the application 
3. Getting error `TypeError: Cannot read properties of undefined (reading 'isKeyObject')`

### SDK version

2.0.0

### Next.js version

12.1.4

### Node.js version

18.15.0

**Comment by adamjmcgrath** [comment]
Hi @mayurborkar27 - thanks for raising this

Could you share a stracktrace and any other code that might help me understand where this error is coming from? Could you also check that you have completed any necessary steps in the [migration guide](https://github.com/auth0/nextjs-auth0/blob/main/V2_MIGRATION_GUIDE.md)

**Comment by sparxz12** [comment]
hi @adamjmcgrath

I am encountering the same error with version 2.4.0.

The error is triggered by calling the getAccessToken method from @auth0/nextjs-auth0, when I use it in my _app.tsx file with getInitialProps as follows:

```
MyApp.getInitialProps = async (appContext: AppContext) => {
  const appProps = await App.getInitialProps(appContext);
  const accessToken = (
    await getAccessToken(appContext.ctx.req as NextApiRequest, appContext.ctx.res as NextApiResponse)
  ).accessToken;
  const languages = await fetchLanguages(accessToken);
  return { ...appProps, pageProps: { languages } };
};
```

I receive the access token and can successfully trigger the authenticated request via fetchLanguages(accessToken). Maybe its also worth mentioning that MyApp is wrapped in UserProvider from '@auth0/nextjs-auth0/client' as follows:

```
return (
    <UserProvider>
      <header className={`${fontSans.variable} ${fontSpecial.variable} font-sans`}>
        <NavbarContainer />
      </header>
      <main className={`${fontSans.variable} ${fontSpecial.variable} font-sans`}>
        {loading ? <BrotLoading className='mx-auto mt-[40vh] h-[50px] w-[50px]' /> : <Component {...pageProps} />}
      </main>
    </UserProvider>
  )
```


However, the app loads and the following stack trace is displayed:

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'isKeyObject')

Call Stack
eval
../node_modules/openid-client/lib/helpers/is_key_object.js (4:0)
../../node_modules/openid-client/lib/helpers/is_key_object.js
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/pages/_app.js (1232:1)
options.factory
/_next/static/chunks/webpack.js (691:31)
__webpack_require__
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (346:21)
eval
../node_modules/openid-client/lib/client.js (11:20)
../../node_modules/openid-client/lib/client.js
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/pages/_app.js (1122:1)
options.factory
/_next/static/chunks/webpack.js (691:31)
__webpack_require__
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (346:21)
eval
../node_modules/openid-client/lib/issuer.js (5:18)
../../node_modules/openid-client/lib/issuer.js
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/pages/_app.js (1362:1)
options.factory
/_next/static/chunks/webpack.js (691:31)
__webpack_require__
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (346:21)
eval
../node_modules/openid-client/lib/index.js (1:15)
../../node_modules/openid-client/lib/index.js
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/pages/_app.js (1352:1)
options.factory
/_next/static/chunks/webpack.js (691:31)
__webpack_require__
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (346:21)
eval
../node_modules/@auth0/nextjs-auth0/dist/auth0-session/transient-store.js (4:22)
../../node_modules/@auth0/nextjs-auth0/dist/auth0-session/transient-store.js
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/pages/_app.js (128:1)
options.factory
/_next/static/chunks/webpack.js (691:31)
__webpack_require__
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (346:21)
eval
../node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js (21:24)
../../node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/pages/_app.js (84:1)
options.factory
/_next/static/chunks/webpack.js (691:31)
__webpack_require__
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (346:21)
eval
../node_modules/@auth0/nextjs-auth0/dist/index.js (6:22)
../../node_modules/@auth0/nextjs-auth0/dist/index.js
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/pages/_app.js (359:1)
options.factory
/_next/static/chunks/webpack.js (691:31)
__webpack_require__
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (346:21)
eval
webpack-internal:///./pages/_app.tsx (14:77)
./pages/_app.tsx
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/pages/_app.js (950:1)
options.factory
/_next/static/chunks/webpack.js (691:31)
__webpack_require__
file:///home/yves/Documents/_arbeit/agentur_brot/see/see-collaboration-platform/packages/frontend/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (346:21)
eval
../node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?absolutePagePath=private-next-pages%2F_app&page=%2F_app! (5:15)
execute
../node_modules/next/dist/client/route-loader.js (211:50)
```

**Comment by adamjmcgrath** [comment]
Hi @sparxz12 - thanks for sharing that

The error suggests you're trying to import something that requires the node runtime (one of these apis https://github.com/auth0/nextjs-auth0#server-for-nodejs) into an environment that doesn't support node (either the browser or the edge)

This can happen if you import anything from `@auth0/nextjs-auth0` and use it in the browser (in this case you should use `@auth0/nextjs-auth0/client`) eg.

```js
import { withPageAuthRequired } from '@auth0/nextjs-auth0/client'; // not '@auth0/nextjs-auth0'

export default  withPageAuthRequired(function MyComponent() { ... })
```

**Comment by sparxz12** [comment]
> Hi @sparxz12 - thanks for sharing that
> 
> The error suggests you're trying to import something that requires the node runtime (one of these apis https://github.com/auth0/nextjs-auth0#server-for-nodejs) into an environment that doesn't support node (either the browser or the edge)
> 
> This can happen if you import anything from `@auth0/nextjs-auth0` and use it in the browser (in this case you should use `@auth0/nextjs-auth0/client`) eg.
> 
> ```js
> import { withPageAuthRequired } from '@auth0/nextjs-auth0/client'; // not '@auth0/nextjs-auth0'
> 
> export default  withPageAuthRequired(function MyComponent() { ... })
> ```

Thank you for your explanation.

The error is being triggered by `_appt.tsx` in the pages folder. I am attaching my entire file for better understanding:

```
import '../styles/globals.css';
import 'react-loading-skeleton/dist/skeleton.css';

import { getSession } from '@auth0/nextjs-auth0';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import localFont from '@next/font/local';
import App, { AppContext, AppProps } from 'next/app';
import Router from 'next/router';
import { useEffect, useState } from 'react';

import BrotLoading from '../components/loading/brot-loading';
import NavbarContainer from '../components/navbar/navbar-container';
import { fetchLanguages } from '../services/language.service';

export const fontSans = localFont({
  src: '../public/assets/fonts/Montserrat-Medium.ttf',
  variable: '--font-see-sans-serif',
});
export const fontSpecial = localFont({
  src: '../public/assets/fonts/PPMonumentExtended-Black.ttf',
  variable: '--font-see-special',
});

const MyApp = ({ Component, pageProps }: AppProps) => {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    const start = () => {
      setLoading(true);
    };
    const end = () => {
      setLoading(false);
    };
    const error = () => {
      console.log('route error');
      setLoading(false);
    };
    Router.events.on('routeChangeStart', start);
    Router.events.on('routeChangeComplete', end);
    Router.events.on('routeChangeError', error);
    return () => {
      Router.events.off('routeChangeStart', start);
      Router.events.off('routeChangeComplete', end);
      Router.events.off('routeChangeError', error);
    };
  }, []);
  return (
    <UserProvider>
      <header className={`${fontSans.variable} ${fontSpecial.variable} font-sans`}>
        <NavbarContainer />
      </header>
      <main className={`${fontSans.variable} ${fontSpecial.variable} font-sans`}>
        {loading ? <BrotLoading className='mx-auto mt-[40vh] h-[50px] w-[50px]' /> : <Component {...pageProps} />}
      </main>
    </UserProvider>
  );
};

MyApp.getInitialProps = async (appContext: AppContext) => {
  const appProps = await App.getInitialProps(appContext);
  const session = await getSession(appContext.ctx.req as NextApiRequest, appContext.ctx.res as NextApiResponse);
  const languages = await fetchLanguages(session?.accessToken);
  return { ...appProps, pageProps: { languages } };
};

export default MyApp;
```

The error occurs as soon as I call the `getSession` or `getAccessToken` method from `@auth0/nextjs-auth0` within `MyApp.getInitialProps`. If I comment out this code (+ of course the subsequent call to fetchLanguages()), I don't receive any errors. As far as I understand, getInitialProps is definitely executed on the server side. Therefore, I assume that my code is not trying to import something that the node runtime requires into the browser. Or am I mistaken?

Unfortunately, my suspicion that getInitialProps may be executed on the edge is not confirmed. I used `getSession` from `@auth0/nextjs-auth0/edge` and did not receive a valid session (the return value was undefined). However, getSession/getAccessToken from `@auth0/nextjs-auth0` do give me a valid session/token. After that, I can call fetchLanguages() with the accessToken, receive the data, successfully pass it to pageProps, the app is briefly rendered, and then crashes with the aforementioned stack trace.

I'm really having a hard time understanding where the missing node runtime comes into play in this process.

Thank you again for your help with this issue. I really appreciate your time and expertise in trying to figure out what's going on.

**Comment by adamjmcgrath** [comment]
Hi @sparxz12 - If found the issue

`getInitialProps` gets executed on the browser as well as the node runtime  see https://nextjs.org/docs/api-reference/data-fetching/get-initial-props#:~:text=For%20the%20initial%20page%20load%2C%20getInitialProps%20will%20run%20on%20the%20server%20only.%20getInitialProps%20will%20then%20run%20on%20the%20client%20when%20navigating%20to%20a%20different%20route%20via%20the%20next/link%20component%20or%20by%20using%20next/router

To resolve the issue see the note about importing server-side only modules inside getInitialProps here: https://nextjs.org/docs/api-reference/data-fetching/get-initial-props#:~:text=If%20you%20are%20using%20server%2Dside%20only%20modules%20inside%20getInitialProps%2C%20make%20sure%20to%20import%20them%20properly%2C%20otherwise%20it%27ll%20slow%20down%20your%20app

**Comment by sparxz12** [comment]
Oh wow, I was absolutely unaware of this behavior of getInitialProps. Thank you so much for pointing out my miscalculation. By wrapping the imports of getSession in eval(), the error has now been resolved. Thank you for your help @adamjmcgrath  , I have once again been able to learn something important!

**Comment by QianKuang-nyu** [comment]
Thanks the suggestion from @adamjmcgrath , solving the issues by following your instruction.

**Comment by sarithachakilala12** [comment]
I am also facing similar issue "Getting error TypeError: Cannot read properties of undefined (reading 'isKeyObject')". Can any one help me or give me an example how to use eval with getSession imports?
