### ISSUE TITLE
returnTo parameter not working with the suggested solution + custom parameters also not working

### ISSUE THREAD

**Issue by prateekchachratf** [auth0/nextjs-auth0#1143]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

So I have looked at the issues and I see a lot of closed answers that suggest the solution wherein we basically edit out the `handleLogout` function to include the returnTo parameter. The issue is we can't register a non-fixed returnTo in the allowed URLs so it always gives an error; another thing that was suggested was to include it in the environment variable but I don't think it's a good coding practise to include a dynamic variable as an environment one

Also we wanted to have a custom parameter like handleLogout where we want to display an alert for the user whenever they've logged out but even that isn't happening because it always gives that error wherein it's "Not allowed in the list of logout URLs". I have no idea what can be the workaround. I tried adding that parameter to the app settings, even changing the link to http://localhost:3000/* but it doesn't support it. 

We just want the user to return to where they were scrolling from after logging out, for logging in it's working perfectly. How do we achieve that?

EDIT: **I would also like to mention that including every allowed URL as mentioned [here](https://github.com/auth0/nextjs-auth0/issues/283) is not possible, since we have ID driven pages so we will have a lot of pages we'd need to include before we even proceed**

### Reproduction

1. Try the logout with the suggested solution 'returnTo' and add a custom parameter if need be 'hasLoggedOut'
2. Both don't work and it is just a basic logout without any feedback for the user, bad for UX

### SDK version

2.4.0

### Next.js version

13.1.6

### Node.js version

18

**Comment by adamjmcgrath** [comment]
Closing as I think https://github.com/auth0/nextjs-auth0/issues/1143#issuecomment-1494494973 has answered your question
