### ISSUE TITLE
withMiddlewareAuthRequired - A Node.js API is used which is not supported in the Edge Runtime.

### ISSUE THREAD

**Issue by TrevorThomp** [auth0/nextjs-auth0#1152]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I swapped the usage of `withPageAuthRequired` and `withApiAuthRequired` with `withMiddlewareAuthRequired` and when I run `next build` I'm seeing the following error that fails to build my containers in GCP.

```sh
./node_modules/next/dist/server/web/spec-extension/image-response.js
A Node.js API is used (process.turbopack at line: 47) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime

Import trace for requested module:
 ./node_modules/next/dist/server/web/spec-extension/image-response.js
./node_modules/next/server.js
./node_modules/@auth0/nextjs-auth0/dist/helpers/with-middleware-auth-required.js
./node_modules/@auth0/nextjs-auth0/dist/edge.js
```

I wasn't noticing this error previously, but recently it has been consistent in each build. I swapped back to using `withPageAuthRequired` and `withApiAuthRequired` and also removed `withMiddlewareAuthRequired` which resolved the errors.

I used the same example as in the docs without any customization so not sure what could cause this to throw. I'm not using Edge API's in my application and they are all standard Node API's.

```jsx
import { withMiddlewareAuthRequired } from '@auth0/nextjs-auth0/edge';

export default withMiddlewareAuthRequired();
```

 I haven't been able to find anyone else having this same issue, so I've been at a loss. Any insight on this would be appreciated.

### Reproduction

1. Follow doc usage of using `withMiddlewareAuthRequired` in the `middleware.ts` file
2. Run `yarn build`

### SDK version

2.4

### Next.js version

13.3

### Node.js version

19

**Comment by adamjmcgrath** [comment]
Hi @TrevorThomp - thanks for raising this

I'm not able to reproduce this when running `build` for the example app, which has a similar middleware function https://github.com/auth0/nextjs-auth0/blob/main/examples/kitchen-sink-example/middleware.ts

Are you able to reproduce this locally and can you share a repo that demonstrates the issue?

**Comment by Charlie-Boyer** [comment]
I can confirm I have the same exact warning since updates to next 13.3, using withMiddlewareAuthRequired

**Comment by TrevorThomp** [comment]
@adamjmcgrath I will work on getting a reproducible example to you. In the meantime, the file that is throwing this error is a recent change in the last 13.3 release of Next.

https://github.com/vercel/next.js/pull/47715
https://github.com/vercel/next.js/commit/d71cbe9116f2a260aee44adfc3832ed7c25e57bb#diff-88cc5222d0ce7e563716eee434a1045d101b0043afd2450d66c9eb1ca4ac5cbb

**Comment by TrevorThomp** [comment]
@adamjmcgrath I was able to create an example repro that is throwing the error pretty consistently.

1. Install dependencies
2. Run `yarn:build` and/or `yarn docker:build` - Sometimes it won't throw, so delete the `.next` folder and build again if not.


https://github.com/TrevorThomp/nextjs-auth-repro

**Comment by adamjmcgrath** [comment]
Thanks for sharing that repo @TrevorThomp 

I'm still seeing the same warning if I change your middleware function to use [next-auth](https://github.com/nextauthjs/next-auth)

```js
// middleware.ts
export { default } from "next-auth/middleware";
```

```bash
./node_modules/next/dist/server/web/spec-extension/image-response.js
A Node.js API is used (process.turbopack at line: 47) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime

Import trace for requested module:
./node_modules/next/dist/server/web/spec-extension/image-response.js
./node_modules/next/server.js
./node_modules/next-auth/next/middleware.js
./node_modules/next-auth/middleware.js
```

So my guess is that this is an issue with next

**Comment by TrevorThomp** [comment]
Okay thanks for taking a look @adamjmcgrath. I will raise this issue with Next and see how this can get resolved. Feel free to close this issue in the interim as the way around it currently is to avoid using Next middleware...

**Comment by adamjmcgrath** [comment]
ok, thanks @TrevorThomp - will keep an eye on that issue you raised and reopen this if anything is needed from our end

**Comment by semy** [comment]
I have the same error with next-auth
