### ISSUE TITLE
Seeing this error: "TypeError: Cannot read properties of undefined (reading 'split')" when using this import statement: "import { UserProvider } from '@auth0/nextjs-auth0';". 

### ISSUE THREAD

**Issue by srikxr** [auth0/nextjs-auth0#1155]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello,
I am seeing this error: "TypeError: Cannot read properties of undefined (reading 'split')" when using this import statement: "import { UserProvider } from '@auth0/nextjs-auth0';". 

However, when I use this import statement: "import { UserProvider } from '@auth0/nextjs-auth0/client';", the error goes away.

I also see this error in logs when the import does not have "/client" at the end: "error - Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports."

As a result, the useUser returns this: "TypeError: Cannot destructure property 'isLoading' of '_auth0_nextjs_auth0__WEBPACK_IMPORTED_MODULE_3__.useUser' as it is undefined." when being imported like this: "import { useUser } from '@auth0/nextjs-auth0';"

And when being imported like this: "import { useUser } from '@auth0/nextjs-auth0/client'; /". the "user" variable in this statement: "  const { isLoading, user, error } = useUser()" is showing as undefined even after authenticating. 

![Screen Shot 2023-04-12 at 1 35 20 PM](https://user-images.githubusercontent.com/21000713/231578238-8e1b089c-e92e-4f81-b939-88a088d80276.png)

### Reproduction

1. Try "import { UserProvider } from '@auth0/nextjs-auth0/client'" and : "import { UserProvider } from '@auth0/nextjs-auth0'"
2. Try "import { useUser } from '@auth0/nextjs-auth0';" and : "import { useUser } from '@auth0/nextjs-auth0/client';"
3. Try this statement: "  const { isLoading, user, error } = useUser()"
4. Call "user"

### SDK version

2.4.0

### Next.js version

13.3.0

### Node.js version

9.6.4

**Comment by adamjmcgrath** [comment]
Hi @srikxr - thanks for raising this

> I am seeing this error: "TypeError: Cannot read properties of undefined (reading 'split')" when using this import statement: "import { UserProvider } from '@auth0/nextjs-auth0';".
> However, when I use this import statement: "import { UserProvider } from '@auth0/nextjs-auth0/client';", the error goes away.

This is expected behaviour - you must install `UserProvider` from `@auth0/nextjs-auth0/client` not `@auth0/nextjs-auth0` (the former is for requiring features that require a browser runtime and the latter is for installing features that require the Node runtime - see https://github.com/auth0/nextjs-auth0#api-reference)

**Comment by Widcket** [comment]
Closing as the above seems to answer your question. Please feel free to ping if you'd prefer to reopen.

**Comment by srikanthproxima** [comment]
@adamjmcgrath  I haven't used the UserProvider in my application but still im facing this issue.
