### ISSUE TITLE
Nextjs-auth0 sometimes throws a TypeError at NodeCookies.getSetCookieHeader when idle

### ISSUE THREAD

**Issue by mishchief** [auth0/nextjs-auth0#1163]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi everyone,

I’m currently getting this error every once in a while after a two days or so of being idle. Clearing my cookies and logging back in fixes the issue. The error message I’m getting is:
```
TypeError: Cannot read properties of undefined (reading 'getHeader')
at NodeCookies.getSetCookieHeader (<repo_path>/master/node_modules/@auth0/nextjs-auth0/dist/auth0-session/utils/cookies.js:47:27)
at Cookies.commit (<repo_path>/master/node_modules/@auth0/nextjs-auth0/dist/auth0-session/utils/cookies.js:31:36)
at StatelessSession.<anonymous> (<repo_path>/master/node_modules/@auth0/nextjs-auth0/dist/auth0-session/session/stateless-session.js:204:38)
at step (<repo_path>/master/node_modules/tslib/tslib.js:193:27)
at Object.next (<repo_path>/master/node_modules/tslib/tslib.js:174:57)
at fulfilled (<repo_path>/master/node_modules/tslib/tslib.js:164:62) {
page: '/dashboard/manage-events'
}
```
I’m not sure what’s causing the issue, but it seems to be related to the ‘getHeader’ property of an undefined variable. I’m working with the [@auth0](https://community.auth0.com/u/auth0)/nextjs-auth0 package, and the error is being thrown from the cookies.js file.

Has anybody encountered this issue or know what else I should be looking at to fix it?

I’ve tried updating the package, but it’s already at the latest version and this still occasionally happens, so far it has only happened on local but am afraid it will happen on prod.

Stack:
NextJs@13.2.3
@auth0/nextjs-auth0@2.4.0

Thanks!

### Reproduction

Unsure about the reproduction steps since it seems to happen randomly and it affects all users of the application, this happened to me today, and to one of my clients and we both had to log out and log back in.

Could it be related to the refresh token?

![Screenshot 2023-04-18 at 2 16 10 PM](https://user-images.githubusercontent.com/14078533/232867548-911bb02c-d246-4859-abca-36b50489db78.png)

It seems to be happening after the auth/me call.

### SDK version

@auth0/nextjs-auth0@2.4.0

### Next.js version

NextJs@13.2.3

### Node.js version

16.x

**Comment by adamjmcgrath** [comment]
Hi @mishchief - thanks for raising this

I've not seen this issue before, and I'm not sure how to understand it without a reproducible example or at least seeing a bit more code.

> TypeError: Cannot read properties of undefined (reading 'getHeader')

This would suggest that the response object that we're trying to set the header (the set-cookie header) on is `undefined`

It's a long shot - but the only thing I can think of is that you might be using one of the async api's without await'ing it? Then the lifecycle of the request might be over before `res.getHeader` is called

```js
export default handler = async (req, res) => {
  ...
  /* forgot await */ setSession(req, res, { ... });
}
```

**Comment by adamjmcgrath** [comment]
Possibly related? https://github.com/vercel/next.js/issues/43840

**Comment by mishchief** [comment]
> Hi @mishchief - thanks for raising this
> 
> I've not seen this issue before, and I'm not sure how to understand it without a reproducible example or at least seeing a bit more code.
> 
> > TypeError: Cannot read properties of undefined (reading 'getHeader')
> 
> This would suggest that the response object that we're trying to set the header (the set-cookie header) on is `undefined`
> 
> It's a long shot - but the only thing I can think of is that you might be using one of the async api's without await'ing it? Then the lifecycle of the request might be over before `res.getHeader` is called
> 
> ```js
> export default handler = async (req, res) => {
>   ...
>   /* forgot await */ setSession(req, res, { ... });
> }
> ```

Thanks @adamjmcgrath I don't have any custom setSession call like this so nothing to await.

I followed this guide to set up my [...auth0.js]: https://auth0.com/docs/quickstart/webapp/nextjs/01-login

And I do have some custom logic there:

```
/** 
Implemented using: "Serverless with the user on the backend" 
https://auth0.com/blog/ultimate-guide-nextjs-authentication-auth0/  
This creates the following routes:

/api/auth/login: The route used to perform login with Auth0.
/api/auth/logout: The route used to log the user out.
/api/auth/callback: The route Auth0 will redirect the user to after a successful login.
/api/auth/me: The route to fetch the user profile from.
*/

import { handleAuth, handleCallback } from "@auth0/nextjs-auth0"
import CoreApiClient from "pages/api/clients/CoreApiClient"

const afterCallback = async (req, res, session) => {
  const { user, accessToken } = session

  const userToken = user.sub.split("|")[1]

  const apiOptions = {
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  }

  const apiClient = new CoreApiClient(apiOptions)
  let userResponse

  try {
    userResponse = await apiClient.getUser(userToken)
  } catch (error) {
    console.log(error)
    if (error?.response?.status === 404) {
      userResponse = await apiClient.createUser()
    }
  } finally {
    session.dbUser = userResponse?.data?.user || null
  }
  return session
}

const authOptions = {
  async callback(req, res) {
    try {
      await handleCallback(req, res, { afterCallback })
    } catch (error) {
      console.log(error)
      res.status(error.status || 500).redirect("/api/auth/logout")
    }
  },
}

export default handleAuth(authOptions)
```

Let me know if this helps or you need more info. Thanks so much!

**Comment by mishchief** [comment]
Could it be related to the custom `callback` setting and `afterCallback`? I think for that I followed this documentation: https://auth0.github.io/nextjs-auth0/types/handlers_callback.AfterCallback.html

**Comment by adamjmcgrath** [comment]
Hi @mishchief - I can't see anything wrong with the code you've shared. The response not being available seems more fundamental than an issue with your app or the SDK. It feels more like an issue with Next.js

**Comment by mishchief** [comment]
> Hi @mishchief - I can't see anything wrong with the code you've shared. The response not being available seems more fundamental than an issue with your app or the SDK. It feels more like an issue with Next.js

thanks so much for helping with this! I will close for now and head to nextjs forums for help!
