### ISSUE TITLE
Unable to redirect to a dynamic URL on logout

### ISSUE THREAD

**Issue by lone-cloud** [auth0/nextjs-auth0#117]
The ?redirectTo query param from v0.13.0 does not work for logouts. Also I see that handleLogout() doesn't accept any options making it impossible to redirect the user to a dynamic URL on log-out. This is necessary when redirecting the user back to a locale-specific URL.

**Comment by lone-cloud** [comment]
After some investigation, I see that this is an implementation shortcoming. 
This should not be taking the returnTo value from settings, but a separate options param specific to logout: https://github.com/auth0/nextjs-auth0/blob/master/src/handlers/logout.ts#L13

**Comment by mayatools** [comment]
+1 to having this PR merged please
