### ISSUE TITLE
after login, "expected 200 OK, got: 404 Not Found" on callback

### ISSUE THREAD

**Issue by benevbright** [auth0/nextjs-auth0#1173]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm just opening an issue to save some of people's time since the issue's impact is pretty big and hard to understand.

This issues starts happening since April 22nd around 15:00 CET. 
On every Vercel deployments after that time. 

And you're probably using Sentry. **disabling it does the trick.**

see the thread in:
https://community.auth0.com/t/next-js-client-handleauth-callback-expected-200-but-got-404/105287/15

### Reproduction

-

### SDK version

-

### Next.js version

-

### Node.js version

-

**Comment by NicerDicerPro** [comment]
Can confirm: fixed.
