### ISSUE TITLE
First login time afterRefetch not triggered when using handleProfile with refetch: true

### ISSUE THREAD

**Issue by muradsofi** [auth0/nextjs-auth0#1188]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am trying to use the handleProfile function with `refetch:true` in my implementation. I expect refetch should happen every time when handleProfile is executed. However, when I test it, it seems that the afterRefetch method does not get triggered during the first login time. I want to understand if is it expected behavior or bug.

(I know when the user login first time I can use handleCallback function)

Here's a code snippet illustrating my implementation: 

```
import {
	handleAuth,
	handleLogin,
	handleLogout,
	handleProfile,
	LoginHandlerError,
	LogoutHandlerError,
	ProfileHandlerError,
	Session,
} from '@auth0/nextjs-auth0';

import { someEndpointCallForGetUserData } from '@/some/path';

export default handleAuth({
	async profile(req, res) {
		try {
			await handleProfile(req, res, {
				refetch: true,
				afterRefetch: async (_req, _res, session) => {
					const { user, accessToken } = session;
					try {
						const userData = await someEndpointCallForGetUserData({ accessToken });
						return {
							...session,
							user: {
								...user,
								me: {
									...userData,
								},
							},
						} as Session;
					} catch {
						return session;
					}
				},
			});
		} catch (exception) {
			const error = new ProfileHandlerError(exception);
			res.status(error.status || 500).send(error.message);
		}
	},
});
```

### Reproduction

Please use code snippet provided by me

### SDK version

1.9.2

### Next.js version

12.3.4

### Node.js version

v18.16.0

**Comment by adamjmcgrath** [comment]
Hi @muradsofi - thanks for raising this

> I expect refetch should happen every time when handleProfile is executed

Yes, if you set `refetch: true`, `handleProfile` will refetch every time you call it.

I just tested this on the example app using the code you've shared and every time I hit `/api/auth/me` `afterRefetch` is triggered.

Could you share a repo that demonstrates the issue? Also, I'm not sure what `"it seems that the afterRefetch method does not get triggered during the first login time"` - could you explain more and share some steps to reproduce this scenario?

**Comment by adamjmcgrath** [comment]
Closing as I believe https://github.com/auth0/nextjs-auth0/issues/1188#issuecomment-1536439145 answers your question. Feel free to ping me if you want to reopen
