### ISSUE TITLE
Handle new NextJS API route handling for auth handling

### ISSUE THREAD

**Issue by yafkari** [auth0/nextjs-auth0#1199]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Seems like `handleAuth` does not work with the new way of handling api routes with `NextJS`. See [here](https://nextjs.org/docs/app/building-your-application/routing/router-handlers).

I struggled a couple of hours to try to find a way to make it work, but I just ended up using `next-auth` and use the `Auth0Provider` from there.

### Reproduction

1. Follow the README.md and try to make a login request after doing the "Add the Dynamic API Route" section

### nextjs-auth0 version

2.5.0

### Next.js version

13.4.1

### Node.js version

16.14.0

**Comment by adamjmcgrath** [comment]
Hi @yafkari - thanks for raising this

We are currently prioritising work to support the app directory as part of https://github.com/auth0/nextjs-auth0/issues/1193 - so closing in favour of that
