### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isKeyObject') when using withPageAuthRequired

### ISSUE THREAD

**Issue by majcherpiotrek** [auth0/nextjs-auth0#1205]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I just upgraded the library from `1.9.1` to `2.5.0` and I'm having problems with SSR components. I followed the migration steps and all CSR components are working fine, however wrapping `getServerSideProps` in `withPageAuthRequired` is causing the following error:
```
TypeError: Cannot read properties of undefined (reading 'isKeyObject')
```

I created a following test page:
```typescript
import { withPageAuthRequired } from "@auth0/nextjs-auth0";

type Props = {
    text: string;
};

export const getServerSideProps = withPageAuthRequired({
    getServerSideProps: async () => {
        return {
            props: {
                text: "Hello World",
            },
        };
    },
});

const Test = ({ text }: Props) => <h1>{text}</h1>;

export default Test;
```

and this is my `_app.tsx`:
```
import { ChakraProvider } from "@chakra-ui/react";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import { AppProps } from "next/app";
import { ErrorBoundary, NextPageWithLayout } from "@/packages/app-shell";
import { NotAuthenticatedOverlay } from "@/packages/auth/NotAuthenticatedOverlay";

type AppPropsWithLayout = AppProps & {
    Component: NextPageWithLayout;
};

const App = ({ Component, pageProps }: AppPropsWithLayout) => {
    const getLayout = Component.getLayout ?? ((page) => page);
    const isPublicComponent = Component.isPublic ?? false;
    return (
        <ChakraProvider>
            <ErrorBoundary>
                <UserProvider>
                    {!isPublicComponent && <NotAuthenticatedOverlay />}
                    {getLayout(<Component {...pageProps} />)}
                </UserProvider>
            </ErrorBoundary>

            {/* eslint-disable-next-line react/no-unknown-property */}
            <style jsx global>{`
                #__next {
                    display: flex;
                    flex-direction: column;
                    height: 100vh;
                }
            `}</style>
        </ChakraProvider>
    );
};

export default App;
```

I check for transitive dependencies to `@auth0/nextjs-auth0` in all of the imports in `_app.tsx` and there are none, there is only a dependency on `@auth0/nextjs-auth0/client`.

### Reproduction

1. Upgrade `@auth0/nextjs-auth0` from `1.9.1` to `2.5.0` in next app.
2. Create a page with a SSR component with its `getServerSideProps` wrapped in `withPageAuthRequired` imported from `@auth0/nextjs-auth0`
3. Getting error TypeError: Cannot read properties of undefined (reading 'isKeyObject')

### nextjs-auth0 version

2.5.0

### Next.js version

12.3.4

### Node.js version

18.6.0

**Comment by adamjmcgrath** [comment]
Hi @majcherpiotrek - thanks for raising this

Our example app has a similar page to your test page https://github.com/auth0/nextjs-auth0/blob/main/examples/kitchen-sink-example/pages/profile-ssr.tsx and doesn't have this issue.

It's usually caused by importing the server part of the SDK into a client part of your app, but I can't see anything in the code you've shared that would cause this.

Could you provide the stack trace and ideally an example repo that demonstrates the issue, then I'd be happy to debug it for you.

**Comment by majcherpiotrek** [comment]
I came back to the topic today and rebuilt the `yarn.lock` and reinstalled the deps and it started working. Hard to say what was the issue, thanks for having a look at it anyway!
