### ISSUE TITLE
Docs for "Hosting on Vercel > Preview Deployments" no longer work

### ISSUE THREAD

**Issue by mattrossman** [auth0/nextjs-auth0#1206]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The docs say that for Vercel Preview deployments you should set:

```env
# .env.production
NEXT_PUBLIC_AUTH0_BASE_URL=$VERCEL_URL
```

[(source)](https://github.com/auth0/nextjs-auth0/blob/5989b327c38a983911a6007766a1cd2fac91363a/examples/README.md#preview-deployments)

When I do this, I get a 500 error saying that `baseURL` is required. Even though I can see that `NEXT_PUBLIC_AUTH0_BASE_URL` is correctly set in my logs, the library seems to not recognize it.

Additionally, the docs suggest that you can use $VERCEL_BRANCH_URL for branch preview URLs, however this variable is undefined and I can't find it mentioned in the [Vercel System Environment Variables](https://vercel.com/docs/concepts/projects/environment-variables/system-environment-variables) (perhaps deprecated?)

### Reproduction

1. Clone sample app https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01
2. Assign  "Preview" environment variables on Vercel, with exception of `AUTH0_BASE_URL`
3. Add `.env.production` file as shown above
4. Configure Auth0 to allow `*.vercel.app` callback URLs / logout URLs
5. `npx vercel deploy` and follow prompts
6. Open preview URL and attempt login

### Additional context

If I change the `.env.production` file to set `AUTH0_BASE_URL`  instead of `NEXT_PUBLIC_AUTH0_BASE_URL` then I can log in as expected (only on "commit" style preview URLs, not the branch preview URLs)

I'm not sure why this happens because this library appears to check both variables:

https://github.com/auth0/nextjs-auth0/blob/5989b327c38a983911a6007766a1cd2fac91363a/src/config.ts#L492

Perhaps the environment variables behavior has changed in recent Next.js versions.

### nextjs-auth0 version

2.5.0

### Next.js version

13.4.1

### Node.js version

18.16.0

**Comment by mattrossman** [comment]
Looks like this PR was very recent so maybe these docs are just ahead of the latest release? https://github.com/auth0/nextjs-auth0/pull/1198

**Comment by adamjmcgrath** [comment]
Hi @mattrossman - thanks for raising this

Yep, I'll do a release of `2.6` today to catch up with those docs changes
