### ISSUE TITLE
What is the best way to do silent authentication in V2?

### ISSUE THREAD

**Issue by SamRoehrich** [auth0/nextjs-auth0#1207]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would like a way to do silent authentication in the V2 of this SDK. I read [this thread](https://github.com/auth0/nextjs-auth0/issues/44) from 2019 but I this solution is raising my vercel usage as I call `handleLogin` every minute.
Is there a better option now in V2 with methods like `touchSession` or `updateSession`?

### Describe the ideal solution

I would like a way to write a custom API route that will update my session without calling the base url of my application.

### Alternatives and current workarounds

2019 thread - https://github.com/auth0/nextjs-auth0/issues/44

**Comment by adamjmcgrath** [comment]
Hi @SamRoehrich - thanks for raising this

If you want to update an existing session, you can make a request to the `/userinfo` endpoint, like so:

```js
// A an api route that updates the session `/api/auth/update-session`
export default handleAuth({
  'update-session': handleProfile({ refetch: true });
})
```

If you want to check the authorization server for if you have a session, you need to visit it with a login (you can use `prompt=none` to fail silently if the user doesn't have a session)

```js
// A an api route that does silent auth `/api/auth/silent-login`
export default handleAuth({
  'silent-login': handleLogin({ authorizationParams: { prompt: 'none' } });
})
```

`touchSession` and `updateSession` only operate on the Application Session Layer they don't check the Auth0 Session Layer (see https://auth0.com/docs/manage-users/sessions/session-layers)

**Comment by SamRoehrich** [comment]
Thanks @adamjmcgrath. Follow up question 
When I call `handleProfile` the `accessTokenExpiresAt` claim does not update. If I wanted to update that so that the user session expiration is pushed back one minute would I do something like this?

```
afterRefetch: (req, res, session) => {
	const updatedAccessToken = session.accessTokenExpiresAt + 6000
	return {
		...session,
		accessTokenExpiresAt: updatedAccessToken,
	}
},

**Comment by adamjmcgrath** [comment]
Hi @SamRoehrich 

Fetching a new user profile from `/userinfo` wont get you a new access token, so the expiry of your access token wont change.

You need to use `getAccessToken({ refresh: true })` to get a new access token.

**Comment by adamjmcgrath** [comment]
Closing as I believe https://github.com/auth0/nextjs-auth0/issues/1207#issuecomment-1549944327 answers your question

**Comment by otech47** [comment]
> If you want to check the authorization server for if you have a session, you need to visit it with a login (you can use prompt=none to fail silently if the user doesn't have a session)
> 
> ```
> // A an api route that does silent auth `/api/auth/silent-login`
> export default handleAuth({
>   'silent-login': handleLogin({ authorizationParams: { prompt: 'none' } });
> })
> ```

This doesn't seem to work out of the box without additional CORS config. I get 

```
Access to fetch at 'https://<domain>.auth0.com/authorize?client_id=...&scope=openid%20profile%20email&response_type=code&redirect_uri=https%3A%2F%2F<site_url>%3A5100%2Fapi%2Fauth%2Fcallback&audience=postgraphile&prompt=none&nonce=...&state=...&code_challenge=...&code_challenge_method=S256' (redirected from 'https://<site_url>/api/auth/silent-login') from origin 'https://<site_url>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

any idea what might be missing?

**Comment by SamRoehrich** [comment]
```
// A an api route that does silent auth `/api/auth/silent-login`
export default handleAuth({
  'silent-login': handleLogin({ authorizationParams: { prompt: 'none' } });
})
```

@adamjmcgrath I don't understand how this works. If I call this api route from my frontend I get the same cors error @otech47 got. My old implementation made this call in an iframe but I would like to remove that iframe, is it possible to make this call from my frontend without an iframe and not get a cors error?

**Comment by SamRoehrich** [comment]
I figured out a solution that works for me.

There is a fetch call to `handleProfile` on my frontend. There is also a call to `checkSession` in the same component. The call to `checkSession` happens before calls to `handleProfile` so if the user token is expired they will get logged out, else they will refresh.

**Comment by reubenjh** [comment]
Just wanted to add to this in case it helps someone - spent a couple days going around in circles trying to get session sharing as good as possible between different sites on my domain using applications on the same tenant.

I wanted to have silent authentication happen automatically so users bouncing between my sites are logged in in them all. However, its not really viable without making a request to the Auth0 server, which would require me attempting silent auth on every page load - not a good idea.

I ended up setting up a proxy api route at `/api/auth/silent` on my auth0 handler that takes in a `redirect` query param and fires off a login attempt with prompt='none' with that redirect url set as the `returnTo` on the authorization request. I use this proxy when linking between my sites, so they go through silent auth then get redirected to the target page. e.g. `api/auth/silent?redirect=/potato` to auth them on their way to `/potato`.

When it comes back through my auth callback handler I detect the specific error codes for a failed silent auth situation and just swallow the error, redirecting them to the returnTo route anyway.

Hopefully this helps someone, you should be able to follow the same pattern for any server side auth0 SDK that has some way to do silent authentication, or for browser based auth SDK’s they expose a checkSession method that you could use from the client app to do the same thing without needing a proxy api.

**Comment by benevbright** [comment]
```
// A an api route that updates the session `/api/auth/update-session`
export default handleAuth({
  'update-session': handleProfile({ refetch: true });
})
```
```
  const { user, checkSession } = useUser();

  const handleUpdateUser = async (data: { name: string }) => {
    await updateUser(data);

    // refetch profile and get user in session updated (user in useUser)
    await fetch("/api/auth/update-profile");
    await checkSession();
  };
```

**Comment by Avital103** [comment]
@reubenjh, I appreciate your explanation. However, there are two specific points I'm still unclear about:

1. Could you please provide details on where the `api/auth/silent` is triggered in the application for each route? Are you using middleware for this purpose? If so, could you share the relevant code snippet?

2. In cases where the silent login fails with the `login_required` error, what condition should be met to prevent further calls to `api/auth/silent`? I'd prefer not to rely on managing cookies or session storage for this. 

@adamjmcgrath, I'm curious if there's a way to access the [Auth0 Session Layer](https://auth0.com/docs/manage-users/sessions/session-layers#:~:text=inside%20a%20cookie.-,Auth0%20Session%20Layer,-%3A%20Auth0%20also%20maintains). It would be helpful to determine whether there's a possibility for the silent login to function properly.

Thank you for your assistance.

**Comment by reubenjh** [comment]
> @reubenjh, I appreciate your explanation. However, there are two specific points I'm still unclear about:
> 
> 1. Could you please provide details on where the `api/auth/silent` is triggered in the application for each route? Are you using middleware for this purpose? If so, could you share the relevant code snippet?
> 2. In cases where the silent login fails with the `login_required` error, what condition should be met to prevent further calls to `api/auth/silent`? I'd prefer not to rely on managing cookies or session storage for this.

Handler code in pages/api/auth/[...auth0.tsx]:
```
 export default handleAuth({
  
  ... any other custom handlers you have...
  
  async silent(req: NextApiRequest, res: NextApiResponse) {
    const redirectUrl = (req.query.redirect ?? '/') as string;
    try {
      await handleLogin(req, res, {
        returnTo: redirectUrl,
        authorizationParams: { prompt: 'none' },
      });
    } catch (error) {
      console.error('bla bla bla', error);
      res.redirect(redirectUrl);
    }
  },
})
```

Triggering code:
In Application A if I want to go to page /potato in Application B and retain the login session, link to `https://applicationb.com/api/auth/silent?redirect=potato`

That will trigger the silent auth handler to attempt a login. If it fails, it will take them to /potato not logged in, if it succeeds, it will take them to /potato logged in. 

Hopefully that answers the question. There's no handling of the error here to prevent further calls like you mention since this is only triggered on that link from my own Application A. No cookies or session voodoo required. It's not the greatest solution but does the trick for now

**Comment by midastouchprd** [comment]
To anybody that's on this an important thing being left out is

is you have to browser navigate to the new `silent-login` route inbetween the page that needs the updated info

My flow is 
1. User sign up 
2. Created in Auth0
3. chooses a program
4. added to an organization in auth0
5. update use metadata with important program info
6. lands on program page dashboard and needs the updated metadata

on the action at 3 there's a silent auth push that redirects to action 6
 `push('/api/auth/silent-login?returnTo=/dashboard');`
 
 this will land me on dashboard with updated metadata.

**Comment by OttlikG** [comment]
For me the important bit was to use `push` instead of `fetch` for calling the `silent-login` endpoint.

```router.push('/api/auth/silent-login');```

**Comment by gabor-at-reed** [comment]
How does this work in the new, v4?
