### ISSUE TITLE
email_verified returns incorrect value

### ISSUE THREAD

**Issue by attilaking** [auth0/nextjs-auth0#1215]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi guys, looks like the `useUser` hook returns incorrect value for `email_verified`. In Auth0 dashboard, the `email_verified` for the user is clearly true, but `useUser` is always returning false. This has been reported by other users too. 
https://community.auth0.com/t/auth0-console-says-email-is-verified-but-auth0-user-in-app-says-email-verified-false/58728/4
<img width="1028" alt="Screenshot 2023-05-22 at 7 33 50 pm" src="https://github.com/auth0/nextjs-auth0/assets/36627158/c9010308-fc67-48cd-ad8d-f26d85854b81">
<img width="1201" alt="Screenshot 2023-05-22 at 7 23 23 pm" src="https://github.com/auth0/nextjs-auth0/assets/36627158/32f6536c-b46d-472a-81fb-25a1befed71d">

### Reproduction

1. Get a user that have their email verified in `auth0`
2. use the `useUser` hook to get user data. 
3. Observe how `email_verified` is true in Auth0 but false in the data returned by `useUser`

### nextjs-auth0 version

2.2.2

### Next.js version

13.3.0

### Node.js version

18.14.0

**Comment by adamjmcgrath** [comment]
Hi @attilaking - thanks for raising this

`useUser` reflects the claims of the ID token when the user last logged in.

In this case it's likely that `email_verified` was false when the user logged in, if the user logs in again the `email_verified` claim should get updated,

**Comment by adamjmcgrath** [comment]
Closing as I believe https://github.com/auth0/nextjs-auth0/issues/1215#issuecomment-1562443513 answers your question

**Comment by gaborvecsei** [comment]
@adamjmcgrath What is the best practice to refresh the user data in this case?
