### ISSUE TITLE
withPageAuthRequiredSSR doesn't seem to respect a base path

### ISSUE THREAD

**Issue by OliverDudgeon** [auth0/nextjs-auth0#1217]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

From the source code, withPageAuthRequiredSSR defaults to `ctx.resolvedUrl` when no `returnTo` is provided. Currently, in my app I have a `next.config.js` with a `basePath`. It seems that `ctx.resolvedUrl` doesn't include this base path, just the path within the pages/app directory. 

### Reproduction

```
// next.config.mjs
const config = {
basePath: "/my-app"
}

export default config
```

```
// pages/protected.tsx
import { withPageAuthRequired as withPageAuthRequiredSSR } from "@auth0/nextjs-auth0";
import { withPageAuthRequired as withPageAuthRequiredCSR } from "@auth0/nextjs-auth0/client";

export const getServerSideProps = withPageAuthRequiredSSR({
  getServerSideProps: () => {/* do something */}
})

const ProtectedPage = () => {
  return <div />
}

export default withPageAuthRequiredCSR(ProtectedPage );
```

Visit the protected page and you will redirect to `/protected`, a 404, and not `/my-app/protected` as expected.

### nextjs-auth0 version

2.6.0

### Next.js version

13.4.1

### Node.js version

18.12.1

**Comment by adamjmcgrath** [comment]
Hi @OliverDudgeon - thanks for raising this

This is a known issue with base path routing and withPageAuthRequired (SSR)- Have a look at this section of the README https://github.com/auth0/nextjs-auth0#base-path-and-internationalized-routing (The section that starts "For any pages that are protected with the Server Side withPageAuthRequired ...")

**Comment by OliverDudgeon** [comment]
Ok thanks for that, I missed that part of the docs. Is there plans to have this done automatically or is it impossible to catch all cases?

```
const getFullReturnTo = (ctx) => {
  // TODO: implement getFullReturnTo based on the ctx.resolvedUrl, ctx.locale
  // and your next.config.js's basePath and i18n settings.
  return '/foo/en-US/my-ssr-page';
};

export const getServerSideProps = (ctx) => {
  const returnTo = getFullReturnTo(ctx.req);
  return withPageAuthRequired({ returnTo })(ctx);
};
```

I have a memory that before v2, it worked without this? Did something change?

**Comment by adamjmcgrath** [comment]
> Is there plans to have this done automatically

@OliverDudgeon - we may look at this again in the future - but no concrete plans at the moment

> I have a memory that before v2, it worked without this? Did something change?

AFAIK Nothing has changed between v1 and v2 - see the v1 docs for example https://github.com/auth0/nextjs-auth0/tree/v1.9.3#base-path-and-internationalized-routing
