### ISSUE TITLE
Sessions never times out nor invalidates after shutting down the browser

### ISSUE THREAD

**Issue by don-esteban** [auth0/nextjs-auth0#1219]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi all,

we have a Next.js app and need to add authentication/authorization. I started with Auth0 evaluation yesterday and probably missing the point completely. Please be patient.

I cloned the example and published the app unmodified here: [My app Next.js/Auth0 example app](https://my-app-zeta-nine.vercel.app). It's [at GitHub too](https://github.com/don-esteban/my-app).

Actually, I did it with two versions. With the basic-example in this repos example folder and with the starter app, which can be downloaded from the Auth0 dashboard of the application.

**Issue: Sessions never time out nor invalidate after shutting down the browser.**

I checked [this community post](https://community.auth0.com/t/why-users-remain-login-after-the-inactivity-timeout/87161) unsuccessfully. All the settings simply do not change anything. Non-persistent sessions neither work.

I used Chrome, Firefox and Safari on macOS. A colleague checked on MS Windows.

[See this community discussion too. ](https://community.auth0.com/t/sessions-never-times-out-nor-invalidates-after-shutting-down-the-browser/108046)

Thanks for any help.

### Reproduction

1. [Go to this app](https://my-app-zeta-nine.vercel.app/) (clone of the downloaded starter app at Dashboard → Applications → My App → Quick Start tab).
1. Register/login
1. Shutdown browser
2. Reopen browser. Still logged in. (Tenant No Persistent Session enabled)
3. Wait for one or two minutes. Close, open browser. Still logged in. Inactivity timeout and Require log in after set to 1 Minute.

### Additional context

Nothing. It's an unmodified clone of the mentioned starter app.

### nextjs-auth0 version

"@auth0/nextjs-auth0": "^2.0.0",

### Next.js version

"next": "^13.1.0",

### Node.js version

v18.16.0

**Comment by adamjmcgrath** [comment]
Hi @don-esteban thanks for raising this

By default the cookie is not set as a [session cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_the_lifetime_of_a_cookie:~:text=Session%20cookies%20are%20deleted%20when%20the%20current%20session%20ends)

 If you want to set the cookie to expire when the browser session ends, you can set the [transient cookie option](https://auth0.github.io/nextjs-auth0/interfaces/config.CookieConfig.html#transient) to `true` (`AUTH0_COOKIE_TRANSIENT=true` if you're using env vars to configure the SDK)

**Comment by adamjmcgrath** [comment]
Closing - as I believe https://github.com/auth0/nextjs-auth0/issues/1219#issuecomment-1574063191 answers your question

**Comment by don-esteban** [comment]
Hi and sorry for the late feedback. Thanks. This resolves the issue. Especially the link to the docs was helpful! With that information, I could manage all session needs we have. I'm still confused about the (for me) not working dashboard configuration, but further reading/practice certainly will resolve this too. No additional help required for the moment. Thanks.
