### ISSUE TITLE
Add loginUrl to WithPageAuthRequiredOptions

### ISSUE THREAD

**Issue by rhysawilliams2010** [auth0/nextjs-auth0#1222]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I have a couple of areas of my nextjs app that I want to use different login urls for. I want to use `next-js/auth0` `withPageAuthRequired` server and client side using a different `loginUrl`.

I want to reuse the same api routes and imports where possible.

The problem is that I can't change the loginUrl at runtime as the client and server side both read the loginUrl from environment variables. I know I can configure `loginUrl` if I use `initAuth`, but I want to be able to reuse my auth instance between areas of the site. 

### Describe the ideal solution

The ideal solution is that you add `loginUrl` to client and server `WithPageAuthRequiredOptions` & 'withMiddlewareAuthRequired' so I can override at run time. 

E.g.

Server
```
export const getServerSideProps = withPageAuthRequired({loginUrl: '/area-a/login'})
```

Client
```
export default withPageAuthRequired(Component, {loginUrl: '/area-b/login'})
```

### Alternatives and current workarounds

At the moment I have copied the code for the HOCs locally and added an option.

**Comment by rhysawilliams2010** [comment]
Sorry, I have found that I really don't need this.

**Comment by adamjmcgrath** [comment]
Thanks for sharing your use case @rhysawilliams2010 - we'll consider this. Please continue to use your workaround for now.

**Comment by adamjmcgrath** [comment]
@rhysawilliams2010 After consideration, we've decided not to support this use case - we will however continue to monitor demand. `withPageAuthRequired` is a simple module that you can create yourself to if you want to customise the default redirect behaviour.

**Comment by spicattutti** [comment]
Where can I upvote this?

We also don't want t he SDK to reside under `<app-origin>/api/auth` but on another route like just `<app-origin>/auth`, as `/api` is an existing route that proxies requests to a backend API.
