### ISSUE TITLE
Module parse failed: Identifier 'NextResponse' has already been declared (3:6) in Next.js 13.4.4

### ISSUE THREAD

**Issue by jonahallibone** [auth0/nextjs-auth0#1223]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

```
- wait compiling /src/middleware (client and server)...
- error ./node_modules/@auth0/nextjs-auth0/dist/helpers/with-middleware-auth-required.js
Module parse failed: Identifier 'NextResponse' has already been declared (3:6)
| "use strict";
| const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
> const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
| const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
| const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;

Import trace for requested module:
./node_modules/@auth0/nextjs-auth0/dist/helpers/with-middleware-auth-required.js
./node_modules/@auth0/nextjs-auth0/dist/edge.js
./src/util/auth0-edge.ts
```

Since upgrading to Next.js 13.4.4, `initAuth0` no longer works.

My `auth0-edge.ts.` looks like this:
```
import { initAuth0 } from "@auth0/nextjs-auth0/edge";
import getEnvUrl from "./get-env-url";

const auth0 = initAuth0({
  baseURL: getEnvUrl(),
});

export default auth0;
```

### Reproduction

1. Upgrade to Next.js `13.4.4`
2. Try to to use `import { initAuth0 } from "@auth0/nextjs-auth0/edge";` in your app

### nextjs-auth0 version

2.6.0

### Next.js version

13.4.4

### Node.js version

20.1.0

**Comment by jonahallibone** [comment]
See elsewhere that this issue will be fixed in an upstream Next.js release. Keeping open for visibility in case someone else runs into the same issue. Feel free to close however

https://github.com/nextauthjs/next-auth/issues/7650#issuecomment-1571768250

**Comment by adamjmcgrath** [comment]
Thanks for raising the @jonahallibone - see also https://github.com/auth0/nextjs-auth0/issues/1218#issuecomment-1567957319
