### ISSUE TITLE
How to request for Third party refresh tokens

### ISSUE THREAD

**Issue by kamalsingh200238** [auth0/nextjs-auth0#1225]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

- I authenticate my users using Google provider.
- I want to get the refresh token provided by Google( not by Auth0 ). 
- And to get that refresh token I have to include ```access_type=offline``` when I make the request to ```/authorize``` endpoint. (I don't know how to make that request)
Link to auth0 docs explaining more on how to Renew third-party tokens: https://auth0.com/docs/secure/tokens/access-tokens/identity-provider-access-tokens#renew-third-party-tokens
# But there is no documentation on how to do that with this SDK package.
Can you please help me out

### Reproduction

1. Try to authenticate the user with Google provider
2. When you get the full user info from ```/users/{id}```. You don't get the refresh token provided by Google in identities array.

### nextjs-auth0 version

2.6.0

### Next.js version

13.4.3

### Node.js version

20.X

**Comment by ssudaraka** [comment]
To get the third-party identity provider's access tokens, you must call the Auth0 Management API's Get User endpoint `/api/v2/users/`. You will find the identity provider's tokens in the `identities` array if the identity provider supports it (Google supports it) - https://auth0.com/docs/secure/tokens/access-tokens/identity-provider-access-tokens.

You will have to implement your own method to call the Auth0 Management API and retrieve the third-party identity provider tokens. This looks like a good to have feature, though.

**Comment by kamalsingh200238** [comment]
Thanks for the reply @ssudaraka. 
I understand that I will get the refresh token from the `identities` array when I call Auth0 Management API `/api/v2/users`.
But Auth0 doesn't get the refresh token from the identity provider by default. I have to pass `access_type=offline` when I authenticate the user.
But I cannot where I have to apply this setting using this SDK.
Read more about it here: https://auth0.com/docs/secure/tokens/access-tokens/identity-provider-access-tokens#renew-third-party-tokens

**Comment by adamjmcgrath** [comment]
Hi @kamalsingh200238 - to pass custom arguments to the `/authorize` endpoint at login, use the [`authorizationParams` ](https://auth0.github.io/nextjs-auth0/interfaces/handlers_login.LoginOptions.html#authorizationParams) option of `handleLogin` - you can see an example of this here: https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#customize-handlers-behavior

**Comment by kamalsingh200238** [comment]
Hi, @adamjmcgrath Thanks a lot for the help. It worked!
Now I'm getting refresh token provided by Google in the `identities` array.
What I did: 
```ts
import { handleAuth, handleLogin } from "@auth0/nextjs-auth0";

export default handleAuth({
  login: handleLogin({
    authorizationParams: {
      access_type: "offline",
      prompt: "consent",
    },
  }),
});

```

**Comment by cjsauer** [comment]
Okay, of course the moment I post that I believe I've figured it out. It seems my `connection_scope` was including a service API that didn't have credentials set up in the Google Cloud backend. Apologies for the noise, and thanks for the reference code above 🙏
