### ISSUE TITLE
Refresh token missing in session

### ISSUE THREAD

**Issue by kokipsiho** [auth0/nextjs-auth0#123]
### Description

Refresh token is missing in object returned from `getSession` method. This makes it impossible to get new access token. Example in documentation always returns 

### Reproduction

- Cofigure session with `storeRefreshToken: true`
- Session object does not contain refresh token

**Comment by tomclark** [comment]
Hi, I'm afraid I can't help, but I just opened #128 which sounds a little similar but is a rather more fundamental problem in that no session is created at all if I configure the session with ```storeAccessToken``` in versions later than 0.7.0. Might it be worth checking whether you see this issue in 0.7.0?

**Comment by pstoica** [comment]
Just ran into this and figured it out. Apparently you need to use the `offline_access` scope?

https://github.com/auth0/nextjs-auth0/issues/4#issuecomment-535039547

**Comment by Widcket** [comment]
Indeed, you need to add `offline_access` to the list of scopes. Thanks @pstoica
