### ISSUE TITLE
Custom SessionStore not working in middleware

### ISSUE THREAD

**Issue by andrienpecson** [auth0/nextjs-auth0#1232]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am currently implementing a custom SessionStore to bypass the large cookie issue. In the `auth0.ts`, I am using `ioredis` as the Redis library. The problem is that I am encountering an issue when NextJs is generating the pages.

### Reproduction

**auth0.ts**
```
import { Auth0Server, initAuth0 } from '@auth0/nextjs-auth0';
import config from './auth0Config';

let _auth0: Auth0Server;

export default function auth0() {
  if (!_auth0) {
    _auth0 = initAuth0(config);
  }
  return _auth0;
}
```

**auth0Config**
```
import Redis from "ioredis";
import { SessionStorePayload, SessionStore, Auth0Server, initAuth0 } from '@auth0/nextjs-auth0';

const redis = new Redis(process.env.REDIS_URL!);

class Store implements SessionStore {
  private redis: Redis;

  constructor() {
    this.redis = redis;
  }

  async get(id: string) {
    const payload = await this.redis.get(id);
    return (payload) ? JSON.parse(payload) : null
  }
  async set(id: string, val: SessionStorePayload) {
    // Set the expiry of the store entry to match the expiry of the session.
    const expiryMs = val.header.exp * 1000;
    await redis.set(id, JSON.stringify(val), 'PX', expiryMs);
  }
  async delete(id: string) {
    await this.redis.del(id);
  }
}

const config = {
  session: {
    store: new Store(),
  },
};

export default config;
```

**middleware.ts**
```
import { NextRequest, NextResponse } from 'next/server';
import { initAuth0 } from '@auth0/nextjs-auth0/edge';
import auth0Config from "@/src/lib/auth0Config";

const auth0 = initAuth0(auth0Config);

export async function middleware(req: NextRequest) {
  const res = NextResponse.next();
  const user = await auth0.getSession(req, res);
  const urlObj = new URL(req.url);

  let returnResponse: NextResponse | Response = res;

  if ((urlObj.pathname.includes("api/auth") || urlObj.pathname.includes("api/login")) || user) {
    if (urlObj.pathname == "/") {
      returnResponse = NextResponse.redirect(new URL("/dashboard", req.nextUrl));
    }
  } else {
    returnResponse = NextResponse.redirect(new URL("/api/auth/login", req.nextUrl));
  }
  
  return returnResponse;
}

export const config = {
  matcher: [
    '/',
    '/api/:path*',
    '/dashboard/:path*',
    '/team/:path*',
    '/shop/:path*',
  ]
};
```

**Issue**
![Screenshot 2023-06-08 at 18 13 21](https://github.com/auth0/nextjs-auth0/assets/13114319/9bae6d55-3bf2-4c8a-bc49-bc0debee3c80)

### nextjs-auth0 version

2.4.0

### Next.js version

13

### Node.js version

16.16.0

**Comment by Widcket** [comment]
Hi @andrienpecson, thanks for raising this.

This error seems to be a matter of compatibility of the Redis library you're using with the Edge runtime. Not sure this is a SDK issue.

**Comment by adamjmcgrath** [comment]
Yep - `ioredis` [requires the Node.js runtime](https://github.com/luin/ioredis#:~:text=A%20robust%2C%20performance%2Dfocused%20and%20full%2Dfeatured%20Redis%20client%20for%20Node.js.) (see also https://github.com/luin/ioredis/issues/769#issuecomment-1480869051)

**Comment by andrienpecson** [comment]
What Redis library do you recommend?

**Comment by adamjmcgrath** [comment]
@andrienpecson - I used `@upstash/redis` when I was testing it in https://github.com/adamjmcgrath/nextjs-auth0-redis-session

Any storage client that works on Vercel's Edge runtime will work.

**Comment by andrienpecson** [comment]
@adamjmcgrath I was able to set up a custom session store but the problem is that is it really expected that `SessionStore.set` is called multiple times? I am encountering this problem which causes also an override of the old session to the updated session in `SessionStore.set`.

**Comment by johnbellone** [comment]
I am seeing this error running locally on my laptop.
