### ISSUE TITLE
v3 Beta

### ISSUE THREAD

**Issue by adamjmcgrath** [auth0/nextjs-auth0#1235]
v3 of this SDK is now available on Beta.

The main update is support for Next.js 13.4's [App Router](https://nextjs.org/docs/app)

> **Edit:** https://github.com/auth0/nextjs-auth0/releases/tag/v3.0.0-beta.3 adds full support for the Edge runtime

To install:

```bash
$ npm i @auth0/nextjs-auth0@beta
```

For more information about how to use the SDK in the app directory, see these resources:

- Basic setup: https://github.com/auth0/nextjs-auth0/tree/beta#app-router (note the section on [App Router limitations](https://github.com/auth0/nextjs-auth0/tree/beta#important-limitations-of-the-app-directory))
- Example app:
  - [The auth handlers route](https://github.com/auth0/nextjs-auth0/blob/beta/example-app/app/api/auth/%5Bauth0%5D/route.ts)
  - [Protecting a page](https://github.com/auth0/nextjs-auth0/blob/beta/example-app/app/profile/page.tsx) (note [returnTo limitations](https://github.com/auth0/nextjs-auth0/blob/beta/src/helpers/with-page-auth-required.ts#L145))
  - [Protecting an API](https://github.com/auth0/nextjs-auth0/blob/beta/example-app/app/api/profile/route.ts)
  - [Usage in a server component](https://github.com/auth0/nextjs-auth0/blob/beta/example-app/app/server-component.tsx)
  - [Usage in a client component](https://github.com/auth0/nextjs-auth0/blob/beta/example-app/app/client-component.tsx)

If you notice any problems, please raise a new issue with the `beta` label

**Comment by tomsseisums** [comment]
Would using the middleware automatically refresh tokens?

**Comment by lostinpatterns** [comment]
Thanks for shipping this update! 🎉 Just to follow up on what Tom said, it'd be great to get some guidance/workarounds on ways to mitigate those limitations. Seeing as the App Router is the future of next.js, it's safe to assume most people will move to adopt it and certainly new projects will be built on it by default. If they also want to adopt Auth0, the question then is how to make that work.

In our case, we refresh our access tokens, so it'd be great to know how to work around this so that we aren't refreshing on every server page render once the access token has expired (which is what sounds like will happen). If the answer to @tomsseisums question is yes then we'd be happy to deploy that as a solution!

**Comment by jalvarado91** [comment]
Thank you for the swift beta release. I have two things, I can open separate issues if needed:

1. The example app in the repo sets up middleware which is what I'd prefer to use, however the example app seems to be using both pages and app dir, and points the middleware initialization to the pages router version of the login. At first glance I thought I was supposed to use both pages and app /api/auth/[auth0] handlers to get the middleware to work. Would be nice to have an app router only example. 

2. I was testing the beta on a app router only app I'm working on and haven't been able to get it to work. I started a new fresh nextjs app with all the default (app router checked), installed the beta, set up the auth0 api handler, the `UserProvider` in the root layout, and the client component sample from the read me and I'm running into the following error basically at load time, not being able to continue at all. 

```
./node_modules/@auth0/nextjs-auth0/dist/handlers/profile.js
Module parse failed: Identifier 'NextResponse' has already been declared (3:6)
| "use strict";
| const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
> const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
| const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
| Object.defineProperty(exports, "__esModule", {
```

![image](https://github.com/auth0/nextjs-auth0/assets/1750392/0b965df8-c2c7-43e6-90f1-3f16b8c04de5)

Seems like maybe it's related to the building?

**Comment by adamjmcgrath** [comment]
@jalvarado91 - see https://github.com/auth0/nextjs-auth0/issues/1218#issuecomment-1567957319

**Comment by danlutz** [comment]
Great work on the beta!
Will it be possible to use both pages and app router, both using auth0 and the respective api route?

**Comment by lewisking** [comment]
Thanks of the work on the beta. However, I get 500 errors whenever I visit any auth route after setting up the route.js file in the correct place. Any ideas how I can debug? I can't even get anything logging in console.

**Comment by ZainChen** [comment]
I'd like to ask when v3 is expected to be released, I'm using the Beta version and the convenience of getting the AccessToken in the server component is a particularly useful feature for me.

**Comment by adamjmcgrath** [comment]
> Will it be possible to use both pages and app router, both using auth0 and the respective api route?

@danlutz, yes - the [example app](https://github.com/auth0/nextjs-auth0/tree/beta/example-app) uses both the app router and the page router

> I get 500 errors whenever I visit any auth route after setting up the route.js file in the correct place. Any ideas how I can debug?

@lewisking - the SDK should log errors to the console by default. If you're not even getting those you must have a more fundamental issue. Raise a new gh issue and share a reproducible example and I'd be happy to investigate.

> I'd like to ask when v3 is expected to be released

@ZainChen (any to any future questions about release timing) - I can't give you a release date, but it will be at least 2 - 3 weeks away.

**Comment by lewisking** [comment]
@adamjmcgrath thanks Adam, was going to create one but just seen @jalvarado91 has created one in the meantime. Let's track the issues there as it's exactly what I'm getting.

**Comment by lgariv** [comment]
Works beautifully with my next 13.4.5 project! Haven't noticed any bugs yet, will report if I will

**Comment by DotCoyote** [comment]
Same here, server-components work like a charm! How do I get the accessToken from a client-component now, though? 🙈 
Do I need to pass it down from the server?

Background: I want to connect to an external API with a Bearer token from auth0. Do I need to create proxy-routes now?

**Comment by lewisking** [comment]
Can I use getSession in middleware? I get the following error:

`Server Error
TypeError: Cannot read properties of undefined (reading 'substring')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
node_modules/oidc-token-hash/lib/shake256.js (3:0)
substring
node_modules/oidc-token-hash/lib/shake256.js (3:39)`

**Comment by brunoscopelliti** [comment]
@lewisking See this one: https://github.com/auth0/nextjs-auth0/issues/1247

**Comment by brunoscopelliti** [comment]
Hi @adamjmcgrath 

Could you please give an example of how to use `updateSession`?
This is what I've tried:

```js
export const GET = withApiAuthRequired(
  async (request: NextRequest, _context: RouteContext) => {
    try {
      const session = await getSession();

      const response = NextResponse.redirect(new URL("/destination", request.url));

      await updateSession(request, response, { ...session, user: { ...session?.user, name: "UPDATED" } });

      return response;
    } catch (error: any) {
      // Handle error
    }
  }
);
```

But it doesn't seem to work; the redirect happens, but the session is unchanged.

**Comment by adamjmcgrath** [comment]
@brunoscopelliti - thanks for raising that

Your example should work, but there's an issue with `withApiAuthRequired` overwriting the "appSession" cookie (if you remove `withApiAuthRequired` your example will work)

I'll raise some work to fix this in the next Beta update

**Comment by BRGustavoRibeiro** [comment]
Hi everyone! I apologize in advance if this isn't the appropriate place to post my question.

I'm currently working on a new project using Next.js and I'm trying to implement both Auth0 SDK and _next-intl_ simultaneously. However, I've encountered an issue where both libraries require exporting _something_ in the middleware. I need to incorporate Auth0 into the middleware to protect all routes.

I've made several attempts, but I haven't been successful in getting both libraries to work together.

Here's the code that next-intl needs to export:

```javascript
export default createMiddleware({
  locales: ["pt-br"],
  defaultLocale: "pt-br",
});

export const config = {
  matcher: ["/((?!api|_next|.*\\..*).*)"],
};
```

And here's the code that Auth0 needs to export in order to protect all routes:

```javascript
import { withMiddlewareAuthRequired } from '@auth0/nextjs-auth0/edge';

export default withMiddlewareAuthRequired();
```

Could someone please assist me with this? I'm genuinely confused and unsure about how to proceed from this point.

**Comment by lewisking** [comment]
> @lewisking See this one: #1247

Thanks man! Works great.

**Comment by kevin-mitchell** [comment]
Any chance this jumps out to anybody as a known issue?

```
...
clientName: 'S3Client',
  commandName: 'ListObjectsV2Command',
  input: { Bucket: undefined, Prefix: 'Yl4y8zRHm1RfTpxK3eNC4/favicon.ico' },
  error: Error: No value provided for input HTTP label: Bucket.
...
  ```

This is with a relatively vanilla Nextjs install.

**Comment by nwidynski** [comment]
There appears to be an issue adding handlers to the handleAuth function in the app directory. The same code works if added to the pages directory.

``` typescript
import { NextApiRequest } from 'next';
import { NextRequest } from 'next/server';

import { handleAuth, handleLogout } from '@auth0/nextjs-auth0';

export const GET = handleAuth({
  logout: handleLogout({
    returnTo: 'http://localhost:4200',
  }),
  federated: handleLogout({
    returnTo: 'http://localhost:4200',
    logoutParams: { federated: '' },
  }),
  onError(_: NextRequest | NextApiRequest, error: Error) {
    console.error(error);
  },
});
```

**Comment by dmithryst** [comment]
Hi everyone! I have some issues with login/logout flow - in fact only initial login leads to login form, after it log in me automaticaly without redirections. So the question is it something wrong with code/app config or this's the issue with the package?

What I use:
**auth0 side**

```js
Customized Identifier + Password


var webAuth = new auth0.WebAuth(params);
webAuth.login({
                realm: databaseConnection,
                username: username,
                password: password,
                captcha: captcha.getValue()
            })
```
**app side**
Packages:
```js
"@auth0/nextjs-auth0": "^3.0.0-beta.3",
"next": "13.4.2", (with app directory)
```
Login/logout logic was almost fully copy-pasted from the example app
```js
 {user ? (
              <li>
                <Link href="/api/auth/logout">Logout</Link>
              </li>
            ) : (
              <li>
                <Link href="/api/auth/login">Login</Link>
              </li>
            )}
```
```js
// app/api/auth/[auth0]/route.ts

import { handleAuth, handleLogout } from '@auth0/nextjs-auth0';

export const GET = handleAuth({
  logout: handleLogout(() => {
    return {
      logoutParams: { federated: '' }, // also doesnt work with { federated: true }
      returnTo: `${process.env.AUTH0_BASE_URL}/home`,
    };
  }),
  onError(req: Request, error: Error) {
    console.error(error);
  },
});
```

**Comment by adamjmcgrath** [comment]
Hi @dmithryst 

> only initial login leads to login form, after it log in me automaticaly without redirections. So the question is it something wrong with code/app config or this's the issue with the package?

This is by design, it's a feature called Single Sign-On (more info https://auth0.com/docs/authenticate/single-sign-on#sso-on-subsequent-logins)

If you want to force the user of your Next application to login again, you can add the `prompt=login` authorization parameter (more info https://auth0.com/docs/authenticate/login/max-age-reauthentication)

```js
// app/api/auth/[auth0]/route.ts
import { handleAuth, handleLogin } from '@auth0/nextjs-auth0';

export const GET = handleAuth({
  login: handleLogin({ authorizationParams: { prompt: 'login' } })
});
```

**Comment by lhimstedt** [comment]
Hey,

I'm creating a NextJs 13 app directory project with the v3 Beta, but I need help with server actions. I call an external API by a NextJs API route as a proxy. The call comes from a server action on a server page. With client-side calls to the proxy, I don't experience any problems. The call from the server action throws a not_authenticated 'The user does not have an active session or is not authenticated'.
But this error came from the proxy before the response from the external API came back. So it calls the external API and immediately returns the not_authenticated error. Has someone an idea why?

```javascript
  // the server action
  async function loadUser(setupMode: boolean): Promise<any> {
    'use server';

    const session = await getSession();
    const res = await fetch(
      `http://localhost:3001/api/users/${session?.user?.sub}?identifier=auth0`
    );
    const user = await res.json();
    console.log('user', user);

    if (setupMode && res.status !== 404) {
      redirect('/settings/profile');
    }
    return {};
  }
```

```javascript
  // the proxy
  const session = await getSession();
  const path = req.url.replace(/^https?:\/\/.*\/api/, '');
  const { method } = req;
  const options: {
    method: string;
    headers: Record<string, any>;
    body?: string;
  } = {
    method,
    headers: {
      authorization: `Bearer ${session?.accessToken}`,
      'Content-Type': 'application/json',
    },
  };

  if (method === 'POST') {
    options.body = JSON.stringify(await req.json());
  }

  const res = await fetch(`http://localhost:3000${path}`, options);
  const data = await res.json();
  return new NextResponse(JSON.stringify(data), { status: res.status });
```

So the `const data` in the proxy returns a valid user. The `const user` in the server action is the not_authenticated error.

Have I overread a related limitation, or am I doing something wrong?

Best regards!

**Comment by paleloser** [comment]
Hey there. First and foremost thank you for maintaining this awesome library.

I used to have the following configuration in the `api` handler:

```js
import { handleAuth, handleCallback, handleLogin } from '@auth0/nextjs-auth0';

export default handleAuth({
  callback: handleCallback({ 
    afterCallback: async (req, res, session, state) => {
      if (session.user) {
        // In production this part is done by the Auth0 post-registration action
        if (process.env.ENV && process.env.ENV === 'local') {
          try {
            await fetch(`${process.env.API_ENDPOINT}/signup`, {
              method: 'POST',
              headers: {
                Authorization: `Bearer ${session.accessToken}`,
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                idpId: session.user.sub,
                email: session.user.email
              })
            })
          } catch (e) {
            console.error(`Unexpected error registering user: ${e}`)
          }
        }

        if (session.user.email === session.user.name) {
          state.returnTo = process.env.AUTH0_BASE_URL + '/profile'
        }
      }
      return session;
    }
  }),
  login: handleLogin({
    authorizationParams: {
      audience: process.env.API_ENDPOINT,
      scope: 'openid email profile offline_access'
    }
  })
});
```

By using the `afterCallback`, I emulated a post-user-registration action locally (in conjunction with `ENV=local`) that helped me to firstly register users in my database as they logged in for the first time and secondly redirect them to their profile page (so they could configure other stuff in their profiles).

Apparently, with the new beta this no longer works, and I get the following after login:
* On the client side (browser): `ERR_TOO_MANY_REDIRECTS`, URL: `http://localhost:3000/api/auth/callback?code=...&state=...`
* On the server side (npm console): 
```js
Request error: AccessTokenError: The user does not have a valid access token.
Request error: AccessTokenError: The user does not have a valid access token.
Request error: AccessTokenError: The user does not have a valid access token.
Request error: AccessTokenError: The user does not have a valid access token.
CallbackHandlerError: Callback handler failed. CAUSE: Missing state cookie from login request (check login URL, callback URL and cookie config).
    at eval (webpack-internal:///(sc_server)/./node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:51:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (webpack-internal:///(sc_server)/./node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:59:24)
    at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:265:37) {
  code: 'ERR_CALLBACK_HANDLER_FAILURE',
  cause: MissingStateCookieError: Missing state cookie from login request (check login URL, callback URL and cookie config).
      at eval (webpack-internal:///(sc_server)/./node_modules/@auth0/nextjs-auth0/dist/auth0-session/handlers/callback.js:18:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async eval (webpack-internal:///(sc_server)/./node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:48:13)
      at async eval (webpack-internal:///(sc_server)/./node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:59:24)
      at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:265:37) {
    status: 400,
    statusCode: 400
  },
  status: 400
}
```

Not blocking us thoug, I'm just commenting this in case it helps.

Thanks in advance!

**Comment by paleloser** [comment]
Also, in regards with this new release, I think it may worth adding an example of authenticating _all_ pages below a given layout (so users don't need to place the `withPageAuthRequired` in every page). Here's what we're using

`root layout`

```js
import '@/styles/globals.css'
import { Inter } from 'next/font/google';
 
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <head>
        <link rel="shortcut icon" href="/icon.svg" type="image/svg+xml"></link>
      </head>
      <body className={`${inter.variable} font-sans min-h-screen`}>
        {children}
      </body>
    </html> 
  )
}
```

`authenticated pages layout`

```js
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";

export default withPageAuthRequired(
  async function Layout({ children }: any) {
    return (
      <UserProvider>
        <main className={`flex flex-col justify-start items-center`}>{children}</main>
      </UserProvider>
    )
  }
)
```

**Comment by adamjmcgrath** [comment]
@asalcedo-ci - we're planning to release v3 by EO July

**Comment by JenReuting** [comment]
> Thank you for the swift beta release. I have one comment, I can open a separate issue if needed:
> 
> The example app in the repo sets up middleware which is what I'd prefer to use, however the example app seems to be using both pages and app dir, and points the [middleware initialization to the pages router version of the login](https://github.com/auth0/nextjs-auth0/blob/beta/example-app/middleware.ts#L3). At first glance I thought I was supposed to use both pages and app /api/auth/[auth0] handlers to get the middleware to work. Would be nice to have an app router only example.
> 
> Edit: Opened an issue I'm encountering using the beta in a fresh app [here](https://github.com/auth0/nextjs-auth0/issues/1239)

I agree with this. The sample code uses both pages and the app directory...it's a bit confusing. Also, the README for the Beta branch that specifically deals with the app directory, directs us to use the pages directory. Just to confirm...we do not need to use the pages directory with the beta branch, right? We can solely use the NextJS13 app router pattern?

**Comment by m-torin** [comment]
Anyone else seeing a `TypeError: "secret" is required` error on build in the example app?

```
info Collecting page data ...TypeError: "secret" is required
    at get (/Users/~/example-app/.next/server/chunks/107.js:358:15)
    at getConfig (/Users/~/example-app/.next/server/chunks/107.js:1637:45)
    at getInstance (/Users/~/example-app/.next/server/chunks/107.js:2690:63)
    at handleAuth (/Users/~/example-app/.next/server/chunks/107.js:2737:31)
    at 472 (/Users/~/example-app/.next/server/app/api/auth/[auth0]/route.js:153:32)
    at __webpack_require__ (/Users/~/example-app/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/Users/~/example-app/.next/server/app/api/auth/[auth0]/route.js:196:39)
    at /Users/~/example-app/.next/server/app/api/auth/[auth0]/route.js:197:81
    at __webpack_require__.X (/Users/~/example-app/.next/server/webpack-runtime.js:138:21)
    at /Users/~/example-app/.next/server/app/api/auth/[auth0]/route.js:197:47

> Build error occurred
Error: Failed to collect page data for /api/auth/[auth0]
    at /Users/~/example-app/node_modules/next/dist/build/utils.js:1161:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

**Comment by milosjovancevic** [comment]
@m-torin 
I think I stumbled upon this and fix for me was to add
`AUTH0_SECRET=DGhgf/HaKKpMmhPIN68PqL01qUQCkH+8hvSaCA360x4=` (random long string) to `.env.local`

**Comment by dlibis** [comment]
Im having this error: Error: Dynamic server usage: cookies, when using this on a server page (app/page.tsx)
`import { getSession } from '@auth0/nextjs-auth0';
export default async function Home() {
  const session = await getSession();
  return <div className="container">{session?.accessToken}</div>;
}`

**Comment by ZainChen** [comment]
appSession is another user or has been modified.
`page.tsx` In the server component, writing to the content in the image reports an error when the page is refreshed.
It is normal to use this writeup in client-side components: `import { withPageAuthRequired } from '@auth0/nextjs-auth0/client';`
![image](https://github.com/auth0/nextjs-auth0/assets/15615524/d78f84ec-1128-415a-a92d-717c27054166)

**Comment by adikari** [comment]
@adamjmcgrath how do I get the token in the API? I used proxy api in the past to call my backend with the appropriate permission. However, currently, I get a `session not found` error.

My use case is, 
1. I have a client application that needs to call my backend
2. I need to send the token to my backend
3. the application uses SSR

Thanks

**Comment by JenReuting** [comment]
We're using the middleware implementation of this beta sdk with the App directory. Can anyone point me to some documentation on how to specify the callback url after the user logs in? I know this is likely one of those stupid simple things that everyone knows but me, but I can't find it after sifting through the docs. TLDR; how do I direct the user to the BASE_URL/dashboard after a successful login?

**Comment by dearrolloruntim3** [comment]
I found an issue with typescript

My page component is like this:

```import React from "react";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";

async function Page({ params }: { params?: { id: string } }) {
  return <span>My page</span>;
}

// @ts-ignore
export default withPageAuthRequired(Page, { returnTo: "/" });
```

It will throw an error because `withPageAuthRequired` expects the component with `params` having only the `slug` field, it doesn't accept any other kind of fields, which is incorrect.

In this examples https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#typescript it says we can accept whatever we want for the route segments, not only slug.

**Comment by phiperomega** [comment]
I've also got the same issue in azure where the env variables is not present at build time. Worked previously with 2.6.0 but not with 3.0.0-beta.3

> Anyone else seeing a `TypeError: "secret" is required` error on build in the example app?
> ....

**Comment by adamjmcgrath** [comment]
@m-torin @milosjovancevic @phiperomega 

in the App Directory, Next.js is attempting to statically render the auth handlers (the auth handlers instantiate the SDK which requires the secret config). I think this is a bug in Next.js (reported here https://github.com/vercel/next.js/issues/45348) because the auth handlers use the `cookies()` dynamic function and should therefore not be opted in for static rendering (per https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic-rendering#dynamic-rendering)

If you can't provide those env vars at build time, you should use the `dynamic` route segment config to explicitly tell Next.js not to statically render that route. eg

```ts
// /app/api/auth/[auth0]/route.ts
import { handleAuth } from '@auth0/nextjs-auth0';

export const GET = handleAuth();

export const dynamic = 'force-dynamic'
```

@dearrolloruntim3 I'll fix the types shortly

@ZainChen I don't understand your problem. Please raise a separate issue with an example repo that demonstrates your problem if you want me to investigate.

**Comment by john-e-riordan** [comment]
> I've also got the same issue in azure where the env variables is not present at build time. Worked previously with 2.6.0 but not with 3.0.0-beta.3
> 
> > Anyone else seeing a `TypeError: "secret" is required` error on build in the example app?
> > ....

I was getting this was apparently able to address it by adding an `.env` file with dummy values which is NOT in my `.gitignore`. The routes get built as `λ  (Server)  server-side renders at runtime` in the output. Injecting environment variables with "real" values at runtime seems to work. I just got it working and only tested it twice, so maybe I'm imagining it now working (but done looking at this today).

Here is my `.env`

```
# The base url of your application
AUTH0_BASE_URL=http://localhost:3000
# The url of your Auth0 tenant domain
AUTH0_ISSUER_BASE_URL=https://YOUR_AUTH0_DOMAIN.auth0.com
# Your Auth0 application's Client ID
AUTH0_CLIENT_ID=YOUR_AUTH0_CLIENT_ID
# Your Auth0 application's Client Secret
AUTH0_CLIENT_SECRET=YOUR_AUTH0_CLIENT_SECRET
# A long, secret value used to encrypt the session cookie
AUTH0_SECRET=LONG_RANDOM_VALUE
```

**Comment by phiperomega** [comment]
Thanks for the response @adamjmcgrath ! Unfortunately the export const dynamic didn't work for me, produces the same error. I'm currently looking at adding the env variables at build time.

**Comment by michaelschufi** [comment]
First of all, thank you for the work on the update. We're excited to use it soon :D

- How stable/secure is this version at the moment? Especially when it comes to checking the login-state with "getSession" inside a server component.
- Is the beta version stable if only used with the `pages` router? 

I'm asking because we're incrementally adopting the app router and will only need the new `getSession` in production in September.

**Comment by niksimFS24** [comment]
Anyone have an idea what could cause this error? Auth flow woks well in localhost but not in PR env. We are providing `AUTH0_SECRET` and `AUTH0_CLIENT_SECRET` as well through Rancher.

```js
- ready started server on 0.0.0.0:80, url: http://localhost:80
CallbackHandlerError: Callback handler failed. CAUSE: invalid_grant (Invalid authorization code)
    at /home/node/app/.next/server/chunks/514.js:1859:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/node/app/.next/server/chunks/514.js:1762:24
    at async /home/node/app/.next/server/chunks/876.js:5172:37 {
  code: 'ERR_CALLBACK_HANDLER_FAILURE',
  cause: IdentityProviderError: invalid_grant (Invalid authorization code)
      at NodeClient.callback (/home/node/app/.next/server/chunks/514.js:160:23)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /home/node/app/.next/server/chunks/514.js:409:29
      at async /home/node/app/.next/server/chunks/514.js:1856:13
      at async /home/node/app/.next/server/chunks/514.js:1762:24
      at async /home/node/app/.next/server/chunks/876.js:5172:37 {
    error: 'invalid_grant',
    errorDescription: 'Invalid authorization code',
    status: 400,
    statusCode: 400,
    openIdState: {
      returnTo: 'this is our app domain here, just edited it :)'
    }
  },
  status: 400
}
```

**Comment by aganglada** [comment]
> Anyone else seeing a `TypeError: "secret" is required` error on build in the example app?
> 
> ```
> info Collecting page data ...TypeError: "secret" is required
>     at get (/Users/~/example-app/.next/server/chunks/107.js:358:15)
>     at getConfig (/Users/~/example-app/.next/server/chunks/107.js:1637:45)
>     at getInstance (/Users/~/example-app/.next/server/chunks/107.js:2690:63)
>     at handleAuth (/Users/~/example-app/.next/server/chunks/107.js:2737:31)
>     at 472 (/Users/~/example-app/.next/server/app/api/auth/[auth0]/route.js:153:32)
>     at __webpack_require__ (/Users/~/example-app/.next/server/webpack-runtime.js:25:42)
>     at __webpack_exec__ (/Users/~/example-app/.next/server/app/api/auth/[auth0]/route.js:196:39)
>     at /Users/~/example-app/.next/server/app/api/auth/[auth0]/route.js:197:81
>     at __webpack_require__.X (/Users/~/example-app/.next/server/webpack-runtime.js:138:21)
>     at /Users/~/example-app/.next/server/app/api/auth/[auth0]/route.js:197:47
> 
> > Build error occurred
> Error: Failed to collect page data for /api/auth/[auth0]
>     at /Users/~/example-app/node_modules/next/dist/build/utils.js:1161:15
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   type: 'Error'
> }
> ```

Seems like the issue is, the new api routes cannot access env variables right?

https://github.com/vercel/next.js/discussions/50759

**Comment by adamjmcgrath** [comment]
👋 v3 is now Generally Available https://github.com/auth0/nextjs-auth0/releases/tag/v3.0.0

If you notice any problems, please raise a new issue

**Comment by topaxi** [comment]
If anyone in the future ever runs into the issue @niksimFS24 described above.

We had to increase our buffer proxy size in nginx of our k8s ingress with these two annotations:

```ts
'nginx.ingress.kubernetes.io/proxy-buffer-size': '16k',
'nginx.ingress.kubernetes.io/server-snippet': 'client_header_buffer_size 16k; large_client_header_buffers 4 32k;'
```

**Comment by zeelmodi-simform** [comment]
@adamjmcgrath I'm getting following error when I try to redirect to login page

`LoginHandlerError: Login handler failed. CAUSE: Discovery requests failing for https://dev-6vy0mwhhwzruj0vb.us.auth0.com, outgoing request timed out after 5000ms
    at eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/login.js:60:19)
    at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:59:24)
    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:253:37) {
  code: 'ERR_LOGIN_HANDLER_FAILURE',
  cause: DiscoveryError: Discovery requests failing for https://dev-6vy0mwhhwzruj0vb.us.auth0.com, outgoing request timed out after 5000ms
      at NodeClient.getClient (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/auth0-session/client/node-client.js:47:19)
      at async NodeClient.authorizationUrl (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/auth0-session/client/node-client.js:114:24)
      at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/auth0-session/handlers/login.js:73:34)
      at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/login.js:57:13)
      at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:59:24)
      at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:253:37),
  status: undefined
}`

I'm currently on the free version of auth0 and also tried various ways to integrate it with my app. I tried it with both app and pages router but none of them seems to be working for me. Any help will be appreciated!

**Comment by joshua-lawrence** [comment]
> @adamjmcgrath I'm getting following error when I try to redirect to login page
> 
> `LoginHandlerError: Login handler failed. CAUSE: Discovery requests failing for https://dev-6vy0mwhhwzruj0vb.us.auth0.com, outgoing request timed out after 5000ms at eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/login.js:60:19) at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:59:24) at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:253:37) { code: 'ERR_LOGIN_HANDLER_FAILURE', cause: DiscoveryError: Discovery requests failing for https://dev-6vy0mwhhwzruj0vb.us.auth0.com, outgoing request timed out after 5000ms at NodeClient.getClient (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/auth0-session/client/node-client.js:47:19) at async NodeClient.authorizationUrl (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/auth0-session/client/node-client.js:114:24) at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/auth0-session/handlers/login.js:73:34) at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/login.js:57:13) at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:59:24) at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:253:37), status: undefined }`
> 
> I'm currently on the free version of auth0 and also tried various ways to integrate it with my app. I tried it with both app and pages router but none of them seems to be working for me. Any help will be appreciated!

Also encountering this issue with increasing frequency.

**Comment by adamjmcgrath** [comment]
@Sivaranjith1 - it's a client component (React Context is not available on the server)
