### ISSUE TITLE
Custom Session Store is being initialize multiple times.

### ISSUE THREAD

**Issue by andrienpecson** [auth0/nextjs-auth0#1241]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I found out that the set function in SessionStore is called multiple times. I think what is happening is that the store is being reinitialized every time an API endpoint or the middleware calls the handler functions of auth0.

### Reproduction

The console in the set function is increasing every time I navigate to a page that calls an authenticated API endpoint.

```
import { SessionStore, Session } from '@auth0/nextjs-auth0';
import { SessionPayload } from '@auth0/nextjs-auth0/dist/auth0-session';

class Store implements SessionStore {
  private redis: redis;

  constructor() {
    this.redis = new redis()
  }

  async get(id: string): Promise<SessionPayload<Session> | null> {
   // I removed the code for get
  }

  async set(id: string, session: SessionPayload<Session>): Promise<void> {
      console.log(id) 
  }

  async delete(id: string): Promise<void> {
   // I removed the code for delete
  }
}

const config = {
  session: {
    store: new Store(),
  },
};

export default config;
```

There is an issue also where after I update the session, the set function will be called multiple times. There are times when the call contains an old session overriding the new one.

The screenshot below shows that the set function is called multiple times with the same session value. You can see that after I updated the session value, the set function was able to receive the update, but on the latter part it received an old one replacing the new session value.
![image](https://github.com/auth0/nextjs-auth0/assets/13114319/914eceba-280a-4959-a2dd-2eb7bcf5c4c7)

### nextjs-auth0 version

2.4.0

### Next.js version

13

### Node.js version

16.16.0

**Comment by andrienpecson** [comment]
@adamjmcgrath I am logging a custom attribute in the session which I need to be updated. The problem is that due to multiple calls to set, I think there is a late call which contains old version of the session which ovverrides the updated one.

**Comment by adamjmcgrath** [comment]
> The problem is that due to multiple calls to set

If you don't want to call set on every request you can disable the rolling session (set `session.rolling` to false), see https://auth0.github.io/nextjs-auth0/interfaces/config.SessionConfig.html#rolling

**Comment by adamjmcgrath** [comment]
Closing, as I believe https://github.com/auth0/nextjs-auth0/issues/1241#issuecomment-1592487689 answers your question - if you want me to investigate anymore, please provide a reproducible test case
