### ISSUE TITLE
handleAuth's callback usage in v3 beta version

### ISSUE THREAD

**Issue by brunoscopelliti** [auth0/nextjs-auth0#1242]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm trying to migrate a small project to app directory, but there are a couple of things that confuse me.
In the old version my authendication handler looked something like:

```
// src/pages/api/auth/[...auth0].ts
import { AfterCallback, handleAuth, handleCallback } from "@auth0/nextjs-auth0";

const afterCallback: AfterCallback = async (_request, response, session) => {
  if (!session.user.email) {
    response.status(401).end("Invalid user");
    return;
  }

  // ...
};

export default handleAuth({
  callback: async (request, response) => {
    try {
      await handleCallback(request, response, { afterCallback });
    } catch (error) {
      response.redirect("/auth/error");
    }
  },
});
```

And now, I changed it to something like:

```
// src/app/api/auth/[auth0]/route.ts
import type { AfterCallbackAppRoute } from "@auth0/nextjs-auth0";
import { handleAuth, handleCallback } from "@auth0/nextjs-auth0";

const afterCallback: AfterCallbackAppRoute = async (req, session) => {
  // ...
};


export const GET = handleAuth({
  callback: async (req, res) => {
    try {
      await handleCallback(req, res, { afterCallback });
    } catch (error) {
      // res.redirect("/auth/error");
    }
  },
});
```

The new version has two problems:

1. Typescript complains about `callback`'s signature:

> Type '(req: NextRequest | NextApiRequest, res: AppRouteHandlerFnContext | NextApiResponse) => Promise<unknown>' is not assignable to type 'Handler'.
  Type 'Promise<unknown>' is not assignable to type 'Response | Promise<Response>'.
    Type 'Promise<unknown>' is not assignable to type 'Promise<Response>'.
      Type 'unknown' is not assignable to type 'Response'.

2. What is still called `res` in my snippet above isn't a `NextApiResponse` anymore; that means I cannot use it anymore to do redirect, or to send an error message like in `afterCallback`. Are these use cases still supported? How?

### Reproduction

Details in description.

### nextjs-auth0 version

3.0.0-beta.0

### Next.js version

13.4.5

### Node.js version

18.15.0

**Comment by adamjmcgrath** [comment]
Thanks for raising this @brunoscopelliti 

> What is still called res in my snippet above isn't a NextApiResponse anymore;

The signature of API handlers is different in the app directory than the pages directory. See https://nextjs.org/docs/app/api-reference/file-conventions/route#parameters

Just like auth handlers in the page router need to match page router api handlers, so auth handlers in the app dir need to match app router handlers. 

You want something like this

```ts
// src/app/api/auth/[auth0]/route.ts
import type { AfterCallbackAppRoute } from '@auth0/nextjs-auth0';
import { handleAuth, handleCallback } from '@auth0/nextjs-auth0';
import { NextRequest, NextResponse } from 'next/server';

const afterCallback: AfterCallbackAppRoute = async (req, session) => {
  // ...
  return session;
};

export const GET = handleAuth({
  callback: async (req, ctx) => {
    try {
      // you need to cast this as returning a response because the auth handlers support
      // signatures for both routers
      return (await handleCallback(req, ctx, { afterCallback })) as Promise<Response>;
    } catch (error) {
      return NextResponse.redirect('/auth/error');
    }
  }
});
```

Although for your case, it would probably be easier to use the shorthand handlers

```ts
// src/app/api/auth/[auth0]/route.ts
import type { AfterCallbackAppRoute } from '@auth0/nextjs-auth0';
import { handleAuth, handleCallback } from '@auth0/nextjs-auth0';
import { NextResponse } from 'next/server';

const afterCallback: AfterCallbackAppRoute = async (req, session) => {
  // ...
  return session;
};

export const GET = handleAuth({
  callback: handleCallback({ afterCallback }),
  onError() {
    return NextResponse.redirect('/auth/error');
  }
});
```

**Comment by brunoscopelliti** [comment]
@adamjmcgrath Thanks you for the explanation, and your proposed solution works like a charm.

**Comment by ADTC** [comment]
Thank you! The docs are so sparse on how to deal with the callback getting error code and error message in the GET params. Your examples helped, though the below had to be fixed.

Due to this [removal of support for relative URLs in Next.js 13](https://nextjs.org/docs/messages/middleware-relative-urls), I had to revise the example of shorthand handlers to automatically create the absolute URL:

```js
// src/app/api/auth/[auth0]/route.ts
import type { AfterCallbackAppRoute } from '@auth0/nextjs-auth0';
import { handleAuth, handleCallback } from '@auth0/nextjs-auth0';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

const afterCallback: AfterCallbackAppRoute = async (req, session) => {
  // ...
  return session;
}

export const GET = handleAuth({
  callback: handleCallback({ afterCallback }),
  onError(request: NextRequest) {
    const url = request.nextUrl.clone();
    url.pathname = '/auth/error';
    return NextResponse.redirect(url);
  },
})
```

Tip: `'/auth/error'` can be changed to any route in your app which can handle the params and display the error message.

**Comment by wade-wojcak-vib** [comment]
Just chiming in regarding the comment above (https://github.com/auth0/nextjs-auth0/issues/1242#issuecomment-1679956832) that this was incredibly helpful to me, and I agree with the point about the documentation around the onError here being sparse or hard to find (especially for App Router implementations).

I am firing an access_denied API call from an Auth0 action if the user uses Google Social Login and their domain doesn't match a whitelist I've defined, and being able to intercept that properly in Next.js to redirect them to a specific error page was really important for my project.
