### ISSUE TITLE
V3 Beta App Router returns 500 Error 

### ISSUE THREAD

**Issue by jalvarado91** [auth0/nextjs-auth0#1246]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After installing the v3 beta in an fresh nextjs app and setting up the api handlers I'm consistently receiving a 500 HTTP Error when visiting any of the handler routes (e.g. `/api/auth/login`). App only has app router routes, no `pages` directory. Not using any middleware either. 

Nothing is getting logged to the console either. So it's hard to debug.

Seems I'm not the only one. Same error reported [here](https://github.com/auth0/nextjs-auth0/issues/1235#issuecomment-1586506785) and [here](https://github.com/auth0/nextjs-auth0/issues/1235#issuecomment-1587481710). 

Screenshot of browser error and console 
![image](https://github.com/auth0/nextjs-auth0/assets/1750392/5be59fdc-79ab-4228-b14d-1ca75abaf25b)

![image](https://github.com/auth0/nextjs-auth0/assets/1750392/0e9b1f34-aa98-4a26-a030-16465186ff5d)

### Reproduction

1. I started a new fresh nextjs app  with all the defaults (app router checked)
2. Installed the beta `npm i @auth0/nextjs-auth0@beta` 
3. Added env vars for my Regular Web Application to .env.local
4. Set up the auth0 api handler route under `app/api/auth/[auth0]/route.ts`
5. Added the `UserProvider` in the root layout
6. Add the client component sample [from the read me](https://github.com/auth0/nextjs-auth0/tree/beta#consume-authentication-1) to `page.tsx`
7. Start the app and go to `http://localhost:3000/api/auth/login` and saw the error above

### Additional context

N/A

### nextjs-auth0 version

3.0.0-beta.0

### Next.js version

13.4.5

### Node.js version

v16.14.2

**Comment by adamjmcgrath** [comment]
Thanks for sharing those steps @jalvarado91 

This is also failing for me with Node 16 (it's working with Node 18) 

I'll investigate and get back to you

**Comment by adamjmcgrath** [comment]
ok, I understand the issue and will work on a fix. In the meantime, you can use the Beta with Node 18 & 20

**Comment by adamjmcgrath** [comment]
fixed in https://github.com/auth0/nextjs-auth0/releases/tag/v3.0.0-beta.1
