### ISSUE TITLE
Getting 502 Error from Lambda when using serverless-next.js

### ISSUE THREAD

**Issue by caaatisgood** [auth0/nextjs-auth0#1252]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm using [`serverless-next.js`](https://github.com/serverless-nextjs/serverless-next.js) to host a Next.js app on AWS. And currently trying to migrate from `auth0-js` to `@auth0/nextjs-auth0`.

Everything works perfectly fine on local but not the case when it gets deployed to AWS due to 502 errors, unfortunately.

### Reproduction

Please refer to my demo project here [caaatisgood/serverless-nextjs-auth0-demo](https://github.com/caaatisgood/serverless-nextjs-auth0-demo) and [https://d1o1w8zz8wsisu.cloudfront.net/](https://d1o1w8zz8wsisu.cloudfront.net/)

### Additional context

Some observations I got so far
- The auth endpoints are responding `null` when testing it from the Lambda panel. For example:
  <img width="1840" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/12913401/280c890d-2223-44e5-9d8e-0155b1ff94db">

  Here's the event payload I used for calling `/api/auth/me`

  ```json
  {
    "Records": [
      {
        "cf": {
          "config": {
            "distributionId": "EXAMPLE"
          },
          "request": {
            "uri": "/api/auth/me",
            "method": "GET"
          }
        }
      }
    ]
  }
  ```

  Seems like on the serverless layer, `null` is not a valid format of the response. Hence the 502 invalid JSON error or "LambdaValidationError from cloudfront" according to `X-Cache` in the response header is thrown.

- I tried adding the profile endpoint by adding a separate file `/api/auth/alt-me.ts` with the following code and it worked.

  ```typescript
  import { handleProfile } from "@auth0/nextjs-auth0";
  
  export default handleProfile({});
  ```

  The response seems legit
  
  <img width="1840" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/12913401/afdb9ed6-a6e0-480e-b846-4a05d2cc9dc3">

  With this event payload

  ```json
  {
    "Records": [
      {
        "cf": {
          "config": {
            "distributionId": "EXAMPLE"
          },
          "request": {
            "uri": "/api/auth/alt-me",
            "method": "GET"
          }
        }
      }
    ]
  }
  ```

  However, it's not the case for login and callback endpoints. The `null` value is still being returned causing the 502 error.

### nextjs-auth0 version

2.6.2

### Next.js version

12.1.0

### Node.js version

14.x, 16.x, 18.x

**Comment by adamjmcgrath** [comment]
@caaatisgood - it doesn't look like an issue with the SDK tbh. If you create a dynamic page route without the SDK does that work? This is the only difference between using handleAuth or the separate auth handlers directly.

Also `serverless-next.js` [doesn't support Next 12](https://github.com/serverless-nextjs/serverless-next.js#:~:text=A%20zero%20configuration-,Next.js%2010/11,-serverless%20component%20for)

**Comment by caaatisgood** [comment]
@adamjmcgrath thanks for getting back to me. `serverless-next.js` doesn't fully support Next.js 12 but is supposed to work in my case as I'm not using any of [the newer features](https://github.com/serverless-nextjs/serverless-next.js#:~:text=Next.js%2012%20features%20Features%20like%20middleware%2C%20bot%2Daware%20ISR%20fallback%2C%20AVIF%20image%20support%2C%20etc.%20are%20not%20yet%20supported%2C%20though%20with%20the%20latest%20component%20version%2C%20you%20should%20be%20able%20to%20use%20existing%20features%20on%20Next.js%2012.).

Just tested that the dynamic API routes work on my current stack. I also added an API that returns `null` ([commit](https://github.com/caaatisgood/serverless-nextjs-auth0-demo/commit/6f448f8b05bdf35531f395f6c49d1ea33501a350)) which would give me the same 502 error on AWS environment. Is there any chance the handlers of the SDK are returning `null` in certain edge cases? I.e. return `null` when configuration check/assertion didn't pass.

**Comment by adamjmcgrath** [comment]
>  Is there any chance the handlers of the SDK are returning null in certain edge cases? I.e. return null when configuration check/assertion didn't pass.

The code for the auth handler is here:
https://github.com/auth0/nextjs-auth0/blob/v2.6.2/src/handlers/auth.ts#L163-L191

As you can see, the handler from `handleAuth()` never returns anything

**Comment by adamjmcgrath** [comment]
> we have a cancel button in the login process where the URL returns <domain>/auth/api/callback?error=<error code>&error_description=<number>&state=<long hash>. And for that case, I'm encountering an error again in the lambda function.

This is expected behaviour, when you get an error form the Authorization Server, it will respond with an error response (note the `error` and `error_description` params in the callback url) - in these cases you should catch the error and handle appropriately (like prompt the user to try and login again)

Closing, as I don't see any issue with the `handleAuth` method
