### ISSUE TITLE
Support edge runtime in app based routes

### ISSUE THREAD

**Issue by gerlv** [auth0/nextjs-auth0#1257]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

NextJS Auth0 can work with edge runtime.

At the moment, only the middleware supports the edge runtime. You can't use edge based getSession in app routes.

### Describe the ideal solution

Edge runtime supported for app based routes

### Alternatives and current workarounds

Use nodejs runtime

**Comment by adamjmcgrath** [comment]
Hi @gerlv 

> You can't use edge based getSession in app routes

You can use the edge based `getSession`  in app based routes in the new Beta (see #1235)

eg.

```ts
import { getSession } from '@auth0/nextjs-auth0/edge';
import { NextRequest, NextResponse } from 'next/server';

const GET = async (req: NextRequest) => {
  const res = new NextResponse();
  const session = await getSession(req, res);

  return NextResponse.json(session?.user, res);
};

export { GET };
```

**Comment by gerlv** [comment]
@adamjmcgrath thank you for a code snippet, I can see it works, but as far as I can see this wouldn't work with app based routes, and you can't override `handleAuth` functionality as all imports are from `@auth0/nextjs-auth0`.

I.e. there is a way to get the session, but the large part of the functionality can't be used with edge runtime.

**Comment by adamjmcgrath** [comment]
> as I can see this wouldn't work with app based routes

Can you elaborate? The code snippet I shared works with app based routes (on the edge runtime) in the new beta, have tested it on the example app

> but the large part of the functionality can't be used with edge runtime

We are currently working on supporting the rest of the functionality on the Edge runtime, should be landing in the new v3 Beta very soon

**Comment by ekojsalim** [comment]
> We are currently working on supporting the rest of the functionality on the Edge runtime, should be landing in the new v3 Beta very soon

Just to clarify, does this mean support for `handleAuth` for Cloudflare Workers i.e. transitioning from the node-only `openid-client` to something like `oauth4webapi`? Asking this since we are prospecting for authn solutions and this is a huge blocker for us.

**Comment by adamjmcgrath** [comment]
> Just to clarify, does this mean support for handleAuth for Cloudflare Workers i.e. transitioning from the node-only openid-client to something like oauth4webapi? 

@ekojsalim - yes, that's correct.

We have a branch which adds support for all the functionality from the Node runtime to the Edge runtime (in the app directory) here https://github.com/auth0/nextjs-auth0/tree/edge-auth-handlers

It's code complete and ready to be shipped to the new Beta, we just have an [issue](https://github.com/vercel/next.js/issues/51642) with Next.js - which we have an open PR for here https://github.com/vercel/next.js/pull/51665

**Comment by ekojsalim** [comment]
That's awesome. Was actually assessing whether to fork & patch but having this supported is great. Looking forward to v3 :)

**Comment by adamjmcgrath** [comment]
👋 Full support for the edge runtime, including `handleAuth` has been added to https://github.com/auth0/nextjs-auth0/releases/tag/v3.0.0-beta.3

More info on the Beta can be found here https://github.com/auth0/nextjs-auth0/issues/1235
