### ISSUE TITLE
Type error with custom handlers in app router

### ISSUE THREAD

**Issue by KaiKloepfer** [auth0/nextjs-auth0#1258]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

There is an error with the typing on App Router custom handlers, see repro below.

### Reproduction

Do a new install and standard setup steps

Create this file
```typescript
// app/api/auth/[auth0]/route.ts
import { handleAuth, handleLogin, HandlerError } from "@auth0/nextjs-auth0";
import {
  AppRouteHandlerFnContext,
  LoginOptions,
} from "@auth0/nextjs-auth0/dist/handlers";
import { Handler } from "@auth0/nextjs-auth0/dist/handlers/router-helpers";
import { NextRequest } from "next/server";

// @ts-expect-error Typing broken for this handler
const login: Handler = async (
  req: NextRequest,
  ctx: AppRouteHandlerFnContext,
  options?: LoginOptions
): Promise<Response> => {
  // Do some other stuff
  return handleLogin(req, ctx, options);
};

export const GET = handleAuth({
  login,
  onError(req: NextRequest, error: HandlerError) {
    console.error(error);
  },
});
```
Removing the `@ts-expect-error` will cause compile to fail. With the line, it works as expected. 

### nextjs-auth0 version

3.0.0-beta.2

### Next.js version

13.4.6

### Node.js version

19.9.0

**Comment by adamjmcgrath** [comment]
@KaiKloepfer - thanks for raising this

Something like the following should work

```ts
// app/api/auth/[auth0]/route.ts
import { handleAuth, handleLogin, HandlerError } from '@auth0/nextjs-auth0';
import { AppRouteHandlerFnContext } from '@auth0/nextjs-auth0/dist/handlers';
import { Handler } from '@auth0/nextjs-auth0/dist/handlers/router-helpers';
import { NextRequest } from 'next/server';

const login: Handler = async (req, ctx) => {
  // Do some other stuff
  return handleLogin(req as NextRequest, ctx as AppRouteHandlerFnContext);
};

export const GET = handleAuth({
  login,
  onError(req: NextRequest, error: HandlerError) {
    console.error(error);
  }
});
```

But let me investigate what the best solution is here

**Comment by adamjmcgrath** [comment]
np @KaiKloepfer 

> Doesn't support passing options in

How would you expect that to work and what error are you getting?

**Comment by adamjmcgrath** [comment]
Also, if you just want to customise the options you can do:

```
import { handleAuth, handleLogin } from '@auth0/nextjs-auth0';

export const GET = handleAuth({
  signup: handleLogin({ authorizationParams: { screen_hint: 'signup' } })
});
```

**Comment by adamjmcgrath** [comment]
@KaiKloepfer - in the app router world, `handleCallback` will return the response that you can mutate (rather than mutating it in the `afterCallback` hook). eg

```ts
import { handleAuth, handleCallback } from '@auth0/nextjs-auth0';
import { AfterCallbackAppRoute } from '@auth0/nextjs-auth0/dist/handlers';
import { NextResponse } from 'next/server';

const afterCallback: AfterCallbackAppRoute = async (req, session) => {
  // Edit the session here
  return session;
};

export default handleAuth({
  async callback(req, ctx) {
    const res = (await handleCallback(req, ctx, { afterCallback })) as NextResponse;
    const userExists = false;
    if (!userExists) {
      // Redirect user to onboarding page
      const url = new URL(res.headers.get('location') as string);
      const returnTo = url.searchParams.get('returnTo');
      if (returnTo) {
        const url = new URL(returnTo);
        const rel = url.toString().substring(url.origin.length);
        res.headers.set('location', `/account/create?returnTo=${rel}`);
      } else {
        res.headers.set('location', '/account/create');
      }
    }
    return res;
  }
});
```

**Comment by adamjmcgrath** [comment]
I updated the example to only include exports from '@auth0/nextjs-auth0'. I think you should have all the exports you need to  type this properly - so am going to close this issue.

**Comment by nwidynski** [comment]
@adamjmcgrath I'm trying to conditionally add logout federation by querying a flag on the authenticated user. Is it possible to get this information within the logout handler under the app directory?

``` typescript
async logout(req, ctx) {
    //const user = getSession() HOW?

    const res = (await handleLogout(req, ctx, {
      returnTo: 'http://localhost:4200',
      //...(user && {logoutParams: { (federated: '') }}),
    })) as NextResponse;

    return res;
  },
```
