### ISSUE TITLE
Question about base url and Vercel Preview Deployments

### ISSUE THREAD

**Issue by jondotblack** [auth0/nextjs-auth0#1261]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am receiving a 500 error when trying to access an auth-protected route on a Vercel Preview branch.  I believe it is something simple I'm missing with the Vercel Preview environment variables (I am overriding them specifically for the test branch).
<img width="695" alt="Screenshot 2023-06-21 at 7 31 34 AM" src="https://github.com/auth0/nextjs-auth0/assets/1533441/cb36d6eb-f80b-465a-9612-cb95f246e09e">

My `middleware.js` file;
```js
import { withMiddlewareAuthRequired } from '@auth0/nextjs-auth0/edge';

export default withMiddlewareAuthRequired();

export const config = {
  matcher: ['/((?!legal|test).*)'],
};
```

My `[auth].js` file;
```js
import { authApiHandler } from '../core/auth';

export default authApiHandler();
```

My `authApiHandler.js` file;
```js
import { handleAuth, handleLogin, handleLogout } from '@auth0/nextjs-auth0';
import * as Sentry from '@sentry/nextjs';

export const authApiHandler = () =>
  handleAuth({
    async login(req, res) {
      try {
        let { returnTo } = req.query;

        await handleLogin(req, res, {
          returnTo: `${returnTo || '/'}`,
        });

        await handleLogout(req, res, {
          returnTo: `${returnTo || '/'}`,
        });
      } catch (error) {
        Sentry.captureException(error);
        res.status(error.status || 400).end(error.message);
      }
    },
  });
```

Looking at the Vercel logs I see this error;
```bash
ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"write after end","code":"ERR_STREAM_WRITE_AFTER_END","stack":["Error [ERR_STREAM_WRITE_AFTER_END]: write after end","    at new NodeError (node:internal/errors:387:5)","    at ServerResponse.end (node:_http_outgoing:968:15)","    at ServerResponse.apiRes.end (/var/task/node_modules/next/dist/server/api-utils/node.js:347:25)","    at login (/var/task/dist/apps/foobar/.next/server/pages/api/auth/[auth0].js:929:39)"]}
Unknown application error occurred
Runtime.Unknown
```

### Reproduction

1. Application runs as expected locally
2. Deploy changes to preview branch
3. No build errors and deploy successfully
4. Can access and load public routes successfully
5. When trying to access an auth-protected page I receive a 500 error and the URL is pointing at `/api/auth/login?returnTo=%2F`

### nextjs-auth0 version

2.6.2

### Next.js version

13.1.1

### Node.js version

16

**Comment by jondotblack** [comment]
> Hi @jondotblack
> 
> You're executing `handleLogin` and `handleLogout` in your `login` handler in `authApiHandler.js` - is that intentional?

Nope, as soon as I posted I thought that didn't look right.  I just pushed the fix and it resolved the 500 error but seeing a ``The provided redirect_uri is not in the list of allowed callback URLs.` error so I still think my environment variables are set incorrectly.

**Comment by adamjmcgrath** [comment]
@jondotblack

> I still think my environment variables are set incorrectly.

There's information on setting your environment variables for Vercel here https://github.com/auth0/nextjs-auth0/tree/main/examples#assigning-the-auth0_base_url

**Comment by jondotblack** [comment]
> @jondotblack
> 
> > I still think my environment variables are set incorrectly.
> 
> There's information on setting your environment variables for Vercel here https://github.com/auth0/nextjs-auth0/tree/main/examples#assigning-the-auth0_base_url

I'm still running into an issue where the `VERCEL_BRANCH_URL` doesn't seem to be processing and when accessing the preview branch it has`redirect_uri=https%3A%2F%2F%24VERCEL_BRANCH_URL%2Fapi%2Fauth%2Fcallback`.  If I just use the actual preview branch URL it all works as expected.

**Comment by adamjmcgrath** [comment]
@jondotblack - does your `.env.production` look like this https://github.com/auth0/nextjs-auth0/blob/main/examples/kitchen-sink-example/.env.production#L10?

**Comment by jondotblack** [comment]
> @jondotblack - does your `.env.production` look like this https://github.com/auth0/nextjs-auth0/blob/main/examples/kitchen-sink-example/.env.production#L10?

Yes it does

**Comment by adamjmcgrath** [comment]
ok, thanks for confirming @jondotblack 

I can't explain why `$VERCEL_BRANCH_URL` in a .env file wouldn't be substituted for anything on your Next.js app - this is how you reference other variables in .env files https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#referencing-other-variables - and the same code works for the example app.

**Comment by jondotblack** [comment]
> Don't see an issue with the SDK, so closing.

I have an open support request with Vercel and will post the outcome of that conversation.  Thank you for the help.
