### ISSUE TITLE
Authentication with access token not working

### ISSUE THREAD

**Issue by nordicgit70** [auth0/nextjs-auth0#1266]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

My use case is to have another client to retrieve data from my API using an access token.

The API is part of a Next.Js App that uses Auth0 for authentication. The access token is retrieved with the function `getAccessToken` and manually copied to the other client. 

The expected behavior was for the other client to be authenticated with the access token.
The actual behavior is HTTP error 500: *The user does not have a valid session.*

This looks similar to #735 which was not concluded.

### Reproduction

1. User authenticates to the App.
2. Next.js API returns access token with `getAccessToken`.
3. Client connect to API with access token, but access is denied with HTTP 500.

### nextjs-auth0 version

2.3.1

### Next.js version

13.4.4

### Node.js version

18.12.1

**Comment by adamjmcgrath** [comment]
Hi @nordicgit70 - thanks for raising this

> My use case is to have another client to retrieve data from my API using an access token.

This SDK does not protect routes with a JWT Bearer token. It is for logging in to Auth0, establishing an httpOnly session cookie, then protecting pages and api routes with the session cookie (not with the bearer authorization header) (more info here https://github.com/auth0/nextjs-auth0/blob/main/ARCHITECTURE.md)

We don't currently have an SDK for protecting Next APIs written in Next from other other applications/domains with a JWT bearer access token.

**Comment by adamjmcgrath** [comment]
Closing as I believe https://github.com/auth0/nextjs-auth0/issues/1266#issuecomment-1607670837 answers your question

**Comment by nordicgit70** [comment]
Thanks for the explanation.

**Comment by sergsar** [comment]
> Hi @nordicgit70 - thanks for raising this
> 
> > My use case is to have another client to retrieve data from my API using an access token.
> 
> This SDK does not protect routes with a JWT Bearer token. It is for logging in to Auth0, establishing an httpOnly session cookie, then protecting pages and api routes with the session cookie (not with the bearer authorization header) (more info here https://github.com/auth0/nextjs-auth0/blob/main/ARCHITECTURE.md)
> 
> We don't currently have an SDK for protecting Next APIs written in Next from other other applications/domains with a JWT bearer access token.

Hey, any updates on this? Is there any actual way to use Next.js endpoints with another domain or application?

**Comment by gabriel-peter** [comment]
+1 to this ^ I would like to avoid a very bespoke solution where I need to validate the access token w/ barebones cypto (sadly struggling to do so)
