### ISSUE TITLE
Question: Just a question regarding the singleton instance creation and usage

### ISSUE THREAD

**Issue by ioanamaierean** [auth0/nextjs-auth0#1271]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I know this is not an issue regarding this library, so sorry for posting it here, but I cannot seam to find any good answer online.

I am trying to create locally a singleton just like this library is creating the `let instance: Auth0Server & { sessionCache: SessionCache }` by using the `getInstance` function (https://github.com/auth0/nextjs-auth0/blob/cc008b321ce697d86204c0206278a9064a86db6f/src/index.ts#L145), in my nextjs app where I use successfully this library. 

My issue is that every time I import my `getSomethingInstance` (or the functions that use getSomethingInstance) into other `pages/api` or `getServerSideProps` a new instance is created, so the singleton does not work. (my code is similar to this one https://github.com/vercel/next.js/blob/cdff5dfb75173f8740913bd8af115909e9e7508b/examples/with-mongodb/util/mongodb.js)

Could you please give me an idea of what I may be doing wrong?

Thank you very much.
Great library!!!

### Reproduction

https://github.com/vercel/next.js/blob/cdff5dfb75173f8740913bd8af115909e9e7508b/examples/with-mongodb/util/mongodb.js

### nextjs-auth0 version

2.2.1

### Next.js version

13.1.6

### Node.js version

18.13.0

**Comment by adamjmcgrath** [comment]
Hi @ioanamaierean - thanks for raising this

Could you share the code for `getSomethingInstance` and an example of how you are using it?

**Comment by adamjmcgrath** [comment]
@ioanamaierean - closing, feel free to ping me the code for `getSomethingInstance` if you want me to reopen
