### ISSUE TITLE
[beta] Types for `withApiAuthRequired` are incomplete

### ISSUE THREAD

**Issue by jgabriele** [auth0/nextjs-auth0#1273]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello,

NextJS 13 supports fetch apis when it comes to `Response` and `Request` (see [this example](https://nextjs.org/docs/app/building-your-application/routing/router-handlers#cookies)). However the `withApiAuthRequired` typing only cares about Next's overrides for those types

<img width="718" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/395650/45f64a2a-988b-4edd-b811-55a2749deb9a">

<img width="1206" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/395650/a62182ba-c56d-40c9-b8e4-9a265ef1320d">

Could you please update the type to support `Request` and `Response`?

### Reproduction

Create a Route Handler with the following content
> export const GET = withApiAuthRequired((req: Request) => {
  return new Response('Hello')
})

Expected result: no TS error

### nextjs-auth0 version

3.0.0-beta.3

### Next.js version

13.4.1

### Node.js version

16.13.0

**Comment by adamjmcgrath** [comment]
Hi @jgabriele - thanks for raising this

We don't currently support `Request`/`Response` in the Beta. We rely on the `cookie` helpers in NextRequest/Response.

Is there any reason you can't use `NextResponse` there?

**Comment by jgabriele** [comment]
Hello 👋 I can use `NextResponse` but as I don't need to I would like to avoid if possible. But I'm also fine using it.

Feel free to close this PR but I'd say a note about this limitation in the docs would be appreciated.
