### ISSUE TITLE
v3 Beta: not_authenticated when calling API from server actions

### ISSUE THREAD

**Issue by lhimstedt** [auth0/nextjs-auth0#1278]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I tried to use the Next.js alpha feature called "server actions" with the next's-auth0 library. The goal is to call an external API from a server action to pre-populate the page. A Next.js API route acts as a proxy for the external one.

The general setup with the proxy and the external API works nicely when calling it from the client side, e.g., after the form submit. But when called from a server action, it just returns this error:

```json
 {
  "error": "not_authenticated",
  "description": "The user does not have an active session or is not authenticated"
}
```

I'm logging the API response from the external API in the proxy and the response from the proxy in the server action. First, I'll see the error above coming from the proxy; then, I'll see a successful response from the external one in the proxy. It returns the error but still passes the request to the proxy route. And this one sends it to the external API.

I also logged the sessions in different places. The getSession() method returns a valid session, including an accessToken, in the server action and the proxy. That's why I wonder why it says not authenticated.

```javascript
// the server action
async function loadOrganization() {
  'use server';
  // when i use getSession here it returns a valid looking session object
  const res = await fetch('http://localhost:3001/api/organizations', {
    method: 'GET',
  });
  console.log('app result', await res.json()); // this response here is the not_authenticated error
}

await loadOrganization();
```

```javascript
// the proxy
import { getSession, withApiAuthRequired } from '@auth0/nextjs-auth0';
import { NextResponse } from 'next/server';

const handler = async (req: any) => {
  const session = await getSession();
  // the session here looks good
  const path = req.url.replace(/^https?:\/\/.*\/api/, '');
  const { method } = req;
  const options: {
    method: string;
    headers: Record<string, any>;
    body?: string;
  } = {
    method,
    headers: {
      authorization: `Bearer ${session?.accessToken}`,
      'Content-Type': 'application/json',
    },
  };

  if (method === 'POST') {
    options.body = JSON.stringify(await req.json());
  }

  const res = await fetch(`http://localhost:3000${path}`, options);
  const data = await res.json();
  // the data here is a successful response from the external API
  return new NextResponse(JSON.stringify(data), { status: res.status });
};

export const GET = withApiAuthRequired(handler);
```

I've tried around a lot. I could overread a limitation of the library with the new app directory. Hopefully, someone can help me :) But many thanks for the latest beta. Everything else works like a charm.

### Reproduction

1. Setup the required basic auth route
2. Setup a basic middleware handler with auth wrapper
3. setup an api route to call, can be without big logic, simple return
4. setup a server-side page with a server action and call it

### nextjs-auth0 version

3.0.0-beta.3

### Next.js version

13.4.7

### Node.js version

18.15.0

**Comment by lhimstedt** [comment]
@adamjmcgrath Hey, sorry, it looks like I can't add the beta label :)

**Comment by adamjmcgrath** [comment]
Thanks for raising this @lhimstedt 

We don't support protecting API routes with a Bearer access token (see https://github.com/auth0/nextjs-auth0/issues/1266#issuecomment-1607670837 for more info)

If you really want to access an API route from the server you'll need to pass along the cookie from the request to your fetch request, see here for example https://github.com/auth0/nextjs-auth0/issues/534#issuecomment-965584244

Although fetching an API route from server code is not recommended in Next, see https://github.com/auth0/nextjs-auth0/issues/534#issuecomment-965584244

**Comment by adamjmcgrath** [comment]
Closing as I believe https://github.com/auth0/nextjs-auth0/issues/1278#issuecomment-1621240460 answers your question
