### ISSUE TITLE
v3: Logout programmatically is not working when a returnTo URL is configured

### ISSUE THREAD

**Issue by juancaacuna** [auth0/nextjs-auth0#1279]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When trying to programmatically implement a logout of the system (not using a Logout button, but code), the returnTo is not well formed (HTTP redirect request 302). But if I try to logout using the button, it works.

I noticed that there is a preflight (OPTIONS request) that normally gets executed when hovering over the Logout button. If I hover over it, before programmatically logging-out (without clicking the button, but using a code logic), it works. Looks like there is something going on with that preflight.

### Reproduction

/app/api/auth/[auth0]/route.tsx
```
import { handleAuth, handleLogout } from "@auth0/nextjs-auth0";

export const GET = handleAuth({
  logout: handleLogout((req) => {
    return {
      returnTo: `${process.env.AUTH0_ISSUER_BASE_URL}/logout?returnTo=${process.env.AUTH0_BASE_URL}&client_id=${process.env.AUTH0_CLIENT_ID}`,
    };
  }),
  onError(req: Request, error: Error) {
    console.error(error);
  },
});

```

Then in the app:
```
setTimeout(() => window.location.pathname = "/api/auth/logout", 5000);
// Same behavior with any kind of redirect.
```

### nextjs-auth0 version

3.0.0-beta.2

### Next.js version

13.4.7

### Node.js version

20.3.0

**Comment by adamjmcgrath** [comment]
Hi @juancaacuna - thanks for raising this

> When trying to programmatically implement a logout of the system (not using a Logout button, but code), the returnTo is not well formed (HTTP redirect request 302). But if I try to logout using the button, it works.

Could you share the value for the returnTo? Ideally could you share a HAR file (with secrets redacted)

> Looks like there is something going on with that preflight.

You don't need a preflight if you're making a request in the use agent (`window.location = /foo`) and Next shouldn't be trying to prefetch that route if you're using an `A` tag.

**Comment by juancaacuna** [comment]
Hi @adamjmcgrath, thanks for your response. I was able to make it work by removing the `returnTo` value.
I was trying to redirect to auth0's logout endpoint after nextjs logout, but the SDK is already doing that by default.
