### ISSUE TITLE
Add doc sample for editing user profile metadata

### ISSUE THREAD

**Issue by robert-j-webb** [auth0/nextjs-auth0#1284]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I had a hard time figuring this out, and I understand it's out of scope for this project, but it's an incredibly common use case for developers who are starting using Auth0, so I think it's worth considering going the extra mile and trying to write a guide for it.

### Describe the ideal solution

I wrote a guide for it: https://robertjwebb.substack.com/p/creating-an-editable-user-profile

I think it could be a lot better. There's parts I don't understand and possibly a better way to do it. However, it is pretty focused and makes a good effort to explain parts of it.

**Comment by Widcket** [comment]
Hi @robert-j-webb, thanks for raising this and sharing your blog post.

In our examples we strive to focus on illustrating the core use cases, though I agree creating an editable user profile is something a lot of developers would find useful. However, an end-to-end example like that is probably better suited for a longer-form medium, like a blog post.

Thanks for the feedback, we really appreciate it.
