### ISSUE TITLE
TransientStore cookie name conflicts when using multiple Auth0 instances

### ISSUE THREAD

**Issue by mogzol** [auth0/nextjs-auth0#1297]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Preface: I'm using Next 13 and the v3 beta of this library, not sure if this issue exists in older versions.

In my app I have multiple instances of nextjs-auth0, since I need tokens for multiple audiences. In my UI I am trying to fetch these tokens simultaneously using fetch requests (with `prompt=none` so there's no login prompt). This almost works, but the issue I'm running into is that the cookies that TransientStore sets (`nonce`, `code_verifier`, `state`) are overwritten when I make multiple requests at once. So when the callback is hit, those cookies are no longer the same value.

There doesn't seem to be any way to override the TransientStore instance, or change the names of the cookies it sets. The only way I've found to work around this is by wrapping the login and callback handlers, and re-writing the request/response cookies before and after the handler. This isn't a great solution, it would be much better if I could just customize the TransientStore to add a prefix to cookies, but for now my solution at least works.

### Reproduction

1. Create multiple auth0 instances by making calls to `initAuth0`. Set the login auth params to `prompt: "none"`. (make sure you are already logged in so it works without prompt).
2. In the UI, send multiple login requests in parallel, handled by the different instances.
3. Observe that all but one of the requests will fail, due to the `code_verifier` cookie having an incorrect value.

Here's an example of my code. Note that I'm using a secondary `refresh` route for the promt-less logins: 

```js
function initInstance(name, audience) {
  const instance = initAuth0({
    routes: {
      callback: "/api/auth/callback?service=" + name,
    },
    authorizationParams: {
      audience,
    },
    session: { name: name + "Session", storeIDToken: name === "default" },
  });

  const handler = instance.handleAuth({
    onError(req, error) {
      console.error(error);
    },
    refresh: instance.handleLogin({
      authorizationParams: { prompt: "none" },
    }),
  });

  return { instance, handler };
}

export const authInstances = {
  default: initInstance("default", process.env.AUTH0_AUDIENCE),
  serviceA: initInstance("serviceA", process.env.AUTH0_AUDIENCE_SERVICE_A),
  serviceB: initInstance("serviceB", process.env.AUTH0_AUDIENCE_SERVICE_B),
};

// Next.js route handler
export const GET = (req, ctx) => {
  const { searchParams } = new URL(req.url);
  let service = searchParams.get("service");

  if (!service || !Object.hasOwnProperty.call(authInstances, service)) {
    service = "default";
  }

  return authInstances[service].handler(req, ctx);
};

// UI Component
export function UserAuth() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  useEffect(() => {
    Promise.all([
      fetch("/api/auth/refresh?service=serviceA", { mode: "no-cors" }),
      fetch("/api/auth/refresh?service=serviceB", { mode: "no-cors" }),
    ]).then(() => setIsAuthenticated(true));
  }, []);

  return !isAuthenticated ? null : "app content";
}
```

### Additional context

Here's the current solution I've come up with. I wrap the login and callback handlers with this function. Like I said, it's not ideal, but it does work:

```ts
function wrapHandler<T extends HandleLogin | HandleCallback, Opts extends Record<string, unknown>>(
  name: string,
  handler: T
): T {
  return ((reqOrOptions: NextRequest | Opts, ctx: AppRouteHandlerFnContext, opts?: Opts) => {
    const wrappedHandler = async (req: NextRequest, ctx: AppRouteHandlerFnContext, opts?: Opts) => {
      const cookieNames = ["nonce", "code_verifier", "state"];

      for (const cookieName of cookieNames.map((cookieName) => name + "." + cookieName)) {
        if (req.cookies.has(cookieName)) {
          const cookie = req.cookies.get(cookieName) as RequestCookie;
          req.cookies.delete(cookieName);
          cookie.name = cookieName.replace(name + ".", "");
          req.cookies.set(cookie);
        }
      }

      const response: NextResponse = await (handler as any)(req, ctx, opts);

      for (const cookieName of cookieNames) {
        const value = response.cookies.get(cookieName);
        if (value) {
          response.cookies.delete(value);
          value.name = name + "." + cookieName;
          response.cookies.set(value);
        }
      }

      return response;
    };

    if (reqOrOptions instanceof Request) {
      return wrappedHandler(reqOrOptions, ctx, opts);
    } else {
      return (req: NextRequest, ctx: AppRouteHandlerFnContext) =>
        wrappedHandler(req, ctx, reqOrOptions);
    }
  }) as T;
}
```

### nextjs-auth0 version

3.0.0-beta.3

### Next.js version

13.4.10

### Node.js version

20.4.0

**Comment by adamjmcgrath** [comment]
Hi @mogzol - thanks for raising this

Yep - happy to look at being able to customise the transaction cookie(s) name as we do [in the express sdk](https://auth0.github.io/express-openid-connect/interfaces/ConfigParams.html#transactionCookie)

Not sure when we might get round to looking at this, but will leave this open as an enhancement.

**Comment by adamjmcgrath** [comment]
Note: also useful to customise the transaction cookies Domain (see #1337) and SameSite (see https://github.com/auth0/express-openid-connect/issues/322)
