### ISSUE TITLE
Support for isLoading on client-side withPageAuthRequired

### ISSUE THREAD

**Issue by ybdiel** [auth0/nextjs-auth0#1302]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am using `afterRefetch` on the `profile` handler in order to call an external server and populate the user / session with some extra data. Sometimes the call takes a few milliseconds to load and when used in combination with `withPageAuthRequired`  on a client component, the component just stays blank until the loading has complete. There is no option to pass a custom component/text to display while `isLoading` nor the variable is being returned at all. 
Looking at `@auth0/nextjs-auth0/client` I suspect that the empty `return` statement is the issue.

```
const withPageAuthRequired: WithPageAuthRequired = (Component, options = {}) => {
  return function WithPageAuthRequired(props): JSX.Element {
    const { returnTo, onRedirecting = defaultOnRedirecting, onError = defaultOnError } = options;
    const { loginUrl } = useConfig();
    const { user, error, isLoading } = useUser();

    useEffect(() => {
      if ((user && !error) || isLoading) return;
    
     ...rest of the code...
};
```

### Describe the ideal solution

Allow for a component to be passed under `options` i.e. `{ onLoading: <div>Loading...</div> }`

**Comment by adamjmcgrath** [comment]
Hi @ybdiel - you can use [onRedirecting](https://auth0.github.io/nextjs-auth0/interfaces/client_with_page_auth_required.WithPageAuthRequiredOptions.html#onRedirecting)

This will show when `useUser` is loading regardless of wether the user is authenticated or not.

**Comment by ybdiel** [comment]
Thanks alot @adamjmcgrath , works like a charm
