### ISSUE TITLE
Types not working for custom Next.js client

### ISSUE THREAD

**Issue by jonahallibone** [auth0/nextjs-auth0#1321]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Types which worked prior to v3.0.0 no longer work in our custom setup

### Reproduction

1. Create a `[...auth0].ts`
2. Paste in the following code:

```
import { AuthError } from "@auth0/nextjs-auth0";
import type { NextApiRequest, NextApiResponse } from "next";
import auth0 from "util/auth0";
import { getFirst } from "util/get-first";

const audience = process.env.AUTH0_AUDIENCE;
const scope = "openid profile email offline_access read:current_user";

function getUrls(req: NextApiRequest) {
  const { host } = req.headers;
  const { query } = req;
  const returnPath = query.returnTo ? `/${getFirst(query.returnTo)}` : "";
  const protocol = process.env.VERCEL_URL ? "https" : "http";
  const baseRedirect = process.env.ENVIRONMENT_URL ?? `${protocol}://${host}`;
  const redirectUri = `${baseRedirect}/api/auth/callback`;
  const returnTo = `${baseRedirect}${returnPath}`;
  return {
    redirectUri,
    returnTo,
  };
}

export default auth0.handleAuth({
  async callback(req: NextApiRequest, res: NextApiResponse) {
    try {
      const { redirectUri } = getUrls(req);
      await auth0.handleCallback(req, res, {
        redirectUri,
        authorizationParams: {
          audience,
          scope,
        },
      });
    } catch (error) {
      console.error(error);
      if (error instanceof AuthError) {
        res.status(error.status || 500).end(error.message);
      }
    }
  },

  async login(req: NextApiRequest, res: NextApiResponse) {
    try {
      const { redirectUri, returnTo } = getUrls(req);

      await auth0.handleLogin(req, res, {
        authorizationParams: {
          prompt: "login",
          audience,
          scope,
          redirect_uri: redirectUri,
        },
        returnTo,
      });
    } catch (error) {
      console.error(error);
      if (error instanceof AuthError) {
        res.status(error.status || 400).end(error.message);
      }
    }
  },

  async logout(req: NextApiRequest, res: NextApiResponse) {
    const { returnTo } = getUrls(req);

    await auth0.handleLogout(req, res, {
      returnTo,
    });
  },
});
```

3. Notice the following errors regarding overloaded functions: 
<img width="469" alt="Screenshot 2023-07-27 at 1 56 28 PM" src="https://github.com/auth0/nextjs-auth0/assets/8886318/3c9fe278-9df5-41c8-a091-fba6f0d83c06">

```
Type '(req: NextApiRequest, res: NextApiResponse) => Promise<void>' is not assignable to type 'Handler'.
  Types of parameters 'req' and 'req' are incompatible.
    Type 'NextRequest' is missing the following properties from type 'NextApiRequest': query, env, aborted, httpVersion, and 52 more
```

4. Attempt to switch to `NextRequest` and make the API call an edge function
5. Get new type error in the same place:
```
Type '(req: NextRequest, res: NextResponse<unknown>) => Promise<void>' is not assignable to type 'Handler'.
  Types of parameters 'res' and 'ctx' are incompatible.
    Type 'AppRouteHandlerFnContext' is missing the following properties from type 'NextResponse<unknown>': cookies, [INTERNALS], headers, ok, and 13 more.
```

### nextjs-auth0 version

3.0.0.

### Next.js version

13.4.12

### Node.js version

20.1.0

**Comment by dkokotov** [comment]
ran into this as well when attempting to upgrade. with all the overloading of the handler signatures it's challenging to follow what is going.

**Comment by michaelschufi** [comment]
The `Handler` type seems to have 3 different overloads. One for App Router API routes, one for Page Router API routes, and one that handles both. However, you actually only ever need either the Page or App Route handlers in practice. 

So what I would propose is to hint to `handleAuth` if you are in the Pages or App Router. 
```ts
export default handleAuth<HandlersPageRoute> /* 👈 */ ({
  login: async (req: NextApiRequest, res: NextApiResponse) => {
    let lang = getSingleQueryValue(req.query.lang);

    return handleLogin(req, res, {
      authorizationParams: {
        lang,
      },
      getLoginState,
    });
  },
});
```

Similar, what you can do with `GetLoginState`.
```ts
export type GetLoginState = GetLoginStatePageRoute | GetLoginStateAppRoute;
```

This you can easily use like:
```ts
const getLoginState: GetLoginStatePageRoute = (req, loginOptions) => {
  let returnTo = getSingleQueryValue(req.query.returnTo);

  if (!returnTo) {
    returnTo = getBaseUrl();
  }

  return {
    ...loginOptions,
    returnTo,
  };
};
```

**Comment by adamjmcgrath** [comment]
@jonahallibone - as a workaround for the time being I recommend you do something like:

```ts
type ApiHandler = (req: NextApiRequest, res: NextApiResponse) => Promise<void>; /* 👈 */

export default auth0.handleAuth({
  async callback(req, res) {
    try {
      const { redirectUri } = getUrls(req);
      await auth0.handleCallback(req, res, {
        redirectUri,
        authorizationParams: {
          audience,
          scope
        }
      });
    } catch (error) {
      console.error(error);
      if (error instanceof AuthError) {
        res.status(error.status || 500).end(error.message);
      }
    }
  },

  async login(req, res) {
    try {
      const { redirectUri, returnTo } = getUrls(req);

      await auth0.handleLogin(req, res, {
        authorizationParams: {
          prompt: 'login',
          audience,
          scope,
          redirect_uri: redirectUri
        },
        returnTo
      });
    } catch (error) {
      console.error(error);
      if (error instanceof AuthError) {
        res.status(error.status || 400).end(error.message);
      }
    }
  },

  async logout(req, res) {
    const { returnTo } = getUrls(req);

    await auth0.handleLogout(req, res, {
      returnTo
    });
  }
} as { [key: string]: ApiHandler }); /* 👈 */
```

**Comment by jonahallibone** [comment]
@adamjmcgrath Curiously, do then handlers (auth/login/refresh etc) expect to be inside an app route or will they work fine inside an api route defined with `config = { runtime: "edge" }`. I don't think we are migrating over to the `app` router in the foreseeable future but we are very excited to be able to have our refresh and auth logic inside an edge handler instead of an api function

**Comment by dkokotov** [comment]
@adamjmcgrath thanks for looking into this so quickly. And fwiw I also have the same question as @jonahallibone above, so looking forward to your answer there (can the handlers be used inside a page api route with edge config). 

To your question about a better approach - why not export different versions of the various methods for the three use cases (app router, page router on node, page router on edge). I don't think a user of the library would ever need to reuse their code across those scenarios. 

I understand not wanting to maintain duplicate code, so internally you could still have them all forward to some shared code that is overloaded in the appropriate way - but from a public api perspective, having distinct imports from `@auth0/nextjs-auth0` vs `@auth0/nextjs-auth0/edge` vs `@auth0/nextjs-auth0/app` that have just the specific signatures for each use case would seem to be better DX. This would also mean as users we wouldn't need to add the type hinting to our code to get the compiler to know which overload it should be using, as is currently needed.

**Comment by jonahallibone** [comment]
@adamjmcgrath 

> @adamjmcgrath Curiously, do then handlers (auth/login/refresh etc) expect to be inside an app route or will they work fine inside an api route defined with `config = { runtime: "edge" }`. I don't think we are migrating over to the `app` router in the foreseeable future but we are very excited to be able to have our refresh and auth logic inside an edge handler instead of an api function

Any chance I could get some clarification on this?

**Comment by adamjmcgrath** [comment]
Answered in https://github.com/auth0/nextjs-auth0/issues/1333#issuecomment-1659855972

**Comment by benevbright** [comment]
Hi, @adamjmcgrath still having issue with 3.2.0 + page router

```
import { NextApiRequest, NextApiResponse } from "next";

import auth0 from "@lib/auth/auth0";

export default auth0.handleAuth({
  login: async (req: NextApiRequest, res: NextApiResponse) =>
    auth0.handleLogin(req, res, {
      authorizationParams: {
        invitation: req.query.invitation,
        organization: req.query.organization,
      },
    }),
});
```

![Screenshot 2023-10-12 at 12 06 17](https://github.com/auth0/nextjs-auth0/assets/916690/024894fa-00a9-431e-baf2-40fafaf28231)

**Comment by benevbright** [comment]
@adamjmcgrath the issue above is still present in 3.5.0 for page route
