### ISSUE TITLE
Custom Auth0 instance in [...auth0].ts not compatible with Edge Runtime

### ISSUE THREAD

**Issue by jonahallibone** [auth0/nextjs-auth0#1333]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Creating an edge compatible version of the `[...auth0].ts` handler in the `pages` directory is not possible.

### Reproduction

Create an `[...auth0].ts` file in `pages/api/auth` with the following content

```
import { type NextRequest, NextResponse } from "next/server";
import auth0 from "util/auth0-edge";

const audience = process.env.AUTH0_AUDIENCE;
const scope = "openid profile email offline_access read:current_user";

const getUrls = (req: NextRequest) => {
  const host = req.headers.get("host");
  const returnPath = `/${req.nextUrl.searchParams.get("returnTo")}`;
  const protocol = process.env.VERCEL_URL ? "https" : "http";
  const baseRedirect = process.env.ENVIRONMENT_URL ?? `${protocol}://${host}`;
  const redirectUri = `${baseRedirect}/api/auth/callback`;
  const returnTo = `${baseRedirect}${returnPath}`;
  return {
    redirectUri,
    returnTo,
  };
};

export const config = {
  runtime: "edge",
};

export const fetchCache = "force-no-store";

export default auth0.handleAuth({
  callback: async (req: NextRequest) => {
    const { redirectUri } = getUrls(req);

    return auth0.handleCallback(
      req,
      { params: {} },
      {
        redirectUri,
        authorizationParams: {
          audience,
          scope,
        },
      }
    );
  },

  login: async (req: NextRequest) => {
    const { redirectUri, returnTo } = getUrls(req);

    return auth0.handleLogin(
      req,
      { params: {} },
      {
        authorizationParams: {
          prompt: "login",
          audience,
          scope,
          redirect_uri: redirectUri,
        },
        returnTo,
      }
    );
  },

  logout: async (req: NextRequest) => {
    const { returnTo } = getUrls(req);

    return auth0.handleLogout(
      req,
      { params: {} },
      {
        returnTo,
      }
    );
  },
  onError(req: NextRequest, error: Error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  },
});
```
Upon trying to login, the app will yield
<img width="1735" alt="Screenshot 2023-07-31 at 1 19 44 PM" src="https://github.com/auth0/nextjs-auth0/assets/8886318/e21fe547-4556-4536-b2e4-5279d3edd704">

I suspec this has to do with my empty `params` but the lacking of typing on that `Record<string, string | string[]>` leaves me sort of unsure how to proceed with attaching the correct data. I assumed it was perhaps the auth0 instance but that seems wrong

### nextjs-auth0 version

3.0.1

### Next.js version

13.4.12

### Node.js version

20.1.0

**Comment by adamjmcgrath** [comment]
But, you should be able to use `getAccessToken` to refresh tokens in edge API handlers on the page router

**Comment by jonahallibone** [comment]
> But, you should be able to use `getAccessToken` to refresh tokens in edge API handlers on the page router

@adamjmcgrath Yea, that worked perfectly! Is it possible to have a similar handle auth to what we have in the page router, where we dynamically resolve the `returnTo` and `redirect_uri` from the previous request?

**Comment by adamjmcgrath** [comment]
@jonahallibone 

> Is it possible to have a similar handleAuth to what we have in the page router, where we dynamically resolve the returnTo and redirect_uri from the previous request?

Yes, you can do:

```ts
import { handleAuth, handleLogin, AppRouteHandlerFnContext } from '@auth0/nextjs-auth0';

export const GET = handleAuth({
  login(req: NextRequest, ctx: AppRouteHandlerFnContext) {
    const { redirectUri, returnTo } = getUrls(req);
    return handleLogin(req, ctx, {
      authorizationParams: {
        redirect_uri: redirectUri
      },
      returnTo
    });
  }
}
```
