### ISSUE TITLE
Logout isn't working with organizations / oidc

### ISSUE THREAD

**Issue by PatrickHeneise** [auth0/nextjs-auth0#1334]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm trying to implement a "full logout" of the application and auth0.

When calling `handleLogout`, I can see the following request in the debug logs:

```
nextjs-auth0:logout logout() with return url: 
nextjs-auth0:logout logging out of identity provider, redirecting to https://xyz.us.auth0.com/v2/logout?client_id=xyz123&returnTo=http%3A%2F%2Flocalhost%3A8080
```

it seems the request then comes back and there's another set of entries where `isAuthenticated` is false:

```
nextjs-auth0:logout logout() with return url: 
nextjs-auth0:logout end-user already logged out, redirecting to http://localhost:8080
```

I'm logged out in the application, but on auth0.com, I don't see any entry for "Logout" in Monitoring / Logs. When I click "Sign In", there's a Success Exchange and I'm immediately logged in again, without being prompted for username/password.

When I enter a returnUrl in the handler that's not registered, I get a Failed Logout entry, but with the auth0.com url, there's no log entry and the session cookie remains in place.

For the login, we're using `organizations`:

```
      await handleLogin(req, res, {
        authorizationParams: {
          audience: process.env.AUTH0_AUDIENCE,
          scope: 'offline_access openid profile email',
          invitation: req.query.invitation,
          organization: req.query.organization
        },
        returnTo: '/'
      })
```

Everything else is according to the examples.

### Reproduction

1. Example app, but with `organization` custom login
2. `logout: handleLogout`

### Additional context

As I understand from the documentation (https://auth0.com/docs/authenticate/login/logout/log-users-out-of-auth0) there should be a call to the `/oidc/logout` call?

I tried to compose a custom `returnUrl` with the `oicd/logout` url, but I can't find the `idTokenHint` in the session/cookie.

### nextjs-auth0 version

2.7.0, 3.0.1

### Next.js version

13.4.12

### Node.js version

18, 20

**Comment by adamjmcgrath** [comment]
Hi @PatrickHeneise - thanks for raising this

I'm not able to reproduce your issue using `nextjs-auth0@3.0.1` and logging in with an organization. After logout I'm prompted for my credentials the next time I attempt to login and I see a successful logout entry in my logs:

<img width="1083" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/1299658/7a3c7415-64f4-47c7-9086-86ca80995984">

> there should be a call to the /oidc/logout call?

This SDK uses our proprietary logout `/v2/logout` (the OIDC one is brand new and we haven't moved to that yet). But the proprietary one should work fine, and does when I test it.

> `logging out of identity provider, redirecting to https://xyz.us.auth0.com/v2/logout?...`

This should clear the session on `auth0.com` - which means you should be prompted for un/pw the next time you attempt to login.

Could you share a HAR file (with secrets redacted) and I'd be happy to investigate

**Comment by PatrickHeneise** [comment]
Thanks @adamjmcgrath ! I had an error in the logout handler of the sample app, now I have it working there with the same application / environment and the logout works and is registered in the auth0 logs:

#### sample

```
2023-08-01T15:19:16.876Z nextjs-auth0:logout logout() with return url: 
2023-08-01T15:19:16.877Z nextjs-auth0:stateless-session reading session from appSession cookie
2023-08-01T15:19:16.878Z nextjs-auth0:stateless-session found session, creating signed session cookie(s) with name 'appSession'(.i)
2023-08-01T15:19:16.879Z nextjs-auth0:logout logging out of identity provider, redirecting to https://xyz.us.auth0.com/v2/logout?client_id=123&returnTo=http%3A%2F%2Flocalhost%3A8081
```

#### my app

```
2023-08-01T15:20:47.739Z nextjs-auth0:stateless-session reading session from appSession cookie
2023-08-01T15:20:47.739Z nextjs-auth0:stateless-session found session, creating signed session cookie(s) with name 'appSession'(.i)
2023-08-01T15:20:47.740Z nextjs-auth0:logout logout() with return url: 
2023-08-01T15:20:47.742Z nextjs-auth0:logout logging out of identity provider, redirecting to https://xyz.us.auth0.com/v2/logout?client_id=123&returnTo=http%3A%2F%2Flocalhost%3A8081
```

not sure if that's an issue that the logout() call comes after looking for the session or not. The bigger difference comes after:

```
2023-08-01T15:20:47.907Z nextjs-auth0:logout logout() with return url: 
2023-08-01T15:20:47.907Z nextjs-auth0:logout end-user already logged out, redirecting to http://localhost:8081
```

that's in my app, but not in the sample. In this second call, `isAuthenticated` is already false; I wonder why there's a second call and if that interrupts / cancels the first call?

Either way, this seems to be an issue in my app, not in the sample, thanks for your help!

**Comment by adamjmcgrath** [comment]
> I wonder why there's a second call and if that interrupts / cancels the first call?

I'm not sure why there's 2 calls to logout, but concurrent calls to logout shouldn't to interrupts or cancel the logout request to the auth server.

**Comment by PatrickHeneise** [comment]
We'll investigate, if it's anything helpful I'll post the result here, but in the sample everything works so we know it's not a library issue.
