### ISSUE TITLE
Refresh token does not update custom claims on access token

### ISSUE THREAD

**Issue by michaelcummings12** [auth0/nextjs-auth0#1338]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I cannot figure out why the refresh token does not update custom claims on the access token.

I have a login action configured that adds custom claims (in this case, roles) to the access token. I call the management API from one of my API's to assign roles to users. I see these roles being added to the users in the Auth0 console, but they are not added to the access token, even after it is refreshed. The *only* way I was able to get it to refresh was by creating an <iframe /> and calling a silent login endpoint. But, this does not work in safari with cross-site tracking prevention.

I've tried adding middleware and calling `withMiddlewareAuthRequired` but that didn't seem to work either.

### Reproduction

1. Log in to the app
2. Update user roles
3. Refresh the page in the app. The user object from `useUser()` still has the old roles.

### nextjs-auth0 version

3.0.1

### Next.js version

13.4.12

### Node.js version

18.16.0

**Comment by adamjmcgrath** [comment]
Hi @michaelcummings12

> I have a login action configured that adds custom claims (in this case, roles) to the access token

The user object is made up of the user profile claims of the _ID Token_ (not the Access Token). ID tokens contain claims asserted about the authenticated user, Access tokens are used in token-based authentication to allow an application to access an external API. 

Therefore `useUser` will query the ID Token for user based claims and not the Access Token.

> 1. Log in to the app
> 2. Update user roles
> 3. Refresh the page in the app. The user object from useUser() still has the old roles.

Can you elaborate more on the "Update user roles" step. Could you share some code on how your refreshing the tokens and what your action is doing?

**Comment by michaelcummings12** [comment]
@adamjmcgrath Thank you for getting back to me. And thank you for clarifying. I can confirm that I have my ID token expiration set to 60 seconds.

The "update user roles" step is a custom action I created that runs during the **login** flow. That works fine because it's on the first login.

But, when I use the Auth Management API to assign/remove a role from a user, it does not apply until they log out and log back in (a bit of a security concern). There has to be a way to refresh the roles - I'm not sure what I'm missing.

**Comment by adamjmcgrath** [comment]
No problem @michaelcummings12

> they are not added to the access token, even after it is refreshed

Could you elaborate a bit more what mechanism you're using to refresh the tokens. And could you confirm that the tokens have changed, and also check them in jwt.io to confirm that the `roles` claim has been updated on the tokens.

**Comment by michaelcummings12** [comment]
I have `offline_access` in the scope, with a short access token expiration, so I just assumed the tokens would refresh automatically. I've seen people do like `{ refetch: true }`, which also didn't seem to work. Is there a method to manually refresh the token?

**Comment by adamjmcgrath** [comment]
@michaelcummings12 

If you call `getAccessToken` after your access token has expired,  and you have a refresh token, the SDK will use the Refresh Grant to get you a new access token (and id token).

If you don't want to wait until your access token is expired you can pass the `{ refresh: true }` config option to `getAccessToken`. ([more info in the API docs](https://auth0.github.io/nextjs-auth0/interfaces/session_get_access_token.AccessTokenRequest.html#refresh))

**Comment by adamjmcgrath** [comment]
I think https://github.com/auth0/nextjs-auth0/issues/1338#issuecomment-1667463770 answers your question so closing
