### ISSUE TITLE
Communicate with NextJS API using Postman

### ISSUE THREAD

**Issue by aorsten** [auth0/nextjs-auth0#135]
### Describe the problem you'd like to have solved
I want to be able to test my nextjs API with Postman. I have previously connected to Postman with Node Express Auth0, which seems to add an Authorization bearer header.

I believe the issue is that I need the ID and Access tokens to be stored in the session - which I do in my app with the initAuth0() method. How can I - if possible - achieve this using Postman? Seems I might need to add some optional parameters in the Oauth2.0 flow - which isn't possible yet in Postman?

**Comment by aorsten** [comment]
Nevermind - I just needed to call the api endpoint performing the login.

**Comment by jtlacci** [comment]
@aorsten do you mean that you called `localhost:3000/login` or your auth0 domain ? 

I have tried `localhost:3000/login` that just returns, the html login form
and I have tried `{{auth0_domain}}/oauth/token` that returns a bearer token that nextjs-auth won't recognise

**Comment by aorsten** [comment]
I used the login endpoint at localhost, e.g. localhost:3000/api/login. However I've struggled more with it, and figured out that it did work when I used the default auth0 domain (mytenant.auth0.com) in my localhost server, but it didn't work if I used my custom Auth0 domain (myauth.example.com).

So it wasn't directly straightforward.. 

BTW, writing this by memory while on my phone, so sorry if some urls or something are a bit off.

**Comment by mattveraldi** [comment]
I also still have this issue, I can get the auth token from postman using OAuth2, but then when I call my secured api it does return an error with this payload:
`
{
    "error": "not_authenticated",
    "description": "The user does not have an active session or is not authenticated"
}
`
The token is correctly inserted in the headers of the request, so i can't figure out what is going on

**Comment by adamjmcgrath** [comment]
@mattveraldi 

> The token is correctly inserted in the headers of the request, so i can't figure out what is going on

This SDK protects API routes with an encrypted session cookie (not Bearer Access Token in the Authorization header)

So you would need a valid cookie, that you would get in a browser when logging in through a UI.

**Comment by mattveraldi** [comment]
> @mattveraldi 
> 
> > The token is correctly inserted in the headers of the request, so i can't figure out what is going on
> 
> This SDK protects API routes with an encrypted session cookie (not Bearer Access Token in the Authorization header)
> 
> So you would need a valid cookie, that you would get in a browser when logging in through a UI.

Thank you, it finally makes sense to me. So the only way to use Postman is importing a valid cookie generated in the browser and then call the APIs that I want to test?

**Comment by adamjmcgrath** [comment]
No problem @mattveraldi 

> So the only way to use Postman is importing a valid cookie generated in the browser and then call the APIs that I want to test?

Correct 👍

**Comment by mattveraldi** [comment]
Thank you 😁

**Comment by vertis** [comment]
Which of course makes the nextjs-auth0 useless if you want to use it to protect API routes with a mobile app.
