### ISSUE TITLE
if i use AfterCallback to add a custom session property,  the type from getSession() does not include that custom property

### ISSUE THREAD

**Issue by Jared-Dahlke** [auth0/nextjs-auth0#1358]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm using https://auth0.github.io/nextjs-auth0/types/handlers_callback.AfterCallbackPageRoute.html to add a custom property to session (favoriteColor).

Now my types are inaccurate so i have to create a custom type and cast all of my session references like this:
```
const session = (await getSession(req, res)) as Session & { favoriteColor: string }
```

Is there a better way to handle this?

### Reproduction

1. add a custom property to session

```
const afterCallback = async (req, res, session, state) => {
 return {
   ...session,
   favoriteColor: 'green'
}

export default handleAuth({
  async callback(req, res) {
    try {
      await handleCallback(req, res, { afterCallback });
    } catch (error) {
      console.log('errir in callback', error)
      res.status(error.status || 500).end();
    }
  },
    async login(req, res) {
      await handleLogin(req, res, {
        authorizationParams: {
            audience: `${process.env.AUTH0_ISSUER_BASE_URL}/api/v2/`,
            scope: process.env.AUTH0_SCOPE,
        },
        returnTo: paths.HOME,
      })
    },
   
  });

```

2.
try to use this in getServerSideProps for example
```
const session = await getSession()
const favColor = session.favoriteColor
```

expected: no type error
actual: there is type error, session doesn't know about the custom property

### nextjs-auth0 version

3.1.0

### Next.js version

13

### Node.js version

16

**Comment by adamjmcgrath** [comment]
Hi @Jared-Dahlke - thanks for raising this

You should add custom user profile settings to `session.user`, then you wont get a type error (favoriteColor will be `any` because https://github.com/auth0/nextjs-auth0/blob/main/src/session/session.ts#L12)

```js
const afterCallback = async (req, res, session, state) => {
 return {
   ...session,
   user { ...session.user, favoriteColor: 'green' }
  }
}
```

**Comment by adamjmcgrath** [comment]
Closing as I believe https://github.com/auth0/nextjs-auth0/issues/1358#issuecomment-1674801955 has answered your question
