### ISSUE TITLE
Allow manual refresh for access token

### ISSUE THREAD

**Issue by mattjennings** [auth0/nextjs-auth0#136]
### Describe the problem you'd like to have solved

It would be helpful to let us force an access token refresh rather than waiting for them to expire. The scenario I've run into is updating a user's claims after they've updated their profile.

### Describe the ideal solution

Adding a `refresh` option to the `getAccessToken` method, like so: `tokenCache.getAccessToken({ refresh: true })`

## Alternatives and current work-arounds

This is my workaround, but it doesn't seem to always work.

```ts
const tokenCache = auth0.tokenCache(req, res)
const session = await auth0.getSession(req)

session.accessTokenExpiresAt = 1
await tokenCache.store.save(req, res, session)

// now it will refresh
const { accessToken } = await tokenCache.getAccessToken() 
```

**Comment by sandrinodimattia** [comment]
This is now available in v0.16 👍
