### ISSUE TITLE
Add support to pass a handler for unauthenticated users to withMiddlewareAuthRequired

### ISSUE THREAD

**Issue by santiagogdo** [auth0/nextjs-auth0#1360]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

So, the `withMiddlewareAuthRequired` automatically redirects the user to the login endpoint if the user is not authenticated. The middleware accepts a function to be ran when the user is authenticated, but not for when the user is not.

I found myself needing to pass some custom parameters to the Auth0 login page, which I can't if I use `withMiddlewareAuthRequired` because I have no control over the scenario where a user is not authenticated.

### Describe the ideal solution

The ideal solution would be that `withMiddlewareAuthRequired` accepts handlers for both case scenarios, when the user is authenticated, and when it is not.

For example, the handler could be used to override the existing logic that is executed when the user is not authenticated.

Another option would be to accept an object to pass custom parameters to be included in the redirection to the login endpoint.

### Alternatives and current workarounds

My current workaround is to not use `withMiddlewareAuthRequired` and instead use a custom middleware. This is not ideal since it pretty much does the same than what the existing `withMiddlewareAuthRequired` function does, but adds the support for the other handler, which results in most of the code being redundant since the library already provides most of that code in the `withMiddlewareAuthRequired` middleware.

**Comment by adamjmcgrath** [comment]
Thanks for raising this @santiagogdo 

All this handler does is redirect to the login route if the user is not authenticated - so if you want to have different behaviour, it makes sense to create your own middleware as you are doing already

**Comment by milosjovancevic** [comment]
Hey @santiagogdo 
I am also in dire need of providing `redirectTo` for when users try to access a page and are not logged in. Need a way to redirect them to initial url. I am using `withPageAuthRequired` tho.
Anyways, would you mind sharing ur `middleware`?
Thanks

**Comment by Jared-Dahlke** [comment]
this works for me in middleware.ts

```
// app/_middleware.ts
import { getSession } from "@auth0/nextjs-auth0/edge";
import { NextRequest, NextResponse } from "next/server";

export async function middleware(req: NextRequest) {
  const { nextUrl } = req;
  const session = await getSession(); // Replace with your method to get the session

  const isProtectedRoute = nextUrl.pathname.startsWith("/app");
  // If the user is not authenticated and is trying to access a protected route
  if (!session && isProtectedRoute) {
    const loginUrl = new URL("/api/auth/login", req.url);
    // set returnTo to be where the user was trying to go
    loginUrl.searchParams.set("returnTo", req.nextUrl.pathname);
    return NextResponse.redirect(loginUrl);
  }

  return NextResponse.next();
}


```
