### ISSUE TITLE
unable to call external api using server component

### ISSUE THREAD

**Issue by Jared-Dahlke** [auth0/nextjs-auth0#1366]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

i am trying to call auth0 management api in a server component like this:

```
// app/protected/page.js   

import { getSession } from "@auth0/nextjs-auth0";

async function getData() {
  const session = await getSession();
  console.log('sessss', session) // this seems to log out correctly as if the session is there / good to go
  const res = await fetch(`${process.env.AUTH0_ISSUER_BASE_URL}/api/v2/users/${session?.user?.sub}`, {
    headers: {
      Authorization: `Bearer ${session.access_token}`,
    },

  })
  
 
  return res.json()
}

const Protected = async () => {

  const response = await getData()

  console.log('response',response)

  return (
    <PageLayout>
      <div className="content-layout">
        <h1 id="page-title" className="content__title">
          Protected Page
        </h1>
        <div className="content__body">
          <p id="page-description">
            <span>
              This page retrieves a <strong>protected message</strong>.
            </span>
            <span>
              <strong>Only authenticated users can access this page.</strong>
            </span>
          </p>
          <CodeSnippet title="Protected Message" code={response.data} />
        </div>
      </div>
    </PageLayout>
  );
};

export default Protected;

```

but i am getting an error for my response:
```
response {
  statusCode: 400,
  error: 'Bad Request',
  message: 'Bad HTTP authentication header format',
  errorCode: 'Bearer'
}
```

### Reproduction

try to fetch data from external api in server side component in next13 app dir.
observe error

### nextjs-auth0 version

"@auth0/nextjs-auth0": "^3.0.0",

### Next.js version

 "next": "13.4.5",

### Node.js version

20

**Comment by adamjmcgrath** [comment]
Hi @Jared-Dahlke 

In order to call the management api you need to specify the *audience* of that api when you login (in this case that would be `https://{yourAuth0Domain}/api/v2/`). You also need to specify the *scope* that gives you access to the [/api/v2/users/{userId} endpoint](https://auth0.com/docs/api/management/v2/users/get-users-by-id) - in this case that would be `read:current_user`

See this example for how to specify the scope and audience https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#access-an-external-api-from-an-api-route

**Comment by Jared-Dahlke** [comment]
thank you!
