### ISSUE TITLE
Using getAccessToken from server component

### ISSUE THREAD

**Issue by NiallRees** [auth0/nextjs-auth0#1372]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

We're looking to migrate to the new app directory. Currently, we use `getServerSideProps` and its [context](https://nextjs.org/docs/pages/api-reference/functions/get-server-side-props) parameter to access the `req` and `res` needed to call this library's `getAccessToken` function in order to make authenticated API calls to another Auth0-protected application. Using the new server components, we'll need to drop `getServerSideProps` for `fetch`es directly in the components themselves. We'll still need to use `getAccessToken` though to authenticate the requests. What I can't understand is how we can use `getAccessToken` when there's no longer access to the `context.req` (`NextApiRequest`) and `context.res` (`NextApiResponse`) objects.

It seems we might need a new method in this library which accepts the required headers using https://nextjs.org/docs/app/api-reference/functions/headers#headers?

### Describe the ideal solution

Be able to call `getAccessToken` from a server component.

### Additional context

Thanks a lot!

**Comment by adamjmcgrath** [comment]
Hi @NiallRees - thanks for raising this

> It seems we might need a new method in this library which accepts the required headers using [nextjs.org/docs/app/api-reference/functions/headers#headers](https://nextjs.org/docs/app/api-reference/functions/headers#headers)?

You can call `getAccessToken` with no args and this will use `next/headers` - the [API docs](https://auth0.github.io/nextjs-auth0/types/session_get_access_token.GetAccessToken.html) are a little light on examples for this so I'll add some.

**Comment by NiallRees** [comment]
Oh awesome! Appreciate the quick response @adamjmcgrath

**Comment by AbhinawRatan** [comment]
According to the [Auth0 documentation], to access your API, you must request an access token when authenticating a user. You can do this by making a POST call to the token URL with the required parameters such as grant_type, client_id, client_secret, and audience. The response will contain an access_token value that you can use to authenticate your requests.
