### ISSUE TITLE
Support for using handlers that return a `Response` with `getSession(req, res)`

### ISSUE THREAD

**Issue by FeldrinH** [auth0/nextjs-auth0#1373]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Maybe I'm missing something obvious but it seems like there is no reliable way to use `getSession(req, res)` with a handler function that **returns** a `Response` that is constructed somewhere inside the handler logic.

Consider for example this NextJS route handler based on this [example](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#app-router-1):
```typescript
function myHandler(req: Request): Response {
    // Some opaque logic (e.g. calling a tRPC fetchRequestHandler)
}

withApiAuthRequired(async req => {
    const res = new NextResponse();
    const { user } = await getSession(req, res);
    const handlerRes = myHandler(req);
    return // What to put here?
});
```
As far as I can tell there is no good way to construct an appropriate NextResponse that combines the body and other attributes from `myHandler` and the cookie changes from `getSession`.

### Describe the ideal solution

I'm honestly not sure what the best approach would be. Maybe it would be possible to add a helper that combines two `NextResponse`/`Response` objects by overwriting the attributes of the first with attributes of the second.

It is also possible that simply using `getSession()` without any arguments is completely valid and safe in this context. If that is the case then  that should be documented / added as an example.

### Alternatives and current workarounds

If you know what parts of the handler response are relevant then you can manually copy those fields into a new `NextResponse`, but that breaks encapsulation.
You can also use a `getSession()` without arguments, but that might introduces some kind of issues with cookie handling.

**Comment by adamjmcgrath** [comment]
> Options 2. and 3. are impossible in this case, because my problem is specifically with situations where myHandler contains code that I don't control, for example calls to an external library

I still think `myHandler` is at fault here. Because you can write to the response before _and_ after using `getSession`, but you can _only_ write to the response after calling `myHandler`. As things that you can run in a route handler goes, `getSession` is being a better citizen than `myHandler`

**Comment by FeldrinH** [comment]
> I still think myHandler is at fault here.

I don't necessarily disagree, but if myHandler consists of code that comes from an external library then there isn't much that the average developer can do about it.

**Comment by FeldrinH** [comment]
> getSession comes from an external library 😄

That's fair enough I guess, but there's two reasons why I felt that appraching the Next Auth0 integration with this problem would be easier and more productive:
* The Auth0 Next integration is just one library, but there are a lot of libraries that export some kind of API handler (for example tRPC, oneRPC, apollo-server-integration-next)
* Next App Router Route Handlers generally have the signature `(req: NextRequest) => NextResponse`, so most libraries export handlers with a compatible signature. Trying to convince all of those libraries that they should take in a partial `NextResponse` in order to support Auth0 and other similar integrations even though Next doesn't require them to seems like a harder case to make.
