### ISSUE TITLE
CallbackHandlerError: Callback handler failed. CAUSE: Missing state cookie from login request (check login URL, callback URL and cookie config).

### ISSUE THREAD

**Issue by nicosuave** [auth0/nextjs-auth0#1377]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I've integrated this library with my Next.JS app. Runs fine locally having followed all the directions for App Router. However, I'm seeing the failure in the title when deploying. 

```
CallbackHandlerError: Callback handler failed. CAUSE: Missing state cookie from login request (check login URL, callback URL and cookie config).
```

### Reproduction

It's a consistently reproducible problem; not sure a repo itself following the directions in the readme that runs fine locally is helpful.

### Additional context

Seems this has come up recently for a few others as well in a [closed issue](https://github.com/auth0/nextjs-auth0/issues/1063#issuecomment-1661705096).

Thus far, I've tried:

- Deploying my app with the development server, no dice
- Logging all env vars to make sure configuration was identical with my local development setup and aligns with the mentioned configuration in the readme in this repo
  - Committing my (to be rotated) local secrets (in .env) to ensure my deployed setup was not awry
- Configuring my login URL in the Auth0 dashboard (not mentioned in the docs for this library, but mentioned in the error message?)
- Removing all users in Auth0 in case some issue with them coming in on a different URL (localhost vs xyz for the deployed version)

### nextjs-auth0 version

3.0.0 & 3.1.0

### Next.js version

13.4.12

### Node.js version

20.1.0

**Comment by nicosuave** [comment]
Feels like some hostname related issue for apps configured with multiple allowed domains— I'm at about wit's end here

**Comment by nicosuave** [comment]
Can confirm the cookie is being set appropriately as well on the correct (sub) domain (same as the one configured for all the various urls, aside from the Auth0 tenant).

**Comment by nicosuave** [comment]
Auth0 logs also check out; all successful logins

**Comment by adamjmcgrath** [comment]
@nicosuave - thanks for raising this

> Missing state cookie from login request (check login URL, callback URL and cookie config).

This usually means that the cookie being set in your login URL can't be read by your callback URL. This can be because of a protocol or hostname mismatch between the 2 URLs, or strict cookie configuration of the SDK or browser.

If you share a HAR file (with secrets redacted) - I can probably tell you what it is specifically.

**Comment by reubenjh** [comment]
I've been dealing with this same issue in my page router app `next.js 13.4.13` `nextjs-auth0 3.1.0` for about 3 months and it's driven me crazy. Same situation - Auth0 logs show successful logins, but the state cookie just doesnt seem to get picked up. 

I keep finding myself thinking it must be something to do with browser cookie config. Or some quirk of the fact I have auth happening for 2 different domains, with sessions shared across applications. Users can log into one application, then when they initiate the login flow on the other it will log them in without the need for entering their credentials. Perhaps this is something to do with them having a session on another application and the cookies assigned to that domain. Does this sound familiar @nicosuave?

Following in case your HAR file investigation bears fruits too

**Comment by exchai93** [comment]
I am also getting the same error but  **locally** when starting the server up and going to the log in page, although this works initiailly when in incognito. 

**Nextjs-auth0 version ^2.7.0

Next.js version ^13.0.0

Node.js version v18.1.0**

Have logged the env var's that match and also printing the request cookies and url out in the callback

cookies 
```
{
  mp_38f48ef59266902a401199220ea29b4c_mixpanel: '{"distinct_id": "auth0|64020ae85bb1eaa344460806","$device_id": "18852ddfebd991-0bb79a766fc7c68-412d2c3d-16a7f0-18852ddfebe645","$initial_referrer": "$direct","$initial_referring_domain": "$direct","$user_id": "auth0|64020ae85bb1eaa344460806"}'
}
```

url` /api/auth/callback?code=gGkhuykzJIXzOWFtvGVah0PLyG3RzeVpmwy51wOIu5aot&state=eyJyZXR1cm5UbyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMC8ifQ`

Any thoughts on how else to solve this 👀

**Comment by adamjmcgrath** [comment]
@nicosuave - am closing this, feel free to update this thread with a HAR if you want me to reopen and investigate

@exchai93 - please refer to https://github.com/auth0/nextjs-auth0/issues/1377#issuecomment-1685876780 for advice on what the issue might be. And feel free to raise a new issue and provide a HAR file if you want me to investigate

**Comment by reubenjh** [comment]
This turned out in my case to be due to users opening multiple tabs on the login page, then logging in on one that isnt the most recent, as the old state cookies get invalidated when you arrive at the login page (afaik)
