### ISSUE TITLE
Missing details in decoded session

### ISSUE THREAD

**Issue by chubibest** [auth0/nextjs-auth0#138]
When I call the auth0.getSession method on the ‘@auth0/auth0-react’ SDK. I do not get the username as part of the profile data.

### Reproduction

- In a Nextjs app import the SDK and initialize it with the following details
 ```
initAuth0({
  domain,
  clientId,
  clientSecret,
  scope: "openid profile email",
  redirectUri,
  postLogoutRedirectUri,
  session: {
    cookieSecret,
    cookieLifetime: 60 * 60 * 8,
    storeIdToken: false,
    storeAccessToken: false,
    storeRefreshToken: false,
  },
  oidcClient: {
    httpTimeout: 2500,
    clockTolerance: 10000,
  },
});
```

- Call the 'getSession' method on the instance you initialized in the 'getServerSideProps' method of a protected page.

### Expected Behavior
The Profile data  returned, should contain the user's username for a logged in user.
### Issue
The Profile data  returned, does not contain the user's username for a logged in user.
![Screenshot from 2020-07-04 11-25-33](https://user-images.githubusercontent.com/45321587/86510796-e1696880-bdea-11ea-8348-a0bb251223ee.png)

### Environment
- **Version of this library used: 0.13.0**

**Comment by sandrinodimattia** [comment]
You'll need to add that claim to the id_token. Reference: https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims

**Comment by chubibest** [comment]
Here are some of the claims I have tried 'openid profile email  sub name given_name preferred_username' not of which appears to produce the desired effect.

**Comment by Widcket** [comment]
Hi, you need to use a Rule to add the username to the ID Token as a custom claim: https://community.auth0.com/t/is-there-a-way-to-include-username-as-a-claim-using-resource-owner-password-grant-access-tokens/18769/2
