### ISSUE TITLE
Cypress login on page with withPageAuthRequired fails with "Missing state cookie from login request" error

### ISSUE THREAD

**Issue by maxvostrikov** [auth0/nextjs-auth0#1392]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When navigating to a page with `export const getServerSideProps = pageRouterAuth.withPageAuthRequired();` for the first time without being logged in, the login fails with Cypress.
The error message is:
```
CallbackHandlerError: Callback handler failed. CAUSE: Missing state cookie from login request (check login URL, callback URL and cookie config).
    at eval (webpack-internal:///(api)/../dist/handlers/callback.js:74:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(api)/../dist/handlers/auth.js:79:13) {
  code: 'ERR_CALLBACK_HANDLER_FAILURE',
  cause: MissingStateCookieError: Missing state cookie from login request (check login URL, callback URL and cookie config).
      at eval (webpack-internal:///(api)/../dist/auth0-session/handlers/callback.js:17:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async eval (webpack-internal:///(api)/../dist/handlers/callback.js:71:16)
      at async eval (webpack-internal:///(api)/../dist/handlers/auth.js:79:13) {
    status: 400,
    statusCode: 400
  },
  status: 400
}
```

- The problem is not reproducible without Cypress - so I can log in with my browser with the same actions
- The environment variables, login URL, callback URL and cookie config seems to be correct, as the login with other means works
- If I visit the `/api/auth/login` link first and login, the page with `withPageAuthRequired` can be visited without errors.

So the error happens only with Cypress and if the `withPageAuthRequired` method did the redirect to the login.

### Reproduction

1. Add the following tests to the example app smoke suite (https://github.com/auth0/nextjs-auth0/blob/5aff8afb9ce37ce96f27195c28f9b187866c3f47/cypress/e2e/smoke.cy.ts#L26):

```
    it('should able to visit ssr page', () => {
      cy.visit('/');
      cy.get('[data-testid=login]').click();
      login();
      cy.visit('/page-router/profile-ssr');
      cy.get('[data-testid=logout]').should('exist');
    });

    it('fails to visit ssr page directly', () => {
      cy.visit('/page-router/profile-ssr');
      login();
      cy.get('[data-testid=logout]').should('exist');
    });
```
2. Launch the example app and Cypress. Run the two new tests

The first test passes.
The second test fails on Cypress.
But I can't reproduce the same error manually in a browser, without Cypress

### Additional context

Cypress version: 12.2.0 (also tried 11.2.0, 12.17.3)

### nextjs-auth0 version

4.1.0

### Next.js version

13.4.12

### Node.js version

9.6.7

**Comment by adamjmcgrath** [comment]
Thanks for raising this @maxvostrikov

I've had a look at the tests you've shared and I'm able to get them to work by changing the `auth_verification` transaction cookie same site to "none" (set the env var `AUTH0_TRANSACTION_COOKIE_SAME_SITE=none`)- this wont work in the "real world" because the page protocol is `http` (so you should only attempt this in your Cypress tests) - this seems like a similar workaround to the one proposed here https://github.com/cypress-io/cypress/issues/25454#issuecomment-1614762265 

<img width="290" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/1299658/e9da24ec-0410-4138-a84a-94d2e18d4113">

The underlying issue seems to be one with cypress - so I suggest you raise an issue there if you want it to work with your default transaction cookie settings.

**Comment by christ776** [comment]
I was having this issue too, and `AUTH0_TRANSACTION_COOKIE_SAME_SITE=none` fixed it, thanks!
