### ISSUE TITLE
Callback on Callback

### ISSUE THREAD

**Issue by niicojs** [auth0/nextjs-auth0#14]
### Describe the problem you'd like to have solved

I would like to be able to handle additionnal code on login callback. For example only allpw authentication in user is in a role

### Describe the ideal solution

Beeing able to add a callback to `auth0.handleCallback` that would allow me to return 401.

## Alternatives and current work-arounds

People are probably doing this in another way, please advice :)

**Comment by HurricaneInteractive** [comment]
@niicojs Another issue had this query. Have a look at the [comment I left](https://github.com/auth0/nextjs-auth0/issues/83#issuecomment-591778387) (auth0 hooks, may not apply though)

Hopefully, it helps in some way

**Comment by sandrinodimattia** [comment]
This is now supported in v0.12:

```js
await auth0.handleCallback(req, res, {
  onUserLoaded: async (req, res, session, state) => {
    throw new Error('You are not allowed to sign in');
  }
});
```

**Comment by chalupagrande** [comment]
@sandrinodimattia: neither `session` nor `state` contains the user role. How am I able to find the user role and restrict access?
