### ISSUE TITLE
Refetch with `storeAccessToken` set to `false`

### ISSUE THREAD

**Issue by craigbilner** [auth0/nextjs-auth0#140]
### Description

I'm not sure if it's by design or a bug but it appears that you need to change the default `storeAccessToken` setting to `true` if you would like to use the `refetch` option. It looks like it's by design in that `refetch` is updating the session so perhaps the docs need to explicitly call this dependency out?

### Reproduction

The README for `refetch` shows:

```
import auth0 from '../../utils/auth0';

export default async function me(req, res) {
  try {
    await auth0.handleProfile(req, res, { refetch: true });
  } catch (error) {
    console.error(error);
    res.status(error.status || 500).end(error.message);
  }
}
```

Though the default config has:

```
// (Optional) Store the access_token in the session. Defaults to false.
    storeAccessToken: false,
```

When using `refetch` it tries:

```
const { accessToken } = yield tokenCache.getAccessToken();
```

Which implies it needs to be in the session. 

In `getAccessToken` it then fails on:

```
if (!session.accessToken && !session.refreshToken) {
````

### Environment

- **Version of this library used:** - `0.13.0`
- **Version of the platform or framework used, if applicable:** - Next `9.4.4`
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by Widcket** [comment]
Hi @craigbilner, this is now fixed in the 1.0.0 beta.
