### ISSUE TITLE
NextJs 13 (app dir) requestAsyncStorage Error when calling next/headers cookies

### ISSUE THREAD

**Issue by Avital103** [auth0/nextjs-auth0#1413]
### Checklist

- [x] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi
I am encountering an issue when attempting to access Next.js cookies in the `/api/auth/[auth0]/route.js` file. 

The error message I'm encountering is:

![image](https://github.com/auth0/nextjs-auth0/assets/75247845/750b5afc-a5d3-439d-aaab-1eb0835ee81a)

> error node_modules\next\dist\client\components\headers.js (50:14) @ cookies
error Error: Invariant: Method expects to have requestAsyncStorage, none available
    at cookies (webpack-internal:///(sc_server)/./node_modules/next/dist/client/components/headers.js:46:15)
    at checkCookie (webpack-internal:///(sc_server)/./src/app/api/auth/[auth0]/route.js:16:78)
    at eval (webpack-internal:///(sc_server)/./src/app/api/auth/[auth0]/route.js:33:27)

Thank you for your assistance in resolving this issue.

### Reproduction

Change the `/api/auth/[auth0]/route.js` file to:

```javascript
import {handleAuth, handleLogin} from '@auth0/nextjs-auth0';
import { redirect } from 'next/navigation'
import {cookies} from 'next/headers';

const getCookie = () => {
    const cookieStore = cookies();
    return cookieStore.get('<cookie-name>').value;
};

export const GET = handleAuth({
    login: handleLogin({
        authorizationParams: {
            organization: getCookie()
        }
    }),

    onError(req, error) {
        console.error(error);
        return redirect('/auth/error');
    }
});
```

### Additional context

It's important to note that 'next/headers' cookies works perfectly on different routes.

### nextjs-auth0 version

^3.1.0

### Next.js version

13.4.2

### Node.js version

v18.17.1

**Comment by adamjmcgrath** [comment]
Hi @Avital103 - thanks for raising this

This error is because you are calling `cookies()` outside of the context of a request:

```js
// Your code:
export const GET = handleAuth({
    login: handleLogin({
        authorizationParams: {
            organization: cookies().get('<cookie-name>').value
        }
    }),
})

// this is effectively the same as
const organization = cookies().get('<cookie-name>').value; // no request happening

export const GET = handleAuth({
    login: handleLogin({
        authorizationParams: {
            organization
        }
    }),
})
```

You need to call `cookies()` in a request. You can evaluate the login options at request time by passing a method to `handleLogin` eg

```js
export const GET = handleAuth({
  login: handleLogin(() => ({
    authorizationParams: {
      organization: cookies().get('<cookie-name>').value
    }
  }))
});
```

**Comment by Avital103** [comment]
Hi @adamjmcgrath 
I appreciate your input.

I hold a different perspective on this statement:

> you are calling cookies() outside of the context of a request

I am invoking it within a function called getCookie, which is subsequently called during the request execution. 

However, attempting your suggested approach still results in the same error:
![image](https://github.com/auth0/nextjs-auth0/assets/75247845/c35f4903-21bd-45a6-a862-872c36f429f5)
