### ISSUE TITLE
Module not found: Can't resolve 'supports-color'

### ISSUE THREAD

**Issue by piotrkulpinski** [auth0/nextjs-auth0#1424]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, 
I'm setting up auth with this package and I've run into an issue after installing it. 

The NextJS server is throwing the following warning: 
```
- warn ./node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/node.js
Module not found: Can't resolve 'supports-color' in '.../app/node_modules/.pnpm/debug@4.3.4/node_modules/debug/src'

Import trace for requested module:
./node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/node.js
./node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/index.js
./node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/auth0-session/utils/debug.js
./node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client/node-client.js
./node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/index.js
```

### Reproduction

1. Install the package with latest NextJS.
2. Run the server
3. Watch console

### nextjs-auth0 version

3.1.0

### Next.js version

13.4.19

### Node.js version

16.20.0

**Comment by adamjmcgrath** [comment]
Hi @piotrkulpinski - thanks for raising this

This looks like an open issue with `debug` see https://github.com/debug-js/debug/issues/912 for a workaround

**Comment by adamjmcgrath** [comment]
@piotrkulpinski `debug` attempts to `require('supports-color')` and fails silently if it's not available (see https://github.com/debug-js/debug/blob/master/src/node.js#L115) so this warning can be safely ignored. If you don't want this warning you can install `supports-color` yourself (although [make sure you install 8 - not 9](https://github.com/debug-js/debug/issues/912)).

I'm reluctant to add `supports-color@8` to this repo and make everyone include it in this bundle if it's not needed, so I suggest this is kept as advice.
