### ISSUE TITLE
Allow configuring network requests to auth0 to go through proxy

### ISSUE THREAD

**Issue by ryanolson-aumni** [auth0/nextjs-auth0#1425]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

openid-client and this library each make certain network requests. With new corporate policies at my company, we need these requests to go through a proxy. It appears as though node-openid-client allows you to extend the options for the HTTP requests made. @auth0/nextjs-auth0 doesn't allow that in its configuration. Right now, we're really struggling to come up with a good solution for proxying requests made by this library.

### Describe the ideal solution

The ideal solution would be to allow an environment variable called AUTH0_HTTP_PROXY that would automatically proxy requests through a proxy.

The less ideal solution would be to allow configuration options that let users override certain request options for openid-client usage.

### Alternatives and current workarounds

None

**Comment by adamjmcgrath** [comment]
Hi @ryanolson-aumni - thanks for raising this

`node-openid-client` allows you to pass an `agent` option which we can add support for.

**Comment by adamjmcgrath** [comment]
Hi @ryanolson-aumni - I wont be able to get to this request this week, you're welcome to raise a PR - thanks
