### ISSUE TITLE
Include links to instructions on dockerization and deployment to other platforms in the README.md

### ISSUE THREAD

**Issue by barrynorthern-tf** [auth0/nextjs-auth0#1434]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am unable to deploy to Vercel and need to dockerize my Next.js application. The nextjs-auth0 README section 'Deployment' only contains a link to how to deploy on Vercel. I am worried about using the middleware because it uses the Edge Runtime, and I am not sure if/how to get this working outside of a Vercel deployment.

### Describe the ideal solution

Add instructions to the README section 'Deployment' linking out to information on how to effectively dockerize an app that is using nextjs-auth0, possibly with guidance on deployment strategies for popular cloud platforms such as GCP, and if/how to use Edge functions if this is needed for the middleware or the pros/cons/alternatives if this is not possible.

**Comment by adamjmcgrath** [comment]
Hi @barrynorthern-tf - thanks for raising this

> if/how to use Edge functions if this is needed for the middleware or the pros/cons/alternatives if this is not possible.

Middleware and Edge functions are provided by Next.js and Vercel. Teaching you how to use these and what hosting provider supports what is out of the scope for an Authentication SDK.

I recommend you check the documentation for Next.js about how to deploy a Next.js application and middleware to your chosen vendor.
