### ISSUE TITLE
CallbackHandlerError: Callback handler failed. CAUSE: Missing state cookie from login request - custom domain?

### ISSUE THREAD

**Issue by PorridgeBear** [auth0/nextjs-auth0#1438]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The same error is being given in issue https://github.com/auth0/nextjs-auth0/issues/1411 but @adamjmcgrath advised to open as its own issue. 

```
CallbackHandlerError: Callback handler failed. CAUSE: Missing state cookie from login request (check login URL, callback URL and cookie config).
    at eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:60:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(rsc)/./node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:59:24)
    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:254:37) {
  code: 'ERR_CALLBACK_HANDLER_FAILURE',
  ```

Previous advice after providing a HAR, which was helpful and certainly looks to be the cause:

> This is straight forward to debug, if you look at your error message it says:
> 
> Missing state cookie from login request (check login URL, callback URL and cookie config)
> 
> If I check the login URL from your HAR file it is: http://localhost:3000/api/auth/login
> If I check the callback URL from your HAR file it is: http://gladpay.localhost:3000/api/auth/callback
> 
> localhost:3000 is a different host than gladpay.localhost:3000, you can't expect a cookie dropped on localhost:3000 to be read by gladpay.localhost:3000 - therefore you can't expect the state cookie from your login request to be read by your callback request (hence, you get a "Missing state cookie from login request" error)

Makes sense, except I am not configuring `localhost:3000` anywhere in my source code or environment, nor in auth0 configuration. I think this is being grabbed by some internal URL building function.

### Reproduction

My assumption is that this relates to use of a custom localhost domain:

* Configure a custom localhost domain, i.e. adding in your `/etc/hosts` file `127.0.0.1 myapp.localhost`
* Set JWT expiry short enough, trigger /api/auth/login (uses `authorize` behind the scenes) to have the appsession cookie set on callback from universal login - notice that the `Initiator` in network request is the correct, custom local domain
* Wait for session timeout, such that `authorize` needs to be called again (happens overnight for my values)
* The `authorize` endpoint is initated on first request to any page of my app (using the standard middleware) BUT this time by `localhost:3000`, losing the custom domain, and thus having the issue of reading the cookie

### Additional context

I've tried to locate where this `authorize` call is performed. I _think_ it's the `NodeClient`. In the other issue, there was suggestion that potentially the node version was at fault. I, too, was on `18.3` and had hope, but have since updated to `v18.17.1` and reproduced this issue again this morning.

### nextjs-auth0 version

3.1.0

### Next.js version

13.4.19

### Node.js version

18.17.1

**Comment by adamjmcgrath** [comment]
Thanks for raising this @PorridgeBear 

> Makes sense, except I am not configuring localhost:3000 anywhere in my source code or environment, nor in auth0 configuration.

There's no configuration - you're visiting `http://localhost:3000/api/auth/login` to login, so this is the host the SDK will set cookies on. You're configuring the SDK and Auth0 to return to `http://gladpay.localhost:3000/api/auth/callback` which can't read the cookies you set on `http://localhost:3000/api/auth/login`

You either need to:

- Visit `http://gladpay.localhost:3000/api/auth/login` to login
 
or:

- Configure the SDK to return to `http://localhost:3000/api/auth/callback` (using `AUTH0_BASE_URL`)

**Comment by PorridgeBear** [comment]
Totally understand what you're saying, except I don't see how that's happening. 

I have 1 single location in my source code that initiates the login, 1 button, and it's a relative path:

<img width="286" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/311566/9bcca0d5-7f84-4a6a-bdf6-873161adaccb">

Reproduction for me looks like this:

* At 10pm I visit http://gladpay.localhost/ and click the button, it _for sure_ per HAR is setting the cookie on the custom domain
* Close the laptop lid, leaving the Chrome tab logged in on the dashboard
* At 8am next day, open laptop, _click_ into URL bar so that I am reusing the same address (which has custom domain/dashboard) and press enter - this attempts to load `http://gladpay.localhost/dashboard` but blows up with the error
* The initiator in Chrome Network tab has changed to be localhost:3000

I see what you're saying though, it looks like Chrome is initiating from `localhost`. I'm going to do these steps one more time to be 100% sure I'm not going mad and will report back.

**Comment by adamjmcgrath** [comment]
I suspect this is something to do with how middleware figures out the hostname of a request - which according to https://github.com/vercel/next.js/issues/37536 is always "localhost" on localhost.

If you want Next.js to use a different hostname on localhost, it looks like you have to specify it when you run the server.

eg `next dev --hostname gladpay.localhost`

**Comment by PorridgeBear** [comment]
It's a good suggestion but I've had this in my configuration since the start of my project, via the npm script:

    "dev": "next dev --hostname gladpay.localhost",

I'm going to close this issue down for now and monitor this. I think it's clear what the issue is when it happens but quite where the `localhost` is coming from is TBC. It didn't happen yesterday when I came back to the site so I am quite perplexed, and I had already seen the issue on a newer Node, so I don't attribute it to that. 

Appreciate the prompt help you're given.

**Comment by ryanhefner** [comment]
Not sure this one should have been closed, I am running into the same issue, and it seems to happen when you set the `AUTH0_COOKIE_DOMAIN`. Removing it resolves the issues, but then I cannot seamlessly keep someone authenticated between `www.` and `app.` on the same domain.

Curious, @PorridgeBear, were you setting the `AUTH0_COOKIE_DOMAIN` in your `.env.*` file?

**Comment by PorridgeBear** [comment]
Hey @ryanhefner no, I don't set `AUTH0_COOKIE_DOMAIN` explicitly, no, so I'm relying on the active hostname context that the Next.js server is running on.

**Comment by ryanhefner** [comment]
@PorridgeBear Thanks for the follow-up. I guess I am just running into some general issues when I attempt to use the `AUTH0_COOKIE_DOMAIN`, wasn’t sure if that was the case in your scenario as well, but I guess not.
