### ISSUE TITLE
account linking is missing

### ISSUE THREAD

**Issue by landsman** [auth0/nextjs-auth0#1448]
When I did testing login with email and then google with the same address it produced two users. That's bad.

### Describe the ideal solution

Merge these accounts automatically on backend side: https://auth0.com/docs/manage-users/user-accounts/user-account-linking/suggested-account-linking-server-side-implementation

![Screenshot 2023-09-20 at 19 14 16](https://github.com/auth0/nextjs-auth0/assets/3184228/3ef45ff1-9b13-4469-9853-cab8fc8e1ad5)

**Comment by Widcket** [comment]
Hi @landsman, thanks for raising this.

You can perform account linking on the server side with our [Node.js SDK](https://github.com/auth0/node-auth0): https://auth0.github.io/node-auth0/classes/management.UsersManager.html#link

**Comment by landsman** [comment]
Yeah, I found that page, but first impression from auth0 is bad thanks to this. Verified emails on both sides - I don't see reason to don't have it automated, out of the box. With op-out possiblity, hm?

**Comment by Widcket** [comment]
Thanks again for reaching out. I understand your use case, however, I'm afraid this exceeds the scope of the SDK, as that functionality would have to be baked into the service itself.

**Comment by landsman** [comment]
I understand, can you forward this feedback to the relevant places please?

**Comment by Widcket** [comment]
Turns our there is an extension you can enable to get autolinking: https://auth0.com/docs/customize/extensions/account-link-extension
