### ISSUE TITLE
logout not working

### ISSUE THREAD

**Issue by deegansiwicki** [auth0/nextjs-auth0#1449]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have attached a video below of the logout issue I am encountering. It throws a network error when clicking the logout link, but it works after you click it a few times. Please advise, thank you!

https://github.com/auth0/nextjs-auth0/assets/71299723/8d9c80d8-83df-4b75-89d1-37b7ed9dc73b

### Reproduction

I am using the app router in the latest version of NextJS with auth0 middleware to protect all of my routes on an admin app.

### nextjs-auth0 version

3.1.0

### Next.js version

13.5.2

### Node.js version

20.6.0

**Comment by karlbateman** [comment]
Visiting the logout URL directly `/api/auth/logout` redirects to Auth0 and returns an error page with "Oops!, something went wrong" displayed.

**Comment by karlbateman** [comment]
After inspecting the error details, I had not set the "Allowed Logout URLs". Upon setting this, the logout and redirect now works as expected.

Looks like a gotcha, make sure to set your "Application URLs" for both local development and any environments where your application is deployed.

**Comment by deegansiwicki** [comment]
This is already set. It does not appear to be the issue.

**Comment by deegansiwicki** [comment]
So it was because I was using Link component provided by NextJS instead of an <a> tag. I ended up creating my own wrapper around the Link component with an auth prop, and set it to true when redirecting to an api endpoint.

**Comment by avertin-cd** [comment]
@deegansiwicki - I am encountering a similar issue. Can you post a code snippet of the change you made to fix this issue?

**Comment by deegansiwicki** [comment]
Hey @avertin-cd, just make sure you are using regular anchor tags for navigating to auth endpoints, instead of the Link component provided by NextJS. This component is to be used for client-side navigation only.

`<a  href="/api/auth/logout">Log Out</a>`
