### ISSUE TITLE
Module not found: Can't resolve 'crypto'

### ISSUE THREAD

**Issue by tijsproost** [auth0/nextjs-auth0#1451]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I get an error when using the edge runtime in NextJS 13.

I use this import: import { getSession, withPageAuthRequired } from '@auth0/nextjs-auth0/edge';

This throws an error when using in a layout or page.tsx.

Module not found: Can't resolve 'crypto'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@auth0/nextjs-auth0/dist/index.js
./src/app/layout.tsx

### Reproduction

import { getSession, withPageAuthRequired } from '@auth0/nextjs-auth0/edge';

Add edge runtime to page.tsx => export const runtime = "edge".

### nextjs-auth0 version

3.1.0

### Next.js version

13.5.2

### Node.js version

18.17.0

**Comment by saraahso** [comment]
I'm running into the same problem when trying to add runtime = "edge" on Next.JS 13

**Comment by adamjmcgrath** [comment]
Hi @tijsproost - thanks for raising this

> Import trace for requested module:
> ./node_modules/@auth0/nextjs-auth0/dist/index.js

This suggests you're using `@auth0/nextjs-auth0` somewhere in your code. The `/edge` export should import from "dist/edge.js".

Can you double check this in your code, or share a repo that demonstrates the issue?

**Comment by tunogya** [comment]
Use middleware.js will make you feel better!

```
// middleware.js
import { withMiddlewareAuthRequired } from '@auth0/nextjs-auth0/edge';

export default withMiddlewareAuthRequired();

export const config = {
  matcher: '/about/:path*'
};
```
