### ISSUE TITLE
App dir withMiddlewareAuthRequired wrapper alternative

### ISSUE THREAD

**Issue by ben-propflo** [auth0/nextjs-auth0#1452]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hi,

I've just migrated an app to use app dir. I saw the warning regarding setting cookies from a server component and the recommendation to use `withMiddlewareAuthRequired`. Unfortunately our middleware needs to run for all our routes (protected & unprotected) so we aren't able to use it. Is there anyway to expose what you're doing [in there](https://github.com/auth0/nextjs-auth0/blob/a5a5dc77d9f7353785c84b1b72d8415f35bad3fb/src/helpers/with-middleware-auth-required.ts#L127) so those of us that can't wrap our middleware can benefit? Assuming that is doing what I think it's doing...

### Describe the ideal solution

Provide a way to update cookies in middleware without using the wrapper

**Comment by ben-propflo** [comment]
Actually after looking through the code it looks like calling getSession() within the middleware will set the cookies, so that should be sufficient enough?

**Comment by adamjmcgrath** [comment]
Hi @ben-propflo - thanks for raising this

> Actually after looking through the code it looks like calling getSession() within the middleware will set the cookies, so that should be sufficient enough? It looks like a new cookie is being set in all the route responses, so just wanting to confirm this is a good plan?

Yep - good plan 👍

**Comment by lexraijmakers** [comment]
Hi @ben-propflo, I see this issue is closed, but did you have any luck with it? Can you share your code? for me, not using `withMiddlewareAuthRequired` just makes it lose the token on every refresh for some reason. But using `withMiddlewareAuthRequired` is not really nice when having a partly protected pages for example.

**Comment by ben-propflo** [comment]
@lexraijmakers you should simply be able to call getSession() in your middleware like this:
```
const res = NextResponse.next()
const sessionUser = await getSession(req, res)

return res
```

From what I remember res gets cookies set on it. You should be able to confirm this by looking at the response cookies for a page in your browser.

**Comment by zachgoll** [comment]
Just adding this here for anyone finding this in the future.  Make sure you're importing the "edge" version of `getSession` if you choose this strategy.  This one stumped me for a bit:

```
import { getSession } from '@auth0/nextjs-auth0/edge' <---
```
