### ISSUE TITLE
No way to pass through `mode` to universal login

### ISSUE THREAD

**Issue by g-sam** [auth0/nextjs-auth0#15]
### Describe the problem you'd like to have solved

No way to pass `mode` parameter to auth0 universal login (used for setting Lock's `initialScreen`)

### Describe the ideal solution

`mode` should be settable when initialising the client or using the login handler

**Comment by g-sam** [comment]
While I'm at it, it would be nice to be able to add custom query params to the `authorize` url!

**Comment by sandrinodimattia** [comment]
Hi @g-sam, here you go: https://github.com/auth0/nextjs-auth0/pull/24 (v0.5.0).
