### ISSUE TITLE
User assumed as non-authenticated when in a half logged-in state

### ISSUE THREAD

**Issue by tlazarov-whiskypartners** [auth0/nextjs-auth0#1515]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When I try to log in with Google using an email that already has an account (signed up with email and password), then the logout button with `/api/auth/logout` doesn't seem to work properly - it doesn't log me out.

### Reproduction

Simple:
1. Log in with social/federated log in
2. In the log in action reject the log in with `api.access.deny`
3. You are now stuck and cannot log in or log out.

### Additional context

I have added custom code to redirect the user to a custom page (non-protected) `/auth/error`. On that page I show the error message from the search parameter and a "Logout" button that is actually a link to "/api/auth/logout". When the user clicks the "Logout" button, they are taken to the `/api/auth/logout` route and then to the `returnTo` URL, configured in the `route.ts` file. BUT the user is not actually logged out, and if they try to come back to the application, e.g. `http://localhost:3000`, they are again, taken to the `/auth/error` custom page.

This is my `route.ts` file:
```ts
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import type { AppRouteHandlerFnContext } from '@auth0/nextjs-auth0';
import {
  handleAuth,
  handleCallback,
  handleLogout,
} from '@auth0/nextjs-auth0';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export const GET = handleAuth({
  callback: async (req: NextRequest, ctx: AppRouteHandlerFnContext) => {
    try {
      return await handleCallback(req, ctx);
    } catch (error) {
      const redirectURL = new URL(
        `${process.env.NEXT_PUBLIC_SITE_URL}/auth/error`,
      );

      req.nextUrl.searchParams.forEach((value, key) => {
        redirectURL.searchParams.set(key, value);
      });

      return NextResponse.redirect(redirectURL);
    }
  },
  logout: handleLogout({
    returnTo: process.env.LOGOUT_REDIRECT_URL ?? '',
  }),
});
```

And this is the `app/(clean)/auth/error/page.tsx`:
```tsx
interface AuthErrorProps {
  searchParams: { [key: string]: string | string[] | undefined };
}

export default function AuthError({ searchParams }: AuthErrorProps) {
  const errorMessage =
    'error_description' in searchParams
      ? searchParams['error_description']
      : 'Unknown error';

  return (
    <div>
      <h1>Authentication Error</h1>
      <p>{errorMessage}</p>
      <a href="/api/auth/logout">
        Logout
      </a>
    </div>
  );
}
```

Digging around, I found out that the issue is within the following logic:
https://github.com/auth0/nextjs-auth0/blob/893cac8a6b1e58cb1818ba875a124449c95f19f4/src/auth0-session/handlers/logout.ts#L27-L32

The user is considered not authenticated, because `isAuthenticated`'s value is `false`, hence it directly redirects the user to the `returnURL`, without properly logging them out.

The only way I managed to fix this is that I set a custom URL for the logout link. So, instead of `/api/auth/logout`, I have now the following:
```ts
const logoutURL = new URL(process.env.AUTH0_ISSUER_BASE_URL + '/v2/logout');

logoutURL.searchParams.set('client_id', process.env.AUTH0_CLIENT_ID ?? '');
logoutURL.searchParams.set(
  'returnTo',
  process.env.LOGOUT_REDIRECT_URL ?? '/',
);
```

while it's not ideal, it works, but I would like to see a proper fix for this.

### nextjs-auth0 version

3.1.0

### Next.js version

13.4.19

### Node.js version

18.16.0

**Comment by adamjmcgrath** [comment]
Hi @tlazarov-whiskypartners - we only support logging out of the identity provider if you're logged in to the application. We don't offer an endpoint that logs you out of your Identity Provider regardless of your logged in state in the application. But, as you've discovered, there's already an endpoint for this created by the identity provider you can use https://auth0.com/docs/api/authentication#auth0-logout 

> On that page I show the error message from the search parameter and a "Logout" button that is actually a link to "/api/auth/logout".

If you don't like your workaround, you could just link straight to auth0's `/v2logout`
