### ISSUE TITLE
How to check if user has a valid, logged in session from a server component? (App router, next 13)

### ISSUE THREAD

**Issue by angusclarkdev** [auth0/nextjs-auth0#1520]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am having trouble understanding the recommended approach to validating the user session before making subsequent API calls from within a server component that depend on the access token from the session. 

Take the following example. `Page` is a publicly accessible route that only needs to request the user data from our backend if the user is logged in. If the user has not logged in yet, we should not make a redundant request to the backend because we don't want the frontend to have to handle an error from our server. 

```
export default async function Page() {
  let user: User | undefined;

  const session = await getSession(); // from '@auth0/nextjs-auth0'

  if (session?.user) {
    user = await getUser(); //  fetch to get user from our API
  }

  return <div>{user?.given_name}</div>
```
My question then is whether or not the approach above is going work for checking whether the session is valid or not. I'm worried that an invalid session with an expired token might still be returned from `getSession` and then we will have to handle unwanted 401 errors from the server if `getUser` is passing an expired token? 

Is there a better approach that you would recommend for opting out of making API calls that require a valid token if the token has expired? Note that we are not using the `withApiAuthRequired` helper as we are hoping to not use next api routes as a proxy, in favour of communicating with our Python backend directly from server components. 

Thank you for your help and your patience...the app directory is still fresh for me so forgive me if my understanding is lacking.

### Describe the ideal solution

Some advice and maybe additional examples in the docs for less obvious use cases such as communicating with an external API from within a server component rather than via app/api routes as proxy.

### Alternatives and current workarounds

I've considered using the `withMiddlewareAuthRequired` helper to run before requests to all routes and check / refresh the rolling session before server component code runs. This would allow the updated session to be read from server components. Would this make sense?

```
export default withMiddlewareAuthRequired(async function middleware(req) {
  const res = NextResponse.next();
  const user = await getSession(req, res);

  // If session is expired, refresh it (I think this happens already with default 'rolling' session

  // get access token from session and attach to cookies
  res.cookies.set('token', user.token);
  return res;
});
```

**Comment by adamjmcgrath** [comment]
Hi @angusclarkdev - thanks for raising this

Could you tell me a bit more about your use case. Do you want the user to be logged out when their access token expires? Also do you use refresh tokens, or do you want the user to only get a new access token when they login again?

> I'm worried that an invalid session with an expired token might still be returned from getSession and then we will have to handle unwanted 401 errors from the server if getUser is passing an expired token?

Your session being valid and your access token being expired are essentially 2 different things, the SDK makes no attempt to sync them, so you may always need to handle 401s (even if you use refresh tokens)

> I've considered using the withMiddlewareAuthRequired helper to run before requests to all routes and check / refresh the rolling session before server component code runs.

This doesn't refresh the access token, so wont prevent it expiring

**Comment by angusclarkdev** [comment]
Hi @adamjmcgrath thanks for you response.

We currently use refresh tokens and the use case is that we would like to handle most, if not all of our data fetching (other than mutations) in server components. We've been able to add page protection to routes that require authentication using the `WithPageAuthRequired` helper. We add some additional fields to our user record post sign up which aren't accessible on the auth0 `user` object, so we want to make an additional call to our API to retrieve the complete user record, e.g:

```
export default withPageAuthRequired(
  async function Profile() {
    const res = await fetch('/some-user-endpoint', {
      headers: {
        Authorization: `Bearer ${`pass access token here`}`,
      },
    });
    const user = await res.json();

    return (
      <Suspense fallback={<div>Loding user data...</div>}>
        <div>Hello {user.name}</div>;
      </Suspense>
    );
  },
  { returnTo: '/profile' },
);
```

The benefit this has is that once the Suspense component has loaded the content, the user data is available on first render and we no longer need to handle this client side. This works fine for protected pages (although still haven't worked out how to pass the access token for the auth header), but we also have pages that are public but still need access to the user record if a user is logged in, such as a landing page with navigation and user profile avatar. So where I'm having trouble is with understanding how to check that a user is authenticated or not _before_ making additional fetches with a valid access token.

At this point I'm ready to forgo attempting to do this and simply make use of the client side useUser and UserProvider with more legacy ways of dealing with data waterfalls e.g: if `(loadingUser) return <LoadingSkeleton />` but because we are a greenfield project utilising the app dir I wanted to give this a shot.

**Comment by adamjmcgrath** [comment]
Hi @angusclarkdev

> We add some additional fields to our user record post sign up which aren't accessible on the auth0 user object, so we want to make an additional call to our API to retrieve the complete user record, e.g:

The `afterCallback` hook is useful for this, take a look at the examples in https://auth0.github.io/nextjs-auth0/types/handlers_callback.AfterCallbackAppRoute.html

> although still haven't worked out how to pass the access token for the auth header

Use `getAccessToken` like so:

```js
const { accessToken } = await getAccessToken();
const res = await fetch('/some-user-endpoint', {
  headers: {
    Authorization: `Bearer ${accessToken}`,
  },
});
```

> So where I'm having trouble is with understanding how to check that a user is authenticated or not before making additional fetches with a valid access token.

You can use `getSession`

```js
async function Public() {
  const session = await getSession();
  if (session) {
    // user is logged in
  } else {
    // user is logged out
  }
}
```

**Caveat to the above ☝️** 

> we would like to handle most, if not all of our data fetching (other than mutations) in server components

The problem with this (as described here https://github.com/auth0/nextjs-auth0#using-this-sdk-with-react-server-components) is that `getSession` needs to write to the cookie if you want to maintain a rolling session and `getAccessToken` needs to write to the cookie if you want to refresh the AT when it expires - and you can't write to the cookie from a Server Component.

The `getSession` issue is fairly easily resolved using middleware, you can simply call `getSession` in your middleware and the rolling session will be updated on every request (that hits the middleware). eg

```js
// middleware.js
export default async function middleware(req) {
  const res = NextResponse.next();
  await getSession(req, res); // bump the rolling session expiry
  return res;
}
```

The `getAccessToken` issue is more nuanced, you could refresh the AT on every middleware request - but this may make too many refresh token requests to the auth server. You could just refresh the AT on requests that you know will require the AT, eg

```js
// middleware.js
export default async function middleware(req) {
  const res = NextResponse.next();
  await getAccessToken(req, res); // refresh the AT if expired (and bump the rolling session)
  return res;
}

export const config = {
  matcher: ['/profile', '/another-req-that-needs-an-at']
}
```

Your other options for the `getAccessToken` issue are:

-  Use routes for your data fetching
-  Use the pages router
- Use (experimental) Server Actions

**Comment by angusclarkdev** [comment]
HI @adamjmcgrath thanks, your response has gone a long way to helping me get an implementation working. 

Regarding the access token issue, I understand now that I will need to make a call to `getAccessToken` in my middleware to ensure the token is not fresh before making protected requests. I have taken your advice and added some conditional logic into the middleware:

```
const privateRoutes = [...];

export default async function middleware(req: NextRequest) {
  const handleI18nRouting = createMiddleware({
    locales: ['en'],
    defaultLocale: 'en',
  });
  const response = handleI18nRouting(req);

  if (privateRoutes.includes(req.nextUrl.pathname)) {
    await getAccessToken(req, response);
  }

  return response;
}
```
Unfortunately it does seem like a user will hit the refresh access token limit quite quickly, as the majority of our requests require a valid access token. I wanted to clarify with you on whether or not we may run into issues here, as I'm reading up on the token [limitations](https://auth0.com/docs/secure/tokens/refresh-tokens#limitations) and it states
> If the limit is reached and a new refresh token is created, the system revokes and deletes the oldest token for that user and application

So sounds like it might not be a problem as old tokens will be deleted? However, this is assuming that the access token behaves similarly to a refresh token.  I'm thinking that if we also configure our access token expiration to be short we might not run into issues but seems like a bit of a risk / unknown.

**Comment by adamjmcgrath** [comment]
Hi @angusclarkdev - you don't have to worry about the RT limitation because refreshing an AT wont issue you a new RT, just a new AT.

> the majority of our requests require a valid access token

That's fine, you're only calling `getAccessToken` on requests that needs it, that's all you can do. The only limit you have to worry about is the rate limit on the Authentication API, which depends on your account https://auth0.com/docs/troubleshoot/customer-support/operational-policies/rate-limit-policy/rate-limit-configurations

**Comment by angusclarkdev** [comment]
Thanks @adamjmcgrath Is it possible to set the accessToken as a bearer token request header for API calls from the middleware itself? This seems like it would be a better way than having to do it for every fetch request declaration as per your example.

i've created a GET route under a `/api` folder and I have the following code in my middleware which checks the current request url before attempting to get and set the access token. This is failing with the error `The user does not have a valid session`.

```js
if (request.nextUrl.pathname.startsWith('/api')) {
    const { accessToken } = await getAccessToken(request, response);
    const requestHeaders = new Headers(request.headers);
    requestHeaders.set('authorization', `Bearer ${accessToken}`);
  }
```

**Comment by adamjmcgrath** [comment]
> Thanks @adamjmcgrath Is it possible to set the accessToken as a bearer token request header for API calls from the middleware itself? This seems like it would be a better way than having to do it for every fetch request declaration as per your example.

Not really, this SDK uses session cookies to protect it's API routes. What you're doing is adding a second redundant authentication method (bearer token auth) to the existing authentication method (session cookies).

**Comment by angusclarkdev** [comment]
OK thanks @adamjmcgrath – As there's no real bug here I'll close the issue, appreciate you taking the time to inform my understand of all of this.

**Comment by Kevin-McGonigle** [comment]
> The getAccessToken issue is more nuanced, you could refresh the AT on every middleware request - but this may make too many refresh token requests to the auth server. You could just refresh the AT on requests that you know will require the AT, eg

> ```js
>// middleware.js
>export default async function middleware(req) {
>  const res = NextResponse.next();
>  await getAccessToken(req, res); // refresh the AT if expired (and bump the rolling session)
>  return res;
>}
>
>export const config = {
>  matcher: ['/profile', '/another-req-that-needs-an-at']
>}
>```

Hey @adamjmcgrath, I've tried out your suggested solution for refreshing the access token in middleware, but have hit a snag with it.

With this setup, whenever a previously authenticated user returns to the site after their access token has expired, any requests I make to protected APIs fail because the access token has expired, and I get an error. Reloading the page then causes the same requests to succeed.

I _think_ what's going on here is that, because `await getAccessToken(req, res)` is called _after_ `NextResponse.next()`, the expired token is still being used for the initial page load.

I've tried out an alternative where I call the parameterless variant of `getAccessToken` _before_ calling `NextResponse.next()`, but this causes the API requests to fail indefinitely - I don't think the session cookie gets updated.

```js
// middleware.js
export default async function middleware() {
  await getAccessToken(); 
  return NextResponse.next();
}
```

Any ideas what can be done to get around this so that the access token is refreshed and made available to my server components on the initial render?

**Comment by ADTC** [comment]
Conceptually what we're all trying to do is this: (AT = access token)

<img width="953" alt="image" src="https://github.com/user-attachments/assets/e78fdf92-37d3-449d-b5f8-ed3e87eaab68">

The problem is that any response cookies set in middleware are not available in the same render pass of the current request. They are only available in a subsequent request, so you'll continue to use the old AT in the API calls of current request.

This is being fixed in this Next.js GitHub PR, which is already merged, but it is not in the stable channel yet. It will perhaps only be available in Next.js 15: https://github.com/vercel/next.js/pull/65008

For now, with Next.js 14, the workaround is to piggy-back the response headers to transmit the access token using a custom header key, then retrieve that in the location where you need it as part of the server-side render of the RSC page.

Note: To enhance the security of this solution, it's recommended to encrypt the AT that is placed in the response header, then decrypt it when it is retrieved (if the retrieval is valid). The secret key is only on the server, never transmitted to client, so it should **_not_** begin with `NEXT_PUBLIC_`. However, you can also store the AT as plain text in the response header.

Here's the workaround solution. This is the `middleware.ts` file:

```ts
import { NextResponse } from 'next/server'
import {
  AccessTokenError,
  getAccessToken,
  updateSession,
  withMiddlewareAuthRequired,
} from '@auth0/nextjs-auth0/edge'

import { encrypt } from 'your/helper/libraries'

export default withMiddlewareAuthRequired(async function middleware(req) {
  try {
    const res = NextResponse.next()
    const accessToken = (await getAccessToken(req, res)).accessToken

    // In Next.js 14, cookies set in middleware are not available in current request.
    // This may be fixed in Next.js 15 which isn't released yet. See https://github.com/vercel/next.js/pull/65008
    // Until then, we set the access token in a header to make it available in the current request.
    if (accessToken) res.headers.set('X-New-AT', await encrypt(accessToken))
    // or simply: res.headers.set('X-New-AT', accessToken)
    return res
  } catch (error) {
    if (error instanceof AccessTokenError) {
      const url = req.nextUrl.clone()
      url.pathname = '/api/auth/logout'
      const res = NextResponse.redirect(url)

      return updateSession(req, res, {
        user: [],
        accessToken: undefined,
        idToken: undefined,
        refreshToken: undefined,
        accessTokenExpiresAt: 0,
      })
    } else {
      throw error
    }
  }
})

export const config = {
  matcher: [
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
}
```
> The `updateSession` code is from [this comment](https://github.com/auth0/nextjs-auth0/issues/1723#issuecomment-2077584305).

Then have a function in your helper libraries like this:

```ts
'use server'

import { headers } from 'next/headers'
import { getAccessToken } from '@auth0/nextjs-auth0'

import { decrypt } from 'your/helper/libraries'

// Called in server for API requests in Server Components,
// and in client for API requests in Server Actions.
export async function getNewAT(): Promise<string> {
  // Get the encrypted access token from headers, set by middleware.
  let accessToken = headers().get('X-New-AT')

  if (!accessToken) {
    // This is a client-side call in a Server Action. Get the token from session.
    accessToken = (await getAccessToken()).accessToken || ''
  } else {
    // This is a server-side call in a Server Component. Decrypt the token.
    accessToken = await decrypt(accessToken)
    // or: skip the else block if the header AT is plain text
  }

  return accessToken
}
```

How to use it:

```ts
response = await fetch('https://my.backend.com' + url, {
  headers: {
    Authorization: `Bearer ${await getNewAT()}`,
    // ...
  }
  // ...
})
```

**Comment by chris-erickson** [comment]
@adamjmcgrath can you comment on this proposed solution? It's a lot going on, but seems ok. After spending a lot of time trying to understand RSC with auth0, it seems evident that there's a shortcoming of official documentation on it. You also mention using Server Actions as a solution - is this because it sends a session token along with the client->server request? Also, not sure if this specifically would address RSC issues?

Anyways, hoping you can add some confirmation to this, or if I missed it, direct me to some definitive documentation (would love examples of all the app router cases/possibilities!) on how to ensure we haven't missed something. Perhaps we'll get NextJS 15 in October, and some of this will be moot? https://nextjs.org/conf

**Comment by ADTC** [comment]
@chris-erickson 
> Perhaps we'll get NextJS 15 in October, and some of this will be moot?

Yes it seems that Next.js 15 will solve the problem of cookie persistence from middleware, and this workaround won't be necessary. It's only necessary for Next.js 14 and below.

> can you comment on this proposed solution?

FWIW, I got a confirmation from Auth0 support that my workaround is actually OK. Quoting:

> After reviewing this internally, the conclusion is that your method of piggybacking/passing the access token through in the request headers to be retrieved in the server-side render of the page is a suitable workaround until NextJS resolves the issue with cookie persistence in v15. We highly recommend that you encrypt the token (as you are already doing) to ensure that it can only be decrypted by the intended recipient (your server).
> 
> I have also requested that our documentation about implementing the SDK when using the Next JS app router be improved to better accommodate these scenarios and limitations.
> 
> ~ JM, Developer Support Engineer, Auth0
