### ISSUE TITLE
Access user on server side

### ISSUE THREAD

**Issue by ImranAhmed** [auth0/nextjs-auth0#153]
I am following the example here to access the user on the server side.

https://auth0.com/blog/ultimate-guide-nextjs-authentication-auth0/

However, I am getting the following error. I am using TypeScript.

![image](https://user-images.githubusercontent.com/2539520/89534559-076c9900-d7ed-11ea-903b-7988ab35c401.png)

Any ideas?

**Comment by aaronsnig501** [comment]
Hey,

I just noticed that I have the same error in VS Code, however, I'm not getting any errors when running the project, everything seems to function correctly, but I don't know if there are some issues behind the scenes that I'm not aware of.

I just checked and the req passed to both `getServerSideProps` and `getInitialProps` are `IncomingMessage`, but the [getSession](https://github.com/auth0/nextjs-auth0/blob/f292729e0d71f55afba0f32218a3f7d967ed6c51/src/instance.ts#L35) does expect `NextApiRequest`

**Comment by ImranAhmed** [comment]
I casted it as follows. 

`const { user } = (await auth0.getSession(req as NextApiRequest)) || {}`

**Comment by Widcket** [comment]
Hi, this should be fixed in the 1.0.0 beta.
