### ISSUE TITLE
Authenticate entire app

### ISSUE THREAD

**Issue by piehouserat** [auth0/nextjs-auth0#155]
Hey guys, not an issue more of a question.

Was wondering how you would go about wrapping the entire application in an auth check with an immediate redirect to login if the user was not logged in.

I realise I could probably just wrap every page in the `withAuth` HOC although that seems dated and inefficient.

I'm building an admin dashboard so SSR isn't exactly super necessary and happy to live without it if you guys recommend.

Can you guys suggest an elegant way of doing this? Normally I'd use a provider to abstract away the auth but I guess in there I wouldn't be able to access the `getInitialProps` to handle SSR

Thanks,
Martin

**Comment by OriginalEXE** [comment]
I would actually recommend only wrapping the pages for which you need the auth. You could wrapp your _app file, but then you would be disabling static optimization for all of your pages.

**Comment by SpicyPete** [comment]
If the entire app has a navbar at top with the user's profile status, but all the pages can be accessed while logged out as well, wouldn't it make sense to wrap the entire app with auth?

Or is there a way to get the users status, while keeping the static optimizations?

**Comment by Widcket** [comment]
Hi @SpicyPete, please check out the samples to see how to use the SDK with a navigation bar component. The 1.0.0 beta release has a new `useUser` hook that you can use to check the authentication state of the user from that component, and do conditional rendering accordingly.


WRT to protecting the whole app at once, I'm afraid that's not possible ATM.
