### ISSUE TITLE
in my production enterprise app that the entire company uses, i get sketchy message: "nextjs-auth0 is attempting to set cookies from a server component,see https://github.com/auth0/nextjs-auth0#using-this-sdk-with-react-server-components"

### ISSUE THREAD

**Issue by Jared-Dahlke** [auth0/nextjs-auth0#1552]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am surprised this still persists. Isn't this the official Nextjs Auth0 package? Lee Rob said he tried to talk to you guys about this and is not sure why it is still appearing. Is there some kind of problem that needs fixed? It is embarrassing to have this warning in the console in our production enterprise applications at work. We are 2 major versions in.

### Reproduction

run the official Auth0 Nextjs  library with any Nextjs 13 or Nextjs 14 app.

### nextjs-auth0 version

 "@auth0/nextjs-auth0": "^3.2.0",

### Next.js version

14

### Node.js version

20

**Comment by adamjmcgrath** [comment]
Hi @Jared-Dahlke 

> It is embarrassing to have this warning in the console in our production enterprise applications at work

The warning only shows in development (when `NODE_ENV=development`) (see https://github.com/auth0/nextjs-auth0/blob/main/src/http/auth0-next-response-cookies.ts#L8) - so this would suggest your production enterprise applications are running in development mode.

Also, if you read the link the warning points to - you'll see that this is still a valid warning. You cannot write to the cookie in React Server Components, and you are using a feature of the SDK that expects to write to the cookie in a RSC. In these cases the SDK may not behave as expected - more info: https://github.com/auth0/nextjs-auth0#using-this-sdk-with-react-server-components

**Comment by Jared-Dahlke** [comment]
Why is their a valid warning using the official auth0 library . We are a paid user, is there someone I can talk to about this?

**Comment by adamjmcgrath** [comment]
Hi @Jared-Dahlke 

> Why is their a valid warning using the official auth0 library

The warning is there to inform you that you can't write cookies in a Server Component. This is not a restriction imposed by the SDK, it is imposed by Next.js. The SDK can't change this - we have to operate within the bounds of the framework.

What we can do is warn you, _at development time_, that the features of the SDK that rely on writing to the cookie wont work in Server Components and [share a link](https://github.com/auth0/nextjs-auth0#using-this-sdk-with-react-server-components) where we offer some solutions to this (like writing to the session cookie in the middleware).

We chose to add this warning, _at development time_, so that you can take any necessary steps to workaround this restriction on Server Components _before_ going to production. If we didn't add a warning developers might only discover this when they start getting feedback from their users about sessions expiring early or noticing increased traffic to their refresh token endpoint.

> We are a paid user, is there someone I can talk to about this?

Information about what support channels Auth0 offer are here https://auth0.com/docs/troubleshoot/customer-support/support-channels

**Comment by Jared-Dahlke** [comment]
I looked at the solutions but they are very minimalistic and not complete. I have no idea how to fix the problem , it doesn’t give any example or detail . Can you please provide the exact code needed to make it work properly?

**Comment by adamjmcgrath** [comment]
Hi @Jared-Dahlke 

It's difficult to give the exact code without knowing how you're using the SDK. In most cases it will simply be a case of protecting your routes with [withMiddlewareAuthRequired](https://auth0.github.io/nextjs-auth0/types/helpers_with_middleware_auth_required.WithMiddlewareAuthRequired.html) - then your session expiry will be updated every time the user touches the session and you can safely ignore the warning.

If your application has more complex requirements, like refreshing access tokens from react server components - then I'd need some more info to give you a good recommendation.

**Comment by ipv6sq** [comment]
experiencing the same issue here
```
export default withMiddlewareAuthRequired();

export const config = {
    matcher: [
        "/dashboard/"
    ]
};
```
If I understand it correctly, then I can safe ignore this warning in server rendering components right? because the `/dashboard` is protected and the session is touched every time a user tried to open it?

**Comment by adamjmcgrath** [comment]
> If I understand it correctly, then I can safe ignore this warning in server rendering components right? because the /dashboard is protected and the session is touched every time a user tried to open it?

Correct 👍

**Comment by Jared-Dahlke** [comment]
ok awesome thank you @adamjmcgrath . I am using middleware so I am good then. I think what throws people off is this sentence here where it says the cookie "can" be written from middleware. Almost as if it's implying something extra has to be done, and it doesn't help that i get the warning as well. Thanks for the clarification!

![image](https://github.com/auth0/nextjs-auth0/assets/32936978/950c55b2-35de-4c64-89cd-6059b6c72f2d)

**Comment by Jared-Dahlke** [comment]
@adamjmcgrath after writing that comment I realized I need to ask you a clarifying question.

i _am_ using middleware.ts to protect my app, but i'm not using `withMiddlewareAuthRequired`, i'm doing it manually like this:

```
//middleware.ts

import { getSession } from "@auth0/nextjs-auth0/edge";
import { NextRequest, NextResponse } from "next/server";

export async function middleware(req: NextRequest) {
  const { nextUrl } = req;
  const session = await getSession();

  const isProtectedRoute =
    nextUrl.pathname.startsWith("/app") || nextUrl.pathname.startsWith("/api");

  const isNotProtectedRoute = nextUrl.pathname.startsWith("/api/auth");
  if (!session && isProtectedRoute && !isNotProtectedRoute) {
    const loginUrl = new URL("/api/auth/login", req.url);
    loginUrl.searchParams.set("returnTo", req.nextUrl.pathname);
    return NextResponse.redirect(loginUrl);
  }

  return NextResponse.next();
}
```

Am I all good still doing it this way?

**Comment by adamjmcgrath** [comment]
Also, will take another look at those docs. Going to put some time aside shortly to see if there's a better way to support using RSC's than what we're doing at the moment.

**Comment by Jared-Dahlke** [comment]
@adamjmcgrath , I noticed that I am getting a bunch of these errors in Sentry:
![image](https://github.com/auth0/nextjs-auth0/assets/32936978/992e05ae-1089-4dc1-9271-38feb1a312fa)

I suspect it has to do with Auth0, because i'm not using cookies anywhere else. Could Auth0 be causing this issue?

```
Error: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
  File "app:///_next/server/chunks/9009.js", line 1, in staticGenerationBailout
  File "app:///_next/server/chunks/9206.js", line 9, in cookies
  File "app:///_next/server/chunks/9206.js", line 1, in Auth0NextRequestCookies.getCookies
  File "app:///_next/server/chunks/9206.js", line 1, in StatelessSession.deleteSession
  File "app:///_next/server/chunks/9206.js", line 1, in StatelessSession.save
...
(5 additional frame(s) were not displayed)
```

**Comment by adamjmcgrath** [comment]
Hi @Jared-Dahlke - this looks like an issue in Sentry (see https://github.com/getsentry/sentry-javascript/issues/9290) - Those errors are a normal part of a successful build (next uses errors to bail out of static rendering) that shouldn't surface to the user.

Looks like Sentry have fixed this in 7.80.0 https://github.com/getsentry/sentry-javascript/pull/9503

**Comment by adamjmcgrath** [comment]
I think I've answered your questions - so closing.

**Comment by Jared-Dahlke** [comment]
Yes that fixed it Adam. Thank you for your help

**Comment by ADTC** [comment]
How can I find out which RSC is trying to set cookies? In my code, I can't find any RSC that imports `auth0` and retrieves session. It's always a client component. So IDK how or why this warning shows. It doesn't have any information about the exact location of the RSC.

**Comment by ADTC** [comment]
Apologies for the revival. I'll move this to #1614

**Comment by ilovemesomeramen** [comment]
So if i understand this correctly,
when using the middleware `withMiddlewareAuthRequired` the session will always be updated correctly but you will still get the warning message when a RSC calls `getSession` or anything related to it?

So the only method to get rid of the warning would be to set the environment variable `AUTH0_SESSION_AUTO_SAVE=false` and modify the `withMiddlewareAuthRequired` middleware such that `touchSession` is called like this:

`
export default withMiddlewareAuthRequired({
  async middleware(req) {
    const res = NextResponse.next();
    await touchSession(req, res);
    return res;
  },
});
`

This seems a little convoluted. I feel like it is misleading that the the warning gets emitted in the first place when everything is setup correctly anyways. Or i missed something in the docs, but it appears to me that the warning is always emitted when `AUTH0_SESSION_AUTO_SAVE` is not set to false. Having a warning emitted while following the recommended setup is extremely confusing.

**Comment by ADTC** [comment]
@ilovemesomeramen or you can just ignore the warning. 😂
