### ISSUE TITLE
Set header in afterCallback documentation

### ISSUE THREAD

**Issue by KylerD** [auth0/nextjs-auth0#1560]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hey folks,

In this [documentation](https://auth0.github.io/nextjs-auth0/types/handlers_callback.AfterCallbackAppRoute.html) an example is given for setting the header in afterCallback:

```js
import { headers } from 'next/headers';

const afterCallback = (req, session, state) => {
  if (!session.user.isAdmin) {
    headers.set('location', '/admin');
  }
  return session;
};
```

However [next/headers](https://nextjs.org/docs/app/api-reference/functions/headers) seems to be readonly. I'm currently upgrading from Next 12 -> 14, what's the best way for me to set headers in the afterCallback ?

### Reproduction

Not a bug

### nextjs-auth0 version

3.2.0

### Next.js version

14.0.2

### Node.js version

20.4.4

**Comment by adamjmcgrath** [comment]
Hi @KylerD - thanks for raising this

Yes, you are correct. Let me update that example. You can update the response headers after the callback using the following:

```js
import { handleAuth, handleCallback } from '@auth0/nextjs-auth0';

export const GET = handleAuth({
  callback: (async (req, ctx) => {
    const res = await handleCallback(req, ctx);
    res.headers.set('foo', 'bar');
    return res;
  })
});
```

**Comment by KylerD** [comment]
Thanks @adamjmcgrath much appreciated
