### ISSUE TITLE
Example of passing user into UserProvider w/ App router

### ISSUE THREAD

**Issue by seanparmelee** [auth0/nextjs-auth0#1571]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

We're in the process of incrementally adopting the app router and I was looking to replicate the behavior where server-rendered pages pass the `user` prop so that it can be passed into the `UserProvider` component in `_app.tsx` rather than relying on the client side to fetch the user.

As an experiment, I tried doing something like:

```tsx
export default async function RootLayout({ children }: PropsWithChildren) {
  const session = await getSession();

  return (
    <html lang="en">
      <body>
        <UserProvider user={session?.user}>
         {children}
        </UserProvider>
      </body>
    </html>
  );
}
```

...which seems to work, aside from the "nextjs-auth0 is attempting to set cookies from a server component" warning (we plan to update the session cookie via middleware and/or route handlers).

I'm ultimately wondering what's the recommended way to achieve this behavior with RSC and would be happy to update the example accordingly.

### Describe the ideal solution

I'd like to be able to pre-fill the `user` in the `<UserProvider>` component from a server component so that user information can be shown in the browser much sooner than it would when the `useUser` hook needs to fetch the user.

**Comment by adamjmcgrath** [comment]
Hi @seanparmelee - thanks for raising this

Your example looks good and, when you update the session cookie via middleware and/or route handlers, you can safely ignore that warning

**Comment by seanparmelee** [comment]
Thanks @adamjmcgrath. In that case, what do you think about updating [this](https://github.com/auth0/nextjs-auth0/blob/62f9076c2eb89609b39e0b9070c9e797fce432a8/src/client/use-user.tsx#L71-L74) text to also mention server components? Could also update example-app's [RootLayout](https://github.com/auth0/nextjs-auth0/blob/62f9076c2eb89609b39e0b9070c9e797fce432a8/example-app/app/layout.tsx) to have the code mentioned above along a comment about the warning?
