### ISSUE TITLE
getSession returns undefined in route handler (next 13, App router)

### ISSUE THREAD

**Issue by angusclarkdev** [auth0/nextjs-auth0#1580]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi @adamjmcgrath I am revisiting implementing a solution that will allow us to call an external API from within server components. After much reading around the subject and with your [help](https://github.com/auth0/nextjs-auth0/issues/1520)  I now have a much better understanding of what solutions this SDK provides, its features / drawbacks. 

I understand that for security the access token is not made available for use on the client and that the recommended approach to calling external APIs that require an access token is to proxy the request through a [route handler](https://nextjs.org/docs/app/building-your-application/routing/route-handlers).

I am trying to implement this but have ran into an issue which I hope has an obvious solution. I am able to successfully login and create a session for my user. I have verified that the session gets created by checking that `appSession` cookie exists, and by console logging the session object in the callback handler for `handleLogin` - However, when I check the session in a route handler, the value is undefined when passed no args, and null when passed the request and response. Here's my auth0 handler: 

```ts
// api/[auth0]/route.js
import { handleAuth, handleCallback } from '@auth0/nextjs-auth0';

async function afterCallback(req, session) {
  console.log('session', session); // session defined here
  
  return {
    ...session,
  };
}

export const GET = handleAuth({
  callback: handleCallback({ afterCallback }),
});
```

this is my route handler: 

```js
import { getSession } from '@auth0/nextjs-auth0';

// api/test/route.js
export async function GET() {
  const session = await getSession();
  console.log('session', session); // session undefined here
  return NextResponse.json({ foo: 'bar' });
}
```
I'm also unable to get the access token as attempting to do so throws an error because the session does not exist! 

Do you have any idea what I'm missing here? 

### Reproduction

run linked app

### Additional context

sample app demonstrating issue

https://github.com/angusclarkdev/sample-auth0

### nextjs-auth0 version

3.3.0

### Next.js version

13.5.6

### Node.js version

18.17.1

**Comment by adamjmcgrath** [comment]
Hi @angusclarkdev 

I've just tested the sample app you've shared using Node 18.17.1 and it's working fine for me.

After I login, I visit `/api/test` and get the expected `{ "foo": "bar" }` response and see the session logged to the console.

**Comment by angusclarkdev** [comment]
Hi @adamjmcgrath thank you for the quick response! 

I have been able to replicate the behaviour you're seeing as well. However, my use case is that I want to make requests to this api route handler from elsewhere in my next js app, like a client or server component, with the goal of being able to pass on the access token to an external API: 

```js
export default async function Index() {
  const response =  await fetch('http://localhost:3000/api/test')
  return (
    <div>
      hello
    </div>
  );
```

When I try this, the session in the route is undefined.

**Comment by angusclarkdev** [comment]
I'm guessing I need to forward the cookies during the request, otherwise my route handler has no way of accessing those cookies in node /server side? That would explain why it works in the browser, i.e session is defined when navigating to `http://localhost:3000/api/test`

**Comment by adamjmcgrath** [comment]
> I'm guessing I need to forward the cookies during the request

Correct - fetch wont automatically attach those

**Comment by angusclarkdev** [comment]
This was the "aha" moment I needed. It's all working as expected now! Thank you @adamjmcgrath
