### ISSUE TITLE
Be able to support both Preview URLs and Branch URLs on Vercel without custom Auth0

### ISSUE THREAD

**Issue by jonahallibone** [auth0/nextjs-auth0#1586]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Currently, deploying to Vercel requires a `.env.production` containing either 
```
NEXT_PUBLIC_AUTH0_BASE_URL=$VERCEL_BRANCH_URL
```
or
```
NEXT_PUBLIC_AUTH0_BASE_URL=$VERCEL_URL
```
Unfortunately, this means teams must choose between using the preview url or the branch URL, which can be a frustrating experience when QAing preview branches in pull requests and in Vercel. 

It is possible to do this if you create a custom Auth0 instance and pass `process.env.VERCEL_URL` as the `baseUrl`.

It would be ideal if there was a way to override this, somewhere in side `handleAuth()`.

### Describe the ideal solution

```ts
export default handleAuth({
  config: {
    baseUrl: process.env.VERCEL_URL // <--- here
  }.
  async login(req: NextApiRequest, res: NextApiResponse) {
    try {
      await handleLogin(req, res, {
        authorizationParams: {
          scope,
        },
      });
    } catch (error) {
      const message =
        error instanceof AuthError ? error.message : "An error occurred";
      const status =
        error instanceof AuthError && "status" in error && error.status
          ? error.status
          : 500;
      res.status(status).end(message);
    }
  },
});
```

**Comment by shyd0w** [comment]
I have been wondering if this can be solved. subbed!!! 🙏

**Comment by adamjmcgrath** [comment]
Hi @jonahallibone - thanks for raising this

> It would be ideal if there was a way to override this, somewhere in side handleAuth().

You can specify the `redirect_uri` (which `AUTH0_BASE_URL` is used to construct) at request time, which should allow you to choose between `$VERCEL_BRANCH_URL` and `$VERCEL_URL`, eg

```js
import { handleAuth, handleLogin, handleCallback } from '@auth0/nextjs-auth0';

const = getRedirectUri(req) {
  const branchUri = `https://${VERCEL_BRANCH_URL}/api/auth/callback`;
  const previewUri = `https://${VERCEL_URL}/api/auth/callback`;
  // Return `branchUri` or `previewUri` based on `req`
}

export default handleAuth({
  login: handleLogin((req) => { authorizationParams: { redirect_uri: getRedirectUri(req) } }),
  callback: handleCallback((req) => { redirectUri: getRedirectUri(req) })
})
```

You just need to default the `AUTH0_BASE_URL` to something that matches the protocol (in this case `https`) - as this is how the SDK chooses the `Secure` setting of the session cookie.

**Comment by jonahallibone** [comment]
Is this `redirectUri` for `handleLogin` supposed to be a `callback` URI?

**Comment by jonahallibone** [comment]
How would I handle this with a branch assigned domain or a production domain?

**Comment by jonahallibone** [comment]
For anyone who lands here and wants to know how this was solved:

```ts
import {
  AuthError,
  handleAuth,
  handleCallback,
  handleLogin,
  handleLogout,
} from "@auth0/nextjs-auth0";
import type { NextApiRequest, NextApiResponse } from "next";

const scope = "openid profile email offline_access read:current_user";

const getRedirectUri = (req: NextApiRequest) => {
  const { AUTH0_BASE_URL, NODE_ENV } = process.env;

  const localUri = "http://localhost:3000/api/auth/callback";
  const productionUriCallback = `https://${AUTH0_BASE_URL}/api/auth/callback`;
  const isDevelopment = NODE_ENV === "development";

  const reqHost = req.headers.host;

  if (!isDevelopment && AUTH0_BASE_URL && reqHost === AUTH0_BASE_URL) {
    return productionUriCallback;
  }

  if (isDevelopment) {
    return localUri;
  }

  return `https://${reqHost}/api/auth/callback`;
};

export default handleAuth({
  async login(req: NextApiRequest, res: NextApiResponse) {
    const REDIRECT_URI = getRedirectUri(req);
    console.log({ REDIRECT_URI });
    try {
      await handleLogin(req, res, {
        authorizationParams: {
          scope,
          redirect_uri: REDIRECT_URI,
        },
      });
    } catch (error) {
      const message =
        error instanceof AuthError ? error.message : "An error occurred";
      const status =
        error instanceof AuthError && "status" in error && error.status
          ? error.status
          : 500;
      console.error(error);
      res.status(status).end(message);
    }
  },
  callback: async (req: NextApiRequest, res: NextApiResponse) => {
    try {
      await handleCallback(req, res, {
        redirectUri: getRedirectUri(req),
      });
    } catch (error) {
      console.error(error);
    }
  },
  logout: async (req: NextApiRequest, res: NextApiResponse) => {
    const { NODE_ENV } = process.env;
    try {
      await handleLogout(req, res, {
        returnTo:
          NODE_ENV === "development"
            ? "http://localhost:3000"
            : `https://${req.headers.host}`,
      });
    } catch (error) {
      console.error(error);
    }
  },
});
```

I am unsure if this is the best way to do this, but it worked for me. Ideally I could get this working without the development checks, but I need some way to check the protocol of the request and I found no reasonable ways to do that

This is tested with custom domains using `AUTH0_BASE_URL` as well it works like a charm for the preview domain, the branch domain, and the assigned domain.

**Comment by adamjmcgrath** [comment]
`AUTH0_BASE_URL` can be a fully qualified url, so how about

```ts
const getRedirectUri = (req: NextApiRequest) => {
  switch (req.headers.host) {
    case process.env.VERCEL_URL:
      return `https://${process.env.VERCEL_URL}/api/auth/callback`;
    case process.env.VERCEL_BRANCH_URL:
      return `https://${process.env.VERCEL_BRANCH_URL}/api/auth/callback`;
    default:
      return `${process.env.AUTH0_BASE_URL}/api/auth/callback`
  }
};
```

**Comment by adamjmcgrath** [comment]
Answered so closing, feel free to ping me if you want to reopen

**Comment by jonahallibone** [comment]
Thanks for answering this. It worked great!

**Comment by jamesarosen** [comment]
Based on @adamjmcgrath's last suggestion, here's a version that does the same thing, but makes it a little easier to configure the allowed domains (especially if you have more or a dynamic list):

```ts
const DEFAULT_HOSTNAME = new URL(process.env.AUTH0_BASE_URL).hostname;
const ALLOWED_HOSTNAMES = new Set([process.env.VERCEL_URL, process.env.VERCEL_BRANCH_URL]);

function getRedirectUri(req: NextApiRequest | NextRequest) {
  const url = new URL('/api/auth/callback', req.url);
  if (!ALLOWED_HOSTNAMES.has(url.hostname)) {
    url.hostname = DEFAULT_HOSTNAME;
  }
  return url.toString();
}
```

**Comment by jonahallibone** [comment]
@adamjmcgrath do you think your answer or a link to this thread could be added to the readme? This was something I was unsure how to do after nearly a year of using this lib, and I'm sure other people have wondered the same thing. Super happy to have a solution now!

**Comment by ajwootto** [comment]
I'm surprised this isn't just solved by something built into the SDK. Shouldn't it support being deployed on Next's main hosting provider out of the box?
