### ISSUE TITLE
Handle Signup

### ISSUE THREAD

**Issue by matthieuh** [auth0/nextjs-auth0#16]
### Description

It seems that using this lib that there is no way to redirect user to signup part of the universal login.

### Describe the ideal solution

I would expect a `auth0.handleSignup`.

I'm maybe missing something but If I'm right I would enjoy open a PR.

**Comment by sandrinodimattia** [comment]
Hi @matthieuh , here you go: https://github.com/auth0/nextjs-auth0/pull/24 (v0.5.0). You could implement a new API route (eg: `/api/signup`) which calls the login handler with specific options which will be used by your login page (eg: `mode=signup`).

Feel free to re-open the issue if this doesn't solve it for you.

**Comment by matthieuh** [comment]
Using the login handler with a mode parameter seems not redirecting user to signup screen with the latest lib version (`v0.5.0`).
```javascript
await auth0.handleLogin(req, res, {
  authParams: {
    mode: 'signup'
  }
});
```

**Comment by torresandres** [comment]
I have this working by passing the "signUp" value as `initialScreen` instead of `mode`:

```
await auth0.handleLogin(req, res, {
  authParams: {
    initialScreen: 'signUp'
  }
});
```

**Comment by jvgreenaway** [comment]
I've tried all the options suggested on this issue but I cannot get this working – I land on the sign in view every time. I‘m using the universal login form. 

Has anybody managed to get this to work recently?

**Comment by Nobotym** [comment]
Try this:
`{ authParams: { screen_hint: 'signup' } }`

**Comment by kjkurtz** [comment]
I tried both of these in different configurations:
`      authParams:{
        initialScreen: 'signUp',
        screen_hint: 'signup'
      }`
And I still ended up with Sign In not Sign Up. So no-go on my end right now!

**Comment by dayvough** [comment]
I'm trying out the approach here using the new universal login: https://community.auth0.com/t/how-do-i-link-users-directly-to-the-hosted-signup-page/42520

```js
auth0.handleLogin(req, res, {
  authParams: {
    prompt: "login",
    screen_hint: "signup",
  },
});
```

And it's still leading me to the Login and not the Sign Up tab.

**Comment by dayvough** [comment]
Hmm, decided to just jump into my auth0 config and follow https://github.com/auth0/nextjs-auth0/issues/25#issuecomment-649310807 instead

```js
auth0.handleLogin(req, res, {
  authParams: {
    prompt: "signup",
  },
});
```

This then worked for me.

**Comment by nodabladam** [comment]
I have "mode" rather than "prompt" in my handleLogin and it seems to be working. 

```
    const { launch_login } = req.query;

    await auth0.handleLogin(req, res, {
      authParams: {
        mode: launch_login || "signup"
      }
    });
```

**Comment by JstnEdr** [comment]
Put this in your [...auth0.js] file -- working with `v1.4.2`

```
export default handleAuth({
  async login(req, res) {
    try {
      await handleLogin(req, res, {
        authorizationParams: {
          // Could conditionally pass params via req.query auth/login/?screen_hint=signup
          screen_hint: 'signup' 
        }
      });
    } catch (error) {
      res.status(error.status || 500).end(error.message);
    }
  }
});
```

**Comment by Barefoot-Dev** [comment]
This works for me in 

```
import { handleAuth, handleLogin } from "@auth0/nextjs-auth0";

export default handleAuth({
  async login(req, res) {
    await handleLogin(req, res, {
      authorizationParams: {
        screen_hint: "signup",
      },
    });
  },
});

```

Was not expecting it to be so hard to find the right params!
