### ISSUE TITLE
getAccessToken clears custom session.user attributes set via onUserLoaded

### ISSUE THREAD

**Issue by marklawlor** [auth0/nextjs-auth0#161]
### Description

As per the README, onUserLoaded can be used to set custom session.user attributes (eg `session.user.age`). However these attributes are removed when the accessToken is refreshed.

This can be observed here https://github.com/auth0/nextjs-auth0/blob/411896ba5044bbeda1b362f7f85b5ab8128d12cd/src/tokens/session-token-cache.ts#L83-L88 where it saves to the session store, overriding the `session.user` key.

This appears unintentional, as later on it attempts to preserve the `session.user` (however its already been overwritten via the `getAccessToken` function

https://github.com/auth0/nextjs-auth0/blob/411896ba5044bbeda1b362f7f85b5ab8128d12cd/src/handlers/profile.ts#L31-L50

### Reproduction

1. Create a callback onUserLoaded that sets a custom `session.user` attribute (such as the example in the README that sets `session.user.age`

```
await auth0.handleCallback(req, res, {
      onUserLoaded: async (req, res, session, state) => {
        return {
          ...session,
          user: {
            ...session.user,
            age: 20
          }
        };
      }
    });
```

2. Force a token refresh

```
  const tokenCache = auth0.tokenCache(request, response);
  await tokenCache.getAccessToken({
    refresh: true,
  });
```

3. Observe the users session

```
const session = await auth0.getSession(req);
console.log(session);
```

The custom attribute will have been removed

### Environment

Version `0.16.0`

**Comment by marklawlor** [comment]
If your blocked on this, I'm currently using this hack fix. It manually performs a refresh, and then does some gymantics with the cookies to get them correctly set. Its designed so once this issue is resolved you can simply delete the hack

```typescript
  /**
   *  START OF HACK FIX FOR github.com/auth0/nextjs-auth0/issues/161
   */
  const session = await auth0.getSession(request);
  if (
    session &&
    session.refreshToken &&
    (session.accessTokenExpiresAt || 0) * 1000 - 60000 < Date.now()
  ) {
    // Force a new token refresh
    const tokenCache = auth0.tokenCache(request, response);
    await tokenCache.getAccessToken({
      refresh: true,
    });

    const cookieWithNewAccessTokenButIncorrectUserAttributes = (response.getHeader(
      "Set-Cookie"
    ) as string[])
      .find((cookie) => {
        return cookie.startsWith("a0:session");
      })
      ?.split(";")[0];

    // Remove the cookie with incorrect user attributes
    response.setHeader("Set-Cookie", []);

    const sessionWithNewAccessTokenButIncorrectUserAttributes = await (tokenCache as any).store.read(
      {
        headers: {
          cookie: cookieWithNewAccessTokenButIncorrectUserAttributes,
        },
      }
    );

    await (tokenCache as any).store.save(request, response, {
      ...sessionWithNewAccessTokenButIncorrectUserAttributes,
      user: {
        ...session.user,
        ...sessionWithNewAccessTokenButIncorrectUserAttributes?.user,
      },
    });

    const correctCookie = (response.getHeader("Set-Cookie") as string[])
      .find((cookie) => {
        return cookie.startsWith("a0:session");
      })
      ?.split(";")[0];

    request.headers.cookie = correctCookie;
  }
  /**
   *  END OF HACK FIX FOR github.com/auth0/nextjs-auth0/issues/161
   */

  return auth0.handleProfile(request, response, { refetch: true });
```

**Comment by adamjmcgrath** [comment]
Hey @marklawlor - I see this also happens in the Beta https://github.com/auth0/nextjs-auth0/blob/beta/src/session/get-access-token.ts#L117

I'll raise some work to fix this shortly

**Comment by Widcket** [comment]
Fixed by https://github.com/auth0/nextjs-auth0/pull/257.
