### ISSUE TITLE
Need a configurable logout path

### ISSUE THREAD

**Issue by Kinbaum** [auth0/nextjs-auth0#164]
### Describe the problem you'd like to have solved

In the following code sample below, it looks like you have the logout URL hardcoded to `/v2/logout` and the `returnTo` parameter. Depending on which OpenID compliant broker you use this library with, this path is going to be different.

```ts
// Existing functionality
function createLogoutUrl(settings: IAuth0Settings, returnToUrl: string): string {
	return `https://${settings.domain}/v2/logout?client_id=${settings.clientId}&returnTo=${encodeURIComponent(
		returnToUrl
	)}`;
}
```

### Describe the ideal solution

As part of the `LogoutOptions`, can we have a configurable logout endpoint as well as url parameters? Something like this would offer far more control over the logout behavior:

```ts
// Using a package like query-string to construct more complex URLs
import queryString from 'query-string';

export interface LogoutOptions {
	path: string;
	query: {
		[key: string]: any
	}
}

function createLogoutUrl(settings: any, options: LogoutOptions): string {
	// Providing defaults if no options are supplied
	const { 
		path = '/v2/logout', 
		query = {
			client_id: settings.clientId,
			// Use the post logout options from the auth0 config instead
			returnTo: encodeURIComponent(settings.postLogoutRedirectUri)
		}
	} = options;
    
	return queryString.stringify({
		url: `https://${settings.domain}${path}`,
		query
	});
}
```

## Alternatives and current work-arounds

Currently there are no workarounds for this as it is a hardcoded value and the identity broker being used doesn't have that endpoint. Something like the proposed solution would offer far more flexibility.

@sandrinodimattia I see that this PR (#102) addresses the `end_session_endpoint`, but depending on which issuer you have, you may have a different key. For example: `issuerName_end_session_endpoint`, not `end_session_endpoint`.

When I look in my terminal, I see the following error:
`TypeError: end_session_endpoint must be configured on the issuer`. Thus calling the method outlined above, which needs more flexibility.

**Comment by sandrinodimattia** [comment]
Thanks for reporting this issue @Kinbaum. Right now our focus us to create a library which works well with Auth0, not a general purpose OIDC library. As such, this is not something we are going to invest in right now.

You might want to explore using https://github.com/nextauthjs/next-auth instead if you're not using Auth0.
