### ISSUE TITLE
Option to automatically refresh token in `withMiddlewareAuthRequired`

### ISSUE THREAD

**Issue by ajwootto** [auth0/nextjs-auth0#1665]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I think it would be nice for the `withMiddlewareAuthRequired` method to automatically handle refreshing of tokens. It was a bit of a gotcha for me that it didn't already do that, and from what I can gather the only way to have my middleware automatically refresh tokens is by calling `getAccessToken`, which I wasn't doing previously because I was using `getSession` which also provides the access token (but also does not refresh it I think?)

### Describe the ideal solution

It would be good to have an option to pass to the middleware like `handleTokenRefresh: true` that just automatically refreshes expired tokens. To me it even makes sense to be the default.

Outside of that, I think that it should at least be more explicitly documented that the way to refresh tokens with this SDK is by explicitly calling `getAccessToken`. 

Some places it would be beneficial to mention it:
In the example for obtaining a refresh token, which explains how to get it but not how to use it:
https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#getting-a-refresh-token
It mentions that in a comment in the sample code above but it's very easy to miss that

In the API docs for getAccessToken
https://auth0.github.io/nextjs-auth0/types/session_get_access_token.GetAccessToken.html

### Additional context

This was non-obvious enough to me that I totally missed how to get refresh to work on my first go-around of deploying this SDK to production. I assumed given the example that all I had to do to get it to work was include the "offline_access" scope and the SDK would refresh the token whenever necessary.

**Comment by frederikprijck** [comment]
This relates to the comment mentioned here: https://github.com/auth0/nextjs-auth0/issues/1636#issuecomment-1919237031

Long story short, the `withMiddlewareAuthRequired` is not concerned about Access Tokens, so it shouldn't be concerned about refreshing neither. So its intentional to not have this built in, but you can built your own middleware for this.

**Comment by ajwootto** [comment]
Hi @frederikprijck thanks for the clarification. Any thoughts about the documentation improvements I suggested?
