### ISSUE TITLE
How to update session in api rout.

### ISSUE THREAD

**Issue by DimitarTerzov** [auth0/nextjs-auth0#169]
Hi,
I want to update the session in API rout, based on data I fetched from external API. Is there a way similar to onUserLoaded?

Thank you!

**Comment by adamjmcgrath** [comment]
Hi @DimitarTerzov

Check out the Beta https://github.com/auth0/nextjs-auth0/tree/beta/src

Any changes to the session session object will be persisted, eg

```js
import { getSession } from '@auth0/nextjs-auth0';

export default async function myApiHandler(req, res) {
  const session = getSession(req, res);
  session.newProperty = 'New value'; // <-- new properties will be persisted;
}
```

Closing this issue for now, let me know if you want me to reopen it

**Comment by DimitarTerzov** [comment]
Thank you!

**Comment by javonclarke** [comment]
> Hi @DimitarTerzov
> 
> Check out the Beta https://github.com/auth0/nextjs-auth0/tree/beta/src
> 
> Any changes to the session session object will be persisted, eg
> 
> ```js
> import { getSession } from '@auth0/nextjs-auth0';
> 
> export default async function myApiHandler(req, res) {
>   const session = getSession(req, res);
>   session.newProperty = 'New value'; // <-- new properties will be persisted;
> }
> ```
> 
> Closing this issue for now, let me know if you want me to reopen it

This helped me fix an issue I was facing with authentication. I wanted to add data to the session, but I didn't want to override the handlers provided by auth0 to do so, namely the `handleProfile` handler. It didn't fully give me what I was looking for any way.

But after simply using `getSession(req, res)` and updating the session in the API route after returning a successful response the session was also updated. It helped get me the functionality I was looking for.

Would it be too much to ask to add this info to the docs on updating the session outside of the auth0 handler? I think it would be super helpful.

**Comment by ericblackham** [comment]
is the session.newProperty still in beta?
