### ISSUE TITLE
state mismatch, expected A, got B (for some Google accounts)

### ISSUE THREAD

**Issue by aorsten** [auth0/nextjs-auth0#172]
**Short**: Getting state mismatch error on `callback` page after a google user is successfully logged in with Auth0 using the google social provider. But only for a few google users.

### Description
I have set up NextJS-Auth0 login in production in our app. I'm using endpoints within `/pages/apu/auth/[login/callback/logout]`. In auth0 I have enabled both database, microsoft, and google login, and have added a rule which on successful authentication adds 1 claim to the access token, and 1 claim to the ID token. I am using a custom domain for my tenant, namely `auth.mydomain.net`.

All of this works for almost all users.
However, a few users have complained that they are unable to sign in with their Google accounts. It seems to me the entire flow works, up until the callback, where they get the following error message directly in the browser:

```
// mydomain.net/api/auth/callback
state mismatch, expected XXXX. got: YYYY
```
The above is written in pure text on a white page in the browser.

So - this error only occurs for a few users. We are unable to reproduce this with our own google accounts. I don't really know where to search for the bug from here. Anyone with similar experiences? 

It also seems to me, by reviewing sign-in history in the auth0 dashboard, that the sign-in actually did work, but that the error is in my app.

### Reproduction

I am unable to reproduce it consistently, as I don't have access to any google accounts where the bug happens. The following is our login and callback code:

```
import { initAuth0 } from '@auth0/nextjs-auth0';

export default initAuth0({
    domain: process.env.AUTH0_DOMAIN,
    clientId: process.env.AUTH0_CLIENT_ID,
    clientSecret: process.env.AUTH0_CLIENT_SECRET,
    audience: process.env.AUTH0_AUDIENCE,
    scope: 'openid email profile offline_access',
    redirectUri: `${process.env.REDIRECT_URI}/api/auth/callback`,
    postLogoutRedirectUri: `${process.env.REDIRECT_URI}/portal`,
    session: {
        cookieSecret: "COOKIE_SECRET_IS_SECRET",
        cookieLifetime: 60 * 60 * 8,
        cookieSameSite: 'lax',
        storeIdToken: true,
        storeAccessToken: true,
        storeRefreshToken: true
    },
    oidcClient: {
        httpTimeout: 2500,
        clockTolerance: 10000
    }
});
```

```
// /api/auth/login
import auth0 from '../../../utils/api-helpers/auth0';
import { REDIRECT_DEFAULT } from '../../../utils/settings';

export default async function login(req, res) {

    try {
        await auth0.handleLogin(req, res, {
            redirectTo: (req && req.query && req.query.redirectTo) || REDIRECT_DEFAULT,
            authParams: {
                screen_hint: (req && req.query && req.query.signup && "signup") || undefined
            }
        });
    } catch (error) {
        console.error(error);
        res.status(error.status || 400).end(error.message);
    }
}
```

```
// api/auth/callback
import auth0 from '../../../utils/api-helpers/auth0';

export default async function callback(req, res) {
    try {
        await auth0.handleCallback(req, res);
    } catch (error) {
        console.error(error);
        res.status(error.status || 400).end(error.message);
    }
}
```

### Environment

> Please provide the following:

- **Version of this library used:** 0.13.0
- **Version of the platform or framework used, if applicable:** NextJS 9.4.4
- **Other relevant versions (language, server software, OS, browser):** Hosted on Vercel, serverless
- **Other modules/plugins/libraries that might be involved:**

**Comment by joaogarin** [comment]
Any ideas how to get passed this problem? also running into the same thing. locally it seems to work ok

**Comment by samuanv** [comment]
I solved a similar issue ensuring that the callbacks have a trailing slash at the end (`redirectUri: `${process.env.REDIRECT_URI}/api/auth/callback/`)
Remember to add this as well in your auth0 app.

Also disabling [trailingSlash property](https://nextjs.org/docs/api-reference/next.config.js/trailing-slash) `trailingSlash: false,` in my `next.config.js`.

Hope this helps

**Comment by aorsten** [comment]
Thanks. I'll check if this solves it, it does sound like a probable cause.
About trailing slashes, isn't false already the default value?

**Comment by aorsten** [comment]
@samuanv what was your similar issue btw? And why did it solve the problem for you - when was the trailing slash added?

**Comment by lone-cloud** [comment]
I believe my solution to #141 will fix this issue too

**Comment by dylanesque** [comment]
> I solved a similar issue ensuring that the callbacks have a trailing slash at the end:
> `redirectUri:${process.env.REDIRECT_URI}/api/auth/callback/`
> Remember to add this as well in your auth0 app.
> 
> Also disabling [trailingSlash property](https://nextjs.org/docs/api-reference/next.config.js/trailing-slash) `trailingSlash: false,` in my `next.config.js`.
> 
> Hope this helps

I ran into this issue, this fix worked instantly for me.

**Comment by adamjmcgrath** [comment]
Hi @aorsten - thanks for raising this issue

Could you let me know if you're still seeing this issue? 

The new Beta has changed how it manages the transient cookies for state validation in the login callback, so you could try using that.

You can check out the Beta here https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0

Closing for now, happy to reopen if you want to discuss this further
