### ISSUE TITLE
Add onUserLoaded callback to handleProfile

### ISSUE THREAD

**Issue by adarnon** [auth0/nextjs-auth0#174]
### Describe the problem you'd like to have solved

The `handleCallback` function has a very useful callback `onUserLoaded` that allows me to enrich the user's session object.
However, if I want to refetch the user's session through `handleProfile`, the session would just get refetched and overridden without any of the changes I had done in `onUserLoaded`.

### Describe the ideal solution

`handleProfile` should receive an optional callback `onUserLoaded` with the same signature as the one in `handleCallback` (except for the `state` parameter, which is irrelevant here), and the returned altered session object is the one that should be saved.

## Alternatives and current work-arounds

Manually implementing the `handleProfile` behavior is a possible workaround.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by adamjmcgrath** [comment]
> However, if I want to refetch the user's session through handleProfile, the session would just get refetched and overridden without any of the changes I had done in onUserLoaded.

Hi @adarnon - We recommend you checkout the Beta https://github.com/auth0/nextjs-auth0/tree/beta, the existing properties of the session are merged with what is refetched https://github.com/auth0/nextjs-auth0/blob/beta/src/handlers/profile.ts#L55-L67 and we're fixing an issue with `getAccessToken` overwriting custom session properties which you can follow in #161
