### ISSUE TITLE
'invalid_grant' error upon login with Safari (WebKit)

### ISSUE THREAD

**Issue by AdrianAndersen** [auth0/nextjs-auth0#1754]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, I have an issue where my Safari users cannot log in. Chrome-like browsers work fine, it is only an issue in Safari afaik.

 I can reproduce the issue with the nextjs-auth0 sample app and have talked to other users on the community page that have the same issue. 
 
 So, after submitting the correct credentials for a user, the following error comes up in the console. The users encounter a blank screen and are completely unable to log in. This is very breaking for me and my users, as most of them use Safari. Hope you can address this issue swiftly, or correct me if I have misunderstood something.
 
<img width="1285" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/26925695/2ded3f9a-d1aa-41da-9e14-b9c29eb432f7">

On the auth0 dashboard I get the following logs:

```json
{
  "auth0_client": {
    "env": {
      "node": "v22.2.0"
    },
    "name": "nextjs-auth0",
    "version": "3.5.0"
  },
  "client_id": "[redacted]",
  "client_name": "Next Auth0 Test",
  "connection_id": "",
  "date": "2024-05-31T19:04:16.643Z",
  "description": "Failed to verify code verifier",
  "details": {
    "code": "******************************************32f"
  },
  "hostname": "[redacted]",
  "ip": "[redacted]",
  "type": "feacft",
  "user_agent": "Other 0.0.0 / Other 0.0.0",
  "user_id": "",
  "user_name": "",
  "log_id": "90020240531190416711985000000000000001223372041180740091",
  "tenant_name": "[redacted]",
  "_id": "90020240531190416711985000000000000001223372041180740091",
  "isMobile": false,
  "id": "90020240531190416711985000000000000001223372041180740091"
}
```

### Reproduction

Use the official [NextJS docs](https://auth0.com/docs/quickstart/webapp/nextjs) and setup a standard template application. Then, try to log in with a WebKit-based browser. (Safari on MacOS or Safari/Chrome on IOS)

### nextjs-auth0 version

3.5.0

### Next.js version

13.5.1

### Node.js version

20.14.0

**Comment by AdrianAndersen** [comment]
Might be related to https://github.com/auth0/nextjs-auth0/issues/1495

**Comment by Sapessii** [comment]
has anyone any update on this?

**Comment by Ojay** [comment]
Did you have any luck with this @AdrianAndersen? We're suffering the same issue and I just can't get around it, any help would be much appreciated, thanks!

**Comment by Sapessii** [comment]
I have been able to fix it, on my side the problem was the service worker cache.

If you are using serwist for the pwa service worker just put this in your worker file:

const routesToFilter = [
	"/api/auth/login",
	"/api/auth/callback",
	"/api/auth/logout",
	"/api/auth/me",
];

const serwist = new Serwist({
	precacheEntries: self.__SW_MANIFEST,
	skipWaiting: true,
	clientsClaim: true,
	navigationPreload: true,
	runtimeCaching: [
		{
			matcher({ sameOrigin, url }) {
				return sameOrigin && routesToFilter.includes(url.pathname);
			},
			handler: new NetworkOnly(),
		},
		...defaultCache,
	],
});

**Comment by Ojay** [comment]
Yep, that was my issue too - excellent stuff!
