### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by yonghing** [auth0/nextjs-auth0#176]
Can we have documentation like this https://auth0.github.io/auth0-react/

**Comment by adamjmcgrath** [comment]
Hi @yonghing - thanks for raising this

The new Beta has auto generated API documentation here https://auth0.github.io/nextjs-auth0/

You can check out the Beta here https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0

Closing for now, feel free to reopen if you want to discuss further.
