### ISSUE TITLE
Is this repository abandoned?

### ISSUE THREAD

**Issue by jl75** [auth0/nextjs-auth0#1783]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I want to express my concerns about the current state of this repository. Please excuse me for being a bit blunt, maybe. And please correct me if I'm wrong.

- There appears to be no or hardly any activity on this repository by the official Auth0 team. All Auth0 activity seems to have dropped after around December, 2023.
- There has been no communication (or I could not find it) on an any upcoming release.
- There are many open issues dating back from around January 1, 2024 until today.
- There have been no recent replies on these open issues by the main maintainers affiliated with Auth0 (@adamjmcgrath, @Widcket).
- The most recent version of this repository was released over 10 months ago.
- There have been no commits since then.
- Pull requests have been disregarded.
- The support for Next.js 14 (released a year ago) is lacking. More recent versions of Next.js 14 seem to manifest more issues.
- The repository has many open issues specific to current Next.js 14 and upcoming Next.js 15.

It could be that the Auth0 team is working hard behind the scenes, but there is not much showing for it right now.

### Reproduction

Create a next.js 14.x app and integrate auth0-nextjs  For higher numbers of x, the app starts to exhibit errors and fails to work.

### Additional context

n/a

### nextjs-auth0 version

3.5.0

### Next.js version

14,15

### Node.js version

20

**Comment by tusharpandey13** [comment]
Hi @jl75, please note that we are working on a new version of nextjs-auth0 (v4) that will support Next >= 14, react >= 18 with a simplified interface and various other improvements. I cannot comment on the ETA for general availability but it should hit a beta release soon.

**Comment by jl75** [comment]
Hi @tusharpandey13 and thank you for your reply.

First of all: I’m absolutely not assured by this response. You cannot simply dismiss this by closing the issue.

Does this represent the official position of Okta/Auth0 on auth0-nextjs? What happened with the (previous?) maintainers? They have always been responsive and helpful. Why has there been no (visible) activity for so long? Why is there not a single response from Okta/Auth0 to open issues, for over 10 months? Why has there not been any communication about a new upcoming release? 

Am I mistaken to expect a continued professional stewardship of this repository on behalf of Okta/Auth0?

Secondly, clients are demanding reliable product roadmaps from their vendors and partners. Even more so for critical components, such as authorization/authentication. The current state of the auth0-nextjs repository is of grave concern to me. It should be of grave concern to Okta/Auth0 too! From your response I get the feeling you are not taking this seriously at all. This whole situation does not bode well for my clients concerning their future and/or continued use of this repository, and in lesser extent to their use of Okta/Auth0 in general.

Notwithstanding the above, I do value the auth0-nextjs software, together with the broader Okta/Auth0 offering of products and services, including its robust infrastructure. While others may abandon auth0-nextjs for alternatives, this is neither feasible nor desirable for me (yet).

However, without any improvements to the current stewardship, I would be increasingly inclined to advise clients against using auth0-nextjs.l in the future.

Moving forward, I would strongly urge Okta/Auth0 to take stewardship seriously again. Wishing well and good luck!
