### ISSUE TITLE
withMiddlewareAuthRequired in v4

### ISSUE THREAD

**Issue by lheilmann** [auth0/nextjs-auth0#1791]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would like to use withMiddlewareAuthRequired in the new v4 alpha. With the current implementation I have to add the checks and routing manually which makes it significantly harder to migrate to the new version.

### Describe the ideal solution

Use withMiddlewareAuthRequired in v4 a similar way as it was implemented in v3. 

### Additional context

This topic has already been touched with @guabu here: https://github.com/auth0/nextjs-auth0/issues/1779#issuecomment-2460099334

**Comment by guabu** [comment]
Hey @lheilmann 👋 Thanks for opening a separate thread!

You shouldn't have to change much here. In the middleware, you can use the `getSession()` method to check if the user is authenticated and either redirect them to a different page or return an error. For example:

```ts
export async function middleware(request: NextRequest) {
  const res = await auth0.middleware(request)
  const session = await auth0.getSession()

  if (!session) {
    return NextResponse.redirect("/error-page")
  }

  return res
}
```

**Comment by lheilmann** [comment]
Hey @guabu! Thanks for the quick help 😊

I would like to redirect users to the login screen if they're not authenticated. The following doesn't seem to work:

```
export async function middleware(request: NextRequest) {
  const { origin } = new URL(request.url);
  const res = await auth0.middleware(request);
  const session = await auth0.getSession();

  if (!session) {
    console.log("No session found, redirecting to login");
    return NextResponse.redirect(`${origin}/auth/login`);
  }

  return res;
}
```

Any ideas how to solve this elegantly similar to `withMiddlewareAuthRequired` in the previous version?

**Comment by guabu** [comment]
It looks like you're running into a redirect loop — you'll have to exclude any authentication related paths so that the user can successfully be redirected if they don't have a session. For example:

```ts
export async function middleware(request: NextRequest) {
  const { origin } = new URL(request.url)
  const res = await auth0.middleware(request)
  const session = await auth0.getSession()

  if (!session && !request.nextUrl.pathname.startsWith("/auth")) {
    console.log("No session found, redirecting to login")
    return NextResponse.redirect(`${origin}/auth/login`)
  }

  return res
}
```

**Comment by uprizingFaze** [comment]
And how can I do it in my middleware.ts file?

```typescript
import { withMiddlewareAuthRequired } from "@auth0/nextjs-auth0/edge";

export default withMiddlewareAuthRequired();

export const config = {
  matcher: [
    "/user/:path*",
    "/dashboard/:path*",
    "/profile/:path*",
    "/protect/:path*",
  ],
};
```
