### ISSUE TITLE
v4 - The environment variable or domain option is required

### ISSUE THREAD

**Issue by brndt** [auth0/nextjs-auth0#1792]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have all my envs put into .env.local but the usage of `getAccessToken` of `Auth0Client` gives the following error:

Error: The AUTH0_DOMAIN environment variable or domain option is required. See https://auth0.com/docs

@guabu

### Reproduction

...

### nextjs-auth0 version

4.0.0-beta0

### Next.js version

15

### Node.js version

22.3

**Comment by guabu** [comment]
Hi @brndt 👋 Could you share how you're instantiating and importing the SDK instance? In particular, did you follow [steps 3 and 4 here](https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#3-create-the-auth0-sdk-client)?

**Comment by brndt** [comment]
I basically copied and pasted the code from these steps.

The only way to get it working is to pass all these parameters explicitly:
`export const auth0 = new Auth0Client({ domain: 'xxxx.eu.auth0.com' ... })`
Seems like the instance can't find env values by itself.

**Comment by guabu** [comment]
Hmm it sounds like the environment variables aren't being loaded for your project. Are you using a `src/` directory? Could you share what your file tree looks like please?

**Comment by brndt** [comment]
Yes, I'm using a src directory.
<img width="1357" alt="Screenshot 2024-11-06 at 21 01 50" src="https://github.com/user-attachments/assets/46267cbc-514e-4eec-bd5b-8b42d21bcffc">
