### ISSUE TITLE
v4 - how to mock the client

### ISSUE THREAD

**Issue by brndt** [auth0/nextjs-auth0#1793]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I was using the following approach when mocking all calls to auth0 from the client components:
https://github.com/auth0-samples/auth0-nextjs-samples/blob/main/Sample-01/tests/app/profile.test.jsx
https://github.com/auth0-samples/auth0-nextjs-samples/blob/main/Sample-01/tests/fixtures.jsx

What would be the alternative way to test my components that use Auth0 API?

@guabu

### Reproduction

...

### nextjs-auth0 version

v4.0.0-beta

### Next.js version

15

### Node.js version

22.3

**Comment by brndt** [comment]
As for e2e tests, I can't find the correct way to check the presence of valid cookie in Cypress
In my case before it was:

```
validate: () => {
        // Validate presence of a valid appSession cookie.
        cy.getAllCookies().then((cookies) => {
          cy.log(cookies.toString())
          let appSessionCookie = cookies.find((cookie) => cookie.name === 'appSession')
          expect(appSessionCookie).to.exist
          expect(appSessionCookie?.value).to.not.be.empty
        })
      }
```

I was using this tutorial: https://docs.cypress.io/app/guides/authentication-testing/auth0-authentication#Custom-Command-for-Auth0-Authentication

**Comment by guabu** [comment]
Hi @brndt 👋 v4 of the SDK no longer requires an `<UserProvider />` component. Instead we rely on SWR. If you're looking to test a component with a user already loaded when using the `useUser()` hook, you could potentially consider wrapping the component with the `SWRConfig` as shown here: https://swr.vercel.app/docs/advanced/cache.en-US#reset-cache-between-test-cases

**Comment by brndt** [comment]
> Hi @brndt 👋 v4 of the SDK no longer requires an `<UserProvider />` component. Instead we rely on SWR. If you're looking to test a component with a user already loaded when using the `useUser()` hook, you could potentially consider wrapping the component with the `SWRConfig` as shown here: https://swr.vercel.app/docs/advanced/cache.en-US#reset-cache-between-test-cases

Could you provide an example using `SWRConfig` for testing component with `useUser()` hook please?

**Comment by brndt** [comment]
Also I need to find a way to mock client instance when I'm using getSession/getAccesToken method.

**Comment by guabu** [comment]
Hey @brndt — I'll get put some examples together for testing shortly.

**Comment by guabu** [comment]
Hey @brndt 👋 Thanks for your patience! Here's a sample of how to test a component that relies on the `userUser()` hook using the `SWRConfig`:

```tsx
// component.tsx
"use client";

import { useUser } from "@auth0/nextjs-auth0";

export default function Counter() {
  const { user, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;

  return <h3>{user?.sub}</h3>;
}
```

```tsx
// component.test.tsx
import { expect, test } from "vitest";
import { render, screen } from "@testing-library/react";
import { SWRConfig } from "swr";

import MyComponent from "./component";

test("useUser hook", () => {
  const data = new Map();
  data.set("/auth/profile", {
    data: {
      sub: "123",
    },
  });

  render(
    <SWRConfig
      value={{
        revalidateOnMount: false,
        fallback: {
          "/auth/profile": {
            sub: "123",
          },
        },
        provider: () => data,
      }}
    >
      <MyComponent />
    </SWRConfig>
  );

  expect(screen.getByRole("heading", { level: 3 }).innerHTML).toEqual("123");
});
```

The above example uses `vitest`. We might re-introduce the `UserProvider` as a level of abstraction here.

> Also I need to find a way to mock client instance when I'm using getSession/getAccesToken method.

The `getSession()` method is only available on the server-side — the `userUser()` hook should give you the necessary user information from the session.

`getAccessToken` can be mocked on import — here is an example of how to do it with vitest: https://vitest.dev/api/vi.html#mock-modules

I hope that helps!

**Comment by brndt** [comment]
Thanks!
I think it should be documented as well.

**Comment by cassus** [comment]
Thanks @guabu for your example! Here's what I ended up using based on your example. I'll share it here in case someone finds it useful.

```ts

const user = {
  // ...
} satisfies User

export function MockAuth0Provider({
  children,
}: {
  children: ReactNode
}): JSX.Element {
  return (
    <SWRConfig
      value={{
        // Auth0Provider sets the user as a fallback, this prevents SWR from trying to fetch a fresher version
        revalidateIfStale: false,
      }}
    >
      <Auth0Provider user={user}>{children}</Auth0Provider>
    </SWRConfig>
  )
```
