### ISSUE TITLE
V4 Nextjs 15 pages router "Failed to load external module" on any import

### ISSUE THREAD

**Issue by MrSimmmons** [auth0/nextjs-auth0#1795]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Using the Nextjs v15 Pages Router with the V4 readme (up to step 4 is enough) will fail to load or build with the following error in browser
![Screenshot 2024-11-10 at 11 06 55 PM](https://github.com/user-attachments/assets/3c09d5e1-661d-454a-997b-ce40cd1e3ae6)

and in terminal
<img width="1164" alt="Screenshot 2024-11-10 at 11 07 13 PM" src="https://github.com/user-attachments/assets/e913c575-fd7a-4716-b78e-106f4c7fa73f">

--------

I am able to successfully get all the exports to work if i manually import the exact path to the folders index file (or directly to the file its self.
<img width="602" alt="Screenshot 2024-11-10 at 11 11 53 PM" src="https://github.com/user-attachments/assets/78a71b04-65a8-4d4a-82e4-fa868844940d">

<img width="579" alt="Screenshot 2024-11-10 at 11 11 38 PM" src="https://github.com/user-attachments/assets/bec6e2b4-f2d7-4f8a-be29-660252c00c70">

### Reproduction

1. Create a V15 Pages router project using the create next app CLI https://nextjs.org/docs/pages/api-reference/cli/create-next-app
2. Follow the getting started guide provided in the V4 readme (up to [Step 4](https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#4-add-the-authentication-middleware) is enough)
3. Start the app in dev mode (will break with both webpack and turbopack bundlers)

### Additional context

VSCode IntelliSense still works on the import functions and classes. So I can still command click them and VSCode will take me to their type sources, and autocomplete still functions. However this is annoying in this sense because the autocompleted "path" is causing the error and I have to manually modify the path as shown above to address it.

------

I noticed that the [provided App Router example ](https://github.com/auth0/nextjs-auth0/tree/v4/examples/with-shadcn) works fine so it must be just an issue with the Pages Router

------

Having your code in a `/src` directory or not makes no difference

------

The directory that the import errors are completing about are correct import paths (aside from maybe the file extension being omitted in the error? That might be the only thing that looks slightly off to me) as I can put them into finder and go to the correct place.

### nextjs-auth0 version

V4.0.0 beta 0

### Next.js version

15.0.3

### Node.js version

20.18.0

**Comment by guabu** [comment]
Hi @MrSimmmons 👋 Thanks for reporting this! I've just pushed a fix — could I kindly ask you to upgrade to `@auth0/nextjs-auth0@4.0.0-beta.2` and give it a try please?

**Comment by MrSimmmons** [comment]
@guabu Hey thanks! it seems to have worked for the client side, but SSR pages & server actions still seem to be getting the same error
![Screenshot 2024-11-12 at 10 46 51 AM](https://github.com/user-attachments/assets/7603fc84-f346-46bc-9fce-c31c3117cb80)

Im guessing that you will have to do the same `.js` file for all exports

**Comment by guabu** [comment]
Hey @MrSimmmons 👋 We've been doing some investigation around this and it looks like there's a difference in how Next.js resolves & transpiles packages for App router vs Pages router.

The next release will include a fix for this. For the time being, you can add the following to your `next.config.ts` which should help resolve the issue temporarily:

```js
transpilePackages: ["@auth0/nextjs-auth0"]
```

**Comment by MrSimmmons** [comment]
Ah awesome that appears to be working now. Ill leave this ticket open and you can close it when the fix is merged
Thanks again!

**Comment by guabu** [comment]
Hi @MrSimmmons 👋 We've cut a new release which addresses this issue. You should now be able to upgrade to the latest and revert any modifications from your `next.config.ts`: `npm i @auth0/nextjs-auth0@4.0.0-beta.3`

Thanks again for reporting this!

**Comment by MrSimmmons** [comment]
@guabu  Awesome just tried it out. Works great thanks guys!

Just so yall know there is another issue with the pages router that I reported over at #1801
TBH I'm not sure if its a Next 15 issue, or a v4 issue, but some clarification would be great since it is the recommended way for SSR pages according to the README

Thanks again!
