### ISSUE TITLE
V4 set `returnTo` or `post_logout_redirect_uri` during logout

### ISSUE THREAD

**Issue by brandicph** [auth0/nextjs-auth0#1797]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

In V4, it is not possible to redirect users to a specific destination when we log users out.

### Describe the ideal solution

Allow users to provide a `returnTo` or `post_logout_redirect_uri`  as part of the `handleLogout` process.

https://github.com/auth0/nextjs-auth0/blob/f8dd6900bbb75f2702e9d8acc0c48a953e92b6d1/src/server/auth-client.ts#L301

An idea is to add a `returnTo` to the `post_logout_redirect_uri` with a fallback to the `appBaseUrl`.
```diff
- url.searchParams.set("post_logout_redirect_uri", this.appBaseUrl)^
+ url.searchParams.set("post_logout_redirect_uri", returnTo || this.appBaseUrl)
```

This should ultimately allow users to do something like this

```
/auth/logout?returnTo=https%3A%2F%2Flocalhost%3A3000%2Fanother-logout-destination
```

**Comment by brandicph** [comment]
cc @guabu

**Comment by guabu** [comment]
Hi @brandicph 👋 We can definitely allow for different logout URLs to be specified via the `returnTo` as you mentioned — the only thing to note is that would require registering each URL in the `Allowed Logout URLs` of your client. Would that work for your use case?

**Comment by brandicph** [comment]
> Hi @brandicph 👋 We can definitely allow for different logout URLs to be specified via the `returnTo` as you mentioned — the only thing to note is that would require registering each URL in the `Allowed Logout URLs` of your client. Would that work for your use case?

@guabu that is perfect 👌 np. we are used to the process of registering each URL in the client's `Allowed Logout URLs.` 🤙

**Comment by guabu** [comment]
Sounds good, I'll get that added in the next release this week. I'll keep you posted once it's been added!

**Comment by brandicph** [comment]
> Sounds good, I'll get that added in the next release this week. I'll keep you posted once it's been added!

Amazing @guabu 🙏 thx

**Comment by alioftech** [comment]
![image](https://github.com/user-attachments/assets/62b88290-71be-4fe2-9bfb-3ce4db082c89)
Hey guys, you are still lagging behind. 
I expect more from you than Clerk

**Comment by guabu** [comment]
Hey @brandicph 👋 We've just cut a new release which should now allow you to pass the logout URL in the `returnTo` query parameter. The README docs have also been updated to reflect that.

Please feel free to upgrade to the latest and give it a shot: `npm i @auth0/nextjs-auth0@4.0.0-beta.3`

**Comment by brandicph** [comment]
> Hey @brandicph 👋 We've just cut a new release which should now allow you to pass the logout URL in the `returnTo` query parameter. The README docs have also been updated to reflect that.
> 
> Please feel free to upgrade to the latest and give it a shot: `npm i @auth0/nextjs-auth0@4.0.0-beta.3`

Amazing @guabu - already installed 😎 Thanks for the fast response!
