### ISSUE TITLE
V4 Nextjs 15 Pages Router SRR pages attempt to fetch user information at compile time

### ISSUE THREAD

**Issue by MrSimmmons** [auth0/nextjs-auth0#1801]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When having a SSR page using `getServerSideProps` function, the `next build` step will attempt to compile the SSR page which is using the `await auth0.getSession(ctx)` function. This then fails because it attempts to create a new instance of the `Auth0Client` which fails because it actually attempts to load the user information at compile time.
(worth noting that I'm assuming its attempting to do this based off the fact that the environment variable validation checks inside `Auth0Client` are the first thing to fail which would only happen if its attempting to create a new instance)

Ideally the system would be smart enough to know that I am requesting user specific information on this page and not treat it as a static site

### Reproduction

1. Create a V15 Pages router project using the create next app CLI https://nextjs.org/docs/pages/api-reference/cli/create-next-app
2. Follow the getting started guide provided in the V4 readme up to the "Accessing the authenticated user" [SSR page](https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#on-the-server-pages-router) using a standard route name (not a dynamic `[].txs` one)
3. Attempt to build the app using `next build`

### Additional context

TBH I'm not too sure if this is a Auth0 issue or a Next.js issue. But I have a vague memory of there being a way for some code to tell the Next.js compiler / bundler to treat any page calling it as being dynamic and to not attempt to compile it.

### nextjs-auth0 version

4.0.0-beta.2

### Next.js version

15.0.3

### Node.js version

20.18.0

**Comment by MrSimmmons** [comment]
Hey @guabu , I don't think so because removing the SSR page from the repo allows the project to build even when all the environment variables are defined as empty strings. Its only if the SSR page is there does it fail at build time.

Also, its only variables prefixed with `NEXT_PUBLIC_` that are required at build time because those variables are bundled with the client side code.

I think it is because Next.js is trying to fully compile the SSR page to be a static page even though I'm using `getServerSideProps`. There is a comment [here](https://github.com/vercel/next.js/discussions/35534#discussioncomment-2420828) on the Next.js github repo that describes that if you don't want "collecting page data" to run, to use `getServerSideProps` instead of `getStaticProps`. However it seems that it is being run here.

code example
```ts
// src/pages/ssr.tsx

export const getServerSideProps = (async (ctx) => {
  const session = await auth0.getSession(ctx.req);

  if (!session) return { props: { user: null } };

  return { props: { user: session.user ?? null } };
}) satisfies GetServerSideProps<{ user: SessionData['user'] | null }>;

export default function SSRPage({
  user,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return <p>Hello {user?.name ?? '[Unknown]'}</p>;
}
```

then running build on local
<img width="743" alt="Screenshot 2024-11-15 at 10 15 25 PM" src="https://github.com/user-attachments/assets/1a22370f-4d75-4b72-8ce6-49b3cad5e3ce">

You can see that it fails on the "Collecting page data" step which doesnt make sense since its a dynamic page

This is why I'm not 100% sure if this is a Next.js issue or an Auth0. If I remove the SSR page, the build happens fine even though I still have my `Auth0Client` in the code and being used in the middleware & api routes.

Im leaning a little more towards this being an Auth0 issue as all of [Next.js's documentation](https://nextjs.org/docs/pages/building-your-application/deploying#environment-variables) says that putting things inside `getServerSideProps` should mark it as being a runtime concern not a build time concern

**Comment by MrSimmmons** [comment]
@guabu 

> Does it fail at build time when all the environment variables are defined?

Nah it passes, but the way I have my stuff set up atm, my build pipeline don't have access to runtime variables. Hence the origin of this issue.

---

Ok I think I understand why now. I just tried doing this and having the import be inside of `getServerSideProps` instead of being outside and it builds successfully.
```ts
export const getServerSideProps = (async (ctx) => {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const auth0 = await require('~/lib/Auth0/client');

  const session = await auth0.auth0.getSession(ctx.req);

  if (!session) return { props: { user: null } };

  return { props: { user: session.user ?? null } };
}) satisfies GetServerSideProps<{ user: SessionData['user'] | null }>;
```

> We could remove the checks that the environment variables are defined but ultimately we sacrifice some feedback for the developer here.

Looking through some of the Next.js source code (and console logging the entire `process.env` obj during a build process to confirm), they seem to set a few different environment variables during the build process. So you could listen to one or some of them to determine if you should be checking env variables or not `process.env.NEXT_IS_EXPORT_WORKER = 'true'` being the one I think we should listen to here.

So this part of the `Auth0Client` class (I've shortened for space)
```ts
if (!domain) throw new Error(...);
if (!clientId) throw new Error(...);
if (!clientSecret) throw new Error(...);
if (!secret) throw new Error(...);
if (!appBaseUrl) throw new Error(...);

const { protocol } = new URL(appBaseUrl)
if (protocol !== "https:" && process.env.NODE_ENV === "production") {
  throw new Error(...);
}
```

You could wrap in a `process.env.NEXT_IS_EXPORT_WORKER` check

```ts
if (!process.env.NEXT_IS_EXPORT_WORKER) {
  if (!domain) throw new Error(...);
  if (!clientId) throw new Error(...);
  if (!clientSecret) throw new Error(...);
  if (!secret) throw new Error(...);
  if (!appBaseUrl) throw new Error(...);

  const { protocol } = new URL(appBaseUrl)
  if (protocol !== "https:" && process.env.NODE_ENV === "production") {
    throw new Error(...);
  }
}
```

That way none of the runtime variables get checked during build time. Since they aren't supposed to be checked during build time anyway since its a server only client

And the fact that the client is not instantiated during the building of the `middleware.ts` file is evidence of this.

**Comment by guabu** [comment]
Yup, I think you're spot on here.

The root of the issue is that Next.js loads the files during build time and if the environment variables aren't present and the library has a check, it'll error out. I've run into this several times with other libraries myself. This is particularly pronounced when self-hosting Next.js since Vercel automatically injects all environment variables during build-time.

I'll look at removing these environment variable checks since other folks might run into this as well. 👌 Unfortunately, this is more of a Next.js quirk expecting the env vars to be present when tracing file.

**Comment by MrSimmmons** [comment]
You can probably still keep the checks for runtime as, like you said, they are useful for development & runtime debugging. I haven't found (admittently I haven't looked very hard) any documentation around `process.env.NEXT_IS_EXPORT_WORKER` so I'm not sure if it is a flag 3rd party things _should_ be using. But it seems perfect for this case.

Another option would be to just move the variable checks outside of the constructor into like a private `validateConfig` method that is called once you try to do something

**Comment by MrSimmmons** [comment]
^ Linked another issue with it failing during CI testing.

> I'll look at removing these environment variable checks since other folks might run into this as well. 👌 Unfortunately, this is more of a Next.js quirk expecting the env vars to be present when tracing file.

Im not sure how if Next.js does anything with how test environments are set up, but it looks like keeping these checks in there might be more of an annoying issue without some clear documentation on how to fully set up an environment

**Comment by guabu** [comment]
Hey @MrSimmmons 👋 A change will land in the next release (linked above) that should no longer throw an error if the environment variable is not defined during the build step.

**Comment by guabu** [comment]
Hey @MrSimmmons 👋 Thanks for reporting the issue! The new release has been cut and should no longer throw if the env var is missing: `npm i @auth0/nextjs-auth0@4.0.0-beta.7`
