### ISSUE TITLE
4.0.0-beta.3/beta.7 JWT returned is incorrect

### ISSUE THREAD

**Issue by ltatakis-optaxe** [auth0/nextjs-auth0#1809]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In the app we use the Auth0 JWT to authenticate against our DB. However the JWT returned via

```
const session = await auth0.getSession()
or
const accessToken = await auth0.getAccessToken()
``` 

is incorrect!

https://jwt.io/ says it has `invalid signature` and that it looks like the JWT payload is not a valid JSON object.

In other apps we get the error 

```
Could not verify JWT: JWSError (CompactDecodeError Invalid number of parts: Expected 3 parts; got 5)
```

I have followed the Read~ME guidance and the advanced settings for our Regular Web App have the signature RS256 and is OIDC compliant. 

We have had this configuration working for a while now. 

I initially thought it might be due to our use of post login actions enhancing the JWT as it is seens in https://github.com/auth0/nextjs-auth0/issues/1804
as we do ` api.idToken.setCustomClaim(`DOMAIN/roles`, assignedRoles)` but commenting them out did not seem to make a difference 

### Reproduction

1. Using the middleware as per example 
```
export async function middleware(request: NextRequest) {
  const authResponse = await auth0.middleware(request)

  const session = await auth0.getSession()
  return authResponse
}
```
2. Output token is invalid

### nextjs-auth0 version

4.0.0-beta.3/beta.7

### Next.js version

15.0.3

### Node.js version

v22.11.0

**Comment by guabu** [comment]
Hey @ltatakis-optaxe 👋 The access token is encrypted by Auth0 (a JWE). You can pass an `audience` parameter to receive a JWT.

Our docs have some guidance on how you can pass parameters to the `/authorize` endpoint: https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#passing-authorization-parameters

**Comment by ltatakis-optaxe** [comment]
Hi @guabu, thanks for the quick reply. In the previous version I just did 

```
login: async (req: NextApiRequest, res: NextApiResponse) => {
    const { invitation, organization }: Query = req.query

    try {
      await handleLogin(req, res, {
        returnTo: '/dashboard/trade',
        authorizationParams: {
          scope: 'openid profile email offline_access',
          invitation,
          organization
        }
      })
    } catch (error) {
      logNodeError(error)
    }
  },
```

I have never applied an audience. Currently I have

```
export const auth0 = new Auth0Client({
  appBaseUrl: process.env.PUBLIC_APP_URL,
  domain: process.env.AUTH0_DOMAIN,
  clientId: process.env.AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET,
  signInReturnToPath: '/dashboard/trade',
  authorizationParameters: {
    scope: 'openid profile email offline_access',
    audience: 'AUTH0_APP_ID?'
  }
})

```

In the my Regular Web Application I cannot find any reference to an audience. I do not know what I should use. 

However, I am not sure if this is the issue, as even adding an audience (the client id) the JWT is still wrong.
 The session details that come through are correct so I am connected and retrieving the session correctly, but that token has a wrong signature somehow.

**Comment by nsanghi** [comment]
@guabu  - passing the `audience` in `auth0` constrcution as per [https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#passing-authorization-parameters](https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#passing-authorization-parameters) is not working for ver 4.0.0-beta.7.  Only opaque token is returned. Using Curl  correctly returns the access_token. 

Also keeping the Auth0 setting same and using `audience` with Next14 + nextjs-auth0:3.5.0 works fine.

**Comment by guabu** [comment]
Thanks for the additional information @ltatakis-optaxe. To share some context, the `audience` is the API that will receive the access token and can verify and decode it. If an audience it not specified, Auth0 will assume that the only audience is the `/userinfo` endpoint and will issue an opaque, encrypted token.

Essentially, the `audience` is: "who will receive the token and can verify it".

If you'd like to receive a JWT that you can verify and decode in another service, you will need to create an API in the Auth0 Dashboard and use its identifier as the `audience` — we've got some docs on how to set up an API here: https://auth0.com/docs/get-started/auth0-overview/set-up-apis

Let me know if that helps — I was able to confirm that specifying the `audience` does indeed return a JWT instead of a JWE.

> passing the audience in auth0 constrcution as per https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#passing-authorization-parameters is not working for ver 4.0.0-beta.7. Only opaque token is returned. Using Curl correctly returns the access_token.

Hey @nsanghi 👋 I haven't been able to reproduce this myself, passing the audience as follows returns a JWT-formatted access token:

```ts
import { Auth0Client } from "@auth0/nextjs-auth0/server";

export const auth0 = new Auth0Client({
  authorizationParameters: {
    audience: "https://example.com/test-api",
  },
});
```

_(where the `audience` parameter is the API identifier)_

Just to rule things out, could you try logging in by appending the audience to the login URL, like so: `/auth/login?audience=https://example.com/test-api` and letting me know if you get a non-opaque token back?

Also, if you're able to share a repo with your sample, that would help narrow down the issue faster.

Thank you!

**Comment by ltatakis-optaxe** [comment]
@guabu  thanks for this. I have now realised that 3.5.0 just retrieved the audience from the env variable directly `AUTH0_AUDIENCE` without the need to specify it.

**Comment by nsanghi** [comment]
@guabu - Here is the link to the repo - https://github.com/nsanghi/front-end
The payload to authorize url has "audience" like so
```
client_id: HlECXoHmo1ILOR12Xqsj65pnda53ZuJS
scope: openid profile email offline_access
response_type: code
redirect_uri: http://localhost:3000/auth/callback
audience: https://turbocore-api.com
nonce: bSbn3z_Efpc9Pf_VjQT8YKsAHJ7BLL2nYzkrqiEt4J0
state: Pa-jsyKUPRlWWaaPpNVqJ6VUKbC2ibS_Ene5nKWn5p0
code_challenge_method: S256
code_challenge: k9IIgqfchSuYUHAHK0d6nssYmi1_sgDs3MYZ5TytP4g
```
Still opaque token is stored in the cookie. Similar code with the same Auth0 Application/API settings works fine with 3.5.0
