### ISSUE TITLE
v4.0.0-beta.7 - Cannot export the User type

### ISSUE THREAD

**Issue by ltatakis-optaxe** [auth0/nextjs-auth0#1810]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I would like to be able to use the `User` type returned by  `import { useUser } from '@auth0/nextjs-auth0'` in my code for typing. It does not seem however I can use it in my project.

In previous versions we were able to do 

```
import { UserProfile, useUser } from '@auth0/nextjs-auth0/client'
```

### Reproduction

Trying to import a type for the user from `useUser` hook

### nextjs-auth0 version

v4.0.0-beta.7

### Next.js version

15.0.3

### Node.js version

v22.11.0

**Comment by guabu** [comment]
Hey @ltatakis-optaxe 👋 You should be able to get the `User` type like so:

```
import { type SessionData } from "@auth0/nextjs-auth0/server";
type User = SessionData["user"];
```

We'll improve the type exports in the next release so you can directly import the the `User` type — thanks for bringing that up!

**Comment by guabu** [comment]
We consolidated the types to be available under the `/types` submodule and the `User` can now be imported as follows: `import { User } from "@auth0/nextjs-auth0/types";` in `4.0.0-beta.8`.

Thanks for the feedback and patience here!
