### ISSUE TITLE
v4.0.0-beta.7 - Cannot export withMiddlewareAuthRequired()

### ISSUE THREAD

**Issue by SvitlanaNedilko** [auth0/nextjs-auth0#1812]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I would like to be able to use withMiddlewareAuthRequired by import { useUser } from '@auth0/nextjs-auth0/edge' but Cannot find module @auth0/nextjs-auth0/edge or its corresponding type declarations.

In previous versions we were able to do

import { UserProfile, useUser } from '@auth0/nextjs-auth0/client'

### Reproduction

import withMiddlewareAuthRequired

### nextjs-auth0 version

4.0.0-beta.7

### Next.js version

14.2.17

### Node.js version

22.11.0

**Comment by alecdesjardins** [comment]
@guabu How would you protect by default with v4?

**Comment by nandan-bhat** [comment]
This issue is fixed on `4.0.0-beta.10`. Closing this ticket.

**Comment by alecdesjardins** [comment]
@nandan-bhat is there documentation for it?
