### ISSUE TITLE
npm: 4.0.0-beta.7 is tagged as latest

### ISSUE THREAD

**Issue by samuelcole** [auth0/nextjs-auth0#1814]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

[In npm, 4.0.0-beta.7 is tagged as `latest`](https://www.npmjs.com/package/@auth0/nextjs-auth0?activeTab=versions), which makes my `yarn upgrade-interactive` think it's ready for prime time, but I don't believe yall believe that (since the v4 branch isn't the main branch, the version has beta in it, etc).

<img width="893" alt="image" src="https://github.com/user-attachments/assets/3387cf0f-ab31-42ca-a898-aaf25f16a592">

### Reproduction

`yarn upgrade-interactive`

<img width="851" alt="image" src="https://github.com/user-attachments/assets/72891168-20b3-424b-b6fd-420225e64452">

### nextjs-auth0 version

4.0.0-beta.7

### Next.js version

15.0.3

### Node.js version

20

**Comment by guabu** [comment]
Hey @samuelcole 👋 You're absolutely right — something went amiss with the last release publishing. We'll get it corrected, sorry about that!

**Comment by nandan-bhat** [comment]
We have fixed this issue. Closing this.
