### ISSUE TITLE
v4 not exporting AccessTokenError

### ISSUE THREAD

**Issue by robcaldecott** [auth0/nextjs-auth0#1819]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In our custom middleware we are checking for an auth0 session token like this:

```ts
const accessToken = await auth0.getAccessToken();
if (!accessToken) {
  // Redirect to the auth0 login page
  return NextResponse.redirect(new URL("/auth/login", req.url));
}
```

However, I think `getAccessToken` can also throw errors, and if so we want to redirect to login. In this case we would need to handle `AccessTokenError` so we can do something like this:

```ts
try {
  const accessToken = await auth0.getAccessToken();
  ...
} catch (err) {
  if (err instanceof AccessTokenError) {
    console.error(err);
    return NextResponse.redirect(new URL("/auth/login", req.url));
  }
  throw err;
}
```

However, I cannot find `AccessTokenError` in the auth0 package.

For now I can instead do this:

```ts
try {
  const accessToken = await auth0.getAccessToken();
  ...
} catch (err) {
  if (err instanceof Error && err.name === "AccessTokenError") {
    console.error(err);
    return NextResponse.redirect(new URL("/auth/login", req.url));
  }
  throw err;
}
```

But I think access to `AccessTokenError` would be preferred.

Thanks in advance.

### Reproduction

See above

### nextjs-auth0 version

4.0.0-beta.6

### Next.js version

15.0.3

### Node.js version

20

**Comment by guabu** [comment]
Hi @robcaldecott 👋 Thanks for the feedback! In the next release (linked above), the `AccessTokenError` will be thrown when a new token could not be obtained. The error and codes will also be exported under `@auth0/nextjs-auth0/errors`.

**Comment by chris-erickson** [comment]
Can this be added to the migration guide?
