### ISSUE TITLE
v4.0.0-beta.7(getAccessToken) - when occured error while trying to refresh the access token should not provide expired one

### ISSUE THREAD

**Issue by sleitor** [auth0/nextjs-auth0#1820]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

when occured error while trying to refresh the access token should not provide expired one

Also nice to have catch that error somehow.

### Reproduction

in your app on server or middleware side add that console:

```javascript
  const accessToken = await auth0.getAccessToken();
  console.log('accessToken', accessToken);
```

1. Set on manage.auth0 for api short "Maximum Access Token Lifetime" (ie 30 sec)
2. Authorize in your app. 
3. Block the user on auth0 side
4. Refresh the page when token should be expired

**Actual result:** 

in the concole will get 2 messages:
```javascript
Failed to fetch token set: An error occured while trying to refresh the access token.
accessToken middleware {
  token: '<eyJhbGciO...>',
  expiresAt: 1732268568
}
```

**Expected result:** 
accessToken should not be presentented.

**Possible solutions:**

1. throw an error on getAccessToken
2. OR responce null with additional hook for error

### nextjs-auth0 version

v4.0.0-beta.7

### Next.js version

15.0.3

### Node.js version

v20.18.0

**Comment by robcaldecott** [comment]
Came here to say the same. We are getting the following logged when called `auth0.middleware` in our custom middleware:

```
Failed to fetch token set: The access token has expired and a refresh token was not granted.
```

Yet `auth0.getAccessToken()` yields a token. And in the UI, calling `useUser` seems to work!

What we want to do is redirect to `/auth/login` if the token is invalid. And we want all routes protected, so middleware is the place we want to make these checks.

**Comment by guabu** [comment]
Hey @sleitor and @robcaldecott 👋 Thanks for reporting this and sharing the reproduction steps!

We have a fix for that will be out in the next release (early this week). An error (`AccessTokenError`) will be thrown then the access token has expired and a new one could not be obtained.

**Comment by guabu** [comment]
`4.0.0-beta.8` has now been released and the `getAcessToken()` method will throw an error if the token has been expired and could not be refreshed.

The `AccessTokenError` can be imported via `import { AccessTokenError } from "@auth0/nextjs-auth0/errors";`

Thanks for the feedback!
