### ISSUE TITLE
v4 - ability to pass user directly to client from server

### ISSUE THREAD

**Issue by ajwootto** [auth0/nextjs-auth0#1823]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

With v3 we had the "UserProvider" component that accepted a user argument allowing you to pass the user directly from the server to the client without requiring it to make a request back to the server:

```
const session = getSession()

<UserProvider user={session.user}>
...etc
```

Now the `useUser` hook always makes a fetch request, which prevents immediate rendering of content that depends on the current user.

### Describe the ideal solution

There should be a built-in option for providing the user that we already have access to in server components on the clientside, rather than making it perform another full round-trip to the server just to get back the same information.

**Comment by guabu** [comment]
Hey @ajwootto, you should be able to serialize and pass the user from the server to your client components. Our documentation has examples of how to do that: https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#on-the-server-app-router

I hope that helps!

**Comment by ajwootto** [comment]
Hi @guabu, I know I can definitely do that myself but what I'm suggesting is that the SDK should provide an out-of-the-box "UserProvider" like v3 did, so that the `useUser` hook doesn't need to make a clientside fetch request to get the info we already have. Right now I've made my own `useUser` hook that reads from my own custom context rather than use the SDK's built-in method, which seems strange given that this would be a very common use-case for this SDK.

**Comment by guabu** [comment]
Hey @ajwootto, thanks for clarifying! We plan on adding an `<Auth0Provider />` as an abstraction to pass in an initial user (for the `useUser()` hook) as well as client-side configuration.

Under the hood we use SWR which can be configured by `<SWRConfig />` but we wanted to introduce a better abstraction for this rather than leaking the underlying implementation.
