### ISSUE TITLE
v4 beta 7 user type is not exported

### ISSUE THREAD

**Issue by ajwootto** [auth0/nextjs-auth0#1824]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

There is no export of the User type representing the user, so Typescript users cannot type things based on that without grabbing it via return types of other methods etc.

### Reproduction

see above

### nextjs-auth0 version

4.0.0-beta.7

### Next.js version

15

### Node.js version

22

**Comment by 634750802** [comment]
Workaround `SessionData['user']`

**Comment by guabu** [comment]
Hi @ajwootto 👋 We'll get that added in the next release, thanks for the feedback!

In the meantime, you can use the workaround suggested by @634750802 and as mentioned in the other thread: https://github.com/auth0/nextjs-auth0/issues/1810#issuecomment-2485886607

**Comment by guabu** [comment]
We consolidated the types to be available under the `/types` submodule and the `User` can now be imported as follows: `import { User } from "@auth0/nextjs-auth0/types";` in `4.0.0-beta.8`.

Thanks for the feedback and patience here!
