### ISSUE TITLE
v4 beta 8 "getAccessToken" is typed to possibly return null

### ISSUE THREAD

**Issue by ajwootto** [auth0/nextjs-auth0#1831]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The server-side getAccessToken method on the Auth0Client has a type definition that says it can possibly return null. However, since it throws when access token is not obtainable, it doesn't seem like this is possible (at least from my reading of the code). Is there a reason to expect we need to both catch thrown errors _and_ null check the result when it doesn't throw? It seems like it should be one or the other

### Reproduction

above

### nextjs-auth0 version

4.0.0-beta.8

### Next.js version

14.2.8

### Node.js version

22

**Comment by guabu** [comment]
Thanks for reporting this! You're correct, the `getAccessToken()` should not return `null`. Updating the types was overlooked when we moved away from returning `null` to throwing in the most recent release.

This should be fixed in the next release.

**Comment by nandan-bhat** [comment]
Closing this ticket as this issue has been fixed `4.0.0-beta.9`
