### ISSUE TITLE
v4.0.0-beta.9 updateSession support

### ISSUE THREAD

**Issue by KaiKloepfer** [auth0/nextjs-auth0#1836]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

In v3, we can call `updateSession` to make changes to the session from the backend, in the v4 beta this functionality is not present.

Ideally we'd like to be able to do something like this from the server:

```
const session = await auth0.getSession();
if (session) {
  await auth0.updateSession({
    ...session,
    user: { ...session.user, dbUser: true },
  });
}
```

### Describe the ideal solution

Add support for `updateSession` in v4

**Comment by guabu** [comment]
Hi @KaiKloepfer 👋 Could you share a little bit more about your use case here? We've removed the `updateSession` method in favour of [the `beforeSessionSaved` hook](https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#beforesessionsaved) which allows you to modify the session before persisting it.

You should be able to do something like so:

```
export const auth0 = new Auth0Client({
  async beforeSessionSaved(session) {
    return {
      ...session,
      user: {
        ...session.user,
        dbUser: true,
      },
    }
  },
})
```

This would only happen after the user has successfully authenticated and is redirected back from Auth0 to your application.

**Comment by calumerskine** [comment]
Imagine the application persists metadata on the user session and allows the user to edit that metadata, ie a `first_name`.

Without the `updateSession` helper, there doesn't seem to be a way to update the session without forcing the user to re-authenticate.

**Comment by guabu** [comment]
Thanks for the additional context, @calumerskine!

I would expect a property like `first_name` to be stored on the user object itself (either in Auth0 or your own application's data store) and not the session itself. In this particular scenario, the next time the user authenticates, their session data will be updated and that property (e.g.: `first_name`) will be overwritten and they will see a different first name.

That's not to say that there aren't valid use cases for the `updateSession` helper — so your feedback here is quite helpful. We're mostly trying to understand how it's being used and to try to make a distinction between data that should be stored on the user (persistent) vs session (ephemeral).

**Comment by calumerskine** [comment]
We're adding claims to the session right now for profile state so will have to lift that up to a service wrapper that queries the user object instead.

The changes for `v4` look great so far. If the move is to make the session state immutable, maybe some helpers for working with persistent data on the user object might be useful.

**Comment by guabu** [comment]
Thanks for the feedback! I agree, we can definitely improve how we handle user updates and how they're synced back to the user profile in Auth0 — today this requires the use of the Management SDK.

We'll look into either getting the `updateSession` helpers added or provide some helpers for updating the user profile more seamlessly.

**Comment by guabu** [comment]
We've added support for the `updateSession` helper in the latest release (`4.0.0-beta.11`). Thank you for your feedback here!
