### ISSUE TITLE
return to query string on logout not work

### ISSUE THREAD

**Issue by Intbar** [auth0/nextjs-auth0#1838]
### Checklist

- [ ] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

![image](https://github.com/user-attachments/assets/aa6839ea-fd26-4ce0-bad6-826cfab4a805)

error

What was expected to happen:
no bug and return to url with query string

What happened:
bug

### Reproduction

![image](https://github.com/user-attachments/assets/25b6742b-fe9e-401a-addb-d02a97e590c5)

step 1:
use v4 auth0 next js
step 2:
logout with return url with query string
step 3:
not work

it works if you leave out returnTo or leave out the query string and make it just base url in returnTo

### Additional context

the base URL is in allowed logout urls auth0

![image](https://github.com/user-attachments/assets/e6e05635-4b88-4098-aed6-a1738a8416a2)

Auth0 says this so the query string should not matter

### nextjs-auth0 version

4.0.0-beta.9

### Next.js version

15.0.4

### Node.js version

v20.12.0

**Comment by guabu** [comment]
Hi @Intbar 👋 You will need to include the query string in the **Allowed Logout URLs** you registered for the client ([see docs](https://auth0.com/docs/authenticate/login/logout/log-users-out-of-auth0#add-query-string-parameters-to-post_logout_redirect_uri)):

> The OIDC Logout endpoint parses query string parameters in the URL provided to the post_logout_redirect_uri parameter.
> 
> You must include these query string parameters in your Allowed Logout URLs, or the logout request may be denied.
> 
> For example, if you pass https://example.com/logout?myParam=1234 to the post_logout_redirect_uri parameter (encoded as `https%3A%2F%2Fexample.com%2Flogout%3FmyParam%3D1234`), **you must include `https://example.com/logout?myParam` in your Allowed Logout URLs.**

**Comment by Intbar** [comment]
WHOOPS i am stupid 😔thank you for reply
