### ISSUE TITLE
Add SWRConfiguration to useUser

### ISSUE THREAD

**Issue by droganov** [auth0/nextjs-auth0#1839]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved
for: `"@auth0/nextjs-auth0": "4.0.0-beta.9"`

I need to tweak SWR to my preference

### Describe the ideal solution

Before:

```ts
export declare function useUser(): {
    user: null;
    isLoading: boolean;
    error: Error;
} | {
    user: User | undefined;
    isLoading: boolean;
    error: undefined;
};
```

after:
```ts
export declare function useUser(config?: SWRConfiguration): {
    user: null;
    isLoading: boolean;
    error: Error;
} | {
    user: User | undefined;
    isLoading: boolean;
    error: undefined;
};
```

### Alternatives and current workarounds

```ts
interface UseUserHook {
  (): { isIdle: boolean } & SWRResponse<User>
}

export const useUser: UseUserHook = () => {
  const response = useSWR(
    '/auth/profile',
    async (...args) => {
      const res = await fetch(...args)
      if (!res.ok) {
        throw new Error('Unauthorized')
      }
      const data = await res.json()
      return data
    },
    {
      onError: rewokeAccessToken,
      onSuccess: getAccessToken,
    }
  )

  return { ...response, isIdle: !response.data && !response.error }
}
```

**Comment by nandan-bhat** [comment]
Closing this issue as it has been resolved in `4.0.0-beta.11`.
