### ISSUE TITLE
Can't get ididToken on v4 version

### ISSUE THREAD

**Issue by psycpvv** [auth0/nextjs-auth0#1840]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In our project, we have to get idToken for token trading.

This is v3 code. As you can see, I could get idToken from `session` object.
```ts
import { NextResponse } from 'next/server'

import auth0 from '@/config/auth0'

export const GET = auth0.withApiAuthRequired(async function GET(req) {
  const res = new NextResponse()
  try {
    const session = await auth0.getSession(req, res)
    const user = session?.user
    if (!user?.email_verified)
      return NextResponse.json(
        { error: 'email is not verified' },
        { status: 400 },
      )
    return NextResponse.json(
      { idToken: session?.idToken, user: session?.user },
      res,
    )
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message },
      { status: error.status || 500 },
    )
  }
})
```
But idToken doesn't exist in the `session` object of v4.

```ts
import { Auth0Client } from '@auth0/nextjs-auth0/server'

import { BASE_URL } from '@/constants/constants'

export const auth0 = new Auth0Client({
  appBaseUrl: BASE_URL,
  authorizationParameters: {
    scope: 'openid profile email read:products offline_access',
  },
})
```
Already `openid` is added on scope.
Help me pls.

### Reproduction

```ts
const session = await auth0.getSession()
console.log(session?.idToken)
// undefined
```
I think, it's enough to explain.

### nextjs-auth0 version

4.0.0-beta.9

### Next.js version

15.0.4

### Node.js version

v22.11.0

**Comment by guabu** [comment]
Hi there! In v4 we do not store the ID token in the session as it's meant to be a snapshot of the user claims. We validate the token, decode it, and make the claims available on the `user` property of the session.

The [`beforeSessionSaved` hook](https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#beforesessionsaved) allows you to have access to the complete set of claims from the ID token if you need to manage which attributes from the ID token make it into the session.

> In our project, we have to get idToken for token trading.

I'm not sure I fully understand what you mean here but if you need to call an external API, we recommend using the access token and specifying and `audience` instead. https://auth0.com/docs/secure/tokens/access-tokens/get-access-tokens

**Comment by psycpvv** [comment]
![image](https://github.com/user-attachments/assets/2c9df101-0aa8-4d7e-8ee4-e04038cd7574)
I got the Id Token from https://treesury.eu.auth0.com/oauth/token API.
I think, It's not the correct way to get an id token. But currently, I can get id token only this way.

**Comment by psycpvv** [comment]
@guabu Isn't there a better solution to get IdToken?

**Comment by guabu** [comment]
Hey @psycpvv, we will explore passing the ID token as a parameter to the `beforeSessionSaved` and/or `onCallback` hooks — this would allow you to persist or use the token. However, it won't be available on the session by default, only it's claims.

For the time being, your approach of calling the token endpoint is completely valid if you need to get a fresh token set with the ID token.

**Comment by guabu** [comment]
In the latest release `4.0.0-beta.13`, you should now be able to access the ID token via the `beforeSessionSaved` hook as documented here: https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#beforesessionsaved
