### ISSUE TITLE
beforeSessionSaved not working

### ISSUE THREAD

**Issue by ArthurLaurijssen** [auth0/nextjs-auth0#1842]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description
Before session saved isn't being called or not working properly 

### Reproduction
``import { Auth0Client } from "@auth0/nextjs-auth0/server";

export const auth0 = new Auth0Client({
  async beforeSessionSaved(session) {
    return {
      ...session,
      test: "test",
      user: {
        ...session.user,
        foo: "bar",
      },
    };
  },
});
` and in middleware.ts `const session = await auth0.getSession();
    console.log("Session:", session);``
1. I try to add some data in the session for the beforeSessionSaved(session)
2. Try to access it in middleware 
3. I don't get any data
4. Console.logs in beforeSessionSaved don't show up so I think it might not be called properly 

### nextjs-auth0 version

4.0.0-beta.10

### Next.js version

15.1

### Node.js version

Node.js v20.13.0.

**Comment by guabu** [comment]
Hi @ArthurLaurijssen 👋 I've tried to reproduce the issue you're reporting but the `beforeSessionSaved` hook is indeed being called successfully and I'm seeing the `session` being logged in the middleware.

Perhaps there may be an issue with how the project is set-up or the tenant is configured. Do you see that the user has been authenticated successfully?

Would you mind sharing a repo with this issue so we can try to reproduce it on our end?

**Comment by ArthurLaurijssen** [comment]
My mistake I wasn't properly logging out and back in . Thanks for checking this with me tough.
