### ISSUE TITLE
v4 "The application's base URL is not set to HTTPS" warning is annoying in localhost

### ISSUE THREAD

**Issue by ajwootto** [auth0/nextjs-auth0#1847]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The error that the SDK logs about the scheme of the base URL not being HTTPS is very annoying in local development, especially when running against localhost which is obviously not a production environment.

I get this error logged like 20 times while the build is running locally, and then again on every page visit.

### Describe the ideal solution

I think this warning should explicitly ignore domains that contain "localhost" since it's most likely that someone is running `npm build && npm start` locally if that is what the environment variable is set to.

**Comment by guabu** [comment]
Thanks for the feedback! We've removed the warning log in the latest release to be more inline with v3's behavior and to reduce the noise from logs during builds and running apps via `next start` in tests and locally.
