### ISSUE TITLE
Client side handoff

### ISSUE THREAD

**Issue by maraisr** [auth0/nextjs-auth0#193]
Currently this library only supports getting access tokens and things on the server.

What would a solution look like where these token's are handed to the client, such that client's can make their own api calls using a JWT.

What I envision, is an approach where `spa-js` is used instead, auth happening on the client, and only upon successful auth we set a cookie, and the client is then in charge of keeping that up to date?

**Comment by adamjmcgrath** [comment]
Hi @maraisr - doing SPA authentication in a Next app is a valid approach, but not one supported by this SDK.

If you want to use Next.js but don't want to manage auth on the server. I recommend you check out our Next.js example in the `auth0-react` SDK repo  https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md#3-protecting-a-route-in-a-nextjs-app-in-spa-mode

I'd also recommend you check out the Beta here https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0 - it has a new suite of front end tools including a `useUser` hook and `withPageAuthRequired` higher order component (but still auth is managed by a server based session)

I think that's answered your question, so closing for now, update this thread if you want me to reopen it.
