### ISSUE TITLE
oidcClient httpTimeout doesn't work

### ISSUE THREAD

**Issue by spmsupun** [auth0/nextjs-auth0#197]
Whatever you put in `httpTimeout` it always response as `TimeoutError: Timeout awaiting 'request' for 2500ms`
```
...
  oidcClient: {
    httpTimeout: 1000000,
    clockTolerance: 10000,
  },
```

![image](https://user-images.githubusercontent.com/1854023/100515624-76f30380-31a3-11eb-8d5b-cc804890e919.png)

**Comment by pstoica** [comment]
Did you resolve this? I've been seeing the same and was curious.

**Comment by spmsupun** [comment]
This happened when I use next js inside a docker container when I used without it, it worked.
