### ISSUE TITLE
Documentation on how to refresh the user

### ISSUE THREAD

**Issue by SpicyPete** [auth0/nextjs-auth0#199]
### Describe the problem you'd like to have solved

This library seems to have support for refresh tokens, but there aren't any examples of how to use this token to refresh the user session.
Once the token expires, the user is currently invalid until they visit the `/api/login` endpoint again.   

### Describe the ideal solution

Documentation or example on how to use the refresh token.  
Ideally an example of how to refresh the user session on across an entire NextJS site.

**Comment by adamjmcgrath** [comment]
Hi @SpicyPete - thanks for raising this

You can't refresh the session - the Refresh Token is to refresh a short lived Access Token that the session manages. To manage the session expiration you should use the session duration properties in the config.

The new Beta has additional config properties to manage this, namely [session.absoluteDuration](https://auth0.github.io/nextjs-auth0/interfaces/config.sessionconfig.html#absoluteduration) and [session.rollingDuration](https://auth0.github.io/nextjs-auth0/interfaces/config.sessionconfig.html#rollingduration).

For example, the default values `absoluteDuration: 604800, rollingDuration: 86400` ensure that the session will expire after 604800 secs (7 days) or 86400 secs (24hrs) of inactivity.

You can check out the Beta here https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0

Closing for now, update this thread if you want me to reopen it.
