### ISSUE TITLE
Guidance on how to utilize the tokenCache with external APIs WITHOUT proxying your calls through NextJS api routes

### ISSUE THREAD

**Issue by drewdecarme** [auth0/nextjs-auth0#201]
### Describe the problem you'd like to have solved

The guidance that is provided in the documentation states that it is a common pattern to proxy any external API requests that require authorization headers or access tokens in some form, through the NextJS provided API mechanisms. This is totally fine, but with a large external API, that would ostensibly require you to re-write that API. In all honestly, I'd like to avoid doing that.

I want to still be able to use the `tokenCache` on the client to only fetch new tokens based upon time to live, refresh rotation, etc... but the only way that I see right now is, on every API call, fetch the token using the `api/token` endpoint and then stuff that token in the headers of the client-side request.

To me, that doesn't seem like the most optimal solution since every client-side request is going to have to fetch a token from the node server and then fetch the data from the external api; 2 round trips

### Describe the ideal solution

**I'm wondering if there is any official guidance on how to go about using the [NextJS Auth0](https://github.com/auth0/nextjs-auth0) package on the client-side?** That would specifically alleviate the need to re-write any external endpoints, just for the sake of using the server-side tokenCache.

## Alternatives and current work-arounds

1. The first thing that came to mind is to use the `auth0/nextjs-auth0` package to manage sign-in, sign-out, and the callback, and then on the client, use the `auth0/auth0-spa-js` package separately. I think it's kind of clunky and would add weight to the client-side package.
2. The second thought that I had was to implement a client-side cache that kind of mimics the mechanisms used in the next-js package, but I fear that this is only going to be re-creating the wheel.

**Comment by iamchathu** [comment]
Great to couple Auth0 SPA SDK with this to use the Token in Client Side too

**Comment by OriginalEXE** [comment]
I personally proxy all requests through a Next.js API route (as mentioned in your title) and with that approach you don't need 2 roundtrips on the frontend. I proxy the requests on the backend to the API itself, and then respond to the client directly. The client is non the wiser that it was really an external API endpoint :)

I do agree it's not super convenient, but not that I got it working, I quite like it actually.

**Comment by adamjmcgrath** [comment]
Hi @drewdecarme - Thanks for raising this.

Whilst we do not recommend this approach unless strictly necessary. We've added guidance for this in the Beta examples https://github.com/auth0/nextjs-auth0/blob/beta/EXAMPLES.md#access-an-external-api-from-the-front-end

Note the caveat in the example. Generally, we recommend the approach that @OriginalEXE has kindly explained above.

You can check out the Beta here https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0

Closing for now, update this thread if you want me to reopen it.

**Comment by drewdecarme** [comment]
Thanks for getting back on this. Also, great to see that this is finally going from experimental to beta. Super stoked about that.

One of the things I love about SSR is keeping the secrets on the server. There's just something about the implicit flow and storing session and access token keys on the client that makes me feel dirty and want to take a shower. This in turn makes this package really attractive and honestly, gives me some warm and fuzzies.

Before you got back to me, I was sending access tokens down via pageProps for pages that required authentication. From there I was populating a context in the layout layer included in the `/pages/_app.tsx` to use the token throughout the app. I'm not really getting around the problem I just described above but just repeating it in a different way. It's a little less obvious, but none the less, there are still access tokens hanging out in the app and would be open to XXS attacks at any point.

After doing this for a while, I really think I might start proxying all requests through a NextJS route. I mean what're a few extra files to increase security, ammiright?

@OriginalEXE You're technically right. It's not two round trips to the client, but instead, it's adding one more hop to communicated with the external API server, which is still 1, repeating code, and 2 adding some more latency to that request.

I feel like it's really a pick your poison type scenario. @adamjmcgrath Would you and your team mind commenting on the method that I explained above? Is that another acceptable solution or am I missing something altogether that would make that sub-optimal?

**Comment by adamjmcgrath** [comment]
Hey @drewdecarme

> @adamjmcgrath Would you and your team mind commenting on the method that I explained above?

Sure, sending access tokens down via pageProps is acceptable, with the caveat you described - that having access tokens on the front end leaves them vulnerable to XSS

Our best practice is what @OriginalEXE has described, proxying requests to external APIs from Next API routes protected with the encrypted cookie session

**Comment by drewdecarme** [comment]
@adamjmcgrath Appreciate the follow-up man!
