### ISSUE TITLE
requireAuthentication and accessToken

### ISSUE THREAD

**Issue by jaredgalanis** [auth0/nextjs-auth0#205]
The `requireAuthentication` handler seems to only check for the existence of a session and user on that session, but I am noticing that it is possible to have a session, but an invalid access token. 

An invalid access token should invalidate the session or the `requireAuthentication` handler should check for the validity of `accessToken`.

**Comment by adamjmcgrath** [comment]
Hi @jaredgalanis - thanks for raising this

My answer to this is the  same as your other Issue https://github.com/auth0/nextjs-auth0/issues/206#issuecomment-760921032
