### ISSUE TITLE
profileHandler does not respond with an authentication error if access token is expired

### ISSUE THREAD

**Issue by jaredgalanis** [auth0/nextjs-auth0#206]
The `profileHandler` throws an `Error` if no valid access token is available, but it does not respond with a `not_authenticated` response in same way that it does if there is a lack of `session`.

**Comment by adamjmcgrath** [comment]
Hi @jaredgalanis - thanks for raising this

The expiry of the Access Token (and or that matter, the expiry of the ID Token) does not dictate the duration of the session, nor visa-versa. For example, you might have a short lived Access Token and that should be refreshed with a Refresh Token (which may have a very long lived expiry). 

So I wouldn't expect necessarily the `profileHandler` to throw when the Access Token has expired, only when the session has expired.

Closing for now, update this thread if you want me to reopen it.
