### ISSUE TITLE
AccessTokenError: The user does not have a valid access token.

### ISSUE THREAD

**Issue by 37devv** [auth0/nextjs-auth0#207]
### Description

I know that this thread exists: https://github.com/auth0/nextjs-auth0/issues/90 but it didn't help me.
The answers in that thread, were that the audience value in the auth0 config was missing. In my case it's there and the same in the settings and in the backend api.

I'm calling an endpoint in the backend, which requires a scope. Im doing this in the getServerSideProps method.
When I try to get an accessToken from the tokencache, I receive following error:
**AccessTokenError: The user does not have a valid access token.**

### Reproduction

https://auth0.com/docs/quickstart/backend/aspnet-core-webapi/01-authorization Check out the starter repo and modify the value in the appsettings.json to fit your settings.

Create a role, assign it to the user and give that role the read:messages permission.
Log in as a user, which has the role and call an endpoint in the backend.
The endpoint must be called in the getServerSideProps method in a nextjs project. The call can be in any nextjs page you create.

My code: 

```
export async function getServerSideProps(context) {

  let data= null;

    const tokenCache = auth0.tokenCache(context.req, context.res);

     //CODE FAILS HERE
    const { accessToken } = await tokenCache.getAccessToken({
      scopes: ['read:messages']
    });

    
    todos = await axios.get("http://localhost:3010/api/private", {
      'Authorization' : `Bearer ${accessToken}`
    })
      .then(response => data= response.data)
      .catch(error => console.error(error));
   
  }

  return {
    props: {
           ...
    },
  };
}
```

### Environment
Env variables:
```
import { initAuth0 } from '@auth0/nextjs-auth0';

export default initAuth0({
    audience: 'process.env.AUDIENCE',
    domain: process.env.AUTH0_DOMAIN,
    clientId: process.env.AUTH0_CLIENT_ID,
    clientSecret: process.env.AUTH0_CLIENT_SECRET,
    redirectUri: 'http://localhost:3000/api/callback',
    postLogoutRedirectUri: 'http://localhost:3000/',
    scope: 'openid profile read:messages',
    session: {
        // The secret used to encrypt the cookie.
        cookieSecret: process.env.COOKIE_SECRET,
        // The cookie lifetime (expiration) in seconds. Set to 8 hours by default.
        cookieLifetime: 60 * 60 * 8,
        // (Optional) Store the id_token in the session. Defaults to false.
        storeIdToken: false,
        // (Optional) Store the access_token in the session. Defaults to false.
        storeAccessToken: false,
        // (Optional) Store the refresh_token in the session. Defaults to false.
        storeRefreshToken: false,
    },
});
```

Dependencies
"@auth0/nextjs-auth0": "^0.16.0",

**Comment by ashburnham** [comment]
`storeAccessToken` and `storeRefreshToken` need to be `true`

**Comment by snavaneeth78** [comment]
> `storeAccessToken` and `storeRefreshToken` need to be `true`

I have both set to true & still have the same error.

**Comment by adamjmcgrath** [comment]
> `audience: 'process.env.AUDIENCE',`

Hi @37devv - from the code you've shared it looks like you're passing the string `'process.env.AUDIENCE'` when you should be passing the value of `process.env.AUDIENCE` (it should not be in single quotes) eg:

```js
{
    audience: process.env.AUDIENCE,
    ...
}
```

**Comment by adamjmcgrath** [comment]
Closing for now - feel free to ping me if you want me to reopen
