### ISSUE TITLE
Site-wide authentication

### ISSUE THREAD

**Issue by GMaiolo** [auth0/nextjs-auth0#208]
### Describe the problem you'd like to have solved
Currently this library fits all my needs with the exception of handling site-wide authentication, the issue arises with a NavBar that's outside the pages (as it's global and it's always showing) where I need to display the user avatar/name and pretty much feedback of being either logged in (displaying a link to the user profile) or not logged in (displaying a login/signup button). 

### Describe the ideal solution
The ideal would be to either have a way of authenticating in _app while avoiding to use `getInitialProps` as we lose SSG capabilities in our whole application.
Another solution would involve having a way to get auth information client side, like [@auth0/auth0-react](https://www.npmjs.com/package/@auth0/auth0-react) does with the `useAuth()` hook.

## Alternatives and current work-arounds
The most straightforward work around is to get the user in all pages' `getServerSideProps`, pass the information down to the pages and for the pages to set the information in Redux or in a custom Context in order for that information to be consumable by a site-wide component – like the global NavBar in my case. But this requires a lot of code repetition to the point where it stops being intuitive.
Another workaround is to get the information in `getInitialProps` but by doing so, as mentioned above, we lose a lot of great capabilities that Nextjs provides.

### Additional information, if any
Right now I'm defaulting to use [@auth0/auth0-react](https://www.npmjs.com/package/@auth0/auth0-react) because of the simplicity it provides.

**Comment by adamjmcgrath** [comment]
Hi @GMaiolo - thanks for raising this

We now have a `useUser` frontend hook and a `withPageAuthRequired` higher order component in the Beta that works the same as `auth0-react`. See https://auth0.github.io/nextjs-auth0/modules/frontend_use_user.html and https://auth0.github.io/nextjs-auth0/modules/frontend_with_page_auth_required.html

You can check out the Beta here https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0

Closing for now, update this thread if you want me to reopen it.
