### ISSUE TITLE
Unable to set as session cookie with no expiration date 

### ISSUE THREAD

**Issue by DeeJEarl88** [auth0/nextjs-auth0#213]
### Description

>  The `cookieLifetime` field is currently always being defaulted to 8 hours. I'd like it so my clients cookies expire and are removed when they close the browser. This requires the cookie expiry to not be set...

**Comment by adamjmcgrath** [comment]
Hi @DeeJEarl88 - thanks for raising this

This is now possible in the Beta, using the `cookie.transient` option https://auth0.github.io/nextjs-auth0/interfaces/config.cookieconfig.html#transient

You can check out the Beta here https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0

Closing for now, update this thread if you want me to reopen it.
