### ISSUE TITLE
Fetching identity provider access_token

### ISSUE THREAD

**Issue by talkl** [auth0/nextjs-auth0#217]
I am following the tutorial of [how to fetch identity provider access_token](https://auth0.com/docs/connections/calling-an-external-idp-api).
I am unable to get the user that logged in using a social identity provider to have the sufficient scopes: [read:users, read:user_idp_tokens]

<img width="1002" alt="Screen Shot 2021-01-03 at 15 58 37" src="https://user-images.githubusercontent.com/9368630/103480680-458ed880-4dde-11eb-86ce-be3c10e325a9.png">

as you can see from the previous screenshot read:users and read:user_idp_tokens were not assigned to the user when he was triggered a consent forum.

im getting this error

AccessTokenError: Could not retrieve an access token with scopes "read:users read:user_idp_tokens". The user will need to sign in again.
    at SessionTokenCache.<anonymous> (/Users/...)
  name: 'AccessTokenError',
  code: 'insufficient_scope'

NEXT_PUBLIC_AUTH0_SCOPE="openid profile email read:users read:user_idp_tokens offline_access"
NEXT_PUBLIC_API_AUDIENCE=https://XXXXX.us.auth0.com/api/v2/

`import { initAuth0 } from '@auth0/nextjs-auth0';

export default initAuth0({
  clientId: process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET,
  scope: process.env.NEXT_PUBLIC_AUTH0_SCOPE,
  domain: process.env.NEXT_PUBLIC_AUTH0_DOMAIN,
  audience: process.env.NEXT_PUBLIC_API_AUDIENCE,
  redirectUri: process.env.NEXT_PUBLIC_REDIRECT_URI,
  postLogoutRedirectUri: process.env.NEXT_PUBLIC_POST_LOGOUT_REDIRECT_URI,
  session: {
    cookieSecret: process.env.SESSION_COOKIE_SECRET,
    cookieLifetime: Number(process.env.SESSION_COOKIE_LIFETIME),
    storeAccessToken: true,
    storeRefreshToken: true,
  },
});
`

`import fetch from 'isomorphic-unfetch';
import { NextApiRequest, NextApiResponse } from 'next';
import auth0 from '../../lib/auth0';

export default async function proxy(req: NextApiRequest, res: NextApiResponse) {
  try {
    const tokenCache = auth0.tokenCache(req, res);
    const { accessToken } = await tokenCache.getAccessToken({
      scopes: [`read:users`, `read:user_idp_tokens`],
    });
    const url = `https://${process.env.NEXT_PUBLIC_AUTH0_DOMAIN}/api/v2/users/${req.query.userId}`;
    const response = await fetch(url, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    });
    const user = await response.json();
    console.log(user);
    const idpToken = user.identities[0].access_token;
    console.log(`idpToken`, idpToken);
    res.status(200).json({ idpToken });
  } catch (error) {
    console.error(error);
    res.status(error.status || 500).json({
      code: error.code,
      error: error.message,
    });
  }
}
`

`import SideBar from '@/components/SideBar/SideBar';
import { IUser } from '@/lib/user';
import WithAuth from '@/components/with-auth/WithAuth';
import useApi from '@/lib/use-api';
import React from 'react';
import Layout from '../../components/Layout/Layout';

function Profile({ user }: { user: IUser }) {
  const { response, error, isLoading } = useApi(`/api/proxy`, {
    params: {
      userId: user.sub,
    },
  });
  return (
    <Layout loading={false}>
      <SideBar user={user} />
      <h1>Profile</h1>

      <div>
        <h3>Profile (server rendered)</h3>
        <img src={user.picture} alt="user" />
        <p>nickname: {user.nickname}</p>
        <p>name: {user.name}</p>
      </div>
      {isLoading && <div>Loading IDP Token...</div>}
      {!isLoading && error && <div>Error: {error}</div>}
      {!isLoading && response && <div>Response: {response}</div>}
    </Layout>
  );
}

export default WithAuth(Profile);
`

`import fetch from 'isomorphic-unfetch';
import { useEffect, useState } from 'react';

function initialState(...args: unknown[]) {
  return {
    response: null,
    error: null,
    isLoading: true,
    ...args,
  };
}

const useApi = (url, options = {}) => {
  const [state, setState] = useState(() => initialState());

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await fetch(url, {
          ...options,
        });

        if (res.status >= 400) {
          setState(
            initialState({
              error: await res.json(),
              isLoading: false,
            }),
          );
        } else {
          setState(
            initialState({
              response: await res.json(),
              isLoading: false,
            }),
          );
        }
      } catch (error) {
        setState(
          initialState({
            error: {
              error: error.message,
            },
            isLoading: false,
          }),
        );
      }
    };
    fetchData();
  }, []);
  return state;
};

export default useApi;
`

`"dependencies": {
    "@auth0/nextjs-auth0": "0.16.0",
    "@fortawesome/fontawesome-svg-core": "1.2.32",
    "@fortawesome/free-brands-svg-icons": "^5.15.1",
    "@fortawesome/react-fontawesome": "0.1.13",
    "antd": "4.9.4",
    "bootstrap": "4.5.3",
    "isomorphic-unfetch": "3.1.0",
    "lottie-react": "2.1.0",
    "next": "10.0.3",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  },`

**Comment by talkl** [comment]
@sandrinodimattia hey Sandrino, can you help with this?

**Comment by talkl** [comment]
solved!

from sandrino,

The scopes you request (openid profile email offline_access ...) are all on behalf of the user. But read:user_idp_tokens cannot be requested on behalf of the user, it can only be requested by a protected client.

Long story short, this is what you'll need to do (assuming you are using the Next.js Auth0 SDK):

1. Go to the dashboard, open APIs, open "Auth0 Management API" and then go to "Machine to Machine Applications"
2. There you'll need to authorize the Next.js application and enable the read:users and read:user_idp_tokens permissions
3. In Next.js, create a protected API route (eg: /pages/api/get-gh-repos.js)
4. Then in that route, you should use the Auth0 SDK to get an API v2 token: https://github.com/auth0/node-auth0/blame/master/README.md#L74-L93 (this is done by using the client ID and secret of the Next.js application, so it can authenticate on its own behalf)
5. From there, you can retrieve the current user from API v2 and it will also contain the user's access token for GH/Bitbucket/...
6. As a final step, use that token to call the GH API

Note: you'll want to cache some of this information since the Management API has some strict rate limits.

**Comment by adamjmcgrath** [comment]
Thanks for sharing your solution @talkl
