### ISSUE TITLE
No state or session cookies set when `NODE_ENV` is production and deployed environment is not secure

### ISSUE THREAD

**Issue by RyanPayso13** [auth0/nextjs-auth0#239]
We have not yet got a secure environment so the deployed environment is `http` only.

When we try to use this library on `localhost` then everything works fine but when deployed i see no `a0:state` or `a0:session` cookies being stored even though the `a0:session` cookie is sent back in the `callback` response.

As we are in `production` mode but deploying to an insecure environment is there a way to set the cookies in the lib to be insecure for this scenario?

I found this commit:

https://github.com/auth0/nextjs-auth0/commit/885a76a4401207fbe40a1e18db15d92e04b9f7e8

Which solves the issue I am having but it only seems to be part of the latest beta release which is not advised for production.  Is there anyway to add this functionality to 0.16.0?

**Comment by Widcket** [comment]
Hi @RyanPayso13, the 0.x codebase will not be further developed, as our focus is now on getting the newly released beta to GA.

**Comment by adamjmcgrath** [comment]
> As we are in production mode but deploying to an insecure environment is there a way to set the cookies in the lib to be insecure for this scenario?

Hey @RyanPayso13 - In the Beta, the cookie secure property defaults to the protocol of the [baseUrl](https://auth0.github.io/nextjs-auth0/interfaces/config.config-1.html#baseurl), but you can override this using the [session.cookie.secure options or AUTH0_COOKIE_SECURE environment variable](https://auth0.github.io/nextjs-auth0/interfaces/config.cookieconfig.html#secure)

**Comment by RyanPayso13** [comment]
@adamjmcgrath I saw the beta but unfortunately it states it is not ready for production so am reluctant to go down that route.

Is there any other way?

**Comment by adamjmcgrath** [comment]
Hey @RyanPayso13 - this library is in an experimental state, so we won't describe it as ready for production until the Beta version is released as `1.x`
