### ISSUE TITLE
Documentation inconsistency

### ISSUE THREAD

**Issue by mvxt** [auth0/nextjs-auth0#240]
### Description
In the [1.0.0-beta.0 docs](https://auth0.github.io/nextjs-auth0/interfaces/config.config-1.html#authorizationparams), it indicates the default values for `authorizationParams` scope look like this: `scope: 'openid profile email'`.

However, when I setup the default and access the `/api/auth/me` route, it only returns the following user params:

```
{
  "nickname":"my-test-user",
  "name":"my-test-user@test.com",
  "picture":"test.png",
  "updated_at":"2021-01-17T06:18:39.941Z",
  "sub":"[REDACTED]"
}
```

On the other hand, when I explicitly specify the `authorizationParams` with `scope: openid profile email`, it returns the following params:
```
{
  "nickname":"my-test-user",
  "name":"my-test-user@test.com",
  "picture":"test.png",
  "updated_at":"2021-01-17T06:12:21.769Z",
  "email":"my-test-user@test.com",
  "email_verified":true,
  "sub":"[REDACTED]"
}
```

It seems like the default doesn't include `email` in the scope, which is inconsistent with the documentation. Not sure if the docs are wrong, the functionality is not aligning with expectations, or if I've somehow messed something up.

### Reproduction

> Setup Auth0 per basic example or docs. Make no changes to the default `[...auth0].js`:
```
import { handleAuth } from '@auth0/nextjs-auth0';

export default handleAuth();
```
> Log in with a user and visit the `/api/auth/me` route. Observe that `email` and `email_verified` are not included in the response body.
> Modify your `[...auth0].js` to the following:

```
import { handleAuth, handleLogin } from '@auth0/nextjs-auth0';

export default handleAuth({
  async login(req, res) {
    try {
      await handleLogin(req, res, { 
        returnTo: '/dashboard',
        authorizationParams: {
          response_type: 'code',
          scope: 'openid profile email',
        }
      });
    } catch (error) {
      res.status(error.status || 500).end(error.message);
    }
  }
});
```
> Log out and log back in with changes saved. Visit the `/api/auth/me` route. Observe that `email` and `email_verified` are now included.

### Environment

- **Version of this library used:** 1.0.0-beta.0
- **Version of the platform or framework used, if applicable:** Node v15.0.1
- **Other relevant versions (language, server software, OS, browser):** macOS 10.15.7, Chrome 87.0.4280.141

**Comment by Widcket** [comment]
Hi @mvxt, `openid profile email` is indeed [the default](https://github.com/auth0/nextjs-auth0/blob/beta/src/auth0-session/get-config.ts#L70). I'm not able to reproduce the issue, when I try out the [basic example app](https://github.com/auth0/nextjs-auth0/tree/beta/examples/basic-example) the response of `/api/auth/me` includes the email.

**Comment by mvxt** [comment]
That's really bizarre. I'm not sure what the difference is that's causing this discrepancy. I'm also not able to recreate the issue on the example app, it's only happening on my application.

I'll close this issue and do some further investigation.
