### ISSUE TITLE
Twitter email not returned in user data

### ISSUE THREAD

**Issue by prahna** [auth0/nextjs-auth0#243]
### Description

Hey, I'm using nextjs-auth0 in my app, the configuration of all social connections works very well. Google, Facebook and Twitter authentication works as intended, the only missing information is the user's email is missing from Twitter. I know there's a special configuration to be done and I've done it all, meaning: in the Twitter project configuration, I have turned on the Request email address and provided privacy policy/terms and conditions pages. In Auth0, I have added the rule to enrich the profile with the email. I also real-time debugged the rule and it works perfectly fine, I see the email returned and set to the user's data. 
The issue I have is in the Nextjs app, when I call the auth0.handleProfile call, it doesn't return the email address. The access token returned also when decoded doesn't include the email address which is pretty annoying as that's what I send to my API (ASP.NET Core) to return the User's data from my DB, and not having the email address doesn't play well.
Did anyone face a similar issue ? What's the way to get the email address from Twitter synced in the profile of the Auth0 user ? Or is there anyway through nextjs-auth0 to get that information ?

Thank you very much

### Reproduction

- Handle Twitter login in your app
- Configure Twitter project configuration to Request user's email on logon
- Add the Enrich profile from Twitter rule in Auth0
- Test login and try to get the email address back

Here is the rule I'm using to enrich the profile:

`function getTwitterEmail(user, context, callback) {
  // additional request below is specific to Twitter
  if (context.connectionStrategy !== 'twitter') {
    return callback(null, user, context);
  }

  const _ = require('lodash');
  const request = require('request');
  const oauth = require('oauth-sign');
  const uuid = require('uuid');

  const url = 'https://api.twitter.com/1.1/account/verify_credentials.json';
  const consumerKey = configuration.TWITTER_CONSUMER_KEY;
  const consumerSecretKey = configuration.TWITTER_CONSUMER_SECRET_KEY;

  const twitterIdentity = _.find(user.identities, { connection: 'twitter' });
  const oauthToken = twitterIdentity.access_token;
  const oauthTokenSecret = twitterIdentity.access_token_secret;

  const timestamp = Date.now() / 1000;
  const nonce = uuid.v4().replace(/-/g, '');

  const params = {
    include_email: true,
    oauth_consumer_key: consumerKey,
    oauth_nonce: nonce,
    oauth_signature_method: 'HMAC-SHA1',
    oauth_timestamp: timestamp,
    oauth_token: oauthToken,
    oauth_version: '1.0'
  };

  params.oauth_signature = oauth.hmacsign(
    'GET',
    url,
    params,
    consumerSecretKey,
    oauthTokenSecret
  );

  const auth = Object.keys(params)
    .sort()
    .map(function (k) {
      return k + '="' + oauth.rfc3986(params[k]) + '"';
    })
    .join(', ');

  request.get(
    url + '?include_email=true',
    {
      headers: {
        Authorization: 'OAuth ' + auth
      },
      json: true
    },
    (err, resp, body) => {
      if (resp.statusCode !== 200) {
        return callback(
          new Error('Error retrieving email from twitter: ' + body || err)
        );
      }
      user.email = body.email;
      user.app_metadata = user.app_metadata || {};
      // update the app_metadata that will be part of the response
      user.app_metadata.social_email = user.email;

      // persist the app_metadata update
      auth0.users.updateAppMetadata(user.user_id, user.app_metadata)
      .then(function(){
        callback(null, user, context);
      })
      .catch(function(err){
        callback(err);
      });

      return callback(err, user, context);
    }
  );
}`

### Environment

Version used is 0.16.0

**Comment by adamjmcgrath** [comment]
Hi @prahna - thanks for raising this

Twitter connections do not retrieve the user's email address by default. However, you can add a rule to request the email address using the Access Token returned from Twitter providing you supply a privacy policy and terms & conditions.

See here for more information on how to do this: https://auth0.com/docs/connections/social/twitter#user-s-email-address-is-missing-from-retrieved-user-profile

**Comment by prahna** [comment]
Hi Adam,

Thank you for your response. My question was on the side of nextjs-auth0, is there a call that we can do to get the full profile of a user, including the email stored in the auth0 user (that I can see through their UI). Or a way to return the structures user_metadata. 

Thanks in advance

**Comment by adamjmcgrath** [comment]
> My question was on the side of nextjs-auth0, is there a call that we can do to get the full profile of a user, including the email stored in the auth0 user (that I can see through their UI). Or a way to return the structures user_metadata.

nextjs-auth0 will only give you an ID Token, an Access Token and a Refresh Token.

If you want more fields from the user object that aren't in the ID Token's claims you have 2 options:

- Add those fields to the ID Token's claims in a Rule https://auth0.com/docs/rules/examples#add-roles-to-a-user and https://auth0.com/docs/connections/social/twitter#user-s-email-address-is-missing-from-retrieved-user-profile
- Get an Access Token for the Auth0 Management API and use it to access `/api/v2/users/{id}`

**Comment by prahna** [comment]
I see, thank you very much for your help, much appreciated.
