### ISSUE TITLE
Mode=signup not working in v0.5.0

### ISSUE THREAD

**Issue by matthieuh** [auth0/nextjs-auth0#25]
### Description

As answered in this issue: https://github.com/auth0/nextjs-auth0/issues/16 it should be possible in `v0.5.0` to use the login handler to redirect user to signup screen (instead of the login one by default).

Seems still not working.

### Reproduction

- Call a `pages/api` route using this config

```javascript
await auth0.handleLogin(req, res, {
  authParams: {
    mode: 'signup'
  }
});
```

=> Im expecting a redirection to the signup page

**Comment by sandrinodimattia** [comment]
@matthieuh, in order for this to work you need to add some logic to your login page (and it only works if you use Classic mode today).

Full example is available here: https://github.com/sandrinodimattia/nextjs-auth0-example/commit/ce7f73b24ea04398a52e959cc5ac43842c509397

Let me know if we can close the issue.

**Comment by matthieuh** [comment]
Thank a lot for the explanation! Make totally sense to me now. 👌
Feel free to close it.

**Comment by matthieuh** [comment]
I finally found something that seems an issue.

Adding the `prompt` parameter to `authParams` key/value seems also passed to all others social auth providers.

It can be reproduced trying to register with google on your example project: https://nextjs-auth0-demo.now.sh/ google returning a 400 with the error message "Invalid parameter value for prompt: Invalid prompt: signup".

**Comment by sandrinodimattia** [comment]
@matthieuh, thanks for reopening the issue. You can actually send custom parameters to Auth0, and my example with prompt might not have been the best for now. So I updated the example to use a different name, which mitigates the issue (eg, `initialScreen` will not be sent to the connection):

https://github.com/sandrinodimattia/nextjs-auth0-example/commit/d71a499bf150705e235dd8dbc827a1ddabce6e37

**Comment by matthieuh** [comment]
I forgot to say that it was working on my side with you explanations and your updated example 👍

**Comment by hichana** [comment]
The code:
`var lock = new Auth0Lock(config.clientID, config.auth0Domain, {
  ...
  initialScreen: (config.extraParams.prompt === 'signup' && 'signUp') || 'login',
  ...
});`

should be added in the 'Universal Login' section of your auth0 account:

<img width="1071" alt="Screen Shot 2020-06-25 at 4 28 08 PM" src="https://user-images.githubusercontent.com/8943047/85676138-4a712200-b701-11ea-8b33-08a12279825a.png">
