### ISSUE TITLE
Handle cross-authentication between naked domain and www domain

### ISSUE THREAD

**Issue by davlxd** [auth0/nextjs-auth0#250]
### Description

Our production site, like a lot of other sites, handle both naked domain (`https://example.com`) and www domain (`https://www.example.com`).

I am facing an issue that is the `redirectUri` callback URL can only be configured as one of the two. Let's say `redirectUri` is configured as `https://www.example.com/api/callback`, then if user tries to login via `https://example.com/login`, because login handler only set `a0:state` cookie to current domain ([here](https://github.com/auth0/nextjs-auth0/blob/9093a416b0eacc396f5f018460622a23e6f3cb91/src/handlers/login.ts#L90)), `https://www.example.com/api/callback` cannot receive `a:state` cookie therefore error will be throw `Invalid request, an initial state could not be found`, user fails to login.

If I configured the other way around vice versa.

I suppose the issue I am facing is not an uncommon one, so

- Am I being stupid that I have some misunderstandings about cookie protocol so I have this issue?
- Since this is not uncommon, usually how do we handle this issue  with `nextjs-auth0` ?
- The way I see it, there are 2 solutions, one is enabling configuration of cookie domain of [this](https://github.com/auth0/nextjs-auth0/blob/9093a416b0eacc396f5f018460622a23e6f3cb91/src/handlers/login.ts#L90) `setCookies`, so to set cookie domain to `.example.com` will solve this issue; Or maybe allow dynamic override of `redirectUri`, like in [here](https://github.com/auth0/nextjs-auth0/blob/9093a416b0eacc396f5f018460622a23e6f3cb91/src/handlers/login.ts#L80), extract `redirectUri` from options, so I can populate from `req.host` per request. These 2 solutions involve change of code, not sure if you guys are interested :)

<br /><br />
Many Thanks, Looking forward to shed some light on me :)

**Comment by adamjmcgrath** [comment]
Hi @davlxd 

> Am I being stupid that I have some misunderstandings about cookie protocol so I have this issue?

No - it's a sensible question :D

> The way I see it, there are 2 solutions, one is enabling configuration of cookie domain of this setCookies, so to set cookie domain to .example.com will solve this issue;

I recommend you check out the new Beta https://github.com/auth0/nextjs-auth0/tree/beta 

It allows you to [configure the cookie domain](https://auth0.github.io/nextjs-auth0/interfaces/config.cookieconfig.html#domain), which will resolve your issue
