### ISSUE TITLE
Error using withPageAuthRequired in beta version

### ISSUE THREAD

**Issue by prahna** [auth0/nextjs-auth0#251]
### Description

Hello, I have an app using the beta version of nextjs-auth0 and I have an issue with a page that requires the user to be authenticated but also does server side API calls in its getServerSideProps. This is the code I'm using now:

`
export const getServerSideProps = auth0.withPageAuthRequired({
  async getServerSideProps(ctx) {
    const res = await fetch("https://xxxxxx/api/images");
    const data = await res.json();

    return { props: { data } };
  },
});
`

This code works perfectly when the user is actually authenticated, it does the request and returns the good data structure.
But when the user is not authenticated, I receive this error:

![image](https://user-images.githubusercontent.com/1527444/105389583-fc17f900-5be5-11eb-8cc9-76d12d09036f.png)

Do you guys know what I'm doing wrong ? Isn't this the right way to use the withPageAuthRequired ?

Thank you for your help

### Reproduction

Create an app that uses the beta version of nextjs-auth0
- Secure one page with the withPageAuthRequired hook
- Add an implementation to the getServerSideProps that does some async query
- Test it with an authenticated user
- Test it without authenticated user

### Environment

Chrome
Nextjs 10
nextjs-auth0 1.0 beta

**Comment by Widcket** [comment]
Hi @prahna, I tried to reproduce it but was unsuccessful:

https://user-images.githubusercontent.com/5055789/105421373-c6dccc80-5c20-11eb-9d3b-b8e03d59f990.mov

What do the invalid props contain?

**Comment by adamjmcgrath** [comment]
@prahna - also could you double check what version of next you are using (run `npm ls next` from your project root)

**Comment by prahna** [comment]
Hey, the version of next I'm using is 9.5.5 and the version of nextjs-auth0 is 1.0.0-beta.0. 
One thing I wanted to mention to @Widcket is that the code inside my getServerSideProps never gets called in case the user is not authenticated, so it seems to me that the structure returned from that function comes from withPageAuthRequired directly and the getServerSideProps function parameter is not called in that case.

**Comment by prahna** [comment]
Hey, you were right @adamjmcgrath to think about the next version. I updated to the latest version 10.0.5 and the problem is not there anymore. This issue can be closed then.
Thank you very much for pointing to the right direction.
