### ISSUE TITLE
initAuth step is missing in the Beta Release Documentation

### ISSUE THREAD

**Issue by canrozanes** [auth0/nextjs-auth0#258]
### Describe the problem you'd like to have solved
I was going through the beta release documentation to asses whether I should upgrade to v1.0.0.beta but as I was reading the documentation, I realized the initAuth0({config}) step is missing.

Is that intentional? Does the new version encourage developers to just set env variables as this package expects or does it encourage the initAuth() step? 

Can it be clarified in the docs?

The migration guide found [here](https://github.com/auth0/nextjs-auth0/blob/v1.0.0-beta.0/V1_MIGRATION_GUIDE.md) suggests that the initAuth0 is still required as it has the following code snippet:

```js
import { initAuth0 } from '@auth0/nextjs-auth0';

export default initAuth0({
  baseURL: 'http://localhost:3000',
  issuerBaseURL: 'https://my-tenant.auth0.com',
  clientID: 'MY_CLIENT_ID',
  clientSecret: 'MY_CLIENT_SECRET',
  secret: 'some_very_long_secret_string',
  clockTolerance: 60,
  httpTimeout: 5000,
  authorizationParams: {
    scope: 'openid profile email',
    audience: 'MY_AUDIENCE'
  },
  routes: {
    callback: '/api/callback',
    postLogoutRedirect: '/'
  },
  session: {
    rollingDuration: 60 * 60 * 24,
    absoluteDuration: 60 * 60 * 24 * 7
  }
});
```

So a clarification from the maintainers would be appreciated.

### Describe the ideal solution

Ideal solution would clarify whether the initAuth0 step is required and if it is, show how to do it.

**Comment by Widcket** [comment]
Hi @canrozanes, in the beta it's no longer necessary to create your own instance of the SDK - it can instantiate a singleton instance and configure itself with the environment variables. You can still create your own instance, but alas it's no longer required.

**Comment by Widcket** [comment]
Please check [this](https://github.com/auth0/nextjs-auth0/blob/v1.0.0-beta.0/EXAMPLES.md#create-your-own-instance-of-the-sdk) for more details.

**Comment by canrozanes** [comment]
ahhh that makes sense. Thank you so much! Also just curious what needs to happen in this package for the stable v1.0.0 release for this package?

**Comment by Widcket** [comment]
We're fixing the issues we find, and making other minor changes. We look forward to getting the library to GA in the coming weeks.
