### ISSUE TITLE
Logout Handler deletes session before getting Id Token for Hint

### ISSUE THREAD

**Issue by chriskolenko** [auth0/nextjs-auth0#265]
On this line:

https://github.com/auth0/nextjs-auth0/blob/6f36586d7189959a67a6dc8f663a529de522ab7f/src/auth0-session/handlers/logout.ts#L33

The session cache is deleted before getting a copy of the IdToken which is needed on line:

https://github.com/auth0/nextjs-auth0/blob/6f36586d7189959a67a6dc8f663a529de522ab7f/src/auth0-session/handlers/logout.ts#L47

**Comment by adamjmcgrath** [comment]
Good catch @chriskolenko - thanks for raising this 👍

**Comment by adamjmcgrath** [comment]
fixed by #267
