### ISSUE TITLE
is it possible to use passwordless? how is this done?

### ISSUE THREAD

**Issue by vasco3** [auth0/nextjs-auth0#27]
### Describe the problem you'd like to have solved

> I would like to be able to use auth0 passwordless

### Describe the ideal solution

> The README could have a brief example of how to use passwordless

**Comment by maitham** [comment]
Would love to see an example on passwordless?

**Comment by sandrinodimattia** [comment]
This library will use Auth0's universal login capabilities, redirecting the user to the login page in Auth0. You can configure your login page to use Passwordless by changing the template:

![image](https://user-images.githubusercontent.com/655409/67610264-d78a6280-f791-11e9-921f-cc5bbef39a35.png)

**Comment by maitham** [comment]
Also you can make a `POST` client side 

```
{
  "client_id":  <client_id>,
  "connection": "email",
  "email":  <email>,
  "send": "link",
  "authParams": {
    "scope": "openid profile",
    "redirect_uri": "http://localhost:3000/api/callback",
    "state":  <auth0_state>, // grab this from the cookies
    "response_type":"code"
  }
}
```

**Comment by maitham** [comment]
@sandrinodimattia Whats the best way to do it if you want a custom login form, should I be doing what I specified in the comment above?

**Comment by vasco3** [comment]
thanks @sandrinodimattia that worked!

**Comment by abusada** [comment]
Hello, @vasco3, Did you get this to work?
I also need to use a custom login form, and the solution above results in a `state mismatch` error thrown by the `node-openid-client` library.

**Comment by zomars** [comment]
Maybe it's just me, but I'm getting a `Client authentication is required` since the client secret is not being sent.
