### ISSUE TITLE
The tslib dependency is missing in package.json

### ISSUE THREAD

**Issue by jacobwgillespie** [auth0/nextjs-auth0#270]
### Description

This library compiles TypeScript with `importHelpers` set to `true`, which means that all helpers will be imported from the `tslib` NPM module, however it does not depend on `tslib` in its dependencies. This means that it's unclear which version of `tslib` it will end up importing, as it will import any version of tslib that consumers of this library happen to have installed, including incompatible versions.

Because of this issue, Yarn 2 issues an error for this package at runtime, so anyone using Yarn 2 will see something like:

> Error: @auth0/nextjs-auth0 tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

The fix for this issue is to add `tslib` to `dependencies` in `package.json`. I'll open a PR that does this.

### Reproduction

`tslib` is not listed in `dependencies`:

https://github.com/auth0/nextjs-auth0/blob/a2932dcf6bd7294725c40ae4daff452fada11fc2/package.json#L106-L120

Also note that not every version of `tslib` is compatible with TypeScript 4.1 (currently the version in use here): https://github.com/Microsoft/tslib#npm.

### Environment

This is environment independent. Yarn 2 makes the issue explicit by printing an error message at runtime, but all package managers share the same issue.

**Comment by jacobwgillespie** [comment]
PR #271 opened with a fix (running `npm install tslib`).

**Comment by adamjmcgrath** [comment]
Merged #271 - thanks @jacobwgillespie!
