### ISSUE TITLE
Add afterRefetch option to handleProfile

### ISSUE THREAD

**Issue by marklawlor** [auth0/nextjs-auth0#273]
### Describe the problem you'd like to have solved

`nextjs-auth0` allows applications to include custom attributes within the JWT, but there are no means to update this data. If the token is refreshed indefinitely the user will be using stale data.

There should be a way to transparently update the user data without a logout/login.

### Describe the ideal solution

Add an `afterRefresh` option to `handleProfile` that allows the `session.user` to be customised. This callback has the same signature as the `afterCallback` option of `handleCallback`.

If the `afterRefresh` callback throws, it should abort the refresh. This allows users to implement custom functionality like DenyLists.

## Alternatives and current work-around

Create a wrapper for `handleProfile` that overrides the values in the `sessionCache` with the updated values.

**Comment by adamjmcgrath** [comment]
Hi @marklawlor - thanks for raising this.

In the new [beta](https://github.com/auth0/nextjs-auth0/tree/beta) any updates to the session are persisted, eg.

```js
// pages/api/my-api-route.js
import { withApiAuthRequired } from '@auth0/nextjs-auth0';

export default withApiAuthRequired(async function myApiRoute(req, res) {
  const { user } = getSession(req, res);
  user.custom_prop = 'foo'; // <= this will be persisted
});
```

Let me know if this doesn't meet the needs of your use case.

**Comment by marklawlor** [comment]
@adamjmcgrath That's functionality different to what I'm asking.

I would like to reuse the logic from `handleProfile({ refetch: true })`, but be able to modify or reject the session after a refetch as occurred.

When using `withApiAuthRequired` I would need to re-implement the refetch logic myself.

I'm not against that and it might be what the work around is. But this library already allows customisation of the session on creation, it makes sense to provide the same customisation on update.

**Comment by Widcket** [comment]
Fixed by https://github.com/auth0/nextjs-auth0/pull/276, which adds an `afterRefetch` hook.
