### ISSUE TITLE
Silently authenticating user for external API (with beta)?

### ISSUE THREAD

**Issue by mikestopcontinues** [auth0/nextjs-auth0#278]
Hi, I'm not sure I should post this here, but it seems like the issue has more to do with using the library than using Auth0 in general. 

Currently, I've got a NextJS admin app that hits an API on a different domain. I'm using this library to log users into the admin app, which does the whole redirect loop. Immediately after that, I'd like to produce an access token for the external API without disturbing the user's experience.

Since the user is already authenticated with the Auth0 app, and that app can grant access to the external API, it seems like I should be able to get an access code for the user to the external API without a second redirect, but I don't see any way to make that happen. I was able to use the client credentials flow for my local API to access the external API, but I'd rather not proxy all of my API requests.

What am I missing?

**Comment by adamjmcgrath** [comment]
Hi @mikestopcontinues - thanks for raising this

You can ask for an Access Token for an external API in your original login request by specifying the required `audience` and `scope` in the original login request, see this example https://github.com/auth0/nextjs-auth0/blob/beta/EXAMPLES.md#access-an-external-api-from-an-api-route

**Comment by mikestopcontinues** [comment]
Thanks, @adamjmcgrath. That did it!
