### ISSUE TITLE
There are a few dead links in the documentation.

### ISSUE THREAD

**Issue by dredshep** [auth0/nextjs-auth0#282]
I was checking out a page when I found a bunch of dead links. This is the page:

https://auth0.github.io/nextjs-auth0/modules/config.html

Most of these blue links don't work. The only ones that work are those that start with CookieConfig and SessionConfig.

![image](https://user-images.githubusercontent.com/78047001/107389167-eef77700-6acc-11eb-87aa-55a900978e79.png)

![image](https://user-images.githubusercontent.com/78047001/107389307-0f273600-6acd-11eb-93cd-2e3bc0ca437a.png)

**Comment by Widcket** [comment]
@dredshep Thanks for raising this. Fixed by #284.
