### ISSUE TITLE
Can auth0.handleProfile(req, res) return email and username?

### ISSUE THREAD

**Issue by bc2012** [auth0/nextjs-auth0#285]
In the auth0-Dashboard under Connections > Database, I have enabled ‘Requires Username’.
Now when signing-up the user must supply a username (in addition to an email and password).

Looking in the auth0-Dashboard under Users & Roles > Users
I can see values for:
Name
Email
Username 

Calling `await fetch('/api/me')` returns an object that contains:
name: //email if Username-Password-Authentication or name if google-oauth2
nickname: //beginning of email up to the ‘@‘ symbol

but not **email** or **username**.

Is there a way to have `auth0.handleProfile(req, res)` return **email** and **username**?

### Environment
@auth0/nextjs-auth0  0.16.0
next  10.0.5

**Comment by mvxt** [comment]
@bc2012 Did you check that you're including the `email` scope when initiating the login? Not sure if this will help but I posted about it here: https://community.auth0.com/t/nextjs-auth0-api-auth-me-route-doesnt-return-as-many-details-as-expected/56299/4?u=mvxt

**Comment by adamjmcgrath** [comment]
@bc2012 - thanks for raising this

@mvxt is correct, you need to update the scope from `openid profile` to `openid profile email` to include the email in your id token claims.

For username, you'll need to create a custom rule - see https://community.auth0.com/t/how-to-retrieve-username-with-auth0-spa-js/38940

**Comment by bc2012** [comment]
@mvxt @adamjmcgrath Thanks for the replies and solving my issues.
