### ISSUE TITLE
`The user does not have a valid session` when calling an api route to get an access token

### ISSUE THREAD

**Issue by RyanPayso13** [auth0/nextjs-auth0#288]
### Description

I am trying to decorate all my requests in axios interceptors.

I have an api route to return the token from the token cache `/api/token`:

```
import auth0 from '@/libs/auth0/auth0';
import { AccessTokenResponse } from '@auth0/nextjs-auth0/dist/tokens/token-cache';
import { NextApiRequest, NextApiResponse } from 'next';

export async function getAccessToken(
  req: NextApiRequest,
  res: NextApiResponse
): Promise<AccessTokenResponse> {
  const tokenCache = auth0(req).tokenCache(req, res);
  return tokenCache.getAccessToken();
}

export default async function token(
  req: NextApiRequest,
  res: NextApiResponse
): Promise<void> {
  try {
    const { accessToken } = await getAccessToken(req, res);
    res.status(200).end(accessToken);
  } catch (error) {
    res.status(error.status || 500).end(error.message);
  }
}
```

This works fine in the interceptor for api calls made client side

```
export async function onRequestFulfilled(
  config: AxiosRequestConfig
): Promise<AxiosRequestConfig> {
  const { data } = await axios.get('/api/token');

  if (data) {
    const result = {
      ...config,
      headers: {
        Authorization: `Bearer ${data}`,
      },
    };
    return result;
  }
  return config;
}
```

However this does not work for me on pages that make requests via `getServerSideProps`. I initially thought that I only needed to add the absolute url e.g. `http://localhost/api/token` but this throws the following error:

`The user does not have a valid session`

Is it possible to call an api route from `getServerSideProps`?

**Comment by adamjmcgrath** [comment]
Hi @RyanPayso13 

> Is it possible to call an api route from getServerSideProps?

It's possible (you're server side fetch will be missing the cookies from the original request), but not recommended. See: https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering

> Note: You should not use fetch() to call an API route in getServerSideProps. Instead, directly import the logic used inside your API route. You may need to slightly refactor your code for this approach.

You should use `tokenCache` directly from `getServerSideProps` rather than calling `/api/token`

**Comment by RyanPayso13** [comment]
That is what I am doing:

```
export async function getServerSideProps({
  req,
  res,
}: NextPageContext): Promise<Record<string, any>> {
  const { path } = absoluteUrl(req as IncomingMessage);
  const { accessToken } = await getAccessToken(
    req as NextApiRequest,
    res as NextApiResponse
  );

    try {
      await policyService.getPolicyByReference({
        path,
        policyReference,
        accessToken,
      });
    } catch (error) {
    }
  }

  return {
    props: {},
  };
}
```

But I wanted to remove the need to pass the token directly to  `policyService.getPolicyByReference` in this instance and instead have the interceptor pick up the token to avoid configuring api calls for SSR like so:

```
export function getPolicyByReference({
  path = '',
  policyReference,
  accessToken = null,
}: {
  path?: string;
  policyReference: string;
  accessToken?: string | null;
}): Promise<PaginatedResponseData<Policy>> {
  const config =
    accessToken !== null
      ? {
          headers: {
            Authorization: accessToken,
          },
        }
      : undefined;

  return axios.get(`${path}/v1/policies/${policyReference}`, config);
}
```

So I would ideally have an interceptor or a service at a higher abstracted level to decorate all calls for me with the token rather than using the axios interceptor for client side and my _hacky_ solution for SSR.

If I understand your comment correctly the reason for the error is that we do not have the `auth0` session cookie available?

From what I have read people have stored the access token in a cookie but this kind of defeats the object of having it available in the Node layer?

I appreciate the quick reply!

**Comment by adamjmcgrath** [comment]
> So I would ideally have an interceptor or a service at a higher abstracted level to decorate all calls for me with the token rather than using the axios interceptor for client side and my hacky solution for SSR.

This kind of pattern will work well in a browser, because there's only one user - so "all calls" are for the same user requiring the same token. On the server, "all calls" will be from different users, you need to query the request for a session to figure out which user, and therefor which token, to use.

> If I understand your comment correctly the reason for the error is that we do not have the auth0 session cookie available?

Yes, you're making a request to `/api/token` without a session cookie, and therefore no valid session

> From what I have read people have stored the access token in a cookie but this kind of defeats the object of having it available in the Node layer?

The Access Token _is_ stored (encrypted) in the session cookie, what `auth0.tokenCache(req, res).getAccessToken();` is essentially doing is reading the cookie from `req`, decrypting it and deserializing it into a session object, and querying that object for an Access Token.

**Comment by adamjmcgrath** [comment]
@RyanPayso13 Closing this - feel free to ping me if you want me to reopen
