### ISSUE TITLE
Reducing cookie size

### ISSUE THREAD

**Issue by DTAPigeons** [auth0/nextjs-auth0#289]
### Description

I recently upgraded to the beta because my session cookies were getting too big for the browser to store. Now with the new cookie splitting feature, it looks like they're being stored without an issue.

However, this creates a new concern. Both cookies get included in the header of every page request sent through the browser. Note.js has a header size limit of 8KB. The two session cookies combined are about 6-7KB which is dangerously close. What steps can I take to reduce the size of the cookie without impacting functionality?

Looking at the session itself it the largest properties it has are the idToken, accessToken and refresh token, followed by the accessTokenScope. Does the token cache use these values? if all my token interactions happen with the token cache do I need to 
keep these values in the session cookie?

**Comment by adamjmcgrath** [comment]
Hi @DTAPigeons - I've requested an Access Token JWT, an ID Token, a Refresh Token and my user has the default claims of a database connection user (6 claims: name, picture, etc.). My `appSession` cookie comes to around 3.5KB, the content itself plus some extra for the JWE encrypted session header:

```
{
  "user": {
    .. a few claims, ~350 Bytes ...
  },
  "idToken": " ... ~1KB ...",
  "accessToken": "... ~1KB ...",
  "accessTokenScope": "openid profile read:shows offline_access",
  "accessTokenExpiresAt": 1613139121,
  "refreshToken": "... ~ 50 Bytes ~~",
  "token_type": "Bearer"
}
```

If I want to use the token cache and handle cases where my Access Token expires then I need all the `accessToken*`, `refreshToken`  and `token_type` properties, they are stored in the session cookie to persist them across requests.

I'd only need the original `idToken` if I wanted to do a OIDC standard logout with a non Auth0 provider - so I can get rid of that. I could probably also drop the user claims I'm not using and save a few Bytes. So I could probably cut my session by ~1.2KB (~30%).

I assume your Access Token JWT, ID Token and Refresh Token are similar sizes, so you must have around 3KB extra of user claims. So you could remove the ID Token (which will save you 1KB) and whatever you can remove from your ~3KB user claims.

See the `AfterCallback` docs for info on how to modify the session before it's stored after login https://auth0.github.io/nextjs-auth0/modules/handlers_callback.html#modify-the-session-after-login

You could also consider increasing the `--max-http-header-size` of your Node server.

Also, in the future we plan to support custom session stores (so you'd store the session data somewhere else, like Redis, and the cookie would just contain a pointer to that session) - I don't yet have a date on when that feature will be available

**Comment by marklawlor** [comment]
@adamjmcgrath I just updated to v1 and something is wrong here.

I am using the Google social connection for my testing, it has a slightly larger ID token but I don't think thats the cause of the problem.

Without `afterCallback` get two cookie set of size 4012 and 65

With this `afterCallback`

```
const auth0 = initAuth0({ ... })

const auth0HandleAuth = auth0.handleAuth({
  callback(request, response) {
    return auth0.handleCallback(request, response, {
      afterCallback(request, response, session) {
        return {
          ...session,
          user: {}, // You just have to modify user in any manner
        };
      }
    });
  },
```

I now have 3 cookies with sizes 3422, 4012 and 65 and nearly doubled my request size. While this is example is under the request limit, adding a couple of custom claims easily pushes you over.

My current workaround is to strip the idToken from the payload

**Comment by adamjmcgrath** [comment]
> 3 cookies are set with sizes 3422, 4012 and 65. This has nearly doubled my request size.

@marklawlor - I suspect what's happened here is that you've logged in with a session that's > 4KB so the SDK has split it into 2 cookies: `appSession.0` and `appSession.1` (4012 and 65). Then, without logging out, you've logged in again and this time edited your session to be <4KB so it's created a single cookie `appSession` (3422).

Your previous chunked cookies (`appSession.0` and `appSession.1`) are now obsolete and will expire based on your cookie expiration settings. This scenario - logging in twice and switching between chunked and non-chunked cookies - is not a scenario I would expect to be likely to happen, except during development, and should be harmless. But I'll add some work to look at cleaning up the obsolete cookies when you switch between the two.

**Comment by marklawlor** [comment]
@adamjmcgrath Yep the cookie splitting was the issue, one of our claims is variable length and changes every refresh. We're now padding this claim to a consistent length.
