### ISSUE TITLE
Ability to check permissions

### ISSUE THREAD

**Issue by colinwolff** [auth0/nextjs-auth0#29]
### Describe the problem you'd like to have solved

> The library provides some helper functions like requireAuthentication for api routes, but currently there is no good way to check permissions from what I can tell.

### Describe the ideal solution

> I'd like a helper function to secure api routes based on the current users permissions. It can be used in conjunction with requireAuthentication. Something like:

```
// Route requires authentication
export default auth0.requireAuthentication(
  // Check for permissions
  auth0.checkPermissions(
    async function user(req, res) {
      try {
        await auth0.handleProfile(req, res);
      } catch (error) {
        console.error(error);
        res.status(error.status || 500).end(error.message);
      }
    },
    // Permissions to be checked - If the defined permissions are not found, the request would be denied.
    ["view:profile"]
  )
);
```

## Alternatives and current work-arounds

> I've been able to implement a solution to decode session tokens and verify permissions using jsonwebtoken & jwks-rsa, but would like to have something incorporated into the nextjs-auth0 library.

**Comment by adamjmcgrath** [comment]
Thanks for raising this @colinwolff 

See my comment in https://github.com/auth0/nextjs-auth0/pull/39#issuecomment-762374340
