### ISSUE TITLE
Beta: Missing "audience" option in handleLogin

### ISSUE THREAD

**Issue by bryanveloso** [auth0/nextjs-auth0#291]
### Description

I'm using the beta and writing in TypeScript, and Intellisense is giving me errors when I try to use `audience` and `scope` in the `handleLogin` options to use an external API as recommended here: https://github.com/auth0/nextjs-auth0/blob/beta/EXAMPLES.md#access-an-external-api-from-an-api-route

Looking at the API reference they seem to be missing: https://auth0.github.io/nextjs-auth0/interfaces/handlers_login.loginoptions.html

<img width="586" alt="Screen Shot 2021-02-12 at 5 31 11 PM" src="https://user-images.githubusercontent.com/1258/107856379-9b42a180-6ddc-11eb-96ac-6c4b8a29d238.png">

**Comment by Widcket** [comment]
Hi @bryanveloso, pass the audience and scope like so:

```js
await handleLogin(req, withLogs(res), {
    authorizationParams: {
        audience: 'audience',
        scope: 'scope'
    }
});
```

The snippet in [EXAMPLES](https://github.com/auth0/nextjs-auth0/blob/beta/EXAMPLES.md#access-an-external-api-from-an-api-route) is outdated, I'll raise a PR to fix it.

**Comment by bryanveloso** [comment]
Great, thank you!

**Comment by Dakuan** [comment]
> Also, you can set them via environment variables;

what's the env vars for audience and scope please?

**Comment by adamjmcgrath** [comment]
@Dakuan `AUTH0_SCOPE` and `AUTH0_AUDIENCE`

Full list https://auth0.github.io/nextjs-auth0/modules/config.html#1-environmental-variables
