### ISSUE TITLE
handleLogin doesn't resolve

### ISSUE THREAD

**Issue by willfalconer** [auth0/nextjs-auth0#293]
### Describe the problem

When using this SDK in a fairly vanilla implementation, the login route never resolves. i.e. Login doesn't redirect to the Auth0 login page.

### What was the expected behavior?

Login should redirect to the Auth0 login page.

### Reproduction

Clone https://github.com/willfalconer/next-auth0-test

- Step 1. Configure a standard web application in Auth0 dashboard, and populate .env.local with relevant values (client ID, client secret etc)
- Step 2. npm run dev
- Step 3. load http://localhost:3000/ and click the login link

### Environment

- **Version of this library used:** 1.0
- **Node:** 14.10.0
- **OS:** Mac OSX 11.2.1

**Comment by adamjmcgrath** [comment]
Hi @willfalconer 

I just cloned https://github.com/willfalconer/next-auth0-test and used my own `.env.local` and was able to successfully login (running Node 14)

Can you share your `.env.local`? (without the values for the secrets)

**Comment by willfalconer** [comment]
Sure, see below:

```
AUTH0_SECRET='[redacted]'
AUTH0_BASE_URL='http://localhost:3000'
AUTH0_ISSUER_BASE_URL='https://deckee.au.auth0.com'
AUTH0_CLIENT_ID='KPABj9frldREd4zgWBWQ6Bj36mkFsQYN'
AUTH0_CLIENT_SECRET='[redacted]'
AUTH0_ENABLE_TELEMETRY='false'
```

FYI: I tried with and without double quotes, single quotes and the telemetry env var. I have checked multiple times that the settings are correct in the Auth0 dashboard, even going so far as to create a new web application just for this reproduction. I have followed the example for using `initAuth0` to directly set the parameters (and then using instance handlers). Each time I get the same outcome.

**Comment by adamjmcgrath** [comment]
Aha - I'm able to reproduce your issue with Node `v14.10.0` and fix it using Node `v14.10.1` - can you try upgrading your Node version. I'll see if I can find out what the problem with `14.10.0` is

**Comment by adamjmcgrath** [comment]
Looks like `14.10.0` had an issue with Async Generators https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.10.1

@willfalconer Feel free to ping me to reopen if your issue isn't solved by upgrading your version of Node

**Comment by willfalconer** [comment]
Thanks for your help @adamjmcgrath

This has resolved my issue.
