### ISSUE TITLE
v1.0.0 seems to have left over code from 0.16.1

### ISSUE THREAD

**Issue by allanmc** [auth0/nextjs-auth0#299]
### Describe the problem

When building with v1.0.0, there seems to be a depedency missing:
```
ModuleNotFoundError: Module not found: Error: Can't resolve '@hapi/iron' in '/home/runner/work/sd-frontend/sd-frontend/client-app/node_modules/@auth0/nextjs-auth0/dist/session/cookie-store'
```

When inspecting the package, it seems like the `src/` folder has no dependencies for `@hapi/iron`. But `dist/` seems to have some old source code left from previous version, which does depend on `@hapi/iron`. E.g. `/dist/session/cookie-store/index.js`:
```
const iron_1 = tslib_1.__importDefault(require("@hapi/iron"));
```

Maybe `dist/` wasn't cleaned before building, or am I missing something?

**Comment by adamjmcgrath** [comment]
Hi @allanmc - yep, thanks for noticing that - I'll make sure it's removed on the next release.

I can't reproduce your `ModuleNotFoundError` error though - are you directly trying to import something from the dist folder? You should only need to import from `@auth0/nextjs-auth0`

**Comment by allanmc** [comment]
@adamjmcgrath Ahh yes, good catch! We actually do have some code that directly import some of the outdated code, we'll have to get rid of that 😃 Thanks!

**Comment by adamjmcgrath** [comment]
great! Thanks for reporting @allanmc - #300 will make sure we don't publish obsolete files on the next release
