### ISSUE TITLE
Support Subdomains in cookies

### ISSUE THREAD

**Issue by Flaque** [auth0/nextjs-auth0#30]
### Describe the problem you'd like to have solved

I have a Nextjs site like `foobar.com` and I'd like to send a request to an API I have running on `api.foobar.com`. 

From the `foobar.com` site, I could send something like this:

```js
fetch(`${apiDomain()}/my-route`, {
  credentials: "include"
})
```

And then I'd see the session cookie:
```
req.headers.cookie // ...a0:session="my-session-cookie"
```

This works on `localhost` and in development. But in production, it doesn't. 

### Describe the ideal solution

I _believe_ that's because there's no `domain` setting set on the cookie, which if omitted, defaults to the host of the current document URL, _not including subdomains._

So to correct this, could we be able to set the `domain` cookie? 

## Alternatives and current work-arounds

I could just proxy this from an `api` route, but it's quite a pain with a graphql api, which is what I'm using.

**Comment by sandrinodimattia** [comment]
This is now supported using the new `cookieDomain` setting:

```js
cookieDomain: '.foobar.com'
```

> Note: Be careful with this setting. By adding the `.` to your domain the cookie will be available to *all* of your subdomains. To restrict the cookie to specific subdomains read this: https://stackoverflow.com/questions/18492576/share-cookie-between-subdomain-and-domain
