### ISSUE TITLE
withPageAuthRequired returnTo after login crashes if it is a Dynamic Route with special characters

### ISSUE THREAD

**Issue by JReinhold** [auth0/nextjs-auth0#308]
### Describe the problem

When wrapping a dynamic route page with `withPageAuthRequired`, and that page has special characters in the slug, the returnTo will be wrong and crash - **but only during development**.

Example:

say we have a page:

```js
// /pages/[echo-string].js

import { useRouter } from "next/router";
import { withPageAuthRequired } from "@auth0/nextjs-auth0/dist/frontend";

export default withPageAuthRequired(function Echo() {
  const router = useRouter();
  return <div>hello {router.query["echo-string"]}</div>;
});
```

and we visit it at `localhost:3000/world`.
We "correctly" get redirected to Auth0 login. but when we return, we are sent back to `localhost:3000/[echo-string]` and NOT `localhost:3000/world` as expected.

The error given is:
> Unhandled Runtime Error
Error: The provided `href` (/[echo-string]?) value is missing query values (echo-string) to be interpolated properly. Read more: https://err.sh/vercel/next.js/href-interpolation-failed

If we rename and refactor the page to be `[echoString].js` the problem goes away. So I assume it has something to do with the hyphen in the slug.

### What was the expected behavior?

It correctly redirects to login and returns back to the original page with the correct slug.

### Reproduction

1. Create a simple Next.js app with `npx create-next-app`.
2. Follow Auth0 setup instructions
3. Create page as described above
4. Visit [`http://localhost:3000/world`](http://localhost:3000/world) directly
5. Log in
6. See that you are taken back to `http://localhost:3000/[echo-string]` with an error report

![image](https://user-images.githubusercontent.com/5678122/108507994-6db59680-72bb-11eb-8783-00b465f76d6e.png)

### Environment

- Node.js: v15.5.1
- Yarn: v1.22.10
- Next.js: 10.0.7
- @auth0/nextjs-auth0: 1.0.0

### Further details

1. It only happens during development. production builds work fine
2. Initially I considered if this was an upstream bug in Next.js, but I'm unsure. If I remove the `withPageAuthRequired` and log `router.asPath` directly in the component, it first logs `/[echo-string]` followed by `/world`. In production it logs `/world` twice.
3. HOWEVER, when using the working `/[echoString].js` pattern, `router.asPath` also firsts logs `/[echoString]`, but this time everything works.
4. The browser network tools show that we are initially redirected to `http://localhost:3000/api/auth/login?returnTo=/[echo-string]` and not `http://localhost:3000/api/auth/login?returnTo=/world`.

**Comment by adamjmcgrath** [comment]
Hi @JReinhold - thanks for raising this

I can't reproduce this using the [basic-example](https://github.com/auth0/nextjs-auth0/tree/main/examples/basic-example) and adding the `/pages/[echo-string].js` page to the app, then visiting http://localhost:3000/world directly. (running Next.js: 10.0.7)

Would you be able to share a minimal reproduction app?

**Comment by JReinhold** [comment]
That is peculiar.. I've pushed a reproduction here: https://github.com/JReinhold/nextjs-auth0-308-reproduction

To iterate, the environment that this is failing for me:
- MacOS 11.1 Big Sur
- Node.js: v15.5.1
- Yarn: v1.22.10
- Next.js: 10.0.7
- @auth0/nextjs-auth0: 1.0.0
- Barebone Auth0 setup following the guide in this repo + Passwordless setup

The steps I take to reproduce are:
1. Add Auth0 environment variables
2. Run `yarn install`
3. Run `yarn dev`
4. Open `http://localhost:3000/world`
5. Log in
6. Get error
7. Log out at `http://localhost:3000/api/auth/logout`
8. Open `http://localhost:3000/works/world`
9. Log in
10. Everything is working

I've added some helpful logs, I recommend checking "Persist logs" in the dev tools.

**Comment by adamjmcgrath** [comment]
Thanks for sharing that @JReinhold - unfortunately, I'm still not able to reproduce your error with a matching setup to what you've described.

After login I get redirected to `http://localhost:3000/world` - I've tested this in FF, Safari and Chrome

Do you perhaps have a Chrome extension installed that might be effecting the result?

> If we rename and refactor the page to be [echoString].js the problem goes away. So I assume it has something to do with the hyphen in the slug.

Is this also the case when you have `/pages/[echoString].js`? I see in your example that it's in `/pages/works/[echoString].js`

**Comment by GeeWee** [comment]
I get the same error, but only intermittently given the repo above.
However I cannot reproduce it in private mode in firefox or on a new chrome profile without addons. However even using the same firefox instance and clearing data in the cache in-between I've only managed to provoke it once (first time I tried, and after 10 more tries or so.)

![image](https://user-images.githubusercontent.com/6381792/108735892-f4bb7680-7528-11eb-965f-9c431c083e43.png)

**Comment by adamjmcgrath** [comment]
> However I cannot reproduce it in private mode in firefox or on a new chrome profile without addons. 

Thanks @GeeWee! If you disable all your Chrome addons then re-enable them one by one, you might be able to identify which one (if any) is causing the issue?

**Comment by GeeWee** [comment]
(I managed to reproduce it in firefox, I only tried a clean chroome profile)
That was my original plan - I tried disabling ublock origin, Privacy badger and the usual suspects, but then after doing that I was unable to reproduce the issue again, even after re-enabling them, and I can no longer reproduce the issue reliably enough to figure out what's going on.

**Comment by adamjmcgrath** [comment]
@GeeWee @JReinhold - still not able to reproduce it in FF or Chrome.

If you have any other suggestions that might help me reproduce this, let me know - thanks

**Comment by adamjmcgrath** [comment]
Am going to close this due to inactivity - if you run into this again or can provide me with any steps to reproduce, ping me and I'll reopen this issue
