### ISSUE TITLE
Dynamically change the audience on getAccessToken

### ISSUE THREAD

**Issue by werevamp** [auth0/nextjs-auth0#315]
### Describe the problem you'd like to have solved

I'm switching over from auth0-react, so I'm a bit new to auth0-next.  When using the **getAccessToken** function I need to pass audience, but it doesn't seem like I can add this dynamically like in auth0-react. It appears that we are stuck with the single audience that was provided after the user logs in.

In auth0 react there is this function **getAccessTokenSilently** where I can pass the audience dynamically like:

```javascript
const accessToken = await getAccessTokenSilently({
  audience: getAudience(), //dynamically add audience depending on which external API you are accessing
  scope,
})
```

### Describe the ideal solution

Ideally I would like the getAccessToken function to work like this:
```javascript
  const { accessToken } = await getAccessToken(req, res, {
    audience: getAudience(),
    scopes: ['read:products']
  })
```

Or, if the audience isn't passed use the default audience provided from login.

**Comment by adamjmcgrath** [comment]
Hi @werevamp - currently the SDK only supports a single access token for a single audience. 

There's no reason why you couldn't store multiple ATs for multiple audiences, you just wouldn't use the `getAccessToken` - instead you'd store and access ATs on the session directly, eg (untested).

```js
// api/auth/[...auth0].js
import { handleAuth, handleCallback, handleLogin, getSession } from '@nextjs-auth0';

export deault handleAuth({
  async login(req, res) {
    await handleLogin({
      authorizationParams: {
        audience: getAudience()
      }
    })
  },
  async callback(req, res) {
    await handleCallback({
      async afterCallback(req, res, session) {
        const existingSession = getSession(req, res);
        const { accessToken } = session;
        return {
          ...session,
          audiences: { ...existingSession?.audiences, [getAudience()]: accessToken }
        }
      }
    })
  }
})

// lib/get-access-token.js
import { getSession } from '@nextjs-auth0';

export default (req, res, audience) => {
  const session = await getSession(req, res);
  return session?.audiences?[audience]; 
}
```

We currently don't have this feature in the roadmap, but this si always under review.

Closing for now, feel free to ping me if you want me to reopen this to discuss.
