### ISSUE TITLE
Refetch additional user informations from the backend

### ISSUE THREAD

**Issue by NuriddinK** [auth0/nextjs-auth0#316]
### Describe the problem you'd like to have solved

I am passing a new user attributes from Auth0 Rules to `/userinfo`, ex. "acceptedAgreement: false". Whenever the user comply to accept the agreement, I am updating the `app_metadata` from the backend using the management API. So far so good, the problem is that even by using **handleProfile** `refetch`, the session does not return the updated information.

### Describe the ideal solution

It'd be very easy if I could refetch the newly updated data OR call a function to apply the change to my session and `/api/auth/me` endpoint. This will ensure additional informations added by rules are also up-to-date when changed, or in this common use-case the user will not be prompted to accept the agreement again while navigating the web app.

## Alternatives and current work-arounds

An alternative work-around would be to call the Management API on every page change, but this seems a bit overkill.

Another way to do that, unsure if it's recommended, would be to directly update the session manually. The problem is that **this will not reflect updates if it's modified from the Auth0 Dashboard** (modifications from the Auth0 Dashboard could be useful for setting custom plans to customers for example), see below.

```
import { getSession } from "@auth0/nextjs-auth0";

const { user } = await getSession(req, res);
user[process.env.AUTH0_NAMESPACE + "acceptedAgreement"] = true;
...
```
### Additional information, if any

Signing out & signing in is too expensive for users, so I'd like to avoid that option.

**Comment by NuriddinK** [comment]
Additional information, I noticed that if I use the `handleLogin` function to silently login, it does update the data accordingly. The problem remains, the desired behaviour would be to update the current user informations without reloading or refreshing the page.

```
await handleLogin(req, res, {
    authorizationParams: {
        prompt: 'none'
    }
});
```

**Comment by adamjmcgrath** [comment]
Hi @NriddinK - Thanks for raising this.

New fields from `/userinfo` should be persisted in the session when you do `refetch: true` in `handleProfile` - we have a [test here that verifies it](https://github.com/auth0/nextjs-auth0/blob/main/tests/handlers/profile.test.ts#L55-L65)

Can you confirm that the field is being returned in the profile handler? You can also [put some debugging here](https://github.com/auth0/nextjs-auth0/blob/main/src/handlers/profile.ts#L68) to verify that it's being applied to the session correctly

**Comment by NuriddinK** [comment]
Hi @adamjmcgrath, 

I verified the profile handler response, unfortunately additional informations arrive unchanged.

I created a repository to reproduce the issue, the steps are in the README.md, see [NextJS/Auth0 issue 316].(https://github.com/NuriddinK/nextjs-auth0-issue-316)

**Comment by adamjmcgrath** [comment]
> I verified the profile handler response, unfortunately additional informations arrive unchanged.

Thanks @NuriddinK - can you confirm that the additional information was in the `/userinfo` [response](https://github.com/auth0/nextjs-auth0/blob/main/src/handlers/profile.ts#L62), it just didn't make it into the `/api/auth/profile` response?

**Comment by NuriddinK** [comment]
If you're already logged in, additional informations are passed to `/userinfo` but they are not up to date if you made any change directly from the auth0 dashboard, I believe this is because `/api/auth/me` is persistent, that is why I'm trying to call `/api/user/profile-refetch`. `refetch` only works for root attributes such as "email", "name", etc... not for additional informations passed through rules, they are indeed not up-to-date to the change made through the auth0 user dashboard.

**Comment by adamjmcgrath** [comment]
> if you're already logged in, additional informations are passed to /userinfo but they are not up-to-date

Thanks @NuriddinK - so just to confirm, you're not seeing the data in the `/userinfo` response you are expecting? I'm just trying to understand if this is an issue with the SDK or your tenant.

**Comment by NuriddinK** [comment]
Yes @adamjmcgrath the `/userinfo` has the correct object keys, but outdated values. to answer your question, I am indeed not seeing the `userinfo` response as I am expecting.

Just to be clear, refetch does not work on additional data passed through Auth0 [Rules](https://auth0.com/docs/rules/metadata).

**Comment by adamjmcgrath** [comment]
Thanks for clarifying @NuriddinK - so this isn't a problem with the SDK. If `/userinfo` doesn't have the response you're expecting, then you can't expect `handleProfile` to.

Can you raise this with https://community.auth0.com/ - and they should be able to help you debug why `/userinfo` and your Rule does not show you the data you are expecting.

If this still doesn't work after getting the response from `/userinfo` correctly, then feel free to open another issue or ping me and I'll reopen this
