### ISSUE TITLE
http request error ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by tcash11** [auth0/nextjs-auth0#319]
### Description

When logging out and then back in with a separate account we are receiving a `connect ECONNREFUSED 127.0.0.1:443` error response on the /api/auth/callback route. This is using the basic setup with the dynamic /api/auth/[...auth0].js endpoint with
```
import { handleAuth } from '@auth0/nextjs-auth0'
export default handleAuth()
```
contents.

Some research on this specific error seems to indicate some similar issues have been fixed in the `got` and `agent-base` packages but that some dependencies are not yet using the patched versions https://github.com/auth0/node-auth0/issues/490

### Reproduction

1. In a basic nextjs app, and vercel dev to run locally, and using the basic setup instructions outlined in nextjs-auth0, startup your application at http://localhost:3000
2. Login successfully with a valid account
3. Logout
4. Try to login with a separate valid account

Expected result: Successful login

Actual result: Login on Auth0 runs successfully, but when it hits the callback on the 
```http://localhost:3000/api/auth/calback?code=####&state=#####  ```
and produces a connect ECONNREFUSED 127.0.0.1:443 error response.

Serverside Error:  
```BadRequestError: connect ECONNREFUSED 127.0.0.1:443
    at Object.<anonymous> ([my-project-path]\node_modules\@auth0\nextjs-auth0\dist\auth0-session\handlers\callback.js:30:19)
    at Generator.throw (<anonymous>)
    at rejected ([my-project-path]\node_modules\@auth0\nextjs-auth0\node_modules\tslib\tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
Workaround is to simply restart your local server and then the login will work again with any valid account.

### Environment

- **Version of this library used:**:  1.1.0
- **Version of the platform or framework used, if applicable:**: NextJS Version 10.0.7  Vercel CLI Version 21.3.1
- **Other relevant versions (language, server software, OS, browser):** Node 14.15.5
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hi @tcash11 - thanks for raising this

> Some research on this specific error seems to indicate some similar issues have been fixed in the got and agent-base packages but that some dependencies are not yet using the patched versions auth0/node-auth0#490

The [issue you describe](https://github.com/sindresorhus/got/issues/951) is with `agent-base` (< 5) (via `https-proxy-agent`) - `next` uses it, but appears to use a version that is not affected by this issue, are you using it directly in your app? (try `npm ls agent-base`)

```
$ npm ls agent-base
@auth0/nextjs-auth0@1.1.0 /Users/adammcgrath/dev/nextjs-auth0
└─┬ next@10.0.5
  └─┬ @ampproject/toolbox-optimizer@2.7.1-alpha.0
    └─┬ https-proxy-agent@5.0.0
      └── agent-base@6.0.2
```

Also see https://github.com/auth0/express-openid-connect/issues/158#issuecomment-726341318 and check you don;t have any other versions of `https-proxy-agent` running locally

**Comment by tcash11** [comment]
Thank you for the help @adamjmcgrath !
> The [issue you describe](https://github.com/sindresorhus/got/issues/951) is with `agent-base` (< 5) (via `https-proxy-agent`) - `next` includes `agent-base`, but appears to use a version that is not affected by this issue, are you using it directly in your app? (try `npm ls agent-base`)
> 
> ```
Following the above advice led us to to finding some other packages we had that were using outdated `agent-base` dependencies. We were able to remove an unneeded package and the other we used a resolution in our package.json to get it up to the latest (with some thorough testing afterwards to make sure it still worked with the patched dep)
```
  "resolutions":{
    "offending-package/**/agent-base": "6.0.2"
  },
```
Thanks again for the help, I would say you can close this issue and hopefully anyone else that runs into this problem can use `npm ls agent-base` to track down other packages in their projects that may be causing this issue.

**Comment by adamjmcgrath** [comment]
Great - glad you got it fixed @tcash11

**Comment by synoptase** [comment]
Leaving this for eventual future googlers, issue also appears with the `auth0@2.33.0` version. Adding the following patch in the `package.json` fixes the issue:

```
"resolutions": {
    "superagent-proxy": "^2.1.0"
  }
```
