### ISSUE TITLE
Login /api/login breaks with 502: BAD_GATEWAY NO_STATUS_CODE_FROM_FUNCTION when 'eval-source-map' used

### ISSUE THREAD

**Issue by gschema** [auth0/nextjs-auth0#32]
### Description

Login into the app breaks when deployed to https://zeit.co app when `'eval-source-map'` used in `next.config.js` config.

### Reproduction

1. Set `next.cofing.js` as: 
```
// ...
const isProd = process.env.NODE_ENV === 'production';

const nextConfig = {
  webpack: (config, options) => {
    config.devtool = 'eval-source-map';
    return config;
  },
 // ...
};
// ...
module.exports = withPlugins(
   // ...,
  nextConfig
);
```

2. run `now` in local to deploy to your zeit deployment

3. once deployment done try to login into your app:
`https://{{your-app-name}}.{{your-account-name}}.now.sh/api/login`

4. see following screen:
![image](https://user-images.githubusercontent.com/287802/67644330-6f43a880-f96c-11e9-9042-3dcddc2104b8.png)

**Info below is for search engines (so people can find it):**
```
502: BAD_GATEWAY
Code: NO_STATUS_CODE_FROM_FUNCTION
ID: 
```

5. In deployment logs error says something along these lines:
```
2019-10-28T00:14:06.548Z	undefined	ERROR	Uncaught Exception	{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'next/dist/next-server/server/api-utils'",
  "stack": [
    "Runtime.ImportModuleError: Error: Cannot find module 'next/dist/next-server/server/api-utils'",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
    "    at startup (internal/bootstrap/node.js:283:19)"
  ]
}
Duration: 140.03 ms  Billed Duration: 200 ms  Memory Size: 3008 MB  Max Memory Used: 28 MB	
Unknown application error occurred
Runtime.ImportModuleError
```

### Environment

- https://zeit.co
- `auth0/nextjs-auth0`: **`0.4.0` and `0.5.0`**
- `next`: **`^9.1.1`**

**Note:**
This is not per se problem with this library. Wanted to share this in case anyone else stumbles upon this problem. My first thought was it is this library being unstable hence thought others might think that too.

### Solution

This solution worked for me:

```
// ...
const isProd = process.env.NODE_ENV === 'production';

const nextConfig = {
  webpack: (config, options) => {
    config.devtool = isProd ? config.devtool : 'eval-source-map';
    return config;
  },
  ...
};
// ...
module.exports = withPlugins(
   // ...,
  nextConfig
);
```

**Comment by qtLOLI** [comment]
I have a similari issue, code breaks at 'api/login' as you, but in logs i have:

`errorType Runtime.UnhandledPromiseRejection
errorMessage ReferenceError: err is not defined
reason { errorType: 'ReferenceError',
  errorMessage: 'err is not defined',
  stack:
   [ 'ReferenceError: err is not defined',
     '    at Server.module.exports.14pD.__webpack_exports__.default (/var/task/.next/serverless/pages/api/login.js:135:112)',
     '    at process._tickCallback (internal/process/next_tick.js:68:7)' ] }
promise {}
stack [ 'Runtime.UnhandledPromiseRejection: ReferenceError: err is not defined',
  '    at process.on (/var/runtime/index.js:37:15)',
  '    at process.emit (events.js:203:15)',
  '    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)',
  '    at process._tickCallback (internal/process/next_tick.js:69:34)' ]
`

I tried to catch all promises i have found but nothing

**Comment by ian-speers** [comment]
Thank you for contributing your findings back to the community 🙇

**Comment by cyrus-za** [comment]
Running into this same issue here: https://github.com/vercel/next.js/issues/13736
