### ISSUE TITLE
Setup of custom domain results in "unexpected iss value"

### ISSUE THREAD

**Issue by dohomi** [auth0/nextjs-auth0#320]
Hello
it would be great if there is some information about custom domains with this plugin. I set up the Universal Login to use the custom domain and adjusted the `AUTH0_ISSUER_BASE_URL`. I still receive an error of:
```
BadRequestError: unexpected iss value, expected https://<CUSTOM_DOMAIN>/, got: https://<TENANT>.eu.auth0.com/
```
I am using a `AUTH0_AUDIENCE` to receive accessToken for a custom API. I am not sure which sections I need to follow. Currently I was looking to update https://auth0.com/docs/custom-domains/configure-features-to-use-custom-domains#universal-login But this didn't fix it. Does `/api/auth/callback` needs to be overwritten? If yes it would be great if an example could be appended to the README

**Comment by adamjmcgrath** [comment]
Hi @dohomi - thanks for raising this

I would expect the only change required to your Next.js application would be to update `AUTH0_ISSUER_BASE_URL`.

Are you getting that `BadRequestError` when your Next.js app verifies you ID Token in the callback, or when your API verifies your Access Token when you try to access it?

**Comment by dohomi** [comment]
@adamjmcgrath I only changed `AUTH0_ISSUER_BASE_URL` and nothing else. 
I receive the error inside `handleCallback` and for testing purpose I removed `AUTH0_AUDIENCE` to see if that might be the reason. 
From the login flow:
```
domain => authenticated page => custom auth0 domain => redirect authenticated page !!ERROR
```
It seems that inside of nextjs-auth0 the `iss` is not correctly determined with the custom domain. I use Universal Login and added the 4 lines of code to enable custom domains.

**Comment by adamjmcgrath** [comment]
> `expected https://<CUSTOM_DOMAIN>/, got: https://<TENANT>.eu.auth0.com/`

From the error it looks like the SDK is expecting ths `iss` claim to be `https://<CUSTOM_DOMAIN>/`, but the iss claim on your ID Token is `https://<TENANT>.eu.auth0.com/`

I would also expect the iss claim to be `https://<CUSTOM_DOMAIN>/`, so I'm a little confused. If you login to `https://<CUSTOM_DOMAIN>/login` you should be issued an ID Token with an `iss` claim of `https://<CUSTOM_DOMAIN>/`

**Comment by dohomi** [comment]
@adamjmcgrath This is the code I attached to the Universal login:
```js
//https://auth0.com/docs/custom-domains/configure-features-to-use-custom-domains#universal-login
  configurationBaseUrl: config.clientConfigurationBaseUrl,
      overrides: {
        __tenant: config.auth0Tenant,  
        __token_issuer: config.authorizationServer.issuer 
    },
```
I additionally made sure that the login custom domain is verified. So far I thought thats all I need to do to make it work. Where would I need to adjust the Auth0 settings that the `iss` claim is set to my domain?

**Comment by adamjmcgrath** [comment]
> Where would I need to adjust the Auth0 settings that the iss claim is set to my domain?

@dohomi - good question! let me investigate

Can you share your tenant domain, client id and custom domain?

**Comment by dohomi** [comment]
@adamjmcgrath sure:
```
tenant domain: kmu.eu.auth0.com
client id: jpHWnJpJngaJRzJPUyUNqfQnSsRuaokl
custom domain: login.chredit.ch
```

**Comment by dohomi** [comment]
@adamjmcgrath this are the values logged out from the Universal login:
```js
auth0Domain: "login.chredit.ch"
auth0Tenant: "kmu"
authorizationServer: {
issuer: "https://login.chredit.ch/"
url: "https://login.chredit.ch"
}
```

**Comment by adamjmcgrath** [comment]
Hey @dohomi - I've just successfully logged in to your tenant using your client id and custom domain on the [basic example](https://github.com/auth0/nextjs-auth0/tree/main/examples/basic-example) app (I'm using form post implicit so I didn't need a client secret)

The ID Token I got issued had the cusom domain as the `iss`

![image](https://user-images.githubusercontent.com/1299658/109800610-5197ea80-7c15-11eb-9320-62eeedf7620a.png)

I wonder if you're getting the issue because you have a stale session on Auth0, could you make sure you've logged out, then log back in again?

**Comment by adamjmcgrath** [comment]
Aha - but then I tried signing in with Google and got the `iss` mismatch.

You probably need to follow the instructions in https://auth0.com/docs/custom-domains/configure-features-to-use-custom-domains#configure-social-identity-providers

**Comment by dohomi** [comment]
@adamjmcgrath true a new registration with email works. 
Google does not work there I receive `iss` mismatch. But I already attached `https://login.chredit.ch/api/auth/callback` to the allowed callback URLs yesterday, same as the origin URL. Not sure why that didn't work so far.

**Comment by adamjmcgrath** [comment]
> EDIT: Ok maybe because I am using the Universal Login its not working.

@dohomi - ok thanks, yep - it could be an issue with using the Auth0 developer keys and classic Universal Login Page

Let me know if you run into any other issues or you're happy for me to close this

**Comment by dohomi** [comment]
@adamjmcgrath all good for now, the issue did not belong in this package thanks for assisting me.

**Comment by RyanKoech** [comment]
As silly as it is, I missed a `/` at the end of the Issuer Url.

**Comment by sourabpramanik** [comment]
> As silly as it is, I missed a `/` at the end of the Issuer Url. Hope this helps!

Thanks @RyanKoech
