### ISSUE TITLE
Nextjs Role Based Protected Routes

### ISSUE THREAD

**Issue by jonparkdev** [auth0/nextjs-auth0#321]
### Describe the problem you'd like to have solved

It there a solution to create role based access controlled routes?  Since roles aren't a feature of "Regular Web Applications" would I also need to create an API in the Auth0 dashboard to work concurrently with the Regular Web App?

This auth0 document explains what I am trying to achieve:
https://auth0.com/docs/authorization/sample-use-cases-role-based-access-control?_ga=2.60164527.322087514.1614695020-1290724891.1612412079

### Describe the ideal solution

I would assume restricting access to a page based on an authenticated user's role would occur in getServerSideProps. 

## Alternatives and current work-arounds

https://github.com/auth0/nextjs-auth0/issues/110 suggests a solution to creating a rule to add roles to IdTokens.

### Additional information, if any

I made a post on the auth0  community with a little more detail:

https://community.auth0.com/t/nextjs-role-based-protected-routes-not-for-apis/58758

**Comment by adamjmcgrath** [comment]
Hi @jonparkdev - thanks for raising this

It's perfectly valid to [add user defined roles to ID Tokens](https://auth0.com/docs/authorization/sample-use-cases-rules-with-authorization#add-user-roles-to-tokens). Once you do this you can check for the role in your page, eg:

```js
improt { getSession } from '@auth0/nextjs-auth0';

// pages/admin.js
export default function Admin({ error }) => error ? <div>error<div> : <div>Admin Section</div>;

export getServerSideProps = ({ req, res }) => {
  const session = getSession(req, res);
  if (!session?.user['http://your-namespace/roles'].includes('admin')) {
    return { props: { error: 'Forbidden' } }
  }
}
```

**Comment by jonparkdev** [comment]
Great! Makes sense, thanks for the help.
