### ISSUE TITLE
show example of redirecting to original url after login?

### ISSUE THREAD

**Issue by leojkwan** [auth0/nextjs-auth0#328]
How do I redirect signed in visitors back to their last visited page? Ex. user was on `/shop/shoe1` -> "/api/auth/login" -> (sign in) -> /auth/callback -> `/shop/shoe1`?

I don't know how to dynamically override the `returnTo` which defaults to baseURL. Thanks!

**Comment by adamjmcgrath** [comment]
Hi @leojkwan - `withPageAuthRequired` will do this for you. 

But if you want to do this yourself, have a look at the code for [frontend](https://github.com/auth0/nextjs-auth0/blob/main/src/frontend/with-page-auth-required.tsx#L87) and [server side](https://github.com/auth0/nextjs-auth0/blob/main/src/helpers/with-page-auth-required.ts#L109)

**Comment by leojkwan** [comment]
Thanks for pointing me in the right direction!
