### ISSUE TITLE
Authenticate for entire app on staging server? Even ideas how?

### ISSUE THREAD

**Issue by mikestopcontinues** [auth0/nextjs-auth0#329]
### Describe the problem you'd like to have solved

I'd like to limit access to my entire NextJS app on a staging server. The app has too many routes for it to make sense to conditionally wrap every single page, so I've been trying to do it from within my App component. 

Mostly, I've tried permutations of the logic found within the `withPageAuthRequired` component. My most successful attempt was to convert it into a hook (`useAuth`) and a component that uses it to block content (`PageAuth`). The trouble is, when the redirect is triggered, it changes the url to `/api/auth/login`, but it doesn't actually cause navigation.

I also tried wrapping AppProps.Component with `withPageAuthRequired` within the App component, but, as you know, you can't use that function client side. I'm guessing this is because it breaks in exactly the way my `PageAuth` component breaks.

I also looked into `auth0-react`, but the problem is the same. I've got to wrap every page with the HOC. Also, it makes a mess of the limited-scope auth I need in the production version of my app. 

### Describe the ideal solution

Ideally, I'd simply like a hook (like `useAuth` above), that I can stick App, some page component, or a sub-component. The return should be `{user, error, isLoading, checkSession}` so that I can block subcomponents from loading. But unlike `useUser`, it should actually handle the redirect logic.

That said, I could live with updated HOCs. And I wouldn't even mind an App-only hook or HOC for this particular case. I just don't want to worry about forgetting I have to conditionally wrap every route I make on this app and others to handle staging.

## Alternatives and current work-arounds

All that said, I'd happily settle for some advice on how to get it working. I've read through your codebase quite a bit since I started working with Auth0, so feel free to direct me to whatever I'm missing.

## Other info...

I'm using the beta, node 14.x, and the most-recent versions of everything else.

Thanks!

**Comment by adamjmcgrath** [comment]
Hi @mikestopcontinues 

You can wrap the whole application in `withPageAuthRequired` to achieve this, eg:

```js
// pages/_app.js
import React from 'react';
import { UserProvider, withPageAuthRequired } from '@auth0/nextjs-auth0';

export default function App({ Component, pageProps }) {
  const AuthRequiredComponent = withPageAuthRequired(Component);
  return (
    <UserProvider>
      <AuthRequiredComponent {...pageProps} />
    </UserProvider>
  );
}
```

> I'm using the beta

The SDK is out of Beta now - recommend you use the [latest version](https://github.com/auth0/nextjs-auth0/releases)

**Comment by mikestopcontinues** [comment]
Hi @adamjmcgrath, thanks for getting back to me. I tried that solution over the last couple of days, and again just now to make sure I wasn't imagining things. It doesn't work, but it turns out it doesn't work because I'm using `initAuth0()`.

In order to make the library work with Vercel deployment, I need to handle three different cases:
 1. VERCEL_ENV === 'production' w/ production domain (www.example.com)
 2. VERCEL_ENV === 'preview' w/ branch deploy to custom domain (www.staging.example.com)
 3. VERCEL_ENV === 'preview' w/ VERCEL_URL domain (*.vercel.app)

I handle it with some conditional logic, where I set `initAuth0({baseURL})`. But the `withPageAuthRequired` that comes out of that function can't be called client-side, which is what happens inside `App`. Is it possible that func, and perhaps a few of the others, should actually be instantiated?

In any case, thank you, because realizing the problem is with `initAuth0` made me realize I can programmatically set `AUTH0_BASE_URL` in `next.config.js` and avoid it completely. Thanks again!

**Comment by mikestopcontinues** [comment]
Hey, I just want to add, in case anyone stumbles on this, setting `AUTH0_BASE_URL` in `next.config.js` works for client-side stuff, but I still had to use `initAuth0` in my api routes. I'm not exactly sure why, but even though I can access the env var in that location, the SDK seems to miss it. I'm guessing it has to do with Next using `webpack.DefinePlugin` to replace env vars.

Anyway, here's how you get it done...

```js
// /pages/api/auth/[...auth0].js

import {initAuth0} from '@auth0/nextjs-auth0';

const {handleAuth} = initAuth0({baseURL: process.env.AUTH0_BASE_URL});

export default handleAuth();
```

**Comment by adamjmcgrath** [comment]
Hey @mikestopcontinues - glad you got it sorted.

> I just want to add, in case anyone stumbles on this, setting AUTH0_BASE_URL in next.config.js works for client-side stuff, but I still had to use initAuth0 in my api routes.

This is probably because you can't mix `initAuth0` and the other named exports from the SDK in your server side code.

This is because `var auth0 = initAuth0()` creates an instance, which you should use for all server side code eg `auth0.getSession()`, if you were to use `import { getSession } from '@auth0/nextjs-auth0'` then `getSession` would create another instance and the 2 wouldn't share the same auth state.

It's stated in the docs at the [bottom of the config page](https://auth0.github.io/nextjs-auth0/modules/config.html), but I should make it throw an error when you try and use the 2 simultaneously.

**Comment by mikestopcontinues** [comment]
Hey! The only way I have it working is mixing. I'm importing `withPageAuthRequired` directly, while using `initAuth0()` for everything in the api. That's why I suspect at least `withPageAuthRequired` should be exported from `initAuth0` on both the client and the server, even if the others aren't. Or else it should only be directly exported like `useUser` and `UserProvider`.

But when I was having the error with the API, I was only using direct exports. I expected my env var would get picked up. But `handleAuth()` was throwing a `baseURL` error, even with my `next.config.js` as `module.exports = {env: {AUTH0_BASE_URL}}`.

**Comment by gmantri-bronzesmoke** [comment]
Hi @adamjmcgrath,

So I tried your solution and running into an error when I try to build the solution using `yarn build`. The error only occurs when I build the solution. If I run the solution in dev using `yarn dev`, everything works great.

Here's the code in my `_app.tsx` file:

```
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { UserProvider, withPageAuthRequired } from '@auth0/nextjs-auth0';

function MyApp({ Component, pageProps }: AppProps) {
  const AuthRequiredComponent = withPageAuthRequired(Component);
  return (
    <UserProvider>
      <AuthRequiredComponent {...pageProps} />
    </UserProvider>
  );
}

export default MyApp;
```

These are the errors I am getting:

```
Type error: No overload matches this call.
  Overload 1 of 2, '(opts?: WithPageAuthRequiredOptions<unknown> | undefined): PageRoute<unknown>', gave the following error.
    Argument of type 'NextComponentType<NextPageContext, any, {}>' is not assignable to parameter of type 'WithPageAuthRequiredOptions<unknown> | undefined'.
      Type 'ComponentClass<{}, any> & { getInitialProps?(context: NextPageContext): any; }' is not assignable to type 'WithPageAuthRequiredOptions<unknown> | undefined'.
        Type 'ComponentClass<{}, any> & { getInitialProps?(context: NextPageContext): any; }' has no properties in common with type 'WithPageAuthRequiredOptions<unknown>'.
  Overload 2 of 2, '(Component: ComponentType<WithPageAuthRequiredProps>, options?: WithPageAuthRequiredOptions | undefined): FC<...>', gave the following error.
    Argument of type 'NextComponentType<NextPageContext, any, {}>' is not assignable to parameter of type 'ComponentType<WithPageAuthRequiredProps>'.
      Type 'ComponentClass<{}, any> & { getInitialProps?(context: NextPageContext): any; }' is not assignable to type 'ComponentType<WithPageAuthRequiredProps>'.
        Type 'ComponentClass<{}, any> & { getInitialProps?(context: NextPageContext): any; }' is not assignable to type 'ComponentClass<WithPageAuthRequiredProps, any>'.
          Construct signature return types 'Component<{}, any, any>' and 'Component<WithPageAuthRequiredProps, any, any>' are incompatible.
            The types of 'props' are incompatible between these types.
              Type 'Readonly<{}> & Readonly<{ children?: ReactNode; }>' is not assignable to type 'Readonly<WithPageAuthRequiredProps> & Readonly<{ children?: ReactNode; }>'.
                Property 'user' is missing in type 'Readonly<{}> & Readonly<{ children?: ReactNode; }>' but required in type 'Readonly<WithPageAuthRequiredProps>'.
```

```
'AuthRequiredComponent' cannot be used as a JSX component.
  Its return type 'Promise<GetServerSidePropsResultWithSession<unknown>>' is not a valid JSX element.
    Type 'Promise<GetServerSidePropsResultWithSession<unknown>>' is missing the following properties from type 'ReactElement<any, any>': type, props, key
```

I am using `version 1.6.1` of `@auth0/nextjs-auth0` SDK.

Can you please help me with this?

Thanks

**Comment by adamjmcgrath** [comment]
@gmantri-bronzesmoke - try `const AuthRequiredComponent = withPageAuthRequired(() => <Component />);`
