### ISSUE TITLE
The cookieSecret setting is empty or null

### ISSUE THREAD

**Issue by phanssens1** [auth0/nextjs-auth0#33]
I'm getting the following error message when I try to log in to my app at https://<domain>.<user>.now.sh/api/login:
`2019-10-28T23:13:26.978Z	fc3be034-8264-4d6c-9b00-c00533c27576	ERROR	Uncaught Exception	{"errorType":"Error","errorMessage":"The cookieSecret setting is empty or null","stack":["Error: The cookieSecret setting is empty or null","    at new CookieSessionStoreSettings (/var/task/node_modules/@auth0/nextjs-auth0/dist/session/cookie-store/settings.js:7:19)","    at Object.createInstance [as default] (/var/task/node_modules/@auth0/nextjs-auth0/dist/instance.node.js:13:29)","    at initAuth0 (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:8:46)","    at Object.2NqA (/var/task/.next/serverless/pages/api/login.js:117:127)","    at __webpack_require__ (/var/task/.next/serverless/pages/api/login.js:23:31)","    at Module.A4T3 (/var/task/.next/serverless/pages/api/login.js:138:68)","    at __webpack_require__ (/var/task/.next/serverless/pages/api/login.js:23:31)","    at Server.module.exports.Gipt.__webpack_exports__.default (/var/task/.next/serverless/pages/api/login.js:167:26)","    at Server.emit (events.js:198:13)","    at parserOnIncoming (_http_server.js:677:12)"]}
Duration: 184.61 ms  Billed Duration: 200 ms  Memory Size: 3008 MB  Max Memory Used: 38 MB	
Unknown application error occurred
Error`

Here's a screenshot:
<img width="700" alt="Screen Shot 2019-10-29 at 10 21 46 am" src="https://user-images.githubusercontent.com/19516634/67725331-18a2a100-fa36-11e9-9b64-537a916859b6.png">

**Comment by karaggeorge** [comment]
You need to provide the `cookieSecret` value in this config: https://github.com/auth0/nextjs-auth0#runtime-configuration

It also needs to be at least 32 characters long

**Comment by phanssens1** [comment]
Thanks @karaggeorge - the env var was present.

I've subsequently found that using dotenv-webpack has resolved the issues: https://github.com/zeit/next.js/blob/master/examples/with-dotenv/next.config.js
