### ISSUE TITLE
frontend/with-page-auth-required does not check for expired tokens

### ISSUE THREAD

**Issue by gunar** [auth0/nextjs-auth0#332]
### Description

For some pages, I need to do  authentication on the client-side (CSR).

This hasn't been working for me:

```js
// pages/index.js
import { withPageAuthRequired } from "@auth0/nextjs-auth0";

export default withPageAuthRequired(function Index() {
  // …
}
```

If my client has an expired token, the mixing `withPageAuthRequired` will still let the component render:

```js
import { withPageAuthRequired } from "@auth0/nextjs-auth0";

export default withPageAuthRequired(function Index() {
  return <>rendered even though token is expired</>
})
```

If I have no tokens, I'm correctly forwarded to the login route. But if I have expired tokens, the component still tries to render (even though `props.user` is undefined).

### Environment

- **Version of this library used:** 1.1.0
- **Version of the platform or framework used, if applicable:** linux
- **Other relevant versions (language, server software, OS, browser):** brave browser
- **Other modules/plugins/libraries that might be involved:** next 10.0.4, react 17.0.1, react-dom 17.0.1

**Comment by gunar** [comment]
Guess one side-thing in all of this is that the `user` props is always empty (i.e. [this](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#protecting-a-client-side-rendered-csr-page) isn't working).

**Comment by adamjmcgrath** [comment]
Hi @gunar - thanks for raising this.

The CSR `withPageAuthRequired` uses the user state on the frontend to detect an active session.

The frontend checks the user's session on the server on page load and everytime you call `checkSession`, as soon as the session on the server has been checked it will go stale on the frontend, eg. it can expire or be invalidated some other way (eg another tab or frame could log the user out).

The frontend can't keep continusouly checking the server, as this would be too many requests, so the front end should assume that the `user` object is a best guess at the user's authentication state on the server, and should therefore handle the cases when it isn't correct. eg

```js
import { withPageAuthRequired } from "@auth0/nextjs-auth0";

export default withPageAuthRequired(function Index() {
  const { data, error } = useApi('/api/protected');

  if (error) {
    if (error.status === 401) {
      // the session has expired, redirect to logout
      window.location.assign('/api/auth/logout');
    }
  }

  return <>{data}</>
});
```

**Comment by gunar** [comment]
Yes. For future reference, this is my current work around:

```js
// pages/_app.js
export default function App({ Component, pageProps }) {
  return (
    <UserProvider>
      <CheckUser>
        <Component {...pageProps} />
      </CheckUser>
    </UserProvider>
  );
}

function CheckUser(props) {
  const { data, error } = useApi('/api/protected');
  if (error) {
    if (error.status === 401) {
      window.location.assign('/api/auth/logout');
    }
  }
  if (!data) return null;
  return props.children;
}
```

Obviously we don't want session validation to infect our every component. It should be centralized. The solution above provides that but it blocks the initial rendering of the page.

Could we add the `exp` field to the client-side user state/session? That should solve this problem.

**Comment by adamjmcgrath** [comment]
Thanks @gunar 

Since `CheckUser` will only run on page load, I'm not sure how this resolves the issue of the session going stale during the lifetime of the page, but if it solves your issue - great.

> Could we add the exp field to the client-side user state/session? That should solve this problem.

Unfortunately not, the library by default uses a rolling session, so `exp` would update everytime you use the an api route (or server generated page).

If you're using [absoluteDuration](https://auth0.github.io/nextjs-auth0/interfaces/config.sessionconfig.html#absoluteduration) only (say 24hrs). There's nothing stopping you adding that to the user property in your `afterCallback` eg:

```sh
# .env.local
AUTH0_SESSION_ABSOLUTE_DURATION=86400
AUTH0_SESSION_ROLLING=false
```

```js
// pages/api/auth/[...auth0].js
import { handleAuth, handleCallback } from '@auth0/nextjs-auth0';

const afterCallback = (req, res, session, state) => {
  session.user.expires = Date.now() + 86400*1000; // ms
  return session;
};

export handleAuth({
  async callback(req, res) {
    try {
      await handleCallback(req, res, { afterCallback });
    } catch (error) {
      res.status(error.status || 500).end(error.message);
    }
  }
});
```
