### ISSUE TITLE
Need way to emit custom logic after login, on logout.

### ISSUE THREAD

**Issue by dsbrianwebster** [auth0/nextjs-auth0#338]
LOVING the amazing work done here! 👏 👏 👏 👏 👏 👏 

We're moving over a couple Next + Auth0 projects where we were using @auth0/auth0-spa-js. 

One thing that is unclear is how we port over are any custom actions we call on signup, login and/or logout. 

Here is a real world example in case thats helpful...

We use Segment analytics one one of these projects and currently(with the auth0-spa-js approach) were able to do the following inside of initAuth0 in the `Auth0Context`

```tsx
const isLogin = window.location.search.includes('code=') && window.location.search.includes('state=');
// Firing Signed In Segement Event
if (isLogin) {
  window.analytics.identify(user.sub);
  window.analytics.track('Signed In', { username: user.name });
}
```

And we are able to handle logout events as follows...

```tsx
logout: (...p) => {
  window.analytics.track('Signed Out', { username: user.name  });
  window.analytics.reset();
  return auth0Client.logout(...p);
},
```

How would one approach this with nextjs-auth0?

**Comment by adamjmcgrath** [comment]
Thanks @dsbrianwebster!

Assuming you want to keep tracking this from the front end, I would do something like the following.

For login, I'd add a query param to my [returnTo](https://auth0.github.io/nextjs-auth0/interfaces/handlers_login.loginoptions.html#returnto) - then use that (instead of `code` and `state` to detect a new login)

```js
<a href="/api/auth/login?returnTo=/?loggedIn">login</a>
...
const isLogin = window.location.search.includes('loggedIn');
// Firing Signed In Segement Event
if (isLogin) {
  window.analytics.identify(user.sub);
  window.analytics.track('Signed In', { username: user.name });
}
```

Logout would be a bit easier, just trigger the analytics before the user visits the logout route

```js
const logout = () => {
  window.analytics.track('Signed Out', { username: user.name  });
  window.analytics.reset();
  window.location.assign('/api/auth/logout');
}

<a onClick={() => logout()}>logout</a>
```

**Comment by dsbrianwebster** [comment]
Awesome @adamjmcgrath! Many thanks 👏
