### ISSUE TITLE
Getting checks.state error with basic example

### ISSUE THREAD

**Issue by WorldOfMaze** [auth0/nextjs-auth0#340]
### Description

After installing `nextjs-auth0` and running the basic example, I am getting `checks.state argument is missing` on the screen as well as in the console.

### Reproduction

1. Copy `auth0/nextjs-auth0` to my local machine at `nextjs-auth0`
2. `cd ./nextjs-auth0`
3. `npm install`
4. `npm run install:basic`
5. `cd ./examples/basic-example`
6. Rename `.env.local.template` to `.env.local` and edit
7. `cd ../..` to return to the `nextjs-auth0` folder
8. `npm run start:basic`

### Expected Results

Application to run and show Login prompt on screen and no errors on console.

#### Browser

`checks.state argument is missing`

#### Console

```
> npm run dev --prefix=examples/basic-example

> nextjs-auth0-example@1.0.0 dev D:\Users\steve\Development\nextjs-auth0-main\examples\basic-example
> next

Loaded env from D:\Users\steve\Development\nextjs-auth0-main\examples\basic-example\.env.local
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled successfully
event - build page: /api/auth/[auth0]
wait  - compiling...
event - compiled successfully
BadRequestError: checks.state argument is missing
    at Object.<anonymous> (D:\Users\steve\Development\nextjs-auth0-main\examples\basic-example\.next\server\pages\api\auth\[auth0].js:594:19)
    at Generator.throw (<anonymous>)
    at rejected (D:\Users\steve\Development\nextjs-auth0-main\node_modules\tslib\tslib.js:115:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Environment

- **Version of this library used:**: `@auth0/nextjs-auth0 1.2.1`
- **Version of the platform or framework used, if applicable:** `next/env 10.0.7`  `node 14.16.0` `npm 6.14.11`
- **Other relevant versions (language, server software, OS, browser):** `Windows 10 Pro` `Brave 1.27.76 Chromium 89`

**Comment by adamjmcgrath** [comment]
Hi @WorldOfMaze - thanks for raising this

The basic example works for me and on our CI, so I suspect it's something to do with your environment.

`checks.state argument is missing` means that the cookie being dropped by `http://localhost:3000/api/auth/login` isn't being picked up by `http://localhost:3000/api/auth/callback`

Do you have any custom cookie config set in `.env.local` (eg `AUTH0_COOKIE_DOMAIN`, `AUTH0_COOKIE_PATH`, `AUTH0_COOKIE_SECURE` or `AUTH0_COOKIE_SAME_SITE`)?

Or, do you have any custom privacy settings set on your Brave browser (eg Shields)? Do you get the same result on Chrome?

**Comment by WorldOfMaze** [comment]
It seems to be something with the Brave Browser as everything works with Chrome.  And, after a rest, Brave is now working.  If this reoccurs, I will up date the issue but for now I am going to go ahead and close.

Thanks for your help.

**Comment by adamjmcgrath** [comment]
Good to hear @WorldOfMaze
