### ISSUE TITLE
Hhow to `getAccessToken` from inside React component

### ISSUE THREAD

**Issue by dsbrianwebster** [auth0/nextjs-auth0#348]
### Description
Documentation missing around how to `getAccessToken` from w/in React

We have scenarios where we need to call apis from React components and be able to pass our accessToken. Something like:

```tsx
  const { data, mutate, error } = useSWR(
    [GetUserFromExternalDBDocument],
    async () => await api.getUserFromExternalDB({ token: getAccessToken() ?? '' }),
    {
      revalidateOnFocus: false,
    },
  );
```
I see from the docs how to use `getAccessToken` from inside a nextjs api route, but not seeing how we access it from inside React. Presumedly there is something similar to how we would have with the older SPA package `await getTokenSilently()`?

**Comment by adamjmcgrath** [comment]
Hey @dsbrianwebster - thanks for raising this.

This SDK is designed to protect your APIs with an encrypted session - which is never available to the frontend. So accessing tokens from the frontend is not built into this library by default.

The preferred way to access an external api is to access your app's backend from the front end (protected with an encrypted session) and use the backend to access the external api, effectively using your next app's backend as a proxy. See this example for more info https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#access-an-external-api-from-an-api-route

If you really want to get access tokens on frontend and call those external APIs directly, you have 2 options:

1. Use the SPA model, where the SDK stores the tokens on the frontend. [auth0-react](https://github.com/auth0/auth0-react) has an [example Next.js app](https://github.com/auth0/auth0-react/tree/master/examples/nextjs-app) you can use as a reference
2. Create an API route that returns the access token to the frontend and call it before calling your external api

**Comment by dsbrianwebster** [comment]
Awesome infos @adamjmcgrath. Makes total sense!
