### ISSUE TITLE
Ability to access the user object on the server (or an example of how modify the user from the client)

### ISSUE THREAD

**Issue by awhit012** [auth0/nextjs-auth0#35]
Hi there, 
Thanks for your work on this. So far it's working great. 

However, I'm a bit lost on how to update the User with custom attributes. 

According to Auth0 docs, we are supposed to store our custom user data in user.user_metadata or user.app_metadata, but need access to the user object to do this. 

For example, I want to store a user's "level", ie "beginner" etc.

handleProfile and handleCallback both access the user data from a session, but don't return it, instead of sending the data back to the client. 

Please advise, how should we access user data server-side?

Alternatively, if we are only meant to access user data on the client, is there an example I could look at for setting and updating user_metadata?

Or, if accessing the user on the server-side is wanted, and needing a pull request, I'd be open to working on this issue.

**Comment by karaggeorge** [comment]
Hey @awhit012 

I believe you can do this to receive the user on the cookie:

```
import auth0 from '../../utils/auth0';

export default async (req, res) => {
  const { user } = await auth0.getSession(req);
  // do something with the user
}
```

I am not sure how you can edit the user with just the context of the cookie. You might need to access the [management API](https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id) with an appropriate token (probably saved in an env var).

Keep in mind, that this is the user object is currently generated and saved when the user logged in, so if you do make a change, it's not going to be reflected until they log out and log back in, until #38 is merged. If you want to fetch a fresh user object, you can take a look at how I fetched it there.

**Comment by Widcket** [comment]
Hi, you need to use a Rule to add the metadata to the ID Token. Then it will be available in the user profile.
Check out the following docs page to learn more: https://auth0.com/docs/rules/metadata
