### ISSUE TITLE
Session management

### ISSUE THREAD

**Issue by francescovenica** [auth0/nextjs-auth0#354]
Hello,

I'm not sure if this is a problem or not, I think that should be documented somewhere how does the session management work. In my mind when we use sessions we need to store them somewhere, in memory or in Redis or similar, using this library I'm able to restart my application or to have different replica (using docker) and still be logged in all the replica doing the login just one time. Is it possible to have some explanation on how the session management works?

### 
If the library manage the session under the hood without need to use store like Redis then we can close this issue, but if possible would be really helpful to document this somewhere.
###

### Describe the problem
If I login and then I restart the application I should lose my session and I should need to login again.

### What was the expected behavior?
If I restart my application I should be logged out, if I use different replica I should be asked to login if hitting a replica for the first time. 

### Environment
- 1.2.0
- NextJs 10.0.5

**Comment by adamjmcgrath** [comment]
Hi @francescovenica - thanks for raising this.

The session is stored in an encrypted cookie, so it will persist server restarts because it's stored on the client. This is mentioned on the README under https://github.com/auth0/nextjs-auth0#comparison-with-auth0-react

**Comment by francescovenica** [comment]
many thanks!
