### ISSUE TITLE
pageProps are empty when page is wrapped with withPageAuthRequired HOC

### ISSUE THREAD

**Issue by scottccoates** [auth0/nextjs-auth0#359]
### Describe the problem
`pageProps` supplied via `getServerSideProps` object is empty when using `withPageAuthRequired`. I know I must be missing something basic as this must be an extremely common use case.

### What was the expected behavior?
I expect that when I call `getServerSideProps`, I should receive the `pageProps` parameter in my functions `render` call. However, `pageProps` is an empty object `{}`. `getServerSideProps` is called, but when the component renders, its props are missing. 

### Reproduction

Step 1 - Create custom _app for UserProvider.
```jsx
function App({ Component, pageProps }) {
  return (
    <UserProvider>
      <Component {...pageProps} />
    </UserProvider>
  );
}
export default (AdminApp)
```

Step 2 - Create a simple page (e.g. `Manage`) wrapped in withPageAuthRequired HOC.

```jsx
function Manage(props) { // <-- props is missing `data` attribute.
  return (
      <span>hello {props.data.siteTitle}</span>
  );
}

export default withPageAuthRequired(Manage);
```

Step 3 - Provide `pageProps` to the custom app via `getServerSideProps`.
```jsx
export async function getServerSideProps(context) {
  const websiteData = await getWebsiteData();

  return {
    props: {data: websiteData}
  }
}
```

Notice that in step 2, the props is not actually supplied with data from step 3. This only happened when I added auth0 to next.js.

### Environment

**Version of this library used:**
`next@10.0.7`
`@auth0/nextjs-auth0@1.2.0`

**Comment by adamjmcgrath** [comment]
Hi @scottccoates - thanks for raising this

I'm not able to reproduce your issue using the basic example app and writing a component that is wrapped in `withAuthenticationRequired` and expects props `getServerSideProps -`https://github.com/auth0/nextjs-auth0/compare/issue-359

Can you see anything wrong with my example or can you share a minimal running app that exhibits the issue?

**Comment by scottccoates** [comment]
Well… this is embarrassing.  Turns out I wasn't properly passing the props to the component from the `_app` file.

```javascript
function App({ Component, pageProps }) {
  return (
    <UserProvider>
      <Component /> {/*WHOOPS!*/}
    </UserProvider>
  );
}
export default (AdminApp)
```


@adamjmcgrath, thank you so much for a speed and helpful resolution!

**Comment by scottccoates** [comment]
Hey @adamjmcgrath, do you notice that fast refresh no longer works with this branch? Try making a change to `index.jsx` and fast refresh works fine. But if you make a change to `protected-page.jsx` you will get a full reload.

**Comment by scottccoates** [comment]
I think it's related to https://github.com/vercel/next.js/issues/12891.
