### ISSUE TITLE
Redirect to previous page after login

### ISSUE THREAD

**Issue by gdowmont** [auth0/nextjs-auth0#361]
Using `"@auth0/nextjs-auth0": "1.3.0"` and `"next": "10.1.3"`.

I have configured dynamic routes for `api/auth` endpoints and those are correctly performing login and logout.

Does anyone know how to configure the callback to return to the previous page that was viewed before login?

For example:
As unauthenticated user I am on `/my-custom-page`.
When I perform successful login I am redirected to `/`.

I would like to be returned to `/my-custom-page` instead.

**Comment by adamjmcgrath** [comment]
Hi @gdowmont 

To return to `/my-custom-page` you can visit `/api/auth/login?returnTo=/my-custom-page`

Next time I do a pass of the docs I'll make sure I add this to the README basic example

**Comment by gdowmont** [comment]
Hi @adamjmcgrath. Thanks for posting the answer and sorry about re-opening this.

I think I have worded my question wrongly.
After login I would like to go back to the previous page I was on before I clicked Login, for example, if my login button is in the header of the page.
`/api/auth/login?returnTo=/my-custom-page` expects hardcoded path.

Sorry if I am asking about something obvious but I am quite new to nextjs and auth0.

**Comment by adamjmcgrath** [comment]
No problem @gdowmont!

If you didn't want to hard code it you could use `/api/auth/login?returnTo=${window.location.pathname}`

**Comment by gdowmont** [comment]
Thanks  again @adamjmcgrath 

I did use `/api/auth/login?returnTo=${router.asPath}` combined with `import { useRouter } from 'next/router';` and that did the job.

Thanks for pointing me in the right direction.

For reference I have attached an example:
```js
import React from 'react';
import { useRouter } from 'next/router';
import Button from '@material-ui/core/Button';
import Link from 'next/link';

export default function LoginMenu() {
  const router = useRouter();
    return (
      <Link href={`/api/auth/login?returnTo=${router.asPath}`} passHref>
        <Button variant="text" color="inherit">
          Login
        </Button>
      </Link>
    );
}
```

**Comment by Tbhesswebber** [comment]
I would be happy to open a new issue if that's valuable, but how would you replicate this behavior for a dynamic route that leverages `getServerSideProps` and `withPageAuthRequired`?

```
// pages/things/[thingId].js

export const getServerSideProps({
  getServerSideProps: (ctx) => {},
  returnTo: /things/[thingId]"
});

```

**Comment by milosjovancevic** [comment]
I have a usecase, we use `withPageAuthRequired` and wrap in top `layout` on `App directory` like this:
```
function RootLayout({ children }: { children: ReactNode }) {
  return (
    <UserProvider>
      <html lang="en" className="h-full leading-tight">
        <body className={`${prata.variable} ${nunito_sans.variable} h-full flex flex-col leading-tight`}>
          <LoadingProvider>
            <div className="flex-grow">
              <div className="grid place-items-center h-full">
                <div className="flex flex-col items-center w-full h-full">
                  <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
                </div>
              </div>
            </div>
          </LoadingProvider>
          <BackToTop />
        </body>
      </html>
    </UserProvider>
  )
}

const GuardedLayout = (Component: any) => withPageAuthRequired(Component)

export default GuardedLayout(RootLayout)
```
I dont have login page/login button, simply when user is not logged in he is confronted with auth0 login screen. And I am not sure how to dynamically pass `returnTo` param.

in my `pages/api/auth/[auth0].ts` I tried something like this:
```
import { handleAuth, handleLogin } from '@auth0/nextjs-auth0'

const getLoginState = (req, loginOptions) => {
  console.log('req.headers.referer', req.headers.referer) // <- this is undefined
  return {
    returnTo: '/onboarding/homeowner', // <- this is the only way I managed to make returnTo working, obviously I need dynamic value here
  }
}

export default handleAuth({
  async login(req, res) {
    try {
      await handleLogin(req, res, { getLoginState })
    } catch (err) {
      res.status(err.status ?? 500).end(err.message)
    }
  },
})
```
Any help would be highly appreciated, I am pulling my hair last few days :S
