### ISSUE TITLE
Remove dependency on auth0 secret

### ISSUE THREAD

**Issue by konsumer** [auth0/nextjs-auth0#364]
### Describe the problem you'd like to have solved

I would prefer to not have to store my `AUTH0_CLIENT_SECRET` in environment / code. It presents a security risk, and auth0 offers a few ways to not need this. It also requires me to trust 3rd parties that host the app with my auth-secrets, instead of just auth0.

### Describe the ideal solution

You can get a public-key for verifying an auth0 token like this:

```js
import fetch from 'isomorphic-unfetch'

const { AUTH0_CLIENT_DOMAIN = 'YOURS.auth0.com' } = process.env

export const getAuthInfo = async () => {
  if (getAuthInfo.getAuthInfo) {
    return getAuthInfo.getAuthInfo
  }
  getAuthInfo.getAuthInfo = await (await fetch(`https://${AUTH0_CLIENT_DOMAIN}/.well-known/jwks.json`)).json()
  return getAuthInfo.getAuthInfo
}
```

if you download that first (or even embed it in a setting in your app) you aren't storing a secret, it's public knowledge and completely safe to pass around.

The full verification flow I use, downloading the public key if  needed, is here:

```js
import jwt from 'jsonwebtoken'

export const verify = async tokenSource => {
  const authinfo = await getAuthInfo()
  if (!authinfo && !authinfo.keys) {
    throw new Error("Don't have auth0 token for some reason")
  }
  const token = jwt.decode(tokenSource, { complete: true })
  if (!token) {
    throw new Error('Could not decode token')
  }
  if (token.header.alg !== 'RS256') {
    throw new Error('Invalid algorithm.')
  }
  const sigKey = authinfo.keys.find(k => k.kid === token.header.kid)
  if (!sigKey) {
    throw new Error("Couldn't find signing-key.")
  }
  try {
    const user = jwt.verify(
      tokenSource,
      `-----BEGIN CERTIFICATE-----\n${
        sigKey.x5c[0]
      }\n-----END CERTIFICATE-----`,
      { algorithms: ['RS256'] }
    )
    if (!user) {
      throw new Error()
    }
    return user
  } catch (e) {
    if (process.env.NODE_ENV === 'production') {
      throw new Error('Could not verify token.')
    } else {
      throw e
    }
  }
}
```

**Comment by adamjmcgrath** [comment]
Hi @konsumer - thanks for raising this

This SDK does the [Authorization Code Flow](https://auth0.com/docs/flows/authorization-code-flow) by default. In this flow, the Client Secret is used to exchange the `code` in the code flow for an Access Token and an ID Token. If you want to do the code flow with a confidential client, like this SDK, you must use the `client_secret_basic` or `client_secret_post` token endpoint auth method, for which you'll need a Client Secret.

If you're doing web sign on only (you don't need an Access Token) you can do the [Implicit Flow with Form Post](https://auth0.com/docs/flows/implicit-flow-with-form-post), for this flow you don't need a Client Secret, this library doesn't do it by default and it's a little more involved - but if you'd like me to show you how to do Form post Implicit with this SDK, let me know.

> You can get a public-key for verifying an auth0 token like this:

This SDK always verifies the ID Token's signature using a public key from the jwks endpoint, regardless of which flow you use.

**Comment by konsumer** [comment]
>  if you'd like me to show you how to do Form post Implicit with this SDK, let me know.

I am doing the above in my code, and it works great. My implementation is super-simple (a sign-on callback and 2 redirects for login & logout, each is like 5 lines of code, and the verify business in a graphql directive.) Is there something wrong with that method? Is there a good reason to use `client_secret_basic` or `client_secret_post` in a web-app, that I'm missing? In my own stuff, I'd don't use this library, but a co-worker is using it, and I had to double-check the code-path of the client-secret to make sure it wasn't exposed anywhere. I was a bit surprised the client-secret was required at all, in a frontend library.

**Comment by adamjmcgrath** [comment]
Hi @konsumer 

> I was a bit surprised the client-secret was required at all, in a frontend library.

This SDK comes with a few frontend helpers, but it is a server side library. The SDK is a confidential client, which is why it can keep a Client Secret.

**Comment by adamjmcgrath** [comment]
Hi @konsumer - let me know if you have any other questions or you're happy to close this issue
