### ISSUE TITLE
Usage with Cloudflare Workers

### ISSUE THREAD

**Issue by lucas-janon** [auth0/nextjs-auth0#367]
Hi, we're currently using auth0-react with Next.js and thinking to migrate to nextjs-auth0.

Given we have many client-side queries to our API, we don't want to rely on an API Route as the proxy for all our requests.

I stumbled upon Cloudflare Workers and they seem to be a good option to host the auth proxy, since they don't have any startup time and they also have more availability zones.

I wanted to know if given how this solution was made that can be possible, or if I should go for a more framework-agnostic auth0 library.

Thank you!

**Comment by adamjmcgrath** [comment]
Hi @lucas-janon,

> Given we have many client-side queries to our API, we don't want to rely on an API Route as the proxy for all our requests.

If you don't want to use API Routes at all, yo're better off staying with auth0-react

If you want to use a mix of API routes and call external APIs directly from the client, you might want to look at the adive in https://github.com/auth0/nextjs-auth0/issues/358#issuecomment-813912289 

I'm not familiar with Cloudflare Workers in particular, so I can't give you advice on them

**Comment by lucas-janon** [comment]
Perfect! Thanks for pointing me to [#358 (comment)](https://github.com/auth0/nextjs-auth0/issues/358#issuecomment-813912289)

Have a nice week!

**Comment by adamjmcgrath** [comment]
no worries - thanks @lucas-janon!
