### ISSUE TITLE
Allow custom parameters when refreshing for access token

### ISSUE THREAD

**Issue by hden** [auth0/nextjs-auth0#369]
### Describe the problem you'd like to have solved

Quoting #136 .

> It would be helpful to let us force an access token refresh rather than waiting for them to expire. The scenario I've run into is updating a user's claims after they've updated their profile.

The scenario I've run into is that I need to pass custom parameter to a rule (or action) when doing so.

### Describe the ideal solution

Adding a `customParams` option to the `getAccessToken` method, like so: `getAccessToken({ customParams: { foo: "bar" } })`

## Alternatives and current work-arounds

None that I known of.

**Comment by adamjmcgrath** [comment]
HI @hden - thanks for raising this

Looks like a sensible addition that we could add, I'm not sure when we'll get round to it but I'll leave this open in case anyone wants to submit a PR.

In the meantime, you can work around this by doing the `refresh_grant` yourself, see https://auth0.com/docs/api/authentication#refresh-token
