### ISSUE TITLE
getSession returns null until a handler is run

### ISSUE THREAD

**Issue by statico** [auth0/nextjs-auth0#374]
### Description

I want to synchronize data between my database and Auth0 when a user logs in. I expect the following to work:

```typescript
import { getSession, handleAuth } from "@auth0/nextjs-auth0"
import type { NextApiRequest, NextApiResponse } from "next"
import { syncUser } from "../../../lib/users"

const handler = handleAuth()

export default async (req: NextApiRequest, res: NextApiResponse) => {
  if (req.query.auth0[0] === "callback") {
    const session = getSession(req, res) // <--------- This is always null!
    if (session) await syncUser(session.user.sub)
  }
  await handler(req, res)
}
```

However, calls to `getSession` before a handler return null. After the handler runs, `getSession` returns a session as expected.

I _could_ move my call to `syncUser` after the `handler` call. However, I want to get the session and sync the user _before_ I run the Auth0 handler because I want my user record to be up to date before I redirect the user to page that might make use of outdated data.

### Reproduction

Save the following as `pages/api/[auth0].ts`:

```typescript
import { getSession, handleAuth } from "@auth0/nextjs-auth0"
import type { NextApiRequest, NextApiResponse } from "next"

const handler = handleAuth()

export default async (req: NextApiRequest, res: NextApiResponse) => {
  console.log("BEFORE:", getSession(req, res)?.user.sub)
  await handler(req, res)
  console.log("AFTER:", getSession(req, res)?.user.sub)
}
```

Then log in. I would expect to see both `BEFORE` and `AFTER` log lines with my Auth0 user ID. However, the `BEFORE` line shows `undefined`.

### Environment

- @auth0/nextjs-auth0 v1.2.0
- Next.js 10.1.2
- Node v15.13.0
- Yarn v2.4.1
- macOS 11.2.3 on M1

**Comment by adamjmcgrath** [comment]
Hi @statico - thanks for raising this

> Then log in. I would expect to see both BEFORE and AFTER log lines with my Auth0 user ID. However, the BEFORE line shows undefined.

What is the url you are observing this on (what is `req.url` in this scenario?). If it's the callback handler (`/api/auth/callback`), then I wouldn't expect you to have a session until the callback handler is run, you need some code to execute that get's the callback parameters from the query and exchanges them for an Access and ID Token and then stores that in a session. I don't see a way around this.

**Comment by adamjmcgrath** [comment]
>  I want my user record to be up to date before I redirect the user to page that might make use of outdated data.

Also, you could use [afterCallback](https://auth0.github.io/nextjs-auth0/modules/handlers_callback.html#aftercallback) - this runs after a session has been established and before the redirect

**Comment by statico** [comment]
Thank you, I completely missed this!
