### ISSUE TITLE
withPageAuthRequired loose my custom props

### ISSUE THREAD

**Issue by vousys** [auth0/nextjs-auth0#377]
Hi! I'm working with next.js 10 and node v15.10.0 and I've a problem: props are missing when I use the "withPageAuthRequired" function, and  I get an "undefined" for my custom prop ( "RequireExtraData") . 

_app.tsx

```
import { AppProps } from 'next/dist/next-server/lib/router/router'
import { NextPage } from 'next'

type CustomPage = NextPage & {
  RequireExtraData?: boolean
}
interface CustomAppProps extends Omit<AppProps, 'Component'> {
  Component: CustomPage
}
 
function MyApp({ Component, pageProps }: CustomAppProps) {
    console.log(Component.RequireExtraData)
}

```

index.tsx

```
const Home = (props) => {
  const { user, isLoading } = useUser()
}
Home.RequireExtraData = true
export default withPageAuthRequired(Home)
```

This code dumps in the console.log :  undefined

But If I don't use the "withPageAuthRequired" function , I get "RequireExtraData" contents . 
Is this the expected behaviour? How can I be able to make it work with "withPageAuthRequired"?

Thanks in advance.

**Comment by adamjmcgrath** [comment]
Hi @vousys - `withPageAuthRequired` will return a new Component that wraps your existing component, so you should do something like:

```js
const Home = withPageAuthRequired((props) => {
  const { user, isLoading } = useUser()
})
Home.RequireExtraData = true
export default Home;
```

**Comment by vousys** [comment]
Thank you so much @adamjmcgrath, now it works as expected!
