### ISSUE TITLE
Node crash

### ISSUE THREAD

**Issue by ademenet** [auth0/nextjs-auth0#378]
Hello!

### Describe the problem

A bit of context: I am adding Auth0 to a project already well advanced. For test purposes, I have followed the first steps from this [tutorial](https://auth0.com/docs/quickstart/webapp/nextjs/01-login) and I added two links in `pages/index.js` like so:

```
...
<div>
  <a href="/api/auth/login">Login</a>
  <a href="/api/auth/logout">Logout</a>
</div>
...
```

But, when I am trying to click on _Login_, the app is crashing with the following error log:

```
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "timeout" argument must be of type number. Received an instance of Object
    at new NodeError (node:internal/errors:329:5)
    at validateNumber (node:internal/validators:134:11)
    at getTimerDuration (node:internal/timers:384:3)
    at new ClientRequest (node:_http_client:183:20)
    at request (node:https:333:10)
    at Object.proxiedOriginalRequest (/Users/path/node_modules/node-request-interceptor/lib/interceptors/ClientRequest/index.js:55:36)
    at ClientRequestOverride.<anonymous> (/Users/path/node_modules/node-request-interceptor/lib/interceptors/ClientRequest/ClientRequestOverride.js:243:39)
    at step (/Users/path/node_modules/node-request-interceptor/lib/interceptors/ClientRequest/ClientRequestOverride.js:33:23)
    at Object.next (/Users/path/node_modules/node-request-interceptor/lib/interceptors/ClientRequest/ClientRequestOverride.js:14:53)
    at fulfilled (/Users/path/node_modules/node-request-interceptor/lib/interceptors/ClientRequest/ClientRequestOverride.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 'ERR_INVALID_ARG_TYPE'
```

I have done some investigations to find where it could come from and I noticed:

- it happens only when I am going to my index page, then, if I try to reach `/api/auth/login` (by clicking on _Login_ or by typing `http://localhost:3000/api/auth/login` in the URL bar): it crashes,
- if I restart my server (with `yarn dev`) and reach directly `/api/auth/login`: it works. Moreover, if I return on my index page and click on the Login link: it works.

### What was the expected behavior?

It should redirect on Auth0 Universal Login.

### Reproduction

I tried to reproduce this error with a toy project but I wasn’t able to do it. However the error is consistent in my project.

I guess it is due to some of our project dependencies issues. I am sharing more of my environment in the next section.

### Environment

- **Version of this library used:** 1.3.0
- **Node version:** 16.0.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:** here is the list of dependencies:

```
"@auth0/nextjs-auth0": "^1.3.0",
"@mapbox/rehype-prism": "^0.6.0",
"@tailwindcss/aspect-ratio": "^0.2.0",
"@tailwindcss/typography": "^0.4.0",
"autoprefixer": "^10.2.4",
"aws-sdk": "^2.882.0",
"core-js": "3",
"framer-motion": "^3.3.0",
"mongodb": "^3.6.6",
"msw": "^0.26.2",
"next": "10.1.3",
"next-mdx-remote": "^2.1.3",
"postcss": "^8.2.4",
"react": "17.0.2",
"react-dom": "17.0.2",
"rehype-katex": "^4.0.0",
"remark-autolink-headings": "^6.0.1",
"remark-code-titles": "^0.1.1",
"remark-iframes": "^4.0.5",
"remark-math": "3.0.1",
"remark-prism": "^1.3.4",
"remark-slug": "^6.0.0",
"tailwindcss": "^2.0.2"
```

- **Any other relevant information you think would be useful:** I have some config files for Babel, Next, Tailwind and PostCSS if it could be related to this issue I can share them.

Thank you!

**Comment by adamjmcgrath** [comment]
@ademenet - This looks related to https://github.com/mswjs/interceptors/issues/86#issuecomment-804858302

Try updating `msw` to see if this fixes the issue

**Comment by ademenet** [comment]
You are right!

I also came across this comment and found the piece of code that was causing the problem in my `_app.js`: 

```
if (process.env.NEXT_PUBLIC_API_MOCKING === "enabled") {
  require("../mocks");  // msw's server mock
}
```

So not related to `nextjs-auth0`. But I don't understand why it starts to crash while I just added `UserProvider` in `_app.js`.

Anyway, thank you very much for your support!
