### ISSUE TITLE
Support for a /signup handler

### ISSUE THREAD

**Issue by chrispeterson3** [auth0/nextjs-auth0#379]
### Describe the problem you'd like to have solved
- Support for a signup handler for `handleAuth`

When creating a new application or service, there should be a quick and easy way for a CTA for "Sign up". It seems that today a user would have to go to `/api/auth/login` and then click "Sign up".

### Describe the ideal solution
A handler for `/api/auth/signup`

## Alternatives and current work-arounds
The suggested workarounds don't seem to work suggested in #24 . After calling `initAuth0`, the types for the options parameter on `handleLogin` do not support `authParams` it seems.

### Additional information, if any
![image](https://user-images.githubusercontent.com/2593324/115935272-ae5e9700-a447-11eb-992a-1ece2534205f.png)

**Comment by chrispeterson3** [comment]
It looks like a bit of user error on my part. `authParams` was changed to `authorizationParams`. This implementation will work.

```import { initAuth0 } from '@auth0/nextjs-auth0';

const auth0 = initAuth0({
  baseURL: process.env.AUTH0_BASE_URL,
  issuerBaseURL: process.env.AUTH0_ISSUER_BASE_URL,
  clientID: process.env.AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET,
  secret: process.env.AUTH0_SECRET,
});

export default async function signup(req, res) {
  try {
    await auth0.handleLogin(req, res, {
      authorizationParams: {
        screen_hint: 'signup',
      },
    });
  } catch (error) {
    res.status(error.status || 500).end(error.message);
  }
}
```

A signup handler would be nice though!

**Comment by samkahchiin** [comment]
Thanks for the sharing! This will works as well. :D

```
import { handleLogin } from '@auth0/nextjs-auth0'

export default async function signup(req, res) {
  try {
    await handleLogin(req, res, {
      authorizationParams: {
        screen_hint: 'signup',
      },
    })
  } catch (error) {
    res.status(error.status || 500).end(error.message)
  }
}
```
