### ISSUE TITLE
Support invitation parameters in the login handler

### ISSUE THREAD

**Issue by htunnicliff** [auth0/nextjs-auth0#381]
### Describe the problem you'd like to have solved

It would be fantastic if the login route (`/api/auth/login`) forwarded query string parameters used by organization invitation URLs, specifically the following:
- `invitation`
- `organization`
- `organization_name`

These parameters should be added to the authorization parameters. See the Auth0 docs on [Organizations > Invite Organization Members > Specify route behavior][1].

This problem is also frustrating because the Auth0 Next.js SDK does not support what the docs [recommend][1]:

> For example, if you have an organization-enabled application with an Application Login URI set to `https://myapp.com/login`, then the link sent in the email invitation that an end-user receives will be: `https://myapp.com/login?invitation={invitation_ticket_id}&organization={organization_id}&organization_name={organization_name}`.

### Describe the ideal solution

The ideal solution would be that the SDK handles this behavior automatically in the background. If that isn't possible, it would be nice if the invitation behavior was documented.

## Alternatives and current work-arounds

Here's what I'm doing in my `[...auth0].ts` handler to achieve this:

```ts
// pages/api/auth/[...auth0].ts
import { handleAuth, handleLogin } from "@auth0/nextjs-auth0";

export default handleAuth({
  async login(req, res, options) {
    const { 
      invitation, 
      organization,
      organization_name
    } = req.query;

    await handleLogin(req, res, {
      ...options,
      authorizationParams: {
        ...options?.authorizationParams,
        invitation,
        organization,
        organization_name
      },
    });
  },
});
```

[1]: https://auth0.com/docs/organizations/invite-members#specify-route-behavior

**Comment by adamjmcgrath** [comment]
Hi @htunnicliff - thanks for raising this.

We have an example for how to handle organization invitations here https://auth0.github.io/nextjs-auth0/interfaces/handlers_login.authorizationparams.html#invitation

Your suggestion looks good too.

We don't have plans at the moment to add this behaviour into the SDK, but we're always reviewing this and I'll add this to our product backlog

**Comment by htunnicliff** [comment]
@adamjmcgrath I like the way it is handled in the example you linked to. Would it be difficult to simply bundle an "invite" route (at `/api/auth/invite`) that uses that exact code, then mention it in the docs?

**Comment by htunnicliff** [comment]
^^ It would be a non-breaking change, since `/api/auth/invite` is not used by the SDK at present.

**Comment by adamjmcgrath** [comment]
Hi @htunnicliff - thanks for the suggestion

We don't have any plans to add any more login endpoints to the SDK. We're happy that one is satisfactory and the login handler is extensible enough to be customized for any combination of urls or parameters you might want to pass on to the Universal Login Page.

That said, we're always reviewing this, so we'll take your suggestions on board. Closing this, feel free to ping me if you'd like me to reopen

**Comment by taylor-ben** [comment]
Handle invitation for Next app router

```ts
import { handleAuth, handleLogin } from '@auth0/nextjs-auth0'

export const GET = handleAuth({
  async login(req: any, res: any, options?: any) {
    const invitation = req.nextUrl.searchParams.get('invitation')
    const organization = req.nextUrl.searchParams.get('organization')
    const organization_name = req.nextUrl.searchParams.get('organization_name')

    return handleLogin(req, res, {
      ...options,
      returnTo: '/dashboard',
      authorizationParams: {
        ...options?.authorizationParams,
        invitation,
        organization,
        organization_name,
      },
    }) as Promise<void | Response>
  },
})
```
