### ISSUE TITLE
Account linking Next JS with Auth0

### ISSUE THREAD

**Issue by dpramani** [auth0/nextjs-auth0#384]
Hi

In my nextjs application I have a user settings page which has a ‘Link Google’ button. The desired functionality is, users should be able to link their google accounts. That can be with the same email they logged in with or a different email. How can we achieve that ?

I am using the nextjs-auth0 package and universal login.

Thanks
Debabrata Pramanik

**Comment by adamjmcgrath** [comment]
Hi @dpramani - thanks for your question

This is outside of the scope of this SDK, but can be done with your auth0 tenant and Universal Login, see this blog post for guidance https://auth0.com/blog/easy-way-for-users-to-link-accounts/
