### ISSUE TITLE
handleProfile with refetch set to true does not fetch a latest user profile 

### ISSUE THREAD

**Issue by minyou9** [auth0/nextjs-auth0#385]
I have an api route to update user profile name and picture. The problem is that in order to see the latest profile, I have to log out and log in again. This is not a good user experience. I looked up the auth0 nextjs docs and found the **handleProfile**. I created an api route for that. However, when I tried to fetch that on the page, it did not show the latest user profile. 

```
import { handleProfile, withApiAuthRequired } from "@auth0/nextjs-auth0";

export default withApiAuthRequired(async function checkProfile(req, res) {
  try {
    await handleProfile(req, res, {
      refetch: true,
    });
  } catch (error) {
    res.status(error.status || 500).end(error.message);
  }
});
```

Does anyone have any insight into this? Any suggestion to clear the cookie after the users update their profiles?

**Comment by adamjmcgrath** [comment]
Hi @minyou9 - thanks for raising this

I can't reproduce your issue and we have [a test](https://github.com/auth0/nextjs-auth0/blob/main/tests/handlers/profile.test.ts#L55-L65) to cover this scenario. What are you using to read the user profile and how are you expecting it to be updated?

**Comment by minyou9** [comment]
Hi @adamjmcgrath 

So basically, I have a route to update users profile through user_metadata. Let say after the users submit their updated profile, I then checked on my auth0 dashboard and under Users Section, I see the latest values.  

Initially, I use useUser to fetch the user profile. However, it does not have the latest changes and I have to logout and log back in to see the latest changes. So I created a route to refetch the user profile by this
```
import { handleProfile, withApiAuthRequired } from "@auth0/nextjs-auth0";

export default withApiAuthRequired(async function checkProfile(req, res) {
  try {
    await handleProfile(req, res, {
      refetch: true,
    });
  } catch (error) {
    res.status(error.status || 500).end(error.message);
  }
});
```
In the frontend, I am using this to retrieve the user profile
```
import useSWR from "swr";

const fetcher = async (uri) => {
   const response = await fetch(uri);
    return response.json();
};
const { data, error } = useSWR("/api/auth/check-profile", fetcher);
```

But when I console log the data, it does not reflect any latest changes. It is still using the cache version.

I apologize for my bad english. But if you need any more information to reproduce, please let me know I will try my best to provide it

Thank you in advance

**Comment by adamjmcgrath** [comment]
Hi @minyou9 - `user_metadata` does not show up in `/userinfo` (the endpoint called by `handleProfile`)

If you want to add properties from `user_metadata` to `/userinfo` take a look at https://auth0.com/docs/scopes/sample-use-cases-scopes-and-claims#add-custom-claims-to-a-token
