### ISSUE TITLE
Does nextjs-auth0 absolutely need to depend on Node.js API?

### ISSUE THREAD

**Issue by awthwathje** [auth0/nextjs-auth0#387]
Hello and first of all thanks for this library. It simplifies server-side authentication setup tremendously!

There is one problem with it though: it depends on Node.js. Well, you may think that this not a problem at all. The library has `nextjs` in its name and Next.js ships with the Node.js server.

However, Next.js is no longer uses Node.js for every SSR deployment. A use case which we starting to see more and more is the serverless deployment. But serverless deployments use Node.js under the hood, right? Right, but not exclusively anymore.

With the advent of Isolates, which are part of V8, there is no longer need for Node.js in serverless infrastructure. We are starting to see offerings from likes of Cloudflare which run Isolates at the edge and at scale.

Next.js, although not designed to run on Isolates, does actually run there with the help of bundlers like FAB. But if we want to use `nextjs-auth0` in a Next.js app, it won't compile, since `nextjs-auth0` depends on Node.js APIs.

I'm already working on a lightweight library to handle Auth0 SSR authentication in Isolates, looking at the `nextjs-auth0` implementation. But the question remains: does `nextjs-auth0` absolutely need to depend on Node.js API?

**Comment by adamjmcgrath** [comment]
Hi @awthwathje - thanks for your interesting question.

I guess the 2 main Node.js APIs that this SDK uses is `http` for Discovery and Code Exchange and `crypto` for JWT verification and JWE encryption and decryption (as well as Buffers, events and other lower level APIs). So this SDK leans pretty heavily on Node.js.

**Comment by adamjmcgrath** [comment]
Hi @awthwathje - closing this, feel free to ping me to reopen if you have any other questions

**Comment by thomasballinger** [comment]
I'm also wondering about this, what are folks doing instead? Is there another API for Auth0 from modern non-Node.js runtimes?

**Comment by thomasballinger** [comment]
Oh look, there's edge support now! Just gotta read the docs :)
<img width="498" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/458879/8134192a-223e-4a0d-93e8-2c6291c037ed">
