### ISSUE TITLE
E2E testing 

### ISSUE THREAD

**Issue by softshipper** [auth0/nextjs-auth0#390]
Hi all  

I would like to do E2E testing with CypressJS and woud like to know how to automate login process.
Would be nice, if someone can help me.

Thanks

**Comment by adamjmcgrath** [comment]
Hi @softshipper - I recommend you check out https://github.com/sir-dunxalot/cypress-nextjs-auth0 which works with the latest version of this SDK

**Comment by htunnicliff** [comment]
@adamjmcgrath would you be willing to reopen this issue?

[cypress-nextjs-auth0](https://github.com/sir-dunxalot/cypress-nextjs-auth0) requires that the `Password` grant is enabled for a Next.js application being tested, but that is not possible to enable when using Auth0 Organizations. 

<img width="923" alt="Screen Shot 2021-08-13 at 8 32 42 AM" src="https://user-images.githubusercontent.com/7614039/129383132-1f1bd756-9b0b-47c6-a771-e69f598ac21c.png">

**Comment by brandonmikeska** [comment]
@adamjmcgrath it also appears that package is no longer working: https://github.com/sir-dunxalot/cypress-nextjs-auth0/issues/23

**Comment by adamjmcgrath** [comment]
@htunnicliff - If you can't use the Password grant and you need to get an Access Token for a user under test, then you have no option but to do the interactive login flow in Cypress. Which would be out of scope for adding to this SDK

**Comment by htunnicliff** [comment]
> @htunnicliff - If you can't use the Password grant and you need to get an Access Token for a user under test, then you have no option but to do the interactive login flow in Cypress. Which would be out of scope for adding to this SDK

Hey @adamjmcgrath – Cypress does not support navigating to other websites during a test, so I don't believe that will work.

**Comment by htunnicliff** [comment]
> > @htunnicliff - If you can't use the Password grant and you need to get an Access Token for a user under test, then you have no option but to do the interactive login flow in Cypress. Which would be out of scope for adding to this SDK
> 
> Hey @adamjmcgrath – Cypress does not support navigating to other websites during a test, so I don't believe that will work. 

Navigating to external sites is not supported, per the [Cypress docs](https://docs.cypress.io/guides/references/best-practices#Visiting-external-sites).

**Comment by adamjmcgrath** [comment]
@htunnicliff - have a look at how this SDK implemented E2E testing against a mock OIDC provider https://github.com/auth0/nextjs-auth0/pull/457

**Comment by htunnicliff** [comment]
> @htunnicliff - have a look at how this SDK implemented E2E testing against a mock OIDC provider #457

@adamjmcgrath I can see how creating a mock OIDC provider would make E2E testing of the Auth0 Next.js SDK workable. 

However, replicating that wouldn't solve the issue of testing an app that depends on the SDK, unless we mocked out Auth0's entire management API, which defeats the purpose of integration testing in the first place.

**Comment by adamjmcgrath** [comment]
Hey @htunnicliff - thanks for your feedback

Yep you're right - If your client doesn't allow the Password (or Client Credentials) grant you can only get ATs interactively (via the Universal Login Page) and Cypress doesn't recommend visiting external sites during tests. Also, a mock OIDC provider wont get you an AT to use with the Auth0 Management API (it's just a mock). These restrictions are not put on you by this SDK, so I'm not sure what you want this SDK to do about it.

**Comment by htunnicliff** [comment]
Hey @adamjmcgrath, I think I'm following. It sounds like the thing that needs to happen for E2E to become possible with Auth0 Organizations is an update to the Authorization API, not this SDK. Thanks for helping me troubleshoot.
