### ISSUE TITLE
useConfig and useUser do not take basePath into account

### ISSUE THREAD

**Issue by bairamau** [auth0/nextjs-auth0#392]
### Description
`useConfig` and `useUser` hooks do not take next.js [basePath](https://nextjs.org/docs/api-reference/next.config.js/basepath) config into account when calculating default `loginUrl` and `profileUrl` value respectively:
https://github.com/auth0/nextjs-auth0/blob/825941a00ec062b91c74a0be27c99c0872fb7389/src/frontend/use-config.tsx#L15
https://github.com/auth0/nextjs-auth0/blob/825941a00ec062b91c74a0be27c99c0872fb7389/src/frontend/use-user.tsx#L136

### Reproduction
1. Create a next.js project with custom `basePath` config
2. Create a page wrapped into `withPageAuthRequired` HOC
3. Request to get user profile will not have correct url
4. `window.location` will be assigned to an incorrect login url
### Environment
- **Version of this library used:** ^1.3.0
- **Version of the platform or framework used, if applicable:** next ^10.1.3
## Alternatives and current work-arounds
Setting custom `NEXT_PUBLIC_AUTH0_LOGIN` and `NEXT_PUBLIC_AUTH0_PROFILE` that include `basePath` fixes the issue

**Comment by adamjmcgrath** [comment]
Hi @bairamau - thanks for raising this.

This is expected behaviour - the default values for login and logout assume no `baseUrl` - if your app provides a baseUrl you should use the workaround you described to provide custom values.

Closing this - feel free to ping me to reopen if you have any other questions

**Comment by bairamau** [comment]
Hi again, @adamjmcgrath, i've encountered a problem, that is closely related to this
Here in helper, we are using runtime redirect
https://github.com/auth0/nextjs-auth0/blob/ae1da65ba75252d92fceddf7135721b16d23af44/src/helpers/with-page-auth-required.ts#L114-L119

and `loginUrl` will already have `basePath` part included, if we have it in nextjs configuration,
that results the described workaround being unusable if we use both client side and server side auth pages in our project, because basePath will be duplicated in url, once from here, and once from `NEXT_PUBLIC_AUTH0_LOGIN `

maybe a good solution would be to add `basePath: false`  property to the redirect, to keep approaches consistent

**Comment by valters** [comment]
Hardcoding a random global URL like `/api/auth/me` does not make sense. You should be prepending `NEXT_PUBLIC_AUTH0_BASE_URL` (if provided) in front of it.
