### ISSUE TITLE
`Property 'user' does not exist on type 'Session | null | undefined'`

### ISSUE THREAD

**Issue by corysimmons** [auth0/nextjs-auth0#397]
- `"@auth0/nextjs-auth0": "^1.3.0"`
- `"typescript": "^4.2.4"`
- `"next": "^10.2.0"`

![image](https://user-images.githubusercontent.com/224636/118399061-4d327980-b629-11eb-9b7f-cfe65dd050fd.png)

But if I hyperclick through to the `Session` type def it looks like `user` is on there.

<img src="https://user-images.githubusercontent.com/224636/118399093-73581980-b629-11eb-9512-8afb05df9bcb.png" width="400">

This happens anywhere I try to use `const { user } = getSession(...)` 😕

**Comment by adamjmcgrath** [comment]
Hi @corysimmons

`getSession` can return `Session | null | undefined` - so what typescript is telling you there is that you can't deconstruct a user from the `getSession` response, without first checking that it's not `null | undefined`. Because at runtime `const { user } = null;` will throw an error.

Better to do something like:

```js
const session = getSession(req, res);
const user = session?.user;
```

**Comment by corysimmons** [comment]
Awesome, thank you so much for your help!

**Comment by dblack** [comment]
Hello --

I'm stuck in a similar loop, in my convert-to-typescript branch. I've even converted `[...auth0].tsx` to `.js` but still getting: `Cannot read properties of undefined (reading &#39;email&#39;)` in the browser from `afterCallback`. Here's the file:
```
import { handleAuth, handleCallback } from '@auth0/nextjs-auth0';
import prisma from './../../../lib/prisma';

const afterCallback = async (session) => {
  const profiledUser = await prisma.user.findFirst({
    where: { email: session.user.email }
  })

  session.user.localId = profiledUser.id
  delete session.refreshToken
  return session;
};

export default handleAuth({
  async callback(req, res) {
    try {
      await handleCallback(req, res, { afterCallback });
    } catch (error) {
      res.status(error.status || 500).end(error.message);
    }
  }
});
```
It works in my non-typescript branch but here, although `session` is populated, `user` is undefined. 

I'm hoping it will be one of these ones where I figure it out as soon as I hit send, but in case not.... :-) Thanks for any help!
