### ISSUE TITLE
add support for refresh token

### ISSUE THREAD

**Issue by vgrafe** [auth0/nextjs-auth0#4]
First of all, thanks for this great library, the struggle was so real before I came across your nextjs example!

As requested in https://github.com/sandrinodimattia/nextjs-auth0-example/issues/2 :

A good feature for the next release would be to store refresh token, in order to allow getting new access tokens when needed.

**Comment by sandrinodimattia** [comment]
Fixed in `v0.2.0`. You'll want to request the `offline_access` scope in addition to any other scopes and then set `storeRefreshToken` to true.

There's some additional things we're tracking here: https://github.com/auth0/nextjs-auth0/issues/7

**Comment by sandrinodimattia** [comment]
Let me know if we can close this issue.

**Comment by vgrafe** [comment]
That was fast!! I'll have a look after work.

**Comment by b2times4** [comment]
Brilliant + fast = brilliant.
I'll (kindly) "need"  [sandrinodimattia/nextjs-auth0-example]( sandrinodimattia/nextjs-auth0-example) to be updated for implementation.
I managed to get the example implemented as is, but brain not large enough to update it with refresh_token

**Comment by vgrafe** [comment]
Just tried 0.2.0, perfect! I can see the token in the JTW session. You can close. 

@b2times4: you might want to file an issue in the repo you linked. I'll mention you if I find myself figuring out a working example of token refresh.

**Comment by sandrinodimattia** [comment]
We now have a full example available that shows how to get a valid access token (and if expired, automatically get a new one using a refresh token):

https://github.com/auth0/nextjs-auth0/blob/master/examples/api-call-example/pages/api/shows.js#L9-L11

I'm going to go ahead and close this issue now.
