### ISSUE TITLE
Access Token expired, but cookie still valid

### ISSUE THREAD

**Issue by karaggeorge** [auth0/nextjs-auth0#40]
### Description

You can set expiration time for your tokens in the Auth0 dashboard. If you set that to a value that's lower than the cookie lifetime, the session cookie should use that as expiration. Otherwise you can get to a point where the cookie is valid, but the access token is not.

### Reproduction

- Set token expiration to 2 minutes
- Set cookie lifetime to 4 minutes
- Log in
- Wait 2 minutes
- Session is valid, while access token is not

### Notes

This could be tracked and updated using the `expired_at` the same way that it's done in #37 

It will also make #38 safer, since you'll always know you can fetch the user with a valid token if the session hasn't expired

If this sounds reasonable, I can open a PR to address it or include it in one of the two mentioned above

**Comment by sandrinodimattia** [comment]
This is now solved in v0.8.0. The correct way to request an access token is through the token cache helper which will automatically get a new access token when needed (and if possible). If a valid access token cannot be returned it will throw an error:

```js
const tokenCache = await auth0.tokenCache(req, res);
const { accessToken } = await tokenCache.getAccessToken();
```
