### ISSUE TITLE
Route to signup page

### ISSUE THREAD

**Issue by thgh** [auth0/nextjs-auth0#400]
### Describe the problem you'd like to have solved

I would like to link to the signup page.

### Describe the ideal solution

Add an API route `/api/auth/signup` that redirects. (similar to /api/auth/login)

## Alternatives and current work-arounds

Combine the login & signup call-to-action into 1 button.

**Comment by adamjmcgrath** [comment]
Hi @thgh - Assuming you're using the new login experience,  you can create your own signup page like so:

Create `pages/api/signup.js`

```js
import auth0 from '../../lib/auth0';

export default async function signup(req, res) {
  try {
    await auth0.handleLogin(req, res, {
      authorizationParams: {
        screen_hint: 'signup',    // this prompts the signup screen
      },
    });
  } catch (error) {
    console.error(error);
    res.status(error.status || 500).end(error.message);
  }
}
```

Then link to the signup page:

```
<a href='/api/signup'>Sign Up</a>
```

If you're using the Classic login experience you might want to use a different `authorizationParams` key and there's a little more work to do on your custom login page, see: https://community.auth0.com/t/how-do-i-redirect-users-directly-to-the-hosted-signup-page/42520

**Comment by orbiteleven** [comment]
TBH this seems like a normal enough use case that the lib could/should provide it out of the box.

**Comment by lucasvmiguel** [comment]
Why was this closed? As @orbiteleven, this seems to be an important piece to implement in this SDK.

**Comment by NathanLandsX** [comment]
Major oversight that this isn't a main part of the SDK. People need signup before login...

**Comment by kkomelin** [comment]
Also need the Signup route.

**Comment by epark10** [comment]
Bumping as signup is a critical part of the user identity process, should be included
