### ISSUE TITLE
Auth0 SDK not working with other serverless functions using NextJS and Vercel

### ISSUE THREAD

**Issue by PumPum7** [auth0/nextjs-auth0#401]
### Describe the problem
When using the NextJS Auth0 SDK you get a 404 not found error instead of getting redirected to the login page. Callback and logout URL are correctly specified to `http://localhost:3000` and `http://localhost:3000/api/callback`

### What was the expected behavior?
A redirect to the login page and the other serverless functions still working.

### Reproduction
1. Use NextJS together with Vercel to handle serverless functions. 
2. Create serverless functions in a different language than JS. In my case this would be go. These serverless functions are located outside the pages/api/auth folder (they are in the root api folder)
3. Try to access the login/logout/... API routes 

### Environment

- **Version of this library used:** 1.3.1
- **Which framework are you using, if applicable:** NextJS 
- **Other modules/plugins/libraries that might be involved:** GoLang serverless functions
- **Any other relevant information you think would be useful:** The website is started by using `vercel dev`. I am also using Go serverless functions.

**Comment by PumPum7** [comment]
For more information: I have also posted this issue on the Auth0 community page https://community.auth0.com/t/nextjs-sdk-results-in-page-not-found/63067

**Comment by adamjmcgrath** [comment]
Hi @PumPum7 - thanks for raising this

> Try to access the login/logout/... API routes

Do all API routes return 404 or just the routes created by the SDK? If you created a dummy route at `pages/api/foo.js` do you get a 404 there as well?

If so, your issue is probably with Next.js rather than this SDK. If not, can you create a minimal app that reproduces the issue and I can debug it for you.

**Comment by PumPum7** [comment]
Only for routes created by the SDK everything else works, also other serverless functions in the pages/api or pages/api/auth folder. 
Also I have also contacted Vercel about this issue since it might be a Vercel issue. 
I will look into creating a minimal App for reproduction purposes later today.

**Comment by PumPum7** [comment]
I was able to fix this issue by moving the file from pages/api/auth to just api/auth in the root directory of the project. This is not the suggested way of doing it according to Vercel but I was able to solve my problem with this workaround.

**Comment by adamjmcgrath** [comment]
@PumPum7 - doesn't sound like this is an problem with the SDK and you have resolved your issue, so closing.

Feel free to ping me if you'd like me to reopen it

**Comment by dlcaio** [comment]
Hey @PumPum7, can you please share more details on how you managed to get it to work ?

For example, what version of next did you use ? Or anything else you may find relevant.

I tried moving the pages/api/auth[...auth0].js file to <root>/api/auth/ but that did not help me. Same 404 error.

Cheers!
