### ISSUE TITLE
Cant login using auth0

### ISSUE THREAD

**Issue by mohhef** [auth0/nextjs-auth0#402]
### Description
Repo: https://github.com/mohhef/Mohamed-Hefny-Portfolio/tree/main/mohamed-hefny-portfolio
Every time  I try to login, I get redirected to the home page without actually prompting the login page.
And my user does not get set even after that automatic redirection
This behaviour started happening to my application randomly. This was not the case before, I used to be able to login and logout normally.

### Reproduction
add an env.local file for the auth0 variables
run the application using
npm run dev-debug
Try to login using the login button on the top right
![ImageNest](https://user-images.githubusercontent.com/41707836/119248159-480b8800-bb5d-11eb-8d84-b111bb0ecfa2.gif)

### Environment

    Windows 10
    npm 14.17
    "@auth0/nextjs-auth0": "^1.3.1",
    "axios": "^0.21.1",
    "bootstrap": "^4.4.1",
    "cross-env": "^7.0.3",
    "dotenv-webpack": "^7.0.2",
    "next": "^10.2.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-typed": "^1.2.0",
    "reactstrap": "^8.9.0",
    "sass": "^1.32.13",
    "swr": "^0.5.6"

**Comment by mohhef** [comment]
The issue was because, next js automatically points to api/auth/me, 
is there a way to override that path to api/v1/auth/me

**Comment by Widcket** [comment]
Hi @mohhef, thanks for raising this. You can customize the profile endpoint, please check out this document for more details: https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#use-custom-auth-urls.
Let me know if you run into any issues.

**Comment by adamjmcgrath** [comment]
Closing this - looks like it's been resolved, @mohhef let me know if you want to reopen it
