### ISSUE TITLE
withPageAuthRequired() not returning a user object

### ISSUE THREAD

**Issue by chris-hinds** [auth0/nextjs-auth0#403]
### Describe the problem

When using the `withPageAuthRequired()` function a user object is not returned as a prop to the page component as described in the example. When a user is not logged in visiting this page does redirect the user allowing them to login however the user object is never returned.

### What was the expected behavior?

Once a user has authenticated the user object is expected to be returned as a prop.

### Reproduction

```
import { withPageAuthRequired } from "@auth0/nextjs-auth0";

const Dashboard = (props) => {
  console.log(props);
  //   if (user) return <div>Welcome, {user.nickname}</div>;
  return <div>Hello</div>;
};

export default withPageAuthRequired(Dashboard);
```

In the above example page, visiting the page when logged out the user is correctly redirected to the login page, however. a user object is never returned. Not in the example code that `props` is simply an empty object even though a user session exists.

### Environment

- Localhost

- **Version of this library used:** 1.3.1
- **Which framework are you using, if applicable:** 10.2.2
- **Other modules/plugins/libraries that might be involved:** React: 17.0.2, React-DOM: 17.0.2

**Comment by chris-hinds** [comment]
Hmmm strangely when I pair this with `getServerSideProps` The component does receive the `user` object.

Example:

```
import { withPageAuthRequired } from "@auth0/nextjs-auth0";

const Dashboard = (props) => {
  console.log(props);
  //   if (user) return <div>Welcome, {user.nickname}</div>;
  return <div>Hello</div>;
};

export const getServerSideProps = withPageAuthRequired({
  getServerSideProps: async (context) => {
    return {
      props: {
        name: "Chris",
      },
    };
  },
});

export default Dashboard;
```

**Comment by Widcket** [comment]
Hi @chris-hinds, thanks for raising this.
To get a user object in your client-side rendered pages, you need to wrap your `pages/_app.js` component in the `UserProvider` component. That's not necessary for server-side rendered pages (`getServerSideProps`). Can you please check if you are wrapping your app in `UserProvider`?

**Comment by adamjmcgrath** [comment]
@Widcket - it doesn't look like we add `user` to props in the client-side `withPageAuthRequired` https://github.com/auth0/nextjs-auth0/blob/main/src/frontend/with-page-auth-required.tsx#L94

This is [consistent with auth0-react](https://github.com/auth0/auth0-react/blob/master/src/with-authentication-required.tsx#L119), but different to our [server-side](https://github.com/auth0/nextjs-auth0/blob/main/src/helpers/with-page-auth-required.ts#L120) `withPageAuthRequired`

@chris-hinds - for the time being you should use `const { user } = useUser()` inside your `withPageAuthRequired` wrapped component to access the user (there's no performance penalty for doing this). We'll investigate whether we want to add this as a feature.

**Comment by Widcket** [comment]
That's correct, the wrapping is necessary for the `useUser` hook to work, but does not add the user prop on itself.
