### ISSUE TITLE
`handleAuth()` can deal with both env file names with prefix or suffix. (.local.env or .env.local)

### ISSUE THREAD

**Issue by yumemi-omi** [auth0/nextjs-auth0#409]
### Describe the problem you'd like to have solved
`handleAuth()` can't read `.local.env` file, while it can read `.env.local`.

### Describe the ideal solution
`handleAuth()` can deal with both file names.(`.local.env` and `.env.local`).

## Alternatives and current work-arounds
Using env file with prefix like `.env.local`.

**Comment by Widcket** [comment]
Hi @yumemi-omi, thanks for raising this. The SDK does not implement the functionality required for reading `env` files, Next.js does. And Next.js [supports only](https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables) `.env.local` at the moment.
You might want to open an issue requesting this feature on the Next.js repo. I'll close this issue for now, please ping me if you'd like to reopen it.

**Comment by yumemi-omi** [comment]
@Widcket 
Thank you for replying. I learned it for the first time. Yes, I will request the feature to the Next.JS repo. Thanks!
