### ISSUE TITLE
Access denied: Unauthorized ('feacft') errors when deployed to Netlify

### ISSUE THREAD

**Issue by endofu** [auth0/nextjs-auth0#411]
### Description

A simple setup that only slightly differs from the provided example runs perfectly on http://0.0.0.0:3000 but if I try to deploy it to Netlify I get "feacft" (access_denied: Unauthorized) after logging in. 

Logging this after a painful day of researching and trying everything without any success.

I see in the Logs that every login attempt consists of a good looking Success Login event but while it is followed by a Success Exchange one locally, on Netlify the second event is Failed Exchange:

```
{
  "date": "2021-06-08T03:10:10.424Z",
  "type": "feacft",
  "description": "Unauthorized",
  "connection_id": "",
  "client_id": null,
  "client_name": null,
  "ip": "5.............4",
  "user_agent": "Other 0.0.0 / Other 0.0.0",
  "details": {
    "code": "*************7Y7"
  },
  "hostname": "t....g.us.auth0.com",
  "user_id": "",
  "user_name": "",
  "auth0_client": {
    "name": "nextjs-auth0",
    "version": "1.3.1",
    "env": {
      "node": "v12.22.1"
    }
  },
  "log_id": "9002...............2402",
  "_id": "9002...............2402",
  "isMobile": false
}
```

`handleCallback` throws this error:

```
BadRequestError: access_denied (Unauthorized)
    at Object.<anonymous> (/var/task/src/nextPage.js:32862:19)
    at Generator.throw (<anonymous>)
    at rejected (/var/task/src/nextPage.js:24932:69)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I logged the `req` and the `res` in the `handleauth( { } )` in `[...auth0].js` and the objects seem to be quite different locally and on Netlify. Locally they are `IncomingMessage` and `ServerResponse` while on Netlify they are a `Readable` and a `Stream` and the local ones are significantly more verbose.

Is Netlify doing something with the requests that breaks the flow here? Or I have to adjust some settings on Auth0 or in my code? 

My whole `[...auth0].js` is rather simple:

```
import { handleAuth, handleCallback } from '@auth0/nextjs-auth0'

const afterCallback = (req, res, session, state) => {
  if (process.env.AUTH0_RETURN_TO) state.returnTo = process.env.AUTH0_RETURN_TO
  return session
}

export default handleAuth({
  async callback(req, res) {
    try {
      await handleCallback(req, res, { afterCallback })
    } catch (error) {
      res.status(error.status || 500).end(error.message)
    }
  },
})
```

### Auth0 Setup

The Auth0 application setup:
- Newly created with the nextjs template
- Application Type: Regular Web Application
- Token Endpoint Authentication Method: None
- Allowed Callback URLs are set: `https://[MY_DOMAIN]/api/auth/callback` and `https://[MY_DOMAIN]/[PAGE_TO_REDIRECT_AFTER_LOGIN]`
- Allowed Logout URLs are set: `https://[MY_DOMAIN]/` and `https://[MY_DOMAIN]/[PAGE_TO_REDIRECT_AFTER_LOGOUT]`
- Refresh Token Rotation: Off
- Refresh Token Expiration: Off
- OAuth - JWT Signature Algo: RS256
- OIDC Conformant: On
- Grant Types: Implicit, Authorization Code, Refresh Token

- Connection: Simple Username-Password-Authentication with a test user
- No Organization set
- Auth0 Management API is not authorized
- Authentication / Database / 'Try Connection' works with the test user

- User is verified
- Authorized the application
- Have the permissions: openid, profile, email

- I use Universal login
- No custom domain

### Reproduction

1. Run nextjs project locally (`next dev`)
2. Navigate to login 
3. Authenticate with Username/Password
4. Arrive back to page accessible only to authenticated users
5. Note success locally
6. Deploy same project to Netlify as a deploy preview
7. Set the same envvars as locally but in the Netlify admin 
8. Navigate to login
9. Submit Username/Password in login form
10. Witness `access_denied (Unauthorized)` on `/api/auth/callback?code=IC.....WH-&state=ey.....n0`

### Environment

- **Version of this library used:** nextjs-auth0 v1.3.1,
- **Version of the platform or framework used, if applicable:** Node v12.22.1, next: 10.0.6, next-on-netlify v2.8.7,  
- **Other relevant versions (language, server software, OS, browser):** Deployed to Netlify (the main project works perfectly both in deploy preview and production)

**Comment by kress92cs** [comment]
Hello endofu :) 

I was wondering if this could be the same problem we have with set cookies and malformed cookies on the same request as you have " 10. Witness access_denied (Unauthorized) on /api/auth/callback?code=IC.....WH-&state=ey.....n0"

You check the request under cookies and see if you have an malformed cookies under /api/auth/callback?code=IC.....WH-&state=ey.....n0".

If this is the case i can provide maybe more clarity on this issue instead of reporting another issue that might be the same.

We are also using nextjs-auth0 v1.3.1

**Comment by endofu** [comment]
Thank you for your response, @kress92cs !

If I check the `headers` and `rawHeaders` in the logs of `handleAuth` they look similar and decent.

The one inside the Netlify function is:
```
cookie: 'nonce=EvXxKxp-LUuavTXxC9SbSyNAo0h_-yIh6DsM5QmeeP0.AIU34Bu8lHFqjbpRHFXXX0SXNfBqxca_OmOsVb3U; state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vZGVwbG95LXByZXZpZXctOTgtLXRvbS1ob2xrZW5bXXXnLm5ldGxpZnkuYXBwIn0.EQvHY3g6o16_Nsx5p2_MTp4mQdof19fUJF5cRE450XU; code_verifier=GoBEawNupKVHoeKh-2tNoBeGPAaNjPEK8c6A_5M2Khk.1Fytp_VirbDLGN2pJvaQyOXXXOpyDrYHzAK2We7uM'
```

while the working version on the dev server:
```
cookie: 'nonce=aKbna_RwjvxgZqPuKbfSilZ2AeMkmp0Bu0XIPIVFMqs.sTcyaF87zBOmKHZio4xXXXbenJbcYYR2ecXREdVdbP4; state=eyJyZXR1cm5UbyI6Imh0dHA6Ly8wLjAuMC4wOjMwMDAifQ.sV8N_Rq6VY-BQm8g-F4gXXXWudM6qrvjJlvVmb_rXjLs; code_verifier=EocFaVcYi8p9N3F79LB0_r5M_y9YkqIj5eIsTEmNqz4.A46qffV_ds5kg_jWcq7PAUXXXyBm0DRvKlocvktWeAA'
```

What is more suspicious to me is that Netlify forwards the request internally because there are a lot more headers there

```
headers: {
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'accept-encoding': 'br, gzip',
    'accept-language': 'en-GB,en;q=0.9',
    'cache-control': 'max-age=0',
    'client-ip': '100.64.0.123',
    cookie: 'nonce=EvXxKxp-LUuavTXxC9SbSyNAo0h_-yIh6DsM5QmeeP0.AIU34Bu8lHFqjbpRHFXXX0SXNfBqxca_OmOsVb3U; state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vZGVwbG95LXByZXZpZXctOTgtLXRvbS1ob2xrZW5bXXXnLm5ldGxpZnkuYXBwIn0.EQvHY3g6o16_Nsx5p2_MTp4mQdof19fUJF5cRE450XU; code_verifier=GoBEawNupKVHoeKh-2tNoBeGPAaNjPEK8c6A_5M2Khk.1Fytp_VirbDLGN2pJvaQyOXXXOpyDrYHzAK2We7uM'
    dnt: '1',
    forwarded: 'for="[2a02:a210:420:ea00:f47d:7ed6:46e2:fc]";proto=https',
    'sec-ch-ua': '"Chromium";v="90", "Opera";v="76", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'cross-site',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 OPR/76.0.4017.177',
    via: 'http/1.1 Netlify[d1decd17-2da5-4e80-8ca7-a0xxx571497e] (Netlify Edge Server)',
    'x-bb-ab': '0.184601',
    'x-bb-client-request-uuid': '64454781-46c2-4a1e-bb36-f0001a1f892c',
    'x-bb-ip': '2a02:a210:420:ea00:f47d:7ed6:46e2:fc',
    'x-bb-loop': '1',
    'x-country': 'NL',
    'x-datadog-parent-id': '141866343258812345678',
    'x-datadog-trace-id': '17685301258835123456',
    'x-forwarded-for': '2a02:a210:420:ea00:f47d:7ed6:ffff:fc, 100.64.0.123',
    'x-forwarded-proto': 'https',
    'x-language': 'en,en;q=0.9',
    'x-nf-cache-gen': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9Cg.eyJnZW4iOiI2MGJlYjBjNmE1ZDhhODAwMDhhMmE3ODU6MTYyMzExMDM0NDE0OSJ9Cg.ES0tWed_vDs6625VRfcRFUe6cKS8IS31q4HbUHPAVus',
    'x-nf-client-connection-ip': '2a02:a210:420:ea00:f47d:7ed6:ffff:fc',
    'x-nf-connection-proto': 'https',
    'x-nf-request-id': '64454781-46c2-4a1e-ffff-f4841a1f892c',
    host: 'deploy-preview-98--t...g.netlify.app',
    'x-forwarded-host': 'deploy-preview-98--t...g.netlify.app'
  },
```

Do I have to set the Auth0 application's `Allowed Web Origins` or `Allowed Origins (CORS)`?

**Comment by endofu** [comment]
I've added every reasonable domain to these but it didn't fix it.

**Comment by endofu** [comment]
Worked it out finally 😅 

It was nothing fancy, just an 'innocent' envvar manipulation in the Netlify build script that tried to create the envvars from the deploy url but somehow made the `AUTH0_BASE_URL` broken in a weird way so it was wrong in function build time but correct when the handler was running. 

Developper error par excellence.
