### ISSUE TITLE
GraphQL Example

### ISSUE THREAD

**Issue by blazestudios23** [auth0/nextjs-auth0#412]
### Describe the problem you'd like to have solved

I trying to use the latest version of nextjs-auth0, there are many examples out there use of using GrpahQL with an older version of this library but I could find none for the recent version which introduced breaking changes. 

### Describe the ideal solution

That a GraphQL example is provided. 

## Alternatives and current work-arounds

Show how to add the auth data to Apollo client so it can be passed to the backend. 

### Additional information, if any

Show a complete example with GraphQL would be helpful to many people

**Comment by Widcket** [comment]
Hi @blazestudios23, thanks for raising this. To use Apollo, you can create an API route that is protected by the Auth0 SDK with [withAPIAuthRequired](https://auth0.github.io/nextjs-auth0/modules/helpers_with_api_auth_required.html), and then use that API route to proxy the requests from the frontend to Hasura. This avoids exposing the Access Token to the frontend, where it could be stolen via XSS.
This comment may be helpful: https://github.com/auth0/nextjs-auth0/issues/277#issuecomment-777875982

**Comment by acomito** [comment]
@Widcket is there no way to get the token on the frontend to avoid having to proxy?

**Comment by Widcket** [comment]
@acomito check out https://github.com/auth0/nextjs-auth0/issues/348#issuecomment-808166458

**Comment by adamjmcgrath** [comment]
@acomito - #348 should answer your question, closing - feel free to ping me if you'd like to reopen
