### ISSUE TITLE
Redirect when User doesn't consent to Facebook app

### ISSUE THREAD

**Issue by tnolan8** [auth0/nextjs-auth0#413]
### Description
When a User doesn't consent to App on Facebook, redirect to `/api/callback` breaks.

### Reproduction
I've enabled login through Facebook for my NextJS application. I initialise nextjs-auth0 as follows:
```javascript
initAuth0({
    mustAcceptTerms: true,
    domain: process.env.AUTH0_DOMAIN,
    clientId: process.env.AUTH0_CLIENT_ID,
    clientSecret: process.env.AUTH0_CLIENT_SECRET,
    scope: "openid profile email",
    redirectUri: process.env.AUTH0_CALLBACK,
    audience: `${process.env.NEXT_PUBLIC_API_URL
      ? process.env.NEXT_PUBLIC_API_URL
      : "http://localhost:3001/graphql"
      }`,
    postLogoutRedirectUri: process.env.AUTH0_LOGOUT,
    session: {
      cookieSecret: process.env.AUTH0_COOKIE_SECRET,
      cookieLifetime: 60 * 60 * 168,
      storeIdToken: true,
      storeAccessToken: true,
      storeRefreshToken: true,
    },
    oidcClient: {
      httpTimeout: 2500,
      clockTolerance: 10000,
    }
    ,
    additionalSignUpFields: [{
      name: "Display Name",
      placeholder: "Display Name",
      prefill: "Display Name",
      validator: function (name) {
        return {
          valid: name.length >= 5,
        };
      }
    },
    ]
  });
```
I then have separate API routes for login and callback i.e. `/api/login.js` and `/api/callback.js`. The login route just calls the `handleLogin()` function and the callback route calls `handleCallback()`. When creating an app on Facebook to use with Auth0 you're able to provide a _Deauthorize Callback URL_ which should be used when the User doesn't consent to the app. However when a user hits cancel on the Facebook consent form I get redirect to `/api/callback` which then throws a `access_denied (Permissions error)`. How can I go about setting this up so that if they don't consent they just get redirect back to the home page of the app?

### Environment
- **0.15.0** (I'm aware I'm using quite an old version of the module)
![Screenshot 2021-06-09 at 15 30 00](https://user-images.githubusercontent.com/11179798/121374202-9c717e80-c937-11eb-8d0a-cf5d86c23475.png)

![Screenshot 2021-06-09 at 15 30 59](https://user-images.githubusercontent.com/11179798/121374302-b317d580-c937-11eb-8d0c-963eb3ee4e0b.png)

**Comment by Widcket** [comment]
Hi @tnolan, thanks for raising this. You'll need to catch the error on the callback handler, and then [redirect](https://nextjs.org/docs/api-routes/response-helpers) to the home page.

**Comment by Widcket** [comment]
@tnolan8 seems like your issue is solved. I'll close this for now, please ping if you'd like to reopen.
