### ISSUE TITLE
Custom Domain issue when using same emails for the sign up process

### ISSUE THREAD

**Issue by dpramani** [auth0/nextjs-auth0#414]
Hi,

I have custom domain installed for my tenant, which works fine excluding certain scenarios.

Example scenario: 

1. I have created an account with say test@gmail.com, via google sign in.
2. Now, I log out of my application (but I am still signed in with that email inside google chrome).
3. Now, I use that email to do a normal sign up, which will send me a verification email, when I click the verification link in the email, I get redirected to the old domain/tenant name and since its not there (As I have the new custom domain set inside AUTH0_ISSUER_BASE_URL), I see an unauthorized message.

Also if I revert back to the old tenant domain(inside AUTH0_ISSUER_BASE_URL), the above flow works.
Also after getting redirected if, I manually replace the old domain with the custom domain, and refresh the page, it works.

I have followed auth0 docs, in setting up the custom domain.

Not sure what's going on.

Thanks
Debabrata Pramanik

**Comment by Widcket** [comment]
Hi @dpramani, thanks for raising this. Do you have **Use Custom Domain in Emails** enabled in your Auth0 tenant? It's under Branding > Custom Domains.

**Comment by dpramani** [comment]
Hi @Widcket Thanks for replying. Yes I have that toggle turned on. As I said if we log out of chrome before resigning again with the same email.  Then the verification link redirects me to the new domain. But if I am signed in into chrome and I try to sign up and click the verification link, it takes me to the old custom domain.

**Comment by Widcket** [comment]
@dpramani I just tested the following:
- Set up `AUTH0_ISSUER_BASE_URL` to my custom domain
<img width="429" alt="Screen Shot 2021-06-11 at 07 17 35" src="https://user-images.githubusercontent.com/5055789/121672233-f1bba600-ca85-11eb-9c71-e20adadfb0b4.png">

- Log in with a Google account
- Log out of the app, but stay logged in into Google
- Sign up with that same email
- Click the email verification link

<img width="608" alt="Screen Shot 2021-06-11 at 07 15 33" src="https://user-images.githubusercontent.com/5055789/121672293-026c1c00-ca86-11eb-93aa-1ec53aa8b0a8.png">

<img width="494" alt="Screen Shot 2021-06-11 at 07 14 46" src="https://user-images.githubusercontent.com/5055789/121672316-08fa9380-ca86-11eb-9bb1-38b2dc3ab4c4.png">

Are you able to reproduce this with the sample apps included [in the repo](https://github.com/auth0/nextjs-auth0/tree/main/examples)?

**Comment by dpramani** [comment]
@Widcket Thanks for testing this. I will go through this and come back to you in a bit.

**Comment by dpramani** [comment]
@Widcket So I have tested the sample apps, which works perfectly fine. Earlier, we were using a rule for auth0-account-linking-extension, which had some traces of the old domain. Maybe that was the problem. Since we are not using it right now, turning that off solved the issue. Thanks for helping me solve this.

**Comment by Widcket** [comment]
Glad you could find the cause.
