### ISSUE TITLE
Getting a syntax error on Internet Explorer 11

### ISSUE THREAD

**Issue by bchurlinov** [auth0/nextjs-auth0#415]
### Description

I am getting a syntax error on Internet Explorer 11.

IE complains that this is causing the issue:
const useConfig = () => react_1.useContext(Config);

This is located in "/node_modules/@auth0/nextjs-auth0/dist/frontend/use-config.js"

### Environment
- **"@auth0/nextjs-auth0": "1.3.1"**
- **"next": "10.2.3"**

**Comment by Widcket** [comment]
Hi @bchurlinov, thanks for raising this. Can you reproduce this using the sample apps [we have on the repo](https://github.com/auth0/nextjs-auth0/tree/main/examples)? This will help rule out a build config issue on your app.

**Comment by bchurlinov** [comment]
Hi @Widcket, thanks a lot for your reply. I downloaded the "basic-example" by using the same next, react and react-dom versions as you do ("next": "^10.0.5", "react": "^17.0.1", "react-dom": "^17.0.1") and I still got the same error as up above when using IE11.

I also tried using the following ( that matches my versions of the dependencies I use), and I am getting exactly the same:

    @auth0/nextjs-auth0": "1.3.1",
    "axios": "0.21.1",
    "cookies": "0.8.0",
    "formik": "2.2.6",
    "jwt-decode": "3.1.2",
    "lodash": "4.17.20",
    "next": "10.2.3",
    "next-seo": "4.22.0",
    "nextjs-cors": "1.0.5",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-pin-field": "1.1.0",
    "sass": "1.32.8",
    "swr": "0.4.0",
    "typescript": "4.1.3",
    "yup": "0.32.9",
    "zustand": "3.5.1"
