### ISSUE TITLE
Hosting via Vercel not working because of AUTH0_BASE_URL.

### ISSUE THREAD

**Issue by mathieutu** [auth0/nextjs-auth0#417]
### Description

Hi, I would like to reopen https://github.com/auth0/nextjs-auth0/issues/383, as https://github.com/auth0/nextjs-auth0/pull/404 did not fix the problem, as you can see in the last comments of https://github.com/auth0/nextjs-auth0/issues/383. 

The documentation at https://github.com/auth0/nextjs-auth0/blob/main/examples/README.md#assigning-the-auth0_base_url seems wrong to me, as the `env` key in config and the webpack `DefinePlugin` don't work for files in node_module, which are not touched by webpack.

Moreover, on a Vercel side, the VERCEL_URL reference the "by commit domain", and not the "by PR domain", so we can't use auth0 with the standard PR domain.

We have to figure out another way to do this.

Any thoughts about this?

Thanks.

### Environment

- **Version of this library used:** v1.4.0
- **Version of the platform or framework used, if applicable:** Next 10.2.3 with Vercel

**Comment by adamjmcgrath** [comment]
Thanks for raising this @mathieutu 

> The documentation at https://github.com/auth0/nextjs-auth0/blob/main/examples/README.md#assigning-the-auth0_base_url seems wrong to me, as the env key in config and the webpack DefinePlugin don't work for files in node_module, which are not touched by webpack.

Are you sure? I've just set `AUTH0_BASE_URL` in `next.config.js` in the [example app](https://github.com/auth0/nextjs-auth0/tree/main/examples/kitchen-sink-example), eg

```js
module.exports = {
  env: {
    AUTH0_BASE_URL: 'foobarbaz'
  }
};
```

Then run `npm run build` and confirmed that `process.env.AUTH0_BASE_URL` was replaced in the `.next` output folder:

```
// examples/kitchen-sink-example/.next/server/chunks/872.js
...
const AUTH0_BASE_URL = "foobarbaz";
...
```

It also seems to work fine in the app when deployed to Vercel https://nextjs-auth0-acm8cej7z-auth0.vercel.app/

**Comment by mathieutu** [comment]
Hum. It's weird, I had the opposite conclusions with previous same tests. 
I'll double check that. 🤔

**Comment by tusbar** [comment]
I can confirm that the fix does not work.

I have the following entry in the `env` section of my `next.config.js`:

```js
AUTH0_BASE_URL: process.env.AUTH0_BASE_URL ?? process.env.VERCEL_URL ?? 'http://localhost:4000',
```

When my app using `VERCEL_URL=localhost:4000 yarn next start -p 4000` and navigating to the api/auth/login route, the joi validation fails with: `TypeError: "baseURL" is required`.

`getConfig` from nextjs-auth does not retrieve the environment variable value: in `dist/config.js`, `AUTH0_BASE_URL` is undefined, so `baseURL` is too.

**Comment by adamjmcgrath** [comment]
Hi @tusbar `env` variables in `next.config.js` will be [replaced at build time](https://nextjs.org/docs/api-reference/next.config.js/environment-variables) (`next build`) and it looks like you're expecting them to be replaced at boot time (`next start`)

**Comment by tusbar** [comment]
The app was built with `VERCEL_URL=localhost:4000` as well.

**Comment by adamjmcgrath** [comment]
@mathieutu - are you still having an issue with this?

@tusbar - I'm not able to reproduce that in the example app (see https://github.com/auth0/nextjs-auth0/issues/417#issuecomment-860649109), are you using the latest version of the SDK? If so, feel free to provide a simple reproducable example and I'd be happy to debug it for you.

**Comment by tusbar** [comment]
The issue is that `process.env.AUTH0_BASE_URL` will not be replaced within the SDK, and the configuration validation will fail at runtime.

Here’s a basic example: https://github.com/tusbar/nextjs-auth0-repro

All I did was export a getServerSideProps in pages/index.js

```js
export const getServerSideProps = withPageAuthRequired({
  getServerSideProps: () => ({
    value: 'foo'
  })
})
```

**Comment by adamjmcgrath** [comment]
Ah, ok - thanks for sharing that example repo @tusbar. It looks like the example app was working differently because it was [installing the SDK from a relative path](https://github.com/auth0/nextjs-auth0/blob/main/examples/kitchen-sink-example/package.json#L37) 

I'll come up with a different way to resolve #383

**Comment by blazestudios23** [comment]
I too can confirm this problem does exist.

**Comment by adamjmcgrath** [comment]
The [original guidance](https://github.com/vercel/next.js/discussions/15424#discussioncomment-41284) to this - before Vercel added the "set a reference to a System Environment Variable" feature (which they've now removed). Was to check in a `.env.production` file that aliased `VERCEL_URL` to the env variable you wanted to alias it to (in this case `AUTH0_BASE_URL`)

So something like this should work:

```shell
# .env.production
AUTH0_BASE_URL=${VERCEL_URL}
```

> Moreover, on a Vercel side, the VERCEL_URL reference the "by commit domain", and not the "by PR domain", so we can't use auth0 with the standard PR domain.

I assume you mean:

"by commit domain" eg. `${VERCEL_GIT_REPO_SLUG}-${Commit short sha}-${VERCEL_GIT_REPO_OWNER}.vercel.app`
"by PR domain" eg. `${VERCEL_GIT_REPO_SLUG}-${VERCEL_GIT_COMMIT_REF}-${VERCEL_GIT_REPO_OWNER}.vercel.app`

So using the above example for the "PR domain", it would be

```shell
# .env.production
AUTH0_BASE_URL=${VERCEL_GIT_REPO_SLUG}-${VERCEL_GIT_COMMIT_REF}-${VERCEL_GIT_REPO_OWNER}.vercel.app
```

I'd rather not rely on checking in production env files because it might encourage users to check in secrets, but this should be a working solution for now - let me know.

There are some requests for this to work on both Vercel preview urls (the one with the commit sha and the one with the branch name) simultaneously, which would require configuring the SDK based on the `request.headers['host']` at request time - for which there is a suggested solution here https://github.com/auth0/nextjs-auth0/issues/108#issuecomment-800059278 - I wouldn't rely on `request.headers['host']` in the SDK for security and reliability (behind proxy's for example) reasons and would encourage you to use a single preview url format if you can.

**Comment by sioquim** [comment]
Managed to sort this issue by overriding Vercel's Build Command

```
AUTH0_BASE_URL="$VERCEL_URL" yarn build
```

**Comment by adamjmcgrath** [comment]
Thanks @sioquim 

> But still not sure how to make PR Domains work.

Would this work?
`AUTH0_BASE_URL="$VERCEL_GIT_REPO_SLUG-$VERCEL_GIT_COMMIT_REF-$VERCEL_GIT_REPO_OWNER.vercel.app" yarn build`

**Comment by sioquim** [comment]
> Would this work?
AUTH0_BASE_URL="$VERCEL_GIT_REPO_SLUG-$VERCEL_GIT_COMMIT_REF-$VERCEL_GIT_REPO_OWNER.vercel.app" yarn build

@adamauth yes, it would but it needs to dynamically use `$VERCEL_URL` for production and  switch to the PR url for others. 

So this one might do the job for my use-case:

```
`[ "$VERCEL_ENV" = production ] && AUTH0_BASE_URL = "$VERCEL_URL" || AUTH0_BASE_URL = "$VERCEL_GIT_REPO_SLUG-$VERCEL_GIT_COMMIT_REF-$VERCEL_GIT_REPO_OWNER.vercel.app" yarn build
```

**Comment by sioquim** [comment]
> Would this work?
AUTH0_BASE_URL="$VERCEL_GIT_REPO_SLUG-$VERCEL_GIT_COMMIT_REF-$VERCEL_GIT_REPO_OWNER.vercel.app" yarn build

@adamauth yes, it would but it needs to dynamically use `$VERCEL_URL` for production and  switch to the PR url for others. 

So this one might do the job for my use-case:

```
[ "$VERCEL_ENV" = production ] && AUTH0_BASE_URL="$VERCEL_URL" || AUTH0_BASE_URL="$VERCEL_GIT_REPO_SLUG-$VERCEL_GIT_COMMIT_REF-$VERCEL_GIT_REPO_OWNER.vercel.app" yarn build
```

**Comment by adamjmcgrath** [comment]
ok, thanks @sioquim - I'm going to test that out on the example app and update the guidance if it works

**Comment by mikestopcontinues** [comment]
I'd really like the `next.config.js` config to work, but I'm not crazy about the alternatives offered here. The easiest way seems to be to create a new instance of the sdk, where your env vars will work exactly as you expect:

```js
const sdk = auth0init({baseURL: process.env.AUTH0_BASE_URL});
```

Honestly, I think recommending bash conditionals in the docs would seem a little too messy for a lot of users. Isn't it better to focus on the new instance approach?

Here's a selection from my `next.config.js` to show what it seems to take to get Next deploy with custom domains working alongside PR deploys. This isn't the kind of logic you'd want to tell users to include in a bash script.

```js

// resolve actual url for current deploy...

const baseUrl = `https://${process.env.BASE_URL}`.replace(/^(https?:\/\/){2}/, '$1');

const branchUrl = {
  master: `https://app.example.com`,
  release: `https://app.release.example.com`,
  preview: `https://app.preview.example.com`,
}[process.env.VERCEL_GIT_COMMIT_REF];

const AUTH0_BASE_URL = isVercelDev ? baseUrl : branchUrl ?? baseUrl;

// next config...

module.exports = {env: {AUTH0_BASE_URL}};
```

**Comment by XavierChanth** [comment]
This is my solution to the problem:
```JS
// services/auth0.js

import { initAuth0 } from '@auth0/nextjs-auth0';

export default initAuth0();
```

Create a singleton and let it load the environment variables. 
Also to note, I used Vercel's environment variables page to load my environment for the app.
(and .env.local on my development PC)

**Comment by mikestopcontinues** [comment]
@XavierChanth Does that really pick up your env vars? I get a `baseURL` error if I try that while passing `{env: {AUTH0_BASE_URL}}` in my `next.config.js`.

**Comment by XavierChanth** [comment]
I used the gui page on vercel to set my vars

**Comment by XavierChanth** [comment]
I'm not sure if the next config will work, but I also import this file instead of '@auth0/nextjs-auth0' when I need an auth0 function.
eg.
```JS
import { getSession } from 'path/to/custom/auth0';
// instead of
import { getSession } from '@auth0/nextjs-auth0';
```

**Comment by blazestudios23** [comment]
In vercel you can set ENV varsity for each branch. I just see the URLs there. Much better solution in my opinion.

Best Andrew

**Comment by mikestopcontinues** [comment]
Not sure I understand @blazestudios23. You can definitely set an env var to have different values for dev/preview/prod, but the preview env vars fans out into numerous domains. All of the `*.vercel.app` domains AND any custom domains that aren't attached to your master branch. In this case, I have two: `preview.example.com` and `release.example.com`. Remember, you also can't use the `VERCEL_GIT_COMMIT_REF` to infer these values, because a branch like `dev/new-feature` will get a `vercel.app` domain, not `dev.new-feature.example.com`. 

If you have a way to systematize it, believe me, I'm all ears.

**Comment by blazestudios23** [comment]
Just use NEXT_PUBLIC_VERCEL_URL then set it for dev, prof and any other branch you want to assign your own URL to.

Best Andrew

**Comment by XavierChanth** [comment]
> Just use NEXT_PUBLIC_VERCEL_URL then set it for dev, prof and any other branch you want to assign your own URL. https://vercel.com/docs/environment-variables That env can be overwritten. And you can choose which branch you want to assign an env var to, by clicking and preview and then selecting a branch from GitHub. Best Andrew

Yes, you can do it this way too, just be sure to pass it in as an argument when creating the initAuth0 instance.

**Comment by mikestopcontinues** [comment]
@blazestudios23 Ahh, neat! Thanks!

**Comment by adamjmcgrath** [comment]
> Managed to have a work-around for this issue by overriding Vercel's Build Command
> AUTH0_BASE_URL="$VERCEL_URL" yarn build

@sioquim - I've been testing this and assiging `AUTH0_BASE_URL="$VERCEL_URL" npm build` for the build command doesn't work because it only provides the `AUTH0_BASE_URL` during the Build Step _not_ during Serverless Function execution when it's required by the SDK. Am I missing something?

**Comment by tusbar** [comment]
I can confirm that committing a `.env.production` with the following works.

```env
# .env.production
AUTH0_BASE_URL=${VERCEL_URL}
```

Also, specifying `AUTH0_BASE_URL` for your production domain in the Vercel environment config (through GUI or CLI) will properly override what’s defined in the `.env.production` file.

**Comment by sioquim** [comment]
>  I've been testing this and assiging `AUTH0_BASE_URL` for the build command (`AUTH0_BASE_URL="$VERCEL_URL" npm build`) doesn't work because it only provides the `AUTH0_BASE_URL` during the Build Step _not_ during Serverless Function execution when it's required by the SDK. Am I missing something?

@adamjmcgrath - Okay, then my setup could be wrong then.

I forgot to mention that my next.config.js has this:
```
env: {
    AUTH0_BASE_URL: process.env.AUTH0_BASE_URL
  },
```

But my previews and production deployments are working properly after injecting the env vars on my build command. However, like what you said - it won't run properly on my serverless functions.

**Comment by rossamurphy** [comment]
Hi there, is anyone at auth0 working on a fix for this?

**Comment by adamjmcgrath** [comment]
Hi @rossamurphy - could you raise a new issue, with steps to reproduce, if you think the [instructions for deploying to vercel](https://github.com/auth0/nextjs-auth0/tree/main/examples#hosting-on-vercel) are incorrect.

**Comment by ADTC** [comment]
Note: [New URL for the instructions for deploying to Vercel.](https://github.com/auth0/nextjs-auth0/blob/main/example-app/README.md#hosting-on-vercel)
