### ISSUE TITLE
Allow redirecting directly to social provider

### ISSUE THREAD

**Issue by bahdcoder** [auth0/nextjs-auth0#421]
### Describe the problem you'd like to have solved

At the moment, there seems to be no way to redirect a user directly to a social connection. It would be great to have a `Sign in with Google` button that goes directly to the social provider, completely skipping the universal login screen. 

### Describe the ideal solution

A possible solution would be to accept route parameters at the login/register endpoints: `/api/auth/login?connection=google-oauth2` would be awesome.

## Alternatives and current work-arounds
No workarounds at the moment. Just redirecting to universal page all the time.

**Comment by adamjmcgrath** [comment]
Hi @bahdcoder 

Have a look at the [Customize Handlers example](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#customize-handlers-behavior).

It shows you how to pass custom params to the login endpoint, you can use this to pass the `connection` parameter.

Closing - feel free to ping me if you'd like to reopen

**Comment by darcy-vitacca** [comment]
@adamjmcgrath I can't seem to get the solution above to work I've tried passing in twitter like this just for testing purposes. Am I missing something?
  async login(req, res) {
    try {
      console.log('req', req);
      await handleLogin(req, res, {
        authorizationParams: {
          connection: 'twitter',
        },
      });
    } catch (error) {
      res.status(error.status || 400).end(error.message);
    }
  },
});
The use case I'm trying to cover is if they auth with another provider or make an account and they want to use the twitter integration of my site they need to auth that and link the accounts. Right now I'm just checking through their auth0 identities and looking for a twitter connection and if not trying the above solution.  If you can think of a better idea or if I'm on the right track I'd appreciate some help.

**Comment by adamjmcgrath** [comment]
@darcy-vitacca - the code you've shared looks correct

Assuming you have a Twitter Social Connection enabled for your Auth0 application, passing `?connection=twitter` to the authorize url should redirect the user directly to Twitter.

**Comment by darcy-vitacca** [comment]
@adamjmcgrath It did work after signing out and signing back in. Is there any way to be logged into an account eg an auth0 sign up through the universal login. Then authorise a twitter account while logged into the auth0 account to post on behalf of the user to twitter. Then in turn have them added to the linked users so the we don't to have to keep authorising through I'm guessing linkUser().

**Comment by adamjmcgrath** [comment]
Hi @darcy-vitacca - this is not supported by this SDK,  but by Auth0 through the [Account Link Extension](https://auth0.com/docs/customize/extensions/account-link-extension)

**Comment by darcy-vitacca** [comment]
@adamjmcgrath Thanks for getting back to me so quickly, I have looked at that but I only wanted to trigger the flow when they land on the Twitter section of my web app and not on login. I don't want to have to authorise them if they don't want to use that feature and only want to use the linkedin section for example. For the moment I wil use a Twitter login as that's the only section that's created but would love to hear if what I want is possible.
