### ISSUE TITLE
Next.js Vercel access_denied (unauthorized)

### ISSUE THREAD

**Issue by blazestudios23** [auth0/nextjs-auth0#423]
Using:

```
“@auth0/nextjs-auth0”: “1.3.1”,
“next”: “latest”,
“react”: “17.0.2”,
“react-dom”: “17.0.2”,
“typescript”: “^4.3.3”
```

This is running on node 14.

my directory is pages/api/auth/[…auth0].ts

```
[…auth0].ts contains:

import { handleAuth } from '@auth0/nextjs-auth0';

```
export default handleAuth();
After signing on with google or twitter, it returns to the https://domain/api/auth/callback
and I get the following error message:

access_denied (Unauthorized)

I do not get that error in my local environment, everything works there. I am hosting with Vercel and get this error in that hosting environment. It’s possible that there is some kind of .env secret that is miss configured. Or that the server less function calling this is not passing something correctly to Auth0.

I really need some help on this, so any advice is greatly appreciated.

**Comment by Widcket** [comment]
Hi @blazestudios23, thanks for raising this. Is `AUTH0_BASE_URL` pointing to your prod URL? Do you have any custom domain set up? If so, is `AUTH0_ISSUER_BASE_URL` pointing to your custom domain?

**Comment by blazestudios23** [comment]
I found the issue. I had:

AUTH0_SCOPE= "openid email profile" 

in Vercel. 

Changing it to:

AUTH0_SCOPE=openid email profile

Fixed the problem.

**Comment by Widcket** [comment]
Glad you were able to find the cause.
