### ISSUE TITLE
Allow session refresh to use auth0 flow actions

### ISSUE THREAD

**Issue by Paliao** [auth0/nextjs-auth0#424]
### Describe the problem you'd like to have solved

Hey, first of all, thanks for the lib! Hope you'll be able to help me!

I have important info that's stored at the app_metadata of the user, and I would like to update it, get a new token with this info on it, and use this token to handle the auth with 2 third-party APIs that uses the session OpenID token **with this updated info on it**.

I'm using a custom scope + auth0 actions(Login flow), which works correctly already:
<img src="https://user-images.githubusercontent.com/29801405/122998743-d143f380-d383-11eb-9004-0dfe90b4af5b.png" height="400px" />

I can modify the metadata, but I can't get this info from the token unless I log in again!

## Alternatives and current workarounds
Besides my currently solution with a custom claim, I have also tried to:

##### Normalize the profile with auth0 rules:

<img src="https://user-images.githubusercontent.com/29801405/122999929-3a783680-d385-11eb-875e-0abc971b27aa.png"  />

##### Use the handleProfile with the refetch option in: 
`
auth0.handleProfile(req, res, { refetch: true })
`

##### Call again handleLogin with the prompt option:
`
auth0.handleLogin(req, res, { authorizationParams: { prompt: 'none' } });
`

##### To logout and login silently but the redirect of the handleLogout  doesn't allow me
`
 auth0.handleLogout(req, res, { returnTo: false });
auth0.handleLogin(req, res, { authorizationParams: { prompt: 'none' } });
`

My issue seems to be that the session idToken is issued only during the login! And I didn't found any way to handle a refresh of it through the lib methods

### Describe the ideal solution
I only thought of 2 solutions for my problem

#### Handle profile can issue this token with a "refetchSession" option
`
auth0.handleProfile(req, res, { refetch: true, refetchSession: true })
`

#### A new method/route to handle this
`
auth0.renewSesssion(req, res)
`

**Comment by Widcket** [comment]
Hi @Paliao, thanks for raising this. I just tested the following:
- Call `handleProfile` with `refetch: true`
- Create a rule with `context.idToken['http://custom-claim'] = context.clientMetadata;`
- Lower the token expiration to a few secs
- Login
- Check profile
- Add a new app metadata key/value pair
- Wait until refresh token exchange
- Check profile -> is updated

Can you please try the above?

**Comment by Paliao** [comment]
Hi @Widcket, thanks for the quick response!

I followed your instructions and found some odd behavior, and I'm not so sure if it's some misconfiguration on my part

I'll list all my important configurations below:

#### Auth0
- I have configured a **regular web application**
- The **Token Endpoint Authentication Method** is: `none`
- The **ID Token Expiration** is set to 60s
- The refresh token rotation is toggled
- The reuse interval is set to 60s too
- The JWT algorithm is: `RS256`

#### initAuth0 config
````
{
  secret: process.env.AUTH0_SECRET,
  issuerBaseURL: process.env.AUTH0_ISSUER_BASE_URL,
  baseURL: process.env.AUTH0_BASE_URL,
  clientID: process.env.AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET,
  authorizationParams: {
    scope: process.env.AUTH0_SCOPE,
  },
  session: {
    name: process.env.AUTH0_SESSION_NAME,
  },
  routes: {
    callback: '/api/auth/login',
    postLogoutRedirect: '/',
  },
}
````

#### Auth0 rule 
`````
function (user, context, callback) {
  const appMetadata = user.app_metadata;
  
  if(appMetadata && appMetadata.organizations) {
     context.idToken[configuration.namespace] = {};
	   context.idToken[configuration.namespace].other = appMetadata;
  }
  
  return callback(null, user, context);
}
`````

#### Current /auth/me route
``````
import { NextApiRequest, NextApiResponse } from 'next';
import auth0 from 'utils/auth0';

export default async function me(req: NextApiRequest, res: NextApiResponse) {
  try {
    await auth0.handleProfile(req, res, { refetch: true  });
  } catch(error) {
    // Code here
  }
}
``````
++

**Comment by Paliao** [comment]
I done scenarios

#### Scenario #1

**Comment by Paliao** [comment]
Sorry, for the issue thing, missclick :/

I've done some scenarios to understand what could it be, and found a behavior that I don't understand

### Scenario 1
- Login
- IdToken with expiration time of 60s
- Wait for 60s
- Call **/auth/me**
- The same idToken returns from the route

#### Expected behavior
- A new token should be issued(?)


### Scenario 2
- Login
- Make a change in the user name through auth0 dashboard
- Call **/auth/me**
- The user profile returns updated, with the new name and the updated time from now
- My idToken still the same

### Scenario 3
- Login
- Make a change in the **app_metadata** through auth0 dashboard
- Call **/auth/me**
- The user profile and the custom claim still the same too

#### Expected behavior
- The custom claim and the update_at field should've been updated
- The idToken were supposed to change too?

**Comment by Widcket** [comment]
@Paliao I see in your rule you're using `user.app_metadata` as the source of app metadata. You should use `context.clientMetadata`:

<img width="896" alt="Screen Shot 2021-06-24 at 09 50 58" src="https://user-images.githubusercontent.com/5055789/123266322-44f41680-d4d2-11eb-88ad-426a59aaf63a.png">

Check in your tenant logs that the refresh token exchange is taking place. When the refresh token happens, the rule will run and add the app metadata contents under a custom claim. Then after that, it should be available in the user profile provided by the Next.js SDK.

<img width="1018" alt="Screen Shot 2021-06-24 at 09 57 55" src="https://user-images.githubusercontent.com/5055789/123266944-da8fa600-d4d2-11eb-8b11-31890c211111.png">

**Comment by Widcket** [comment]
@Paliao seems like your issue is solved. I will close this one, please ping me if you'd like to reopen it.
