### ISSUE TITLE
Is it possible to not send set-cookie header each time? 

### ISSUE THREAD

**Issue by divyenduz** [auth0/nextjs-auth0#425]
### Description

`getSession` calls sessionFactory(sessionCache) which calls cookie utils where setting `Set-Cookie` header happens for each request (probably because of rotation policy?)

https://github.com/auth0/nextjs-auth0/blob/main/src/auth0-session/utils/cookies.ts#L16

Is it possible to disable this each time we try to get the current session? Only login response should sent the `set-cookie` header and `getSession` helper should just return the session. 

### Context

I want to do this because I want to cache some user specific responses but GraphCDN doesn't cache when origin sends `Set-Cookie` https://graphcdn.io/docs/how-to/debug-cache-misses

### Environment

> Please provide the following:

- **Version of this library used:**: 1.4.0
- **Version of the platform or framework used, if applicable:** next.js 11

**Comment by adamjmcgrath** [comment]
Hi @divyenduz - thanks for raising this.

By default this wouldn't be possible because we use a rolling session (eg [log out after 24hrs of innactivity](https://auth0.github.io/nextjs-auth0/interfaces/config.sessionconfig.html#rolling)), which means every time you visit the site the session needs to be updated to reset the innactivity clock.

**Comment by divyenduz** [comment]
Thank you for your answer, is there a way to configure this? If no, is that a feature that you would consider? (happy to send a PR for it)

**Comment by adamjmcgrath** [comment]
You can disable the rolling session feature, but we currently still [store a new 'updated at' value](https://github.com/auth0/nextjs-auth0/blob/main/src/auth0-session/cookie-store.ts#L178) for every request and I don't see us changing that.

However there's nothing stopping you adding your own [`onHeaders` listener ](https://github.com/auth0/nextjs-auth0/blob/main/src/session/cache.ts#L22) to the response and removing the `Set-Cookie` if your confident that you don't need the updated session.

Closing this - feel free to ping me if you'd like to reopen to discuss more

**Comment by divyenduz** [comment]
For folks who reach here, this works and successfully removed the `Set-Cookie` header. I am only doing this in the GraphQL part of my API and it resolves my use case. I didn't have to set `rolling` to false. 

![image](https://user-images.githubusercontent.com/746482/123510771-9ab8f200-d67d-11eb-9b94-49e48ed07e69.png)
