### ISSUE TITLE
Logout doesn't work with subdomain cookie

### ISSUE THREAD

**Issue by divyenduz** [auth0/nextjs-auth0#429]
### Describe the problem

I am using `nextjs-auth0` with custom domain (`.trackfootball.app`)

```
const auth0 = initAuth0({
  clientID: process.env.AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET,
  routes: {
    callback: '/api/auth/callback',
    postLogoutRedirect: '/',
  },
  session: {
    cookie: {
      domain: process.env.COOKIE_DOMAIN,
    },
  },
})
```

Handler at `api/auth0/[...auth0].ts`

```
import { handleAuth } from '@auth0/nextjs-auth0'

export default handleAuth()
```

Logout handled doesn't delete the `appSession` cookie. My hunch is that because it doesn't contain the domain name

![image](https://user-images.githubusercontent.com/746482/123519715-4e85a600-d6ad-11eb-906c-f58dc17b84a9.png)

I was trying to follow the implementation and it should be removed here https://github.com/auth0/nextjs-auth0/blob/7269847bdc19ebc39972357690c9bd859e002822/src/auth0-session/cookie-store.ts#L169-L172 but the domain is not included in the `set-cookie` header. 

### What was the expected behavior?

Logout handler should expire cookie set with a custom subdomain `.<domain>`

### Reproduction

- 1. Use a `.<domain>` domain in cookie
- 2. Attempt a logout via logout handler

### Environment

- **Version of this library used:** 1.4.2
- **Which framework are you using, if applicable:** 11.0.1
- **Other modules/plugins/libraries that might be involved:** NA
- **Any other relevant information you think would be useful:** NA

**Comment by adamjmcgrath** [comment]
Thanks for reporting this @divyenduz - will take a look and get back to you

**Comment by adamjmcgrath** [comment]
Hi @divyenduz - I'm not able to reproduce this using the basic example app. When I set the cookie domain setting to `.adammcgrath.com` and logout I see the following `Set-Cookie` header

```
Set-Cookie: appSession=; Max-Age=0; Domain=.adammcgrath.com; Path=/
```

Could you share an example app that demonstrates the problem?

**Comment by divyenduz** [comment]
Weird, thank you for looking into it. I will try to reproduce this in isolation. 

P.S. Just for information, this might be unrelated but I removed the updated session from most of the server responses https://github.com/auth0/nextjs-auth0/issues/425#issuecomment-868984125

**Comment by divyenduz** [comment]
Just noted that neither basic or kitchensink use custom SDK instance which I use. Maybe it is that. Let me quickly try a reproduction (it will need to be deployed though, localhost doesn't reproduce this ofc)

**Comment by adamjmcgrath** [comment]
> Let me quickly try a reproduction (it will need to be deployed though, localhost doesn't reproduce this ofc)

Thanks @divyenduz - fyi I tested this locally by adding:

```
127.0.0.1 adammcgrath.com
```

To my `/etc/hosts` file

**Comment by divyenduz** [comment]
Here is a quick reproduction of what I am experiencing and a quick demo video of the same https://www.loom.com/share/9a1049e2737b4f2b84fbfc795290fe1f

**Comment by divyenduz** [comment]
Ha, that was it, I needed to use the custom SDK instance in all places i.e. handleLogout handler. Sorry about the false alarm.
