### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Arhitector** [auth0/nextjs-auth0#431]
We have migrated from hook version (@auth0/auth0-spa-js) to ssr (@auth0/nextjs-auth0). Hook version works well. After finishing migration to @auth0/nextjs-auth0  we have tested it on localhost (dev mode) and it works perfectly. Using the same environment variables we have got  a successful google cloud build. After checking the index page we have got an error `**502 Bad Gateway**`.

Steps:
- go to:  https://YOUR_APP/ (where we have checking of auth and redirect to login route **https://YOUR_APP/api/auth/login**)
- we are not logged in and we are redirecting to **https://YOUR_APP/api/auth/login**
- redirect to auth0 login screen
- after success login (have record in logs about success login) we have redirect to  **https://YOUR_APP/api/callback?code=AUTHORIZATION_CODE&state=xyzABC123** with `**502 Bad Gateway**`

Resume:
- implemented according to the documentation word for word.
- variables are 100% available
- on local machine 100% works developer mode and poduction build.
- auth0 panel have log about success login and logout
- cloud build success with out any errors
-  config.devtool = isProd ? config.devtool : 'eval-source-map';  <--  doesn't help
- was check cookies size and it is  468 byte. Same size on local machine where all works perfect

Question: How to fix?

### Environment

"@auth0/nextjs-auth0": "^1.4.0",
"next": "^10.2.3",
"react": "17.0.2",

local machine:
Mac OS 11.4 Chrome 91.0.4472

**Comment by Widcket** [comment]
Hi @Arhitector, thanks for raising this. If it works locally with both dev and production builds, it is most likely down to a misconfiguration in your deployment environment (e.g. a quotation mark in one of your env vars), or something specific to your cloud provider (e.g. a failing health check). I'm afraid we can't help with that.

Some Auth0-specific things you can check:
- You have the correct callback URL set up in the Auth0 dashboard (you mention `https://YOUR_APP/api/callback` but it should be `https://YOUR_APP/api/auth/callback`)
- If you're using a custom domain, it is correctly set up ->  in your `AUTH0_ISSUER_BASE_URL ` env var
- You don't have rules/actions/extensions that might be causing problems
- Your env var values are correct

**Comment by Arhitector** [comment]
Thank you @Widcket for your response. `https://YOUR_APP/api/callback` it was mistake path is correct `/api/auth/callback`.
What is 'rules/actions/extensions'?

**Comment by Widcket** [comment]
Glad you could find out the issue.

**Comment by Arhitector** [comment]
No. I didn't find). Mistake with path was in description. What does 'rules/actions/extensions' mean?

**Comment by Widcket** [comment]
@Arhitector [Rules](https://auth0.com/docs/rules), [actions](url) and [extensions](https://auth0.com/docs/extensions) are ways to extend the functionality of Auth0. If you have any of them in your tenant you need to check that they're working as intended and not causing the error you experience.

**Comment by Arhitector** [comment]
You can close this task. It's works. I suppose problem was on double request to api.
When we get response from auth0 service we get re-render component that has been sent additional request. It's my guess.

**Comment by Widcket** [comment]
Glad you could get it working.
