### ISSUE TITLE
Get session info in the frontend

### ISSUE THREAD

**Issue by lucasvmiguel** [auth0/nextjs-auth0#433]
### Describe the problem you'd like to have solved

Get session info in the frontend

### Describe the ideal solution.

I know that the decision to not have the session stored in the frontend was because of security (which makes total sense). However, the following implementation would help a lot.

The hook would talk to the backend to fetch the session, helping the developer to just call the hook to get the session. (and the session wouldn't be stored in the frontend)

Eg backend:
```ts
import type { NextApiRequest, NextApiResponse } from 'next'

import { withApiAuthRequired, getSession } from '@auth0/nextjs-auth0'

// endpoint provided by the SDK
export default withApiAuthRequired(async (req: NextApiRequest, res: NextApiResponse) => {
  const session = getSession(req, res)

  if (session) {
    res.status(200).json(session)
    return
  }

  res.status(404).end()
})
```

Eg frontend:
```tsx
import { PropsWithChildren } from 'react'
import type { AppProps } from 'next/app'

import { UserProvider } from '@auth0/nextjs-auth0'
import { ApolloProvider } from '@apollo/client'

import { createApolloClient } from '../lib/apollo'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <UserProvider>
      <ApolloProviderComponent>
          <Component {...pageProps} />
      </ApolloProviderComponent>
    </UserProvider>
  )
}

const ApolloProviderComponent = ({ children }: { children: PropsWithChildren<{}> }) => {
  // hook provided by the SDK
  const session = useUserSession()
  const client = createApolloClient(session.idToken)

  return (
    <ApolloProvider client={client}>
      {children}
    </ApolloProvider>
  )
}

export default MyApp

```

## Alternatives and current work-arounds

Had to implement it by myself, but I was able to see others having exactly the same issue.

The implementation was advised here: https://github.com/auth0/nextjs-auth0/issues/348#issuecomment-808166458

**Comment by Widcket** [comment]
Hi @lucasvmiguel, thanks for raising this. The SDK already has the `useUser` hook that calls the profile endpoint (`/api/auth/me` by default), and returns the user. What other session info are you expecting to get on the frontend?

**Comment by lucasvmiguel** [comment]
For example idToken`, I use that to contact my external backend API. But, I could see in other issues that other fields are required.

Issue with same problem: https://github.com/auth0/nextjs-auth0/issues/348

**Comment by Widcket** [comment]
Having the tokens in the frontend exposes them to be stolen via XSS, so we do not recommend that.
To access external APIs, you can setup a Next.js endpoint that proxies the request, adding the token.
If your data fetching mode relies mainly on calling APIs from the frontend, this SDK may not be the best fit, and you might want to look at the React SDK instead.

**Comment by lucasvmiguel** [comment]
That's fair, I guess I can call my Next.JS API endpoint to redirect to my external API (injecting the token before calling the external API)

Thanks for the recommendation 👍

**Comment by Widcket** [comment]
Glad it was useful.
