### ISSUE TITLE
withApiAuthRequired and external clients

### ISSUE THREAD

**Issue by bmadsen-ownrs** [auth0/nextjs-auth0#435]
### Describe the problem you'd like to have solved

Hello nextjs-auth0! 

Thanks for a great library.

We are using `withApiAuthRequired` to protect our API routes in our Nextjs application. All is going great so far. Now we have an idea to create an additional mobile application client that could re-use many of the routes we already have made for the Nextjs pages. 

We are struggling to figure out how we'd perform the authentication flow via the mobile app, since the API routes are cookie based.

### Describe the ideal solution

The ideal solution would be able to somehow re-use some of the authentication callbacks this library provides to generate the encrypted cookie based on access tokens we can provide by calling Auth0 directly from the mobile app.

Any ideas greatly appreciated 🙏 

## Alternatives and current work-arounds

None so far

### Additional information, if any

None so far

**Comment by adamjmcgrath** [comment]
Hey @bmadsen-ownrs - thanks!

> The ideal solution would be able to somehow re-use some of the authentication callbacks this library provides to generate the encrypted cookie based on access tokens we can provide by calling Auth0 directly from the mobile app.

Unfortunately, you can't get the value of the cookie on the client as it's `HttpOnly` - this is part of the [security model](https://github.com/auth0/nextjs-auth0#cookies-and-security) of the SDK

If you're going to call auth0 directly from the mobile client and get an Access Token, then you should protect your mobile API routes with an Access Token. 

Perhaps you could have different enpoints for the different auth methods that reuse the same code, eg

```js
// shared/helloworld.js
export default (req, res) => res.json({ msg: 'Hello World!' });

// api/desktop/helloworld.js
import helloWorld from '../shared/helloworld';
import{ withApiAuthRequired } from '@auth0/nextjs-auth0';

export default withApiAuthRequired(helloWorld);

// api/mobile/helloworld.js
import helloWorld from '../shared/helloworld';
import { NextJwtVerifier } from '@serverless-jwt/next';

const verifyJwt = NextJwtVerifier({ issuer, audience });

export default verifyJwt(helloWorld);
```

*Other JWT verification libraries are available

**Comment by bmadsen-ownrs** [comment]
@adamjmcgrath thanks for the quick response and the suggestion 💪
