### ISSUE TITLE
Silent authentication without user interaction

### ISSUE THREAD

**Issue by roaks3** [auth0/nextjs-auth0#44]
### Describe the problem you'd like to have solved

There does not appear to be a way to have the user silently authenticate without the need for interaction from the user (ie. requiring a click of a "Login" button).

### Describe the ideal solution

A new handler (something like `SilentLoginHandler` or `CheckSessionHandler`) that would allow us to check for an existing Auth0 session and create the cookie required for subsequent authenticated calls.

### Alternatives and current work-arounds

- Since the library does not expose the cookie store, there does not appear to be a work-around
- If this library is not used, `auth0.js` appears to have a solution in `checkSession()` that will return the token of an existing session, which can be used for subsequent authenticated calls.

### Additional context

This request is in support of a requirement we have to support a shared login session seamlessly across two applications. If a user has already logged in through one application, we would like the session to be automatically loaded right when the user lands on the second application.

**Comment by juhaelee** [comment]
Just for clarity, is this the reason why I am logged out of my application (in less than 3 days) and forced to login again even after I set my [inactivity timeout to 3 days](https://auth0.com/docs/sessions/concepts/session-lifetime)?

**Comment by UlyssesInvictus** [comment]
To clarify and expand on a similar use case, our application needs the ability to silently authenticate the user in the client, but then forward that token / cookie to the Next API so that the token can then be authenticated and used for server side rendering. In our particular case, it's not feasible to perform the authentication server side first, as we're sharing a cross-domain application with the rest of our organization, and need to be able to (silently) perform the authentication based on cookies that have already been set in the client by these other domains.

**Comment by joecris** [comment]
not sure if it helps, but current loginHandler can do silent authentication by passing additional authParams `prompt: 'none'`

`import auth0 from '../../utils/auth0';

export default async function login(req, res) {
  try {
    await auth0.handleLogin(req, res, {
      authParams: {
        prompt: 'none'
      }
    });
  } catch (error) {
    console.error(error);
    res.status(error.status || 400).end(error.message);
  }
}`

**Comment by marklawlor** [comment]
Should this library implement Silent authentication when the Auth0 docs recommend against it?

> Recent advancements in user privacy controls in browsers adversely impact the user experience by preventing access to third-party cookies. Auth0 recommends using Refresh Token Rotation, which provides a secure method for using refresh tokens in SPAs while providing end-users with seamless access to resources without the disruption in UX caused by browser privacy technology like ITP.

[source - https://auth0.com/docs/authorization/configure-silent-authentication](https://auth0.com/docs/authorization/configure-silent-authentication)

**Comment by develanet** [comment]
I'm currently using the `prompt: 'none'` workaround as @joecris mentioned above. 

In my case I'm actually using this silent auth path as the redirect_url for a [Stripe Checkout Session](https://stripe.com/docs/api/checkout/sessions). This enables my app to refresh the Auth0 session and get the updated profile where I'm storing the Stripe customer ID and subscription info etc. Not sure if it's ideal but it works for me...

```
// pages/api/silent-auth.js

export default async function silentAuth(req, res) {
  try {
    await auth0.handleLogin(req, res, {
      authParams: {
        prompt: 'none',
      },
      redirectTo: `/signup/success?session_id=${req.query.session_id}`,
    });
  } catch (error) {
    console.error(error);
    res.status(error.status || 500).end(error.message);
  }
}
```

**Comment by adamjmcgrath** [comment]
Hi @roaks3 - thanks for raising this

Thanks @develanet's [your suggestion](https://github.com/auth0/nextjs-auth0/issues/44#issuecomment-699487696) is correct, this is how we recommend you should do silent authentication using the SDK, there are no plans to add a silent auth handler to the SDK, but as you can see - creating one yourself is trivial.

**Comment by francescovenica** [comment]
Hello, I'm trying to create the silent-auth endpoint and it seems to work, the issue is when I try to call it from my frontend as I get a cors error:

```
Access to fetch at 'https://xxx.auth0.com/authorize' (redirected from 'https://domain.local:3000/api/silent-auth') from origin 'https://domain.local:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```


do you have any idea why? I'm using a custom domain on my local machine, I already inserted the domain in all the whitelist options in the application setting page
