### ISSUE TITLE
Export the auth0 client

### ISSUE THREAD

**Issue by gabsn** [auth0/nextjs-auth0#442]
I would need to be able to use the auth0 client to fetch the access token from the apollo client.

Right now, there is a `getAccessToken` function but it can only be used in the context of an api call...

It would be nice to have access to the full auth0 client so we can use its methods everywhere.

Anyway, right now I'm a bit blocked and I need to first query an api endpoint to get the access token... which is a not a good thing security-wise.

**Could you add a `getAccessTokenSilently` with a simple API to be use everywhere globally?**

**Comment by adamjmcgrath** [comment]
Hi @gabsn - thanks for raising this

> Could you add a getAccessTokenSilently with a simple API to be use everywhere globally?

We've answered this question here: https://github.com/auth0/nextjs-auth0/issues/348#issuecomment-808166458

**Comment by adamjmcgrath** [comment]
Closing this - feel free to ping me if you'd like me to reopen

**Comment by gabsn** [comment]
Sure sorry, it took me time to find my answers since the subject is quite complex.
