### ISSUE TITLE
1.5.0 crashing

### ISSUE THREAD

**Issue by hacknlove** [auth0/nextjs-auth0#443]
### Describe the problem

Release 1.5.0 is crashing my app

### What was the expected behavior?

The code should work the same, as no breaking changes have been declared.

### Reproduction

This is the code that is breaking the app:

```
export const getServerSideProps = withPageAuthRequired({
  returnTo: '/',
  getServerSideProps(ctx) {
    if (!ctx.query.symbol) {
      return {
        props: {},
      };
    }

    return explore(ctx)
  },
});
```

**Logs:**

> 1 silly lifecycle webapp@0.1.1-0~dev: Returned: code: 1  signal: null
> 12 info lifecycle webapp@0.1.1-0~dev: Failed to exec dev script
> 13 verbose stack Error: webapp@0.1.1-0 dev: `next dev`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/home/pykiss/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:315:20)
> 13 verbose stack     at ChildProcess.<anonymous> (/home/pykiss/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:315:20)
> 13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
> 14 verbose pkgid webapp@0.1.1-0

### Environment

- "@auth0/nextjs-auth0": "^1.4.2"
- "next": "^11.0.1"

**Comment by adamjmcgrath** [comment]
Hi @hacknlove - let me check this out and get back to you

**Comment by adamjmcgrath** [comment]
Hi @hacknlove - I can't reproduce your issue using the following snippet and `@auth0/nextjs-auth0@1.1.5.0`/ `next@11.0.1`

```js
export const getServerSideProps = withPageAuthRequired({
  returnTo: '/',
  getServerSideProps(ctx) {
    if (!ctx.query.symbol) {
      return {
        props: {},
      };
    }
    // not sure what `explore` did
    return ctx;
  },
});
```

And the logs you've shared aren't telling me anything other than that `next dev` failed to run.

If you can share some other error message or a reproducable example I can debug it for you

**Comment by hacknlove** [comment]
That's the problem, there is any other error message.

I'll try to reproduce it with the minimun amount of code possible, by removing everything not related.

**Comment by hacknlove** [comment]
My bad.

It was not caused by `@auth0/nextjs-auth0@1.5.0` it was caused by `mongo@4.0.0`

The error disappeared when commpenting the getServerSideProps, because that way mongo was not used.

Sorry.

I close this.
