### ISSUE TITLE
Does not show user login prompt (screen) anymore after first login

### ISSUE THREAD

**Issue by abiswas529** [auth0/nextjs-auth0#445]
### Description

**Does not show user login prompt anymore after first login**

Currently I am using `"dependencies": {
    "@auth0/nextjs-auth0": "^1.4.2",`
When I first login to the application it shows the user login prompt but if I logout and try to login second time it does not showing the prompt again rather it automatically log in with the previous login credentials.

**I want every time a user log out from the application, then on the next login user should go through the login prompt again so that they can decide which account to use.**

 I am using `initAuth0 `from ` import { initAuth0 } from "@auth0/nextjs-auth0";`
below it the configuration that I am currenlty using 

```
  export default initAuth0({
    clientID: process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID,
    clientSecret: process.env.APP_AUTH0_CLIENT_SECRET,
    secret: process.env.APP_AUTH0_SECRET,
    baseURL: process.env.APP_AUTH0_BASE_URL,
    issuerBaseURL: process.env.APP_AUTH0_ISSUER_BASE_URL,
    authorizationParams: {
      connection: "<My_Connection>",
      audience: "<AUDIENCE>",
      scope: process.env.NEXT_PUBLIC_AUTH0_SCOPE,
    },
    idpLogout: true,
    auth0Logout: true,
    routes: { postLogoutRedirect: "/" },
  });
```

### Reproduction

I am using both 
```
 idpLogout: true,
 auth0Logout: true,
```
But it is not working,

Any help or documentation on how to achieve this will be much appriciated.

**Comment by adamjmcgrath** [comment]
Hi @abiswas529 - thanks for raising this

> idpLogout: true
> auth0Logout: true

You should logout from auth0 when you logout of your app with the above settings and I can't reproduce your issue on the basic-example app

Do you see the `/logout` issued by your tenant when you logout? eg

![image](https://user-images.githubusercontent.com/1299658/126314894-ad183a4e-6810-41c0-9f68-7439be5f6b2d.png)

Also, how are you creating the logout handler? Are you using the instance you created from `initAuth0` or the named export `handleAuth`?

**Comment by abiswas529** [comment]
Hi @adamjmcgrath Thanks for your reply.

FYI
I am using the instance created from `initAuth0 `. Below is the Logout route that I am using.

```
import auth0 from "../../lib/auth0";

export default async function logout(req, res) {
  try {
    await auth0.handleLogout(req, res);
  } catch (error) {
    console.error(error);
    res.status(error.status || 500).end(error.message);
  }
}

```
Here is the API folder structure - 

![image](https://user-images.githubusercontent.com/55099778/126445304-4287f225-0f92-4b0f-a2ba-b6ce5404a3b8.png)

And this is how I am calling the logout from my component `<a href="api/logout">Sign Out</a>`\

Checked in postman interceptor it is generating the logout as below.

![image](https://user-images.githubusercontent.com/55099778/126448475-6c41ef8d-92c4-4ef9-bb0b-ae302b3d6790.png)

**Comment by adamjmcgrath** [comment]
Thanks for sharing that @abiswas529 

If you're making the request successfully to `auth0.com/v2/logout` then I can't explain why subsequent visits to `auth0.com/authorize` aren't prompting you to login again.

My other suggestions:
- Do you have any rules in place that might prevent you from logging out?
- Is that logout request succeeding? After logout do you still have the `auth0` cookie on `yourtenant.auth0.com/authorize`?
- What does the code look like in your auth folder?
- Can you create a minimal example that reproduces the problem that I can debug?

**Comment by adamjmcgrath** [comment]
Hi @abiswas529 - let me know if you're still seeing issues with logout and if you've had a chance to look at my suggestions

**Comment by abiswas529** [comment]
Hi, @adamjmcgrath thanks for your help.

This issue is resolved now. yes, there are rules in place.

Appreciate your help. 🙏
