### ISSUE TITLE
useUser and getAccessToken not synced

### ISSUE THREAD

**Issue by Kohei909Otsuka** [auth0/nextjs-auth0#452]
### Description

I use `nextjs` + `auth0` + `graphQL(external api server)`

to get access token my next js app has `pages/api/graphql_proxy.js` like below

``` js
export default async function graphqlProxy(req, res) {
  let token = ""
  try {
    const { accessToken } = await getAccessToken(req, res, {});
    token = accessToken
  } catch (error) {
    // "AccessTokenError always happens if not loggined"
    if (error.code !== "invalid_session") {
      console.error("err happens af graphqlProxy function", error);
    }
  }

  const apiRes = await fetch(`${process.env.API_BASE_URL}/graphql`,{
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`
    },
    body: JSON.stringify(req.body),
  })
  res.status(200).send(apiRes.body)
}
```

and all graphQL requests(some of them require login, some of them not) pass this proxy and go to graphQL server. 
On the graphQL server, it checks `Bearer ${token}`, and detect if it is from logined user or not.

the problem I have is when code(`getAccessToken`) above has err 

```
[Error: The access token expired and a refresh token is not available. The user will need to sign in again.] {
  code: 'access_token_expired'
}
```

`useUser` on client side still returns user object without error.

So there is no way to ask users to login,
I think `useUser` output and `getAccessToken` output should always synced, but it's not...

detail timeline

```
1. client side: call useUser, and request graphqlProxy because useUser returns User object without error
2. server side(lamda): getAccessToken can't get token, then HTTP header will be `Bearer `(empty)
3. serve side(external graphQL server): it says unauthorized because token is empty on header
```

Can you help me ?
I want know how to fix this problem...

`logout => login` solves this problem, but it occurs again after a while.

### Reproduction

![wakame_–_Serverless_Functions_png_と_127498726-42ebdb2a-2808-4281-bb4a-3a5406a39016_png__1902×1048_](https://user-images.githubusercontent.com/11783802/127522315-e621198d-979f-43d5-b9b4-7a6dd90ad111.png)

![Cursor_と_127498726-42ebdb2a-2808-4281-bb4a-3a5406a39016_png__1902×1048_](https://user-images.githubusercontent.com/11783802/127523993-9969784f-d79a-4539-8c02-eb432b143b42.png)

### Environment

> Please provide the following:

- **Version of this library used: 1.5.0**
- **Version of the platform or framework used, if applicable: next.js: 11.0.1**
- **Other relevant versions (language, server software, OS, browser): google chrome on Mac OS + Lamda**
- **Other modules/plugins/libraries that might be involved:**

**Comment by Widcket** [comment]
Hi @Kohei909Otsuka, thanks for raising this.

In order to get a new Access Token when the current one expires, you'll need a [Refresh Token](https://auth0.com/docs/tokens/refresh-tokens). To have the SDK obtain and use a Refresh Token, you need to add the `offline_access` scope. You can do so with the `AUTH0_SCOPE` [environment variable](https://github.com/auth0/nextjs-auth0/blob/main/examples/README.md#environment-variables).

WRT `useUser`, what the hook does is call the profile endpoint and cache the result, so it is bound to become stale. You can use the `checkSession` method returned from `useUser` to force a refresh. See:

https://user-images.githubusercontent.com/5055789/105118105-8bb98c80-5aac-11eb-8bfd-03341a7b7cab.mov

**Comment by hamatoyogi** [comment]
Having a similar issue, not with GraphQL, but basically the same.

Was about to open an issue after talking to @jamesqquick but found this...

In our case we also get a recurring error in our Next backend logs: `TypeError: Cannot read property 'cookie' of undefined`

These things might be related. Any help would be much appreciated.

**Comment by Widcket** [comment]
Hi @hamatoyogi, can you please expand on the issue you're experiencing?

**Comment by Widcket** [comment]
@Kohei909Otsuka check out [this example](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#access-an-external-api-from-an-api-route) that shows how to pass the scope programmatically as well.

**Comment by Widcket** [comment]
@Kohei909Otsuka will close this issue for now. Please ping if you'd like to reopen.

**Comment by morioust** [comment]
> In order to get a new Access Token when the current one expires, you'll need a [Refresh Token](https://auth0.com/docs/tokens/refresh-tokens). To have the SDK obtain and use a Refresh Token, you need to add the `offline_access` scope. You can do so with the `AUTH0_SCOPE` [environment variable](https://github.com/auth0/nextjs-auth0/blob/main/examples/README.md#environment-variables).

I added the `offline_access` scope via the `AUTH0_SCOPE` environment variable. I also tried to pass the scope programmatically, as in the example you linked. But I still have the same issue as @Kohei909Otsuka:
```
[Error: The access token expired and a refresh token is not available. The user will need to sign in again.] {
  code: 'access_token_expired'
}
```

It just seems to ignore the `offline_access` scope. It also does not appear in the user's session after login.

Do you have an executable project example where obtaining a refresh token via the offline_access scope works?

Any help is very appreciated.

**Comment by morioust** [comment]
I managed to get it to work.

For everyone having the same issue:
Under the API Settings, in the section Access Settings, I enabled "Allow Offline Access".
For testing I set the token expiration to a low number.

When logging a user out and in again, it will now ask for the additional scope permission.

The *Allow Offline Access* setting was disabled by default on my API, so if that was the correct way to solve it, it would be great to have that referenced in the docs.

**Comment by blazestudios23** [comment]
I'm not seeing these setting in the Web App client. Aren't we using web app clients with Next.js?

**Comment by adamjmcgrath** [comment]
@blazestudios23 - this is in the settings for your API (not your client) https://manage.auth0.com/#/apis

**Comment by blazestudios23** [comment]
So am I supposed to use the machine to machine Client with next.js and not a single page application client?

**Comment by adamjmcgrath** [comment]
I think we've got our wires crossed. You should use a Regular Web Application client. If your client accesses an API defined by Auth0 (in https://manage.auth0.com/#/apis) and wants a Refresh Token. The API should be set to "Allow Offline Access" in the API Settings

**Comment by blazestudios23** [comment]
OK. I have this set up. But the error gets thrown in the Next.js app and the token is never sent to the external server. So something has to be missing.

**Comment by blazestudios23** [comment]
I'm now getting this error:

```bash
[Error: Could not retrieve an access token with scopes "openid profile email offline_access". The user will need to sign in again.] {
[next.dev]   code: 'insufficient_scope',
[next.dev]   page: '/api/[...all]'
[next.dev] }
```

I've tried logging out and clearing the clearing all site data. I get it no matter what I do, with 0 cookies stored on the front end.

**Comment by blazestudios23** [comment]
OK, so I found this article:

https://community.auth0.com/t/accesstokenerror-when-requesting-offline-access-scope/62813

I found that I didn't have the Refresh Token Rotation enabled, so enabled it. Now I get this error:

```bash
OPError: invalid_grant (Unknown or invalid refresh token.)
[next.dev]     at processResponse 
```

There really needs to be an article on how to do this whole process, as there are just so many little parts to it.

**Comment by adamjmcgrath** [comment]
Hi @blazestudios23 

> I found that I didn't have the Refresh Token Rotation enabled, so enabled it. Now I get this error:

You don't need to enable Refresh Token Rotation, this is only for SPAs see https://auth0.com/docs/security/tokens/refresh-tokens/refresh-token-rotation

Using Refresh Token Rotation with no [reuse interval](https://auth0.com/docs/security/tokens/refresh-tokens/configure-refresh-token-rotation#configure-in-the-dashboard) and no mechanism for preventing concurrent refresh token grants may result in [breach detection](https://auth0.com/docs/security/tokens/refresh-tokens/configure-refresh-token-rotation#automatic-reuse-detection) which might be what your `invalid_grant` error is about. 

You can get more information on what is causing your error in your tenant logs https://manage.auth0.com/#/logs

If you think there's a specific issue in the SDK feel free to raise a new issue. For general help on Refresh Tokens, please use the community forums https://community.auth0.com/

**Comment by blazestudios23** [comment]
@saidybarry I got it working: 

Here's my files:

```
waitOn({ resources, log: true }, async () => {
  const apollo = new ApolloServer({
    // new way to add the playground in.
    plugins: [
      SHOW_PLAYGROUND
        ? ApolloServerPluginLandingPageGraphQLPlayground()
        : ApolloServerPluginLandingPageDisabled(),
      ApolloServerPluginInlineTrace(),
    ],
    validationRules,
    gateway,
    context: async ({ req, res }): Promise<Context> => {
      let auth0User = {
        email: null as any,
        sub: null as any,
        ['emailIdentifier']: null as any,
        error: null,
      };

      try {
        auth0User = await getAuth0User(req);

        auth0User.email = auth0User['https://gateway.moonwalk.com/email'];
        if (auth0User?.error) {
          logger.error(auth0User?.error);
        }
      } catch (e) {
        logger.error(e);
        throw new Error('Not Authorized');
      }

      const custCtx: Context = {
        auth0User,
        // set which app the request came from
        app: (req.headers['apollographql-client-name'] as string) || 'unknown',
        cookie: req?.headers?.cookie,
        response: res,
        refererUrl: req?.headers?.referer,
      };
      return custCtx;
    },
    introspection: Boolean(SHOW_PLAYGROUND),
  });


```


```
function getKey(header: any, cb: any) {
  client.getSigningKey(header.kid, function (err, key: any) {
    // @ts-ignore
    const signingKey = key.publicKey || key.rsaPublicKey;
    cb(null, signingKey);
  });
}

interface Auth0User {
  email: string;
}

export const getAuth0User = (req: Request): any => {
  // simple auth check on every request
  const token = req.headers?.authorization?.split(' ')[1];

  if (!token) {
    return { email: null };
  }

  const decoded: any = decode(token);

  if (decoded?.iss !== `${process.env.AUTH0_DOMAIN}/`) {
    return { email: null };
  }

  const result = new Promise((resolve) => {
    verify(
      token,
      getKey,
      {
        audience: 'https://gateway.moonwalk.com',
        issuer: `${process.env.AUTH0_DOMAIN}/`,
        algorithms: ['RS256'],
      },
      (error, decoded: any) => {
        if (error) {
          resolve({ error });
        }

        if (decoded) {
          resolve(decoded);
        }
      }
    );
  });

  return result;
};


```
