### ISSUE TITLE
Make auth0.handleLogin > authorizationParams > login_hint read only for users and disappear when field has focus

### ISSUE THREAD

**Issue by shellymutu-grigg** [auth0/nextjs-auth0#456]
### Describe the problem you'd like to have solved

Currently unable to identify a way of making the text that appears in the email field in the Universal Login when the login_hint value is populated to be read-only and to disappear when a user clicks into the field.

Feedback from users is they do not like/find it annoying having to clear out the text to enter email details during login flow.

Could not seem to find this documented in the SDK or via docs

```
// login.ts
// using "@auth0/nextjs-auth0": "^1.4.2"

import { NextApiRequest, NextApiResponse } from 'next';
import { auth0 } from '@utils/auth0';

export default async function login(req: NextApiRequest, res: NextApiResponse) {
  try {
    // https://auth0.github.io/nextjs-auth0/modules/handlers_login.html#handlelogin
    await auth0.handleLogin(req, res, {
      authorizationParams: {
        login_hint: 'Enter your email address',
      },
    });
  } catch (error) {
    // Error logging
    // eslint-disable-next-line no-console
    console.error(error);
    res.status(error.status || 500).end(error.message);
  }
}
```

### Describe the ideal solution

Ideally a flag would be able to be provided with the login_hint to identify that the text should be read only and disappear on field focus.

## Alternatives and current work-arounds

Currently have removed login_hint after feedback from multiple users

### Additional information, if any

N/A

**Comment by Widcket** [comment]
Hi @shellymutu-grigg, thanks for raising this. To customize Universal Login, you can try using a custom template – see the following docs page for more information: https://auth0.com/docs/universal-login/new-experience/universal-login-page-templates. Perhaps you can achieve the effect you're looking for with some CSS.

Given that styling UL is not related to this SDK (it's done via the Dashboard, or via the Management API), I'll close this issue.
