### ISSUE TITLE
useUser doesn't work properly when using it in Per-page Layouts 

### ISSUE THREAD

**Issue by gabrielelpidio** [auth0/nextjs-auth0#458]
### Describe the problem

When applying the pattern of  [Per-page Layouts](https://nextjs.org/docs/basic-features/layouts#per-page-layouts) and trying to use the useUser hook in it the application like so: 

```javascript
import React, { ReactElement } from "react";
import { useUser } from "@auth0/nextjs-auth0";
import Link from "next/link";

const Layout = (page: ReactElement) => {
  const { user, isLoading, error } = useUser();
  if (isLoading) {
    return "loading...";
  }

  if (error) {
    return (
      <div>
        An error has ocurred
        <Link href="/">Go home</Link>
      </div>
    );
  }
  return (
    <div>
      <header>
        <img src={user?.picture} alt="Profile pic" />
      </header>
      {page}
    </div>
  );
};

export default Layout;

```
It throws the following error

` Error: You forgot to wrap your app in <UserProvider>`

For reference this is the _app.tsx: 
```javascript
//deps
import { UserProvider } from "@auth0/nextjs-auth0";

//types
import type { NextPage } from "next";
import type { AppProps } from "next/app";
import { ReactElement, ReactNode } from "react";

type NextPageWithLayout = NextPage & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

function App({ Component, pageProps }: AppPropsWithLayout) {
  const { user } = pageProps;
  const getLayout = Component.getLayout ?? ((page) => page);
  return (
    <UserProvider user={user}>
      {getLayout(<Component {...pageProps} />)})
    </UserProvider>
  );
}

export default App;

```

### What was the expected behavior?

UseUser should be able to run on the Layout component so that it has access to the users info to render say, profile pics or the name on the layout

Right now the workaround that I'm using is to fetch /api/auth/me with SWR in the Layout component

### Reproduction

- Create a NextJS app with basic Auth0 integration following the documentation on this repo, including wrapping the app with the UserProvider
- Create a Layout and initialize it inside a component like demoed on [Next.js Per-page Layout section](https://nextjs.org/docs/basic-features/layouts#per-page-layouts) in the official docs
- Try to use useUser inside the Next.js Component
### Environment

-@auth0/auth0-nextjs 1.5.0
- Next.js 11.0.1

**Comment by Widcket** [comment]
Hi @gabrielelpidio – thanks for raising this.
I tried to reproduce this on the kitchen sink [example app](https://github.com/auth0/nextjs-auth0/tree/main/examples/kitchen-sink-example) included in this repo, but I was unsuccessful:

https://user-images.githubusercontent.com/5055789/129276166-c0be0645-a447-4d3c-8752-e38eb110eb19.mov

Are you able to reproduce this in an isolated environment, e.g. that example app or our Quickstart [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01)?

**Comment by gabrielelpidio** [comment]
Hi @Widcket I was able to reproduce it with a very simple example. Here is the repo: 
https://github.com/gabrielelpidio/kitchen-sink-example-auth0

**Comment by Widcket** [comment]
@gabrielelpidio, `Profile.getLayout` must be a function that returns an element, not an element. Like so:
```jsx
Profile.getLayout = function getLayout(page) {
  return <AuthLayout>{page}</AuthLayout>;
};
```

https://user-images.githubusercontent.com/5055789/129432739-800f8afc-8b93-4201-a499-836d2874edac.mov

**Comment by gabrielelpidio** [comment]
It makes lots of sense. thought I could export it as an Element and use it. Works perfectly now

Thanks for the help @Widcket!
