### ISSUE TITLE
Unable to handle login error with custom template

### ISSUE THREAD

**Issue by abiswas529** [auth0/nextjs-auth0#462]
### Description
In my application when a user using an already registered email address in google signup, we are throwing an error and the error details are present therein URL as `http://localhost:3000/api/auth/callback?error=access_denied&error_description=User%20superuser19969%40gmail.com%20is%20already%20registered.&state=eyJyZXR1cm5UbyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9#`.

Currently, we are getting a screen below,

![image](https://user-images.githubusercontent.com/55099778/129343326-44b26e79-23f8-4c56-9e2a-865391c69c8f.png)

Somehow I want to customize the UI and give the user an option to go back to the login prompt or to the home screen.
I searched and found `Module utils/errors` has a `Class HandlerError` but there is no proper example of how to use this and showcase our own template if such a case arrives.

### What is the expected behavior

The expectation here is to showcase a better custom UI to the user in case if he/she uses the already registered Gmail id in google signup.

Any documentation on how to achieve this or any example repo will help here.

### Reproduction

1. Register with a Gmail id using create an account.
2. Use the same Gmail id in google signup.

### Environment

"@auth0/nextjs-auth0": "^1.4.2",

**Comment by Widcket** [comment]
Hi @abiswas529, thanks for raising this. You'd have to catch the error in the login handler, I think. There you can redirect the user. See https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#customize-handlers-behavior.

**Comment by abiswas529** [comment]
Hi @Widcket, Thanks for the quick help. Now I am able to handle the error and customize it as per my need. 🙌
