### ISSUE TITLE
How long is this supposed to be experimental?

### ISSUE THREAD

**Issue by PacoVK** [auth0/nextjs-auth0#47]
Are there any near future plans to release a not experimental version of the sdk? Really looking forward to use it 👍 Progressbar or Milestones would be awesome ❤️

**Comment by nodabladam** [comment]
Merging the open PRs would go a long way towards getting us there.

**Comment by markau** [comment]
My question is not so much about how long it might take, but more an assurance that it is part of the auth0 strategic direction; that I can start to build a project based on nextjs and this library.

**Comment by balupton** [comment]
At @bevry we looked into using this, as it is also used by the nextjs auth example:

- https://github.com/zeit/next.js/tree/canary/examples/auth0
- https://github.com/zeit/next.js/tree/87e096eb5b196d37be492b3b0ed250ebedfb4e8d/examples/auth0

And got something rudimentary up and going:

- https://github.com/bevry/fountain

However, it was a lot more tricky than we thought it should be, so now looking at:

- https://github.com/pwa-builder/pwa-auth
- with some cloudflare workers for the backend

**Comment by markau** [comment]
Thanks for passing on your experience @balupton 

It seems the architecture of nextjs makes this harder than it would otherwise be. I am not sure why the backend need be involved at all. Following the Auth0 docs and library for Angular, I had a workable application up and running in a day using Code flow + PKSE authentication, and role-based authorisation to an external API. That's the level of abstraction I was hoping for.

**Comment by Widcket** [comment]
Hi everyone, we've just released [v1.0.0-beta.0](https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0). This is an important step towards getting the library to GA. Please try it out, your feedback is welcome.

**Comment by adamjmcgrath** [comment]
Hi @PacoVK - thanks for your question

We don't have a release date for general availability - but once we're happy with the [v1.0.0-beta.0](https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0) we'll be proceeding with an official release

**Comment by Widcket** [comment]
The [v1.0.0 release](https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0) is out now.
