### ISSUE TITLE
Absolute Session Duration Does Not Work

### ISSUE THREAD

**Issue by sdoironkcdus** [auth0/nextjs-auth0#470]
### Describe the problem

When using the base SDK and using the environmental variables to configure the SessionConfig, setting the `AUTH0_SESSION_ABSOLUTE_DURATION` does not work as expected.

The documentation states that this variable is "The amount of time after the user has logged in that they will be logged out". 
 No matter what I set the value as, my session never gets logged out, and I am using `withPageAuthRequired()` on the page I've been testing it with.  It's also worth noting that I did set `AUTH0_SESSION_ROLLING` as `false` since it seems like that'd cause the desired effect of the absolute duration to not trigger.

### What was the expected behavior?

Based on the language on the documentation, this optional config value should route to the `/api/auth/logout` path in order to logout the session, and bring me to the login page after the set value (time in seconds) has elapsed and I have loaded a page or API that is wrapped with either `withPageAuthRequired()` or `withApiAuthRequired()`.

### Reproduction

1. Create a new NextJS project
2. Setup an Auth0 `Regular Web Application`
3. Install & setup this package with just the base SDK (so using the dynamic API route, etc)
4. Create a page that has `withPageAuthRequired()`
5. Set the `.env.local` variables for `AUTH0_SESSION_ROLLING` to `false`, and `AUTH0_SESSION_ABSOLUTE_DURATION` to `15` (yes 15 seconds for testing, unless this is too low? Not sure how anybody would know otherwise since there's no documentation outlining any minimums or maximums)
6. Log in and wait for the absolute duration time
7. Refresh the page or go to another page that is also wrapped with `withPageAuthRequired()`
8. You won't be logged out

### Environment

Version: 1.5.0
Framework: NextJS 10.1.13 & React 17.0.1

**Comment by adamjmcgrath** [comment]
Hi @sdoironkcdus - thanks for raising this.

When I set `AUTH0_SESSION_ROLLING` to `false` and `AUTH0_SESSION_ABSOLUTE_DURATION` to `15` and login to the `kitchen-sink` app, it sets a cookie with an expiration date 15 secs in the future as expected

![image](https://user-images.githubusercontent.com/1299658/130451674-c6359db7-b87a-463f-9a7a-ddca8f6782ef.png)

I think the issue you are having is that, the session cookie expires as expected but when you visit another page protected with `withPageAuthRequired`, you're logged out locally so get redirected to auth0, but you are not logged out of auth0 so get automatically redirected back without a login prompt and a new session is established.

If you want to force the user to always be prompted with the login form, you can use `prompt=login` (see https://auth0.com/docs/login/max-age-reauthentication). Which would get passed as a custom `authorizationParams` option to the default login handler, see the example of overriding the custom params in the login handler here https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#customize-handlers-behavior

**Comment by sdoironkcdus** [comment]
@adamjmcgrath Ah I see.  Yes that's exactly what I needed, thank you very much.  I would recommend that the documentation for `AUTH0_SESSION_ABSOLUTE_DURATION` be re-worded a little bit to clear up that confusion.  But again, thank you, this has been a lingering issue I haven't been able to figure out for a while now lol 😅
