### ISSUE TITLE
Bug "offline_access" scope not providing refresh token

### ISSUE THREAD

**Issue by dylanesque** [auth0/nextjs-auth0#475]
### Describe the problem

I'm working on a Next application, and I'm seeing users' sessions expire after about a day, despite having the timeouts set to the maximum value. I'm requesting that access tokens get refreshed via the 'offline_access" being added to the `scope` per https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#access-an-external-api-from-an-api-route, but with no results. 

### Environment

Version of this library used: 1.5.0
Version of the platform or framework used, if applicable: Next.js 11.1.0
Other relevant versions (language, server software, OS, browser): Chrome 92.0
Other modules/plugins/libraries that might be involved: Node v16.6.1

**Comment by Widcket** [comment]
Hi @dylanesque, thanks for raising this.

Do you have refresh tokens enabled in your API?
<img width="988" alt="Screen Shot 2021-08-23 at 19 25 04" src="https://user-images.githubusercontent.com/5055789/130527273-16cae0f3-61df-49c8-9a49-8d0900f74ed8.png">

If so, are you able to reproduce the problem in the [kitchen sink sample app](https://github.com/auth0/nextjs-auth0/tree/main/examples/kitchen-sink-example)?

**Comment by dylanesque** [comment]
> Hi @dylanesque, thanks for raising this.
> 
> Do you have refresh tokens enabled in your API?
> <img alt="Screen Shot 2021-08-23 at 19 25 04" width="988" src="https://user-images.githubusercontent.com/5055789/130527273-16cae0f3-61df-49c8-9a49-8d0900f74ed8.png">
> 
> If so, are you able to reproduce the problem in the [kitchen sink sample app](https://github.com/auth0/nextjs-auth0/tree/main/examples/kitchen-sink-example)?

Hi, tokens are definitely enabled in the console, I haven't set up the kitchen sink app yet, so I would probably need a day or two to confirm that.

**Comment by Widcket** [comment]
@dylanesque will close this issue for now, as seems that you've solved the problem. Please ping if you'd like to reopen.

**Comment by statico** [comment]
Hi @Widcket, I'm looking into this and I don't see that setting under our API's settings. We only have one API in product: the default "Auth0 Management API" API. Any ideas?

<img width="1040" alt="CleanShot 2021-09-10 at 15 50 19@2x" src="https://user-images.githubusercontent.com/137158/132925505-30baa176-79ea-4fff-bdc8-8de0103830c9.png">
