### ISSUE TITLE
How to access more user profile attributes

### ISSUE THREAD

**Issue by peter-yolabs** [auth0/nextjs-auth0#477]
### Describe the problem you'd like to have solved

Trying to access a user's` created_at` field using this library, but unable to find any information on how to achieve this.  
It seems like a common enough scenario that I imagine it exists, just in a non-obvious way.  

### Describe the ideal solution

Information or a guide on how to access these profile fields using this library.

**Comment by adamjmcgrath** [comment]
Hi @peter-yolabs 

The `created_at` claim isn't included by default, you'll need to create a rule to add it as a custom claim. See https://community.auth0.com/t/how-to-get-user-profile-structure-after-login-signup-fields-such-as-created-at-last-login-user-id/46382/8 for an example

**Comment by peter-yolabs** [comment]
@adamjmcgrath I see, that answer shows it's possible, but isn't very clear on how to achieve this.  
I'll do some more digging and reading, but it would be great if there was a straightforward guide that covers all the parts of doing something like this, rather than just a code snippet in an answer deep in the forum.  Not easy to find at all.

**Comment by adamjmcgrath** [comment]
Thanks for the feedback @peter-yolabs 

We have lots of SDKs and it doesn't really scale for each one to teach you how to use the product (we have docs and forums for that)

Also, here's the offical doc on adding custom claims https://auth0.com/docs/tokens/create-namespaced-custom-claims
