### ISSUE TITLE
Using HandlerError/AccessTokenError for better error handling with TypeScript

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [auth0/nextjs-auth0#479]
### Describe the problem you'd like to have solved

The documentation suggests the following JavaScript try/catch pattern for error handling when modifying the behavior of the callback and login endpoints:
```javascript
export default handleAuth({
  async callback(req, res) {
    try {
      await handleCallback(req, res, { afterCallback });
    } catch (error) {
      res.status(error.status || 500).end(error.message);
    }
  }
});
```

Depending on TypeScript configuration, the pattern may or may not translate directly to TypeScript. To use this pattern with true type safety, `error` needs to have the underlying `HandlerError` type, which is not always evident from the documentation.

The recently released TypeScript 4.4 introduces the [`useUnknownInCatchVariables` flag](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables) which changes the default type of catch clause variables from `any` to `unknown`. It was added to the strict family of options, so it is likely to affect many projects. Users of TypeScript and `@auth0/nextjs-auth0` may be affected by this flag, and `@auth0/nextjs-auth0` could do a few things to make enabling it easier.

### Describe the ideal solution

`HandlerError` and `AccessTokenError` could be made more easily importable as exports from the main module, rather than having to import from `@auth0/nextjs-auth0/dist/utils/error`.

The `AfterCallback` and `GetLoginState` documentation could mention that `HandlerError` is the type of error being handled to ease the translation to TypeScript.

The `GetAccessToken` documentation could mention that `AccessTokenError` is the type of error being thrown.

## Alternatives and current work-arounds

`HandlerError` can be imported as `import type { HandlerError } from '@auth0/nextjs-auth0/dist/utils/errors'`. In order to safely use a `HandlerError` from an API route handler, this is an option:

```typescript
export default handleAuth({
  async callback(req, res) {
    try {
      await handleCallback(req, res, { afterCallback });
    } catch (_error) {
      const error = _error as HandlerError;
      return res.status(error.status || 500).end(error.message);
    }
  },
});
```

However, importing types from `@auth0/nextjs-auth0/dist/utils/errors` does not immediately work without also adding a dependency on `@types/http-errors`.

**Comment by Widcket** [comment]
cc @adamjmcgrath
