### ISSUE TITLE
Delete invalid Session

### ISSUE THREAD

**Issue by dkleber89** [auth0/nextjs-auth0#480]
I have multiple Apps the are working with the same Identity Provider ... So when some user login on one application (eg app 1) and then switch the app (eg. app 2) then i have implemented some silent login and he ist logged in also on app 2.

Everything is fine at this time.

When the user logged out on app 2 ... the session (session cookie) in app 1 is still valid because the end of the lifetime not reached.
When app 1 tries to get a new accessToken from the identity provider (in getInitialProps of _app) the he gets an error.

For me this is expected but there i have a Question:

**What is the correct way to delete the session cookie?**

I have tried with this:
``` ts
res.setHeader('set-cookie', `myCorrectSessionCookie=; expires=Thu, 01 Jan 1970 00:00:00 GMT`);
```

But it seems the library also setting this session cookie (When i call getSession or getAccessToken) in the same response with the old values and im not able to delete the cookie in this way.

Thanks for support

**Comment by adamjmcgrath** [comment]
Hi @dkleber89 - could you handle the error of `getAccessToken` and redirect the user to the logout?

**Comment by dkleber89** [comment]
Hi @adamjmcgrath thanks for the input ... this sounds possible ... i will give it a try

**Comment by Widcket** [comment]
@dkleber89 looks like your issue has been solved. I'll close this issue, please ping if you'd like to reopen it.
