### ISSUE TITLE
withApiAuthRequired Unauthorized Redirect Functionality

### ISSUE THREAD

**Issue by sdoironkcdus** [auth0/nextjs-auth0#482]
### Describe the problem you'd like to have solved

I would like the `withApiAuthRequired` function to be able to redirect the user to the login page if they are not authenticated.  Having a project that is entirely authentication required for both pages and APIs is ideal, but if the user's appSession expires (in my project's case because they leave the page open and come back to it hours/days later) and they don't switch to a different page, then every API request they make while on that page will respond with an error because they aren't able to access the APIs since they aren't authenticated anymore.

### Describe the ideal solution

Currently when a page is wrapped with the `withPageAuthRquired` function and the user is not authenticated, the user will be redirected to the login page.  It would be ideal and greatly appreciated if that same functionality could apply to the `withApiAuthRequired` wrapper function.

## Alternatives and current work-arounds

Any API that is wrapped with `withApiAuthRequired` will respond with a 401 error code if the user is not authenticated.  A workaround would be to explicitly handle anywhere that is calling a protected API (which is every API within my project's codebase) for a response code of 401 in order to properly log the user out via NextJs's `useRouter()` hook

### Additional information, if any

I am open to suggestions that would achieve the same result or similar if this solution isn't possible

**Comment by Widcket** [comment]
Hi @sdoironkcdus, thanks for raising this. You can create a wrapper for your API calls that handles the 401, and redirects the user to login. Something similar to the `useApi` [hook](withApiAuthRequired) in the example app (though that particular hook does not do a redirect, it is an example of a wrapper).

**Comment by Widcket** [comment]
@sdoironkcdus looks like your question has been answered, so I'll be closing this issue. Please ping if you'd like to reopen.

**Comment by ivorpad** [comment]
@sdoironkcdus This is what I did.

```js
const handleApiAuthRequiredError = (apiRoute: NextApiHandler) => {
  return async (req: NextApiRequest, res: NextApiResponse) => {
    const session = getSession(req, res);

    if (!session) {
      res.redirect("http://localhost:3000");
      return;
    }

    await apiRoute(req, res);
  };
};

export default handleApiAuthRequiredError(withApiAuthRequired(handler));
```
