### ISSUE TITLE
Get a new access token when URL changes

### ISSUE THREAD

**Issue by chris-hinds** [auth0/nextjs-auth0#489]
Is it possible to get a new access token when the page URL changes? I am trying to implement organisations within my web app and one user can be in multiple organisations but can have different permissions.

So when a user switches organisations I need to generate a new access token that has the correct permissions for that organisation.

Or can I simply request a new access token and pass in a parm to specify the org id and add the correct permissions that way?

**Comment by adamjmcgrath** [comment]
Hi @chris-hinds - in order to switch organisations you'll need to login again, you can do this silently using the suggestion here https://github.com/auth0/nextjs-auth0/issues/44#issuecomment-699487696

You will also want to pass the new `organisation` parameter to the `loginHandler`

**Comment by chris-hinds** [comment]
Thanks, @adamjmcgrath I actually just got that working myself. Except that I am using redirects from within a login action.

If a user is a member of more than 1 organisation, the action will redirect the user to a page where they can select their organisation.

Then the rule, gets the selected organisation once redirected to `/continue` and get the role and permissions for that user and that organisation adding them to the accessToken as custom claims

**Comment by adamjmcgrath** [comment]
Glad you got it working @chris-hinds
