### ISSUE TITLE
Custom State throws error on handleCallback

### ISSUE THREAD

**Issue by mintuz** [auth0/nextjs-auth0#49]
### Description

Support for custom state was recently merged into master as part of #41. I want to make use of this functionality however handleCallback is throwing the following error.  

```
state mismatch, expected hCjR7jFdawU2UruuliNuD9scqEU_hyYRs7KuS8ktV241c4U0cbflbeBsSmuiDcmB, got: {"redirectTo":"/progress"}
```

AuthorizeUrl generated (Removed sensitive parts)
```
https://xxxxxxxxxx.eu.auth0.com/authorize?client_id=xxxxxxx&scope=openid%20profile%20email&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fcallback&state=%7B%22redirectTo%22%3A%22progress%22%7D&auth0Client=xxxxxxxxxxxx
```

### Reproduction

**handleLogin**
```
import auth from "../../lib/auth";

export default async function login(req, res) {
  try {
    console.log(req.query);
    await auth.handleLogin(req, res, {
      authParams: {
        state: JSON.stringify({redirectTo:req.query.redirectTo}),
      }
    });
  } catch (error) {
    console.error(error);
    res.status(error.status || 400).end(error.message);
  }
}
```

**handleCallback**
```
import auth from "../../lib/auth";
export default async function callback(req, res) {
  try {
    console.log(req.query);
    await auth.handleCallback(req, res, { redirectTo: "/" });
  } catch (error) {
    console.error(error);
    res.status(error.status || 400).end(error.message);
  }
}

```

### Environment
- **Version of this library used:** 0.5.0
- **Version of the platform or framework used, if applicable:**  9.1.1
- MacOS Catalina

**Comment by qburnsFB** [comment]
Getting the same issue on my setup, trying to do a redirect

**Comment by mintuz** [comment]
I believe the purpose of randomBytes is to prevent CSFR with the alteration you made @qburnsFB that protection will disappear?

https://auth0.com/docs/protocols/oauth2/oauth-state

We probably want to do something similar to what the `authorize` method does within auth0 SDK

https://community.auth0.com/t/pass-custom-parameters-on-auth0-login-redirect/19075

**Comment by qburnsFB** [comment]
I used randombytes on the client side, similar to what [this user did](https://github.com/auth0/nextjs-auth0/issues/36#issuecomment-553947097).

**Comment by sandrinodimattia** [comment]
Starting from v0.12 you have better control over the state to include a `redirectTo`

```js
    await auth0.handleLogin(req, res, {
      getState: (req) => {
        return {
          someValue: '123',
          redirectTo: '/other-url'
        };
      }
    });
```
