### ISSUE TITLE
error - Error [BadRequestError]: checks.state argument is missing

### ISSUE THREAD

**Issue by samrath2007** [auth0/nextjs-auth0#491]
My api route:
```
import { handleAuth, handleCallback } from "@auth0/nextjs-auth0"
import prisma from "db"

const afterCallback = async (req, res, session, state) => {
  await prisma.user.create({
    data: {
      name: session.user.name as string,
      email: session.user.email as string,
      picture:
        (session.user.picture as string) ||
        "https://st4.depositphotos.com/4329009/19956/v/600/depositphotos_199564354-stock-illustration-creative-vector-illustration-default-avatar.jpg",
    },
  })
  return session
}

export default handleAuth({
  async callback(req, res) {
    await handleCallback(req, res, { afterCallback })
  },
})
```
The error:
```
error - Error [BadRequestError]: checks.state argument is missing
    at new HandlerError (/Users/sam/code/my-project/node_modules/@auth0/nextjs-auth0/dist/utils/errors.js:49:28)
    at Object.<anonymous> (/Users/sam/code/my-project/node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:39:31)
    at step (/Users/sam/code/my-project/node_modules/@auth0/nextjs-auth0/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Users/sam/code/my-project/node_modules/@auth0/nextjs-auth0/node_modules/tslib/tslib.js:124:57)
    at rejected (/Users/sam/code/my-project/node_modules/@auth0/nextjs-auth0/node_modules/tslib/tslib.js:115:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 400,
  page: '/api/auth/[...auth0]'
}
```
### Environment

- **Version of this library used:**
  - 1.5.0
- **Which framework are you using, if applicable:**
  - Nextjs
- **Other modules/plugins/libraries that might be involved:**
  - Prisma maybe?

**Comment by adamjmcgrath** [comment]
Hi @samrath2007 - `checks.state argument is missing` suggests that you don't have a `state` cookie to check when you return to your application after login.

Are you hitting that route as part of your login flow? And if so, can you share the url that you logged in from and the callback url, along with what cookeis are being sent to the callback url?

**Comment by samrath2007** [comment]
I actually rewrote my login flow, it works now. I do have a question though, if a user signs up with email how can I make them also enter their name?

**Comment by FDiskas** [comment]
Running e2e tests in this repository also points to the same problem
![Screenshot from 2021-09-13 22-25-16](https://user-images.githubusercontent.com/468006/133144542-1a9b4079-cd68-4f10-9c00-e7ce11bfa742.png)

**Comment by hacknlove** [comment]
This error was driving me crazy because it worked on some browsers and failed on some others.... until I realized the reason.

It worked with https and it failed with http

So if you are experiencing this issue, check that too.

**Comment by adamjmcgrath** [comment]
@samrath2007 - have a look at https://auth0.com/docs/connections/database/require-username

@FDiskas - please raise a separate issue with details on how you're running the end to end tests if you want me to investigate
