### ISSUE TITLE
Maintain consistent user session data

### ISSUE THREAD

**Issue by srbagg** [auth0/nextjs-auth0#492]
### Describe the problem you'd like to have solved

Consider the following scenario:
1. An user is created by Admin on Auth0 and assigned a role.
2. User logs into the application using this SDK and user agent receives the session cookie.
3. Admin revokes the user by removing the assigned role in step-1.
4. The previous cookie still exists on user agent and is valid until it expires or user re-logs-in again
5. The application continues to serve all the data as the role is present in old id_token / accessToken.

User session data inconsistency occurs here as application is using old session state info. while Auth0 has updated session state for user.

### Describe the ideal solution

There should be a way in SDK to check and update the session info on client or force user to logout or someway to invalidate the existing session in this scenario.

**Comment by srbagg** [comment]
Hello @adamjmcgrath, I tried your suggestion like this:

```
// pages/api/auth/[...auth0].ts

export default handleAuth({
  profile: (req, res) => handleProfile(req, res, { refetch: true }),
});
```

Upon these changes, the same issue was happening i.e. I updated the role for the user while he is logged in and still the old id_token was used. Id_token and accessToken does not get updated. Not sure if I'm missing anything here.

**Comment by adamjmcgrath** [comment]
> We've setup custom rule to inject roles in id_token & accessToken on Auth0.

Rules don't run on `/userinfo` - only when you authenticate.

You'll need to use [silent auth](https://auth0.com/docs/login/configure-silent-authentication) to trigger the rule without user interaction, eg

```js
await handleLogin(req, res, {
  authorizationParams: {
    prompt: 'none'
  }
});
```

**Comment by adamjmcgrath** [comment]
Closing as I think https://github.com/auth0/nextjs-auth0/issues/492#issuecomment-919049563 answers your question
