### ISSUE TITLE
/api/auth/logout returnTo parameter not redirecting

### ISSUE THREAD

**Issue by chrispeterson3** [auth0/nextjs-auth0#497]
### Describe the problem you'd like to have solved
The `returnTo` query param for the `/api/auth/logout` endpoint does not seem to be working. Is this supported with this package?

The README refers to a `returnTo` parameter on the login endpoint, but not documentation for logout.

**Comment by SebitaCR14** [comment]
@chrispeterson3  i used the returnTo.  In `[...auth0].js` you need to write something like that.
``` import { handleAuth, handleLogin } from '@auth0/nextjs-auth0';
  export default handleAuth({
  async login(req, res) {
    try {
      await handleLogin(req, res, {
        authorizationParams: getLoginState(req, res),
        returnTo: '/foo'
      });
    } catch (error) {
      res.status(error.status || 500).end(error.message);
    }
  }
});```

**Comment by Widcket** [comment]
Hi @chrispeterson3, thanks for raising this.
The SDK does support `returnTo` for logout, see https://github.com/auth0/nextjs-auth0/blob/main/src/handlers/logout.ts#L16
There's also a test for it: https://github.com/auth0/nextjs-auth0/blob/main/tests/auth0-session/handlers/logout.test.ts#L135
