### ISSUE TITLE
UserProvider throwing error when server-side rendering _app.tsx

### ISSUE THREAD

**Issue by nickythorne** [auth0/nextjs-auth0#500]
The documentation mentions that `<UserProvider>` should be rendered inside the custom app file `_app.tsx`. When doing that using `next@11.1.2` and `@auth0/nextjs-auth0@1.5.0`, this results in the following error:

> error - ./node_modules/cacheable-lookup/source/index.js:10:2
Module not found: Can't resolve 'dns'
Import trace for requested module:
./node_modules/got/dist/source/core/index.js
./node_modules/got/dist/source/create.js
./node_modules/got/dist/source/index.js
./node_modules/openid-client/lib/helpers/request.js
./node_modules/openid-client/lib/index.js
./node_modules/@auth0/nextjs-auth0/dist/auth0-session/transient-store.js
./node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
./node_modules/@auth0/nextjs-auth0/dist/index.js
./src/pages/_app.tsx
 

`_app.tsx` file:

```
function App({ Component, pageProps }: AppProps) {
    const [queryClient] = React.useState(() => new QueryClient());
    return (
        <QueryClientProvider client={queryClient}>
            <Hydrate state={pageProps.dehydratedState}>
                <UserProvider user={pageProps.user}>
                    <Bootstrap appName={Package.name}>
                        <Component {...pageProps} />
                    </Bootstrap>
                </UserProvider>
            </Hydrate>
        </QueryClientProvider>
    );
}
```

Minimal `_app.tsx` file:

```
function App({ Component, pageProps }: AppProps) {
    return (
        <UserProvider user={pageProps.user}>
            <Component {...pageProps} />
        </UserProvider>
    );
}
```

**Comment by Widcket** [comment]
Hi @nickythorne, thanks for raising this.

The SDK currently uses Next.js `11.1.2` for development:
https://github.com/auth0/nextjs-auth0/blob/main/package.json#L93

That version is then used in the kitchen sink example app, which is used to run smoke tests on every PR. It has been working correctly with that Next.js version. I also tried it manually, and compiles successfuly:

<img width="965" alt="Screen Shot 2021-09-17 at 00 24 23" src="https://user-images.githubusercontent.com/5055789/133719258-d50a9c0f-942f-47b0-83ed-2f04fa64fd68.png">

I'll close this issue for now, as seems to be related to your project. Please ping if you'd prefer to reopen.
