### ISSUE TITLE
Callback fails when processing member invitation redirect

### ISSUE THREAD

**Issue by nickythorne** [auth0/nextjs-auth0#502]
Please include the following information in your post:

SDK: nextjs-auth0
SDK Version: 1.5.0
Platform Version: Node v16.2.0

We are attempting to invite users to an organisation and are hitting an issue whereby the callback endpoints (within the default nextjs-auth0 `/api/auth/callback` endpoint is failing due to a state mismatch error).

Here are the steps taken:

1. Create Organisation using Management API (https://auth0.com/docs/organizations/configure/create-organizations#management-api)

2. Enable username/password connection for that Organisation using management API (https://auth0.com/docs/organizations/configure/enable-connections#management-api)

3. Inviting a list of users to the newly created organisation using the Send Membership Invitations API (https://auth0.com/docs/organizations/configure/send-membership-invitations#management-api)

3. Invitee receives the invitation email with a login link (defined in tenant settings) which includes the invitation and organization parameters. Example URL `https://{host}/api/auth/login?invitation=xgHtmW8bgR0MdvMM3hM9yCPdKE6ufG9Y&organization=org_ssaeGaKNJBfrfsQ&organization_name=test` 

3. Invitee receives the invitation email with a login link (defined in tenant settings) which includes the invitation and organization parameters. Example URL `https://{host}/api/auth/login?invitation=xgHtmW8bgR0MdvMM3hM9yCPdKE6ufG9Y&organization=org_ssaeGaKNJBfrfsQ&organization_name=test` 

4. Modified the default login handler that nextjs-auth0 provides in order to forward the incoming organization and invitation params and set them as custom authorization params. 

```
export default async function loginHandler(req: NextApiRequest, res: NextApiResponse) {
    return await handleLogin(req, res, {
        authorizationParams: {
            organization: req.query.organization as string,
            invitation: req.query.invitation as string,
        },
    });
}
```

5. The library redirects the user to the /authorize endpoint, forwarding the organization and invitation values and the user is presented with the custom organisation-branded invitation acceptance screen.
![Screenshot 2021-09-22 at 16 17 16](https://user-images.githubusercontent.com/860710/134374256-2903f725-890f-4f8c-8eb8-31f90e26d1e2.png)

6. The user enters a password, and clicks continue. They are presented with a consent page where they authorize the app. 
![Screenshot 2021-09-22 at 16 17 58](https://user-images.githubusercontent.com/860710/134374290-96713649-b95e-4c0a-88ba-794821f38639.png)

7. When accepted, auth0 redirects back to the callback handler in nextjs-auth0 with code and state parameters. `http://{host}/api/auth/callback?code=QgwBGJrS5suZZMBe&state=eyJyZXR1cm5UbyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMS8ifQ`

 This is where the callback handler in the SDK fails with an Error stating that there's a state mismatch:
> state mismatch, expected eyJyZXR1cm5UbyI6Ii8ifQ, got: eyJyZXR1cm5UbyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMS8ifQ

When decoding these state JWTs it's because the `returnTo` values are different. 
SDK expects:
```
{
  "returnTo": "/"
}
```

Auth0 is sending:
```
{
  "returnTo": "http://localhost:3001/"
}
```
Question is why is Auth0 sending this value and why are these values different during the invitation process? 

To attempt to fix this issue, I have added an implementation for `getLoginState` option in the `handleLogin` function, in order to send a fixed `returnTo` value of 'http://localhost:3001/'.  

```
    return await handleLogin(req, res, {
        getLoginState: () => {
            return {
                redirectTo: 'http://localhost:3001/',
            };
        },
        authorizationParams: {
            organization: req.query.organization as string,
            invitation: req.query.invitation as string,
        },
```

But this results in the following error:
> Error [BadRequestError]: checks.state argument is missing

This means the user hits an "Internal Server Error" page. The interesting this is that the whole invitation process seems to have work, and the invitee does have an active session. But the callback failing prevents the end-to-end flow from working seamlessly.

Any help would be greatly apprechiated.

**Comment by Widcket** [comment]
Hi @nickythorne, thanks for raising this.

I see that `https://{host}/api/auth/login?invitation=xgHtmW8bgR0MdvMM3hM9yCPdKE6ufG9Y&organization=org_ssaeGaKNJBfrfsQ&organization_name=test` is using HTTPS, as expected, since the Dashboard enforces that for the application login URL.
But then your callback URL is `http://{host}/api/auth/callback?code=QgwBGJrS5suZZMBe&state=eyJyZXR1cm5UbyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMS8ifQ`, that is, HTTP. 

Does it happen if you use HTTPS?
Also, do you have the SDK set up with a custom cookie configuration?

**Comment by nickythorne** [comment]
Thanks for the response.

Yes it happens for HTTPs also have checked in a development tenant and production tenant (development being HTTP and prod being HTTPS).

The only custom cookie configuration we have is setting the cookie name via `AUTH0_SESSION_NAME` and specifying `AUTH0_COOKIE_DOMAIN`. The callback works for normal signup/login flows, it's only the invitation acceptance flow that seems to throw this error.

**Comment by adamjmcgrath** [comment]
Hi @nickythorne - if you're running your application on https and logging in via `https://{host}/api/auth/login`, then your callback url should also be `https`, this comes from `AUTH0_BASE_URL`, so this should be `https://{host}/`

This SDK will set a secure cookie on `https` when you login, that can't be read from `http` on your callback. Which is why you're getting a state mismatch.

**Comment by adamjmcgrath** [comment]
Closing as I think https://github.com/auth0/nextjs-auth0/issues/502#issuecomment-928063120 should answer your question, feel free to ping me if you want to reopen it
