### ISSUE TITLE
Next.js, external GraphQL API don't work as per documentation 

### ISSUE THREAD

**Issue by blazestudios23** [auth0/nextjs-auth0#503]
### Description

I'm using Next.js on the front end and Node + Apollo on the backend. 

I've spent the last few days looking over all the resources on how to connect an external GraphQL API to Next + Auth0 and I either get an error about the token being expired or an error about malformed JWT. 

> Provide a clear and concise description of the issue, including what you expected to happen.

### Reproduction

I'm using a proxy in the API route to add an auth_token to GraphQL requests, below is the code for the proxy:

/pages/api/[...all].ts
```

import { NextApiRequest, NextApiResponse } from "next"
import httpProxyMiddleware from "next-http-proxy-middleware"
import { withApiAuthRequired, getSession, getAccessToken } from '@auth0/nextjs-auth0';

export default withApiAuthRequired(async (req: NextApiRequest, res: NextApiResponse) => {

  const { accessToken } = await getAccessToken(req, res, { 
    refresh: true
  });
  
      return (httpProxyMiddleware(req, res, {
        // You can use the `http-proxy` option
        target: `${process.env.NEXT_PUBLIC_GRAPHQL_API_ENDPOINT}/graphql`,
        // In addition, you can use the `pathRewrite` option provided by `next-http-proxy-middleware`
        pathRewrite: [{
          patternStr: '^/graphql',
          replaceStr: '/v1/graphql'
        }, {
          patternStr: '^/api',
          replaceStr: ''
        }],
        headers: {
          authorization: `Bearer ${accessToken}`
        }
      })
  )});
```

This sends a token, which is not a complete JWT. 

The recommend code for parsing this token is below, the code is on several Next.Js example projects:

```
const client = jwksClient({
  jwksUri: `${process.env.AUTH0_DOMAIN}/.well-known/jwks.json`,
});

function getKey(header: any, cb: any) {
  client.getSigningKey(header.kid, function (err, key) {
    // @ts-ignore
    const signingKey = key.publicKey || key.rsaPublicKey;
    cb(null, signingKey);
  });
}

interface Auth0User {
  email: string;
}

export const getAuth0User = (req: Request): any => {
  // simple auth check on every request
  const token = req.headers?.authorization?.split(' ')[1];

  if (!token) {
    return { email: null };
  }

  verify(
    token,
    getKey,
    {
      audience: process.env.API_IDENTIFIER as string,
      issuer: `${process.env.AUTH0_DOMAIN}/`,
      algorithms: ['RS256'],
    },
    (err, decoded: any) => {
      if (err) {
        throw new Error('jwt verify error: ' + err.message);
      }
      return decoded;
    }
  );
};
```

The response I get is below:

```
Auth0User:  Error: jwt verify error: jwt malformed

```

### Environment
Front end:

```
"@apollo/client": "^3.3.8",
"@apollo/react-ssr": "^4.0.0",
"@auth0/nextjs-auth0": "^1.5.0",
"next-http-proxy-middleware": "^1.1.1",
```

Back end:
```
"jsonwebtoken": "^8.5.1",
 "jwks-rsa": "^2.0.4",
```

**Comment by adamjmcgrath** [comment]
Hi @blazestudios23 - in order to het a JWT access token you must specify an audience, see https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#access-an-external-api-from-an-api-route and https://auth0.com/docs/security/tokens/access-tokens for more info

**Comment by blazestudios23** [comment]
I've updated my code to the following, which still doesn't resolve the issue:

pages/api/auth/[...auth0].ts

```
import { handleAuth, handleLogin } from '@auth0/nextjs-auth0';

function getParameterByName(name: string, url: string | undefined) {
    if (!url){
        return null
    }
    name = name.replace(/[\[\]]/g, '\\$&');
    var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)'),
        results = regex.exec(url);
    if (!results) return null;
    if (!results[2]) return '';
    return decodeURIComponent(results[2].replace(/\+/g, ' '));
}


export default handleAuth({
    async login(req, res) {
        try {
            await handleLogin(req, res, {
                authorizationParams: {
                audience: process.env.API_IDENTIFIER ,
                scope: 'openid profile email offline_access'
                },
                returnTo: redirectUrl,
            });
        } catch (error: any) {
            res.status(error.status || 400).end(error.message);
        }
    },
});
```

I'm still only getting a token that looks like this:
```
Y3YQIVvf-PcAP-guztEBsIvOVMH7G09z
```

This doesn't decode on with the backend code provided in all the examples for a Node/GraphQL server, which I pasted at the start of the thread. 

What am I missing here?

**Comment by blazestudios23** [comment]
I did finally get a JWT after clearing all the app data in the front end and re-logging in. 

But I'm still not getting expected behavior. I'm trying to get the user's email in the token, but this is all the data I get in the token:

```
{
  iss: 'https://domain.auth0.com/',
  sub: 'google-oauth',
  aud: [
    'https://domain.com',
    'https://domain.auth0.com/userinfo'
  ],
  iat: 23421412,
  exp: 123212,
  azp: 'somenchars',
  scope: 'openid profile email'
}

```

How do I get the users email in this JWT?

**Comment by adamjmcgrath** [comment]
Hi @blazestudios23 - the `email` scope will add the email to the ID Token (not the Access Token)

> The only user information the access token possesses is the user ID, located in the sub claim

See https://auth0.com/docs/security/tokens#access-tokens

If you need the info in the access token as well, you should add this via [Rule](https://auth0.com/docs/rules) as [custom claim](https://auth0.com/docs/configure/apis/scopes/sample-use-cases-scopes-and-claims#add-custom-claims-to-a-token)

**Comment by blazestudios23** [comment]
The final part to get the email required that I go the Auth0 consult to auth pipeline -> rules.

Create a rule with the below code:

```
function (user, context, callback) {
  context.accessToken.custom_email = user.email;
  context.accessToken['https://somevalue.com/email'] = user.email;
  return callback(null, user, context);
}

```
