### ISSUE TITLE
Vercel hosting docs should be brought up to the top-level README

### ISSUE THREAD

**Issue by grempe** [auth0/nextjs-auth0#505]
For anyone hosting a Next.js app on Vercel (many users of this lib I presume) it is very important to understand how the integration with preview environments will work.

After finding several active issues on this I finally found the following buried in the examples/README.md file:

https://github.com/auth0/nextjs-auth0/tree/main/examples#hosting-on-vercel

This was the important info about the single problematic environment variable `AUTH0_BASE_URL` that I needed to get Vercel preview deployments to work with Auth0.

It would also be helpful if it was further described that once you make the suggested commit to add the `.env.production` file that you go into the Vercel GUI and override `AUTH0_BASE_URL` for __every__ environment that has a fixed URL (e.g. production, staging). The `Development` env should set this to `http://localhost:3000` and the general `Preview` enviroment should have this variable unset, thereby defaulting to the `$VERCEL_URL`.

Please promote this info up to the main top-level README.md file.

See also: https://github.com/auth0/nextjs-auth0/issues/417#issuecomment-877091950

**Comment by adamjmcgrath** [comment]
Hi @grempe - thanks for the suggestion

They're quite long the Vercel deploy docs, also Vercel is just one of many platforms user's of this SDK deploy to. That said, I'm happy ot add a link to it from the README.

> It would also be helpful if it was further described that once you make the suggested commit to add the .env.production file that you go into the Vercel GUI and override AUTH0_BASE_URL for every environment that has a fixed URL (e.g. production, staging).

We do this already [here](https://github.com/auth0/nextjs-auth0/tree/main/examples#production-deployments) - but perhaps we should change the name to something other than "Production deployments"
