### ISSUE TITLE
Redirect user to auth0 from Page.getInitialProps

### ISSUE THREAD

**Issue by fromi** [auth0/nextjs-auth0#51]
Page.getInitialProps can be executed on the server side.
When it is the case, and the page is restricted to authenticated user, I want to redirect immediatly unauthenticated users to Auth0 login page.
I tried calling `await login(req, res)` inside getInitialProps. I requires a change in login API route: replace NextApiRequest and NextApiResponse by IncomingMessage and ServerResponse, but it is fine because `auth0.handleLogin` accept those types.

Unfortunately, the callback does not work, I get this error message: "Invalid request, an initial state could not be found". I suspect the initial state is stored somewhere when handleLogin is called from the client side, but nothing happens when it is called from the server side inside getInitialProps.

Could you please add or document a way to redirect to auth0 from inside a getInitialProps function?

**Comment by pks1989** [comment]
Hi ! 

I use this way: 
`
...
const pageInitialData = async ({ req, res, reduxStore }) => {
  if (typeof window === 'undefined') {
    const result = await auth0.getSession(req);
    if (!result) {
      res.writeHead(302, {
        Location: '/api/login',
      });
      res.end();
      return {};
    }
    // my stuff after authorization
    // const { dispatch } = reduxStore;
    // await dispatch(getInitialProjects(res));
    // const { upsertProjectUser } = await dispatch(
    //   upsertLoggedUser({ email: result.user.email, name: result.user.name }),
    // );
    // await dispatch(getAllUsers());
    // await dispatch(getInitialUserData(upsertProjectUser));

    return result.user;
  }
  return {};
};`

and in pages/api/login
`
import auth0 from '../../auth0config';

export default async function login(req, res) {
  try {
    await auth0.handleLogin(req, res);
  } catch (error) {
    res.status(error.status || 500).end(error.message);
  }
}

`

**Comment by sandrinodimattia** [comment]
I updated the `basic-example` with a HOC that shows how to do this for SSR pages:

```js
const Profile = ({ user }) => (
  <Layout user={user}>
    <h1>Profile</h1>

    <div>
      <h3>Profile (server rendered)</h3>
      <pre>{JSON.stringify(user, null, 2)}</pre>
    </div>
  </Layout>
);

export default withAuth(Profile);
```

If a user is available `withAuth` will make expose it in the props, otherwise the user will be redirected to the login page.
