### ISSUE TITLE
Logout not logging out

### ISSUE THREAD

**Issue by francescovenica** [auth0/nextjs-auth0#510]
### Description

Having a rule like this:
```
async function myRule(user, context, callback) {
  if (!user.email_verified) {
    return callback(new UnauthorizedError("email_not_verified"));
  }
}
```

When the user is a new user and the email is not verified I redirect him to a page `/verification-email` with some text and a button to go back to the login page. The button redirect the user to `/api/auth/logout` that redirect the user to the login page, the issue is that the user never logout because when it is redirected to `/api/auth/login` it is still logged in as it is redirected to the `/email-verification` page...I would like to have a way completely logout the user 

### Environment

v. 1.3.0
node: v14.17.3
chrome

**Comment by Widcket** [comment]
Hi @francescovenica, seems like this is not an SDK issue/bug, but a matter of correctly setting up the rule.
I'll be closing this issue; if you need assistance please raise a support ticket.
