### ISSUE TITLE
Request: a route that would trigger new verification emails

### ISSUE THREAD

**Issue by mattcasey** [auth0/nextjs-auth0#514]
### Describe the problem you'd like to have solved

User hasn't verified their email yet, and perhaps cannot find the email in their inbox or it has been a while.

### Describe the ideal solution

handleAuth() would generate a new route like `/resendVerification` that I could call from the browser.

## Alternatives and current work-arounds

An example in the wiki on how to call the route listed on https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email.

It would be great if this library handled this case. It's been plug-and-play for me otherwise and I'd rather not have to learn how to make API calls myself.

**Comment by mattcasey** [comment]
In case anyone is wondering, it took me about an hour to figure out how to do it on my own. It works, but I still feel like this lib could just offer it as a feature:
```
export default async function resendVerification (req: NextApiRequest, res: NextApiResponse) {
  const session = getSession(req, res);
  const uuid = session!.user.sub;
  const { access_token } = await POST(process.env.AUTH0_ISSUER_BASE_URL + '/oauth/token', {
    grant_type: 'client_credentials',
    client_secret: process.env.AUTH0_CLIENT_SECRET,
    client_id: process.env.AUTH0_CLIENT_ID,
    audience: process.env.AUTH0_AUDIENCE
  }, {
    headers: {
      Authorization: `Bearer ${process.env.AUTH0_MGMT_API_ACCESS_TOKEN}`
    }
  });

  await POST(process.env.AUTH0_ISSUER_BASE_URL + '/api/v2/jobs/verification-email', {
    user_id: uuid
  }, {
    headers: {
      Authorization: `Bearer ${access_token}`
    }
  });
  ```

**Comment by Widcket** [comment]
Hi @mattcasey, thanks for raising this.

It's unlikely we'll add this to the library, as it's a use case a bit too specific, and this library is not meant to be a Management API client.

Note that you can use [node-auth0](https://github.com/auth0/node-auth0) to interact with the Management API.
