### ISSUE TITLE
User can't logout / can't switch accounts when the authentication is rejected by a rule

### ISSUE THREAD

**Issue by eduards** [auth0/nextjs-auth0#517]
### Description

Users that authenticate with Google Auth whose login fails due to an `UnauthorizedError` that was raised in an Auth0 rule can't switch to another account and thus are stuck.

### Reproduction

- We have to first create a rule that raises an error for certain accounts via `return callback(new UnauthorizedError('Access denied.'));` (simplest example: `if (user.email === 'john.doe@google.com') return callback(new UnauthorizedError('Access denied.'));`)

- Then we attempt to log in with this Google account. This fails as expected and redirects the user to `/api/auth/callback?error=unauthorized&error_description=Access%20denied`

- To allow the user to login with a different account we redirect them to `/api/auth/login`. However, this doesn't show the login screen. Instead the user gets redirected back to `/api/auth/callback?error=unauthorized&error_description=Access%20denied` page.

- The above seems to be the correct behaviour. Let's try to log out first before redirecting the user to the login screen via `api/auth/login`: We redirect the user to `/api/auth/logout`. This will send redirect the user back to the logout callback URL. 

- It seems reasonable to expect that now, after logging out, when the user attempts to access `/api/auth/login`, they should see the login screen and be able to log in with a different account. However, this just redirects them back to the error page `/api/auth/callback?error=unauthorized&error_description=Access%20denied`.

- The user is now stuck. Neither can they log in with a different account nor can they log out so that the login screen is shown again.

### Workaround

I found a workaround: Rather than logging out via `/api/auth/logout` (which doesn't work as described above) we can send the user to `https://[CUSTOM_DOMAIN]/v2/logout?&client_id=[CLIENT_ID]`. After this call, when the user attempts to login via `/api/auth/login` they won't get redirected to the error callback page anymore. Instead, they will see the login view and are able to log in with a different account (hopefully with one that the rule doesn't reject 🤞)

### Notes

- I have a custom domain set up.

### Environment

> Please provide the following:

- **Version of this library used:** 1.5.0
- **Version of the platform or framework used, if applicable:** Next.js 11.1.2
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hi @eduards - thanks for raising this

> The above seems to be the correct behaviour. 

Yes, in order to rety login after a rule error you need to add a directive in the login request to force the display of the login page or logout of auth0 and login again see https://auth0.com/docs/rules/raise-errors-from-rules#retry-login-after-a-rule-error.

This library wont attempt to log you out if you don't have a session, so you'll need to use the Auth0 api directly if you want to go for the Auth0 logout option (as you described in your workaround)

The other option is to force the display of the login, which you can do by passing `prompt=login` to the login request, eg 

```js
// api/custom-login.js
import { handleLogin } from '@auth0/nextjs-auth0';

export default async function customLogin(req, res) {
  try {
    await handleLogin(req, res, { authorizationParams: { prompt: 'login' } });
  } catch (error) {
    res.status(error.status || 400).end(error.message);
  }
}
```

Closing this, feel free to ping me if you want me to reopen
