### ISSUE TITLE
withApiAuthRequired says not_authenticated when we use own instance of Auth0 SDK

### ISSUE THREAD

**Issue by gabor-at-reed** [auth0/nextjs-auth0#534]
### Description

We have to create our own instance of this SDK because we have secrets from the AWS secret store. We followed the [official readme](https://github.com/auth0/nextjs-auth0/blob/v1.6.1/EXAMPLES.md#protect-an-api-route) and [examples](https://github.com/auth0/nextjs-auth0/blob/v1.6.1/EXAMPLES.md#protecting-a-client-side-rendered-csr-page), and we found some [official guidance](https://github.com/auth0/nextjs-auth0/issues/376#issuecomment-833488401) on how we should use the async `withPageAuthRequired()` . However, it doesn't work with `withApiAuthRequired()`. This method always throws error like: `{"error":"not_authenticated","description":"The user does not have an active session or is not authenticated"}`
The page itself works fine, the user has to be authenticated to see the page, but the API endpoint call always comes back with this error, even the user is logged in.

Any help, suggestions or guidance would be much appreciated!

### Reproduction

Relevant code snippets from our codebase:

`pages/protected-api-example.js`

```
import {auth0} from '../../../utils/auth0';
import {fetchSecretData} from '../../../services/examples/secret-data';

const ProtectedAPIExample = props => {
  // stuff...

  return (
    <>
      <p>more stuff...</p>
    </>
  );
};

export const getServerSideProps = async context => {
    const instance = await auth0();

    return instance.withPageAuthRequired({
        getServerSideProps: async () => {
            const secretData = await fetchSecretData();

            const session = instance.getSession(context.req, context.res);
            console.log('session: ', session); // we got the logged in user data succesfully

            return {
                props: {
                  // ...
                }
            };
        }
    })(context);
};

export default ProtectedAPIExample;

```

`services/examples/secret-data.js`

```
export const fetchSecretData = () => {
    const _apiUrl = 'http://localhost:3000/api/protected';

    return fetch(_apiUrl).then(response => response.json());
};

```

`pages/api/protected.js`

```
import {auth0} from '../../../utils/auth0';

const result = async (req, res) => {
    const instance = await auth0();

    const sessionApi = instance.getSession(req, res);
    console.log('sessionApi: ', sessionApi); // it says null here

    return instance.withApiAuthRequired(async () => {
        const {user} = instance.getSession(req, res); // we don't reach this point because it thinks the user is not logged in...
        console.log('user: ', user);
        res.json({protected: 'My Secret', id: user.sub});
    })(req, res);
};

export default result;

```

### Environment

- **Version of this library used:** 1.6.1
- **Version of the platform or framework used, if applicable:** Next.js 12.0.2

**Comment by adamjmcgrath** [comment]
Hey @gabor-at-reed - thanks for raising this.

Your request `/api/protected` is not being made from a browser, so there is not cookie on the request. This is why your `/api/protected` route thinks you're logged out.

You could do something wonky like manually adding the cookie to that request (this is actually what `next-auth` [does](https://github.com/nextauthjs/next-auth/blob/main/src/client/index.js#L320-L321))

```js
export const fetchSecretData = (req) => {
    const _apiUrl = 'http://localhost:3000/api/protected';
    return fetch(_apiUrl, { headers: { cookie: req.headers.cookie } } ).then(response => response.json());
};
```

But it's not recommended, because you're basically invoking 2 serverless functions to fulfil `/protected-api-example` when 1 will do.

Better to use the logic from `/api/protected` directly in `getServerSideProps`

See for reference:
> Note: You should not use fetch() to call an API route in getStaticProps. Instead, directly import the logic used inside your API route. You may need to slightly refactor your code for this approach.
https://nextjs.org/docs/basic-features/data-fetching

**Comment by gabor-at-reed** [comment]
@adamjmcgrath Thanks for your help! It's working now. 🎉
