### ISSUE TITLE
Using CSR withPageAuthRequired with an own instance

### ISSUE THREAD

**Issue by gabor-at-reed** [auth0/nextjs-auth0#536]
### Description

Could you provide a solution for that scenario when we want to use the `withPageAuthRequired()` on CSR, but with an own instance? We use AWS secret manager to get the secrets for Auth0. 

Following [your guidance](https://github.com/auth0/nextjs-auth0/issues/376#issuecomment-833488401) and the official Auth0 example from [here](https://github.com/auth0/nextjs-auth0/blob/v1.6.1/EXAMPLES.md#protecting-a-client-side-rendered-csr-page), we try to get this working with a code like this:

```
import {auth0} from '../../../utils/auth0';

const AuthRequiredCSRExample = props => {
  // stuff...

  return (
    <>
      <p>more stuff...</p>
    </>
  );
};

const instance = await auth0();

export default instance.withPageAuthRequired(AuthRequiredCSRExample);

```

In the `next.config.js` I had to enable the top-level-await feature:

```
config.experiments = {
  ...config.experiments,
  topLevelAwait: true
};
```

But now I got an error message on the page which says:
![image](https://user-images.githubusercontent.com/1906302/140893645-23c6dbb1-a584-41b7-b461-b0402b44452f.png)

It looks like if we have to get the secrets from somewhere (e.g. AWS secret manager), we lose the ability to use this CSR `withPageAuthRequired()` feature. But correct me, please if I'm wrong!

Any help would be appreciated!

### Environment
- Version of this library used: 1.6.1
- Version of the platform or framework used, if applicable: Next.js 12.0.2

**Comment by Widcket** [comment]
Hi @gabor-at-reed, thanks for raising this.

Please refer to https://github.com/auth0/nextjs-auth0/blob/v1.6.1/EXAMPLES.md#create-your-own-instance-of-the-sdk for more information about setting up a custom instance.

```js
const auth0 = initAuth0();

const { withPageAuthRequired } = auth0;
```

**Comment by gabor-at-reed** [comment]
@Widcket Please notice, we need to get the environment variables' values async as we are fetching them from AWS Secret Manager. That's why I referred to @adamjmcgrath 's solution from another issue where he showed how we could get the Auth0 instance async and use it `withPageAuthRequired()`.

Your example and the official link provide a solution for a standard use case where you don't need to use async. Unfortunately, that doesn't work for us.

**Comment by adamjmcgrath** [comment]
Hi @gabor-at-reed - you should be able to use the named exports for browser methods, eg (useUser, withPageAuthRequired(CSR))

```js
import { withPageAuthRequired } from '@auth0/nextjs-auth0';

const AuthRequiredCSRExample = props => {
  // stuff...

  return (
    <>
      <p>more stuff...</p>
    </>
  );
};

export default withPageAuthRequired(AuthRequiredCSRExample);
```

`initAuth0` is just for the server side methods.

Let me know if this doesn't work and I'll investigate

**Comment by gabor-at-reed** [comment]
@adamjmcgrath Thank you! It does make sense now.
