### ISSUE TITLE
Invalid request, an initial state could not be found (a0:state cookie)

### ISSUE THREAD

**Issue by grahambryan** [auth0/nextjs-auth0#54]
I moved this from @sandrinodimattia personal repo to here. 

Great example, it has been very helpful! I have got it to work locally on my machine but I am having trouble getting it to work in a production environment (I am not using now). 

I launch my application with this `HOST=0.0.0.0 PORT=80 npm run start` that uses the script `next start -p $PORT --hostname $HOST`. I am able to login but when it redirects me using my api/callback I get this error `Invalid request, an initial state could not be found`, but only in production. Does anyone have any suggestions?

using next 9.1.5 and node 12.12.0

The auth0 setup is

Regular Web Application
Added Allowed callbacks: http://mydomain.com/api/callbacks
Added Allowed logouts:  http://mydomain.com/
OAuth using RS256, OIDC Conformant is True 

The error: 
```bash
Error: Invalid request, an initial state could not be found
    at Object.<anonymous> (node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:18:19)
    at Generator.next (<anonymous>)
    at node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (node_modules/tslib/tslib.js:106:16)
    at Object.handleCallback (node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:6:43)
    at callback (.next/server/static/BfCtWDV94nuOqqQfHvyvp/pages/api/callback.js:146:70)
    at Object.apiResolver (node_modules/next/dist/next-server/server/api-utils.js:39:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Server.handleApiRequest (node_modules/next/dist/next-server/server/next-server.js:367:9)
```

The error derives from here, 

```
        // Require that we have a state.
        const state = cookies['a0:state'];
        if (!state) {
            throw new Error('Invalid request, an initial state could not be found');
        }
```

Any reason why I may not be receiving the a0:state cookie, I have been through https://auth0.com/docs/cms/wordpress/invalid-state this guide but still no luck.

**Comment by grahambryan** [comment]
When launching the app with `NODE_ENV=production` it causes the environment to become secure and since my application was running on `http` and not `https` the secure cookie was not being sent to my browser. So setting NODE_ENV to something else made it work if you are trying to test this system in a production environment.

**Comment by MontoyaAndres** [comment]
Hey, I have the same error, but seems that the problem comes from the http protocol, because I'm using the command `now dev` to work with the app in development that runs over http. In this case, I always need to test the app in production (Deploying it on Now)?

**Comment by grahambryan** [comment]
I’m unfamiliar with using ‘now’ for deployment so I can’t be much help here. My app is mainly for internal use inside a firewall and the solution above works for my case. But the overall solution I I believe is testing on an a secure http.

**Comment by MontoyaAndres** [comment]
I tried uploading it to production (with ssl) and it doesn't work, this is the error I have:

https://github.com/auth0/nextjs-auth0/issues/60
