### ISSUE TITLE
getSession implicit set-cookie can re-apply stale cookies

### ISSUE THREAD

**Issue by derrickpelletier** [auth0/nextjs-auth0#544]
### Description

Using `auth0.getSession(req, res)` always results in a `Set-Cookie` header being applied. Seems to me that this could easily cause race-conditions that reapply a session to a user when it shouldn't. 

Working on handling failed refreshes and clearing the session, i've seen this happen a couple times already.

### Reproduction

- authenticate, acquire `appSession` cookie.
- have an endpoint that is polled that calls `auth0.getSession`.
- more likely with multiple tabs, but possible with a single tab depending how the requests overlap:
  - tab1 makes req to `/logout`. Executes `handleLogout()` or manually deletes `appSession` cookie.
  - tab2 makes req to `/some-poll`. Executes `auth0.getSession()`.
  - tab1 returns,  clearing the `appSession` cookie.
  - tab2 returns, setting the old `appSession` cookie back in place.

### Environment

> Please provide the following:

- **Version of this library used:** `1.6.1`
- **Version of the platform or framework used, if applicable:** `next@11.1.2`

**Comment by adamjmcgrath** [comment]
Hi @derrickpelletier - This SDK enables a rolling session by default.

That means every time the user touches the session the expiry of the cookie must be updated.

In the situation you describe, if tab 2 makes a request to `/some-poll` before tab1 logs the user out, it's expected behaviour that it will read a valid session cookie. This would apply to any endpoint that had to update a session cookie, so is not unique to this SDK.

Closing as this is expected behaviour

**Comment by derrickpelletier** [comment]
>  it's expected behaviour that it will read a valid session cookie. This would apply to any endpoint that had to update a session cookie, so is not unique to this SDK.

Yeah i understand it's expected behaviour that it would **read** a valid session cookie. But by touching it, it performs another set-cookie, so when that request is returned, the cookie that should-have-been/was deleted by the logout, would get re-applied to the client because tab2 wanted to update the expiry? 

I'm not fully understanding how that's expected behaviour? Seems strange to me that a user could click logout and have some other active request end up cancelling that out. The logout would invalidate the refresh tokens but for the remainder of the lifespan on the session it'd still function... Seems like bad UX?

-----

> This SDK enables a rolling session by default.

When you say "by default" are you saying there's a way to opt-out of this behaviour?
