### ISSUE TITLE
[Question] How to use `withApiAuthRequired` with Checkly or other API testing tools?

### ISSUE THREAD

**Issue by kauffecup** [auth0/nextjs-auth0#548]
### Description

[Checkly](https://www.checklyhq.com/) is a tool for both API monitoring and E2E testing and is currently linked to from Vercel's [monitoring integrations](https://vercel.com/integrations/checkly)

I'm trying to write tests that hit an API on production that is wrapped in `withApiAuthRequired` directly, and assert on various conditions that can be run at regular intervals and as a part of deploys. However, (I believe) doing so requires me to have the `appSession` cookie set in the request header

Is it possible to programmatically set that cookie such that I can write these kinds of tests?

### Current Progress

In Checkly specifically, they allow you to run what they call a set up script, which is designed to handle things like authentication before the run the actual API test. In these, I'm able to receive the `access_token` from authenticating with auth0 directly:

```js
const { access_token, ...otherValuableThings? } = await requestPromise({
  uri: AUTH0_URI,
  json: true,
  method: "POST",
  form: {
    grant_type: "password",
    username: USERNAME,
    password: PASSWORD,
    client_id: AUTH0_CLIENT_ID,
    client_secret: AUTH0_CLIENT_SECRET,
    audience: AUTH0_AUDIENCE,
  },
})
```

I was hoping to then do something like:

```js
request.headers['Cookie'] = `appSession=${magicFunction({ access_token, ...otherValuableThings})}`
```

But to do so I'd need to implement `magicFunction`

Is there a way to accomplish this without setting `appSession`, perhaps by doing something like:

```js
request.headers["Authorization"] = `Bearer ${access_token}
```

(as is the recommended method in Checkly's docs for setup scripts with Auth0 API testing: https://www.checklyhq.com/docs/api-checks/setup-teardown-scripts/)

### Anyways

I found (what I believe to be) a similar issue here https://github.com/auth0/nextjs-auth0/issues/335 which was closed in March with a reference to a comment about closing while exploring ways to integrate with E2E testing better. If that's still the case, then apologies and feel free to close this!

Would appreciate any help with how to do API testing, and really appreciate using auth0, this library, and the maintenance of it! If there's a better place to ask this please direct me and feel free to close this. Thank you! And let me know if you have any followup questions!

**Comment by adamjmcgrath** [comment]
Hi @kauffecup - thanks for raising this.

We don't provide a `magicFunction` to create a session cookie I'm afraid. But you could take a look at https://github.com/sir-dunxalot/cypress-nextjs-auth0 for how they do E2E testing for `nextjs-auth0`. The `magicFunction` is specifically this bit https://github.com/sir-dunxalot/cypress-nextjs-auth0/blob/master/encrypt.js

**Comment by kauffecup** [comment]
@adamjmcgrath thanks for the quick response! do you know if there’s an endpoint created via nextjs-auth0 that could be used to get the cookie? perhaps hitting /callback directly with the right query params?

**Comment by adamjmcgrath** [comment]
@kauffecup - either you create the cookie programmatically, using something like what I've described in https://github.com/auth0/nextjs-auth0/issues/548#issuecomment-981551266 or you login through the UI (something like https://www.checklyhq.com/docs/browser-checks/login-scenarios/#social-login)
