### ISSUE TITLE
Error on creating getServerSideProps with  withPageAuthRequired : TypeError: "secret" is required

### ISSUE THREAD

**Issue by DraksBG** [auth0/nextjs-auth0#549]
Hello I am trying to invoke getServerSideProps  with withPageAuthRequired  but I am getting the that error whenever I am trying to access a page on which I am no logged TypeError: "secret" is required
I am having the initializing the secret as it is described in  https://auth0.github.io/nextjs-auth0
Can some one give me a hand in telling me what I do wrong

```
export const getServerSideProps = withPageAuthRequired({
  returnTo: `/page`,
  async getServerSideProps(ctx) {
    const pageScopes = allScopes['page'];
    const session = await auth0.getSession(ctx.req, ctx.res, {
      scopes: pageScopes.split(' '),
      refresh: true,
    });

    if (!session?.user) {
      return {
        redirect: {
          destination: `/api/sign-in?redirectTo=/page`,
          permanent: false,
        },
      };
    }

    const layoutData = await returnLayoutData('page');

    return {
      props: {
        pageType: gtmSome.pageType,
        pageTitle: gtmSome.pageTitle,
        description: gtmSome.pageDescription,
        layoutData,
      },
    };
  },
});
```

I have lost the last two days in search of the problem couldn't find a proper solution
Version of the NextJS Auth0  is   "@auth0/nextjs-auth0": "^1.4.0",
Version of the NextJs is   "next": "~10.2",

**Comment by adamjmcgrath** [comment]
Hi @DraksBG 

I can't see anything wrong with the code you've shared. It looks like you're using named exports, and so initialising the SDK with environment variables. Therefore I would check that you have populated the `AUTH0_SECRET` environmental variable.

If you're still having problems, and would like me to debug it for you, could you share a working repo that demonstrates the issue.

**Comment by DraksBG** [comment]
@adamjmcgrath  Thank you so much I would love to, but it's a retail version and I can't share a repo,  So I would keep digging and see what the problem is, thank you once more.
