### ISSUE TITLE
Rolling session and short live access token 

### ISSUE THREAD

**Issue by francescovenica** [auth0/nextjs-auth0#551]
Hello,

I would like to keep id_token and access token short live (~30sec), the cookie in the app should update itself in order to expire always after 15min, if the user doesn’t interact with the app after 15min I should be logged out…if the cooke expire without an interaction I should be force to re-login and all the token must be useless…I’m a bit confused on how I should achieve this, my idea is to set:

tenant: Inactivity timeout = 15min
api: Token Expiration For Browser Flows / Token Expiration to 30 sec
app: id token in the app 30 sec
app: Refresh Token Rotation 120 sec (but it should be >30sec if I’m not wrong)
app: Refresh Token Expiration absolute lifetime 3600 / inactivity 900 sec
are these the correct settings?

I'm using also:

session: {
  rolling: true,
  rollingDuration: parseInt(AUTH0_ROLLING_DURATION),
  ....
}
with these setting sometimes I get:
The access token expired and a refresh token is not available. The user will need to sign in again.

many thanks
Francesco

**Comment by adamjmcgrath** [comment]
Hi @francescovenica - thanks for sharing this

> The access token expired and a refresh token is not available. The user will need to sign in again.

Are you requesting a Refresh Token? You need to add `offline_access` to the scope to request one (see https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#access-an-external-api-from-an-api-route for an example)

Also, if you're specifying an API using `audience` that API needs to be enabled for offline access (Your Tenant > API Settings > Access Settings, "Allow Offline Access")

**Couple of other things:**

> tenant: Inactivity timeout = 15min

This will have no effect on the duration of your local session

> api: Token Expiration For Browser Flows / Token Expiration to 30 sec

We have a [60 sec leeway](https://github.com/auth0/nextjs-auth0/blob/main/src/session/get-access-token.ts#L135) for determining if an Access Token has expired. So very low expiries might not work as you'd expect, I'd increase it to above 1 min.

> app: id token in the app 30 sec

This is the expiry for when the ID Token can be processed in the callback route. 30 secs should be fine, but this won't have an effect on the session duration and we also have a [60 second leeway on this](https://auth0.github.io/nextjs-auth0/interfaces/config.baseconfig.html#clocktolerance)

> app: Refresh Token Rotation 120 sec (but it should be >30sec if I’m not wrong)

You shouldn't have the Refresh Token Rotation enabled, this is only really for SPAs (see https://auth0.com/docs/security/tokens/refresh-tokens/refresh-token-rotation#maintain-user-sessions-in-spas)

**In General**

I would stick to the defaults and set `rollingDuration` in the SDK to 15 mins and Access Token expiration to 1 min.

If you want to have the scenario "all the token must be useless" after logout, you can't revoke the Access Token or at least you can't easliy (google how to revoke a JWT) but with an expiry of 1min you should be ok. You can revoke the Refresh Token (see https://auth0.com/docs/security/tokens/refresh-tokens/revoke-refresh-tokens) this library doesn't natively support it, but you can add some custom logic to logout.

Remember that the tokens are kept in an encrypted HttpOnly cookie, so leaking is unlikely.

**Comment by francescovenica** [comment]
Hello @adamjmcgrath, thanks for the quick answer.

It's ok for me to have the 15min rolling session, to increase the lifetime of the tokens to 1m or even 90sec but without the token rotation how does the refresh token works?

I'm not sure but I think that with the offline scope the refresh token  I was thinking to set use this configs for the `Refresh Token Expiration`:
Absolute Lifetime = 3600s
Inactivity Lifetime = 900s

I suppose that at some point also the refresh token should be refreshed somehow, is this managed by Aut0 internally?

**Comment by adamjmcgrath** [comment]
Hi @francescovenica 

> It's ok for me to have the 15min rolling session, to increase the lifetime of the tokens to 1m or even 90sec but without the token rotation how does the refresh token works?

We have docs on how refresh tokens work here https://auth0.com/docs/security/tokens/refresh-tokens

> I suppose that at some point also the refresh token should be refreshed somehow, is this managed by Aut0 internally?

Refresh tokens aren't refreshed, they're typically long lived. From the docs:

> Applications must store refresh tokens securely because they essentially allow a user to remain authenticated forever.
https://auth0.com/docs/security/tokens/refresh-tokens

**Comment by francescovbmi** [comment]
Thanks @adamjmcgrath, I'm having another issue that I don't know how to fix...when I login I create a session, if this session is valid for 15min and I log out immediately I'm still able to re-use this session....should the session be invalid after logout?

**Comment by francescovenica** [comment]
Thanks @adamjmcgrath, I'm having another issue that I don't know how to fix...when I login I create a session, if this session is valid for 15min and I log out immediately I'm still able to re-use this session....should the session be invalid after logout?

**Comment by adamjmcgrath** [comment]
Hi @francescovenica - The session is stateless, there’s no server-side state like a database backing it up, so it’s not possible to revoke a session, only to logout and delete the session cookie.

**Comment by adamjmcgrath** [comment]
Closing, feel free to ping me if you have any other questions
