### ISSUE TITLE
Override AUTH0_BASE_URL during runtime

### ISSUE THREAD

**Issue by jayarnielsen** [auth0/nextjs-auth0#552]
### Description

I have a next.js app that services many organizations via wildcard domains like https://my-org.my-site.com, https://my-other-org.my-site.com. Using examples I found here in resolved GitHub issues, I was able to get the redirectUri working as expected. However, now I randomly run into issues with users getting a `checks.state argument is missing` error when they attempt to log in. According to [this thread](https://community.auth0.com/t/badrequesterror-checks-state-argument-is-missing/42609), the solution is to set AUTH0_BASE_URL to match the domain serving the app. Problem is I can't do that because the domain could be any of https://*.my-site.com.

### Reproduction

Custom `[...auth0].tsx` route

```typescript
import {
  handleAuth,
  handleCallback,
  handleLogin,
  handleLogout,
} from "@auth0/nextjs-auth0";
import type { NextApiRequest, NextApiResponse } from "next";

function getUrls(req: NextApiRequest): {
  redirectUri: string;
  returnTo: string;
} {
  const protocol = process.env.NODE_ENV === "development" ? "http" : "https";
  const host = req.headers.host;
  return {
    redirectUri: `${protocol}://${host}/api/auth/callback`,
    returnTo: `${protocol}://${host}`,
  };
}

export default handleAuth({
  async callback(req: NextApiRequest, res: NextApiResponse) {
    try {
      const { redirectUri } = getUrls(req);
      await handleCallback(req, res, { redirectUri: redirectUri });
    } catch (error) {
      res.status(error.status || 500).end(error.message);
    }
  },

  async login(req: NextApiRequest, res: NextApiResponse) {
    try {
      const { redirectUri, returnTo } = getUrls(req);

      await handleLogin(req, res, {
        authorizationParams: {
          redirect_uri: redirectUri,
        },
        returnTo: returnTo,
      });
    } catch (error) {
      res.status(error.status || 400).end(error.message);
    }
  },

  async logout(req: NextApiRequest, res: NextApiResponse) {
    const { returnTo } = getUrls(req);
    await handleLogout(req, res, {
      returnTo: returnTo,
    });
  },
});
```

### Environment

- Next.js 11.1.2
- @auth0/nextjs-auth0 1.6.1

**Comment by adamjmcgrath** [comment]
Hi @jayarnielsen - thanks for raising this.

I can't see anything wrong with your code, and you shouldn't need `AUTH0_BASE_URL` to be dynamic - it just needs to match the protocol (https or http)

If you're getting `checks.state argument is missing` it suggests that the cookie being dropped by your login route, can't be read by your callback route. Are they on the same domain and protocol? Can you provide details of the URL when you login and the call back url?

**Comment by francescovenica** [comment]
I had a similar issue with `{market}.domain.xxx` and I fixed it creating an auth0 instance for each domain:

```
const auth0 = {};
const getAuth0Instance = async (req, res) => {
  const { host } = req.headers;
  if(!auth0[`${host}`]){
    auth0[`${host}`] = initAuth0({
        baseURL: `${protocol}://${host}`,
        ...
    });
  }
  return auth0[`${host}`];
};
```

with a fixed baseUrl I found very tricky getting all working fine also because I didn't have a common url used a main point of entrance....

**Comment by jayarnielsen** [comment]
@francescovenica That's pretty much what I came up with, too!

```typescript
export const initializeAuth0 = (
  req: NextApiRequest | IncomingMessage
): ReturnType<typeof initAuth0> => {
  return initAuth0({
    baseURL:
      req.headers.origin ||
      `${process.env.NODE_ENV === "development" ? "http" : "https"}://${
        req.headers.host
      }`,
  });
};
```

Being able to override the baseURL per domain was the only way I could avoid the checks.state error. It also meant I could eliminate a lot of boilerplate in my `[...auth0].ts` route

```typescript
import type { NextApiRequest, NextApiResponse } from "next";
import { initializeAuth0 } from "../../../src/lib/auth0";

export default function auth(
  req: NextApiRequest,
  res: NextApiResponse
): void | Promise<void> {
  const auth0 = initializeAuth0(req);
  return auth0.handleAuth()(req, res);
}
```

**Comment by adamjmcgrath** [comment]
Hi @jayarnielsen 

The `baseUrl` does 2 things:
- It is used to derive the `Secure` flag for the session and transaction cookies: https://github.com/auth0/nextjs-auth0/blob/main/src/auth0-session/get-config.ts#L41
- It is used to derive the redirect uri for the login and callback routes: https://github.com/auth0/nextjs-auth0/blob/main/src/auth0-session/handlers/login.ts#L13 and https://github.com/auth0/nextjs-auth0/blob/main/src/auth0-session/handlers/callback.ts#L11

If the protocol of your base url correctly matches the protocol of your login and callback urls and you correctly set the `redirectUri` for the callback and login handlers, then you shouldn't need to manage your own instance of the SDK or create multiple instances. 

But if the solution you've posted works for you, that's fine, it's perfectly valid. Closing as I think we've covered everything

**Comment by yzhe554** [comment]
Hi @adamjmcgrath , I meet a different issue.
In our usecase, we are using azure frontdoor. Our public site is for example https://www.public-domain.com, however, the actual host is https://www.private-domain.net.
Everything works fine from https://www.private-domain.net but I am getting `checks.state argument is missing` from https://www.public-domain.com. Any suggestions?

**Comment by Raphaww** [comment]
@jnlsn did you use edge middleware to handle your subdomains?
```
//middleware.js
...
const account =
   process.env.NODE_ENV === "production" && process.env.VERCEL === "1"
      ? hostname.split('.')[0]
      : hostname.replace(`.localhost:3000`, "");

if (req.nextUrl.pathname.startsWith('/api')) {
   return NextResponse.rewrite(
      new URL(`/api/${account}${req.nextUrl.pathname.replace('/api', '')}`, req.url)
   );
}
...
```
It works in local but I am getting this error in **vercel** on my callback url `CallbackHandlerError: Callback handler failed. CAUSE: Missing state parameter in Authorization Response.`

but the 'state' parameter is right there.
`https://org.my-domain.com/api/auth/callback?code=P4q_PTQji5PoyHic1VNqcOD2Ipp-8P56cmKHfnRlX2c8o&state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vaXh0dWwucmV2ZW5hdGl1bS1zaXRlcy5jb20ifQ`

I don't know if it's some error caused because of the middleware. It would be great if your share the way you handle multi tenancy. Thank you

**Comment by VisheshNucleusTeq** [comment]
I want to bring in a flow like slack 
where before login slack ask for workspace and then it redirects user to that particular workspace login 
any Idea how can I achieve this  I am using Keycloak and @auth0/nextjs-auth0
