### ISSUE TITLE
`user` is inferred to be `Claims | null | undefined` instead of `Claims` when using `InferGetServerSidePropsType`

### ISSUE THREAD

**Issue by LucasLemanowicz** [auth0/nextjs-auth0#560]
### Describe the problem

The type for `user` inferred from `withAuthenticationRequired` is `Claims | null | undefined`.

### What was the expected behavior?
The type should just be `Claims`

### Reproduction

Here is a simple repro:

```typescript
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import { InferGetServerSidePropsType, NextPage} from "next";
import React from "react";

const TestPage: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({ user }) => {
    return <pre>{JSON.stringify(user, null, 2)}</pre>;
};

export const getServerSideProps = withPageAuthRequired();
export default TestPage;
```
In the example above, the `user` prop is inferred to be of type `Claims | null | undefined`, which I believe is wrong (because as I understand, `withPageAuthRequired` would redirect to login before rendering the page if it were null or undefined).

The current workaround is to manually define that `user` is of type `Claims`:

```typescript
import { Claims, withPageAuthRequired } from "@auth0/nextjs-auth0";
import { InferGetServerSidePropsType, NextPage} from "next";
import React from "react";

interface IProps extends InferGetServerSidePropsType<typeof getServerSideProps> {
    user: Claims;
}

const TestPage: NextPage<IProps> = ({ user }) => {
    return <pre>{JSON.stringify(user, null, 2)}</pre>;
};

export const getServerSideProps = withPageAuthRequired();
export default TestPage;
```

Is the type wrong, or am I misunderstanding something and not aware of a situation in which `user` could be null or undefined?

### Environment

- **Version of this library used:** 1.6.2
- **Which framework are you using, if applicable:** Node 14.18.1, NextJS 12.0.7
- **Other modules/plugins/libraries that might be involved:** Typescript 4.5.4
- **Any other relevant information you think would be useful:**

**Comment by Widcket** [comment]
Hi @LucasLemanowicz, thanks for raising this.

The type displayed is correct, as the user [is defined](https://github.com/auth0/nextjs-auth0/blob/main/src/helpers/with-page-auth-required.ts#L28) in server-side `withPageAuthRequired` as `user?: Claims | null`, which translates to `Claims | null | undefined`.

**Comment by LucasLemanowicz** [comment]
What would be the correct way to use the types in my case above? By the time it gets to my `TestPage`, I can assume that `user` is set, right?

**Comment by Widcket** [comment]
When `withPageAuthRequired` returns, [it includes](https://github.com/auth0/nextjs-auth0/blob/main/src/helpers/with-page-auth-required.ts#L125) `session.user`, which is of type `Claims`. If there is no user, it [redirects](https://github.com/auth0/nextjs-auth0/blob/main/src/helpers/with-page-auth-required.ts#L115) to the login endpoint. So yes, you can assume that the user is set.

You can see in the kitchen sink example the [more specific](https://github.com/auth0/nextjs-auth0/blob/main/examples/kitchen-sink-example/pages/profile-ssr.tsx#L6) `UserProfile` being used instead of `Claims`, which is `[key: string]: any;`.

**Comment by Widcket** [comment]
cc @adamjmcgrath

**Comment by LucasLemanowicz** [comment]
Understood, thanks for explaining. Appreciate the link to your example, it looks like you also just manually set the type. It would be nice to have a way to define it more programmatically in the future, but this all makes sense to me now.

**Comment by adamjmcgrath** [comment]
Closing, feel free to continue the discussion over a pr if you think we can improve the types here
