### ISSUE TITLE
Share authentication between domains

### ISSUE THREAD

**Issue by MaximeConan** [auth0/nextjs-auth0#568]
Hello everyone, I’m trying to share authentication between two domains (the back office and the application).

Apps are not on the same domain.

Is there a way to be logged on the backoffice and forward the token from URL or something else ?

I use the Universal login flow.

**Comment by adamjmcgrath** [comment]
Hi @MaximeConan - not sure exactly the mechanics you're after.

But you can get the Access Token by using [getAccessToken](https://auth0.github.io/nextjs-auth0/modules/session_get_access_token.html#getaccesstoken)

**Comment by MaximeConan** [comment]
Hi @adamjmcgrath , I would like to be able to authenticate from application A and keep this token while browsing to application B. This allows the backoffice admins to share the same session with the front office of our application without have a SSO for yet.

I finally forked the project to expose the `sessionCache` and manage it myself! 

It might be interesting for the future to have the `sessionCache` exposed directly in the package to allow users to manager it by themselves if they want?

If so I can make a PR in this sense.

**Comment by adamjmcgrath** [comment]
Hi @MaximeConan - thanks for sharing that. And glad you got it working.

We've thought about exposing `sessionCache` for use cases like these, but we decided to keep it private to avoid possible abuses that would make the SDK not as secure by default as we would like.

We are however constantly reviewing this decision and your additional use case is helpful.
