### ISSUE TITLE
Clearcookie Doesn't Respect AUTH0_COOKIE_SAME_SITE

### ISSUE THREAD

**Issue by jpulec** [auth0/nextjs-auth0#569]
### Describe the problem
It seems that the `clearCookie` function used to remove the `appSession` cookie doesn't respect the `AUTH0_COOKIE_SAME_SITE` environment variable.

This means that if you set `AUTH0_COOKIE_SAME_SITE=none` to support cross-origin requests, users can log in, but when they try to logout, the `appSession` cookie isn't cleared.

### What was the expected behavior?

The `clearCookie` function should respect `AUTH0_COOKIE_SAME_SITE` when being used to clear `appSession`.

### Environment

- **Version of this library used:** 1.6.1

**Comment by adamjmcgrath** [comment]
Hi @jpulec - thanks for raising this

Yep - looks like for `SameSite=None` and Chrome >=80 - we need to set the Secure attribute (looking at https://www.thinktecture.com/en/identity/samesite/how-to-delete-samesite-cookies/#why-doesnt-chrome-delete-my-samesitenone-cookies)

I'll raise some work to fix this

**Comment by adamjmcgrath** [comment]
Hi @jpulec - I get the issue, but I'm not able to reproduce it on Chrome 96.0.4664.110. Can you tell me what browser you are using? Also, do you have a running example I can login to that demonstrates the issue?

The session cookie gets cleared, even when it's `Secure=True, SameSite=None` and the Set-Cookie header that clears it has neither of those attributes

eg this request seems to clear the cookie as expected (on https://localhost)

![image](https://user-images.githubusercontent.com/1299658/148065307-78e69e4b-d24d-4ae0-93e6-9257f50952a4.png)

**Comment by jpulec** [comment]
@adamjmcgrath You have to make sure that you're making a cross origin request, since then chrome will ignore the responses request to clear the cookie. In our case, we run our app in an iframe, which gets treated as cross origin by chrome. I can put  together a longer explanation/example later today.

**Comment by adamjmcgrath** [comment]
Ah ok, thanks @jpulec - I can reproduce this logging out of https://vercel-deploy-test-app.vercel.app/ in an iframe (I'm not sure how you're able to login in an iframe because of #541?)

![image](https://user-images.githubusercontent.com/1299658/148204225-9af262e4-85fe-4f60-bf23-8ebcfaa577b2.png)

I'll take a look

**Comment by jpulec** [comment]
> (I'm not sure how you're able to login in an iframe because of #541?)
We actually have to open a new popup window to perform our authentication, which works fine and sets `appSession` to work cross origin.

Our use case is a chrome extension where we inject an iframe as part of a content script. Without all these options for cross origin handing for the `appSession`, we wouldn't be able to use this library at all.

Thanks for much for the quick look and turn around!

**Comment by adamjmcgrath** [comment]
> We actually have to open a new popup window to perform our authentication

Ah, makes sense 👍 - I'll let you know when this gets released

**Comment by adamjmcgrath** [comment]
Released in [1.7.0](https://github.com/auth0/nextjs-auth0/releases/tag/v1.7.0)
