### ISSUE TITLE
docs: Cross Site Request Forgery (CSRF) Considerations / Vulnerabilities

### ISSUE THREAD

**Issue by meticoeus** [auth0/nextjs-auth0#58]
Description (Problem)

The documentation does not make any mention of CSRF and whether there are any steps needed to address it or whether it is a concern.

Please clarify in the docs if there are steps that should be taken to mitigate risk if usage of this library is vulnerable to this type of attack. If this library already addresses this for you, it would be reassuring for the docs to mention that.

If steps are needed, it would be quite handy to include a complete example when proxying a backend API or some other relevant scenario.

**Comment by sandrinodimattia** [comment]
I published v0.7.0 which now sets the session cookie to `SameSite=Lax` by default, which mitigates CSRF attacks.

Eg: an attacker will not be able to host a page on their malicious website to POST something to your site.

https://github.com/auth0/nextjs-auth0#cookies

**Comment by meticoeus** [comment]
Thanks, that mostly answers my question. For those of us who are not security exports, are the cookie settings in use considered "good enough" for most cases?

**Comment by sandrinodimattia** [comment]
The default value is `Lax` which is a good balance between security and usablity. You can also enable `Strict` depending on your use case, but that will prevent the session to be loaded if third party sites redirect to your site which could hurt the end user experience (ie: the user will never be signed in if they were redirected to your site from an other site).

**Comment by meticoeus** [comment]
Okay, thanks for the clarification : )
