### ISSUE TITLE
returnTo parameter on logout not working

### ISSUE THREAD

**Issue by dr-skot** [auth0/nextjs-auth0#583]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/main/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

returnTo={path} on logout does not redirect to {path}
instead you land at the default callback url

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

1. log in
2. use the location bar to go to /api/auth/logout?returnTo=/wherever
3. you don't end up at /wherever

whereas,

1. log out
2. use the location bar to go to /api/auth/login?returnTo=/wherever
3. log in
4. you end up at /wherever

### Environment

> Please provide the following:

- **Version of this library used:**
1.7.0

- **Version of the platform or framework used, if applicable:**
nextjs 12.0.1

- **Other relevant versions (language, server software, OS, browser):**
Brave Browser Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (x86_64)

- **Other modules/plugins/libraries that might be involved:**

**Comment by Widcket** [comment]
Hi @dr-skot, thanks for raising this.

You need to pass the **returnTo** value either as an environment variable (`AUTH0_POST_LOGOUT_REDIRECT`) or as a config option in the logout handler:

```js
await handleLogout(req, res, {
    returnTo: returnTo,
});
```
Passing it directly to `/api/auth/logout` (e.g. `/api/auth/logout?returnTo=/wherever`) is not supported.
I'll close this issue, as I believe the above answers your question. Please let me know if you'd like to reopen.

**Comment by dr-skot** [comment]
Ah okay.

You're right, I'm able to make it work by passing a returnTo parameter to handleLogout. Thanks for your help.

Can I feature-request logout?redirectTo= ?
I realize that the docs below are describing a different api, but why not match this behavior to reduce confusion?

Because opportunity for confusion abounds in this jungle of app settings and tenant settings and api secrets and allowed urls and environment variables... we need all the help we can get.

Thanks again


https://auth0.com/docs/authenticate/login/logout/redirect-users-after-logout
>  1. Add a `returnTo` query string parameter with the target URL as the value. Encode the target URL being passed in. For example, to redirect the user to `http://www.example.com` after logout, make the following request: `https://YOUR_DOMAIN/v2/logout?returnTo=http%3A%2F%2Fwww.example.com <https://your_domain/v2/logout?returnTo=http%3A%2F%2Fwww.example.com>`
> 

the "Allowed Logout URLs" section of application settings
> A set of URLs that are valid to redirect to after logout from Auth0. After a user logs out from Auth0 you can redirect them with the `returnTo` query parameter.

**Comment by Widcket** [comment]
This has been requested in the past: https://github.com/auth0/nextjs-auth0/issues/532

**Comment by wacanam** [comment]
this is what i did.


`import { handleAuth, handleLogin, handleLogout, NextAppRouterHandler } from '@auth0/nextjs-auth0';

export const GET: NextAppRouterHandler = async (...args) => {
  const req = args[0];
  const returnTo = req.nextUrl.searchParams.get('returnTo')
  return handleAuth({
    signup: handleLogin({
      authorizationParams: {
        login_hint: 'signup',
      }
    }),
    logout: handleLogout({
      ...returnTo ? { returnTo } : {},
    }),
  })(...args);
}`
