### ISSUE TITLE
Next.js Rewrites

### ISSUE THREAD

**Issue by Tbhesswebber** [auth0/nextjs-auth0#584]
### Describe the problem you'd like to have solved

Cypress has certain limitations that prevents tests from navigating to other domains (including subdomains). The majority of our application is behind authentication, but there is one namespace within the site that allows users to generate unique sharing urls for public consumption.  We are leveraging `cypress-nextjs-auth0`, but that requires us to log in and out using password grant type, which we don't support in the application itself. This becomes especially problematic because we need to be able to test some of our systems in production, which means we need to have an unsupported grant type turned on in our production environment.

### Describe the ideal solution

I don't know that this is something that this package can actually do anything about, but I figured the knowledge-base here would likely be able to come up with some creative options that I might be able to prototype.  The only thing that I can think of is leveraging the `rewrites` property in `next.config.js`, but attempting that didn't work, presumably because there's a redirect that happens once we land in Auth0 land.

```js
async rewrites() {
    return [
      {
        source: "/auth/login",
        destination: process.env.AUTH0_ISSUER_BASE_URL,
        basePath: false,
      },
    ];
  },
```

## Alternatives and current work-arounds

None (but if people have suggestions, I'll update this as I try things)

**Comment by adamjmcgrath** [comment]
Hi @Tbhesswebber - thanks for raising this

I'm not sure what you're trying to achieve by redirecting from `/auth/login` to `AUTH0_ISSUER_BASE_URL`

If you want to login to a production auth0 application with no password grant, I would say your only option is to login using the Universal Login Page via cypress - which I understand is not best practice, but in production you don't have many options available.

**Comment by Tbhesswebber** [comment]
So the idea is to leverage Next.js rewrites, not redirects. Effectively, they allow you to present a page, even an external site (like google), as if it were a part of your application. I don't know the exact voodoo used, but I validated that it's not a cross origin iframe. 

Cypress is actively working on supporting subdomains and multiple domains per test, so this was potentially a moot question, but I asked anyway because we have significant test flake when signing out even with the password grant because of the redirect to the login page (we have no consistently available public page that we could redirect to)

I appreciate the quick response! If you do think of anything wacky to try, I'm all ears!

**Comment by adamjmcgrath** [comment]
Ah ok, I get you - you should be able to visit different subdomains in a cypress test, so as long as you're using [custom domains](https://auth0.com/docs/customize/custom-domains) in prod (which you should be doing).

Even if you figured out the redirects issue that's blocking you, I don't think the `rewrites` solution is going to work, because the Universal Login Page will need to be on the same domain as the API it consumes.

**Comment by adamjmcgrath** [comment]
We use a [mock authorization server](https://github.com/auth0/nextjs-auth0/blob/main/scripts/oidc-provider.js) in our e2e tests, but that won't help you in prod

**Comment by adamjmcgrath** [comment]
Closing - feel free to ping me if you want to continue the conversation
