### ISSUE TITLE
Simplification of the code

### ISSUE THREAD

**Issue by HelloEdit** [auth0/nextjs-auth0#59]
### Describe the problem you'd like to have solved

I've been interested in auth0 for some time, and this package perfectly meets my expectations. While cloning the code, I realized that the organization was counter-intuitive (I'd like to if I'm the only one to think so): the typecript definitions are separated from the code using them, their names are not very explicit...
I started to rebuild the code from scratch to improve my understanding of the system and I came up with [something like this](https://github.com/HelloEdit/next-auth0) with a few modifications from the original code:

- The interface and Typescript's types are [included in the code files directly](https://github.com/HelloEdit/next-auth0/blob/master/src/client.ts#L6). I personally find it much clearer and easier to find.
- Instead of creating classes to validate parameters and set defaults, I used [object destructuring](https://github.com/HelloEdit/next-auth0/blob/master/src/instance.ts#L86) and [ow ](https://github.com/sindresorhus/ow) to [validate](https://github.com/HelloEdit/next-auth0/blob/master/src/instance.ts#L84) the [shape and the type of the object's properties](https://github.com/HelloEdit/next-auth0/blob/master/src/instance.ts#L71).
- I also change the [setting's name](https://github.com/HelloEdit/next-auth0/blob/master/src/instance.ts#L19). I really did this for me because I found that some names were not intuitive. (e.g. `redirectUri` and `postLogoutRedirectUri` which I renamed `postLoginUri` and `postLogoutUri`).
- I wanted to have more flexibility with the login and logout handlers. My idea was that nextjs-auth0 didn't have to write directly in the answer and that I preferred to take care of it (especially for `handleProfile` in my case). Instead of
```js
import auth0 from '../../utils/auth0';

export default async function login(req, res) {
  try {
    await auth0.handleLogin(req, res);
  } catch (error) {
    console.error(error);
    res.status(error.status || 400).end(error.message);
  }
}
```

I have something like this

```js
import auth0 from "../../utils/auth0";

export default async function login(req, res) {
  await auth0
    .handleLogin({ req, res })
    .then(url => {
      res.writeHead(302, { Location: url }).end();
    })
    .catch(error => {
      res.status(400).end(error.message);
    });
}
```

I wanted to be able to integrate my own error handling process and add things to the response object. (I also replaced the handler argument `handleSomething(req, res)` with an object with `res` and `req` in it `handleSomething({ res, req })` because I could never remember in what order I should pass them to the function 😢.)

### Describe the ideal solution

I love what auth0 has done to allow developers using next.js to integrate their auth0 process, and I don't want to criticize their work, but I would like to know if you agree with the changes I listed above. I did this more to familiarize myself with the module and not to make change proposals directly. I am open to discussion 😄

Thanks for your work,

**Comment by Widcket** [comment]
Hi @HelloEdit, please check out the new and simplified API in the [v1.0.0-beta.0](https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0) release. Would love to have your feedback.

**Comment by Widcket** [comment]
If you'd like to share your feedback, feel free to open a new issue.
