### ISSUE TITLE
A way to store a cookie that auth0-react can use to authenticate with

### ISSUE THREAD

**Issue by corysimmons** [auth0/nextjs-auth0#590]
### Describe the problem you'd like to have solved

I'd like to be able to login to my NextJS app using `nextjs-auth0`, and if login succeeds detect `isAuthenticated` and redirect to a SPA using `auth0-react` on the same domain.

In the SPA, I would like to show a loading spinner while the SPA checks `isAuthenticated` and show the app or redirect them back to the NextJS app if they aren't logged in.

Currently the only bit of data persisted between the `nextjs-auth0` app and the `auth0-react` app is the `appSession` encoded cookie.

I'm not sure how to use that `appSession` cookie to authenticate the SPA, or if it's even possible.

### Describe the ideal solution

Ideally there would be some cookie persisted from NextJS to the SPA (if they're on the same domain) that would allow the SPA to authenticate using the `auth0-react` library.

## Alternatives and current work-arounds

I haven't fully fleshed it out yet but it is possible to create my own cookie with an access & refresh token using custom handlers within `[...auth0].ts`, and that cookie will persist to the SPA, but even then I'm not sure if it's possible to use that access/refresh token to authenticate using `auth0-react`.

### Additional information, if any

I'm not sure if this might be a security threat (which would explain why the `appSession` cookie gets encoded so strongly to begin with), but it seems like having a NextJS product website at https://example.com with plans/pricing/login that redirected to https://example.com/app SPA would be a pretty common pattern, especially since monorepos are so popular now.

I'm also not sure if this has anything to do with the [custom store implementation that's on the roadmap](https://github.com/auth0/nextjs-auth0/issues/279).

CC'ing @adamjmcgrath since he is the main contributor to `auth0-react` and this feature might need both libraries to receive updates.

**Comment by corysimmons** [comment]
lol sorry about the ping Adam. I just saw you maintain this library as well. 🤦

**Comment by adamjmcgrath** [comment]
Hi @corysimmons - thanks for raising this

> but it seems like having a NextJS product website at https://example.com/ with plans/pricing/login that redirected to https://example.com/app SPA would be a pretty common pattern, especially since monorepos are so popular now.

If you're logged in to `auth0.com` through the `nextjs-auth0` SDK on `https://example.com`, then visiting a protected route on a SPA at `https://example.com/app` will redirect you to login on `auth0.com` and, because you're already logged in to `auth0.com`, you'll be redirected back to the SPA and logged in non-interactively. Is this what you're after?

**Comment by adamjmcgrath** [comment]
Closing as I believe https://github.com/auth0/nextjs-auth0/issues/590#issuecomment-1038908932 answers the question. Ping me if you want me to reopen

**Comment by corysimmons** [comment]
So if both the SPA (using `auth0-react`) and the Next app (using `nextjs-auth0`) are on the same domain, using similar Auth0 Application config, they will just work?

When I log into the nextjs app, I get an `appSession` cookie that the SPA doesn't seem to care about.

**Comment by adamjmcgrath** [comment]
@corysimmons - the SDKs wont share any sort of session, even if they're on the same domain.

You need to login to both SDKs, however - once you've logged in to one of the SDKs, you will have a session on `auth0.com` so the second login through an SDK can be non-interactive.

**Comment by corysimmons** [comment]
Ah okay, thank you.
