### ISSUE TITLE
 Internationalized Routing does not seem to work

### ISSUE THREAD

**Issue by esharmony** [auth0/nextjs-auth0#594]
I have followed the guide on [Internationalized Routing](https://nextjs.org/docs/advanced-features/i18n-routing) and set my languages in the Auth0 console. 

I tried just to set pl, (my application has many languages, but i stuck with one and maybe try and figure out a dynamic way later)

I changed the provider and the url, and set the base path as suggested  

I am also using the universal login.

I get a 404 client error

**Comment by adamjmcgrath** [comment]
Hi @esharmony - thanks for raising this.

> I changed the provider and the url, and set the base path as suggested

Could you share your code for this and what value you set the base path to?

> I am also using the universal login.

Universal Login is the only way to use this SDK

> I get a 404 client error

What was the URL you were trying to access?

**Comment by esharmony** [comment]
I can try and put something together but cannot share the project I am working on: 
But I basically followed the docs: 

set up auth0 with next as per the readme here
Added the languages in the tenant settings pl along with default set to en 

provider:
```
<UserProvider loginUrl="/pl/api/auth/login" profileUrl="/pl/api/auth/me">
    <Component {...pageProps} />
  </UserProvider>

```
// env.local
basepath: AUTH0_BASE_URL='http://localhost:3000/pl' 

and tried url: localhost:3000/pl/api/auth/login

this returned a 404 

I was trying quite a lot of things out so maybe I missed something.

At the moment I am working on a solution, by overwriting the login using the handleLogin and providing a authorizationParams.

I will then use a bit of middleware to remove the locale param from next.

It seems it will work though a little hacky.

**Comment by adamjmcgrath** [comment]
Hi @esharmony 

API routes are not available under a locale on Next.js since https://github.com/vercel/next.js/pull/26629 

So `loginUrl="/pl/api/auth/login"` wont work, you need to use the non local version `/api/auth/login`

**Comment by adamjmcgrath** [comment]
`/foo` is an example of a [basePath](https://nextjs.org/docs/api-reference/next.config.js/basepath) which is different from Internationalized Routing.

**Comment by esharmony** [comment]
So is there a way to provide Internationalisation with next via sub path routing, or shall i continue with my hacky way :)

**Comment by adamjmcgrath** [comment]
You can fix the 404 in your original issue by visiting `/api/auth/login` rather than `/pl/api/auth/login`

I'm not sure what you mean by "provide Internationalisation with next via sub path routing". If you can provide me with what code you're using., what the expected behaviour is and what the actual behaviour is I might be able to help you.

**Comment by esharmony** [comment]
Than i just pass a query parma into this and pas it along in the handleLogin authorizationParams and use that in the auth0 to change the lang. This seems good.

**Comment by esharmony** [comment]
Many thanks
