### ISSUE TITLE
Unable to use persisted layouts following the official Next documentation

### ISSUE THREAD

**Issue by HMilbradt** [auth0/nextjs-auth0#597]
### Description

Following the [documentation ](https://nextjs.org/docs/basic-features/layouts#with-typescript)for adding persistent layouts to Next, I end up with the following Typescript error when using authenticated pages.

`Property 'getLayout' does not exist on type 'FC<WithPageAuthRequiredProps>'`

I realize that this is sort of a hack by Next themselves to get these layouts to work, but it would be really handy if the `withPageAuthRequired` function would support this.  It's a recommended pattern to enable layout persistence between pages.

### Reproduction

The following is enough to reproduce the error.  Note that the `getLayout` function here is taken almost exactly from the Next documentation, just modified to work with Auth0.

Adding a `// @ts-ignore` resolves the error message and allows the layout to work as expected.  

```
import type { ReactElement } from 'react'
import { withPageAuthRequired } from '@auth0/nextjs-auth0'

function Page(): ReactElement {
  return <p>Hello</p>
}

const AuthWrapper = withPageAuthRequired(Page)

AuthWrapper.getLayout = function getLayout(page: ReactElement) {
  return <div>{page}</div>
}

export default AuthWrapper
```

### Environment

- **Version of this library used: 1.7.0**
- **Next: 12.0.10**

**Comment by adamjmcgrath** [comment]
Hi @HMilbradt - thanks for raising this

`getLayout` doesn't exist on a React component, so this should fail regardless of whether you are using `withPageAuthRequired` or not.

Have a look at https://dev.to/ofilipowicz/next-js-per-page-layouts-and-typescript-lh5 for a suggested fix for this

**Comment by HMilbradt** [comment]
Thanks for the link @adamjmcgrath!  To be perfectly honest, the reason I raised this issue is that React and Next _do_ support this.  The example from the docs I linked works out of the box.

It would be really nice to not need to extend types to get this functionality back.   It should also be supported out of the box IMO.

**Comment by HMilbradt** [comment]
@ccccooooddddyyyy. and for anyone else stumbling on this:

https://stackoverflow.com/a/71433194/8727490

I had mistakenly wrapped the `page` with `withPageAuthRequired`, but it turns out you're actually supposed to wrap the `getServerSideProps` with it.  Oddly this "worked", but looking back there was definitely a delayed page load as a result of this error, and obviously the typings I noted earlier did not work.

**Comment by Kerumen** [comment]
I think `withPageAuthRequired` should be using [hoist](https://github.com/mridgway/hoist-non-react-statics) to copy static properties from the child page to the wrapper. This way we could simply do

```js
function Page(): ReactElement {
  return <p>Hello</p>
}

Page.getLayout = function getLayout(page: ReactElement) {
  return <div>{page}</div>
}

export default withPageAuthRequired(Page)
```


What do you think @adamjmcgrath?

**Comment by forkollaider** [comment]
The way @Kerumen described implementation is safer then @HMilbradt & @adamjmcgrath did, because you need to add `getLayout` method to source component and only then wrap it with authentication , otherwise it will simply not work as expected
