### ISSUE TITLE
Setting `returnTo` on a protected dynamic SSR route

### ISSUE THREAD

**Issue by marclemagne** [auth0/nextjs-auth0#599]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/main/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

[As instructed](https://community.auth0.com/t/how-to-set-returnto-for-ssr-for-a-dynamic-route/77755) by a member of the Community team, I am opening an issue here to discuss this issue.

I am using this SDK to protect a dynamic SSR route (`/test/something`). Using the [example from the documentation](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#protecting-a-server-side-rendered-ssr-page), when I **link** to a protected page, after logging in, I am redirected to a resolved URL that looks like: `/test/something?id=something`. I am trying to figure out how to get it to redirect back to the ["pretty URL"](https://nextjs.org/docs/routing/dynamic-routes) instead.

Looking at [this (unrelated)](https://community.auth0.com/t/how-to-set-returnto-for-ssr-for-a-dynamic-route/77755) section from the README, I was able to achieve this but it seems like a lot of extra, non-standard code for what seems like a common use-case with Next.js:

```
export const getServerSideProps: GetServerSideProps = (ctx) => {
  // Just as a quick example
  const [path] = ctx.resolvedUrl.split("?");

  return withPageAuthRequired<{ customProp: string }>({
    returnTo: path,
    async getServerSideProps(ctx) {
      return { props: { customProp: "bar" } };
    },
  })(ctx);
};
```
Am I missing something or do I have something misconfigured?

Thank you. Happy to provide any other details as deemed relevant.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

The original snippet from the SSR example:
```
export const getServerSideProps = withPageAuthRequired({
  async getServerSideProps(ctx) {
    return { props: { customProp: "bar" } };
  },
});
```
When linking to `/test/something` this will redirect to `/test/something?id=something` after logging in.

### Environment

> Please provide the following:

- **Version of this library used:** 1.7.0
- **Version of the platform or framework used, if applicable:** Node v17.1.0 (on macOS 12.2); Next.js 12.0.10 (and 12.1)
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hi @marclemagne - thanks for raising this

> I am using this SDK to protect a dynamic SSR route (/test/something).

Then after login, I would expect you to be redirected back to `/test/something`

> when I link to a protected page, after logging in, I am redirected to a resolved URL that looks like: /test/something?id=something.

I'm not sure why `?id=something` is being added to your `returnTo` path

> I am trying to figure out how to get it to redirect back to the ["pretty URL"](https://nextjs.org/docs/routing/dynamic-routes) instead.

I assume the "pretty URL" you're after in this example is `/test/something`?

Not sure what's going on here - if you want me to debug it for you, can you provide a runnable example that demonstrates the issue?

**Comment by adamjmcgrath** [comment]
Actually, I see what you mean - looks like this is how Next works with dynamic routes https://github.com/vercel/next.js/discussions/18662

Since we don't know what query params should be removed and which ones shouldn't there's not much we can do here - closing, feel free to ping me if you want me to reopen.

**Comment by marclemagne** [comment]
Thanks for looking into it. Seems like that is how it works, for now, and if one really needs it there's a workaround, too.
