### ISSUE TITLE
Error when using "handleLogin" - expected 200 OK, got: 301 Moved Permanently

### ISSUE THREAD

**Issue by delicmomcilo** [auth0/nextjs-auth0#608]
### Description

When routing to the dymanic route "/api/auth/login" the "handleLogin" function in failing and throwing an error. 
![image](https://user-images.githubusercontent.com/22791561/157100515-c4b36611-d9e0-46ce-90b1-96cec146a9e0.png)
The weird thing about this is that I am only getting this error when I run the application on my Windows computer. When I try to reproduce this on a MacBook everything works fine. Everything is running on the same version (Node, lib sdk version etc)

### Reproduction

Error is getting thrown in the handleAuth/handleLogin function without any useful error messages. Tried running the implementation from nextjs-auth0 example and I am getting the same result.

### Environment

"@auth0/nextjs-auth0": "^1.7.0"
"next": "^12.0.8"
Node version: v16.13.1
Tested with Chrome/Edge.

**Comment by adamjmcgrath** [comment]
Hi @delicmomcilo - thanks for raising this

It looks related to https://github.com/panva/node-openid-client/issues/13 - could you tell me what value you're using for `AUTH0_DOMAIN ` in your Windows environment?

**Comment by delicmomcilo** [comment]
Hi @adamjmcgrath - thank you for your reply. It seems that you are right, the issue was with the http/https. My environment variable for base url was `AUTH0_BASE_URL='http://localhost:3000`  -  I changed this to `AUTH0_BASE_URL='https://localhost:3000`. I needed to add `https://localhost:3000` to my callback & allowed url and everything seems to work fine.

**Comment by adamjmcgrath** [comment]
Great, glad you got it working 👍 

> Error is getting thrown in the handleAuth/handleLogin function without any useful error messages
That error would be more helpful if ti said which request was failing - I'll add this to our improvements list for the next major iteration
