### ISSUE TITLE
Example of custom login/sign up screen?

### ISSUE THREAD

**Issue by jlei523** [auth0/nextjs-auth0#611]
So far, the only Next.js + Auth0 examples have redirected users to auth0's website to login or sign up.

What if I want to use my own custom login and signup screens?

Are there examples of how to do this?

**Comment by adamjmcgrath** [comment]
Hi @jlei523 - thanks for raising this

This SDK only provides login through the Universal Login Page - there's no option to use embedded login

See https://auth0.com/docs/authenticate/login/universal-vs-embedded-login for why we only offer ULP

**Comment by jlei523** [comment]
Redirecting users to auth0 for logging in is not the best user experience. Users will be confused about why they're being redirected to a random site for login (auth0 is random for non-techie users). 

Most sites do not redirect users to a different domain to login. For social auth, they usually show a popup. This is a common user experience that users expect and trust. 

I hope that Auth0 will come up for an example for this.

It looks like I will have to pass on Auth0.

**Comment by adamjmcgrath** [comment]
Thanks for your feedback @jlei523 

> Most sites do not redirect users to a different domain to login.

We recommend you use custom domains (eg `login.YOUR_DOMAIN.com`) in production, see https://auth0.com/docs/customize/custom-domains

> For social auth, they usually show a popup. This is a common user experience that users expect and trust.

There's nothing stopping you from launching the Universal Login Page in a popup if that's the User Experience you want to go for

**Comment by jlei523** [comment]
> Thanks for your feedback @jlei523
> 
> > Most sites do not redirect users to a different domain to login.
> 
> We recommend you use custom domains (eg `login.YOUR_DOMAIN.com`) in production, see https://auth0.com/docs/customize/custom-domains
> 
> > For social auth, they usually show a popup. This is a common user experience that users expect and trust.
> 
> There's nothing stopping you from launching the Universal Login Page in a popup if that's the User Experience you want to go for

This is a good idea. I will try this first.

**Comment by Trayja** [comment]
@adamjmcgrath 
> There's nothing stopping you from launching the Universal Login Page in a popup if that's the User Experience you want to go for

How would one do this? The auth0-react SDK has a handy `loginWithPopup` method but I can't find the equivalent in nextjs-auth0. Thanks in advance.

**Comment by anthony-urbina** [comment]
> @adamjmcgrath
> 
> > There's nothing stopping you from launching the Universal Login Page in a popup if that's the User Experience you want to go for
> 
> How would one do this? The auth0-react SDK has a handy `loginWithPopup` method but I can't find the equivalent in nextjs-auth0. Thanks in advance.

same here, could really use this popup for my next app.. any word on this?

**Comment by georgy-scifind** [comment]
@adamjmcgrath Any update on this question?

> There's nothing stopping you from launching the Universal Login Page in a popup if that's the User Experience you want to go for
