### ISSUE TITLE
Incorrect audience in the JWT

### ISSUE THREAD

**Issue by dariosky** [auth0/nextjs-auth0#613]
Good day, I may be wrong, but when I login and get the JWT via the `getSession()`- `idToken`; what I get as `aud` is what I set in the environment as `AUTH0_CLIENT_ID` when I decode it in https://jwt.io/ (and on my API backend it raises an error though)

I also tried to force the audience with this in my `[...auth0].js`:

```
import { handleAuth, handleLogin } from "@auth0/nextjs-auth0"

export default handleAuth({
  async login(req, res) {
    try {
      await handleLogin(req, res, {
        authorizationParams: {
          audience: process.env.AUTH0_AUDIENCE,
          scope: "openid profile email",
        },
      })
    } catch (error) {
      res.status(error.status || 400).end(error.message)
    }
  },
})
```

**Comment by adamjmcgrath** [comment]
Hi @dariosky 

This is expected behaviour

> `aud` REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value.

https://openid.net/specs/openid-connect-core-1_0.html#IDToken

You should use the Access Token to access an external API, see https://auth0.com/docs/secure/tokens/access-tokens#custom-api-access-tokens

**Comment by dariosky** [comment]
Thank you @adamjmcgrath,
good - I'll relax my backend validation then - he was checking that the audience of the JWT token was the same as the one requested by the client during login - but as you say that's not the case.
It's still unclear to me, where the audience is used in this flow - I found [this thread](https://stackoverflow.com/questions/28418360/) with some explanation.
I'll close this, thanks.

**Comment by adamjmcgrath** [comment]
@dariosky 

> he was checking that the audience of the JWT token was the same as the one requested by the client during login
This is correct - your backend validation should check this and they should match (see: https://auth0.com/docs/secure/tokens/access-tokens/validate-access-tokens)

You just shouldn't try and access the API with an ID Token (aud=CLIENT_ID), you should use the Access Token (aud= AUTH0_AUDIENCE)
