### ISSUE TITLE
wrap withApiAuthRequired

### ISSUE THREAD

**Issue by jaredgalanis** [auth0/nextjs-auth0#615]
I'd like to be able to instantiate the auth0 client (with some data off the request handler request object) and then call `withApiAuthRequired` on the instance of that client. 

To achieve this I thought I'd be able to `initAuth0` and then call `withApiAuthRequired` inside of my API route request handler, rather than the other way around. Something like this:

```
import { initAuth0 } from '@auth0/nextjs-auth0'

export default function MyApiRoute(req, res) {
  //instantiate client with something off the request
  const client = initAuth0({ /* with all the necessary config vars, but whose value depends on data off the req*/})

  return client.withApiAuthRequired(async (req, res) => {
    //do stuff
  })
}
```

When I do this, withApiAuthRequired doesn't seem to be called at all though (I've been debugging inside of the library). I can call other lib methods like `getAccessToken` and they seem to work fine.

Is there an example of this type of thing that you can alert me to @adamjmcgrath?

**Comment by adamjmcgrath** [comment]
Hi @jaredgalanis - I can't see any reason why `withApiAuthRequired` wouldn't be called (unless `initAuth0` throws an error or `MyApiRoute` is not called at all) - you should be able to step through that code and see where it terminates, but if you want me to debug it for you, please share a running example.

The only issue I can see is that `initAuth` shouldn't be called on every request, you should share the same instance of `initAuth` between requests, see how we instantiate the default auth client that we use with the `withApiAuthRequired`  named export: https://github.com/auth0/nextjs-auth0/blob/0bbd9f8a0c93af51f607f28633b5fb18c5e48ad6/src/index.ts#L53-L61

**Comment by jaredgalanis** [comment]
Thanks @adamjmcgrath! 

Good call on the reusing the instance of `initAuth0`. I'll try to do that where possible. I did notice that part of index in the lib too. 🙂

I'll try to get you reproduction asap, but it may be a few days. 

I've definitely been able to recreate what the library is doing with `withApiAuthRequired` in my own wrapper func and it works as expected so I'm wondering if something is short-circuiting it internally in the lib. 

Does the function that is passed to `withApiAuthRequired` need to have special API route properties? Is there a type that I'd need to conform to?

**Comment by adamjmcgrath** [comment]
> I'll try to get you reproduction asap, but it may be a few days.

👍 

> Does the function that is passed to withApiAuthRequired need to have special API route properties? Is there a type that I'd need to conform to?

The function should be a `NextApiHandler` https://github.com/vercel/next.js/blob/v12.0.10/packages/next/shared/lib/utils.ts#L301

**Comment by adamjmcgrath** [comment]
Closing, happy to reopen if you want to provide a reproducible example
