### ISSUE TITLE
Getting useUser.user updated when app_metadata changes

### ISSUE THREAD

**Issue by arbejd** [auth0/nextjs-auth0#626]
### Describe the problem you'd like to have solved
Hi All, love the framework.

I need to get the client to check for changes in the idToken and accessToken once in a while.

using the kitchen-sink-example it takes a logout and a login in order to get any changes down to the client.

Im having a hard time understanding the whole space around "checksession" "refresh tokens", some examples that is named my-handler that doesnt return anything. I think i read most of the documentation and i still cant get anything to work. Is this possible, and do you have any workable examples or hints on this?

### Describe the ideal solution

I would like to get a new idToken at least on page refresh so like 

`useEffect( ()=> 
     refresh()
   , [])` 

## Alternatives and current work-arounds
I think this should be baked in, otherwise the whole app_metadata thing is pretty pointless. I just cant figure it out

### Additional information, if any
Thank you

**Comment by adamjmcgrath** [comment]
Hi @arbejd 

> I need to get the client to check for changes in the idToken and accessToken once in a while.

The authorization server issues ID Tokens and Access Tokens, so the only way to get a new ones is to login again (you can use prompt=none to do this non interactively see https://github.com/auth0/nextjs-auth0/issues/492#issuecomment-919049563)

**Comment by arbejd** [comment]
Ahh makes sense. Do i put this in the normal [...auth0].js or do i create a custom route and redirect or?

**Comment by arbejd** [comment]
Ok for future reference i just made a function on api/refresh and did what this comment suggested.

Thank you @adamjmcgrath !

> Hi @arbejd
> 
> > I need to get the client to check for changes in the idToken and accessToken once in a while.
> 
> The authorization server issues ID Tokens and Access Tokens, so the only way to get new ones is to login again (you can use prompt=none to do this non interactively see [#492 (comment)](https://github.com/auth0/nextjs-auth0/issues/492#issuecomment-919049563))

**Comment by adamjmcgrath** [comment]
> Obviously a refresh button, but if i want it on F5 refresh, how could i call the api/refresh and let it redirect me?

Logging the user in again on every page load is not really something we'd expect you to do, but if you really wanted to you'd basically do what you'd do on click of the refresh button, but when the page loads (with something in place to stop you from endlessly looping between the auth server and your app)

If you just want to get `app_metadata` for the current user you could try using the Auth0 Management API's get user by id endpoint https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id

You'd need an access token with:

audience: `https://{AUTH0_DOMAIN}/api/v2/`
scope: `read:current_user`

See https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#access-an-external-api-from-an-api-route for getting an Access Token for accessing an external API

And see https://auth0.com/docs/microsites/manage-users/define-maintain-custom-user-data

**Comment by arbejd** [comment]
Thank you Adam, i will look into this
