### ISSUE TITLE
AUTH0_SESSION_ROLLING_DURATION

### ISSUE THREAD

**Issue by jagathwee** [auth0/nextjs-auth0#629]
Hi,

Do we need to set AUTH0_SESSION_ROLLING_DURATION and "Inactivity timeout " (Tenant -> Settings -> Advanced -> Login Session Management -> Inactivity timeout)  to the same value for this to work as expected?

Thanks,
Jagath

**Comment by adamjmcgrath** [comment]
Hi @jagathwee

> Do we need to set AUTH0_SESSION_ROLLING_DURATION and "Inactivity timeout " (Tenant -> Settings -> Advanced -> Login Session Management -> Inactivity timeout) to the same value for this to work as expected?

No, the value `AUTH0_SESSION_ROLLING_DURATION` works as expected. These values do not have to be the same, even if they were, the session duration would depend on activity - which could be different on your auth server and your application
