### ISSUE TITLE
Automatically sign in after sign up using Auth0 API

### ISSUE THREAD

**Issue by aldrinc** [auth0/nextjs-auth0#63]
### Describe the problem you'd like to have solved

Through [our website](https://tryjumpstart.co/) we help customers file for a US company online. They enter their information in our form and we ask them for a password and then sign users up via the Auth0 API (/dbconnections/signup endpoint).

Currently I am prompting them to sign in using the Auth0 login page after they place their order but this is a sub-par user experience as the user just signed up as a part of our native flow and now has to sign in again to access his/her account.

```
// My create user function
  createUser = user =>
    fetch(`${process.env.AUTH0_API_ENDPOINT}/dbconnections/signup`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(user)
    })
      .then(response => response.json())
      .then(user => {
        return user
      });
```

### Describe the ideal solution

I want to automatically sign in my new users after they sign up on my website. 

Is there any way to automatically sign the user in after creating his or her account in Auth0 via the API?

**Comment by sandrinodimattia** [comment]
When you create a user through our API (`/dbconnections/signup` or API v2), there is no way to automatically sign in the user afterwards.

**Comment by aldrinc** [comment]
@sandrinodimattia Is there any other approach I can use to sign up and sign in a user as a part of a native flow without spinning up my own auth servers?
