### ISSUE TITLE
Adding support for next js _middleware

### ISSUE THREAD

**Issue by GripenANM** [auth0/nextjs-auth0#633]
### Describe the problem you'd like to have solved
Currently, all authentication for this SDK is only using a function to secure API routes, SSR, and CSR on every page. It makes managing these functions really hard if there's something that needs to be changed, every page will have been revisited and change

### Describe the ideal solution
In the meantime, I don't think I can use get a session in the middleware. So I want to have a _middleware function to authenticate the user on the client-side with next Js _middleware. 

 
## Alternatives and current workarounds
just add the auth function to every page.

**Comment by adamjmcgrath** [comment]
Thanks for raising this @GripenANM 

We already have an open issue for middleware support #525 - so I'll close this in favour of that.

Middleware support is definitely on our roadmap, but I can't give you a timeline for it I'm afraid
