### ISSUE TITLE
Deprecation of the fixed size Authorization Code and Access Tokens

### ISSUE THREAD

**Issue by jordie23** [auth0/nextjs-auth0#636]
### Description

I posted a thread on the auth0 community as suggested but there's been no response from auth0 or package developers. So this doesn't match any of the Issue types but if you're gonna push people to the auth0 community you should at least be active there.

We are using this package and are getting deprecation notices in our auth0 logs.

Please can you make this clear: Is this package ready for the deprecation of the fixed size Authorization Code and Access Tokens? Is it all versions of the package which work or is there a particular version required? Or is there some configuration option we need to check/change to handle it?

Thread: 
https://community.auth0.com/t/nextjs-deprecation-of-the-fixed-size-authorization-code-and-access-tokens/80875

**Comment by jordie23** [comment]
Hi @adamjmcgrath 

Thanks for the response, I appreciate it. That answers my question perfectly. 

We have been testing today with out dev tenant and haven't seen issues, but wanted to confirm that we didn't need to urgently adjust config or get the package update out (we're about it update it actually, but just good to know it's not going to break the site if we don't get it out in time).

**Comment by adamjmcgrath** [comment]
No problem @jordie23 👍
