### ISSUE TITLE
Getting 404 /api/auth/login not found in vercel deployment

### ISSUE THREAD

**Issue by bymoe** [auth0/nextjs-auth0#640]
Everything works locally just fine, but I am getting `/api/auth/login 404` not found on production, the login page refuse to appear.

![error](https://user-images.githubusercontent.com/20565199/162476900-5af802f2-ede2-4414-a6ae-d60dcd9f8150.png)

I have everything set up as described [here](https://github.com/auth0/nextjs-auth0/tree/main/examples#hosting-on-vercel)  

Callback url
`https://{VERCEL_GIT_REPO_SLUG}-*-{VERCEL_TEAM}.vercel.app/api/auth/callback`
Logout url
`https://{VERCEL_GIT_REPO_SLUG}-*-{VERCEL_TEAM}.vercel.app/`

And I've checked my environment variables hundred times and they're all set. Appreciate any help!

**Comment by Widcket** [comment]
Hi @bymoe, thanks for raising this.

Please check out https://github.com/auth0/nextjs-auth0/issues/566.
