### ISSUE TITLE
this site can’t provide a secure connection 

### ISSUE THREAD

**Issue by mxcdh** [auth0/nextjs-auth0#642]
Hello

I have problem with secure connection in my project.
Bellow my setup and code:
![error](https://user-images.githubusercontent.com/98115983/162567099-80276aa7-546d-40e1-aa77-ea7a52001ec1.png)

![auth0](https://user-images.githubusercontent.com/98115983/162567061-b9d46fbd-c568-4406-a253-445be708da5a.png)

What is wrong?

**Comment by Widcket** [comment]
Hi @mxcdh, thanks for raising this.

This doesn't look like an issue with the SDK. Are you able to reproduce this with the [kitchen sink](https://github.com/auth0/nextjs-auth0/tree/main/examples/kitchen-sink-example) example app?

**Comment by Widcket** [comment]
Closing as it seems you're no longer experiencing the issue. Please ping if you'd prefer to reopen.
