### ISSUE TITLE
TypeError: "secret" is required

### ISSUE THREAD

**Issue by Mikasuru** [auth0/nextjs-auth0#644]
> I got this error and idk how to fix
- Source
```
(api)\pages\api\auth\[auth0].ts (3:25) @ eval

  1 | import { handleAuth } from '@auth0/nextjs-auth0';
  2 | 
> 3 | export default handleAuth();
    |                         ^
  4 | 
```

**Comment by Mikasuru** [comment]
There is my .env.local
```
AUTH0_SECRET='xxxx'
# The base url of your application
AUTH0_BASE_URL='http://localhost:3000'
# The url of your Auth0 tenant domain
AUTH0_ISSUER_BASE_URL='https://xxx.us.auth0.com'
# Your Auth0 application's Client ID
AUTH0_CLIENT_ID='xxx'
# Your Auth0 application's Client Secret
AUTH0_CLIENT_SECRET='xxx'
```

**Comment by adamjmcgrath** [comment]
Hi @Mikasuru - thanks for raising this

As long as your `AUTH0_SECRET` environment variable is defined, you wont get a `"secret" is required` when `handleAuth()` is executed. So I can only assume that your environment variables aren't being loaded.

You can confirm this by printing out the  `AUTH0_SECRET` environment variable before line 3 in `(api)\pages\api\auth\[auth0].ts` eg 

```
import { handleAuth } from '@auth0/nextjs-auth0';

console.log('AUTH0_SECRET = ', process.env.AUTH0_SECRET)

export default handleAuth();
```

**Comment by birdboy307** [comment]
I'm having the same issue

**Comment by cindyloo** [comment]
AUTH0_SECRET or AUTH0_CLIENT_SECRET? (it's the former)

**Comment by GithubOllie** [comment]
Here are two simple things that caught me out and resolved the issue. 

Ensure your `env.local` is actually '.env.local'
Ensure the `.env.local`file is located at the root of your project. (mine was in the src file which cause the error)

**Comment by bh865** [comment]
> Hi @Mikasuru - thanks for raising this
> 
> As long as your `AUTH0_SECRET` environment variable is defined, you wont get a `"secret" is required` when `handleAuth()` is executed. So I can only assume that your environment variables aren't being loaded.
> 
> You can confirm this by printing out the `AUTH0_SECRET` environment variable before line 3 in `(api)\pages\api\auth\[auth0].ts` eg
> 
> ```
> import { handleAuth } from '@auth0/nextjs-auth0';
> 
> console.log('AUTH0_SECRET = ', process.env.AUTH0_SECRET)
> 
> export default handleAuth();
> ```

I'm getting the same error but I can see my secret when I console it like you mentioned.

**Comment by jlundholm-git** [comment]
This question deals more with trying to run NextJS locally, but I was having the same issue while trying to build the image in GitHub Actions. Passing environment variables to a Docker image through build args was giving me issues and since the variable just needs to be set I settled for this.

```
import { handleAuth, handleLogin } from '@auth0/nextjs-auth0';

export const GET = () => {
  process.env.AUTH0_SECRET = process.env.AUTH0_SECRET || 'fake';

  return handleAuth({
    login: handleLogin({
      returnTo: "/",
    }),
  });
}
```

**Comment by haiderkamrann** [comment]
You have to edit the next.config.js file and add:

require('dotenv').config();

module.exports = {
  env: {
    AUTH0_SECRET: process.env.AUTH0_SECRET,
    AUTH0_BASE_URL: process.env.AUTH0_BASE_URL,
    AUTH0_ISSUER_BASE_URL: process.env.AUTH0_ISSUER_BASE_URL,
    AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID,
    AUTH0_CLIENT_SECRET: process.env.AUTH0_CLIENT_SECRET,
  },
};
