### ISSUE TITLE
net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by elliotchaim** [auth0/nextjs-auth0#645]
### Description

- The application returns an opaque network error when trying to redirect to Auth0 to authenticate the user.
- I have adequate logging mechanisms in place, yet I do not receive error logs (neither in development nor in production)
- Frustratingly, this happens intermittently - but more frequently than I would like.
    - I experience in development from time to time. When I do, I am forced to restart my machine to stop the error from occuring.
    - I have Datadog Synthetic Monitoring in place from which I can infer that this happens in production (Netlify) at least once per day.
    - Interestingly, when this happens in production, it occurs in some locations and not others at the same time.
- I have also raised https://github.com/vercel/next.js/issues/36322 as I cannot be sure if this is the framework or the auth0 package.

Error recieved:

```
net::ERR_CONNECTION_RESET - https://mydomain.com/my-route
```

### Reproduction

- Navigate to any page exported with `withPageAuthRequired`
- Happens intermittently

### Environment

> Please provide the following:

```
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
Binaries:
  Node: 16.13.0
  npm: 8.1.0
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 12.1.5
  react: 18.0.0
  react-dom: 18.0.0
  @auth0/nextjs-auth0: 1.7.0,
```

**Comment by adamjmcgrath** [comment]
Hi @elliotchaim - thanks for raising this

`net::ERR_CONNECTION_RESET` usually means that your browser can’t connect to your server - it would be hard for me to tell you any more than this without more information. Can you provide a reproducible example?

**Comment by zemlatruskavets** [comment]
I also started getting this error a few days ago; like Elliot, I don't get any useable information in the logs and the error occurs intermittently (thus difficult to reproduce).

**Comment by adamjmcgrath** [comment]
There's not much I can do with the information you've given, if you can provide a reproducible example I'd be happy to reopen this and debug it for you

**Comment by elliotchaim** [comment]
@adamjmcgrath As explained, this problem is intermittent so I can't really give you a reproducible example.

I've just had this locally so I can give you the following log:

```
HandlerError [RequestError]: read ECONNRESET
    at new HandlerError (/Users/elliotchaim/project/frontend/app-portal/node_modules/@auth0/nextjs-auth0/dist/utils/errors.js:53:28)
    at Object.<anonymous> (/Users/elliotchaim/project/frontend/app-portal/node_modules/@auth0/nextjs-auth0/dist/handlers/login.js:35:31)
    at step (/Users/elliotchaim/project/frontend/app-portal/node_modules/@auth0/nextjs-auth0/node_modules/tslib/tslib.js:144:27)
    at Object.throw (/Users/elliotchaim/project/frontend/app-portal/node_modules/@auth0/nextjs-auth0/node_modules/tslib/tslib.js:125:57)
    at rejected (/Users/elliotchaim/project/frontend/app-portal/node_modules/@auth0/nextjs-auth0/node_modules/tslib/tslib.js:116:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ECONNRESET'
}
```

This occurs when navigating to the `/api/auth/login` route in my browser. It seems like the nextjs backend is struggling to communicate with auth0. But this is all code provided by the `nextjs-auth0` package.
