### ISSUE TITLE
TypeError: "additionalSignUpFields" is not allowed

### ISSUE THREAD

**Issue by SantinoPetrovic** [auth0/nextjs-auth0#646]
Hi!

I'm trying to set up initAuth0 function with additionalSignUpFields, but I am getting this error: TypeError: "additionalSignUpFields" is not allowed.

As I understand it, additionalSignUpFields is not an option to be placed in initAuth0 function. Is there other ways with nextjs-auth0 to be able to pass in additionalSignUpFields or is there other ways to add/pass custom fields with this SDK?

This is the initAuth0 code below I've tried to use:

```
import { initAuth0 } from '@auth0/nextjs-auth0';

export default initAuth0({
  clientID: process.env.AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET,
  secret: process.env.AUTH0_SECRET,
  baseURL: process.env.AUTH0_BASE_URL,
  issuerBaseURL: process.env.AUTH0_ISSUER_BASE_URL,
  httpTimeout: 2500,
  authorizationParams: {
    screen_hint: 'signup',
    scope: process.env.AUTH0_SCOPE,
  },
  additionalSignUpFields: [{
    name: "first_name",
    placeholder: "Your first name",
  },
  ],
});
```

**Comment by adamjmcgrath** [comment]
Hi @SantinoPetrovic - thanks for raising this

This SDK just redirects users to the Universal Login Page - you can't configure the login experience from this SDK. 

[additionalSignUpFields](https://auth0.com/docs/libraries/lock/lock-configuration#additionalsignupfields-array-) is a feature of the Lock SDK which is used in the Classic Universal Login page, you can learn how to customise the Class Universal Login page here https://auth0.com/docs/customize/universal-login-pages/customization-classic

**Comment by SantinoPetrovic** [comment]
Hi again!

I see. Thanks for the answer!

**Comment by adamjmcgrath** [comment]
np 👍
