### ISSUE TITLE
`checks.state argument is missing` after calling `webAuth.authorize()` with google one tap

### ISSUE THREAD

**Issue by sakekasi** [auth0/nextjs-auth0#647]
### Description

I am using the method described [here](https://community.auth0.com/t/integrating-google-one-tap-sign-up-login-with-auth0/20209/9) to integrate google one-tap with my next js app. In short, it calls webauth.authorize() to authorize with auth0 after authorizing with google. This worked in a previous app that used auth0-passport, but when I run it with my nextjs-auth0 server, it gives me a `checks.state argument is missing` error. 

### Reproduction

* modify the basic nextjs-auth0 example to add in google one tap
* call webAuth.authorize()

(I'm happy to create a reproducing repo if that is necessary)

Here are the network requests being made from my app

<img width="653" alt="Screen Shot 2022-04-21 at 3 08 22 PM" src="https://user-images.githubusercontent.com/979969/164560676-fa860d36-2655-4b08-a108-2179a04c8974.png">

As you can see, we never visit `/api/auth/login`, so the `state` cookie is never set. Is it possible to configure nextjs-auth0 to use a different form of transient state that would work better with webauth?

### Environment

> Please provide the following:

- nextjs-auth0 version 1.7.0
- nextjs 12.1.5
- auth0-js 9.18.0

**Comment by sakekasi** [comment]
For further reference, here's what a successful authentication with google sign in looks like. After the first callback, a login is initiated which leads to a second callback

<img width="653" alt="Screen Shot 2022-04-21 at 3 43 42 PM" src="https://user-images.githubusercontent.com/979969/164563374-00166bbf-f190-48ad-996d-384e7049bc80.png">

**Comment by sakekasi** [comment]
Looks like I was able to resolve the issue by redirecting the user to the login page on error instead of giving them a 500

```
export default async function callback(req: NextApiRequest, res: NextApiResponse) {
  try {
    const auth0 = await ensureAuth0();
    await auth0.handleCallback(req, res);
  } catch (error: any) {
    console.error(error);
    res.redirect(302, '/api/auth/login');
  }
}
```

Does this seem reasonable? I know it's a little bit odd to be relying on redirecting to login like this. Do you think this is a safe thing to do?

**Comment by adamjmcgrath** [comment]
Hi @sakekasi - thanks for raising this

Your suggestion would work, but you should be able to do [those steps](https://community.auth0.com/t/integrating-google-one-tap-sign-up-login-with-auth0/20209/9) replacing auth0-js with nextjs-auth0, eg instead of:

> 3. Use [Auth0.js’s authorize() 79](https://auth0.com/docs/libraries/auth0js/v9#webauth-authorize-) method to perform an authentication flow with Auth0, passing a connection parameter with a value of google-oauth2 and a login_hint with a value of the email address you collected in step 2

Login with `nextjs-auth0` passing a connection parameter with a value of google-oauth2 and a login_hint with a value of the email address you collected in step 2 eg.

```js
const { sub: email } = await performGoogleOneTap();
window.location.href = `/api/auth/custom-login?email=${email}`;
```

```js
// pages/api/auth/custom-login.js
export default async function login(req: NextApiRequest, res: NextApiResponse) {
  try {
    await auth0.handleLogin(req, res, {
      authorizationParams: {
        connection: 'google-oauth2',
        login_hint: req.query.email
      }
    });
  } catch (error: any) {
    console.error(error);
  }
}
```

**Comment by sakekasi** [comment]
Just gave it a try, and it works! I like this way much better, since it saves me an extra round of redirects. Thanks a million for the help!

**Comment by adamjmcgrath** [comment]
Great! Happy to help @sakekasi
