### ISSUE TITLE
Using a custom cookie domain when creating an instance results in 2 cookies

### ISSUE THREAD

**Issue by danr-za** [auth0/nextjs-auth0#648]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/main/CODE-OF-CONDUCT.md).

### Description

We use a cookie domain to share the cookie between subdomains.
We need the host from the request thus the handler is created on-demand and we pass it there:
```ts
return initAuth0({
    session: {
      cookie: {
        domain: <our custom domain>
      }
    }
  })
```

This however results in having 2 cookies after logging in:
* One with the custom domain
* One with a "default" domain 

**Note** - doing the same with an environment variable `AUTH0_COOKIE_DOMAIN` results in a single cookie as expected.

### Reproduction

* Add a handler that creates an instance on-demand and pass a custom domain
* Login
* Observe your cookies

### Environment

> Please provide the following:

- **Version of this library used: 1.7.0**
- **Version of the platform or framework used, if applicable: Next.js v12.1.5**
- **Other relevant versions (language, server software, OS, browser):Chrome,MacOS**
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hi @danr-za - thanks for raising this

Couple of suggestions:
- Are you mixing your own instance and the named exports, you need to use on or the other (See https://auth0.github.io/nextjs-auth0/modules/config.html#configuration-properties)
- Could the second cookie be from a previous debugging session that you haven't cleared

If it's neither of the above, could you provide a reproducible example? I can't see anything wrong with your code and can't reproduce the issue using `initAuth0`

**Comment by danr-za** [comment]
Thanks for the quick response @adamjmcgrath!
 
Yep, figured out the imports of the handlers were from the library and not the instance we manually created. 🤦
Now that made a lot of sense in other issues we experienced.
Hope its fine and I'll ask another question here that relates to this - 
What we're currently doing is extracting the `idToken` and `accessToken` on `afterCallback`:
```ts
afterCallback(req,res,session) { 
  storeIdToken(session.idToken) // sets an `id_token` cookie with the value
  storeAccessToken(session.accessToken) // sets an `access_token` cookie with the value
  delete session.idToken
  delete session.accessToken
}
```

Our BE expects them for authentication and it also reduces the cookie size in general (together with other claim strips we perform).

Thing is, because the cookie's expiration is set to session, we need to set them and we use `handleProfile` for that:
```ts
async profile(req, res) {
      const session = auth0.getSession(req, res)
      const shouldRefetch = helper.shouldRefetch(req, res, session)

      await auth0.handleProfile(req, res, {
        refetch: shouldRefetch,
        afterRefetch: callback(handler)
      })
    }
```

but, because we previously delete idToken and accessToken it throws and error that access token does not exist.
We expected that refetch would actually create a new session with those but its clearly not the case.

Is there a proper way to achieve that?

Thanks!

**Comment by adamjmcgrath** [comment]
np @danr-za 

> We expected that refetch would actually create a new session with those but its clearly not the case.

`refetch` calls `/userinfo` to refetch your profile information. `/userinfo` requires an Access Token to authenticate, which is why the method is failing, because it can't find an Access Token in your session.

If you want to create a new session, you need to login again or use refresh tokens.

- to login again, you need to visit the login handler, you can use prompt=none to do this non interactively
- to use refresh tokens you need to add the `offline_access` scope, then `getAccessToken` will fetch new tokens when the Access Token expires or when you pass `refresh: true` (you can use `afterRefresh` to strip the tokens from the session and update your BE)

**Comment by danr-za** [comment]
Perfect, we eventually used the refresh token (we already had it, just refreshed it on the profile handler when necessary).
Thanks for the help again.
