### ISSUE TITLE
Option to log user out of auth0 session after app session expired

### ISSUE THREAD

**Issue by knapcp3** [auth0/nextjs-auth0#651]
### Problem

After getting 401 response from the protected endpoint (because app session expired), I call `window.location.assign('/api/auth/logout')` but I don’t get logged out from auth0 session. This case is handled in this file [nextjs-auth0/logout.ts at main · auth0/nextjs-auth0 · GitHub](https://github.com/auth0/nextjs-auth0/blob/main/src/auth0-session/handlers/logout.ts) and it looks like condition on line 27 is true (when this is called after getting 401 response earlier from the API) so endSessionUrl is not called and user is not logged out of auth0 session.
I would expect that there is an option to log the user out of auth0 session when calling `/api/auth/logout` endpoint.

### Possible solution

Creating a query parameter available on the `/api/auth/logout` endpoint which indicates if the `{AUTH_SERVER}/v2/logout` endpoint should be called.

**Comment by adamjmcgrath** [comment]
Hi @knapcp3 - thanks for raising this

We've considered this before in https://github.com/auth0/nextjs-auth0/issues/362#issuecomment-821202378 and our advice is to use the Auth0 API directly for these cases
