### ISSUE TITLE
withPageAuthRequired breaks hot reloading

### ISSUE THREAD

**Issue by 6peterlu** [auth0/nextjs-auth0#652]
### Description

When wrapping `pages/index.tsx`'s default export in `withPageAuthRequired`, hot reloading stops working.

### Reproduction

- Create a default next.js project
-`import { withPageAuthRequired } from '@auth0/nextjs-auth0';`
- Wrap the index component with the auth0 function
- Run `next dev` to run the dev server
- Attempt to edit code within `index.tsx`.
- Observe a full reload instead of a hot reload.

### Environment

> Please provide the following:

- **Version of this library used:**
1.7.0
- **Version of the platform or framework used, if applicable:**
next version 12.1.4
- **Other relevant versions (language, server software, OS, browser):**
On MacOS and Linux inside Docker
- **Other modules/plugins/libraries that might be involved:**
N/A

**Comment by adamjmcgrath** [comment]
Thanks for raising @6peterlu 

Should be fixed by #653
