### ISSUE TITLE
Support multiple database connections

### ISSUE THREAD

**Issue by osdiab** [auth0/nextjs-auth0#662]
### Describe the problem you'd like to have solved

I have some applications that currently include more than one database connection. This is problematic because when a user sets their password after being invited to the app using one of the connections, when they try to log in it appears to fail since Auth0 is checking against the wrong database connection.

### Describe the ideal solution

Support [the `connectionResolver` callback that is mentioned in the Auth0 Lock documentation](https://github.com/auth0/lock#other-options). Or if it already supported, mention it somewhere in the documentation.

## Alternatives and current work-arounds

- specify the specific connection to use when creating the `auth0` instance. this doesn't really work since we don't know who's logging in yet at that point in the auth flow; would need to ask it first.
- Dont use `@auth0/nextjs` and instead use lock; but that kinda sucks

### Additional information, if any

[Auth0 Lock library docs mention](https://auth0.com/docs/libraries/lock/selecting-from-multiple-connection-options?#selecting-among-multiple-database-connections)

**Comment by adamjmcgrath** [comment]
Hi @osdiab - thanks for raising this

>  when they try to log in it appears to fail since Auth0 is checking against the wrong database connection.

Could you explain the steps you take to login and the error message you get

Lock is a different type of SDK to this, it is an embedded form that sends username/password and this SDK just redirects to the Universal Login Page, so a `connectionResolver` wouldn't apply to this SDK.

**Comment by osdiab** [comment]
Hi @adamjmcgrath , we just fixed it on our end by no longer using multiple database connections with a single app, so this isn't as urgent anymore.

But basically what was happening was that in our app, we have an invite flow powered by the Auth0 reset password flow, which Auth0 recommends. In doing so we specify the database connection to use, so the user ends up making an account in a specific database connection. But then when they try to log in, we weren't specifying the specific database connection, so our user would get redirected to the default universal login page, but wouldn't be able to log in since the username/password form was (arbitrarily?) using a different database connection.

Like I said not as important for us anymore, but yea i don't really know how one would work with `@auth0/nextjs-auth0` and Universal Login with multiple connections - maybe by having a custom universal login page that instantiates Lock with the necessary parameters? 🤷🏼

**Comment by adamjmcgrath** [comment]
> But then when they try to log in, we weren't specifying the specific database connection

You can specify a connection to log into by passing the `connection` argument to `authorizationParams` in the login handler, eg:

```js
// pages/api/auth/[...auth0].js
import { handleAuth, handleLogin } from '@auth0/nextjs-auth0';
import { myCustomLogger, myCustomErrorReporter } from '../utils';

export default handleAuth({
  async login(req, res) {
    await handleLogin(req, res, {
        authorizationParams: {
          connection: 'my-connection'
        }
      });
  }
});
```

**Comment by osdiab** [comment]
Yes but if you want users to be able to select a social login option that doesn't work.

**Comment by osdiab** [comment]
makes sense, yeah hardcoding a connection to use forces the user to use that connection, whereas I'm saying that lock has the capability to _without forcing a specific connection_, to provide a function to determine which database connection to use, should that user decide to use username/password login. but yeah sounds like you would set up that configuration in a customized universal login page, on auth0's end, not at the NextJS application's end. Makes sense, I'll close this then!
