### ISSUE TITLE
works perfectly locally, does not work with vercel deployment custom url

### ISSUE THREAD

**Issue by delasky** [auth0/nextjs-auth0#667]
### Description

Apologies in advance. I've read https://github.com/auth0/nextjs-auth0/issues/566 and the vercel hosting sections of the README but I think there's something I'm either not understanding or doing wrong.

Everything works perfectly locally, but when I deploy using a custom domain on vercel, i get `expected 200 OK, got: 404 Not Found`

I don't need the preview or git branch deployments to work, just the production deployment at my domain, foo.com.

I have foo.com set as the AUTH0_BASE_URL in a .env.production file, and as a vercel env variable.

I can confirm that this env variable is being properly set in the deployed application.

i have the domain in my Auth0 application settings in allowed callback settings
`https://foo.com/api/auth/callback`
and in my allowed logout urls.

Still no joy. I'm guessing there's something simple I'm misunderstanding but right now I'm stumped and any help would be appreciated.

**Comment by adamjmcgrath** [comment]
Hi @delasky 

> Everything works perfectly locally, but when I deploy using a custom domain on vercel, i get expected 200 OK, got: 404 Not Found

When are you getting this error? When you visit `https://foo.com/api/auth/login`? It actually looks like an error from the `openid-client` trying to find your issuer's discovery document.

What value do you have for `AUTH0_ISSUER_BASE_URL` in production?
