### ISSUE TITLE
Rolling session issue

### ISSUE THREAD

**Issue by foxfl** [auth0/nextjs-auth0#673]
### Description

We have added this library in our next.js application. It seems like the rolling session is not working as expected. We use the ID-Token from the session to authenticate with an external GraphQL Api. The expire time of the ID-Token and Access Token are set to the same values and we request the `offline_access`to get a refresh token. After the expiration of the access and id token, the session is not refreshed and we are hitting a 401 on the external API. Every `getServerSideProps` is wrapped in `withPageAuthRequired`, which we thought would take care of refreshing tokens after expiration. And each local API ist wrapped in 'withApiAuthRequired' 

This is how our `handleAuth` looks like 

```
export default handleAuth({
  async login(req, res) {
    try {
      await handleLogin(req, res, {
        authorizationParams: {
          // Add the `offline_access` scope to also get a Refresh Token
          scope: 'openid profile email offline_access', // or AUTH0_SCOPE
          audience: 'https://aws.amazon.com'
        }
      });
    } catch (error) {
      res.status(error.status || 400).end(error.message);
    }
  }
});
```

Example of an `getServerSideProps`

```
export const getServerSideProps =
  withPageAuthRequired<ApolloServerSidePropsResult>({
    getServerSideProps: async ({ req, res, params }) => {
      const { qid } = params || {};
      try {
        const { idToken, user } = getSession(req, res) || {};

        ... fetch from API ...

        return {
          props: {
           result: apiData
          }
        };
      } catch (error) {
        return {
          props: {
            result: null
          }
        };
      }
    }
  });
```

Are we missing something here? 

### Version of this library used:
1.9.0
Version of the platform or framework used, if applicable:
next.js 12.1.4

**Comment by adamjmcgrath** [comment]
Hi @foxfl - thanks for raising this

ID Tokens are not designed to call APIs (see https://auth0.com/blog/id-token-access-token-what-is-the-difference/#What-Is-an-ID-Token-NOT-Suitable-For- for more information)

If you use the Access Token to access your external API, you'll call `getAccessToken` which will automatically refresh it for you when the Access Token expires if you have a Refresh Token.

See this example for reference https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#access-an-external-api-from-an-api-route

**Comment by adamjmcgrath** [comment]
Hi @foxfl - I think this answers your question. Feel free to ping me if you want me to reopen this
