### ISSUE TITLE
`GetServerSidePropsWrapper` type issues with Props and Query

### ISSUE THREAD

**Issue by zackdotcomputer** [auth0/nextjs-auth0#675]
### Describe the problem

Wrapping a `getServerSideProps` function with `getServerSidePropsWrapper` causes erasure of the P and Q types, which means the result cannot be type-checked to match against the page component's expected Props or the paths expected Query.

Additionally, if the Q type is defined, then the function cannot be handed to the wrapper as it complains about a potential disagreement between Q and `ParsedUrlQuery`.

### What was the expected behavior?

`getServerSidePropsWrapper` should accept any P and Q types and should return precisely the same type as the handler it wraps.

### Reproduction

The issue is reproducible with just a few lines of TS code:
```typescript
import { getServerSidePropsWrapper } from "@auth0/nextjs-auth0";
import { GetServerSideProps, GetServerSidePropsContext, Redirect } from "next";

const getPropsExample: GetServerSideProps<{ roles: string[] }, { userId: string }> = async () => {
  return { redirect: { destination: "/", permanent: false } };
};
const wrappedExample: typeof getPropsExample = getServerSidePropsWrapper(getPropsExample);
```

This produces two compiler errors on the final line:
On the assignment because of the Props erasure:
```
Type 'GetServerSideProps<{ [key: string]: any; }, ParsedUrlQuery, PreviewData>' is not assignable to type 'GetServerSideProps<{ roles: string[]; }, { userId: string; }, PreviewData>'.
  Property 'roles' is missing in type '{ [key: string]: any; }' but required in type '{ roles: string[]; }'.ts(2322)
```

On the wrap because of the Query erasure:
```
Argument of type 'GetServerSideProps<{ roles: string[]; }, { userId: string; }, PreviewData>' is not assignable to parameter of type 'GetServerSideProps<{ [key: string]: any; }, ParsedUrlQuery, PreviewData>'.
  Property 'userId' is missing in type 'Dict<string | string[]>' but required in type '{ userId: string; }'.ts(2345)
```

### Environment

- `@auth0/nextjs-auth0` version `1.9.0`
- `next` version `12.1.6`
- Typscript version `4.6.2`

**Comment by adamjmcgrath** [comment]
Thanks for raising this @zackdotcomputer - we'll add something to our backlog
