### ISSUE TITLE
Add suggestion to configure `www.` redirect to avoid `BadRequest: checks.state`

### ISSUE THREAD

**Issue by SpencerKaiser** [auth0/nextjs-auth0#676]
_Note: I'm by no means an expert on this stuff; just sharing my understanding and hoping others will correct anything that's inaccurate_

### Describe the problem you'd like to have solved
[There are quite a few issues describing the dreaded `BadRequest: checks.state` issue](https://github.com/auth0/nextjs-auth0/issues?q=is%3Aissue+checks.state+is%3Aclosed). After experiencing it myself I think I've discovered more info that might help others. I would love to see a change to the docs to encourage users to setup a permanent redirect to force their users to visit the domain **with OR without** `www` but not both.

### Describe the ideal solution
As many have found, the issue occurs when the cookie is not present after being redirected back to the app's callback. I experienced this issue in our production environment after NEVER seeing it in stage and I eventually traced it back to it being an issue with `www.` (something we don't have since our stage environment is `stage.my-awesome-site.com` and subdomains don't seem to be compatible with `www`). 

Here's what happened:
- A user navigated to `www.my-awesome-site.com` (take note of the **`www.`**) and didn't have a valid session
- Our `AUTH0_BASE_URL` value was set to `https://my-awesome-site.com` (**without `www.`**)
- After the user authenticates, Auth0 redirects the user to `AUTH0_BASE_URL + returnTo`, which is effectively a different domain from where the user started
- 💥 `BadRequest: checks.state` after the cookie is dropped by the browser

## Alternatives and current work-arounds
In order to account for this in our app, we configured a permanent redirect to effectively remove the `www.`, which has worked perfectly.

### Additional information, if any
Not sure if there's something on the Auth0 that could be configured to allow for URLs with **_and_** without `www.`, but I imagine this is much more of an http issue, so I think a callout to setup this redirect would likely help others avoid the issue!

**Comment by adamjmcgrath** [comment]
Hi @SpencerKaiser - thanks for raising this

> Not sure if there's something on the Auth0 that could be configured to allow for URLs with and without www., 

Yes, by default the [Cookie domain config](https://auth0.github.io/nextjs-auth0/interfaces/config.cookieconfig.html#domain) is not set, so creates a "Host only cookie" (`www.my-awesome-site.com` is a different host than `my-awesome-site.com`)

If you set Cookie domain config to the naked domain `my-awesome-site.com` your Cookie can be read by both `www.my-awesome-site.com` and `my-awesome-site.com`.

This is not the default because you may be hosting on a subdomain and not want to share your cookie with other sub domains

**Comment by SpencerKaiser** [comment]
That's immensely helpful! So how do I configure that within my setup? (I'd still like to know although I don't necessarily need it anymore now that we have the redirect - I also think it looks cleaner without `www.`, so win win? 😅)

And hopefully this helps yall because I'm sure responding to that error has been painful for everyone on your team... the forum posts don't seem to be much help either, so I really hope this helps knock down the number of requests you get from users for this one!

**Comment by adamjmcgrath** [comment]
> So how do I configure that within my setup?

You provide the `AUTH0_COOKIE_DOMAIN` environment variable, see https://auth0.github.io/nextjs-auth0/interfaces/config.cookieconfig.html#domain

Thanks for your advice on the docs, we'll take it on board with any planned update. 

Closing, as I think I've answered your question on customising the cookie domain
