### ISSUE TITLE
Modify "signUpLink" option?

### ISSUE THREAD

**Issue by mjunix** [auth0/nextjs-auth0#678]
I'm trying to modify the [signupLink](https://auth0.com/docs/libraries/lock/lock-configuration) option.
Is this possible when using this package? (Either through this package or some other way like dashboard or management API?)

**Comment by adamjmcgrath** [comment]
Hi @mjunix - thanks for raising this

You can't modify that option in this SDK, but if you're using the [Classic Login Experience](https://auth0.com/docs/authenticate/login/auth0-universal-login/classic-experience) you can modify Lock's option's yourself by customising the Login page template, see https://auth0.com/docs/customize/universal-login-pages/customization-classic for more info
