### ISSUE TITLE
Don't get IdToken nor AccessToken 

### ISSUE THREAD

**Issue by tobkle** [auth0/nextjs-auth0#69]
I'm able to login to Auth0. But whenever I switch on any of the tokens, I don't get a valid session any more. I never get an IdToken nor an AccessToken into my session for using them with Apollo authenticating in Hasura:
```
    // Store the id_token in the session. Defaults to false.
    storeIdToken: true,
    // Store the access_token in the session. Defaults to false.
    storeAccessToken: true,
```

```
    "@apollo/react-hooks": "3.1.3",
    "@apollo/react-ssr": "3.1.3",
    "@auth0/nextjs-auth0": "^0.10.0",
    "apollo-cache-inmemory": "1.6.5",
    "apollo-client": "2.6.8",
    "apollo-link-context": "1.0.19",
    "apollo-link-http": "1.5.16",
    "dotenv": "^8.2.0",
    "graphql": "14.5.8",
    "graphql-tag": "2.10.1",
    "isomorphic-unfetch": "^3.0.0",
    "js-cookie": "2.2.1",
    "next": "9.1.7",
    "react": "16.12.0",
    "react-dom": "16.12.0"
```

Tried also the example from https://github.com/vgrafe/nextjs-auth0-hasura
But never got it working with Authorization Header only with anonymous, which is not what I  require.

**Comment by kavuri** [comment]
Same here. I got some short string like 1h4NJkvu_HOM7O2y4OXUwH5xgphmjgYP, which is definitely not an access token.

**Comment by tobkle** [comment]
Also the examples in the folders ```examples/api-call-example``` in combination with ```examples/sample-api``` aren't working. As soon as I set ```storeIdToken: true```, I don't get a session any more. If I have it on ```false```, I get a session, but without token.
Do I need to setup a special configuration in the Auth0 Dashboard somewhere in order to get that working?

**Comment by vgrafe** [comment]
Something is off indeed. The auth on the live demo is not working. I'll look into why this weekend.

**Comment by balazsorban44** [comment]
I have the same issue. I am a *noob*, but with some `console.log`-ing, I found out, that at this point: https://github.com/auth0/nextjs-auth0/blob/7a4a33c4e603b8f2a9e4db8bd05850ddb15e95bb/src/handlers/callback.ts#L47

`session` still has `accessToken`, so something after that might screw it up.

I don't know if it is helpful information, just wanted to share.

**Comment by semyou** [comment]
Has this been investigated?

**Comment by Afsoon** [comment]
About this issue, can you make an example repository?. Because I have a project with Hasura, Apollo and Auth0, with SSR, working without problems. 

The only way to retrieve the `idToken` remember is in the API and using the method `getSession`. You have a small explanation in this comment I made in another issue https://github.com/auth0/nextjs-auth0/issues/21#issuecomment-578383434

**Comment by tobkle** [comment]
@Afsoon We can use also the example you've already checked. It is the very same problem there. I tried also [https://github.com/BjoernRave/Auth0-Urql-Nextjs-Prisma2](https://github.com/BjoernRave/Auth0-Urql-Nextjs-Prisma2) and read your comment. I have the very same problem:

If I set in lib/auth0.ts
```
storeIdToken: true,
```
The login isn't successfully processed any more.
In console I see a message:

```has accessToken gip false```

I also changed /pages/api/getToken.ts in order to see the session content:
```
import auth0 from '../../lib/auth0';

export default async function session(req, res) {
	try {
		// const { accessToken } = await auth0.getSession(req);
		// if (accessToken) res.send(accessToken);
                // res.status(500).end(accessToken);
                // did instead...
		const session = await auth0.getSession(req);
		if (session) res.send(session);
		res.status(500).end(session);
                 ...
}
```

But as Login doesn't succeed with the storeIdToken flag, I don't get any idToken in my session if I run 
```
http://localhost:3000/api/getToken
```

**Comment by tobkle** [comment]
@Afsoon However, I would be also interested in your Hasura example, I haven't worked out yet, how to proxy the Hasura call within /pages/api/hasuracall.ts

**Comment by Afsoon** [comment]
I forked the project from the other issue and made the changes I said in the comment, https://github.com/Afsoon/Auth0-Urql-Nextjs-Prisma2, in the following screenshot can you notice in the first load the idToken is null, because I never logged but after the login you can see the token in the console:

<img width="1680" alt="imagen" src="https://user-images.githubusercontent.com/713534/73121000-35833d80-3f6d-11ea-93b8-8a36a5443b0b.png">

And you can see in the React Dev Tools, you notice the props `idToken`, that contains the value of the JWT: 

<img width="1680" alt="imagen" src="https://user-images.githubusercontent.com/713534/73120991-12f12480-3f6d-11ea-83bb-a70a2fa7cd64.png">

I can't publish yet the example because I still didn't launched the application and I am not totally sure it's working at 100%, but this solution is based on how I have structure the project.

**Comment by tobkle** [comment]
Interesting. Copied your code and still don't get the idToken. Anything wrong with my Auth0 setup?
```
[ ready ] compiled successfully - ready on http://localhost:3000
Warning: You're using a string directly inside <Link>. This usage has been deprecated. Please add an <a> tag as child of <Link>
has idToken gip false
idToken value: null
has idToken gip false
idToken value: null
has idToken gip false
idToken value: null
has idToken gip false
idToken value: null
has idToken gip false
idToken value: null
has idToken gip false
idToken value: null
[ info ]  bundled successfully, waiting for typecheck results...
[ ready ] compiled successfully - ready on http://localhost:3000
[ event ] build page: /api/getToken
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
TypeError: Cannot destructure property `idToken` of 'undefined' or 'null'.
    at session (/Users/toby/Code/next-auth0/frontend/.next/server/static/development/pages/api/getToken.js:158:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.apiResolver (/Users/toby/Code/next-auth0/frontend/node_modules/next/dist/next-server/server/api-utils.js:42:9)
    at async DevServer.handleApiRequest (/Users/toby/Code/next-auth0/frontend/node_modules/next/dist/next-server/server/next-server.js:427:9)
    at async Object.fn (/Users/toby/Code/next-auth0/frontend/node_modules/next/dist/next-server/server/next-server.js:350:37)
    at async Router.execute (/Users/toby/Code/next-auth0/frontend/node_modules/next/dist/next-server/server/router.js:42:32)
    at async DevServer.run (/Users/toby/Code/next-auth0/frontend/node_modules/next/dist/next-server/server/next-server.js:468:29)
[ info ]  bundled successfully, waiting for typecheck results...
```
Then my Auth0 settings must be somewhere wrong and I don't understand the logic.

I did the following:
1. Created an Application within Auth0.
Used the domain, clientId and clientSecret from the Application in the env variables
2. Created an API with identifier 'inventhora.com/api/graphql' used RS256 for it.
3. Run it.

**Comment by balazsorban44** [comment]
I also experimented a bit, and looks like if I remove `Iron.seal` and `Iron.unseal` at: https://github.com/auth0/nextjs-auth0/blob/5db64aa053bd6fd1c03afeabbedbf9260c026519/src/session/cookie-store/index.ts#L33
and:
https://github.com/auth0/nextjs-auth0/blob/5db64aa053bd6fd1c03afeabbedbf9260c026519/src/session/cookie-store/index.ts#L73

I get the `idToken`! So my theory about a too large cookie seems to be the case, at least for me. I don't know how to solve the problem though, since I am pretty sure the `Iron.seal` and `Iron.unseal` methods are crucial for encryption...

**Comment by shansmith01** [comment]
Hey @Afsoon. Any chance you can share your repo. I am also working on a project with Hasura, Apollo and Auth0, with SSR. I am going nuts figuring out a good way to pass the idToken from the backend into the apolloClient headers

Thanks

**Comment by tobkle** [comment]
Still don't get any idToken. Tried a lot meanwhile. But it looks like there is no support. So I no longer consider Auth0 for my development.

**Comment by schwamic** [comment]
@tobkle maybe this can help you:

#### lib/auth0.js

```js
import { initAuth0 } from '@auth0/nextjs-auth0'

export default initAuth0({
  domain: process.env.AUTH0_DOMAIN,
  clientId: process.env.AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET,
  scope: process.env.AUTH0_SCOPE,
  redirectUri: process.env.REDIRECT_URI,
  postLogoutRedirectUri: process.env.POST_LOGOUT_REDIRECT_URI,
  audience: 'myaudience',
  session: {
    cookieSecret: process.env.SESSION_COOKIE_SECRET,
    cookieLifetime: process.env.SESSION_COOKIE_LIFETIME,
    storeIdToken: false,
    storeRefreshToken: false,
    storeAccessToken: true,
  },
})
```

#### apolloClient.js

```js
import { ApolloClient } from 'apollo-client'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { HttpLink } from 'apollo-link-http'
import { setContext } from 'apollo-link-context'
import { onError } from 'apollo-link-error'
import fetch from 'isomorphic-unfetch'

let accessToken = null

const requestAccessToken = async () => {
  if (!!accessToken) return

  const res = await fetch('/api/session')
  if (res.ok) {
    const json = await res.json()
    accessToken = json.accessToken
  } else {
    accessToken = 'public'
  }
}

// return the headers to the context so httpLink can read them
const authLink = setContext(async (req, { headers }) => {
  await requestAccessToken()
  if (!accessToken || accessToken === 'public') {
    return {
      headers,
    }
  } else {
    return {
      headers: {
        ...headers,
        Authorization: `Bearer ${accessToken}`,
      },
    }
  }
})

// remove cached token on 401 from the server
const resetTokenLink = onError(({ networkError }) => {
  if (networkError && networkError.name === 'ServerError' && networkError.statusCode === 401) {
    accessToken = null
  }
})

const httpLink = new HttpLink({
  uri: process.env.API_URL,
  credentials: 'include',
  fetch,
})

export default function createApolloClient(initialState, ctx) {
  // The `ctx` (NextPageContext) will only be present on the server.
  // use it to extract auth headers (ctx.req) or similar.
  accessToken = null
  return new ApolloClient({
    ssrMode: Boolean(ctx),
    link: authLink.concat(resetTokenLink).concat(httpLink),
    cache: new InMemoryCache().restore(initialState),
  })
}
```

#### api/session.js

```js
import auth0 from '../../lib/auth0'

export default async function session(req, res) {
  try {
    const s = await auth0.getSession(req)

    if (s) res.send(s)
    res.status(500).end(s)
  } catch (error) {
    res.status(error.status || 500).end(error.message)
  }
}
```

#### Steps

##### Auth0

- Generate Auth0 Regular Web App (Next.js)
- Generate Auth0 API with audience ('myaudience')
- Add rules to set tokens and sync with hasura backend; (docs)[https://hasura.io/docs/1.0/graphql/manual/guides/integrations/auth0-jwt.html#test-auth0]

##### Hasura

- Add `HASURA_GRAPHQL_JWT_SECRET`; [config-generator](https://hasura.io/jwt-config)
- Add `HASURA_GRAPHQL_UNAUTHORIZED_ROLE` (e.v. role 'anonymous')
- Add `HASURA_GRAPHQL_ADMIN_SECRET`

##### Next.js App

- Install [Auth0](https://github.com/zeit/next.js/tree/master/examples/auth0) and enable `storeAccessToken` and add `audience` from Auth0-API ([without audience no jwt token](https://github.com/auth0/nextjs-auth0#calling-an-api)) (e.g.lib/auth0.js)
- Install [Apollo](https://github.com/zeit/next.js/tree/master/examples/with-apollo) to Next.js
- Add `Link` context with jwt (e.g. apolloClient.js)
- Add `api/session` route to get session for client and server (e.g. api/session.js)

Hope that's it :-)

**Comment by devpascoe** [comment]
Interesting. I could only get this to work by:
storeIdToken: false,
storeRefreshToken: true,
storeAccessToken: true,

if i set storeIdToken to true then cookie isnt set.

**Comment by jblewnormal** [comment]
@schwamic Your solution worked for me, thank you so much!

Creating a new `/api/auth/session.js` route and using `import { getSession } from '@auth0/nextjs-auth0'` within it allowed me to get the `requestAccessToken()` method you defined working within the components that needed my session.

Thanks again!
