### ISSUE TITLE
App hosted on zeit/now is being redirected to a 502 BAD_GATEWAY error after user login

### ISSUE THREAD

**Issue by fortunee** [auth0/nextjs-auth0#70]
### Description
The page is redirected to a 502 BAD_GATEWAY error after user login, it happens intermittently to specific users.

### Reproduction
- The user navigates to `/login`
- Auth0 default login page is loaded
- User enters credentials
- User is redirected to 502 error

### Code sample to reproduce the issue
```js
// pages/api/login
import { NextApiRequest, NextApiResponse } from ‘next’
import { auth0 } from '~/src/api/auth'

export default async function login(req: NextApiRequest, res: NextApiResponse) {
  try {
    await auth0.handleLogin(req, res, {})
  } catch (error) {
    console.error(error)
    res.status(error.status || 400).end(error.message)
  }
}
```
### Screenshots
<img width="1792" alt="Screen Shot 2020-01-21 at 2 01 04 PM" src="https://user-images.githubusercontent.com/12124618/72882200-7b889900-3d02-11ea-9842-7979d5627557.png">

### Environment
[zeit/now](https://zeit.co/home)

- **Version of this library used:** 0.7.0
- **Other relevant versions (language, server software, OS, browser):** Javascript, Linux, Chrome

**Comment by jimwheaton** [comment]
We had a similar issue on our project (502s) that was related to the `a0:session` cookie size. Depending on what you're storing in the cookie (eg. access_token, id_token, refresh_token), you'll hit a size limit. For us, this was causing the 502s. We dialed back what were were storing in the cookie and it resolved the issue. Hope that helps you out.

**Comment by Widcket** [comment]
Hi all, can you please check if this issue still happens in the new [v1.0.0-beta.0](https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0) release? We've completely reworked the session code, and now support cookie stitching.
