### ISSUE TITLE
Problem with Next.js/Auth0 behind HTTP Basic Auth?

### ISSUE THREAD

**Issue by j-mattsson** [auth0/nextjs-auth0#702]
I'm running a Next.js-application with auth0 using your library. The application is on a public server behind nginx. Because we are not ready for production we have configured nginx to protect the website with HTTP Basic Auth. However, after the initial HTTP Basic Auth dialog (expected) I am greeted with another (unexpected) HTTP Basic Auth dialog while the website loads requiring me to login in both dialogs.

I'm not sure if your library is the culprit but I did notice a 401 request to "/api/auth/me" when loading the website, could this be the problem? If so, is it possible to prevent this request?

(Also this problem only occurs on Chrome, not Firefox)

**Comment by adamjmcgrath** [comment]
Hi @mjunix - thanks for raising this

> I'm not sure if your library is the culprit but I did notice a 401 request to "/api/auth/me" when loading the website, could this be the problem?
This SDK will never prompt you with an HTTP Basic Auth dialog, both are coming from your nginx configuration - if it's prompting you twice it'll be in issue with that.

> If so, is it possible to prevent this request?
This request is issued from the `UserProvider` - you can only avoid this request by not using the `UserProvider`. The request is used to populate the user state in the `useUser` hook

**Comment by mjunix** [comment]
Thanks, I guess I need to take another look at our nginx-configuration.
