### ISSUE TITLE
Unknown or invalid refresh token when session expires.

### ISSUE THREAD

**Issue by muradsofi** [auth0/nextjs-auth0#704]
- **Version of this library used: 1.9.0
- **Version of the platform or framework used, if applicable: 10.2.3

Hello, I'm using **_@auth0/nextjs-auth0_**.  and try to enable refresh token rotation. But I have an issue with the refresh token.  When I decrease session time to 100 seconds and after 100 seconds have passed I assume I will request for getting a new access token with the refresh token and will continue using the application. But when 100 seconds have passed I get the error  'Unknown or invalid refresh token.'

Is this bug or did I do something wrong? If I understand it correctly every time when I request I need to get a new refresh token and access token. And I assume SDK not update refresh token and because that I get this error

**Comment by Widcket** [comment]
Hi @muradsofi, thanks for raising this.

Are you adding the `offline_access` scope? Without it, you won't get a refresh token.
See https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#access-an-external-api-from-an-api-route

<img width="679" alt="Screen Shot 2022-06-01 at 23 05 05" src="https://user-images.githubusercontent.com/5055789/171532463-d839b534-df1e-4189-9489-954ad367c54a.png">

**Comment by muradsofi** [comment]
Hey, @Widcket. Yeah sure I not directly adding offline_access scope but instead of using ENV variables. 

AUTH0_SCOPE=openid email profile offline_access

**Comment by Widcket** [comment]
@muradsofi it's not possible to get a refresh token for the Management API. See https://auth0.com/docs/secure/tokens/access-tokens/management-api-access-tokens#token-lifetime

**Comment by Widcket** [comment]
Note that you can use [node-auth0](https://github.com/auth0/node-auth0) to interact with the Management API.

**Comment by Widcket** [comment]
Seems like the above answered your question, so I'll close this issue. Please feel free to ping if you'd prefer to reopen.

**Comment by muradsofi** [comment]
- @auth0/nextjs-auth0
- 1.9.0
- NextJS 10.2.3 


Hello again, I changed management api but when I try to use **refresh token** in @auth0/nextjs-auth0 I still see weird behaviors. 

I already added **offline_access** to **AUTH0_SCOPE** *(AUTH0_SCOPE=openid email profile offline_access)* in environment file

When I check my **session** I see a **refresh token** inside the **session** but when my **access token** expires I don't get a new **access token** automatically. For getting a new **access token** do I need to manually call something?

If for getting a new access token I need to call  **getAccessToken** method. It also works a little bit weirdly. When I call **getAccessToken** manually it returns a new **access token** but not an update **session**.
