### ISSUE TITLE
Struggling to customize the login/signup pages

### ISSUE THREAD

**Issue by semyou** [auth0/nextjs-auth0#72]
### Description

Is it possible to customize the forms and use my hosted ones on my own site with this module? Or do I need to install also nextjs-spa-js?
I noticed also that language setting from the form handleLogin doesn't work with the classic experience. Is this normal and expected? But it works on the new experience with ui_locales. However, the new experience is very limited and you cannot even add extra fields to the sign up form. Any guidance is more than welcome. Thanks

**Comment by remiroyc** [comment]
nextjs-auth0 use auth0 universal login. When the user signin, your app redirect the user to Auth0. After the transaction is completed Auth0 will redirect the user back to your application. 

By default auth0 provides default look and feel for your universal login pages but you can override it using custom HTML. 

Go to your ```auth0 dashboard > Universal Login > Login```


![Capture d’écran 2020-04-25 à 21 05 54](https://user-images.githubusercontent.com/11146088/80288478-8fe09580-8738-11ea-9004-5a34f2f03874.png)

**Comment by Widcket** [comment]
Thanks @remiroyc for the guidance.
