### ISSUE TITLE
How do you customise the error handler for the useUser hook ?

### ISSUE THREAD

**Issue by Jonashr** [auth0/nextjs-auth0#720]
When running lighthouse we get this error cause we use the useUser hook:

**Browser errors were logged to the console**

The page work whether the user is logged in or not so we would like to rewrite the error handler to instead return a different type of response. As it is a new page and reliant on SEO we would like to improve the lighthouse scores in whatever way is possible.

I read the section about **Error Handling and Security** in the documentation, and we understand that logging these errors to the console is the default and intended behaviour, but it is possible to rewrite the error handler.  But we are still not quite clear how to go about rewriting the error handler for the useUser hook. Do you have any examples how you would do it ? Thank you.

**Comment by adamjmcgrath** [comment]
Hi @Jonashr - thanks for raising this

This SDK doesn't log any errors to the console, could you share what is being logged exactly?

**Comment by Jonashr** [comment]
@adamjmcgrath 

Thanks, I think maybe my wording wasn't the best so let me try to be a bit more specific.

We now have **two types** of 401 errors logged in console:

The first is from _Api Routes_ that uses **withApiAuthRequired**
<img width="654" alt="Screenshot 2022-06-08 at 9 22 01" src="https://user-images.githubusercontent.com/8199791/172505615-a1ce1cac-256e-4c4d-af6a-c8629e0c561f.png">

This behaviour is like expected. To avoid logging these type of errors in console it seems the only way is to remove the withApiAuthRequired and instead return a different message if the user isn't logged in. This is used for instance to render a login menu with the users selected profile image and profile name. Even though it is conditionally rendered, meaning if the **useUser** hooks returns anything else than undefined, the code will still execute even when the user is not logged in    
and log a 401 error to the console. So here we are considering just ditching the **withApiAuthRequired**, although this feels less than ideal. Even though we do proper validation on the backend, it is still nice to have this extra layer of security on the frontend when the user is not logged in.

The other type of 401 error that I am asking about is the one coming from the **/api/auth/me** endpoint, and how you would go about rewriting the error handler for this. Typically it looks like this:

<img width="641" alt="Screenshot 2022-06-08 at 9 22 16" src="https://user-images.githubusercontent.com/8199791/172506398-ca1eb040-8b88-4251-8cbd-23161009ef7e.png">

This is pretty much logged on all the pages because the **useUser** hook is used in a NavBar component  to render extra stuff like profile image and name if the user is logged in. Since the user is not logged in at this point, useUser returns undefined and this error message is logged in the console. My initial guess would be that we have to rewrite the **handleProfile**  method somehow.

**Comment by adamjmcgrath** [comment]
Hi @Jonashr - thanks for sharing that info 

> So here we are considering just ditching the withApiAuthRequired, although this feels less than ideal. Even though we do proper validation on the backend, it is still nice to have this extra layer of security on the frontend when the user is not logged in.

`withApiAuthRequired` protects the backend api endpoints, so you don't want to ditch this.

The `useUser` hook is making the request to `/api/user` to populate the `user` property. The `/api/user` API returns a JSON representation of the user if you're logged in or a 401 if you're not and the hook populates the user based on this API.

You can customise this behaviour, but you'd need to modify your server code by writing a custom [handleProfile](https://auth0.github.io/nextjs-auth0/modules/handlers_profile.html) that doesn't return a status of 401. See https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#customize-handlers-behavior

And you'd need to write some client side code in the custom fetcher passed to [UserProvider](https://auth0.github.io/nextjs-auth0/modules/frontend_use_user.html#userproviderprops). That returns undefined if it get's an empty 200 response from the custom `handleProfile` (it [currently returns undefined if it gets a 401](https://github.com/auth0/nextjs-auth0/blob/main/src/frontend/use-user.tsx#L176))

**Comment by adamjmcgrath** [comment]
I think the above answers your question, feel free to ping me if you want to reopen
