### ISSUE TITLE
Setting NEXT_PUBLIC_AUTH0_LOGIN does not overwrite the default of /api/auth/me

### ISSUE THREAD

**Issue by lnrdgmz** [auth0/nextjs-auth0#723]
### Describe the problem

I am trying to use nextjs-auth0 with a custom api path, `/api/my_auth/[endpoint]` instead of `/api/auth/[endpoint]`. I am able to successfully set the callback url (`AUTH0_CALLBACK='/api/my_auth/callback'`) in the `.env.local` file, but setting `NEXT_PUBLIC_AUTH0_LOGIN='/api/my_auth/me'` has no effect. The front-end continues making requests to `/api/auth/me`, which return a 404.

### What was the expected behavior?

The front-end should make successful requests to `/api/my_auth/me`.

### Reproduction

1. Clone this fork of the sample app: https://github.com/lnrdgmz/auth0-nextjs-samples
Relevant changes are here: https://github.com/lnrdgmz/auth0-nextjs-samples/commit/c45c3c2cfee34a1962e478f6aa188cf44f94cee5

2. Copy `.env.local.example` and fill in the necessary values.

### Environment

I'm just using the sample app.

- **Version of this library used:**
1.9.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by Widcket** [comment]
Hi @lnrdgmz, thanks for raising this.

`NEXT_PUBLIC_AUTH0_LOGIN` is for `withPageAuthRequired`. For the profile endpoint, set `NEXT_PUBLIC_AUTH0_PROFILE` as well.

<img width="1036" alt="Screen Shot 2022-06-07 at 21 31 04" src="https://user-images.githubusercontent.com/5055789/172506523-cf3dc437-2ff5-4eba-922c-55da2530f569.png">

See https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#use-custom-auth-urls

**Comment by lnrdgmz** [comment]
@Widcket Thank you for the clarification!

I was using the docs [here](https://auth0.github.io/nextjs-auth0/modules/config.html), which lists `NEXT_PUBLIC_AUTH0_LOGIN`, not `NEXT_PUBLIC_AUTH0_PROFILE`. When skimming the code, I overlooked the difference. Maybe `NEXT_PUBLIC_AUTH0_PROFILE` should be added to that doc?
