### ISSUE TITLE
TypeError: "secret" is required

### ISSUE THREAD

**Issue by RennSter20** [auth0/nextjs-auth0#737]
I have set up basic settings for auth0 and I get this error

TypeError: "secret" is required
  3 | 
  4 | 
> 5 | export default handleAuth();
    |                         ^

This is my .env.local

MONGO_URI="mongodb+srv://xxxxx@cx.otxy99.mongodb.net/?retryWrites=true&w=majority"

AUTH0_SECRET='REDACTED'
AUTH0_BASE_URL='http://localhost:3000'
AUTH0_ISSUER_BASE_URL='https://dev-4phx77yjn.us.auth0.com'
AUTH0_CLIENT_ID='et7CDWQeI6yxV3GpjWxYqArdpW6fhD9Cge'
AUTH0_CLIENT_SECRET='REDACTED'

**Comment by adamjmcgrath** [comment]
Hi @RennSter20 - thanks for raising this

As long as your `AUTH0_SECRET` environment variable is defined, you wont get a `"secret" is required` error when `handleAuth()` is executed. So I can only assume that your environment variables aren't being loaded.

You can confirm this by printing out the  `AUTH0_SECRET` environment variable before line 3 in `(api)\pages\api\auth\[auth0].ts` eg 

```
import { handleAuth } from '@auth0/nextjs-auth0';

console.log('AUTH0_SECRET = ', process.env.AUTH0_SECRET)

export default handleAuth();
```

**Comment by Widcket** [comment]
Closing as the above seems to answer the question. Please feel free to ping if you'd prefer to reopen.
