### ISSUE TITLE
A way to sign in without needing to go to the universal login page

### ISSUE THREAD

**Issue by corysimmons** [auth0/nextjs-auth0#739]
### Describe the problem you'd like to have solved

Although it's easier to offer a lib that sticks to the universal signin page, a better UX is to simply allow users to click a button to trigger a popup or redirect directly to the OAuth page.

### Describe the ideal solution

next-auth does this like so:

```tsx
import {signIn} from 'next-auth/react'

export default function LoginBtn() {
  return <button onClick={() => signIn('github')}>Login</button>
}
```

...which will immediately take you to the Github signin page then redirects to whatever URL you specified in your custom Github OAuth application.

## Alternatives and current work-arounds

I don't think there are any aside from bespoking auth. Maybe I am overlooking how to do this with `nextjs-auth0`.

### Additional information, if any

I can imagine tons of developers want this feature. I'm aware it might be more work vs simply offering the universal sign-in page, but it's currently the only reason I'm messing around with next-auth instead of just reaching for this library every time.

**Comment by Widcket** [comment]
Hi @corysimmons, thanks for raising this.
It is possible to go straight to the provider's page by passing the `connection` parameter to the login handler. The value should be the name of the connection as shown in the Dashboard page "Social Connections" ("Authentication" > "Social").

For example:
```js
export default async function login(req, res) {
  try {
    await auth0.handleLogin(req, res, {
      authorizationParams: {
        connection: 'google-oauth2'
      }
    });
  } catch (error: any) {
    console.error(error);
  }
}
```

**Comment by corysimmons** [comment]
Awesome I'll be sure to check it out and re-open if I'm still having problems! Thank you for the quick response!

**Comment by phamdongtruong99** [comment]
i want to custom signup action and something action. please suggest for me docs and solution. thank for best <3
