### ISSUE TITLE
Add Refresh Token Example

### ISSUE THREAD

**Issue by dizzyn** [auth0/nextjs-auth0#74]
Please add simple example of token renewal or describe whole case in the documentation the same way the login/logout/me... are described.

Thank You :)

**Comment by sandrinodimattia** [comment]
You shouldn't have to care about a refresh token since the library handles it for you, eg on this line of code you'll receive a new access token if your existing one is expired:

https://github.com/auth0/nextjs-auth0/blob/master/examples/api-call-example/pages/api/shows.js#L9

**Comment by sandrinodimattia** [comment]
Closing this one due to inactivity, feel free to re-open if you need more help.

**Comment by mattjennings** [comment]
Could we add an option to `tokenCache.getAccessToken()` that allows a force refresh? I've found myself in a scenario where I'd like to update the claims on the token but it seems my only option is to wait until the token expires.
