### ISSUE TITLE
Callback to nginx results in `state missing from the response` or `only absolute urls supported`

### ISSUE THREAD

**Issue by thugzook** [auth0/nextjs-auth0#744]
### Description

Running a next.js/express app with nginx handling reverse proxy causes error: 'state missing from the response'.

### Reproduction

[...auth0].js
```javascript
const afterCallback = async (req, res, session, state) => {
    /* Create user in DB with accessToken in header */
    return session
}

export default handleAuth({
    async login(req, res) {
        try {
            await handleLogin(req, res, {
                authorizationParams: {
                  audience: process.env.NEXT_PUBLIC_AUTH0_AUDIENCE,
                },
              });
        } catch (error) {
            res.status(error.status || 400).end(error.message);
        }
    },
    async callback(req, res) {
        try {
            await handleCallback(req, res, { afterCallback })
        } catch (error) {
            res.status(error.status || 500).end(error.message)
        }
    }
}); 
```

nginx conf file
```
location /_next/webpack-hmr {
    proxy_pass http://localhost:3000/_next/webpack-hmr;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
	}
  location /api/auth/login {
	proxy_pass http://127.0.0.1:3000/api/auth/login;
  }
  
  location /api/auth/logout {
	proxy_pass http://127.0.0.1:3000/api/auth/logout;
  }
  location ~* ^/api/auth/callback/(.*)$ (
	proxy_pass http://127.0.0.1:3000/api/auth/callback/$1;
  )
```

index
```javascript
<Button onClick={() => router.push('/api/auth/login')}>
   Log in
</Button>
```

Works in local 'next dev' but not on production builds. On local production the error is 'only absolute urls supported'. On AWS w/ nginx, the error is 'state missing'

### Environment

> Please provide the following:

- @auth0/nextjs-auth0 : 1.9.0
- npm: 8.11.0
- Node: 16.15.1

**Comment by thugzook** [comment]
I've tried adding `returnTo` in `handleLogin`. No dice in local production.

**Comment by adamjmcgrath** [comment]
Hi @thugzook 

`state missing from the response` means that you are not providing the `state` query parameter in the callback url, the SDK expects the callback url to have the `state` and `code` parameters: `/api/auth/callback?code={CODE}&state={STATE}` - I suspect the issue is in your reverse proxy configuration

`only absolute urls supported` means that you are trying to call `fetch` with a relative url, so you should look for where you're calling fetch and make sure it's with an absolute url.

**Comment by thugzook** [comment]
> I suspect the issue is in your reverse proxy configuration

I believe so, too. I will report back when I get to that.

> only absolute urls supported means that you are trying to call fetch with a relative url

Interesting. I get this error when I'm redirected to /api/auth/callback from /api/auth/login. As far as I'm aware, I never define the callback URI anywhere.

**Comment by thugzook** [comment]
I've identified my problem with `only absolute urls supported` in this callback structure from `handleAuth()`:

```javascript
export default handleAuth({
    async login(req, res) {
        ...
    },
    async callback(req, res) {
        try {
            await handleCallback(req, res, { afterCallback })
        } catch (error) {
            res.status(error.status || 500).end(error.message)
        }
    }
});

const afterCallback = async (req, res, session, state) => {
    const client = new ApolloClient({
        cache: new InMemoryCache(),
        link: from([httpLink]),
      });
    await client.mutate({
        mutation: CREATE_USER,
        variables: {
            ...
        },
        context: {
            headers: {
                authorization: "Bearer " + session.accessToken
            }
        }
    })
    return session
}

=====
if (process.env.NODE_ENV === "production") {
    httpLink = createHttpLink({ uri: "/graphql" });
}
```

Currently working on error with state.

**Comment by thugzook** [comment]
> `state missing from the response` means that you are not providing the `state` query parameter in the callback url, the SDK expects the callback url to have the `state` and `code` parameters: `/api/auth/callback?code={CODE}&state={STATE}` - I suspect the issue is in your reverse proxy configuration

location ~* ^/api/auth/callback/(.*) (
	proxy_pass http://127.0.0.1:3000/api/auth/callback/$1$is_args$args;
  )

**Comment by thugzook** [comment]
> `state missing from the response` means that you are not providing the `state` query parameter in the callback url, the SDK expects the callback url to have the `state` and `code` parameters: `/api/auth/callback?code={CODE}&state={STATE}` - I suspect the issue is in your reverse proxy configuration

You were right. I was terminating the callback early. Here's my updated reverse proxy:

```
  location ~* ^/api/auth/callback/(.*) {
        proxy_pass http://127.0.0.1:3000$request_uri;
  }
```
