### ISSUE TITLE
CORS Errors on logout

### ISSUE THREAD

**Issue by smparekh** [auth0/nextjs-auth0#757]
### Describe the problem
When logging out a user, CORS errors prevent redirect.

Login redirection works as intended...

Errors in console:
```
Application error: a client-side exception has occurred (see the browser console for more information).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://auth.dev.mydomain.com/v2/logout?returnTo=https%3A%2F%2Ftest-app.mydomain.com&client_id=XXXXXX. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 404.

22:24:10.987 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://auth.dev.mydomain.com/v2/logout?returnTo=https%3A%2F%2Ftest-app.mydomain.com&client_id=XXXXXX. (Reason: CORS request did not succeed). Status code: (null).
```

I have double checked all applicable settings for my tenant:
- [x] Allowed Logout URLs contains https://test-app.mydomain.com
- [x] Allowed Web Origins contains https://test-app.mydomain.com
- [x] Allowed Callback URLs containts https://test-app.mydomain.com/api/auth/callback

### What was the expected behavior?
App should redirect to https://test-app.mydomain.com

### Environment

- **Version of this library used:**
  - Auth0 NextJS version: ^1.9.1
- **Which framework are you using, if applicable:**
  - Next.JS version: ^12.2.0
- **Any other relevant information you think would be useful:**
  - Component:
  ```jsx
  <Link href="/api/auth/logout" passHref>
      <a>Logout</a>
  </Link>
  ```
  - I have grafana setup via the same tenant and application where login/logout works as intended.

**Comment by smparekh** [comment]
Thanks for the assist, I have reverted to using a bare link.

**Comment by schnucks-rrphillips** [comment]
That will fix basic links but the same thing happens on protected pages that use withPageAuthRequired. When the redirect occurs we see the CORS error in Chome. In FF and Safari the page does not load and the user never makes it to the Auth0 login screen. Note that this does not occur when running the app on local. Only when deployed to an environment in production mode.

**Comment by cwk29** [comment]
@schnucks-rrphillips I have been battling this issue with Next 13 and nextjs-auth0 2.4.0.  Any solutions for this?

**Comment by mawaisismail** [comment]
@cwk29 / @schnucks-rrphillips - also hitting the same problem with NextJS 14 and @auth0/nextjs-auth0 3.5.0. Is anyone working on fixing this?

**Comment by tmcentee** [comment]
I'm running into the same issue as @schnucks-rrphillips and feel like I'm out of options at this point. 

Using an `a` tag prevents the pre-fetching CORS error, but when behind a page that has `withPageAuthRequired` the actual redirect from the Auth0 lib to my Auth0 still has a CORS error.
