### ISSUE TITLE
React Native compatibility

### ISSUE THREAD

**Issue by raphaelbadia** [auth0/nextjs-auth0#768]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'd love to use this plugin, however I also intend to consume the api routes from my react-native app.

As react-native apps don't have cookies, I have no idea on how to use withApiAuthRequired()... 

### Describe the ideal solution

I think that it would be great to provide an extra wrapper accepting a jwt header instead of a session cookie, but I have no idea if it's doable or not.

### Alternatives and current workarounds

I didn't find any alternative yet

**Comment by adamjmcgrath** [comment]
Hi @raphaelbadia - have a look at https://github.com/auth0/nextjs-auth0/issues/435#issuecomment-875733573 as an answer to your question

**Comment by adamjmcgrath** [comment]
Closing as answered, feel free to ping me if you want to reopen
