### ISSUE TITLE
TypeError: "secret" is required

### ISSUE THREAD

**Issue by arrbrk1** [auth0/nextjs-auth0#770]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have my Auth0 Secret environment variable as "REACT_APP_AUTH0_SECRET"

I've tried logging it and it's showing, but I'm still getting this error:

![image](https://user-images.githubusercontent.com/25717193/181013061-700e0640-6dc8-474d-b84f-ea230d53c038.png)

I have this file (auth0.ts) in my ```lib``` directory

```ts
import { initAuth0 } from "@auth0/nextjs-auth0";

export default initAuth0({
  secret: process.env.REACT_APP_AUTH0_SECRET,
  issuerBaseURL: process.env.REACT_APP_AUTH0_ISSUER_BASE_URL,
  baseURL: process.env.REACT_APP_AUTH0_BASE_URL,
  clientID: process.env.REACT_APP_AUTH0_CLIENT_ID,
  clientSecret: process.env.REACT_APP_AUTH0_CLIENT_SECRET,
});
```

and I'm importing it in ```/api/auth/[...auth0.ts]``` this way:

```ts
import auth0 from "../../../lib/auth0";

//the log I mentioned that's working:
console.log("auth0 secret:", process.env.REACT_APP_AUTH0_SECRET);

export default auth0.handleAuth();
```

![image](https://user-images.githubusercontent.com/25717193/181012444-432445ad-81e2-4db2-9944-ffbbdafd4fcc.png)

### Reproduction

1: Create an auth0.ts file:

```ts
import { initAuth0 } from "@auth0/nextjs-auth0";

export default initAuth0({
  secret: process.env.REACT_APP_AUTH0_SECRET,
  issuerBaseURL: process.env.REACT_APP_AUTH0_ISSUER_BASE_URL,
  baseURL: process.env.REACT_APP_AUTH0_BASE_URL,
  clientID: process.env.REACT_APP_AUTH0_CLIENT_ID,
  clientSecret: process.env.REACT_APP_AUTH0_CLIENT_SECRET,
});
```
2: Import it in /api/auth/[...auth0.ts]:
```ts
import auth0 from "../../../lib/auth0";

export default auth0.handleAuth();
```

### SDK version

1.9.0

### Next.js version

12.1.6

### Node.js version

16.15.0

**Comment by dianachiudev** [comment]
- Assuming that you are using a nextjs application, you shouldn't be using `REACT_APP_` as a prefix. But even if you were using the correct prefix for a nextjs frontend application e.g. `NEXT_PUBLIC_`, You don't want to expose the client secret to your frontend application either, **so omit all the prefixes before AUTH0.**

- Also, you don't necessarily need to use `initAuth0` because your AUTH0 environment variables will automatically be populated
