### ISSUE TITLE
Making Auth0Setting dynamic based on subdomains, etc.

### ISSUE THREAD

**Issue by xhiroga** [auth0/nextjs-auth0#778]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am implementing a multi-tenant application with different tenant settings for each subdomain.
With initAuth, it is not possible to set the Auth0Setting based on the value at request time.

### Describe the ideal solution

I would like to perform Auth0Setting based on a value determined at the time of request, such as a subdomain of a URL.

### Alternatives and current workarounds

Can be avoided by building NextJS for the number of tenants, but cannot build scalable multi-tenant applications

**Comment by adamjmcgrath** [comment]
Hi @xhiroga 

> With initAuth, it is not possible to set the Auth0Setting based on the value at request time.

There's nothing stopping you calling `initAuth` at request time, eg

```js
export default (req, res) {
  return initAuth0({ baseURL: somethingFromReq }).handleAuth(...)(req, res);
};
```

You should just memoize this call by tenant, so you're not creating a new instance on every request

**Comment by adamjmcgrath** [comment]
Closing as I think https://github.com/auth0/nextjs-auth0/issues/778#issuecomment-1222062824 answers your question
