### ISSUE TITLE
http://localhost:3000/api/auth/callback site can't be reached after login

### ISSUE THREAD

**Issue by AlwaysBuyCheap** [auth0/nextjs-auth0#786]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I created a next.js login project and followed the code sample including adding the callback_url and logout_url to the project settings but after successfully loggin in to the website and redirecting to http://localhost:3000/api/auth/callback?code=...
it generates an error of 'this site cant be reached'. But when I go back to localhost:3000 and click on log in, it successfully logs in.

Here is the errror:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/64446398/186400081-eb8b3cbc-e84f-4a69-8b85-65988afd2250.png">

And here the configuration settings:
![image](https://user-images.githubusercontent.com/64446398/186400167-b15778fe-c9ea-48f8-960e-03778aefb147.png)
![Drawing](https://user-images.githubusercontent.com/64446398/186402156-aacc3c88-12b9-417c-b35c-e5aac69e3ea3.png)

### Reproduction

Create a Next.js Regular Web App.
Downloading the sample code from the quick start
Go to the project folder:
a. run npm install @auth0/nextjs-auth0
b. run the openssl rand -hex 32 on the command line to generate a 32-bit long random value and add it to the AUTH0_SECRET field in the .env.local file
c. in the .env.local file, AUTH0_BASE_URL = http://localhost:3000/, instead of AUTH0_BASE_URL = ‘http://localhost:3000/’
c. run npm run dev

### SDK version

^1.9.0

### Next.js version

12.1.6

### Node.js version

v18.1.0

**Comment by younseoryu** [comment]
Got the same issue.

**Comment by AlwaysBuyCheap** [comment]
I solved it, the problem was that I had the project set up as a single page application insead of a regular web application, so I had to change it on the project settings.

**Comment by farhang103** [comment]
mine is still in regular web application but still it's not working
