### ISSUE TITLE
Role Based Authz - Best Practice

### ISSUE THREAD

**Issue by colin-riddell** [auth0/nextjs-auth0#799]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Trying to get RBAC to work in a nice way :)

### Describe the ideal solution

Hi folks!

I've been doing some work on how to implement role based access / Authz stuff that has a nice scalable developer experience and fits in with the library without too many weird hacks.

 Since there's not a `checkClaims` interface available like there is with the react library, I thought I'd try some stuff my self. I'm not sure what is nicer though and wanted to hear folks thoughts.

I imagined it would be good to be able to tag a page with, for example, a couple of roles to say only allow users with these roles to access the page. That could be with a HOC or statically against the component as I've seen done elsewhere.

## My HOC `withRoleAuthorization`:

I wrapped `withPageAuthRequired` to make a HOC where I provide the component, allowed roles and an error component.

```javascript
import { withPageAuthRequired } from '@auth0/nextjs-auth0';

const withRoleAuthorization = (
    Success,
    allowedRoles,
    Err,
    onError,
    onRedirecting,
    returnTo
  ) => {
    function hoc({ user }) {
      function arrContains(arr1, arr2) {
        return arr1.some(item => arr2.includes(item))
      }
  
      // check if the array of roles for a user contains any of the roles for the allowed array 
      // for the page.
      const usersRoles = user['http://mysite.com/roles']
      if (!arrContains(usersRoles, allowedRoles)){
        return (<Err />)
      }
      return (<Success user={user} />);
    }

    // https://auth0.github.io/nextjs-auth0/interfaces/frontend_with_page_auth_required.withpageauthrequiredoptions.html
    return withPageAuthRequired(hoc, {onError, onRedirecting, returnTo})
  }
export default withRoleAuthorization;  
```

## Approach 1 - HOC per page.
 
Basic concept is that you export the hoc'd version of your page component. Nuff said?:

```javascript
import ErrorMessage from '../components/ErrorMessage';
import withRoleAuthorization from '../utils/withRoleAuthorization';

function Profile({ user }) {
  // can use the user prop! sweet
  return (
    <>
     <p>stuff</>
    </>
  );
}

// use the HOC!!. giving it component and list of roles and an error component
export default withRoleAuthorization(Profile, ["role1", "role2"], () => (<ErrorMessage>Nope</ErrorMessage>))
```

## Approach 2 - HOC in `_app.js`

For this approach I'd replace the call to `withRoleAuthorization` with something like this:

```javascript
Profile.auth = { roles: ["role1", "role2"], error: () => (<ErrorMessage>Nope</ErrorMessage>) }
export default Profile;
```

Then in `_app.jsx`:
 Still using the `withRoleAuthorization` HOC, but instead of doing it per-page, do it in _app and only for components that have a "static" `auth` object. (The `Profile.auth =` above)

eg: (_app.jsx):

```javascript
export default function App({ Component, pageProps }) {

  const { roles, error } = Component.auth || {};
  const AuthedComp = withRoleAuthorization(Component, roles, error)
  const PublicComp = Component;
  return (
    <UserProvider>
      <Layout>
        {Component.auth ? (
          <>
            <AuthedComp {...pageProps} />
          </>
        ) : (
          <Component {...pageProps} />
        )}
      </Layout>
    </UserProvider>
  );
}
```

What's nicer here? Approach 1, or approach 2? I think I'm leaning into approach 2, as it covers a way of making some pages that are not wrapped with `withRoleAuthorization` at all?!

Cheers! 😁 

### Alternatives and current workarounds

No alternatives.. just asking about best practice + suggesting some ideas.

**Comment by adamjmcgrath** [comment]
Hey @colin-riddell - thanks for sharing this

Both approaches look good tbh, I think it would come down to personal preference. I can't give you any steer on which one is better from a best practice point of view, they both look fine.

**Comment by colin-riddell** [comment]
Would you like me to add this to a guide anywhere or anything @adamjmcgrath ?

**Comment by adamjmcgrath** [comment]
Thanks for the offer @colin-riddell - am happy to leave this issue as guidance for anyone searching for this use case
