### ISSUE TITLE
Allow custom Token Algorithms

### ISSUE THREAD

**Issue by acockerham** [auth0/nextjs-auth0#80]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved
I am trying to use this library to connect with a custom (enterprise) oidc Provider.  When I try to process autho0.handleCallback, I get the message "unexpected JWT alg received, expected RS256, got: ES256".  

My provider returns the token with ES256 algorithm.

From what I can find, @auth0/nextjs-auth0/utils/oidc-client.js call to new issuer.Client(...) does not allow us to provide our own values for id_token_signed_response_alg.  

openid-client defaults the id_token_signed_response_alg to RS256 so it is not possible to get the values to match when handlers/callback/callbackHandler is run.

### Describe the ideal solution
Solution would be to allow utils/oidc-client.js to take in the additional parameters from XXX in addition to the existing options that can be overridden.  id_token_signed_response_alg is the primary value I am requesting, but it would be nice to support all client metadata from https://github.com/panva/node-openid-client/blob/master/docs/README.md#client.  These options could be added to IAuth0Settings interface.

utils/oidc-client.js
```
    const issuer = await Issuer.discover(`https://${settings.domain}/`);
    client = new issuer.Client({
      client_id: settings.clientId,
      client_secret: settings.clientSecret,
      redirect_uris: [settings.redirectUri],
      response_types: ['code'],
      **id_token_signed_response_alg: settings.idTokenSignedResponseAlg,**
    });
```

## Alternatives and current work-arounds

I tried to access and modify the Client Object myself, but I don't know how to do that.
If I modify the package under node_modules it does let me return the token, but that is not a solution.

### Additional context

I noticed that there is at least one other issue people have had (#21) where the "unexpected JWT alg" message was seen.

**Comment by FadyMak** [comment]
Hi @acockerham 👋 I'm afraid this goes beyond the scope of this library as Auth0 only supports the issuance of tokens using `RS256` and `HS256`. You can, however, create an OIDC connection in Auth0 which would allow your users to authenticate through that IdP and have Auth0 handle the user management and securing any APIs you might have: https://auth0.com/docs/connections/enterprise/oidc
