### ISSUE TITLE
Add the option for the "appSession" cookie that is set to be a "Session Cookie" instead of having and expiring time set.

### ISSUE THREAD

**Issue by cgstaber** [auth0/nextjs-auth0#827]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

If the appSession cookie that is set was a "Session Cookie", when the browser window was closed, the cookie would not persist and the user would be signed out. 

### Describe the ideal solution

When the user closes the browser, they have to sign in again when they come back.

### Alternatives and current workarounds

I can set the time to something like 1 hour, but that's still not ideal - especially if they are on a public computer.

**Comment by cgstaber** [comment]
Ah thank you! I thought there had to be a way! I saw that option in the documentation, but read it as a cookie that never expires... 
Thanks a lot! :)

**Comment by adamjmcgrath** [comment]
> but read it as a cookie that never expires...

Yeah, it does read a bit like that... will make a note to improve that doc string
