### ISSUE TITLE
There is no method to change password

### ISSUE THREAD

**Issue by berkaygurbuz** [auth0/nextjs-auth0#829]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am looking at resetting the password API. Original API has a change password method but nextjs/auth0 does not. How can I use [this method](https://auth0.com/docs/api/authentication?_ga=2.262731017.443041451.1664219019-2117241438.1658306253&_gl=1*1ayvktn*rollup_ga*MjExNzI0MTQzOC4xNjU4MzA2MjUz*rollup_ga_F1G3E656YZ*MTY2NDIxOTAxOS45LjEuMTY2NDIxOTU0Ni41MC4wLjA.#change-password:~:text=No-,Change%20Password,-//%20Script%20uses%20auth0) on my own nextjs project. 

### Describe the ideal solution

Adding this method on nextjs/auth0

**Comment by adamjmcgrath** [comment]
Hi @berkaygurbuz - thanks for raising this

This is an OpenID Connect client and so changing password is out of scope for this SDK

Take a look at the docs for how to issue a request to send a password reset email https://auth0.com/docs/authenticate/database-connections/password-change
