### ISSUE TITLE
Using withPageAuthRequired for SSR pages causes 504 timeout on Vercel

### ISSUE THREAD

**Issue by dwilt** [auth0/nextjs-auth0#831]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I've just started up a brand new [NextJS project](https://github.com/dwilt/budgetme) via the `npx create-next-app` command and went through [the `nextjs-auth0` installation steps](https://github.com/auth0/nextjs-auth0#installation) (which worked like a charm - thank you!). When I went to use the `withPageAuthRequired` for _SSR_ pages, that's when I ran into trouble.

Locally, everything worked great (both with `npm run dev` and `npm run build; npm run start`):

![image](https://user-images.githubusercontent.com/1065539/192611406-982d3ccf-06f3-4b3f-868e-75725d546a86.png)

But when I pushed it up to Vercel, I would get a 504 warning from Vercel:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/1065539/192607231-a7c3afb0-b70f-4c99-bab4-6898ef71bb8b.png">

You can see it happening here: https://budgetme-lobx32xfe-dwilt.vercel.app/

This is all that shows in the Vercel logs for that deploy:

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/1065539/192608146-036e0bb6-6483-4a68-b67a-7e93b65b5d9c.png">

This is the commit that caused it: https://github.com/dwilt/budgetme/commit/da4f976489f12b970ef5527c331cea9b154f1249

When I convert the `withPageAuthRequired` from a check a server-side to a client-side check, the website works. The [commit prior](https://github.com/dwilt/budgetme/commit/e1aa422fb53bc2ae514adca9e495e9987a4303fa) is what is deployed to production and you can see logging in works fine there (feel free to try!): https://budgetme.us.

Interestingly enough though, on the deployment page in Vercel for that commit, the preview image of the deploy shows the Auth0 login screen as if the page is loading there so it's almost working 😂

<img width="980" alt="image" src="https://user-images.githubusercontent.com/1065539/192608507-63487e64-b86a-4175-b400-57c05187bfe4.png">

FWIW, I can still use the client-side verification but it would be nice to try out this server-side check to see if it's better for performance and if I can leverage it in anyway 🤷 

### Reproduction

Since this is really only happening on Vercel, this is a bit harder to have repro steps for. However, I've gone and made the [repo](https://github.com/dwilt/budgetme) public so you should be able to download it, setup a new Auth0 instance and then reproduce the issue yourselves. I'm also happy to invite you to my Auth0 org or whatever. This isn't a high-security project lol If you do go setup a new instance of a Vercel project, here are the env variables I'm using:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/1065539/192609242-dfcb8249-a8c7-4c46-b946-76256a562c44.png">

Let me know if I can help out more to give better reproduction help here.

### SDK version

1.9.1

### Next.js version

12.3.0

### Node.js version

16.17.0

**Comment by adamjmcgrath** [comment]
Hi @dwilt - thanks for raising this

I'm able to reproduce the 504, by removing `withPageAuthRequired` and just having an empty `getServerSideProps` - see https://github.com/dwilt/budgetme/commit/592295810d2832596c08941ca97f25fc67a95dcb

<img width="985" alt="image" src="https://user-images.githubusercontent.com/1299658/193094030-7fa4d707-0d2c-4939-90d7-3e3c9e51fa35.png">

I also noticed a discussion about `mui` and 504's here https://github.com/vercel/next.js/discussions/32686#discussioncomment-2001211 which looks related

**Comment by dwilt** [comment]
@adamjmcgrath thanks so much man. My bad, I should've dug more thoroughly on the Vercel side. This seems like it was [the issue that you referenced](https://github.com/vercel/next.js/discussions/32686#discussioncomment-2001211) and when I applied [one of the suggested fixes](https://github.com/vercel/next.js/discussions/32686#discussioncomment-3358485), it worked.
