### ISSUE TITLE
Option to disable page props augmentation when using `withPageAuthRequired`

### ISSUE THREAD

**Issue by joelzwarrington** [auth0/nextjs-auth0#836]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would like to have the option to expose `user` page prop to page components. I'd like to expose my own `user` page property with other metadata (not just the metadata coming from Auth0) but it's being overridden by the `withPageAuthRequired` helper.

### Describe the ideal solution

```js
export const getServerSideProps = withPageAuthRequired({
  augmentPagePropsWithUser: false
});
```

**Comment by adamjmcgrath** [comment]
Thanks for raising this @joelzwarrington - this has been fixed in v2 by https://github.com/auth0/nextjs-auth0/pull/800 - we hope to get a beta out in the next week or so

**Comment by joelzwarrington** [comment]
> Thanks for raising this @joelzwarrington - this has been fixed in v2 by https://github.com/auth0/nextjs-auth0/pull/800 - we hope to get a beta out in the next week or so

@adamjmcgrath, do you mind mentioning me on an issue/PR when that beta is available? Thank you 🙏

**Comment by adamjmcgrath** [comment]
Will update this thread 👍

**Comment by Widcket** [comment]
Hi @joelzwarrington, the beta release is out now: https://github.com/auth0/nextjs-auth0/releases/tag/v2.0.0-beta.0

**Comment by joelzwarrington** [comment]
> Hi @joelzwarrington, the beta release is out now: https://github.com/auth0/nextjs-auth0/releases/tag/v2.0.0-beta.0

Excellent, thank you 🥂🔥

**Comment by joelzwarrington** [comment]
@Widcket, I can't seem to access the v2 migration guide markdown file.

https://github.com/auth0/nextjs-auth0/blob/v2.0.0-beta.0/V2_MIGRATION_GUIDE.md

**Comment by adamjmcgrath** [comment]
Hi @joelzwarrington - thanks for raising this. Looks like the CI tagged the wrong branch, will get that fixed.

In the meantime you can use https://github.com/auth0/nextjs-auth0/blob/vNext/V2_MIGRATION_GUIDE.md

**Comment by adamjmcgrath** [comment]
https://github.com/auth0/nextjs-auth0/blob/v2.0.0-beta.0/V2_MIGRATION_GUIDE.md should be working now
