### ISSUE TITLE
withAuth missing call to child component's getInitialProps

### ISSUE THREAD

**Issue by tomclark** [auth0/nextjs-auth0#84]
I was working my way through the basic example in the repo and noticed that getInitialProps on my components wrapped with the withAuth HOC is never called. I added a call to it in the HOC, and it seems to have resolved the issue:

```javascript
    static async getInitialProps ({ req, res }) {
      const session = await auth0.getSession(req)
      if (!session || !session.user) {
        res.writeHead(302, {
          Location: '/api/login'
        })
        res.end()
        return
      }

      let componentProps = {}
      if (InnerComponent.getInitialProps) {
        componentProps = await InnerComponent.getInitialProps({ req, res })
      }

      return { user: session.user, ...componentProps }
    }
```

Are there any issues with calling the child method this way? Might it be appropriate to update the example to include this call if this is the right way to do it, or am I missing something about why this isn't there?

Thanks for your work on this handy plugin.

**Comment by aaron-fuleki** [comment]
@tomclark did you ever get an answer to this? I'm also seeing something weird, where `withAuth` seems to be firing `auth0.getSession()` on client renders, so it says `Error: The getSession method can only be used from the server side`, then it dies.

I thought `getInitialProps()` was guaranteed to be server-side only?

**Comment by tomclark** [comment]
No update to my question, unfortunately, and I'm afraid it rather fell off my radar.

I don't know whether they're new functions since I last looked at it (I don't think they can be, but I don't remember them from the docs), but there appear to be two other functions to do with server-side functionality: getStaticProps, and getServerSideProps. See the "recommended" notice here: https://nextjs.org/docs/api-reference/data-fetching/getInitialProps

Sorry I can't offer more. I will come back to this, and I'll be checking out those functions when I do. I'd certainly be interested in hearing back if you find out any more.

**Comment by nodabladam** [comment]
@aaron-fuleki  getInitialProps is both server and client...

"For the initial page load, getInitialProps will run on the server only. getInitialProps will then run on the client when navigating to a different route"
~ https://nextjs.org/docs/api-reference/data-fetching/getInitialProps

**Comment by aaron-fuleki** [comment]
Yeah, those are new to 9.4, I think. The bummer with `getServerSideProps` is that it's [only allowed in a page](https://nextjs.org/docs/basic-features/data-fetching#only-allowed-in-a-page-2).

Assuming that Next's API around this stuff has stabilized a bit (hah!), I'd love to see some official examples of how to handle Auth0 at the app level, rather than having to remember/enforce it on pages. There are lots of use cases where an entire app needs AAA enforcement, or entire path branches.

**Comment by Widcket** [comment]
Hi everyone, with the new [v1.0.0-beta.0](https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0) release you can protect both server-side (with `getServerSideProps`) and client-side rendered pages by using `withPageAuthRequired`. The server-side rendered pages will get a `user` prop with the user profile. `withPageAuthRequired` will redirect to the login page if not authenticated.
Please check out [the examples](https://github.com/auth0/nextjs-auth0/blob/beta/EXAMPLES.md#protecting-a-server-side-rendered-ssr-page) for more details. Note that the beta supports only Next.js 10+, though.
@aaron-fuleki I'm afraid that's not possible with Next.js yet.
