### ISSUE TITLE
Modify session in getServerSideProps with getAccessToken 

### ISSUE THREAD

**Issue by muradsofi** [auth0/nextjs-auth0#841]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When I try to modify the session in getServerSideProps it works fine.  

```
export const getServerSideProps = withPageAuthRequired({
  returnTo: '/',
  async getServerSideProps(ctx) {
    const session = getSession(ctx.req, ctx.res);
    if (session) {
      session.test = 'Hello World';
    }
    return { props: {} };
  },
});

```

But when I want to get a new access token via `getAccessToken` function and modify the session with `afterRefresh` method it does not work. 

```
 export const getServerSideProps = withPageAuthRequired({
  returnTo: '/',
  async getServerSideProps(ctx) {
    await getAccessToken(ctx.req, ctx.res, {
      afterRefresh: async (_req, _res, session) => {
        session.test = 'Hello World';
        return session;
      },
    });
    return { props: {} };
  },
});
```

And when I check my session looks like the session is not updated. Is it a bug or expected behavior? 

If it's not a bug how I must update my session with `afterRefresh` method? And I didn't find any example for this case 

### Reproduction

```
 export const getServerSideProps = withPageAuthRequired({
  returnTo: '/',
  async getServerSideProps(ctx) {
    await getAccessToken(ctx.req, ctx.res, {
      afterRefresh: async (_req, _res, session) => {
        session.test = 'Hello World';
        return session;
      },
    });
    return { props: {} };
  },
});
```

### SDK version

1.9.0

### Next.js version

10.2.3

### Node.js version

v16.13.0

**Comment by adamjmcgrath** [comment]
HI @muradsofi - thanks for raising this

`afterRefresh` is only called when the access token is refreshed (using the refresh grant), and that only happens if the token is expired or you pass `refetch: true` to force the token to refresh.

**Comment by muradsofi** [comment]
@adamjmcgrath Thanks for answer :) 

Yeah I know when `afterRefresh` executes :) In my case **access token expired** and afterRefresh function executes fine. The problem is session modification does not work and somehow it's not update my session :/

**Comment by adamjmcgrath** [comment]
Hi @muradsofi - I'm not able to reproduce your issue on the example app https://github.com/auth0/nextjs-auth0/compare/after-refresh-test

And I have a passing test that verifies that the session get's updated in `afterRefresh` here https://github.com/auth0/nextjs-auth0/blob/main/tests/session/get-access-token.test.ts#L235

So I'm not sure what your issue is - if you can provide a working example that demonstrates the issue, I could debug it for you

**Comment by adamjmcgrath** [comment]
Don't worry about the example @muradsofi - I see what it is, will raise a fix shortly - thanks for raising it
