### ISSUE TITLE
Add "Stale" to project

### ISSUE THREAD

**Issue by HurricaneInteractive** [auth0/nextjs-auth0#85]
### Describe the problem you'd like to have solved

At the moment there are currently quite a few issues created that haven't been active for quite a few months. It would be good to auto-close them if they aren't being worked on.

### Describe the ideal solution

Github has a app that can be installed called [Stale](https://github.com/apps/stale) which would help with this.

**Comment by semyou** [comment]
100%

**Comment by Widcket** [comment]
As we've now published the 1.0.0 beta, we've started going through the issues. So I'm going to close this one.
