### ISSUE TITLE
get accessToken inside axios instance without using Nextjs API Routes

### ISSUE THREAD

**Issue by hosseind88** [auth0/nextjs-auth0#852]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hi, I want to have an axios instance inside ```utils/http.ts``` module f.e and use my external backend api (Nestjs) and pass the accessToken in headers, and also I don't want to use Nextjs API Routes because it's not necessary and is just an extra working, I just want to have some initial props that I think I can do it in ```getInitialProps``` and call my axios instance there and pass data in props, or maybe just do it client side when the component gets rendered.
is there any way to do this?

### Describe the ideal solution

like this:

```
// utils/http.ts

export const http = axios.create({
  baseURL: " *** ",
 headers: {
    Authentication: 'Bearer ${accessToken}'
 }
});
```

```
// pages/index.tsx
function Home() {
  const { user } = useAuth0();
  const usersFetcher = useMemo(
    () => (!user?.sub ? null : () => allFacebookUsersApi(user?.sub)),
    [user?.sub]
  );
  const users = useAsyncFetch(usersFetcher);
  
  return (
     ***
  )
}
```

### Alternatives and current workarounds

I can use ```auth0-react``` maybe and get access to accessToken, but as in document https://github.com/auth0/nextjs-auth0#comparison-with-the-auth0-react-sdk , if I use it, I have to use [Static HTML Export](https://nextjs.org/docs/advanced-features/static-html-export) that I don't want to.

**Comment by adamjmcgrath** [comment]
Hi @hosseind88 - thanks for raising this

Have a look at https://github.com/auth0/nextjs-auth0/issues/348#issuecomment-808166458 which should answer your quesiton

**Comment by hosseind88** [comment]
thanks, yeah I configured my Nestjs backend exactly with this https://auth0.com/blog/developing-a-secure-api-with-nestjs-adding-authorization/ document and also my Nextjs frontend app with this document https://auth0.com/blog/ultimate-guide-nextjs-authentication-auth0/ and I added Guard for a Get request

![Screen Shot 2022-10-10 at 23 12 03](https://user-images.githubusercontent.com/72156162/194940947-7e112fd6-8218-499b-a358-9acad70a8353.png)

but it gives ```{
    "statusCode": 401,
    "message": "Unauthorized"
}```

**Comment by adamjmcgrath** [comment]
@hosseind88 - have a look at https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#access-an-external-api-from-an-api-route
