### ISSUE TITLE
Hi, how can i get accesstoken in next for axios call 

### ISSUE THREAD

**Issue by lakshmankashyap** [auth0/nextjs-auth0#873]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

need token or session token

### Describe the ideal solution

need token or session token

**Comment by adamjmcgrath** [comment]
Hi @lakshmankashyap  - thanks for raising this

Have a look at https://github.com/auth0/nextjs-auth0/issues/348#issuecomment-808166458 which should answer your quesiton
