### ISSUE TITLE
Redirects using withMiddlewareAuthRequired

### ISSUE THREAD

**Issue by divmgl** [auth0/nextjs-auth0#874]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Making a redirect with `withMiddlewareAuthRequired`:

```tsx
export default withMiddlewareAuthRequired(async function middleware(
  req: NextRequest
) {
  return NextResponse.redirect("/register")
})
```

strips the status code and always returns a 200. That means that the document body results in `/register`.

This:
```tsx
export default async function middleware(
  req: NextRequest
) {
  return NextResponse.redirect("/register")
}
```

works fine...

### Reproduction

See description.

### SDK version

2.0.0

### Next.js version

12.3.1

### Node.js version

18.8

**Comment by divmgl** [comment]
@adamjmcgrath I'm unable to open a pull request to address this (already found the problem) because your tag, v2.0.0, does not have your middleware file. Additionally, the `package.json` file for that tag still has `1.9.2`.

**Comment by adamjmcgrath** [comment]
Hi @divmgl - thanks for raising this

Looks like the CI tagged the wrong branch - will fix

Please raise any PRs for the Beta against https://github.com/auth0/nextjs-auth0/tree/vNext

**Comment by dexter-atob** [comment]
Fantastic turnaround. Thanks!

**Comment by divmgl** [comment]
Fantastic turnaround, thanks!
