### ISSUE TITLE
NextJS 13 Turbopack Error

### ISSUE THREAD

**Issue by Jared-Dev** [auth0/nextjs-auth0#882]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using NextJS 13's Turbopack compiler I get the following error.
```
error - [resolve] [project-with-next]/node_modules/keyv/src/index.js  Error resolving commonjs request
  unable to resolve module "@keyv/redis" or module "@keyv/mongo" or module "@keyv/sqlite" or module "@keyv/postgres" or module "@keyv/mysql" or module "@keyv/etcd" or module "@keyv/offline" or module "@keyv/tiered" or dynamic
  
  | It was not possible to find the requested file.
  | Parsed request as written in source code: module "@keyv/redis" or module "@keyv/mongo" or module "@keyv/sqlite" or module "@keyv/postgres" or module "@keyv/mysql" or module "@keyv/etcd" or module "@keyv/offline" or module "@keyv/tiered" or dynamic
  | Path where resolving has started: [project-with-next]/node_modules/keyv/src/index.js
  | Type of request: commonjs request
```

The output from `npm explain keyv` indicates that the package in question is a dependency being pulled in from auth0's Next library.
```
keyv@4.5.0
node_modules/keyv
  keyv@"*" from @types/keyv@4.2.0
  node_modules/@types/keyv
    @types/keyv@"*" from @types/cacheable-request@6.0.2
    node_modules/@types/cacheable-request
      @types/cacheable-request@"^6.0.1" from got@11.8.5
      node_modules/got
        got@"^11.8.0" from openid-client@4.9.1
        node_modules/openid-client
          openid-client@"^4.9.1" from @auth0/nextjs-auth0@1.9.2
          node_modules/@auth0/nextjs-auth0
            @auth0/nextjs-auth0@"^1.9.2" from the root project
  keyv@"^4.0.0" from cacheable-request@7.0.2
  node_modules/cacheable-request
    cacheable-request@"^7.0.2" from got@11.8.5
    node_modules/got
      got@"^11.8.0" from openid-client@4.9.1
      node_modules/openid-client
        openid-client@"^4.9.1" from @auth0/nextjs-auth0@1.9.2
        node_modules/@auth0/nextjs-auth0
          @auth0/nextjs-auth0@"^1.9.2" from the root project
```

### Reproduction

Start a Next13 project and configure Auth0's Next libary. Run `next dev --turbo` to enable the turbopack compiler.

### SDK version

^1.9.2

### Next.js version

13.0.0

### Node.js version

lts/*

**Comment by adamjmcgrath** [comment]
Thanks for raising this @Jared-Dev 

Will see if there's something we can do to resolve this, but bear in mind that [Turbopack is still in alpha](https://turbo.build/pack/docs#:~:text=Turbopack%20is%20currently%20in%20alpha.%20It%20is%20not%20yet%20ready%20for%20production%20use.%20We%20appreciate%20your%20support%20and%20feedback%20as%20we%20work%20to%20make%20it%20ready%20for%20everyone.)

**Comment by adamjmcgrath** [comment]
@Jared-Dev - it looks like turbopack doesn't like the dynamic require in `keyv` here https://github.com/jaredwray/keyv/blob/2022-10-17/packages/keyv/src/index.js#L22

Since Turbopack [supports dynamic require's](https://turbo.build/pack/docs/features/imports#:~:text=We%20also%20support%20dynamic%20require()%20syntax%2C%20for%20if%20you%20want%20to%20import%20a%20dynamically%20named%20asset%3A) - this looks like a bug in Turbopack (It looks related to https://github.com/vercel/turbo/issues/2349) 

If I workaround this issue using the advice here https://github.com/jaredwray/keyv/issues/45#issuecomment-1079958339

I run into another issue with turbopack's commonjs support here https://github.com/vercel/turbo/issues/2372

**Comment by Jared-Dev** [comment]
@adamjmcgrath roger, mainly just making sure it is on the radar! 

_I knew this was a chance this was related to Turbopack being in `alpha`, but just in case the package wouldn't work for some reason I reported it. If nothing else it will give other users a point of reference!_

**Comment by adamjmcgrath** [comment]
Have upgraded `openid-client` (which was importing `keyv` via `got`) to the latest which doesn't use `got` anymore.

With the latest beta of `nextjs-auth0` I can confirm that the sample application compiles successfully with `2.0.0-beta.2` running `npm run dev --turbo` on Next 13

**Comment by marcelomedina10** [comment]
I have this issue in my terminal with nextjs 13:

```
Import trace for requested module:
./node_modules/keyv/src/index.js
./node_modules/cacheable-request/src/index.js
./node_modules/got/dist/source/core/index.js
./node_modules/got/dist/source/create.js
./node_modules/got/dist/source/index.js
./node_modules/openid-client/lib/helpers/request.js
./node_modules/openid-client/lib/index.js
./node_modules/@auth0/nextjs-auth0/dist/auth0-session/transient-store.js
./node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
./node_modules/@auth0/nextjs-auth0/dist/index.js
./app/(auth)/chat/page.js
- warn ./node_modules/keyv/src/index.js
Critical dependency: the request of a dependency is an expression
```

And i solved with this:

> Have upgraded `openid-client` (which was importing `keyv` via `got`) to the latest which doesn't use `got` anymore.
> 
> With the latest beta of `nextjs-auth0` I can confirm that the sample application compiles successfully with `2.0.0-beta.2` running `npm run dev --turbo` on Next 13
