### ISSUE TITLE
checks.state argument is missing error when using custom value for AUTH0_COOKIE_PATH

### ISSUE THREAD

**Issue by jagathwee** [auth0/nextjs-auth0#911]
### Checklist

- [x] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello, 

We want to configure a custom value for AUTH0_COOKIE_PATH. Once done, we get the following error:

"checks.state argument is missing"

I saw that this is partially discussed in this issue: https://github.com/auth0/nextjs-auth0/issues/340, but there is no workaround or reason why this is happening. Could you please let me know what I am missing here? 

Thanks,
Jagath

### Reproduction

Configure a custom value for AUTH0_COOKIE_PATH.

### SDK version

1.9.2

### Next.js version

12.2.0

### Node.js version

16

**Comment by adamjmcgrath** [comment]
Hi @jagathwee - thanks for raising this

Could you share a har file (with secret's redacted) or failing that what config values you're using for base url, cookie path and what your login and callback urls are?

**Comment by jagathwee** [comment]
Hi @adamjmcgrath, 

Thanks for the response! 
Attached below is a har file from when we got the error.  Please let me know if you need any other information. 

[localhost.txt](https://github.com/auth0/nextjs-auth0/files/10091771/localhost.txt)

**Comment by adamjmcgrath** [comment]
Thanks for sharing the har file @jagathwee 

You're setting a cookie with `Path=/custompath` - but it needs to be read by `/api/auth/callback`, a cookie with `Path=/custompath` will only be read by path's under `/custompath`

**Comment by adamjmcgrath** [comment]
@jagathwee closing as I believe https://github.com/auth0/nextjs-auth0/issues/911#issuecomment-1328765823 answers your question

**Comment by jagathwee** [comment]
@adamjmcgrath Thanks for the reply. We did not try it yet, and I'll get back to you if we have any questions.
