### ISSUE TITLE
Latest beta tag produces Can't resolve 'v8'

### ISSUE THREAD

**Issue by sharpsteelsoftware1** [auth0/nextjs-auth0#916]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am using the tagged beta so that I can use edge functions on Vercel. When I upgraded to the beta tag the next dev command fails. 

### Reproduction

`"@auth0/nextjs-auth0": "^2.0.0-beta.4"`
`yarn dev`

> $ next dev
> ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> info  - Loaded env from /Users/jmalicke/Projects/muf/dev/repos/muf/bubbles-serverless/.env.local
> error - ./node_modules/openid-client/lib/helpers/deep_clone.js:1:33
> Module not found: Can't resolve 'v8'
> 
> Import trace for requested module:
> ./node_modules/openid-client/lib/issuer.js
> ./node_modules/openid-client/lib/index.js
> ./node_modules/@auth0/nextjs-auth0/dist/auth0-session/transient-store.js
> ./node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
> ./node_modules/@auth0/nextjs-auth0/dist/index.js
> ./pages/_app.tsx
> 
> https://nextjs.org/docs/messages/module-not-found
> warn  - You are using an experimental edge runtime, the API might change.
> wait  - compiling /_error (client and server)...
> error - ./node_modules/openid-client/lib/helpers/deep_clone.js:1:33
> Module not found: Can't resolve 'v8'
> 
> Import trace for requested module:
> ./node_modules/openid-client/lib/issuer.js
> ./node_modules/openid-client/lib/index.js
> ./node_modules/@auth0/nextjs-auth0/dist/auth0-session/transient-store.js
> ./node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
> ./node_modules/@auth0/nextjs-auth0/dist/index.js
> ./pages/_app.tsx
> 
> https://nextjs.org/docs/messages/module-not-found

### SDK version

2.0.0-beta.4

### Next.js version

13.0.4

### Node.js version

18.6.0

**Comment by sraka1** [comment]
@adamjmcgrath even using `getSession` in `getServerSideProps` in _app.tsx produces this issue. Any advice?

**Comment by FowlkeJL** [comment]
> @adamjmcgrath even using `getSession` in `getInitialProps` in _app.tsx produces this issue. Any advice?
> 
> In fact, just importing the module in `getInitialProps` already fails.

Has this been addressed?  How do you only use getSession in the _app.js getInitialProps?
