### ISSUE TITLE
Issue with new release version 2

### ISSUE THREAD

**Issue by gauravverma029** [auth0/nextjs-auth0#946]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Module not found: Can't resolve 'v8'

Import trace for requested module:
./node_modules/@auth0/nextjs-auth0/node_modules/openid-client/lib/issuer.js
./node_modules/@auth0/nextjs-auth0/node_modules/openid-client/lib/index.js
./node_modules/@auth0/nextjs-auth0/dist/auth0-session/transient-store.js
./node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
./node_modules/@auth0/nextjs-auth0/dist/index.js
./pages/_app.jsx

https://nextjs.org/docs/messages/module-not-found
wait  - compiling...
error - ./node_modules/@auth0/nextjs-auth0/node_modules/openid-client/lib/helpers/deep_clone.js:1:33

### Reproduction

Install latest version with next-auth

### SDK version

2

### Next.js version

12

### Node.js version

16

**Comment by Widcket** [comment]
Hi @gauravverma029, thanks for raising this.

Please see https://github.com/auth0/nextjs-auth0/issues/916#issuecomment-1321806947.
