### ISSUE TITLE
Redirect loop with getSession if cookieSameSite is strict

### ISSUE THREAD

**Issue by tylermenezes** [auth0/nextjs-auth0#96]
`getSession()` returns `undefined` until the next "real" page load after logging in when the cookie samesite policy is set to strict, [due to browser security restrictions.](https://bugzilla.mozilla.org/show_bug.cgi?id=1465402) This leads to a redirect loop upon first login if the homepage is expecting the user to be logged in.

This isn't really a "bug" exactly, but it should be added to the README documentation as this behavior is unexpected unless you know a lot about the implementation of samesite.

**Comment by nodabladam** [comment]
When I try to use nextjs-auth0 with Cypress, my first test always fails with a login redirect loop and then the rest of the tests are logged in and work.  I have been unable to figure out why and wonder if this is a hint in the right direction.

**Comment by tylermenezes** [comment]
Luckily once you know what to look for this is relatively easy to test -- you should be able to see the request going through without a cookie header in the web inspector network tab :)

**Comment by adamjmcgrath** [comment]
Hi @tylermenezes - thanks for raising this.

We default the cookie `SameSite` value to `Lax` for this reason, there are lots of cookie (and other) configurations that can break login flow (wrong path, domain, secure setting, samesite setting) - for all defaults we recommend you don't change them unless you know what you're doing :)

**Comment by tylermenezes** [comment]
> for all defaults we recommend you don't change them unless you know what you're doing :)

@adamjmcgrath You actually don't. All you say on the matter is "can be changed to 'strict' or 'none'". "Strict" is not supported by this library and should not be mentioned as an option in the README.

Again this is not an implementation bug, it's a documentation bug.
