### ISSUE TITLE
Cookie issue checks.state

### ISSUE THREAD

**Issue by prahna** [auth0/nextjs-auth0#966]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi,

I want to start by saying that I have gone through all the issues on this GitHub regarding this checks.state problem and have tried all of them before posting. 

The problem happens only when I'm in staging/production environments, aka HTTPS environments on Azure. Domains look like https://abc.azurewebsites.net and https://abc-qa.azurewebsites.net. 

When the problem happens, and I try to force a logout by navigating to /api/auth/logout. If I login again after that, I do not have the issue anymore, so it seems to be only the first time that it happens.

Here is my auth0 config:
```
  import { initAuth0 } from "@auth0/nextjs-auth0";
  
  export default initAuth0({
    baseURL: process.env.AUTH0_BASE_URL,
    issuerBaseURL: process.env.AUTH0_DOMAIN,
    clientID: process.env.AUTH0_CLIENT_ID,
    clientSecret: process.env.AUTH0_CLIENT_SECRET,
    secret: process.env.AUTH0_SECRET,
    authorizationParams: {
      scope: "openid profile email data:all offline_access",
      audience: process.env.AUTH0_API_BASE_URL,
    },
    session: {
      cookie: {
        domain: process.env.AUTH0_COOKIE_DOMAIN,
      },
    },
  });
```

I use a custom post Callback query like this:
```
import auth0 from "../../../helpers/auth0";
import axios from "axios";

function getUrls(req) {
  const redirectUri = `${process.env.AUTH0_BASE_URL}/api/auth/callback`;
  const returnTo = `${process.env.AUTH0_BASE_URL}`;
  return {
    redirectUri,
    returnTo
  };
}

export default auth0.handleAuth({
  async login(req, res) {
    try {
      await auth0.handleLogin(req, res, {
        baseURL: `${process.env.AUTH0_BASE_URL}`,
        returnTo: getUrls(req).returnTo,
        scope: "openid profile email data:all offline_access",
        authorizationParams: {
          scope: "openid profile email data:all offline_access",
          redirect_uri: getUrls(req).redirectUri
        },
      });
    } catch (error) {
      res.status(error.status || 500).end(error.message);
    }
  },
  async callback(req, res) {
    try {
      await auth0.handleCallback(req, res, {
        baseURL: `${process.env.AUTH0_BASE_URL}`,
        redirectUri: getUrls(req).redirectUri,
        returnTo: getUrls(req).returnTo,
        async afterCallback(req, res, session, state) {
          const r = await axios.post(
            `${process.env.NEXT_PUBLIC_API_URL}/api/users/login`,
            session.user,
            {
              headers: {
                Authorization: `Bearer ${session.accessToken}`,
              },
            }
          );
          return {
            ...session,
            user: {
              ...session.user,
            },
          };
        },
      });
    } catch (error) {
      res.status(error.status || 500).end(error.message);
    }
  },
});
```

My environment variables are configured like this:
```
AUTH0_BASE_URL='https://abc-qa.azurewebsites.net'
AUTH0_COOKIE_DOMAIN='abc-qa.azurewebsites.net'
AUTH0_DOMAIN='https://abc.us.auth0.com'
AUTH0_API_BASE_URL='https://abcapi.azurewebsites.net'
AUTH0_CLIENT_ID='xxx'
AUTH0_CLIENT_SECRET='xxx'
AUTH0_SECRET='xxx'
```

Similar for production environment.

I really need help with this please, I have tried everything and it's the last critical issue before I can go in Beta version.

Thank you very much for any help or cues on what I'm doing wrong.

### Reproduction

1. Use configuration like copied above in description
2. Navigate to website
3. Go to login
4. Notice "checks.state" error 
5. Navigtate to "/api/auth/logout" to logout
6. Login again the same way as before
7. Notice that it works perfectly the 2nd time around and subsequent times

### SDK version

1.9.2

### Next.js version

10.0.5

### Node.js version

16

**Comment by prahna** [comment]
Hey Adam,
Thank you for the quick answer, it's really appreciated.

I have a question for the Cookie domain. I can see how now I don't need it. But the moment I go live, there will be a redirection. Let's say https://www.abc.com will actually be https://abc.azurewebsites.net. Which domain should be the right domain? Will I need to specify the domain then, or if I leave it unset it will work well?

As for your lead looking at the login URL, as I was preparing the HAR file I noticed it! My button will navigate to "http" but the callback will go to "https" causing the checks.state issue. I can't believe I didn't see this before! Stepping line by line in the network view in Chrome was necessary to see it.

Thank you so much for your help. My issue seems to be fixed so far! I will comment here if I see it creeping up again.
If I can have a clarification for that first Cookie domain question, this issue can be closed safely.

Cheers!

**Comment by adamjmcgrath** [comment]
> Which domain should be the right domain? Will I need to specify the domain then, or if I leave it unset it will work well?

You do not need to set the cookie domain since users will get a cookie for whatever hostname is in their address bar. You only need to set the cookie domain when you want a cookie for multiple subdomains (eg set the cookie domain to `.abc.com` so that `foo.abc.com` and `bar.abc.com` can read the cookie)

> My button will navigate to "http" but the callback will go to "https" causing the checks.state issue. Just had to ensure the href goes to https and voila! I can't believe I didn't see this before! Stepping line by line in the network view in Chrome was necessary to see it.

Yeah, it's a tricky one to debug - we've improved the error around this in v2 which should make it easier.

I think this answers your question so closing
