### ISSUE TITLE
Module not found: Can't resolve 'v8' when using custom initAuth0

### ISSUE THREAD

**Issue by azzlack** [auth0/nextjs-auth0#967]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using monorepos (with turbo and pnpm) and using an `initAuth0` instance in a workspace project, we get a `Module not found: Can't resolve 'v8'` when using custom initAuth0 on all pages that try to call a nextjs api endpoint that uses getSession.

To explain the flow we are trying to achieve in our app:  
1. Client navigates to the app, and logs in using Auth0 credentials
2. Cookie is set, and the custom profile handler adds some props to the userprofile object
3. Client makes a call to a nextjs api endpoint, using the cookie as authentication
4. The nextjs api endpoint calls another api, converting the cookie to an Authorization header before sending the request

### Reproduction

See repo at https://github.com/azzlack/auth0-nextjs-initauth0-bug

> NOTE: You need to populate the empty variables in the `.env` file

Run `pnpm dev` in the `main` branch to see a **working** version.
Run `pnpm dev` in the `monorepo` branch to see a **failing** version.

### SDK version

2.0.1

### Next.js version

13.0.6

### Node.js version

18

**Comment by Widcket** [comment]
Hi @azzlack, thanks for raising this.

Please see https://github.com/auth0/nextjs-auth0/issues/916#issuecomment-1321806947.

**Comment by azzlack** [comment]
I saw that one earlier, and looked at the migration docs, but it couldnt see if it applied to `initAuth0` flows.
If I try to use the `/client` parts I get an error saying they should not be mixed.

From my initial debugging, it seems to be related to monorepos and/or pnpm.
It could of course be related to the client/server components, but why does it work when not using a monorepo?

**Comment by Widcket** [comment]
> When using monorepos (with turbo and pnpm)

By turbo you mean Turbopack? Note that [it's in alpha](https://nextjs.org/docs/advanced-features/turbopack).

**Comment by azzlack** [comment]
Sorry, Turbo as in Turborepo.

**Comment by Widcket** [comment]
I tried the `monorepo` branch with another package manager (yarn) and it did not error:

<img width="881" alt="Screen Shot 2022-12-13 at 14 19 20" src="https://user-images.githubusercontent.com/5055789/207400852-cde5ddb8-735e-438a-8497-5039b29444cf.png">
<img width="798" alt="Screen Shot 2022-12-13 at 14 19 46" src="https://user-images.githubusercontent.com/5055789/207400868-b7b3f2a7-47d5-4f91-b065-043243c38cd0.png">

**Comment by Widcket** [comment]
I see the above is picking up the wrong `lib` package. But, using pnpm, if I remove the SDK as a peer dependency from the `lib` package it also succeeds:

<img width="1357" alt="Screen Shot 2022-12-13 at 14 31 08" src="https://user-images.githubusercontent.com/5055789/207403879-aacb8ec8-447e-4d20-9421-f845d214f942.png">
<img width="1009" alt="Screen Shot 2022-12-13 at 14 30 29" src="https://user-images.githubusercontent.com/5055789/207403873-42a4066d-54ee-4139-b5fb-81cc8861897f.png">

**Comment by Widcket** [comment]
Note that the SDK is set as a dependency as well as a peer dependency in https://github.com/azzlack/auth0-nextjs-initauth0-bug/blob/monorepo/packages/lib/package.json

**Comment by azzlack** [comment]
Thanks for looking into this, I will test again tomorrow and see if I get the same result as you.

**Comment by azzlack** [comment]
I saw that you were testing with node 19.2.0, i also tried upgrading to that - but it yielded the same error

**Comment by azzlack** [comment]
Thank you so much! Splitting up the files into several packages worked wonderfully. 🤩 

Just out of curiosity, when you split this library into a client and server components, did you have to do anything special for it to work ? Or was it just adding the following section in `package.json` ?

```
"exports": {
    ".": "./dist/index.js",
    "./client": "./dist/client/index.js",
    "./edge": "./dist/edge.js",
    "./testing": "./dist/helpers/testing.js"
  },
```

**Comment by adamjmcgrath** [comment]
no problem @azzlack 

> when you split nextjs-auth0 into a client and server components, did you have to do anything special for it to work ? Or was it just adding the following section in package.json ?

We also had to create the equivalent files (eg https://github.com/auth0/nextjs-auth0/blob/main/edge.js) for build tools (like eslint) that don't support package exports

**Comment by azzlack** [comment]
Nice, thank you. I did the same now and it works pretty well 😄 

This case could probably be closed, but maybe there should be a note somewhere in the documentation regarding Turborepo? I can make a PR for it if you tell me where/if you would like it.

**Comment by adamjmcgrath** [comment]
No worries @azzlack 

Thanks for offering to add some docs about Turborepo, if it's ok with you I'm going to hold off on documenting this until I know a little more about it. I suspect that it's an issue in Turborepo, or turbopack - if I can create a minimal case I might go and raise an issue over there.
