### ISSUE TITLE
Callback and preview deployments

### ISSUE THREAD

**Issue by GriffinSauce** [auth0/nextjs-auth0#97]
### Description

When using preview deployments with Zeit Now the domain for the deployment is not know to the application at build or startup. There are no environment variables that provide this information but it is possible to get the host from a particular request.

This means that the appropriate callback URL (`redirectUri`) is not known at the point that this library expects it to be configured (settings).

### Reproduction

- Create a next app
- Implement the library
- Deploy a branch to Zeit Now
- Login will redirect you to the callback on whatever your main domain for the app is (if you manually edit the url go to your preview deployment everything is fine)

### Potential solutions

1. Since we're passing `req` into handle login perhaps the library could handle finding the host and `redirectUri` could be just the path (ie. `/api/callback`). I'm not sure about the implications of other hosts than Now though with this choice.

2. Alternatively `redirectUri` could be added to LoginOptions so it can be overwritten in the login route where we have the `req` for context.

3. The `redirectUri` setting could be changed to support a function with `req` as input.

**Comment by GriffinSauce** [comment]
Another alternative by the way is to instantiate this at every call of the API so the settings can be customised per call but that is not how the docs currently describe the usage and I'd be afraid of unforeseen issues.

**Comment by GriffinSauce** [comment]
Well, they beat me to it, `NOW_URL` has returned:
https://zeit.co/blog/environment-variables-ui

**Comment by cyrus-za** [comment]
NOW_URL (or VERCEL_URL) does not solve it as they tend to create multiple url's e.g. github branch name or now.sh vs vercel.app and they display different url's at different places. It would be great if auth0 could just read req.headers.host and use that or alternatively let us pass a function in with req as input.

**Comment by GriffinSauce** [comment]
Host header can be manipulated from the client though so this opens up a potential vulnerability. Especially since this is a nextjs library and not necessarily hosted on Vercel (where I believe that header is safeguarded)
