### ISSUE TITLE
implement or advise on how to implement a setSession method

### ISSUE THREAD

**Issue by rbmdotdev** [auth0/nextjs-auth0#972]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I need to be able to manually set the access_token, id_token, scope, expires_in and token_type after my server has completed a resource owner password grant flow for a particular user.  this is also described and implemented for the v1 of this library here https://github.com/auth0/nextjs-auth0/pull/198 but it looks like it died on the vine unfortunately.

some of users will use the universal login however some of users will choose this alternate method of logging into our app.  They will also likely not every change from this method that uses the resource owner password grant flow.

The backend currently works great with auth0 but I am having trouble figuring out how I am supposed to set the session with this library so that it realizes this user has indeed successfully logged in and uses the new tokens from then on.

### Describe the ideal solution

a setSession handler or hook that can be called after nextjs receives the credentials from our non nextjs backend server

### Alternatives and current workarounds

I dont see an obvious workaround but would be happy to be shown one

**Comment by adamjmcgrath** [comment]
Hi @rbmdotdev - thanks for raising this

This SDK only supports logging in via the Universal Login and we have no plans to support embedded login I'm afraid.

Because Universal Login is more secure than embedded, none of our new regular web application SDKs support it.

**Comment by rbmdotdev** [comment]
My use case is not an embedded one.  I don't need embedded login support I just need a way to manually set the session myself on the backend.

auth0 espouses to support oidc and oauth specs, the resource owner password flow is a standard part of the oauth2 spec.  deliberately not supporting customers who need to use this flow is silly.
