### ISSUE TITLE
Support cross-device authentication (relevant for passwordless/email login)

### ISSUE THREAD

**Issue by sraka1** [auth0/nextjs-auth0#974]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The current implementation requires a login session to be completed end-to-end on the same tab/device.

See https://github.com/auth0/express-openid-connect/issues/145#issuecomment-707024770, https://github.com/auth0/express-openid-connect/issues/145#issuecomment-707024770 and https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md.

While these issues all explain why this happens technically (and that's fine), **none of them explain why this design decision was chosen and if there are plans to revert it?** Requiring the user to stay on the same device/tab while performing the login has a very marginal, practically negligible effect on increased security. With magic links, the implied security stems from the assumption that access to the users' email is secure. If that security is broken, it does not matter if the login is completed off-device in a split flow or in the same tab as part of the same complete flow. I understand that making these changes would require some core changes on how `openid-client` is used, but right now you are forcing customers into really obtuse workarounds because they need passwordless login to work across devices. And just to clarify again, clicking the link should log the user in on the device where it was clicked, not on the original session (to prevent phishing or people clicking unknown links, which should be a big no-no, but you never know).

Potential workaround for anyone that stumbles upon this:
Add a handler in the callback for the `checks.state` issue and redirect to login page.
Pass some extra parameter to the login page like `retry=true`
Override getLoginState on login
```
getLoginState: (loginReq: IncomingMessage, options: LoginOptions) => ({
      returnTo: options.returnTo || req.originalUrl,
      retry: !!loginReq.query?.retry,
    }),
```
On the callback handler make sure to only redirect once by checking the incoming request URL and parsing out the state again and preventing another redirect if retry=true. This will prevent an infinite loop in case smth is wrong on the Auth0 side (i.e. the state param not being passed or anything else weird like that).

### Reproduction

1. Use passwordless login
2. Click the email in another device
3. You will not be logged in

### SDK version

Both ~1 and ~2

### Next.js version

~12

### Node.js version

~16

**Comment by adamjmcgrath** [comment]
Hi @sraka1 - thanks for raising this

> Requiring the user to stay on the same device/tab while performing the login has a ...

We don't require users to stay on the same tab, only the same user agent

You are restricted to the same user agent by the protocol (this is an OpenID Connect client), it's not a design decision we've come up with. More info here https://www.rfc-editor.org/rfc/rfc6749#section-10.12

**Comment by sraka1** [comment]
Sorry, I meant in the same browser environment (or to be more specific, the place where the `state` cookie stays the same). Also, thanks for the quick reply.

I did indeed think it's a limitation of OAuth and/or OpenID, but didn't actually check the RFC spec. I guess apps/tools such as Slack or OpenCollective simply rolled something outside the OAuth/OpenID spec? If so, that is unfortunate. Basically you are saying there is no way to accomplish this without breaking the spec fundamentally (which would require a major rewrite of this library)?

While I understand the CSRF implication, it seems (as already written above), low-risk. The whole passwordless flow depends on the security of the email account. And as part of that security, the email provider blocking potential phishing emails and so on. Our reasoning was that if it is good enough for Slack (over which confidential company msgs are exchanged), it should be good enough for us.

**Comment by adamjmcgrath** [comment]
Thanks for sharing your views on the security aspects of passwordless @sraka1 

Regardless of the specification and wether you deem it high risk or low risk, login CSRF a vulnerability, and not one I would introduce to this library as I don't see this as a valid enough use case. TBH, this is the first time someone has ever requested a user be able to initiate login on one device so they can complete it on a different device.

Even though Slack might support this, I notice, when initiated from my mobile, their magic link email says in bold "**From your mobile device**, tap the button to confirm", suggesting that they still expect you to complete login on the same device you initiated it.

> Basically you are saying there is no way to accomplish this without breaking the spec fundamentally (which would require a major rewrite of this library)?

It would be fairly trivial to accomplish this, simply remove the CSRF checks from the callback handler, you're welcome to fork this SDK and do it yourself, but I would question wether this use case you're after would really be worth it.

**Comment by adamjmcgrath** [comment]
Closing as I think https://github.com/auth0/nextjs-auth0/issues/974#issuecomment-1362692377 answers your question. Feel free to ping me if you want to reopen
