### ISSUE TITLE
withMiddlewareAuthRequired ignorePaths should not contain '/_next'

### ISSUE THREAD

**Issue by tisonkun** [auth0/nextjs-auth0#977]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

```ts
      const ignorePaths = [login, callback, unauthorized, '/_next', '/favicon.ico'];
      if (ignorePaths.some((p) => pathname.startsWith(p))) {
        return;
      }
```

Currently, request to `/_next` always bypass the auth process. This can leak content when the hack figure out the path of the generated js file.

### Reproduction

https://everlasting-lgzkwcx3s-korandoru.vercel.app/_next/static/chunks/pages/index-045929068d457202.js

This page uses the basic middleware config:

```ts
import {withMiddlewareAuthRequired} from "@auth0/nextjs-auth0/edge";

export default withMiddlewareAuthRequired();
```

You can find the page content leaks by searching "Get started by editing" which is part of the content.

### SDK version

2.0.1

### Next.js version

13.1.0

### Node.js version

18

**Comment by tisonkun** [comment]
It seems I may implement this with "For using middleware with your own instance of the SDK" example. I'll give it a try.

**Comment by adamjmcgrath** [comment]
Hi @tisonkun - thanks for raising this.

This is by design, this middleware is not designed to protect static files like css and images. You tend to run into issues like https://github.com/nextauthjs/next-auth/issues/4848 if you start doing that

**Comment by tisonkun** [comment]
@adamjmcgrath Thanks for your reply. But the static folder holds js files also, which contain the protected content. If you don't protect them, then a random person can get the content anyway.

**Comment by tisonkun** [comment]
@adamjmcgrath Interesting. I notice that directly access a js file doesn't go into the "every route in your project" condition and vercel middleware actually isn't called.

**Comment by tisonkun** [comment]
I use `yarn patch` to workaround this issue and see if it can meet my requirement. Of course it locks my dep version to this SDK so I'll try to make a patch on the upstream when I really get this stuff work.

**Comment by adamjmcgrath** [comment]
@tisonkun 

> But the static folder holds js files also,

You should not store secrets in your frontend javascript files. These are cached in public caches.

You are using a server side SDK for authentication, why would you not store your secrets on the server side?

**Comment by tisonkun** [comment]
@adamjmcgrath It's not a secret, but actually page content. Said you want to protect you home page, but the page content leaks from the js file. This is how `next build` works.

Anyway, I finally built a two-phase solution to publish static files under a different path, so whether or not ignore `_next` is not important anymore. Refer to https://github.com/facebook/docusaurus/discussions/8477#discussioncomment-4489869.

**Comment by adamjmcgrath** [comment]
@tisonkun - If you need to protect the content from being leaked, then I would describe it as secret

Closing #979 as it looks like you've found an alternative

**Comment by tisonkun** [comment]
@adamjmcgrath make sense.

`next build` generate js files contain your page content and located at `_next/static`. So if you'd like to prevent crawlers finding your content, those files should be protected. This logic comes from Next.js so I have no way to change it.

Perhaps I store all the content in a database and fetch with server-side rendering, but that solution is far more complicated (even requiring a storage instance!).

**Comment by tisonkun** [comment]
@adamjmcgrath 

Still, the maintainers can think of this case. When the document tells users that all the routes are protected (with default config), actually a crawler can download their page content without authenticating and authorizing.

**Comment by tisonkun** [comment]
The design decision here is that `withMiddlewareAuthRequired` export one hook after the bypass logic runs and authentication is done.

Given that Edge MiddleWare supports [Match paths based on conditional statements](https://vercel.com/docs/concepts/functions/edge-middleware#match-paths-based-on-conditional-statements), I'd suggest we provide a new hook just in the bypass logic and default to current manner.

```tsx
      const resolveShouldBypassReq = shouldBypassReq ? shouldBypassReq : (req: NextRequest) => {
        const { pathname } = req.nextUrl;
        const ignorePaths = [login, callback, unauthorized, '/_next', '/favicon.ico'];
        return ignorePaths.some((p) => pathname.startsWith(p));
      }

      if (resolveShouldBypassReq(req)) {
        return
      }
```

I'm glad to provide a patch with tests if it's the correct/acceptable way.

**Comment by tisonkun** [comment]
FYI https://github.com/tisonkun/nextjs-auth0/commit/1eae839daec9ab3db3de4a9b0c4a7146c9018926 with tests. Code styles can be updated if the project requires.

**Comment by ajwootto** [comment]
@adamjmcgrath IMO @tisonkun is right to have raised this. The contents of `_next` files are not necessarily "static" since anybody using dynamic serverside rendering will be sending back files on this path that contain data that should only be shown to a logged-in user.

For example, in a standard SaaS dashboard where a logged in user might be receiving a bunch of data specific to their account, much of that data will be in the `_next` javascript files since that is what is used to hydrate the page after serverside rendering.
