### ISSUE TITLE
Module not found: Can't resolve 'v8'

### ISSUE THREAD

**Issue by Will956** [auth0/nextjs-auth0#983]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello 👋 

First of all, you may have already seen that issue's title and I'm sorry if it sounds like a duplicate to you but I'm not sure if I understand correctly other issues or if it's another case here.

I've made a minimal reproduction here https://github.com/Will956/nextjs-auth0-v8-issue. This is a simple NextJS app with one page.

That page is server-rendered and uses two fetchers _(that are defined in the same utils file)_ to get data: one from the server, and one from the client.

```js
// utils/fetch.ts
import { getAccessToken } from "@auth0/nextjs-auth0";

const baseUrl = "http://localhost:3000";

export const fetcherClient = async (url: string) => {
  const res = await fetch(`${baseUrl}${url}`);
  return res.json();
};

export const fetcherServer = async (ctx: any, url: string) => {
  const accessToken = await getAccessToken(ctx.req, ctx.res);
  const res = await fetch(`${baseUrl}${url}`, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });
  return res.json();
};
```

and used as follows:
```js
(...)
import { fetcherClient, fetcherServer } from "./utils/fetch";
(...)

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const data = await fetcherServer(ctx, "/api/hello");
  console.log("data", data);

  return {
    props: {
      // Will be passed to the page component as props
    },
  };
};

export default function Home() {
  useEffect(() => {
    const fetchData = async () => {
      const data = await fetcherClient("/api/hello");
      console.log("data", data);
    };
    fetchData();
  }, []);

  return (
    <>
      (...)
    </>
  );
}

```

And that page can't be rendered since it triggers the error `Module not found: Can't resolve 'v8'` _(the `getAccessToken` defined in `fetcherServer` makes the page fail)_

I already had a look at other issues and it looks related to me but not corresponding to my case here:
- https://github.com/auth0/nextjs-auth0/issues/916#issuecomment-1321806947, I'm not importing something from the client within the server _(at the SDK level I mean)_
- https://github.com/auth0/nextjs-auth0/issues/967#issuecomment-1350921211, I do not use Turborepo/Turbopack here

I understand that you've made recent changes that separate client from server codes, but, does that mean I have to do the same in my codebase to make it work with the SDK _(it works if I separate `fetcherClient` and `fetcherServer` in a different file)_?

Thanks _(and sorry again if it was already clear from other issues)_ ❤️ 

### Reproduction

1. Clone https://github.com/Will956/nextjs-auth0-v8-issue
2. Fill a `.env.local` with your Auth0 values
3. Run `npm run install`
4. Run `npm run dev`
5. You should see the error

### SDK version

2.0.1

### Next.js version

13.1.1

### Node.js version

16.18.1

**Comment by adamjmcgrath** [comment]
Hi @Will956 - thanks for raising this.

> I understand that you've made recent changes that separate client from server codes, but, does that mean I have to do the same in my codebase to make it work with the SDK (it works if I separate fetcherClient and fetcherServer in a different file)?

Yes, this is a requirement of Next.js not this SDK

You're importing a server side component into client side code when you import `fetcherClient` into your frontend component. Because `fetcherClient` depends on `@auth0/nextjs-auth0` which depends on `openid-client` which depends on `v8` (a native Node library) - and webpack isn't smart enough to know that you're only using `@auth0/nextjs-auth0` in `fetcherServer` which is used in `getServerSideProps`

It is smart enough to know what import is being used in `getServerSideProps` if the imports are separated in the page file itself. See [data-fetching/get-server-side-props](https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#:~:text=You%20can%20import%20modules%20in%20top%2Dlevel%20scope%20for%20use%20in%20getServerSideProps.%20Imports%20used%20will%20not%20be%20bundled%20for%20the%20client%2Dside.%20This%20means%20you%20can%20write%20server%2Dside%20code%20directly%20in%20getServerSideProps%2C%20including%20fetching%20data%20from%20your%20database.)

**Comment by Will956** [comment]
Got it, thanks for your answer. We got a workaround to prevent separating all of our files by extending the webpack configuration to create this new environment variable:
```js
// ./next.config.js
config.plugins.push(
  new webpack.DefinePlugin({
    'process.env.RUNTIME_ENV': JSON.stringify(
      isServer ? 'server' : 'browser'
    ),
  })
);
```
and then within our fetch abstraction file (that has our `fetchServer` and `fetchClient` function):
```js
// ./utils/fetch.ts
export const fetchServer = async (context) => {
  (...)
  let accessToken = null;
  if (process.env.RUNTIME_ENV === 'server') {
    try {
      const auth = await import('@auth0/nextjs-auth0');
      accessToken = await auth.getAccessToken(context.req, context.res);
    } catch (e) {
      console.error('Error while getting access token', e);
    }
  }
  (...)
}

export const fetchClient = async () => { (...) }
```

Not sure if it has some side effects, but it works 👌

**Comment by tachang** [comment]
> importing a server side component into client side code

My understanding is that NextJS allows you to do this? Or is it jus NextJS 12?

**Comment by ubuntupunk** [comment]
bump
