### ISSUE TITLE
Can't find withMiddlewareAuthRequired

### ISSUE THREAD

**Issue by xjustleoo** [auth0/nextjs-auth0#988]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

`
import { withMiddlewareAuthRequired } from '@auth0/nextjs-auth0/middleware';

export default withMiddlewareAuthRequired();

export const config = {
  matcher: '/user/:path*',
}`

I'm trying import the "withMiddlewareAuthRequired" function but get "Cannot find module '@auth0/nextjs-auth0/middleware' or its corresponding type declarations."

### Reproduction

1. Install newest version of auth0 next js
2. Create middleware.ts
3. Paste
`import { withMiddlewareAuthRequired } from '@auth0/nextjs-auth0/middleware';

export default withMiddlewareAuthRequired();`

### SDK version

2.0.1

### Next.js version

13.0.0

### Node.js version

16

**Comment by adamjmcgrath** [comment]
Hi @xjustleoo - thanks for raising this,

You need to import it from `@auth0/nextjs-auth0/edge` (see https://github.com/auth0/nextjs-auth0#edge-for-middleware-and-the-edge-runtime)

Let me know if there's some out of date documentation somewhere

**Comment by adamjmcgrath** [comment]
Closing as I believe https://github.com/auth0/nextjs-auth0/issues/988#issuecomment-1373439396 answers your question
