### ISSUE TITLE
Documentation could be clearer for JS

### ISSUE THREAD

**Issue by acecauis** [auth0/nextjs-auth0#99]
Hi,

I went through your documentation and was led to making a post on the Community forums of Auth0; however, it was suggested I report an issue here. So below is a short explanation to reproduce my situation and a more detailed description of my main concern. 

### To summarize steps to reproduce my issue:
I went through the documentation and went ahead to copy the files contained in the `/basic-example` directory, along with the respective code for each file as shown in the following image:

![image](https://user-images.githubusercontent.com/37757724/79528666-3b4e6380-8030-11ea-9817-d04bdeb709f3.png)

However, I did make an attempt to convert the files from TypeScript to JS files -- as some files are written in TypeScript (e.g. files in `/basic-example/pages` and `/basic-example/components` directories).

### My current situation:
I am building a site with Nextjs (and currently not using TypeScript). I have a Login button that I want to redirect to the Auth0 login page, like the example page on the documentation for the nextjs-auth0 library.

I don’t really understand the setup for this example, but (and correct me if I’m wrong) it appears as if the example is more complex than the documentation describes. For example, each of the three examples (/api-call-example, /basic-example, and /sample-api) in the /examples directory appear to be required for the entire [page] (https://nextjs-auth0-api-example.now.sh/) to work.

To clarify what I want to achieve: I want my Login button on my Header to redirect to the Auth0 login page (just like the nextjs-auth0 example page), have the user be able to log in and see a Profile button (that displays some data of the user — also as in the example page) and Logout button.

Right now, I am just trying to get the /basic-example to work and have the following JS files, like in the directory (ignore auth0_myEdits.js):

![image](https://user-images.githubusercontent.com/37757724/79528666-3b4e6380-8030-11ea-9817-d04bdeb709f3.png)

Upon running npm run dev, I get an infinite loop of the page trying to load and wind up with a .json error report file. Not sure what I am doing wrong but I believe it may have something to do with my auth0.js or config.js file (perhaps entering my actual clientId, clientSecret, domain, etc.? but I am unsure how this is conveyed in the code provided in the example directory??)

Any help would be greatly appreciated!

I will try reformatting the /basic-example to using TypeScript, removing the config.js file, and solely using the auth0.js file with my appropriate app info and seeing if that works. If that doesn’t work, should I get in touch with support?

Thanks again!

**Comment by sandrinodimattia** [comment]
Could you provide a repository of your sample setup? Have you created a `.env` file in the directory? I added more documentation in the readme: https://github.com/auth0/nextjs-auth0/tree/master/examples/basic-example

The basic example covers your need and you don't need the other examples.

**Comment by sandrinodimattia** [comment]
And please share a screenshot of the ".json error report file"

**Comment by acecauis** [comment]
Actually fixed my issue. The issue was that I didn't include a `.env` file in the directory.

**Comment by sandrinodimattia** [comment]
Ok, thanks for the update 👍
