### ISSUE TITLE
Middleware fails to login properly when appSession is split into parts

### ISSUE THREAD

**Issue by JB-Scott** [auth0/nextjs-auth0#996]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

User is not logged in properly when using withMiddlewareAuthRequired() if the appSession is too large to fit in one cookie and is split into 2 or more cookies (e.g. 'appSession.0' and 'appSession.1'). In this case, the login dialog appears and accepts the user login details and then forwards to the appropriate page. However, useUser() will not return any details and logout does not work. If the appSession is just one cookie ('appSession') everything works correctly.

### Reproduction

1. Create a user with enough extra metadata that will be stored in the appSession cookie to make the appSession cookie split into two cookies ('appSession.0' and 'appSession.1')
2. Follow instructions to protect all pages via middleware: https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#protecting-pages-with-middleware
3. Login and then try to access useUser() or logout - they will both fail (confirm that there are two appSession cookies: 'appSession.0' and 'appSession.1'. If there is just one appSession cookie, they will be successful.

### SDK version

2.0.1

### Next.js version

13.1.1

### Node.js version

16.16.0

**Comment by adamjmcgrath** [comment]
Thanks for reporting this @JB-Scott - I will investigate

**Comment by adamjmcgrath** [comment]
Hi @JB-Scott - thanks for raising this

I'm not able to reproduce what you're seeing using the same versions of this SDK/Next and Node on our example app (see my test branch here https://github.com/auth0/nextjs-auth0/compare/mw-chunking-test)

Is this happening for you on a specific hosting provider? Also, could you provide a HAR file (with secrets redacted)?
