### ISSUE TITLE
Using `getSession()` within a Vercel `edge` function API route returns an error

### ISSUE THREAD

**Issue by phillipleblanc** [auth0/nextjs-auth0#997]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I want to deploy an API protected by Auth0 using this library to the new [Vercel Edge functions](https://vercel.com/docs/concepts/functions/edge-functions).

Edge Functions use Vercel's [Edge Runtime](https://edge-runtime.vercel.sh/packages/runtime), which is built on the same high-performance [V8 JavaScript and WebAssembly engine](https://developers.google.com/apps-script/guides/v8-runtime) used by the Chrome browser.

Edge Functions are NOT Node.js, and several APIs are not available.

When attempting to use the edge runtime, I get the following error:

```
error - node_modules/oidc-token-hash/lib/shake256.js (3:0) @ <unknown>
error - Cannot read properties of undefined (reading 'substr')
```

One of the missing APIs is on the variable `process.version`. That returns undefined in the Vercel Edge Function runtime. This variable is required by the [`oidc-token-hash`](https://github.com/panva/oidc-token-hash/blob/main/lib/shake256.js#L3) library, which this library indirectly depends on (through `oidc-provider`).

I'm assuming that a call to `getSession` will eventually call the problematic code in `oidc-token-hash`, which prevents this from working.

### Reproduction

1. Create a Vercel project with an API route protected by `withApiAuthRequired`
2. Call `getSession` within that API route
3. Configure the API route to run on the Vercel edge runtime

```
export const config = {
  runtime: 'edge',
};
```

4. Try calling the API

### SDK version

2.0.1

### Next.js version

13.1.1

### Node.js version

N/A

**Comment by adamjmcgrath** [comment]
Hi @phillipleblanc - thanks for raising this

You need to use `getSession` from `@auth0/nextjs-auth0/edge` in order to use `getSession` on the Edge runtime, see https://github.com/auth0/nextjs-auth0#edge-for-middleware-and-the-edge-runtime

**Comment by TheodorRene** [comment]
Is there any way to catch this? I had a similar issue where using `getSession` within a page:

diff --git a/ts-frontend/pages/_app.tsx b/ts-frontend/pages/_app.tsx
index 971f9c26b..0ace4a6c3 100644
--- a/ts-frontend/pages/_app.tsx
+++ b/ts-frontend/pages/_app.tsx
@@ -3,8 +3,12 @@ import { UserProvider } from '@auth0/nextjs-auth0/client';
```ts
 import type { AppProps } from 'next/app';
 import '../styles/globals.css';
 import Script from 'next/script';
+import { getSession } from '@auth0/nextjs-auth0';
 import { clientSideClient } from 'utils/clientSideApolloClient';
 
+const functionthatDoesNothing = () => {
+  getSession(undefined as any, undefined as any);
+};
 function MyApp({ Component, pageProps }: AppProps) {
   return (
     <UserProvider>
```
Using this code with an unused function we get `util.types` is undefined:
``
Uncaught TypeError: util.types is undefined
    <anonymous> is_key_object.js:4
    NextJS 4
    <anonymous> client.js:13
    NextJS 4
    <anonymous> issuer.js:6
    NextJS 4
    <anonymous> index.js:1
    NextJS 4
    <anonymous> transient-store.js:4
    NextJS 4
    <anonymous> index.js:21
    NextJS 4
    <anonymous> index.js:6
    NextJS 4
    <anonymous> _app.tsx:10
    NextJS 4
    <anonymous> (index):5
    onEntrypoint route-loader.js:211
_app.js:4:1
```
It seems to me that serverside libraries are called client side. Commenting out the unusued function removes the error. I would think more people will burn themselves on this.
